### ISSUE TITLE
Refresh DownSampleToViewSize

### ISSUE THREAD

**Issue by gianisimone** [luberda-molinet/FFImageLoading#1000]
### Description

I would like to force the CachedImage to refresh DownsampleToViewSize after some layouts modification of its parent.

How can this be achieved?

Thank you for your great work.

**Comment by daniel-luberda** [comment]
Just call `cachedImage.ReloadImage` - that's all. Thanks.

**Comment by gianisimone** [comment]
Thank you for your support!
