### ISSUE TITLE
How to Zoom in

### ISSUE THREAD

**Issue by CDrosos** [luberda-molinet/FFImageLoading#1001]
### Description

Im wandering if i can somehow zoom in an image and then change the image of the imageview. Can somehow archive this effect?

**Comment by daniel-luberda** [comment]
You can view the source of this: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/ImageCropView

 (it uses FFImageLoading internally)

**Comment by CDrosos** [comment]
i dont think this app does what i want. I want the zoom in to have a duration, not happen instantly

**Comment by daniel-luberda** [comment]
You can use `CropTransformation` combined with eg RxExtensions or use platform / frameworks specific animation APIs.
