### ISSUE TITLE
Error place holders not used for empty/null URLs

### ISSUE THREAD

**Issue by dlpopescumtk** [luberda-molinet/FFImageLoading#1002]
### Description

The Error place holder doesn't seem to be used if the source URL for the image is empty

### Steps to Reproduce

Load a RecyclerView with a list of items with a ImageUrl property

### Expected Behavior

If the URL is null/empty, load the Error placeholder

### Actual Behavior

The image is completely blank

### Basic Information

A temporary workaround is to set the image url to some dummy value, if the original value is null or empty, which will trigger the use of Error place holder.

###  Screenshot
https://1drv.ms/u/s!Au6mN6iwQdOzifsED6h3fFihoVLjsQ

- Version with issue: 2.3.4
- Platform: Android 8.0

**Comment by daniel-luberda** [comment]
Hi @dlpopescumtk

Why would you want to load error placeholders for null values? It's a correct behaviour, there're a lot of cases when you want to set an image to an empty one.

**Comment by dlpopescumtk** [comment]
@daniel-luberda : you're right, I might've been unclear.

I have this in my item layout file

	_<ffimageloading.cross.MvxCachedImageView
			android:id="@+id/iv_picture"
			android:clickable="false"
			android:src="@drawable/global_profile_image"
			android:layout_width="120dp"
			android:layout_height="120dp"
			app:MvxBind="LoadingPlaceholderImagePath 'res:global_profile_image.png'; ErrorPlaceholderImagePath 'res:global_profile_image.png'; Transformations Transformations; ImagePath ImageUrl"/>_	

So my actual question is how do I set the placeholder for an empty/null url? I'm using the same image for errors and null values, hence the confusion of the initial question.

Cheers,
Lucian

**Comment by nick-potts** [comment]
This may help
https://github.com/luberda-molinet/FFImageLoading/wiki/API#loading

**Comment by daniel-luberda** [comment]
You can easily solve this on a ViewModel's side. Just use a property which returns placeholder's image when source is `null`, eg `ImageUrlOrPlaceholder`. I don't think it should be implemented in FFImageLoading.

**Comment by dlpopescumtk** [comment]
@daniel-luberda : I was indeed doing that, already, I was curious if it's an issue, so I thought I'd ask you :)
Thanks for the help!

**Comment by SagarPanwala** [comment]
I know this is closed one, but still can we make 1 boolean or something like that if url is null or empty , control will use ErrorImage, I'm using 1 custom control on multiple places. So with this, I just need to set property from xaml in that control and Bang. Currently I'm using converter, but this will remove need of converters.
This is suggestion. Forgive me that I write comment in closed bug, but this one is most relative with my thought so I added it here.
