### ISSUE TITLE
Error in C# and Xamrian project

### ISSUE THREAD

**Issue by AbdulghaniSyr** [luberda-molinet/FFImageLoading#1005]
### Description
I create a simple project Cross platform and make 5 pages with labels, and buttons,
when I try to run it I faces these error two times even when I recode the project from scratch,
what should I do to solve this problem?

### Screenshots

![image](https://user-images.githubusercontent.com/19244093/38319334-403cc552-383a-11e8-9d2d-99245171b700.png)

![image](https://user-images.githubusercontent.com/19244093/38319355-4aa4ae56-383a-11e8-9b9a-778890afa0bd.png)
 I tested the app only on android Emulator
#Cs #28  #xamrin

**Comment by Magic73** [comment]
delete bin and obj folders. then rebuild the solution.

**Comment by daniel-luberda** [comment]
I'll close this one as I don't see anything FFImageLoading related.
