### ISSUE TITLE
Can't bind BackgroundColor to view model property

### ISSUE THREAD

**Issue by stesvis** [luberda-molinet/FFImageLoading#1007]
### Description

If I set the BackgroundColor property in XAML it works fine, but if I bind it to a view model property, it doesn't.

### Steps to Reproduce

XAML:
`<ffimageloadingsvg:SvgCachedImage Source="resource://VeloGuideApp.Resources.Images.guest_dash_ic_guides.svg" BackgroundColor="{Binding GuidesToggleBgColor}" WidthRequest="100" HeightRequest="100"/>`

ViewModel:
```
        private Color _guidesToggleBgColor;
        public Color GuidesToggleBgColor
        {
            get { return _guidesToggleBgColor; }
            set { SetProperty(ref _guidesToggleBgColor, value); }
        }
...
        GuidesToggleBgColor = Color.LightGray;
```

### Expected Behavior

Background color would be LightGray

### Actual Behavior

BackgroundColor is not set

### Basic Information

- Version with issue: 2.3.6
- Platform: iOS/Android

**Comment by daniel-luberda** [comment]
I'll close this one as it's not FFImageLoading related. https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics
