### ISSUE TITLE
error in pcl xamarin doid project

### ISSUE THREAD

**Issue by pedromocoramalho** [luberda-molinet/FFImageLoading#1009]
- Version with issue: 2.3.6

- Platform: andoid

System.TypeLoadException: Could not resolve type with token 01000035 (from typeref, class/assembly FFImageLoading.Views.ImageViewAsync, FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)

### Reproduction Link / Code
![image](https://user-images.githubusercontent.com/18282832/38380329-47910d74-38fb-11e8-86c6-15bd2861c827.png)

**Comment by daniel-luberda** [comment]
Exception is self explanatory, you're missing `FFImageLoading.Platform` assembly. You must install FFImageLoading package to all of your projects, then remove all `bin` / `obj` folders to be sure it's not a VS issue.
