### ISSUE TITLE
System.ArgumentNullException thrown on HttpReadTimeout

### ISSUE THREAD

**Issue by nikolasborrel** [luberda-molinet/FFImageLoading#1010]
### Description

When reaching a HttpReadTimeout, a System.ArgumentNullException is often thrown instead of a timeout exception

Below is the call, the stack trace is attached. Thanks.

`ImageService.Instance.LoadUrl(the_url).DownSample(1200).DownloadProgress((progress) => {}).Success(SuccessAction).Error(HandleErrorAction).Into(ImageView);`

### Basic Information

- Version with issue: FFImageLoading 2.3.6
- Platform: iOS / Xamarin
[crash_log_ffimageloading.txt](https://github.com/luberda-molinet/FFImageLoading/files/1902964/crash_log_ffimageloading.txt)

**Comment by nikolasborrel** [comment]
Also sometimes a NullReferenceException is thrown

**Comment by daniel-luberda** [comment]
I checked attached stack trace. It looks like it's not an FFImageLoading issue, but a Xamarin issue. You should post it on `Xamarin.iOS` project site.
