### ISSUE TITLE
PlaceHolder when Source is null

### ISSUE THREAD

**Issue by Zure1** [luberda-molinet/FFImageLoading#1011]
I tried to implement this in a fork but I didn't the code enough to pull this off :(

My suggestion is to add the possibility to show a placeholder when Source is null. This could be done by adding a property named "NullPlaceholder" which replaces Source if Source if null.

This would be useful, especially for the use case where one is using FFImageLoading in a ListView and you don't know if Source will be filled or null.

**Comment by daniel-luberda** [comment]
Duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/1002 (solution provided)
