### ISSUE TITLE
What unit is used for CircleTransformation's BorderSize?

### ISSUE THREAD

**Issue by salvador-guerrero** [luberda-molinet/FFImageLoading#1012]
### Description

I was trying to apply a 4dp border to a 50x50 image, at first i assumed CircleTransformation's BorderSize property used dp as its unit, but i got a very thin border, so i checked the source code for Android and found this

[FFImageLoading.Transformations.Droid/RoundedTransformation.cs](https://github.com/luberda-molinet/FFImageLoading/blob/4b8c23720a713a3acf016c253d151175cdc8471d/source/FFImageLoading.Transformations.Droid/RoundedTransformation.cs#L96)

    borderSize = (borderSize * (desiredWidth + desiredHeight) / 2d / 500d);

This helped me to get the border i expected, but i'm wondering what's the logic behind this calculation

**Comment by daniel-luberda** [comment]
Honestly, I don't remember :) Transformations were implemented for my private needs years ago. I think we should unify it though in upcoming versions. I added it to new features / enhancements thread
