### ISSUE TITLE
Native linking error: framework not found IOSurface for architecture arm64

### ISSUE THREAD

**Issue by zjmsky** [luberda-molinet/FFImageLoading#1019]
#when i download FFImageLoading 2.3.6 from Nuget。In ios project i use this code " **CachedImageRenderer.Init();**" then  vs compile error。The error is "**Native linking error: framework not found IOSurface for architecture arm64**"。

**My vs 2017 version is 15.6.6,my Xamarin verison is 4.9.0.753.Xamarin.iOS version is 11.9.1.24. Can you help me to solve this problem?Thanks!**
![default](https://user-images.githubusercontent.com/18650697/39223163-faadf576-4872-11e8-8c7a-eca766839d08.png)
![default](https://user-images.githubusercontent.com/18650697/39223165-ff061c8e-4872-11e8-9739-593711eb4a8a.png)

**Comment by daniel-luberda** [comment]
I don't think it's related to FFImageLoading.

- make sure you have the same package version installed in all projects
- remove all bin/obj folders from all projects

Did you try it?

**Comment by daniel-luberda** [comment]
Please reopen if you provide a repo. Thx.

**Comment by Mustafa7070** [comment]
in visual studio 2015 v14.0
xamarin.ios v 10.10
after I added this line to my ios project, I get the same error

using FFImageLoading;
ImageService.Instance.LoadFile(ViewModel.BannerUrl).Into(ImageBunner);

when I removed that, my project Build successfully!

I don't know why !!!

**Comment by DIma-Kush** [comment]
any solutions?
got the same on IOS, while on Android FFImageLoading library works good
Installed like in docs: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API

**Comment by anup3795** [comment]
@Mustafa7070 ,I am facing same issue after adding FFImageLoading.Do you have any solution for this?
