### ISSUE TITLE
Cannot access a disposed object in get_SizeInBytes

### ISSUE THREAD

**Issue by justintoth** [luberda-molinet/FFImageLoading#1020]
### Description

Using the latest version of FFImageLoading for Xamarin Android, our latest Android release has been generating hundreds of the below error. It seems to be related to accessing a bitmap that has already been disposed.

### Steps to Reproduce

Not sure.

### Expected Behavior

App won't crash.

### Actual Behavior

App crashes with the following error:

> Package: com.rpr.mobile
> Version Code: 392
> Version Name: 1.69.11
> Android: 7.0
> Android Build: NRD90U
> Manufacturer: LGE
> Model: LG-H872
> Thread: Thread-7-34347
> CrashReporter Key: 7F46D7F3-EA2A-7748-F49F-B17137BFB3FCB5F97C21
> Start Date: Wed Apr 25 22:19:28 MDT 2018
> Date: Wed Apr 25 22:24:12 MDT 2018
> Format: Xamarin
> 
> Xamarin caused by: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'FFImageLoading.Drawables.FFBitmapDrawable'.
>   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <1d4884c8abbf46189d6e939cfb7ab141>:0 
>   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <1d4884c8abbf46189d6e939cfb7ab141>:0 
>   at Android.Graphics.Drawables.BitmapDrawable.get_Bitmap () [0x0000a] in <b79b50d567014e26a020222ba34de2fd>:0 
>   at FFImageLoading.Drawables.SelfDisposingBitmapDrawable.get_SizeInBytes () [0x00008] in <e0f5a132c16f4463a79a91161df8798f>:0 
>   at FFImageLoading.Cache.LRUCache.SizeOf (Java.Lang.Object key, Java.Lang.Object value) [0x0000a] in <e0f5a132c16f4463a79a91161df8798f>:0 
>   at Android.Util.LruCache.n_SizeOf_Ljava_lang_Object_Ljava_lang_Object_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_key, System.IntPtr native_value) [0x00017] in <b79b50d567014e26a020222ba34de2fd>:0 
>   at (wrapper dynamic-method) System.Object.000b7b78-3853-43a7-94eb-f00dc47e5fc8(intptr,intptr,intptr,intptr)
> 	at md59cd5ae6924ea1865908f6a4eed48fb35.LRUCache.n_sizeOf(Native Method)
> 	at md59cd5ae6924ea1865908f6a4eed48fb35.LRUCache.sizeOf(LRUCache.java:30)
> 	at android.util.LruCache.safeSizeOf(LruCache.java:286)
> 	at android.util.LruCache.remove(LruCache.java:238)

### Basic Information

- Version with issue: 2.3.6
- Platform: Xamarin Android

**Comment by daniel-luberda** [comment]
Fixed with @justintoth commit. Thanks.
