### ISSUE TITLE
Unable to bind to Degrees on fftransformations:RotateTransformation

### ISSUE THREAD

**Issue by Bejasc** [luberda-molinet/FFImageLoading#1022]
### Description

Have an `ffimageloading:CachedImage`, wanting to apply a rotation to it through data binding. I am able to set a rotation explicitly by giving the `Degrees` a value, but not able to bind a value to the same field.

The error, produced on build is:
`No property, bindable property, or event found for 'Degrees', or mismatching type between value and property.`

### Steps to Reproduce

1 - Bind to the Degrees property of fftransformations:RotateTransformation
2 - Start Build
3 -  `No property, bindable property, or event found for 'Degrees', or mismatching type between value and property.`

### Expected Behavior
Image appear on form rotated by the value specified in the bound property. 

### Actual Behaviour

Error on Build 
`No property, bindable property, or event found for 'Degrees', or mismatching type between value and property.`

### Basic Information

- Version with issue:  2.3.6
- Last known good version: n/a
- Platform: Xamarin Forms

### Reproduction Link / Code

```xaml
<ffimageloading:CachedImage Grid.Row="0" Grid.Column="0" HorizontalOptions="Center"         VerticalOptions="Center" DownsampleToViewSize="true"
    Aspect="AspectFit" Source="{Binding SourceImage}" Margin="5,5,5,5">
    <ffimageloading:CachedImage.Transformations>
        <fftransformations:RotateTransformation Degrees="{Binding Rotation}"/> <!-- Cannot use binding here, code works if a value ie "45" is explicitly provided -->
    </ffimageloading:CachedImage.Transformations>
</ffimageloading:CachedImage>
```

**Comment by Bejasc** [comment]
For anyone else coming across this issue, I've solved it by creating a control that wraps around the `CachedImage`, and applying a new `RotateTransformation` to the transformations list.

```csharp
public class RotatedImage : CachedImage
    {
        public static BindableProperty MyRotationProperty = BindableProperty.Create(nameof(MyRotation), typeof(int), typeof(RotatedImage), 0, propertyChanged: UpdateRotation);

        public int MyRotation
        {
            get { return (int)GetValue(MyRotationProperty); }
            set { SetValue(MyRotationProperty, value); }
        }

        private static void UpdateRotation(BindableObject bindable, object oldRotation, object newRotation)
        {
            var _oldRotation = (int)oldRotation;
            var _newRotation = (int)newRotation;

            if (!_oldRotation.Equals(_newRotation))
            {
                var view = (RotatedImage)bindable;
                var transformations = new System.Collections.Generic.List<ITransformation>() {
                    new RotateTransformation(_newRotation)
                };
                view.Transformations = transformations;
            }
        }
    }
```

Still, it would be nice to support binding out of the box!

**Comment by daniel-luberda** [comment]
Hi, glad that you sorted it out. It's on our todo list. See: https://github.com/luberda-molinet/FFImageLoading/issues/860

I'll close this one.
