### ISSUE TITLE
Unable to retrieve image data. Only http or https scheme is allowed

### ISSUE THREAD

**Issue by Umar3x** [luberda-molinet/FFImageLoading#1023]
### Description

I read a lot of issues about this error ... Tried a lot, but there is too much information, and I can't figure out what's happening ... I'm sorry for opening an issue but I can't find a way to stop this error. Here is my XAML : 

`    <forms:SvgCachedImage Source="resource://MyApp.Resources.mysvgFile.svg"/>`

I also tried with classic binding 
`            Source = SvgImageSource.FromFile("mysvgFile.svg");`

I put the svg file as EmbeddedResource, did not change anything. 

I tried all ways explained in wiki, having another error (put Init() in the mainAcitivity) : 

**04-27 22:58:07.643 D/skia    (25805): --- SkAndroidCodec::NewFromStream returned null
04-27 22:58:07.644 D/skia    (25805): --- SkAndroidCodec::NewFromStream returned null[Gorilla][2][10:58:07.653 P 04/27/18][Error] [Img] Failed to download image.. FFImageLoading is unable to generate image.**

04-27 22:58:07.653 I/mono-stderr(25805): [Gorilla][2][10:58:07.653 P 04/27/18][Error] [Img] Failed to download image.. FFImageLoading is unable to generate image.

`
<ffimageloadingsvg:SvgCachedImage WidthRequest="200" HeightRequest="200" Source="sample.svg"/>	`

**I think that might be due to profile type of project (using SCL), I tried w/o gorilla player, the error remains. Why is it throwing an error about HTTP/HTTPS as I'm using local resources ?** 

I also tried to change HTTP implementation from Android project properties, not changing anything. 
Thanks.

### Basic Information

- Version with issue: 2.3.6
- Platform:  Android
**- Project Type : Prism for XF .NET standard 2.0**

**Comment by daniel-luberda** [comment]
- make sure you have the same package version installed in all projects
- remove all `bin`/`obj` folders from all projects 
- make sure your file content type is set to `EmbeddedResource`
- you should use `Source = SvgImageSource.FromResource("MyApp.Resources.mysvgFile.svg");` instead `Source = SvgImageSource.FromFile("mysvgFile.svg");`
