### ISSUE TITLE
It is possible that sometimes Success or Error event are never called?

### ISSUE THREAD

**Issue by marcin-solvenet** [luberda-molinet/FFImageLoading#1027]
### Description
Hi Daniel,

Thanks again for this great library. I have an issue with downloading images in background. Sometimes the events Success or Error are never called, just a Finish event.
It happens randomly and seems to be more often on Android.

Can you please check if there is a case for such situation?

### Steps to Reproduce

It happens randomly more often on Android.

### Expected Behavior

Always either Success either Error event should be called. Am I correct?

### Actual Behavior

Sometimes Success and Error events are not called just a Finish event.

### Basic Information

- Version with issue: 2.3.4, happened also on 2.3.6
- Platform: iOS and Android
### Reproduction Link / Code
I'm downloading images using this code

  _imageLoaderTask = ImageService.Instance.LoadUrl(url, TimeSpan.FromDays(15))
                                                   .Success((imageInfo, loadingResult) => this.ImageDownload_Success(imageInfo, loadingResult))
                                                   .Error((exception) => ImageDownload_Error(exception))
                                                   .Finish((sheduledWork) => ImageDownload_Finish(sheduledWork))
                                                   .DownloadOnly();

  _imageLoaderTask.RunAsync();

**Comment by daniel-luberda** [comment]
All logic is in one class: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Work/ImageLoaderTask.cs

Search for `OnSuccess` and `OnErrror` - if there's any issue it should be there. I'll need to review it if there could be any potential issues, but currently no-time for this :)

**Comment by daniel-luberda** [comment]
I reviewed the code and it looks like only when `OperationCanceledException` is thrown it won't call `OnError`. I don't think we should change it, we could add `OnCancel` callback instead.

**Comment by marcin-solvenet** [comment]
Thanks @daniel-luberda I agree, onCancel callback solves problem we had

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/1278
