### ISSUE TITLE
Failed to resolve assembly: 'FFImageLoading.Forms, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by TMagnum1974** [luberda-molinet/FFImageLoading#1028]
Hi there!

I created a brand new Xamarin.Forms (2.5.1.527436) .net Standard Project. Created a Content Page, installed FFmageLoading.Forms, FFImageLoading.Svg.Forms, FFImageLoading.Transformations. Version is 2.3.6. Using Visual Studio 2017 15.6.7

I do just have an iOS Project, showing the References correctly (did unload the Android Project for now since I just want to build it sometime later). The iOS App works in general (LivePlayer / Simulator).

Created a ContentPage and added this:
**xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms**

But I can't get it to work - I always get this error:
Failed to resolve assembly: 'FFImageLoading.Forms, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

I tried to change the assembly name to Xamarin.FFImageLoading.Forms (since that's the referenced assembly name) but it makes no difference.

I did add the following line to AppDelegate.cs:
**FFImageLoading.Forms.Touch.CachedImageRenderer.Init();**

_Directly using CachedImageRenderer.Init(); did not work - had to state it fully qualified ..._

I don't understand what I'm doing wrong here - is there a way to help? 

Thanks in advance!

P.S: Or is this (just) an issue when using LivePlayer (using the most recent from the beta program ...)? Because the build succeeds but once I try it in Live Player, I get the above mentioned error?!

**Comment by daniel-luberda** [comment]
Did you try newest prerelease version?

**Comment by TMagnum1974** [comment]
Excellent! It works now - thank you!

**Comment by nguyenthanhliemfc** [comment]
I facing this issue with version 2.4.11.982.
How to fix it!
Thank!
