### ISSUE TITLE
Cache: crushed images when open the page 1st time

### ISSUE THREAD

**Issue by biapar** [luberda-molinet/FFImageLoading#1030]
### Description

After I activate the cache, the images are crushed when open the page the first time. After close and open again all is ok.

### Steps to Reproduce

Image gallery with no crushed images
![img_9817](https://user-images.githubusercontent.com/661517/39890902-8807e078-549c-11e8-9385-6d8ba57a2e61.png)

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform: 

### Screenshots

Correct view after reload the view
![img_9818](https://user-images.githubusercontent.com/661517/39890986-c5f5bff4-549c-11e8-94f8-87daf0f3d91c.png)

### Reproduction Link / Code

Download: Check the app "Bagno 38 Lido" into the app stores

**Comment by daniel-luberda** [comment]
I can't help you if you don't share any code or a repo.

BTW: It's probably not an FFImageLoading issue, please make sure your image container view `VerticalOptions` are set to `FillAndExpand`

**Comment by biapar** [comment]
The problem appear after that I activate the cache loading.
