### ISSUE TITLE
Svg rounded corners not rendered

### ISSUE THREAD

**Issue by michelmoorlag** [luberda-molinet/FFImageLoading#1033]
### Description

I have two svg's that contain a line with rounded corners. When I render them in a Xamarin Forms App the rounded corners are cut off

### Steps to Reproduce

1. Create a new XF 3.0 app from scratch
2. Add the latest 2.3.6 Xamarin.FFImageLoading.Forms and Xamarin.FFImageLoading.Svg.Forms nuget packages
3. Add the initialization FFImageLoading like documented
4. Add the added svg's to the shared .net standard project in a Resouces folder and set them to  "Embedded recource"
5. Replace the lable in the stacklayout in the mainpage with

    <ContentPage.Content>
        <StackLayout>
            <forms:SvgCachedImage WidthRequest="50" HeightRequest="50" Aspect="AspectFit" Source="resource://YourApp.Resources.icon_magnifying-glass2.svg"/>
            <forms:SvgCachedImage WidthRequest="50" HeightRequest="50" Aspect="AspectFit" Source="resource://YourApp.Resources.icon_list.svg"/>
        </StackLayout>

Start a Android or iOS simulator and see that the rounded corners are cut off.

### Expected Behavior

I would expect the whole svg is shown in the app with rounded corners

### Actual Behavior

The svg's rounded corners are cut off to a 90 degrees strait line.

### Basic Information

- Version with issue: 2.3.6
- Last known good version: unknown
- Platform: both Android and iOS

### Screenshots
svg:
![image](https://user-images.githubusercontent.com/14913939/40118353-00d5f0e0-591a-11e8-864f-413126d994e7.png)
In app:
![image](https://user-images.githubusercontent.com/14913939/40118251-b068661a-5919-11e8-9265-51bffc0d475f.png)

### Reproduction Link / Code

[svgs.zip](https://github.com/luberda-molinet/FFImageLoading/files/2009201/svgs.zip)

**Comment by daniel-luberda** [comment]
It's fixed in newest stable.
