### ISSUE TITLE
Load resource uri with Base64 image not work while using databinding

### ISSUE THREAD

**Issue by KhuongNtrd** [luberda-molinet/FFImageLoading#1039]
I have an image with base64 code (attached), using `data:image/png;base64,[BASE64ENCODEDFILE]` format to show, that work only while set directly in xaml but not work with data binding.

  at FFImageLoading.DataResolvers.ResourceDataResolver.Resolve (System.String identifier, FFImageLoading.Work.TaskParameter parameters, System.Threading.CancellationToken token) [0x0005b] in C:\projects\ffimageloading\source\FFImageLoading.Droid\DataResolvers\ResourceDataResolver.cs:29 
  at FFImageLoading.DataResolvers.WrappedDataResolver+<Resolve>d__2.MoveNext () [0x00020] 
in C:\projects\ffimageloading\source\FFImageLoading.Common\DataResolvers\WrappedDataResolver.cs:22 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at FFImageLoading.Work.ImageLoaderTask`3+<RunAsync>d__108[TDecoderContainer,TImageContainer
,TImageView].MoveNext () [0x002f7] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:523 

[base64_image.txt](https://github.com/luberda-molinet/FFImageLoading/files/2035531/base64_image.txt)

**Comment by daniel-luberda** [comment]
1. You didn't attach full stack trace, please provide full exception stack trace. 
2. Please make sure your file start with `data:image/png;base64,[BASE64ENCODEDFILE]`

If it won't work, please attach a repo project.

**Comment by KhuongNtrd** [comment]
```
public class DataUrlPageModel : BasePageModel
{
	public DataUrlPageModel()
	{
	}

	public string SvgString => "<svg height=\"100\" width=\"100\"><circle cx=\"50\" cy=\"50\" r=\"40\" stroke=\"#000\" stroke-width=\"3\" fill=\"#ccc\"/></svg>";

	public string SvgStringUrlFormat => "data:image/svg+xml,<svg height=\"100\" width=\"100\"><circle cx=\"50\" cy=\"50\" r=\"40\" stroke=\"#000\" stroke-width=\"3\" fill=\"#ccc\"/></svg>";
	
	public string Base64String => "data:image/png;base64,/9j/4AAQSkZJRgABAQEAAAAAAAD/4QC8RX...";
	
	public void Reload()
	{
	}
}

```

```
<StackLayout>
	<ffimageloading:CachedImage HeightRequest="100"
								Source="{Binding Base64String}"/>
</StackLayout>
```

It not work, I've debug with current source but the type converter not work, seem binding bugs, base64 string too long.

**Comment by Mirinael** [comment]
Hi, I think I'm having the same issue. If I use a very small base64 encoded image (~ <50ko), using a binding on the base64 string in xaml is working. However, with a bigger image, it raises an Image loading failed.

I didn't try in cs instead of xaml tho. On my way. :)

Here's the stack trace :
[stack_trace.txt](https://github.com/luberda-molinet/FFImageLoading/files/2599005/stack_trace.txt)

**Comment by PauchardThomas** [comment]
> Source

Still have "Invalid URI: The Uri string is too long"

**Comment by MerlinSOI** [comment]
I am having exactly the same message for a long URI.
@daniel-luberda, could you reopen the issue and fix it?

**Comment by Raystorm7** [comment]
Hi,
same problem here.
If I set the CompressionQuality to a low number (between 0 and 20) the image is shown, but if I set this value with an higher number the the component throw an error.
Attached the stack.
@daniel-luberda, could you reopen the issue and fix it?
Thank you.
[stack.txt](https://github.com/luberda-molinet/FFImageLoading/files/4127462/stack.txt)

**Comment by AndreSlim** [comment]
I had the same problem with images that were too large in base64, the solution for me was to remove the prefix `data:image/jpg;base64,` and set the Binding of type `ImageSource`

Fragment of my XAML code
`<ffimageloading:CachedImage`
`Aspect="AspectFill"`
`FadeAnimationEnabled="True"`
`Source="{Binding Image}" />`

Fragment of my C # code in ViewModel (MVVM pattern)
`Regex regex = new Regex(@"^[\w/\:.-]+;base64,");`
`imageBase64 = regex.Replace(imageBase64, string.Empty);`
`Image = ImageSource.FromStream(() => new MemoryStream(Convert.FromBase64String(imageBase64)));`

I hope it helps someone
