### ISSUE TITLE
FFImageLoading not work on macOS

### ISSUE THREAD

**Issue by albilaga** [luberda-molinet/FFImageLoading#1040]
### Description

FFImageLoading not loading into NSImageView after success

### Steps to Reproduce

Run the repo below. The image view should load from url. 

### Expected Behavior

The Image View should load data from url and directly show it in imageview. I just added default image to make sure ImageView is already added in View. If I use directly
`ImageView.Image = new NSImage(new NSUrl("https://..."))` it work

### Actual Behavior

Image View not updating data with the finished Image loaded from url

### Basic Information

- Version with issue: 2.3.6
- Last known good version: not sure. the first time using FFImageLoading in macOS
- Platform: macOS

### Reproduction Link / Code

https://github.com/albilaga/FFImageLoadingMacBugDemo.

**Comment by daniel-luberda** [comment]
Fixed, try newest prerelease. (I only tested it with Xamarin.Forms)
