### ISSUE TITLE
DownsampleWidth for non-resource (filepath) images not working?

### ISSUE THREAD

**Issue by stevehunter123** [luberda-molinet/FFImageLoading#1041]
### Description

I'm new to FFImageLoading, but when I use a resource from the tutorial, downsamplewidth results in a small image as expected.  When I do the same thing with a filepath image (e.g. chosen from iOS or android photo gallery), it is always the same size instead of small image.

Works:
		CachedImage img = new CachedImage();
			img.DownsampleWidth = 100;
			img.Source = "resource://gallery.img.jpg";

Doesn't work (full size):
mainActivity.cs
		protected override void OnActivityResult(int requestCode, Result resultCode, Intent data) {
				string convertedPath = getRealPathFromURI(data.Data);
					(Xamarin.Forms.Application.Current as App).ShowImage(convertedPath);

appDelegate.cs
imagePicker.FinishedPickingMedia += (sender, e) => {
var filepath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "tmp.png");
InvokeOnMainThread(() =>	{
			(Xamarin.Forms.Application.Current as App).ShowImage(filepath);
});

app.xaml.cs
ShowImage(...) {
			img.Source = filepath;
			img.DownsampleWidth = 10;  // can be 100 too, doesn't make any difference

**Comment by daniel-luberda** [comment]
Please attach a repo project. Local files are resized exactly the same as any other. 

BTW: 

```C#
img.Source = filepath;
img.DownsampleWidth = 10; // can be 100 too, doesn't make any difference
```

Wrong order here... you're setting downsample size AFTER you load an image...

**Comment by stevehunter123** [comment]
Actually, I tried to do both before and after.  It didn't matter.  I will upload sample code soon.  For example, I did this just to be sure.

img.DownsampleWidth = 10; // can be 100 too, doesn't make any difference
img.Source = filepath;
img.DownsampleWidth = 10; // can be 100 too, doesn't make any difference
