### ISSUE TITLE
Not working with SCL projects ?

### ISSUE THREAD

**Issue by Phobie53** [luberda-molinet/FFImageLoading#1042]
### Description

I am trying to use SVG on my SCL project but image is not displayed
Though it was my SVG files but on the demo sample it's working.
Though it was my implementation but SVG's file of the demo are not working on my project

So I created a new .Net standard project, it's working with my images.
I created a new SCL project, it's not working.
(Same images, same implementation in both)

### Steps to Reproduce

Create a new SCL project, follow the tutorial and images are not loaded

### Expected Behavior

Images should be loaded

### Actual Behavior

Images not loaded

### Basic Information

- Version with issue: latest
- Last known good version: -
- Platform: Android

### Screenshots

No image load so no screen

### Reproduction Link / Code

`<ffimageloadingsvg:SvgCachedImage WidthRequest="100" HeightRequest="100" Source="resource://Livli.Resources.Livli.svg"/>`

**Comment by daniel-luberda** [comment]
SCL's are working fine. Please ma sure you followed this: 

- https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API
- https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support#xamarinforms

and attach a repo project if it won't help.

**Comment by Phobie53** [comment]
[Livli.zip](https://github.com/luberda-molinet/FFImageLoading/files/2044129/Livli.zip)
Hello, I have done everything but still not working. This is my current project I am working on.
On the Login.xaml line 11, 12, 13 you can find my issue. Thanks for your time.

**Comment by daniel-luberda** [comment]
There are various issues in your code. I suggest to read our wiki page first. 

1. Self explanatory:

```
2018-05-28 23:35:42.373 Livli.iOS[4389:2403796] Image loading faImage loading failed: Livli.svg;(size=0x100,dip=True)
System.IO.FileNotFoundException: Livli.svg
```

2.  It should be 
`<ffimageloadingsvg:SvgCachedImage WidthRequest="100" HeightRequest="100" Source="resource://Livli.Resources.Livli.svg"/>`
not 
`<ffimageloadingsvg:SvgCachedImage WidthRequest="100" HeightRequest="100" Source="Livli.Resources.Livli.svg"/>`
and also you should set file resource id property to: `Livli.Resources.Livli.svg` (it's empty in your samples)

3. You should use native http client handlers as described here: https://docs.microsoft.com/pl-pl/xamarin/android/app-fundamentals/http-stack

etc.

**Comment by Phobie53** [comment]
Hello, thanks for your advices.

I did what you said but still not working. So I added : 
```
var assembly = Assembly.GetExecutingAssembly();
		    foreach (var res in assembly.GetManifestResourceNames())
		    {
		        System.Diagnostics.Debug.WriteLine("found resource: " + res);
		    }
```

And I got 

> [0:] found resource: Livli.Droid.Resources.Livli.svg
> [0:] found resource: Livli.Droid.Resources.Oval.svg
> [0:] found resource: Livli.Droid.Resources.ShortPrimaryButton.svg
> [0:] found resource: Livli.Droid.Resources.fingerprint.svg

So when I do : 
`<ffimageloadingsvg:SvgCachedImage WidthRequest="100" HeightRequest="100" Source="resource://Livli.Droid.Resources.Livli.svg"/>`

It's working. But it's not the best solution since I want my application to be cross platform. Do I need to do for each platform a **OnPlatform** tag ?

```
<OnPlatform x:TypeArguments="x:String" x:Key="LogoSVG">
                <On Platform="Android" Value="Livli.Droid.Resources.Livli.svg" />
                <On Platform="iOS" Value="Livli.iOS.Resources.Livli.svg" />
            </OnPlatform>
```

**Comment by daniel-luberda** [comment]
You should include those files in shared dll and use one common name. That's all. Currently, you're using platform specific projects.
