### ISSUE TITLE
Unhandled Exception ff version 2.4.0.799 pre

### ISSUE THREAD

**Issue by maherzaidoune** [luberda-molinet/FFImageLoading#1043]
### Description
First thank you for this awesome library .
i'm using FFImageLoading in my project, i was trying to improve the listview performance by updating to last ffimageloading version , but i got an unhadled exception.

### Steps to Reproduce

just update ffimageloading to the last version,2.4.0.799-pre

### Expected Behavior

better performance

### Actual Behavior

application crash on loading screen with "System.MethodAccessException: Method `FFImageLoading.Forms.CachedImage.set_IsRendererInitialized(bool)' is inaccessible from method `FFImageLoading.Forms.Platform.CachedImageRenderer.Init(System.Nullable`1<bool>)'" exception

### Basic Information
-xamarin forms 3.0.0.482510
-ffImageLoading 2.4.0.799 pre

### Screenshots

![ff](https://user-images.githubusercontent.com/10913540/40592467-0cad09e4-6220-11e8-9531-ef05ab109b7c.png)

**Comment by daniel-luberda** [comment]
Please make sure: 

- You have the same FFImageLoading version in all projects
- Remove all `bin`/`obj` folders & rebuild

**Comment by maherzaidoune** [comment]
that doesn't fix it

**Comment by daniel-luberda** [comment]
I'm quite sure you have different library dll versions colliding somewhere (between projects)

**Comment by maherzaidoune** [comment]
i just updatedto the stable 2.4.1.823 and it works fine

**Comment by FrancescoAntonelli** [comment]
Have same issue

**Comment by AditCygnet** [comment]
@maherzaidoune  I have used 2.4.1.823 version also still not resolved.

**Comment by maherzaidoune** [comment]
@AditCygnet   it works for  me, with  the last xamarin stable release

**Comment by daniel-luberda** [comment]
It's not an FFImageLoading issue but rather Visual Studio's issue. The key is to remove all cached files (like `obj`, `bin` folders. I'll close this one.
