### ISSUE TITLE
SVG line thickness rendered incorrect

### ISSUE THREAD

**Issue by michelmoorlag** [luberda-molinet/FFImageLoading#1044]
### Description

I have two svg's with the smae line thickness. I preview the line thickess look the same because they are but in-app one is show correct but th other has a very thin line. Also the clock hands are solid but in-app the inside is white?

### Steps to Reproduce

Create a new XF 3.0 app from scratch

Add the latest 2.3.6 Xamarin.FFImageLoading.Forms and Xamarin.FFImageLoading.Svg.Forms nuget packages

Add the initialization FFImageLoading like documented

Add the added svg's to the shared .net standard project in a Resouces folder and set them to "Embedded recource"

Replace the lable in the stacklayout in the mainpage with

<ContentPage.Content>

<forms:SvgCachedImage WidthRequest="50" HeightRequest="50" Aspect="AspectFit" Source="resource://YourApp.Resources.icon_milk_churn.svg"/>
<forms:SvgCachedImage WidthRequest="50" HeightRequest="50" Aspect="AspectFit" Source="resource://YourApp.Resources.icon_time.svg"/>
Start a Android or iOS simulator and see that the line thickness of the icon_milk_churn is incorrect. Also the hands of the clock are not solid.

### Expected Behavior

I would expect that the icon_milk_churn.svg would have a fatter line thickness like the clock. Also I would expect the hands of the clock to be solid.

### Actual Behavior

The line thickness of the icon_milk_churn.svg is too thin. The inside of the clock hands are white.

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform: 

### Screenshots

Preview:
![image](https://user-images.githubusercontent.com/14913939/40642461-7a1f6f32-631d-11e8-9d5d-59c9c543cfa4.png)
In-app:
![image](https://user-images.githubusercontent.com/14913939/40642616-e92b9932-631d-11e8-8b48-5bc70a7e068f.png)

### Reproduction Link / Code

[icons.zip](https://github.com/luberda-molinet/FFImageLoading/files/2047042/icons.zip)

**Comment by daniel-luberda** [comment]
Fixed

**Comment by michelmoorlag** [comment]
Really great work!
Can you tell what was the problem?

**Comment by daniel-luberda** [comment]
it's here: https://github.com/luberda-molinet/FFImageLoading/commit/d15a6dfb59cf58858454878c84cbc2cce1e04341
