### ISSUE TITLE
Re-Re-Open Svg-s are rendered pixelated

### ISSUE THREAD

**Issue by MosCD** [luberda-molinet/FFImageLoading#1045]
### Description

This is an old Issue, now months old
closed issue though in every where although it is not resolved.
No update till now the packages that solves this issue
Still SVG are rendered pixelated on my app 
I supported this plugin in the past because it is really usefull but with that issue left without resolving
I am now searching other alternatives

This issue has been posted [here](https://github.com/luberda-molinet/FFImageLoading/issues/991)
and [here](https://github.com/luberda-molinet/FFImageLoading/issues/548)
and [here](https://github.com/luberda-molinet/FFImageLoading/issues/522)

All closed with no clear answer to the major plugin flow as I see it. I SVGs are rendered pixelated, then the whole solution must be changed

Please developers working on that plugin. solve this old problem and save us time and effort

![screen shot 2018-05-29 at 8 07 15 pm](https://user-images.githubusercontent.com/32604165/40673916-ec4a2576-637b-11e8-9e6c-d98050d0992c.png)

- Version with issue: 2.3.6
- Last known good version: 
- Platform:

**Comment by MosCD** [comment]
Am sorry @daniel-luberda  for your busy time, but this problem is old enough to catch your attention
I have upgraded all  packages to version 2.4.1 and the problem still exists

<img width="432" alt="screen shot 2018-05-31 at 12 06 59 pm" src="https://user-images.githubusercontent.com/32604165/40773300-2d1988c6-64cb-11e8-84b1-06c1cf2afed6.png">

I embed Svg to my code this way

XAML
`
<Grid Padding="20,10">
        <local:TintedCachedImage SvgSource="macro.svg" TintColor="Yellow"/>
</Grid>
`

and in C#

`
public class TintedCachedImage : CachedImage
    {
        public static BindableProperty TintColorProperty = BindableProperty.Create(nameof(TintColor), typeof(Color), typeof(TintedCachedImage), Color.Transparent, propertyChanged: UpdateColor);

        public Color TintColor
        {
            get { return (Color)GetValue(TintColorProperty); }
            set { SetValue(TintColorProperty, value); }
        }

        private static void UpdateColor(BindableObject bindable, object oldColor, object newColor)
        {
            var oldcolor = (Color)oldColor;
            var newcolor = (Color)newColor;

            if (!oldcolor.Equals(newcolor))
            {
                var view = (TintedCachedImage)bindable;
                var transformations = new System.Collections.Generic.List<ITransformation>() {
                    new TintTransformation((int)(newcolor.R * 255), (int)(newcolor.G * 255), (int)(newcolor.B * 255), (int)(newcolor.A * 255)) {
                        EnableSolidColor = true
                    }
                };
                view.Transformations = transformations;
            }
        }

        //To Support SVG
        public static BindableProperty SvgSourceProperty = BindableProperty.Create(nameof(TintColor), typeof(string), typeof(TintedCachedImage), null, propertyChanged: UpdateSvg);
        public string SvgSource
        {
            get { return (string)GetValue(SvgSourceProperty); }
            set { SetValue(SvgSourceProperty, value); }
        }

        private static void UpdateSvg(BindableObject bindable, object oldVal, object newVal)
        {
            var _instance = bindable as TintedCachedImage;
            _instance.Source = SvgImageSource.FromFile((string)newVal);
        }
    }


`

**Comment by daniel-luberda** [comment]
FFImageLoading uses view width / height to know what size of bitmap should be generated. Did you try to set a constant with / height for that view and see if it solves your issue? Or at least set image layout options to `FillAndExpand`

**Comment by daniel-luberda** [comment]
Any news?

**Comment by MosCD** [comment]
It seems like when you add a height the image gets sharper

please see the difference between the following captures

<img width="1413" alt="screen shot 2018-06-24 at 11 40 30 am" src="https://user-images.githubusercontent.com/32604165/41817421-a50e7234-77a3-11e8-9b10-1958bad6eba3.png">

this is without adding any width or height, although the image is stretched by the grid to take the full page, the scripts seems not to understand that unless you put a dummy height

see this

<img width="1443" alt="screen shot 2018-06-24 at 11 40 48 am" src="https://user-images.githubusercontent.com/32604165/41817434-cd6560f8-77a3-11e8-817f-d6bbcd864fd9.png">

because I added a height of "100" the image is sharper although the actual height is bound by the grid

Well, this seems as a temporary fix, at least I can use the plugin and support it

Thanks for your commitment to update this plugin, you are like a heart to our projects.

**Comment by daniel-luberda** [comment]
Fixed with: 

- https://github.com/luberda-molinet/FFImageLoading/commit/831a6741c0f4377cce7605f0e51ed35011c026ab
- https://github.com/luberda-molinet/FFImageLoading/commit/f0f6b74509a59e7f573e0947708262b4e33f4dc9
