### ISSUE TITLE
Not showing image in ErrorPlaceholder

### ISSUE THREAD

**Issue by asdiomar1** [luberda-molinet/FFImageLoading#1049]
### Description

I'm receiving images from server and it's working correctly. Doing tests I noticed that if the image source it's null or empty it doesn't show the error placeholder image.

### Expected Behavior

Show error placeholder image if the source is null

### Actual Behavior

It doesn't show anything

### Basic Information

- Version with issue: 2.3.6
- Platform: Android

**Comment by daniel-luberda** [comment]
That's a correct behaviour. You should handle it yourself if you want to have a different behaviour. `Null` is a correct value and it's used to remove any sources from an image view.

**Comment by asdiomar1** [comment]
That's what I did, thanks for the response!
