### ISSUE TITLE
Support .NETStandard for SVG

### ISSUE THREAD

**Issue by mrxten** [luberda-molinet/FFImageLoading#1051]
Will library work with embedded resources in net standard?
Now whatever I do I get message 

> Call CacheImageRenderer.Init();

And yes, I did all steps from wiki and used earlier your library for usual cached images.

Thanks.

**Comment by daniel-luberda** [comment]
> Will library work with embedded resources in net standard?

Yes. 

> Now whatever I do I get message
> Call CacheImageRenderer.Init();

It's self explanatory - You need to put `CacheImageRenderer.Init();` in a platform specific project. Could you elaborate what's your issue?
