### ISSUE TITLE
ReplaceStringMap change is not reflected

### ISSUE THREAD

**Issue by davidmn** [luberda-molinet/FFImageLoading#1053]
### Description

ReplaceStringMap does not change the SVG. 

### Steps to Reproduce

```
var dict = new Dictionary<string, string>
{
    { "grey", "red" }
};
    var img = new SvgCachedImage
{
    Source = "results.svg",
};

img.ReplaceStringMap = dict;
img.ReloadImage();

			
StackTest.Children.Add( img );
```

On some SVG that looks like:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
    width='800'
    height='400'
    xmlns='http://www.w3.org/2000/svg'
    version='1.1'
    xmlns:xlink='http://www.w3.org/1999/xlink'>

    <defs>
        <rect id='left-lens' width='30' height='30' x='360' y='185'/>
        <rect id='right-lens' width='30' height='30' x='400' y='185'/>
        <mask id='mask'>
            <rect width='800' height='400' fill='white' />
            <use xlink:href='#left-lens'/>
            <use xlink:href='#right-lens'/>
        </mask>
    </defs>
    
    <rect width='800' height='400' fill='white' mask='url(#mask)'/>

    <use xlink:href='#left-lens' stroke-width='5' stroke='grey' fill='none'/>
    <use xlink:href='#right-lens' stroke-width='5' stroke='grey' fill='none'/>
</svg>
```

### Expected Behavior

The grey stroke should be replace with red.

### Actual Behavior

The grey stroke is still shown.

![two grey rectangles](https://i.imgur.com/P5hcovN.png)

### Basic Information

- Version with issue: 2.4.1.823
- Last known good version: I cant seem to find a version where this snippet works.
- Platform: Android

**Comment by daniel-luberda** [comment]
```C#
var dict = new Dictionary<string, string>
{
    { "grey", "grey" }
};
```

You're replacing grey with grey. Try this: 

```C#
var dict = new Dictionary<string, string>
{
    { "grey", "red" }
};
```

**Comment by davidmn** [comment]
Copy paste error from trying to debug. Changing to `{ "grey", "red" }` still exhibits the same issue.

**Comment by daniel-luberda** [comment]
There's a working sample here: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/SvgReplacePage.xaml (just tried it once again)

Could you make a repo?

**Comment by davidmn** [comment]
I ended up not being able to use SVGs for other reasons so I've not had time to make an example. I guess we could close this.

**Comment by EmilAlipiev** [comment]
hey it is strange behavior indeed. I have some svgs ReplaceStringMap works but attached svg doesnt work. it looks like same problem. did you find a solution for this?

I am also doing like 

var dict = new Dictionary<string, string>
{
    { "#FFFFFF", "#2196F3" }
};

```
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" height="32" width="32" viewBox="0 0 32 32">
  <g>
    <path id="path1" transform="rotate(0,16,16) translate(0,4.10000038146973) scale(1,1)" fill="#FFFFFF" d="M0,17.599985L5.0999756,17.599985 5.0999756,23.799999 0,23.799999z M9,12.299994L14.099976,12.299994 14.099976,23.799999 9,23.799999z M18,6.400027L23,6.400027 23,23.799999 18,23.799999z M26.899994,0L32,0 32,23.799999 26.899994,23.799999z" />
  </g>
</svg>

```
for example same code works for the below svg

```
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 24 24">
  <g>
    <path id="path1" transform="rotate(0,12,12) translate(0.1680006980896,0) scale(0.75,0.75)  " fill="#FFFFFF"  
  </g>
</svg>
```

**Comment by EmilAlipiev** [comment]
@daniel-luberda problem could be with this change. I dont understand why substring starts from 6th position? 

https://github.com/luberda-molinet/FFImageLoading/pull/970/commits/d9fee2fe25d248bbbc6e8d94c36d8a173c292990

**Comment by EmilAlipiev** [comment]
I found the problem in my case. I am using converter as show below 
  
```
<ffimageloadingsvg:SvgCachedImage  Style="{StaticResource IconStyle}"     Source="resource://App1.level.svg"                 
                  ReplaceStringMap="{Binding AssignButton, Converter={StaticResource AppColorToButtonConverter}}" 
                  />
```
```

public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
              
            var ReplaceMap = new Dictionary<string, string>()
                {
                    { "#FFFFFF", "#3F51B5" }
                };

            return ReplaceMap;
          
        }
```

If i define ReplaceStringMap before Source property, it works but other way around like above doesnt work. Please find the repro attached. in the repro change order of source and ReplaceStringMap properties, you will see that it works
[App1.zip](https://github.com/luberda-molinet/FFImageLoading/files/2385097/App1.zip)
