### ISSUE TITLE
svg files show on android emulator but not in mobile device htc one m9 android 7

### ISSUE THREAD

**Issue by mammadkoma** [luberda-molinet/FFImageLoading#1055]
MainActivity.cs : 
CachedImageRenderer.Init(enableFastRenderer: false);
SvgCachedImage.Init();

MainView.xaml
xmlns:ff="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
<ff:SvgCachedImage WidthRequest="100" Source="resource://Sanaap.App.Images.SosRequest.svg"/>

svg files show on android emulator Xamarin Forms project (android).
but not in mobile device htc one m9 android 7 (show nothing).
Why?

Xamarin.FFImageLoading.Svg.Forms 2.3.6
xamarin 4.10

**Comment by daniel-luberda** [comment]
It may be a lot of things:

- remove all `bin` / `obj`, then rebuild
- Xamarin linking issue
- etc etc

**Comment by mammadkoma** [comment]
No svg s not show at all.
remove all bin / obj, then rebuild not work.
Linking is none.

**Comment by mammadkoma** [comment]
![image](https://user-images.githubusercontent.com/17564001/41199823-312b4b80-6cae-11e8-9baa-d7f8383d0d9a.png)

**Comment by mammadkoma** [comment]
This project not show svg files on mobile device too : 
https://github.com/ysmoradi/XamarinFormsPrismSvgSample

**Comment by mammadkoma** [comment]
https://stackoverflow.com/questions/18356098/having-issue-on-real-device-using-vector-image-in-android-svg-android : 

On newer devices that have hardware rendering turned on by default, you need to explicitly turn on software rendering.
`imgView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
`

But how can I this in xamarin forms?

**Comment by mammadkoma** [comment]
Nobody ?!

**Comment by ysmoradi** [comment]
Related to https://github.com/mono/SkiaSharp/issues/554

**Comment by daniel-luberda** [comment]
It's not an FFImageLoading issue. As @ysmoradi mentioned, you should continue on SkiSharp issue page. cheers :)

**Comment by mammadkoma** [comment]
If possible, try selecting the armeabi-v7a option in the linker options and not using the old armeabi option.
