### ISSUE TITLE
Xamarin.Forms Docs Update

### ISSUE THREAD

**Issue by jordan-hewitt** [luberda-molinet/FFImageLoading#1058]
Not an issue, just documents should be updated regarding the Xamarin.Forms API.

Right now you say to use FFImageLoading.Init() in the AppDelegate/MainActivity of iOS and Android to initialize the package.  

In current versions, it says this is obsolete and to use             FFImageLoading.Forms.Platform.CachedImageRenderer.Init(); (use true/false for droid for fast loading)

Your docs should reflect this :)

**Comment by daniel-luberda** [comment]
Feel free to do it yourself. Wiki is editable by anyone :)

**Comment by WasserEsser** [comment]
@daniel-luberda @jordan-hewitt has edited the wiki, this issue can be closed.

**Comment by daniel-luberda** [comment]
Great. Thanks @jordan-hewitt @WasserEsser
