### ISSUE TITLE
The .Into() method is no longer available?

### ISSUE THREAD

**Issue by daniel112** [luberda-molinet/FFImageLoading#1059]
### Description
I'm looking through the document for ways to catch when the image is successfully loaded or not.
My goal is to display an ActivityIndicator on while the image is loading, and depending on if it fails or not, show the image.

I want to do something like:
ImageService.Instance.LoadUrl(urlToImage)
.Success(() =>
{
  activityIndicator.IsRunning = false;
}).Into(cachedImageObject);

but i am unable to call the 'Into' method. is there another way I can do to display the ActivityIndicator on image load?

### Basic Information
- Platform: Xamarin.Forms

**Comment by daniel-luberda** [comment]
It's an extension method. You just need to import correct namespaces.
