### ISSUE TITLE
Requesting a BackgroundColorTransformation

### ISSUE THREAD

**Issue by AlexanderMelchers** [luberda-molinet/FFImageLoading#1060]
Hi all,

 I recently tried updating the `FFImageLoading`-libraries in our App to the new 2.4 minor version, but ran into trouble with the `Xam.Plugins.Forms.CachedImageCircle`-package we're using, since the `CircleCachedImage`-control is looking for the `CachedImageRenderer` in the `FFImageLoading.Forms.Droid`-assembly, which no longer exists.

After a bit of searching, I've now decided to use `CircleTransformation` in order to get those images as need it to be displayed as a circle, while keeping most of our other code in tact. _However_, `CircleCachedImage` had a `FillColor`-property that allowed you to change the background colour of transparent images while still applying the circle transformation. Setting the `BackgroundColor` on a `CachedImage`, however, fills the entire `View`'s surface with that background colour, and _doesn't_ apply the circle transformation to the background...

Now I found the suggestion of a `BackgroundColorTransformation` before, in issue #555, an idea that was later abandoned. However, I would like to reopen the request for such a transformation, since it seems very practical when dealing with images that have a transparent background.

All the best,
Alexander.

**Comment by AlexanderMelchers** [comment]
I'd be willing to try my hand at creating this transformation myself as well, though for that to work I'd need to know the basic architecture of the transformation system. Right now I don't quite understand how transformations are resolved, for example. I mean, you can add transformations in PCL/platform-agnostic code, but implementations seem to be platform-specific, as expected. So how does the system get from platform-agnostic specification to platform-gnostic implementation?

**Comment by AlexanderMelchers** [comment]
I'd be willing to try my hand at creating this transformation myself as well, though for that to work I'd need to know the basic architecture of the transformation system. Right now I don't quite understand how transformations are resolved, for example. I mean, you can add transformations in PCL/platform-agnostic code, but implementations seem to be platform-specific, as expected. So how does the system get from platform-agnostic specification to platform-gnostic implementation?

**Comment by AlexanderMelchers** [comment]
Decided to answer my last question myself, as I bumped into #427, which explains how to do it and contains [a link](https://log.paulbetts.org/the-bait-and-switch-pcl-trick/) describing the "Bait and Switch PCL Trick" used to do so...

**Comment by daniel-luberda** [comment]
It's implemented, but not tested yet. See `ColorFillTransformation`. You can review my commits too: 

- https://github.com/luberda-molinet/FFImageLoading/commit/ea64ddbdf482cefc96d0eb15980394fe0f8ee7c8
- https://github.com/luberda-molinet/FFImageLoading/commit/87c69858b4546d8734968ae40fac4e616d256514

**Comment by AlexanderMelchers** [comment]
Hi Daniel,

Thanks for your feedback! It's good to know that such a feature already exists, even if it's still untested. I'd be happy to test and review your code, but would need to find some time within our development-schedule to do this. I'll let you know when I do...

Best regards,
Alexander.

**Comment by AlexanderMelchers** [comment]
Hey Daniel,

Though it took some time, one of my colleagues tested the `ColorFillTransformation` using FFImageLoading's sample projects yesterday. The transformation seems to work perfectly on iOS and Android and seems to do exactly what we need. I didn't get it to work on UWP because of an issue with MakePri.exe (as described [here](https://stackoverflow.com/questions/45353944/error-file-makepri-exe-not-found)) and haven't checked any other OS, but since iOS and Android are the most pertinent to our situation (and, judging from the commits, the primary versions of the transformation implemented) and these seem to work, I hope this will suffice to include the `ColorFillTransformation` in one of FFImageLoading's next releases.

The only thing we noticed is that the order in which the transformations are applied is important in that the circle transformation doesn't get applied to the color fill if the color fill is not the first transformation in the list. I'm not sure whether this is per design (I've got too little experience with other transformations to know what the default behavior is), but it's certainly not blocking and in a way makes sense - yet is something you should be aware of when applying the transformations...

Is there any indication of when we could expect the transformation to be included? I'm asking since we would like to continue updating your library...

All the best,
Alexander.

**Comment by LeoJHarris** [comment]
@daniel-luberda Will the new transformation be included anytime soon in future release?

**Comment by daniel-luberda** [comment]
It's currently included, so I'll close this.
