### ISSUE TITLE
CachedImage don't rise events

### ISSUE THREAD

**Issue by BullT** [luberda-molinet/FFImageLoading#1065]
Hello,

I'm programin on Xamarin.forms and when I make a new CachedImege, it don't rise any event (Finish, Succes or Error).

This is my code:

```


        private Xamarin.Forms.ImageSource imageSource;
        private CachedImage cachedImage;

            cachedImage = new CachedImage()
            {
                HorizontalOptions = LayoutOptions.Center,
                VerticalOptions = LayoutOptions.Center,
                WidthRequest = 300,
                HeightRequest = 300,
                CacheDuration = TimeSpan.FromDays(30),
                DownsampleToViewSize = true,
                RetryCount = 0,
                RetryDelay = 250,
                Source = this.ImageSource
            };

            cachedImage.Success += OnSuccess;
            cachedImage.Finish += OnFinish;
            cachedImage.Error += onError;

}

        private void onError(object sender, CachedImageEvents.ErrorEventArgs e)
        {
            throw new NotImplementedException();
        }

        private void OnFinish(object sender, CachedImageEvents.FinishEventArgs e)
        {
            throw new NotImplementedException();
        }

        private async void OnSuccess(object sender, CachedImageEvents.SuccessEventArgs e)
        {
            this.ImageArray = await cachedImage.GetImageAsJpgAsync();

            this.IsRunning = false;
            this.IsEnabled = true;
        }
```

How I can to do for rise an event?

Thanks,
XCO

**Comment by daniel-luberda** [comment]
Wrong order: 

- First, set your handlers
- After that set `Source = this.ImageSource` 
- Don't throw any exceptions there! Replace it with `Console.WriteLine`  call.

**Comment by BullT** [comment]
Thanks Daniel,

I'm sorry, maybe I explain wrong (Sorry for my English)

Let me explain what I want do.
I want transform an image an later save as ImageSource.

How can I can save a transformed image to ImageSource (`this.ImageArray = await cachedImage.GetImageAsJpgAsync();`?

When I do that, the app stop.

Thanks.
XCO

**Comment by rredoh** [comment]
I experienced same problem. When is actually Finish and Success called?

**Comment by daniel-luberda** [comment]
It's better to use cross platform API for such cases: 

```C#
ImageService.Instance.LoadUrl("https://....").Transform(new CircleTransformation()).AsJpegAsync()
```

@rredoh See this: https://github.com/luberda-molinet/FFImageLoading/issues/1027
