### ISSUE TITLE
Image scaling issues in ListView Android

### ISSUE THREAD

**Issue by justintoth** [luberda-molinet/FFImageLoading#1066]
### Description

When I first load photos in an Android ListView with the scaleType set to centerCrop, it correctly displays the photos spanning the entire width and height of the row. 

<img width="798" alt="screen shot 2018-07-02 at 12 09 25 pm" src="https://user-images.githubusercontent.com/1443831/42174818-7f5e454c-7df1-11e8-9284-48fef1c1e6a5.png">

However, if I then scroll down so the rows are out of sight and then scroll back up (in which case it uses a cached row), the scaling is removed and it just shows the photos fitting the height but not the width so there are borders on the left and right.

<img width="799" alt="screen shot 2018-07-02 at 12 09 35 pm" src="https://user-images.githubusercontent.com/1443831/42174841-8d61f0e4-7df1-11e8-8cdc-df2b533c9529.png">

That's the first issue... To work around this, I tried setting a CropTransformation with a zoomFactor of 1.0f, which actually makes it scale the image every time. Unfortunately, for some reason the CropTransformation seems to be working incorrectly now and zooms the photos way in regardless of which zoomFactor value I set. With a 1.0f value I would expect no zooming to occur, and yet it zooms the photos way in.

<img width="800" alt="screen shot 2018-07-02 at 11 55 32 am" src="https://user-images.githubusercontent.com/1443831/42174993-0f15f69e-7df2-11e8-931d-56fa1e3ce95d.png">

### Steps to Reproduce

Here is the ImageView that we're loading in the property row:

```
<ImageView
            android:id="@+id/property_row_photo"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop"
            android:src="@drawable/image_loading" />
```

And here is the code that is setting the url of the ImageView every time the row comes into view:

```
public static void SetUrlBitmap (this ImageView imageView, string url, 
            string loadingResource = null) {
            imageView.CacheKey = url;
            ImageService.Instance.LoadUrl (url)
                .CacheKey (url)
                .LoadingPlaceholder (loadingResource, ImageSource.ApplicationBundle)
                .Transform (new CropTransformation (1.0f, 0, 0))
                .Retry (3, 200)
                .Into (imageView);
        }
```

### Expected Behavior

The scaleType of centerCrop should be applied whenever the photo rows come back into view, even if it's reusing a cached ListView row. Also, the CropTransformation zoomFactor should be applied correctly, rather than zooming way in.

### Actual Behavior

The scaleType of centerCrop is applied the first time the ListView row is displayed, but then isn't applied when scrolling back into view. Also, the CropTransformation is zooming the photo in really far even with a default zoomFactor value of 1.0f.

### Basic Information

- Version with issue: v2.4.3.840
- Last known good version: Unknown
- Platform: Xamarin Android

**Comment by justintoth** [comment]
:: Bump ::

**Comment by daniel-luberda** [comment]
@justintoth Could you make a simple repo? It would help to debug it.

**Comment by daniel-luberda** [comment]
BTW: it should be fixed with the latest stable.
