### ISSUE TITLE
ImageService.Instance.LoadFile (File Not Found)

### ISSUE THREAD

**Issue by BullT** [luberda-molinet/FFImageLoading#1067]
### Description

Hi,

Im making an app for xamarin.forms Android and I want load an image from Resource/drawable.
When I run the program apear this error: `System.IO.FileNotFoundException: no_image.png`

### Steps to Reproduce

This is de code:
```
            var noImageStream = await ImageService.Instance.LoadFile("no_image.png")
                                .Transform(new CircleTransformation())
                                .Transform(new GrayscaleTransformation())
                                .AsPNGStreamAsync();
```

### Help

I think that the problem is on path for the image`LoadFile("no_image.png")`.

How can solve this problem?

Thanks,
XCO

**Comment by daniel-luberda** [comment]
@BullT 

`ImageService.Instance.LoadFile` - used for loading files from the disk (full path only). You should use `LoadCompiledResource` (app bundle) or `LoadEmbeddedResource` (net resource)

Cheers.
