### ISSUE TITLE
Synchronous use of ImageLoader (UWP)

### ISSUE THREAD

**Issue by deakjahn** [luberda-molinet/FFImageLoading#1070]
### Description

I'm trying to use it for standalone operation in XF (no CachedImage, just a way to load and downsample an image file on the device, to be passed on to other drawing operations, preferably retained in memory cache for later reuse). Do you think I could use it for this purpose? I have to use it in a sync manner, no `async/await` and `Task.Run()`, the drawing part (actually, SkiaSharp and its canvas) doesn't tolerate that, it leads to thread problems.

### Steps to Reproduce

```
var stream = ImageService.Instance.LoadFile(path)
  .DownSample(256)
  .DownSampleMode(FFImageLoading.Work.InterpolationMode.Medium)
  .ErrorPlaceholder("resource://XXX.Resources.error.png")
  .WithCache(FFImageLoading.Cache.CacheType.Memory)
  .Error((w) => Log.Info("error"))
  .Finish((w) => Log.Info("finish"))
  .Success(() => Log.Info("success"))
  .AsPNGStreamAsync()
  .GetAwaiter()
  .GetResult();
```

### Expected Behavior

Stream returned.

### Actual Behavior

It never returns, without any chance of debugging. Events are never reached.

### Basic Information

- Version with issue: current

**Comment by deakjahn** [comment]
Made more experiments:

```
Log.Info("start " + path);
var stream = await ImageService.Instance.LoadFile(path)
  .DownSample(256)
  .DownSampleMode(FFImageLoading.Work.InterpolationMode.Medium)
  .ErrorPlaceholder("resource://XXX.Resources.error.png")
  .WithCache(FFImageLoading.Cache.CacheType.Memory)
  .Error((w) => Log.Info("error " + w.Message))
  .Finish((w) => Log.Info("finish"))
  .Success(() => Log.Info("success"))
  .AsPNGStreamAsync();
Log.Info("stream");

Log.Info("draw " + path);
//...
Log.Info("end " + path);
```

The verbose FF log:

```
- start _8164252.JPG
- start _8164254.JPG
- start _8164255.JPG
- start _8164257.JPG
- Generating/retrieving image: image1.JPG;256x0
- Generating/retrieving image: image2.JPG;256x0
- success
- finish
- success
- finish
- Generating/retrieving image: image3.JPG;256x0
- Generating/retrieving image: image4.JPG;256x0
- stream
- draw image1.JPG
```

So, it's obvious now that this `AsPNGStreamAsync()` doesn't do what I expect it to do according to the documentation. I can't wait for the image to come back completely this way. All four images are started asynchronously and by the time I finally get the first one and start to actually use (`draw` in the log), the sync is long gone.

**Comment by daniel-luberda** [comment]
Synchronous usage of async apis is always risky as may lead to deadlocks which are really not easy to debug. I'll close this one as FFImageLoading's API's are async.

**Comment by deakjahn** [comment]
Oh, that was a long time ago. I probably solved it back then but I don't remember any more. :-) Probably launching it on another thread and specifying a continuation.
