### ISSUE TITLE
[help wanted] What the default duration of cache? 30days?

### ISSUE THREAD

**Issue by JTOne123** [luberda-molinet/FFImageLoading#1073]
Very stupid question

I'm using default XF.CachedImage in XAML **without** CacheDuration and load my images from the web.
My website sets max-age is 1 day

What the default cache duration in this case?

```
                        if (!parameters.CacheDuration.HasValue && Configuration.TryToReadDiskCacheDurationFromHttpHeaders
                            && response.Headers?.CacheControl?.MaxAge != null)
                        {
                            downloadInformation.CacheValidity = response.Headers.CacheControl.MaxAge.Value;
                        }
```

According to this is should be 1 day, because TryToReadDiskCacheDurationFromHttpHeaders is true by default.

**This is very confused me DiskCacheDuration = TimeSpan.FromDays(30d);**

**Comment by daniel-luberda** [comment]
Hi @JTOne123,

`TryToReadDiskCacheDurationFromHttpHeaders` is configurable  - enabled by default

Logic is:

- If custom cache duration is set, it will be used primarily. 
- If not then: If `TryToReadDiskCacheDurationFromHttpHeaders` it will use disk cache duration from server response.
- If not then: default disk cache duration is used (it's also configurable)

**Comment by JTOne123** [comment]
thanks
