### ISSUE TITLE
Initialize failed on Xamarin.Forms Android

### ISSUE THREAD

**Issue by KokomiShiina** [luberda-molinet/FFImageLoading#1077]
### Description
Run time error thrown on Android device using the Latest version of FFImageLoading.
Tested on Android 4.4 (API 19) and Android 8.0 (API 26) both is reproducible.

The project is created right away using Visual Studio Xamarin Forms portable project template.

```
Method `FFImageLoading.Forms.CachedImage.set_IsRendererInitialized(bool)' is inaccessible from method `FFImageLoading.Forms.Platform.CachedImageRenderer.Init(System.Nullable`1<bool>)'
```
### Expected Behavior

App starts.

### Actual Behavior

App crashes

### Basic Information

- Version with issue: 2.4.3.840
- Last known good version: 2.3.6
- Platform: Xamarin.Forms 3.1.0.63723 (Android)

### Reproduction Link / Code
*MainActivity.cs* (Android project)
```C#
protected override void OnCreate (Bundle bundle)
{
    Instance = this;

    TabLayoutResource = Resource.Layout.Tabbar;
    ToolbarResource = Resource.Layout.Toolbar; 

    base.OnCreate (bundle);
    this.SetTheme(Resource.Style.Theme_Design_Light);
    FFImageLoading.Forms.Platform.CachedImageRenderer.Init(false);

    global::Xamarin.Forms.Forms.Init (this, bundle);
    LoadApplication (new Foobar.App ());
}
```

**Comment by daniel-luberda** [comment]
- Make sure you have the **same** FFImageLoading version installed in **all** your projects
- Remove all `bin`/`obj` folders then rebuild.

**Comment by KokomiShiina** [comment]
Thanks @daniel-luberda ,
For most cases after updating library, I did Clean/Rebuild and it will work.
But this actually requires removing `bin/obj`. Problem solved
