### ISSUE TITLE
Mac: Failed to resolve "WebP.Mac.WebPCodec"

### ISSUE THREAD

**Issue by Papirosnik** [luberda-molinet/FFImageLoading#1078]
### Description

I'm going to use this excellent plugin in my cross-platform Xamarin Forms project for colortinted images.
I've added current stable versions of  Xamarin.FFImageLoading.Forms and Xamarin.FFImageLoading.Transformations from nuget.org.
Unfortunately, I can't build my project because of:

MMP: Error MM2002: Failed to resolve "WebP.Mac.WebPCodec" reference from "WebP.Mac, Version=1.0.6628.22309, Culture=neutral, PublicKeyToken=null" (MM2002)

In Debug I see launched app but then it immediately crashes:

Could not find `WebP.Mac` referenced by assembly `FFImageLoading.Platform, Version=2.4.3.840, Culture=neutral, PublicKeyToken=null`.
Could not find `WebP.Mac` referenced by assembly `FFImageLoading.Forms, Version=2.4.3.840, Culture=neutral, PublicKeyToken=null`.
Could not find `WebP.Mac` referenced by assembly `FFImageLoading.Forms.Platform, Version=2.4.3.840, Culture=neutral, PublicKeyToken=null`.

### Steps to Reproduce

Just try to use CachedImage with Xamarin.FFImageLoading.Transformations in Xamarin Forms on Mac

### Basic Information

- Version with issue: 2.4.3.840
- Last known good version: unknown
- Platform: Xamarin Forms 3.1.0 for Mac, in any Debug/Release x86/x64 modes

**Comment by daniel-luberda** [comment]
Hi @Papirosnik,

Are you sure you have WebP and FFImageLoading packages installed in platform specific project?

**Comment by Papirosnik** [comment]
Hi!
I'm not sure I should have WebP installed separately.
At least I didn't install it on any other platform (ios, android, uwp) and all looks working properly (despite on other bugs :).

**Comment by daniel-luberda** [comment]
It should be installed automatically as it's a package dependency: https://github.com/luberda-molinet/FFImageLoading/blob/master/nuget/Xamarin.FFImageLoading.nuspec#L49

Could you mention other bugs? Thanks :)
