### ISSUE TITLE
FFImage no longer available in UWP version.

### ISSUE THREAD

**Issue by Pinox** [luberda-molinet/FFImageLoading#1081]
In latest version of  FFImageLoading (2.4.3.840)   for native Windows UWP I get the following error:

![ffloading](https://user-images.githubusercontent.com/5297255/43039121-26015986-8d27-11e8-94a0-5a9d71a97da5.PNG)

Is FFImage deprecated or am I missing something.  It used to work in previous version ( 2.3.6). What should I use instead ?

Pointers in the right direction will be appreciated.

Thanks.

**Comment by daniel-luberda** [comment]
There's a much better control now, which is MVVMCross compatible. `MvxCachedImageView`

Cheers.

**Comment by Pinox** [comment]
@daniel-luberda  awesome.  Thanks again.

**Comment by Pinox** [comment]
Hi @daniel-luberda  ,  

I tried the MvxCachedImageView as per recommendation but it I can't get it to work. It throws an error:

![ffloading](https://user-images.githubusercontent.com/5297255/43049800-231b9146-8dfe-11e8-8d0a-d7060f4132d4.PNG)


Please find attached repo in UWP that throws:
[Testing_FFLoading.zip](https://github.com/luberda-molinet/FFImageLoading/files/2217353/Testing_FFLoading.zip)

**Comment by hirosato223** [comment]
@Pinox I'm currently seeing the same XamlParseException + ImagePath in my windows project... do you remember how you resolved this?

**Comment by Pinox** [comment]
@hirosato223  I gave up on this.  Tried a couple times to get help. Even bought the author a coffee. No luck.  The problem is the samples are so out of date that everything in this project creates an enormous amount of friction in figuring out how things work. Feel free to open issue, I closed it in frustration.
