### ISSUE TITLE
Retrieve image from URL cache with parameters and "%2F".

### ISSUE THREAD

**Issue by dblookup** [luberda-molinet/FFImageLoading#1083]
Please, FFImageloading is not retrieving offline image from URL cache with parameters, like URLs from Firebase Storage. Please, see the url below:

https://firebasestorage.googleapis.com/v0/b/test-6bd62.appspot.com/o/photos%2Fphoto.jpg?alt=media&token=27a7c60d-23a5-4025-a003-23b852c7dc33

Please, is there any outline solution for it?

Thank you so much

**Comment by daniel-luberda** [comment]
Hi @dblookup 

On which platform do you experience this issue?

**Comment by dblookup** [comment]
Hi Daniel,

Thank you for your reply. So far I've tested on Android (phone) and iOS (ipad).
Please find attached a project example.
[ImageURLTest.zip](https://github.com/luberda-molinet/FFImageLoading/files/2226988/ImageURLTest.zip)

Steps to Reproduce
1) With online device, open the app (you can see the image normally).
2) Close app.
3) Turn off the wi-fi and open the app again (the ffimageloading doesn't retrieve the image).

Thank you again

**Comment by dblookup** [comment]
Hi Daniel,

I identified the issue. It is in the image's httpheader with MaxAge=0. I setted the configuration parameter "TryToReadDiskCacheDurationFromHttpHeaders = false" and it worked.

I saw in the code that you check if it is different from null but not different from zero. I do not know if this is correct, but anyway problem solved.

Thank you for your assistance.

**Comment by kormemis** [comment]
@dblookup 
hello , did you change "TryToReadDiskCacheDurationFromHttpHeaders = false" on source or change in  code ? 

I wrote the code in cs code behind page as 
`FFImageLoading.Config.Configuration.Default.TryToReadDiskCacheDurationFromHttpHeaders = false;`

but firebase storage images still not cached.
