### ISSUE TITLE
Aspect Fill Problem

### ISSUE THREAD

**Issue by patsadow2** [luberda-molinet/FFImageLoading#1086]
Is there any way in (Android) to cut the image to fit the size of field when (aspect fill) ? 

```
      <forms1:CachedImage Aspect="AspectFill" HeightRequest="100" WidthRequest="100"
                                                    Source="{Binding Image}" />

```
For example to fill boundary 100x100 when i have image 1900x 1000 and 1000x 1900, instead i get always 120x100 or 100x120 or something like that. :(

**Comment by taublast** [comment]
Include your image inside a contentview with a 100 HeightRequest constraint, the image inside wont outpass it.
