### ISSUE TITLE
Check internet connection trying to download image.

### ISSUE THREAD

**Issue by eamiguinho** [luberda-molinet/FFImageLoading#1088]
I was testing scrolling through a listview on Xamarin.Android and adding Loading Placeholder, Error Placeholder and LoadUrl could make it quite slow on older devices, so I remove the LoadingPlaceholder and works way better, but the only problem is the time it takes (timeout time) for the ErrorPlaceholder to show up, which can make it a weird experience. Can we pass a boolean with connection status and if not connected, don't wait for the timeout if the image isn't cached? 

This might be something that's already implemented but I can't see any docs about it.

Thanks

**Comment by EmilAlipiev** [comment]
loadingplaceholder painful. i just founded that embedded svg images are not loading if connection is very slow and i use loadingplaceholder
