### ISSUE TITLE
CachedImageRenderer Init error Xamarin.Forms.Droid v3.1.637273

### ISSUE THREAD

**Issue by juanagu** [luberda-molinet/FFImageLoading#1091]
### Description
I updated Xamarin.Forms and CachedImageRenderer does not work with Xamarin.Forms v 3.1.637273 on Android. Works fine on iOS.

### Steps to Reproduce
Initialize in MainActivity the FfImageLoading library:

```
using FFImageLoading.Forms.Platform;
....
protected override void OnCreate(Bundle bundle)
{
base.OnCreate(bundle);
...
CachedImageRenderer.Init(true);
...
global::Xamarin.Forms.Forms.Init(this, bundle);
}
```

In MainPage.xaml: 

```
xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
    xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
    xmlns:fftransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
...
<ffimageloadingsvg:SvgCachedImage >
                        <ffimageloading:CachedImage.Transformations>
                            <fftransformations:TintTransformation HexColor="#ffffffff" EnableSolidColor="true" />
                        </ffimageloading:CachedImage.Transformations>
                    </ffimageloadingsvg:SvgCachedImage>
```

### Expected Behavior
Show MainPage and CacheImage  

### Actual Behavior
<img width="900" alt="screen shot 2018-07-31 at 16 04 21" src="https://user-images.githubusercontent.com/4689126/43481115-6c74651e-94db-11e8-9065-e02d32a33f93.png">

### Basic Information

- Version with issue: v2.4.2.840 and Xamarin.Forms  v3.1.637273  
- Platform: Android

**Comment by daniel-luberda** [comment]
- Make sure you have installed FFImageLoading packages in **all** projects
- Remove all `bin`/`obj` folders then rebuild
