### ISSUE TITLE
Can I preview the downloaded or selected image from gallery

### ISSUE THREAD

**Issue by pritish5** [luberda-molinet/FFImageLoading#1092]
I am downloading the images from the server or from photo galley and loading it to `ffimageloading`. In Xamarin forms
         
```
<StackLayout>
      <flv:FlowListView FlowColumnCount="3" x:Name="listItems" 
	SeparatorVisibility="None" HasUnevenRows="false" RowHeight="100" >
            <flv:FlowListView.FlowColumnTemplate >
                <DataTemplate >
                       <ffimageloading:CachedImage DownsampleToViewSize="true" AbsoluteLayout.LayoutFlags="All" HeightRequest="100" AbsoluteLayout.LayoutBounds="0,0,1,1" Source="{Binding .}" Aspect="AspectFill" HorizontalOptions="FillAndExpand">
                       </ffimageloading:CachedImage>
                   </DataTemplate>
                 </flv:FlowListView.FlowColumnTemplate>
             </flv:FlowListView>
</StackLayout>
```

It showing me downloaded images as well as attached images from gallery into `ffimageloading` perfectly. Can I choose/Select that 1 by 1 image from `ffimageloading` to see the preview. Is there any property so that I can select an image and preview it?

**Comment by daniel-luberda** [comment]
Hi @pritish5,

Could you write more details what you want to achieve? I'm not sure if I understood it correctly.
