### ISSUE TITLE
Image loading Failed in Xamarin Forms Android

### ISSUE THREAD

**Issue by xapptree** [luberda-molinet/FFImageLoading#1094]
### Description

Issue with Image loading in Xamarin forms Android, before it works well but now it is not working and throwing 
FFImageLoading.DownloadAggregateException: One or more errors occurred. ---> System.Exception: HttpHeadersTimeout
  at FFImageLoading.Cache.DownloadCache+<DownloadAsync>d__17.MoveNext () [0x007d7] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:199 
--- End of stack trace from previous location where exception was thrown ---

Please help me out of this.

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform:

**Comment by daniel-luberda** [comment]
Hi @xapptree,

Exception is self explanatory: `HttpHeadersTimeout` - you probably have some connections issues.

**Comment by xapptree** [comment]
Hi,
I resolved this issue by setting TSL1.2 in Xamarin forms Android settings.

Thanks,
AKBAR.
