### ISSUE TITLE
Using SvgCachedImage do not load SVG resource inside pin markers before 200 milliseconds 

### ISSUE THREAD

**Issue by wilkerfoureaux** [luberda-molinet/FFImageLoading#1100]
### Description

We are using SvgCachedImage to load SVG resources inside pin markers in Xamarin.Forms.GoogleMaps map and everything goes well only after 200 milliseconds from the same resources. Each new resource goes through the same scenario. So, the pins added before this time do not show the svg resource but if the map is called again, all the resources (now cached) are displayed.

### Steps to Reproduce

(xamarin)
1. Create a view with GoogleMaps map.
2. In the map class creation.
3. Put random customView pins from the <FFImageLoading:SvgCachedImage ... svg> in the XAML.

### Expected Behavior

All pins shown in the map. SVGs loaded before <= 200 milliseconds.

### Actual Behavior

SVGs are not displayed before <= 200 milliseconds;

### Basic Information

- Version with issue: 2.4.3.840 (Xamarin.FFImageLoading.Svg.Forms)
- Last known good version: N/D
- Platform: Android & iOS (Xamarin)

### Screenshots

N/I

### Reproduction Link / Code

N/I

**Comment by wilkerfoureaux** [comment]
Hello, any clue to this problem?

**Comment by daniel-luberda** [comment]
Hi @wilkerfoureaux, sorry for a late response. **Many** issues are fixed now in recent stable. It should also load images faster. It's not easy to help you without any sample project attached. Could you test the newest stable? Or at least provide some sample code?
