### ISSUE TITLE
Cached gif disappear in Carousel View

### ISSUE THREAD

**Issue by EmmanuelJego** [luberda-molinet/FFImageLoading#1102]
### Description

Hello!
I'm currently using a carousel view (Xamarin.Forms.CarouselView) in which I display a cached gif or image on each view. 
It works great, but if I swipe at least twice in the same direction (let's say to the right), and then go back to my previous pisition (ex : 1st page, I swipe to the 3rd one, and then go back to the 1st one), the gif has disappeared. 
The problem doesn't show if it's a cached image or a simple image, just with gifs.

I believe it happens because the carousel view keeps only the content of the current view and the two ones on its sides (right and left), so when I want to go back to a previous view, the gif has been disposed.

I am right? Do you know how could I solve this issue?
Thanks for your help!

### Basic Information

- Version with issue: 2.4.3.840

**Comment by daniel-luberda** [comment]
Hi @EmmanuelJego 

Could you make a simple repo, so I could reproduce it?

**Comment by EmmanuelJego** [comment]
Hi @daniel-luberda 

I have created a repo : https://github.com/EmmanuelJego/GifCarouselView

As explained in the README, the first and last GIFs don't seem to be affected in this sample. In my real project, the first and last GIFs disappear as well.

PS : to make it "work", I have to make the gif's source null and then back to the initial source, when I detect a swipe: 
`cachedImage.Source = null; cachedImage.Source = VM.SourceResource;`

**Comment by thearaks** [comment]
Setting CacheType="None" solves the issue, but it's not a viable solution.
Also, when the GIF is playing, the timing between the frames is not right: the animation is super-fast.
Please take a look at the GIF support on Android, it's broken, it was working fine on 2.2.25.
Thank you!

**Comment by claudiocleberson** [comment]
Hi, I face the same problem, on a listview the gif disappears if you scroll up and down. A workaround I found was override the OnAppearing on the cell.

 protected override void OnAppearing()
        {
            base.OnAppearing();

            var item = BindingContext as ChatMessages;
            gifImage.Source = item?.Attachement?.AttachementUrl;
            gifImage.WidthRequest = (double)item?.Attachement?.Width;
            gifImage.HeightRequest = (double)item?.Attachement?.Height;

        }

**Comment by wcfCode** [comment]
Hope to solve as soon as possible   @daniel-luberda

**Comment by daniel-luberda** [comment]
It should be fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/2d5a086e8dadb98f1e1f273a5e83f1ad22475bcf and https://github.com/luberda-molinet/FFImageLoading/commit/2276596d4918c96edc2ec07c6bfa1f7adcf9efaf

**Comment by daniel-luberda** [comment]
Please reopen if you still experience it. Android GIF issue is now fixed. Cheers.

**Comment by HugoTruffe** [comment]
Hi:

I am using the version 2.4.11.982 and I have the same problem in Android 6.0 api 23 (Xamarin.Forms 4.1)

**Comment by HugoTruffe** [comment]
I need to show a carousel view with 4 views (pages) where there is a gif on each page. 

The two first is ok but the two last the gif is not show
