### ISSUE TITLE
Xamarin Android - problem with gatting Bitmap from SVG

### ISSUE THREAD

**Issue by Alcuno** [luberda-molinet/FFImageLoading#1103]
### Description

Hello I am trying to use FFImageLoading in project for loading SVGs into bitmpas.
So a noob issue...
Xamarin project (Android + iOS):
- Xamarin.FFImageLoading 2.3.6
- Xamarin.FFImageLoading.SVG 2.3.6

Code is in Reproduction Link / Code

Thanks for reply...

### Steps to Reproduce

1) I tried to set heigth to 0. I get the exception, but thread was not finalized...
2) I tried to set height and width to 64, no error, but thread was not finalized...

### Basic Information

- Version with issue: Xamarin.FFImageLoading.SVG 2.3.6

### Reproduction Link / Code
```C#
public async static Task<Drawable> PreloadtImage(string name, int height, int width)
 {
         var svgString = @"<svg><rect width=""30"" height=""30"" style=""fill:blue"" /></svg>";
         return await ImageService.Instance.LoadString(svgString).WithCustomDataResolver(new SvgDataResolver(height, width, true)).AsBitmapDrawableAsync();
}

public static Drawable GetImage(string name, int height, int width)
{
         var dpHeight = GetDipValue(height);
         var dpWidth = GetDipValue(width);

         return PreloadtImage(name, dpHeight, dpWidth).Result;
}

```

**Comment by daniel-luberda** [comment]
2.3.6 is old and unsupported, did you try newest 2.4.4?
