### ISSUE TITLE
Xamarin iOS - Invisible SVG objects are visible in app

### ISSUE THREAD

**Issue by Stensan** [luberda-molinet/FFImageLoading#1104]
Hi, I have a SVG with two text objects. The first one is visible with display:inline and the second one is invisible with display:none, so this shouldn't be rendered. I work with Inkscape and there the objects are shown right. But if I use FFImageLoading in my iOS Xamarin Forms app both objects are visible instead of only the first one. Sorry if I don't describe this correctly, I am new to SVG. Please find my test project attached.
[TestSVG.zip](https://github.com/luberda-molinet/FFImageLoading/files/2297593/TestSVG.zip)

**Comment by daniel-luberda** [comment]
Fixed :)

**Comment by Stensan** [comment]
It seems this is not yet fixed in the latest version 2.4.5. Could you please test this again?

**Comment by daniel-luberda** [comment]
Please attach a sample SVG file so I could debug it.

**Comment by Stensan** [comment]
Please find my test project with the SVG file attached in my first comment

**Comment by daniel-luberda** [comment]
Fixed
