### ISSUE TITLE
How to load SVG image in Toolbar menu item?

### ISSUE THREAD

**Issue by ruchiverma6** [luberda-molinet/FFImageLoading#1105]
### Description

I need to show SVG image icon in tool bar menu item. Suppose I need to add search icon in svg format at top right corner of screen in ToolBar.
How can I achieve this?

Please help.

**Comment by mateuswolkmer** [comment]
The issue seemed to be resolver in the latest Xamarin update. Is it possible to use SVGs as a ToolbarItem now?

**Comment by daniel-luberda** [comment]
@mateuswolkmer  Try `SvgImageSource` as a source

**Comment by mateuswolkmer** [comment]
Now there is `IconImageSource` in the `ToolbarItem` class, replacing just the `Icon `property, but I'm having a hard time pointing it to my EmbeddedResource SVG.

**Comment by mateuswolkmer** [comment]
Ok, so I got it to use the SVG as source, but the icon is really small still (I thought that by using SVG as source it would actually display a bigger icon). Is there a way to make the icons bigger? Note how the icons in the right are way smaller than the Hamburguer icon on the left.

![61611610_2329509377322252_3869407101495279616_n](https://user-images.githubusercontent.com/20559356/58579578-c9a3d600-8221-11e9-8f95-db6b5bd048d7.png)

**Comment by daniel-luberda** [comment]
`SvgImageSource` has sizes in constructor. Did you try it?

**Comment by mateuswolkmer** [comment]
Couldn't get it to work, the icon defaults to its text whenever trying to use SvgImageSource. The only way I got it to work is by just passing a string of the EmbeddedResource SVG name, but then it downsizes the icon. If you could provide a code sample of creating a ToolbarItem with a SVG as ImageSource I would appreciate it.

**Comment by mateuswolkmer** [comment]
Ok, so it seems that iOS devices don't even render the SVG in the toolbar, so it is not usable at the moment anyway.

**Comment by simon10says** [comment]
Hi @mateuswolkmer , could you show the code fragment how to get it working with embedded svg? I've tried:
```c#
var resources = typeof(BindableToolbarItem).Assembly.GetManifestResourceStream("App.Assets.home.svg");
string content;
using (var reader = new StreamReader(resources))
{
     content = reader.ReadToEnd();
}
var tmp = SvgImageSource.FromSvgString(content, vectorWidth: 35, vectorHeight: 35);
IconImageSource = tmp.ImageSource;
```
The `content` is populated witht the `<svg>`, but It's not showing anything.

**Comment by mateuswolkmer** [comment]
@simon10says Just reference a _.svg_ file as the `IconImageSource` on a `ToolbarItem` constructor and have the file placed in the platforms resources:
```
ToolbarItems.Add(new ToolbarItem
{
    IconImageSource = "flag.svg",
    Text = "Flag Icon",
    Order = ToolbarItemOrder.Primary
});
```

**Comment by grayter1** [comment]
@mateuswolkmer "Ok, so I got it to use the SVG as source, but the icon is really small" - can you explain how you managed to do this? I cannot force my app to use svg

**Comment by mateuswolkmer** [comment]
@grayter1 
> @simon10says Just reference a _.svg_ file as the `IconImageSource` on a `ToolbarItem` constructor and have the file placed in the platforms resources:
> 
> ```
> ToolbarItems.Add(new ToolbarItem
> {
>     IconImageSource = "flag.svg",
>     Text = "Flag Icon",
>     Order = ToolbarItemOrder.Primary
> });
> ```

**Comment by grayter1** [comment]
I can read and I saw that... :) but it is not working so I ask how you do it. Platform resources means folder Resources or dictionary? Neither works for me.

**Comment by mateuswolkmer** [comment]
@grayter1 For Android its the "Assets" folder, and in iOS its the "Resources" folder, just place the svg there and it should be available to be referenced. Although, as I mentioned before, this didn't work in iOS, the svg is just not rendered, but in Android it worked fine (with the exception that the rendered icon was very small and I couldn't get it to render in a bigger size still).

**Comment by EmilAlipiev** [comment]
> @grayter1 For Android its the "Assets" folder, and in iOS its the "Resources" folder, just place the svg there and it should be available to be referenced. Although, as I mentioned before, this didn't work in iOS, the svg is just not rendered, but in Android it worked fine (with the exception that the rendered icon was very small and I couldn't get it to render in a bigger size still).

does it work for uwp also? are you using shell? because it doesnt work for me as well :(

**Comment by wagesj45** [comment]
@grayter1 Yeah it isn't working for me either.

**Comment by NLitvinenko** [comment]
This is still not working :) Wondering why there are so many closed issues, that aren't yet fixed
