### ISSUE TITLE
URL source used to work in older version

### ISSUE THREAD

**Issue by helzgate** [luberda-molinet/FFImageLoading#1106]
### Description

These images in this format: `http://eaccess.smpcorp.com/CustomImageHandler/SimpleImageHandler.ashx?p1=Bulk%3DRU684S%3BZoomFactor%3D1.30%3BImageName%3Dru684s_1.jpg%3BDivision%3DEMD%3BType%3DText%3BMark%3D` used to work in an older version of FFImageLoading which was version 2.2.9 without using a converter.  These URL's no longer work in the newer version 2.4.3.840.  Even though they still work fine in a regular `<Image></Image>` tag.  Any ideas what is going on?

### Basic Information

- Version with issue: 2.4.3.840
- Last known good version: 2.2.9
- Platform: UWP & Android (haven't tested iOS)
- Xamarin Forms: 3.1.0.697729
- NetStandard Library: 2.0.3

**Comment by VladimirMoiseenko** [comment]
Daniel,
I had issues with loading images when URL did not end with some extension, like *.jpg. It seems that your cache system expects such extensions. When I changed my client & server logic to work with extension, it has begun to work correctly.

**Comment by daniel-luberda** [comment]
@helzgate Server responds with incorrect content type `text/html`
