### ISSUE TITLE
SVG image with <clipPath> doesn't load

### ISSUE THREAD

**Issue by khadeeja-alif** [luberda-molinet/FFImageLoading#1108]
When I add this SVG to my view,  it doesn't show up 

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 64 74.462"><defs><style>.a,.c{fill:#727272;}.a{stroke:#707070;}.b{opacity:0.8;clip-path:url(#a);}</style><clipPath id="a"><rect class="a" width="64" height="74.462" transform="translate(854 908)"/></clipPath></defs><g class="b" transform="translate(-854 -908)"><path class="c" d="M32.088,42.051H3.575S-14.886,22.359,32.088,0C79.063,22.359,60.6,42.051,60.6,42.051Z" transform="translate(853.912 907.796)"/><path class="c" d="M56.615,69.539H0V0H56.615V69.539ZM9.231,20.923V56H47.385V20.923h-.051a18.933,18.933,0,0,0-3.754-6.531c-3.491-4.283-8.629-8.3-15.272-11.931-6.642,3.633-11.781,7.648-15.272,11.931a18.965,18.965,0,0,0-3.755,6.531Z" transform="translate(857.692 954.77)"/></g></svg>`

Seems like an issue with `<clipPath>` Did see issues on clipPath parsing for SkiaSharp.
But is there any workaround to solve this Issue?

**Comment by assemhakmeh** [comment]
I submitted a pull request that would solve this issue. The workaround for now is to set the clip-path attribute on the element instead of in css (class and style attribute won't work).

**Comment by daniel-luberda** [comment]
PR is merged now, new release soon (thanks @assemhakmeh)
