### ISSUE TITLE
How to hide default action sheet while downloading Image from DB

### ISSUE THREAD

**Issue by pritish5** [luberda-molinet/FFImageLoading#1111]
Hi 

I am loading images from SQL Server Database into 

`listItemsPhotos.FlowItemsSource = _downloaded`

![ffimage1](https://user-images.githubusercontent.com/2580866/45292822-04d76b00-b514-11e8-9054-0627f4ac3e7a.png)

every thing is working fine but I am facing one issue that while downloaded image I save it into phone memory and once it downloaded it display its defalut system action sheet how can I hide this action sheet.  FYI I am attaching the image here I am facing problem.
![ffimage](https://user-images.githubusercontent.com/2580866/45292869-246e9380-b514-11e8-9b7f-dd6ca043d2ae.png)
So How Can I hide this?

**Comment by pritish5** [comment]
@any one waiting for reply

**Comment by pritish5** [comment]
@daniel-luberda please reply for this I am stuck here!!!!!

**Comment by daniel-luberda** [comment]
@pritish5  It's not an FFImageLoading related issue. Read this: https://blog.xamarin.com/simple-cross-platform-file-io-for-ios-android-and-windows/
