### ISSUE TITLE
Binding BorderHexColor of CircleTransformation error

### ISSUE THREAD

**Issue by denizz-ryzhkov** [luberda-molinet/FFImageLoading#1112]
### Description

Compilation error when try to use binding with BorderHexColor of CircleTransformation.
Error: No property, bindable property, or event found for 'BorderHexColor', or mismatching type between value and property. 

Tried to bind BindableProperty of string type

### Basic Information

- Version with issue: 2.4.3.840

**Comment by devopsone** [comment]
It would be great if the properties could be bindable. I also miss that.

**Comment by daniel-luberda** [comment]
Currently, transformations are not bindable but it's on our todo list. #860
