### ISSUE TITLE
Firebase Storage Images cannot be Cached

### ISSUE THREAD

**Issue by kormemis** [luberda-molinet/FFImageLoading#1113]
### Description

I have a xamarin ios project works with DLtoolkit which is used FFImageLoading, firebase storage images cannot not be cached. how can I solve it ?
link example : https://firebasestorage.googleapis.com/v0/b/rinohub.appspot.com/o/receipts%2Ftest%2F5b462211ae298b08f496f128.jpeg?alt=media&token=22a297e0-d71f-4184-9fbd-31c65958d740

- Version with issue: 2.4.3.840
- Platform: xamarin.forms

**Comment by EmilAlipiev** [comment]
how is that related to this library? you have set your images non public.

**Comment by kormemis** [comment]
I meant the images fetched from firabase was not cached and I found the solution , I put this code to `App.cs` after `initializecomponent();`  as described in issue #1083 

```
var config = new FFImageLoading.Config.Configuration
            {
                TryToReadDiskCacheDurationFromHttpHeaders = false
            };
            ImageService.Instance.Initialize(config);
```

**Comment by EmilAlipiev** [comment]
i am curious something why are you trying to cache with token=22a297e0-d71f-4184-9fbd-31c65958d740
I think that you can access it using without token also. is there any reason that you cache it with token?

**Comment by kormemis** [comment]
it is because of that if authentiaction options is set for e-mail and password , you can not access the image without the token. firebase stores images with tokens. no any other option

**Comment by EmilAlipiev** [comment]
"you can not access the image without the token. firebase stores images with tokens. no any other option".. this is not correct, you can access images without token if you set up. https://stackoverflow.com/questions/46153828/access-url-without-token-in-firebase-storage?rq=1

but I guess that your purpose is different. you want your images to be private i believe.

**Comment by Lapinou42** [comment]
2 days to try to find a solution, but image from FireBase could not be cached... Event if with your solution...
