### ISSUE TITLE
CachedImage.GetImageAsJpgAsync => 

### ISSUE THREAD

**Issue by vd3d** [luberda-molinet/FFImageLoading#1114]
When calling CachedImage.GetImageAsJpgAsync() I got a NullPointerException, but I don't know why !

I have also try this :

Device.BeginInvokeOnMainThread(async () =>
            {
                var imageBuffer = await filterImage.GetImageAsJpgAsync();   
            });

But it doesn't help !

Any idea of the issue ? How to solve it ?

Thanks for your help

**Comment by vd3d** [comment]
BTW, I have also test the code from (copy/paste in my own project) :

\samples\FFImageLoading-master\FFImageLoading-master\samples\Simple.TizenForms.Sample\Forms\GetImageTestPage.cs

But I got the same problem !

I have try to build FFImage but I got several compilation issues, I use VS2017 Pro.
Is there some special settings to build it ?

Maybe I can debug the issue to help ?

**Comment by ThallisonRhanniel** [comment]
You should get the JPG image inside the '' sucess '' event
Example: filterImage.Success += filterImage_Success;

private async void filterImage_Success(object sender, CachedImageEvents.SuccessEventArgs e)
{
      var imageBuffer = await filterImage.GetImageAsJpgAsync();
}

**Comment by daniel-luberda** [comment]
Exactly as  @ThallisonRhanniel explained (thanks)
