### ISSUE TITLE
Running Xunit tests with visual studio runner

### ISSUE THREAD

**Issue by rlasker3** [luberda-molinet/FFImageLoading#1115]
I am using Xunit and the Xunit Visual Studio Runner causes the SvgCachedImage to throw an error that says : "You are referencing the Portable version in your App - you need to reference the platform version". I've tried adding references to different NuGet packages that you offer but none of them seem to work.

This error gets throw any time that I instantiate a new ContentPage in my unit tests that has the SvgCachedImage object in the Xaml. Is it possible to run FFImageLoading in Unit Tests in Visual Studio?

In my unit test runner project I am referencing: Xamarin.FFImageLoading.Svg (2.4.3.840), xunit (2.4.0) & xunit.runner.visualstudio (2.4.0)

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/wiki/Unit-Testing----how-to-enable
