### ISSUE TITLE
MvxCachedImageView 

### ISSUE THREAD

**Issue by Pinox** [luberda-molinet/FFImageLoading#1117]
Hi ,

Can someone plse help me here,  how  do I bind a url to MvxCachedImageView.

If I use in XAML :    ImagePath="http://www.pngall.com/wp-content/uploads/2016/05/Ferrari-Download-PNG.png"   then I get an error in UWP native app.

"Image" property does not except a string in MvxCachedImageView so that is not an option.

So , to what property do I bind then using a string url ?

**Comment by daniel-luberda** [comment]
You should use `ImagePath` property: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Windows/Views/MvxCachedImageView.cs#L142-L149

**Comment by Pinox** [comment]
Hi Daniel, 

Thanks for the reply.  In UWP FFImage then it works eg: 

   
        <ff:FFImage 
            Width="500"
            Height="500"
            Source="https://static.formula1.ferrari.com/imgresize-   cache/edfc43fa15f02a4ed751742f6dbddca5.jpg"
            />

If I use Image path , it's not working:

  
        <ff:MvxCachedImageView 
               Height="500"
               Width="500"
              ImagePath="https://static.formula1.ferrari.com/imgresize-cache/edfc43fa15f02a4ed751742f6dbddca5.jpg"
            />

Therefor my enquiry.
