### ISSUE TITLE
Incorrect rendering with transform="translate..." option

### ISSUE THREAD

**Issue by Saratsin** [luberda-molinet/FFImageLoading#1120]
### Description

transfortm="translate..." option not clearing x, y values after exiting the group node

### Steps to Reproduce

Create svg similar to this:
```
...
<g ... transform="translate(x, y)">
    ....
</g>
<g ... transform="translate(0, 2)">
   ...
</g>
...
```

And try to render it.

### Expected Behavior

First group render everything taking x and y as zero points of coordinates.
Second group render everything taking 0 and 2 as zero points of coordinates.

### Actual Behavior

First group will render everything taking x and y as zero points of coordinates.
Second group takes x+0 and y+2 as well
(not clearing old values).
As result, rendering is not correct.

### Basic Information

- Version with issue: 2.4.3.840 (FFImageLoading.Svg)
- Last known good version: n/a
- Platform: Android, iOS

### Screenshots

**Original look**
<img src="https://user-images.githubusercontent.com/16039381/45919432-a9a36200-be9d-11e8-9bb5-55c5d95f0517.png"  width="450" />

iOS | Android
:---------:|:---------:
<img src="https://user-images.githubusercontent.com/16039381/45919396-3c8fcc80-be9d-11e8-96fb-86b26308ceef.png"  width="200" /> | <img src="https://user-images.githubusercontent.com/16039381/45919398-46b1cb00-be9d-11e8-9b0d-9d8c8682c43e.png"  width="200" />

**Comment by daniel-luberda** [comment]
Could you attach an SVG file? I'll reopen it then. Cheers.
