### ISSUE TITLE
WPF platform support

### ISSUE THREAD

**Issue by JaeWangL** [luberda-molinet/FFImageLoading#1122]
### Description
I'm using this repo very well
and wpf is supported in xf since xf 3.0

I wonder if this repo will support wpf??

**Comment by daniel-luberda** [comment]
Adding WPF should be easy, as most of the code would be shared with UWP, but I'll need more time for this or help

**Comment by daniel-luberda** [comment]
It's already implemented thanks to @melimion 
I'll merge it soon and release new minor version. 

https://github.com/luberda-molinet/FFImageLoading/pull/1248
