### ISSUE TITLE
[Android] EXIF rotation

### ISSUE THREAD

**Issue by deakjahn** [luberda-molinet/FFImageLoading#1123]
### Description

I'm aware of https://github.com/luberda-molinet/FFImageLoading/issues/130 but that's is old and I still have problems, although only on Android. Could it be that the platform doesn't support all orientations and FF simply relies on what the platform provides?

### Steps to Reproduce

```
    <StackLayout Orientation="Vertical">
      <ff:CachedImage x:Name="i1" HeightRequest="150" />
      <ff:CachedImage x:Name="i2" HeightRequest="150" />
      <ff:CachedImage x:Name="i3" HeightRequest="150" />
      <ff:CachedImage x:Name="i4" HeightRequest="150" />
      <ff:CachedImage x:Name="i5" HeightRequest="150" />
      <ff:CachedImage x:Name="i6" HeightRequest="150" />
      <ff:CachedImage x:Name="i7" HeightRequest="150" />
      <ff:CachedImage x:Name="i8" HeightRequest="150" />
    </StackLayout>
```

```
    public MainPage() {
      InitializeComponent();

      i1.Source = ImageSource.FromUri(new System.Uri("https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_1.jpg"));
      i2.Source = ImageSource.FromUri(new System.Uri("https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_2.jpg"));
      i3.Source = ImageSource.FromUri(new System.Uri("https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_3.jpg"));
      i4.Source = ImageSource.FromUri(new System.Uri("https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_4.jpg"));
      i5.Source = ImageSource.FromUri(new System.Uri("https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_5.jpg"));
      i6.Source = ImageSource.FromUri(new System.Uri("https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_6.jpg"));
      i7.Source = ImageSource.FromUri(new System.Uri("https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_7.jpg"));
      i8.Source = ImageSource.FromUri(new System.Uri("https://github.com/recurser/exif-orientation-examples/raw/master/Landscape_8.jpg"));
    }
```

The pictures used are from the https://github.com/recurser/exif-orientation-examples project, two sets of 8 images each with all possible EXIF orientations.

### Expected Behavior

All images rotated as the EXIF dictates.

### Actual Behavior

![screenshot_2018-09-25-19-49-18](https://user-images.githubusercontent.com/2234271/46033159-c76f0200-c0fd-11e8-9857-9455fe93f62a.png)

### Basic Information

- Version with issue: 2.4.3840

**Comment by daniel-luberda** [comment]
Hi @deakjahn  This is the code responsible for EXIF rotation on Android: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Decoders/BaseDecoder.cs#L62-L83

Do you see any issue? (PR welcome)

**Comment by deakjahn** [comment]
Well, these are the most often used values, that's true, however, in theory, there are eight values... I don't know how sure you can be of those never ever popping up.

**Comment by deakjahn** [comment]
I could very easily send you source code but sorry, I don't have the tools installed and don't want to disturb my current work setup in order to be able to create real requests. If this suits you, I'm completely game. :-)

**Comment by daniel-luberda** [comment]
Sure :) That would be great too.

**Comment by deakjahn** [comment]
You check for the specific values of 3, 6 and 8 in BaseDecoder.DecodeAsync(). Actually, you can be cleverer than that if you realize that the EXIF orientation value is in fact a bit field where the individual bits describe various rotating and flipping transformations (see https://magnushoff.com/jpeg-orientation.html). So, what I would suggest is to send the original `orientationValue` instead of `exifRotation` to `ToRotatedBitmap()` and solve all orientations there:

`IsBitSet()` is just a convenience function I use, it could be simply inlined:

    public static bool IsBitSet(this int value, int bit) => ((value & (1 << bit)) > 0);

**Comment by daniel-luberda** [comment]
Fixed. Thanks @deakjahn for details. Cheers.
