### ISSUE TITLE
Memory leaks with CarouselView & ListView

### ISSUE THREAD

**Issue by EmmanuelJego** [luberda-molinet/FFImageLoading#1124]
### Description

Hi!

I'm currently working with cached image (cached GIFs), but I noticed memory leaks while using these within a CarouselView. The Xamarin Profiler confirmed this issue, showing that CachedImage instances within the carousel are not released. 
Using simple Image the problem does not appear.
I tried to clear the cache with `ImageService.Instance.InvalidateMemoryCache();` which works since the images are reloaded if I try to display them again, but the memory is not released. I also tried `CacheType="None"`.

I checked different github issues and this problem is apparently already known (https://github.com/luberda-molinet/FFImageLoading/issues/719, https://github.com/luberda-molinet/FFImageLoading/issues/828, ...).
But actually the problem appears also with a ListView, as said in this issue : https://github.com/luberda-molinet/FFImageLoading/issues/867

I didn't find any solution yet.
Do I miss something?

Thanks for you help!

### Basic Information

- Version with issue: 2.4.3.840

**Comment by daniel-luberda** [comment]
It's fixed now in latest prerelease.
