### ISSUE TITLE
Set the degree of Blurr for BlurredTransformation

### ISSUE THREAD

**Issue by LeoJHarris** [luberda-molinet/FFImageLoading#1125]
Enhancement request: 

I thought it would be cool to be able to set the degree of blur using the BlurredTransformation. Bindable property for ranging from 1 - 100 or something and allow the developer to set the amount of blur for the transformation.

**Comment by daniel-luberda** [comment]
You can set blur radius, see `Radius` property: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Droid/BlurredTransformation.cs#L26

The only thing is that transformations properties are not bindable, so you need to set transformation to a new instance: 

`cachedImage.Transformations = new List<ITransformation>() { new BlurredTransformation() { Radius = 5 } }`

**Comment by daniel-luberda** [comment]
Also bindable transformations are on a TODO list: 

:) Cheers. https://github.com/luberda-molinet/FFImageLoading/issues/860
