### ISSUE TITLE
SVG with embedded recource not working

### ISSUE THREAD

**Issue by r4ibOm** [luberda-molinet/FFImageLoading#1134]
### Description

I made an embedded resource inclusion using a png image and it worked normally, but when I switch to svg the image is not displayed.

### Steps to Reproduce

Using the same path as the png image, just changing the extension to .svg but without success.

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform: Android

### Screenshots

![capturar1](https://user-images.githubusercontent.com/44219005/47059626-9899f800-d1a0-11e8-90fe-54e79d06d430.JPG)
![capturar2](https://user-images.githubusercontent.com/44219005/47059652-b10a1280-d1a0-11e8-9198-f89c9d440d74.JPG)

### Reproduction Link / Code

            <ffimageloading:CachedImage HorizontalOptions="Center" VerticalOptions="Center"
			                            WidthRequest="24" HeightRequest="24"
			                            DownsampleToViewSize="true"
			                            Source = "{local:EmbeddedImage ResourceID=Simulador.de.Investimentos.Images.SVG.Info.svg}">
            </ffimageloading:CachedImage>

**Comment by EmilAlipiev** [comment]
make sure that you follow the convention for source `resource://myProjectName.Simulador.de.Investimentos.Images.SVG.Info.svg?assembly=myProjectName`

svg embedded images are surely working. i am using them heavily

**Comment by r4ibOm** [comment]
> make sure that you follow the convention for source `resource://myProjectName.Simulador.de.Investimentos.Images.SVG.Info.svg?assembly=myProjectName`
> 
> svg embedded images are surely working. i am using them heavily

I tried that way but it did not work.
`            <ffimageloading:CachedImage HorizontalOptions ="Center" VerticalOptions ="Center"
			                            WidthRequest ="24" HeightRequest ="24"
			                            DownsampleToViewSize ="true"
			                            Source = "resource://Simulador.de.Investimentos.Images.SVG.Info.svg?assembly=Simulador.de.Investimentos}>
            </ffimageloading:CachedImage>`

**Comment by EmilAlipiev** [comment]
you are using wrong library. you should use ffimageloadingsvg.

**Comment by r4ibOm** [comment]
Now it worked. Thank you.
