### ISSUE TITLE
Embedded Svg images are not loading or very slow if connection is slow

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#1135]
### Description
 
i am loading embedded svg images into the listview. with the code below. Images are locally embedded into the project, no internet images. And they are super small like between 10kb-50kb. If i have a good internet connection or no connection at all (tested in flight mode), all are loaded super fast.
But when i have poor connection, they are super slow or even some not loaded. I dont understand why svg images are depends on internet connection.

```
 <Style x:Key="ImgStyle" TargetType="ffimageloadingsvg:SvgCachedImage">
        <Setter Property="Aspect" Value="AspectFit"/>
        <!--<Setter Property="LoadingPlaceholder" Value="loading.gif"/>-->
        <Setter Property="FadeAnimationEnabled" Value="True"/>
        <Setter Property="InputTransparent" Value="True"/>
        <Setter Property="ErrorPlaceholder" Value="resource://myProject.Shared.Images.Icons.error.svg?assembly=myProject.Shared"/>
        <Setter Property="HeightRequest">
            <OnIdiom x:TypeArguments="x:Double" Phone="65" Tablet="96" Desktop="144"  />
        </Setter>
    </Style>

     <ffimageloadingsvg:SvgCachedImage  Style="{StaticResource ImgStyle}"                                  
                                                    Source="resource://myProject.Shared.Images.Icons.image1.svg?assembly=myProject.Shared"
                       />
```

 
### Basic Information

- Version with issue:  2.4.3.840 
- Platform: Android device with 6.0.1

**Comment by daniel-luberda** [comment]
Hi @EmilAlipiev,

Do you load other images concurrently? FFImageLoading has a queue of image loading tasks which defaults to max concurrent tasks of:

`SchedulerMaxParallelTasks = Math.Min(4, Math.Max(2, (int)(Environment.ProcessorCount / 2d)));`

You probably hit the case, where all queue slots are taken by other tasks.
