### ISSUE TITLE
[Question] TintTransformation in code behind

### ISSUE THREAD

**Issue by stesvis** [luberda-molinet/FFImageLoading#1139]
Maybe this is a stupid question, but how can I do this in C#?

```
<ffimageloadingsvg:SvgCachedImage x:Name="statusIcon" Source="resource://LiveDispatch.Mobile.Resources.status_circle.svg" 
	 WidthRequest="20" HeightRequest="20" 
	 HorizontalOptions="Center" VerticalOptions="Center">
	<ffimageloadingsvg:SvgCachedImage.Transformations>
		<ffimageloadingTrans:TintTransformation HexColor="#ff0000" EnableSolidColor="true"/>
	</ffimageloadingsvg:SvgCachedImage.Transformations>
</ffimageloadingsvg:SvgCachedImage>
```

Specifically, how to set the TintTransformation color from the code behind?

Thanks

**Comment by daniel-luberda** [comment]
Hi @stesvis 

```C#
cachedImage.Transformations = new List<ITransformation>() 
{ 
  new TintTransformation() { HexColor="#ff0000", EnableSolidColor="true"  } 
}
```

**Comment by stesvis** [comment]
Thank you!
Is the HexColor property bindable?
Is this possible somehow?

<ffimageloadingsvg:SvgCachedImage x:Name="statusIcon" Source="resource://LiveDispatch.Mobile.Resources.status_circle.svg" 
	 WidthRequest="20" HeightRequest="20" 
	 HorizontalOptions="Center" VerticalOptions="Center">
	<ffimageloadingsvg:SvgCachedImage.Transformations>
		<ffimageloadingTrans:TintTransformation HexColor="{Binding MyColor}" EnableSolidColor="true"/>
	</ffimageloadingsvg:SvgCachedImage.Transformations>
</ffimageloadingsvg:SvgCachedImage>

**Comment by daniel-luberda** [comment]
Not yet. Didn't have time to implement it. It's on "TODO" list. Cheers.
