### ISSUE TITLE
Re-Assignment of Source doesn't change the image.

### ISSUE THREAD

**Issue by alicint** [luberda-molinet/FFImageLoading#1140]
### Description

I'm using CachedImage inside a caoursel view which recycles the views and then assigns a new image to the recycled views but it seems like re-asignments keep the images the same. no change occurs.

### Steps to Reproduce
I'm using this carousel view
https://github.com/AndreiMisiukevich/CardView

and images are loaded from Url.

**Comment by daniel-luberda** [comment]
Hi @alicint 
Could you make a repo?

**Comment by eternalbard** [comment]
I think I have the same issue... I have an avatar picture of the user. Then he takes a new picture from camera, I change the Source from Prism View Model and the new picture doesn't appear.

But my ffImage:CachedImage is inside a SfListView's HeaderTemplate. Hadn't time to try a fixed static ffImage:CacedImage instead.

**Comment by daniel-luberda** [comment]
It should be fixed now. You should clear cache entry first (but that's obvious)
