### ISSUE TITLE
Adding file type extension to end of file name in disk cache directory

### ISSUE THREAD

**Issue by AArayeshi** [luberda-molinet/FFImageLoading#1142]
Thanks for having this grate tools.
Now the images file extension in the disk cache is the expiry duration number such as "key.432000".
But in some cases I need to have real file type extension like "key.jpg" to have ability to see real images in disk cache directory.
Or may be adding config option to having file type extension in the end of file name or not.
I suggest making file names like "key.duration.jpg".

Thanks

**Comment by daniel-luberda** [comment]
You can determine file type with this: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Helpers/FileHeader.cs
