### ISSUE TITLE
Image crop view too slow to respond

### ISSUE THREAD

**Issue by argiebacomo** [luberda-molinet/FFImageLoading#1144]
### Description

the crop function is a little wonky, a little slow to respond. Is there a way to make it more responsive? I've already tried adjusting the pan speed, but its still kind of slow to respond.

### Steps to Reproduce

I just copied the codes in the samples and just adjusted the pan speed.

### Expected Behavior

respond on pan gesture

### Actual Behavior

it takes a second/s before it moved.

### Basic Information

- Version with issue: 1.0.7
- Last known good version: unknown
- Platform: Xamarin.iOS(Xamarin.Forms) on Visual Studio Community 2017 for Mac

**Comment by daniel-luberda** [comment]
It's another lib (not this site)
