### ISSUE TITLE
Assigning same source to two CachedImage instances of different sizes causes image size to incorrect

### ISSUE THREAD

**Issue by vikram-ma** [luberda-molinet/FFImageLoading#1146]
### Description

CachedImage doesn't honor HorizontalOptions  and VerticalOptions & Aspect  property in some cases.

### Steps to Reproduce
1. Add multiple CachedImage object instances. Set some HorizontalOptions and VerticalOptions to FillAndExpand.
2. Each of the CachedImage object sizes are different.
3. Assign same image source to all CachedImage object instances. At this point all image sizes look correct, and fill entire CachedImage object.
4. Resize the Layout which holds these CachedImage instance objects.
5. Toggle the visibility of CachedImage object instance. 

### Expected Behavior
6. images should continue to occupy entire CachedImage or entire width depending on HorizontalOptions and VerticalOptions setting.

### Actual Behavior

6. Repeat steps 4-5 form "Steps to reproduce" few times, and then image appears smaller and do not fill the entire CachedImage object. Images in Bigger CachedImage takes the size of the smallest CachedImage used.
7. This issue also happens when I set different properties for HorizontalOptions and VerticalOptoins or Aspect to CachedImage object instances and repeat steps 4-5.

### Basic Information

- Version with issue: 2.4.3.840
- Last known good version: Unknown
- Platform: Android

**Comment by rredoh** [comment]
I experienced the same too. But in my case I'm just adding 2 CachedImages with same image source

**Comment by daniel-luberda** [comment]
It should be fixed with: https://github.com/luberda-molinet/FFImageLoading/issues/1110
