### ISSUE TITLE
It's throwing an exception in Android: System.TypeLoadException

### ISSUE THREAD

**Issue by Bohirjon** [luberda-molinet/FFImageLoading#1150]
### Description
Hey guys I just upgraded the "FFImageLoading" to 2.4.3.840 with xamarin forms to 3.4.0.987044-pre2 and I deleted all bin obj folders and then tried to run app, it doesn't load the assembles
### Steps to Reproduce

 Open a new xam.Forms project with the latest version 3.3.0.967583 (or prerelease version  3.4.0.987044-pre2) and add the nugets (Xamarin.FFImageLoading & Xamarin.FFImageLoading.Forms)  into both projects shared and xam.android and put the FFImageLoading.Forms.Platform.Init() method then try to run it.

### Expected Behavior
It doesn't load the assembles and throws an exception this: System.TypeLoadException: VTable setup of type FFImageLoading.Forms.Platform.CachedImageFastRenderer failed.

### Actual Behavior
It should work as previous version.

### Basic Information

- Version with issue:  2.4.3.840
- Last known good version: 2.3.6
- Platform: Xamarin.Android

**Comment by daniel-luberda** [comment]
Please attach a repo as I can't reproduce it.

**Comment by Bohirjon** [comment]
Hi @daniel-luberda, I downgraded the xam.Forms to stable version and it got working, I thought I've tried with the stable ver. Thanks, you can close this.

**Comment by plsgard** [comment]
Got the same problem after upgrading Xamarin.Forms from 3.4.0.924579-pre1 to 3.4.0.987044-pre2. Like @Bohirjon, I cleaned all bin/obj folders but finally revert to the previous Xamarin.Forms version (3.4.0.924579-pre1) only on Android project correct the problem.

Seems to be similar to #313

**Comment by katkusmt** [comment]
Issue still persists, I am on 3.4.0.1008975. Anyone got ideas how to solve this?

**Comment by gsgou** [comment]
This is still happening on FFImageLoading 2.4.4.859 and Xamarin.Forms 3.6.0.220655 (stable). @daniel-luberda maybe you can reopen please?

This occurs both using CachedImageRenderer.Init in FFImageLoading.Forms.Platform AND the obsolete FFImageLoading.Forms.Droid.

**Comment by daniel-luberda** [comment]
It's fixed in latest prerelease nuget. 
Duplicate of: https://github.com/luberda-molinet/FFImageLoading/issues/1154

**Comment by xhashimks** [comment]
@daniel-luberda  - Can you please put back the 2.4.4.858-pre package? I have this issue with Forms Version 3.5.. I cannot upgrade Forms to version 3.6 as I am getting another issue with iOS project with FFImageLoading for which I already commented on an open ticket.. Please let me know your comments.

**Comment by daniel-luberda** [comment]
@xhashimks  Done

**Comment by xhashimks** [comment]
@daniel-luberda - I am getting the same issue with Xamarin Forms v3.5.0.274416 and the 2.4.4.858-pre package. Can you please help me in resolving this?

**Comment by Rickbieze** [comment]
i had the same issue on android ("System.TypeLoadException: VTable setup of type FFImageLoading.Forms.Platform.CachedImageFastRenderer failed"), fixed it by updating all nugets and rebuilding the solution (xamarin forms v 4.0.0.425677 and  Xamarin.FFImageLoading.Forms v 2.4.11.982)

**Comment by MuhammadHamzaRajput** [comment]
commit your code or take a copy of your project.
After the apply this command on package manager console "update-package".
After this clean build your project, then restart visual studio and rebuild your project.
This procedure work for me.

**Comment by DotnetPilot** [comment]
Getting the same error..

Unhandled Exception:
System.TypeLoadException: VTable setup of type FFImageLoading.Forms.Droid.CachedImageFastRenderer failed

v2.4.11.982 via nuGet

**Comment by DotnetPilot** [comment]
` protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            

            LoadApplication(new App());
            FFImageLoading.Forms.Platform.CachedImageRenderer.Init(true);
        }`
