### ISSUE TITLE
Is this library support Image Preview in full screen?

### ISSUE THREAD

**Issue by prashantpimpale93** [luberda-molinet/FFImageLoading#1151]
### Description

Do this library supports Image preview [like on Image click the Image should be visible on full screen]?

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform:

**Comment by EmilAlipiev** [comment]
it has nothing to do with this library. this is what you must program. Library is responsible of displaying images and it does perfectly

**Comment by prashantpimpale93** [comment]
Yes... thanks for the reply! I moved on with an image preview pop and
worked like a charm..!

**Comment by EmilAlipiev** [comment]
you may close the issue ;)

**Comment by prashantpimpale93** [comment]
Yes will definitely do on Monday!

On Nov 17, 2018 21:25, "Emil Alipiev" <notifications@github.com> wrote:

you may close the issue ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/luberda-molinet/FFImageLoading/issues/1151#issuecomment-439627042>,
or mute the thread
