### ISSUE TITLE
Does not show svg image 

### ISSUE THREAD

**Issue by Wep4ik** [luberda-molinet/FFImageLoading#1152]
### Description
Can't use SVG images in xamarin.forms uwp project.
I follow this https://www.youtube.com/watch?v=eVA9C7Ik_AM tutorial step by step, but in my uwp( i have not tried in other projects) doesn't show svg image. 
I use .Net Standart 2.0

**Comment by EmilAlipiev** [comment]
you should give more details. svg images are working fine.  you are probably coding wrong

**Comment by Wep4ik** [comment]
Ye,was my bad. Uwp,iOS and android working fine,but I have a problem with macOS project ,I add macOS project in my solution aswell
