### ISSUE TITLE
Updating to v2.4.4.859 is not rendering some SVG file properly

### ISSUE THREAD

**Issue by mhdshbk** [luberda-molinet/FFImageLoading#1156]
### Description

I'm trying to update XF3.2 to 3.4, and I got an exception with `Init()` of FFImageLoading in the Android and updated to the nuget package to v2.4.4.858-pre as mentioned in #1154 
After updating the package, the attached svg file is not rendered properly. It was working fine in the previous version 2.4.3.840.
The file doesn't work with the latest stable release also.
[overlay.svg.zip](https://github.com/luberda-molinet/FFImageLoading/files/2591557/overlay.svg.zip)

### Expected Behavior

![img_5afff5284c44-1](https://user-images.githubusercontent.com/14141789/48657938-4f6aeb80-ea5f-11e8-837e-eba7f254d2bd.jpeg)

*the branding has been colored

### Actual Behavior

![img_9271](https://user-images.githubusercontent.com/14141789/48657911-cf448600-ea5e-11e8-9064-1c53c18199b6.PNG)

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: 2.4.3.840
- Platform: Android and iOS

### Screenshots
Attached the screenshots as Actual & Expected Behaviors

**Comment by EmilAlipiev** [comment]
i am having similar issue. can you please provide a simple project? you will get faster help with that i think. otherwise tomorrow i will try to create one. today i am not having access to my computer.

**Comment by EmilAlipiev** [comment]
I have just added sample project with more details over here https://github.com/luberda-molinet/FFImageLoading/issues/1157

**Comment by daniel-luberda** [comment]
Could you try 2.4.5.860 prerelease?

**Comment by mhdshbk** [comment]
@daniel-luberda Thanks for the fix. Little busy these days. Will let you know as soon as I check and confirm it's fixed.

**Comment by andrewbaranov** [comment]
> Could you try 2.4.5.860 prerelease?

Work perfect. Was problems with crash and svg. Thx

**Comment by mclillill** [comment]
Had the same problem.  2.4.5.860 prereleas seems to fix it

**Comment by winterdouglas** [comment]
Hi. I've been using the version 2.4.3.840 for a while without problems, now I updated to Xamarin.Forms 3.4 and found the issue described here. I tested with the proposed pre-released version and the icons don't look weird anymore but for some of them the colors are not correct. With the version 840 mentioned above they were working fine.

![image](https://user-images.githubusercontent.com/1329194/50485230-d0b98480-09f4-11e9-947e-27347291a736.png)
The download one above should be blue as the tag one.

**Comment by winterdouglas** [comment]
> Hi. I've been using the version 2.4.3.840 for a while without problems, now I updated to Xamarin.Forms 3.4 and found the issue described here. I tested with the proposed pre-released version and the icons don't look weird anymore but for some of them the colors are not correct. With the version 840 mentioned above they were working fine.
> 
> ![image](https://user-images.githubusercontent.com/1329194/50485230-d0b98480-09f4-11e9-947e-27347291a736.png)
> The download one above should be blue as the tag one.

I just took a look on their source code here and the difference between them is that the download one sets the color as a css style and the other don't.

**Comment by irongut** [comment]
>I tested with the proposed pre-released version and the icons don't look weird anymore but for some of them the colors are not correct. With the version 840 mentioned above they were working fine.
> I just took a look on the source code of my SVGs here and the difference between them is that the download one sets the color as a css style and the other as attribute, that's the reason.

Exactly as described two weeks ago, with sample images, here: https://github.com/luberda-molinet/FFImageLoading/issues/1157#issuecomment-447601446

**Comment by daniel-luberda** [comment]
Fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/df7b058bc8e2ebd2e6a60d4ab4b9fef4c0343d43
