### ISSUE TITLE
SVG images Problems using XF 3.4 and Ffimageloading 2.4.4

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#1157]
Hi @daniel-luberda 

Please see the difference between XF3.4 and FFImagloading 2.4.4 vs XF3.3 and FFimageloading 2.4.3 On Android. The same problems also on UWP.
I couldnt test but most probably on IOS as well.

**Problem1;** 
In the attached project, please go to AboutPage

_XF3.4 and FFImagloading  2.4.4_ 

![image](https://user-images.githubusercontent.com/10422347/48703695-cf768a00-ebf4-11e8-9b3d-632f9f779136.png)

_XF3.3 and FFImagloading  2.4.3_ 

![image](https://user-images.githubusercontent.com/10422347/48704380-aa831680-ebf6-11e8-994f-acea3789adbe.png)

**Problem2;**  using icon on masterdeail icons are either not displayed at all or not properly displayed
In the attached project, please open masterdetail see in both versions size difference.
  
_XF3.4 and FFImagloading 2.4.4_ 
![image](https://user-images.githubusercontent.com/10422347/48705009-5c6f1280-ebf8-11e8-8162-3281e2c4254c.png)

_XF3.3 and FFImagloading  2.4.3_ 
 
![image](https://user-images.githubusercontent.com/10422347/48705462-7bba6f80-ebf9-11e8-85c9-f7ab6f0e28cf.png)

**Problem 3** in the listview svg images arent displayed at all
In the attached project, please go to itemsPage

_XF3.4 and FFImagloading  2.4.4_ 

![image](https://user-images.githubusercontent.com/10422347/48703916-84a94200-ebf5-11e8-86bf-0d94c0a7595f.png)

XF3.3 and FFImagloading  2.4.3 
![image](https://user-images.githubusercontent.com/10422347/48704356-9808dd00-ebf6-11e8-996d-25238d0b0c8e.png)

Sample Project:

[App1.zip](https://github.com/luberda-molinet/FFImageLoading/files/2595126/App1.zip)

Related Issues:

https://github.com/luberda-molinet/FFImageLoading/issues/1156
https://github.com/luberda-molinet/FFImageLoading/issues/1154

**Comment by daniel-luberda** [comment]
Could you try 2.4.5.860 prerelease?

**Comment by IoTFier** [comment]
@daniel-luberda , is it possible that this is the same issue related to the issue I shared with you about FFImageloading not selecting proper image resolution for XF 3.3 and XF 3.4 ? Nothing was changed around this on my end ..

Thanks

**Comment by EmilAlipiev** [comment]
> Could you try 2.4.5.860 prerelease?

Works like before :)  thank you

**Comment by IoTFier** [comment]
@daniel-luberda  - I tried it using the latest pre... my image issue is still the same... any thoughts will be appreciated ..as I didn't change anything around images just updated the XF from 3.2 to 3.3, 3.4.....

**Comment by EmilAlipiev** [comment]
@IoTFier which one is your issue? can you reference?

**Comment by IoTFier** [comment]
@EmilAlipiev  - I mentioned this issue in https://github.com/luberda-molinet/FFImageLoading/issues/1154

**Comment by daniel-luberda** [comment]
Plase try to delete all cached / bin files. I was able to render those files correctly on newest prerelease nuget:

- `abs.svg`
- `cardio1.svg`

**Comment by EmilAlipiev** [comment]
@michelmoorlag can you please share your svgs.

**Comment by michelmoorlag** [comment]
[icon_milking_farm_grey.zip](https://github.com/luberda-molinet/FFImageLoading/files/2606824/icon_milking_farm_grey.zip)

@EmilAlipiev : I have added two svg's in the zipfile.  The merlinstatus_milking svg is showing disorted with FF 2.4.3 and the other on is showing all black with FF 2.4.5.860

**Comment by AuriR** [comment]
>           Could you try 2.4.5.860 prerelease?

Fixed it for me. Thanks!

**Comment by AuriR** [comment]
Here's a copy of a file that WASN'T working until the pre-release fix. Sorry for attaching ZIP - GitHub doesn't support dragging in an SVG :-P

[icon_website.zip](https://github.com/luberda-molinet/FFImageLoading/files/2612350/icon_website.zip)

**Comment by irongut** [comment]
I'm having similar problems with svgs in v2.4.4 and different ones with the v2.4.5.860-pre prerelease.

v2.4.4 ignores a transform in one of my svg files:
`<g id="Layer_2" transform="translate(0,-383.08398)">`

v2.4.5.860-pre fixes the transform issue but ignores a style in another svg file so draws paths in the wrong colour. This was working prior to this prerelease version.

I can work around the style issue by changing my svg but it may be more of a problem for others. I've attached the two images that I had these problems with.

[ffimage.svg.issue1157.zip](https://github.com/luberda-molinet/FFImageLoading/files/2683105/ffimage.svg.issue1157.zip)

**Comment by michelmoorlag** [comment]
@irongut: I think I have indeed the same issue. After upgrade to 2.4.4. some svg's show disorted. After upgrade to the preview the disorted images showed fine but for some others some color's changed to black. Thank you for pinpointing the exact issue. 
@daniel-luberda: I hope this detailed information can help you solve the issue? This would really us :)

**Comment by daniel-luberda** [comment]
Fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/df7b058bc8e2ebd2e6a60d4ab4b9fef4c0343d43
