### ISSUE TITLE
Nuget targeting Android 9.0

### ISSUE THREAD

**Issue by deakjahn** [luberda-molinet/FFImageLoading#1158]
### Description

The Nuget package warns me to target 9.0 instead of 8.1 on Android. Why was this necessary? Isn't this too early yet?

**Comment by EmilAlipiev** [comment]
where do you see that warning? when i open new project using VS2017, it uses 8.1 and i dont see any warning

**Comment by deakjahn** [comment]
Among the usual warnings in the VS error list. But I can't show you now because I thought, what the heck, changed the SDK to 9.0 and no I don't have the warning. :-)

I had the 8.1 SDK (API 27) and the project set to this API level. I received the warning then.

**Comment by madmurdock** [comment]
@daniel-luberda The TargetFramework seems to be set here https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/FFImageLoading.Droid.csproj#L14

I've started getting the warning since upgrading to 2.4.3.840

**Comment by madmurdock** [comment]
Snuck in when upgrading C#? https://github.com/luberda-molinet/FFImageLoading/commit/ac6e2c42013103b0467af6d5d469252124677cb6#diff-5761dcb3af6c983c8ea345a1a81a5697L15

**Comment by daniel-luberda** [comment]
Already fixed thanks to @madmurdock 

Please use newest prerelease nuget.
