### ISSUE TITLE
lag on image scroll

### ISSUE THREAD

**Issue by safeery2k** [luberda-molinet/FFImageLoading#1161]
### Description

Hi,

I am using listview and syncfusion grid control in my app to show images but it shows old image first and then the original one. I have gone through the documentation and beleive this was resolved in xf 2.2? I am using 3.x version of xf currently and still facing it.

I have seen the work around to set image source to null but i am generating views using xaml and i am not sure how can i set the image source to null and then to the required image. Could you please help on this?

Thanks

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform:

**Comment by daniel-luberda** [comment]
You should have use this: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#usage-in-listview-with-listviewcachingstrategyrecycleelement-enabled
