### ISSUE TITLE
Various questions about SVG loading 

### ISSUE THREAD

**Issue by MichaelRumpler** [luberda-molinet/FFImageLoading#1163]
### Description

I'm trying to load .svg files which are embedded resources in my .NET Standard
project. I do use Xamarin.Forms, but I have custom renderers where I display
the images so I need this on iOS and Android. The image names may not exist
in my app, so I need to check that and display a different image in that case.

I tried several approaches with different problems.

#### LoadStream()

All approaches have in common that LoadStream() does not take a simple Stream as
parameter. I load the embedded resource with Assembly.GetManifestResourceStream()
which returns synchronously. So I need to call
`LoadStream(_ => Task.FromResult(stream))`
This is an additional unneccesarry Task.
In the end I also need to continue my cell renderer synchronously. So best would
be, if the whole process would be synchronously.

#### iOS: Into(UIImageView)

Here I call

	ImageService.Instance
		.LoadStream(_ => Task.FromResult(stream))
		.WithCustomDataResolver(new SvgDataResolver(32, 32, true))
		.Success((imageInformation, loadingResult) => {
			if (ImageView.Image.Size.Width != 32)
				ImageView.Image = ImageView.Image.Scale(new CGSize(32, 32), 0);
			ImageView.Image = ImageView.Image.ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);
		})
		.Into(ImageView);

But there are several problems with this approach:

##### 1. The Action passed to Success is run on a background thread

Although I call that from a custom renderer on the UI thread, the Success function
is executed in a different context. I need to switch back with
`BeginInvokeOnMainThread` which is a bit annoying.

##### 2. When the image is not cached yet, then ImageView.Image is null and I don't see an image

The image is not displayed at the first try. I need to scroll down and up a bit
and then it shows up. I guess this is because it is already cached at the 2nd try.
I also tried adding `Retry(3)`, but that didn't help. As it does call `Success`
I think that it doesn't recognize the problem and thus doesn't retry it.

##### 3. The size cannot be corrected

If I run the code on a @2x device, then ImageView.Image.Size will be 64/64.
I check for that and try to scale it down, but that doesn't seem to work.
If I load a .png file from disk, then I do get the @2x file (there's a little "2" in the bottom right corner), but the Size
is still 32/32. The result is, that the .svg images are much bigger than the
.pngs.
I also tried `new SvgDataResolver(32, 32, false)`, but then you see the pixels.
It looks like a 32x32 image is created and then scaled to 64x64.

#### iOS: AsUIImageAsync()

	ImageService.Instance
		.LoadStream(_ => Task.FromResult(stream))
		.WithCustomDataResolver(new SvgDataResolver(32, 32, true))
		.AsUIImageAsync()
		.ContinueWith(t =>
		{
			var svgImage = t.Result;
			Xamarin.Forms.Device.BeginInvokeOnMainThread(() =>
			{
				if (svgImage.Size.Width != 32)
					svgImage = svgImage.Scale(new CGSize(32, 32), 0);
				svgImage = svgImage.ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);
				ImageView.Image = svgImage;
				svgImage.Dispose();
			});
		});

This code also has some problems.

##### 1. await AsUIImageAsync() produces a deadlock

I tried to await AsUIImageAsync() first, but that produced a deadlock so I used
ContinueWith instead. But this does not keep the context, so I have to switch
back to the main thread again which is a bit ugly.

##### 2. Also no image on first try

I guess this time it is, because the GetCell() method in the cell renderer
returned before the image was loaded. Again, when I scroll down/up a bit, the
images appear.

I use exactly the same code here to scale the image. Here it works, but in
`IntoUIImageViewCell` it doesn't.

#### Android

On Android the images are displayed in the correct size. So this is much better.
There are still some issues though.

##### await AsBitmapDrawableAsync() runs in a deadlock

Similar as iOS this never comes back. Maybe I'm doing something wrong, but I
don't know anything else I could do. If I use ContinueWith instead like I did
on iOS, then it works.

##### Tinting the image does not work

This may also be something I do wrong. I tried both using your
`Transform(new TintTransformation("#EC9522"))` or `DrawableCompat.SetTint`.
The latter works in my app with pngs, but in the sample app neither works.
Although `SetTint` does change the color from black to grey, it does not use
the color I specified.
Maybe this is something with the transparency channel? Unfortunately the code
from https://github.com/luberda-molinet/FFImageLoading/wiki/Android-API#transparency
does not work.

### Basic Information

- Version with issue: FFImageLoading 2.4.5.860-pre (XF 3.4)
- Platform: Android and iOS

### Reproduction Link / Code

[FFImage_Svg.zip](https://github.com/luberda-molinet/FFImageLoading/files/2640101/FFImage_Svg.zip)

**Comment by daniel-luberda** [comment]
Hi @MichaelRumpler, sorry for so long delay. I had a lot of work recently, tried to read all issues here but there was a lot of it for just one person. 

> LoadStream()
> All approaches have in common that LoadStream() does not take a simple Stream as
> parameter. I load the embedded resource with Assembly.GetManifestResourceStream()
> which returns synchronously. So I need to call
> LoadStream(_ => Task.FromResult(stream))
> This is an additional unneccesarry Task.
> In the end I also need to continue my cell renderer synchronously. So best would
> be, if the whole process would be synchronously.

It's the same approach as `Xamarin.Forms.Image`, it's necessary to provide a `func` for a few reasons such as loading operation can retry, etc. You can simply do something like this: 

```C#
var bytes = yourStream.ToByteArray();
imageLoading.LoadStream(_ => Task.FromResult(new MemoryStream(bytes)));
```

> The image is not displayed at the first try. I need to scroll down and up a bit
> and then it shows up. I guess this is because it is already cached at the 2nd try.
> I also tried adding Retry(3), but that didn't help. As it does call Success
> I think that it doesn't recognize the problem and thus doesn't retry it.

There were some issues which could lead to the issue you describe. It should be fixed in newest stable. 

1. The Action passed to Success is run on a background thread

> Although I call that from a custom renderer on the UI thread, the Success function
> is executed in a different context. I need to switch back with
> BeginInvokeOnMainThread which is a bit annoying.

You can easily change this behaviour with custom config: 
```C#
var config = new FFImageLoading.Config.Configuration()
{
    ExecuteCallbacksOnUIThread = true
};
ImageService.Instance.Initialize(config);
```

> I also tried new SvgDataResolver(32, 32, false), but then you see the pixels.
> It looks like a 32x32 image is created and then scaled to 64x64.

Image is not scaled, it's generated with parameters you provide:
https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SvgDataResolver.cs#L160-L164

> await AsUIImageAsync() produces a deadlock
> 2. Also no image on first try
> I guess this time it is, because the GetCell() method in the cell renderer
> returned before the image was loaded. Again, when I scroll down/up a bit, the
> images appear.

FFImageLoading are async, you can use something like: `task.ConfigureAwait(false).GetAwaiter().GetResult()`, but I don't recommend it. 
You can use `MvxCachedImage` and `MvxCachedImage` which is native control for iOS/Android/Windows, you just set a property and forget about everything else. 

> This may also be something I do wrong. I tried both using your
> Transform(new TintTransformation("#EC9522"))

You probably forgot to add `Xamarin.FFImageLoading.Transformations` nuget into a platform specific project. It's really important.

**Comment by MichaelRumpler** [comment]
Thanks for taking the time to answer my questions.
I used SkiaSharp directly instead. SkiaSharp has a more synchronous API which is better in my case where the images are already embedded and don't need to be loaded from somewhere.
