### ISSUE TITLE
System.BadImageFormatException: Expected reference type but got type kind 17

### ISSUE THREAD

**Issue by seanyda** [luberda-molinet/FFImageLoading#1165]
### Description

System.BadImageFormatException: Expected reference type but got type kind 17 is being thrown when I inherit from `SvgCachedImage` instead of `Image` on my Xamarin.Forms project. No stack trace is left behind, this only occurs on Android, when I run the project on iOS everything seems to work ok.

Seems like this issue has came up from the last few builds... as I am downgraded to version 2.4.1.823 and things seem to be working ok.

<img width="515" alt="screenshot 2018-12-06 at 14 27 03" src="https://user-images.githubusercontent.com/16290413/49590154-0540a000-f963-11e8-93e4-8423a225e319.png">

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: 2.4.1.823
- Platform: Android

**Comment by nichojo89** [comment]
Fyi, I also experience this issue on version 2.4.1.823 and on iOS

**Comment by muhammetsahin** [comment]
I think, you should add this line to your MaintActivity.cs
Install this two packages to all projects (shared, ios and android)
* Xamarin.FFImageLoading.Svg
*Xamarin.FFImageLoading.Svg.Forms
![image](https://user-images.githubusercontent.com/2045788/54076504-73c42f80-42bd-11e9-95f7-6c5f4b868d40.png)

In my case it worked.

`  var ignore = typeof(FFImageLoading.Svg.Forms.SvgCachedImage);`

![image](https://user-images.githubusercontent.com/2045788/54076497-5d1dd880-42bd-11e9-8399-a387c60b1e4f.png)



**Basic Information**
Version with issue: 2.4.4.840 (And do not upgrade .859 )
Last known good version: 2.4.1.823
Platform: Android

@seanyda
