### ISSUE TITLE
Xamarin IOS application crashes while list with over 500 images is scrolling fast

### ISSUE THREAD

**Issue by vkhadyka** [luberda-molinet/FFImageLoading#1166]
I have a list with 560 items with images which loaded and cached locally with `FFImageLoading`. When I tries to scroll list to bottom and top to for few minutes. I got crash without any logs and etc. I think that memory low exception.

I implemented override for ReceiveMemoryWarning function.

```
public override void ReceiveMemoryWarning(UIApplication application)
{
     ImageService.Instance.InvalidateMemoryCache();
     GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
     base.ReceiveMemoryWarning(application);
 }
```
and set property `ClearMemoryCacheOnOutOfMemory` for `ImageService` is `true`. But it doesn't help. After a few minutes of fast scroll from top to bottom and back to top my application is crashing.

How to avoid memory exception and crash?

**Comment by adrianknight89** [comment]
@vkhadyka How big are your images? You could try reducing their size.

**Comment by sarojpdamco** [comment]
Same is happening in my app also
