### ISSUE TITLE
SVG style is ignored in defs

### ISSUE THREAD

**Issue by MikeW1986** [luberda-molinet/FFImageLoading#1167]
### Description

fill colors are not loaded from:

  <defs>
    <style>.cls-1{fill:#8797b4;}</style>
  </defs>

### Steps to Reproduce

[info_circle_blue.zip](https://github.com/luberda-molinet/FFImageLoading/files/2662491/info_circle_blue.zip)

Use attached SVG

### Expected Behavior

svg with color #8797b4

### Actual Behavior

svg is black

### Basic Information

- Version with issue: 2.4.5.860-pre
- Last known good version: 2.4.3.840
- Platform: iOS and Android

**Comment by MikeW1986** [comment]
in last stable version: 2.4.4.859 it works also good, but i tested pre version because of bug #1157

**Comment by irongut** [comment]
I have the same issue and tried the pre for the same reason. I've included a sample file in a post in bug #1157.

**Comment by daniel-luberda** [comment]
Fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/df7b058bc8e2ebd2e6a60d4ab4b9fef4c0343d43
