### ISSUE TITLE
LoadStream with CacheKey is not working in Xamarin.Mac

### ISSUE THREAD

**Issue by nor0x** [luberda-molinet/FFImageLoading#1169]
### Description

`LoadStream` does not works if a custom `CacheKey` is provided. I'm using the following code to load various image from a server - neither `OnSuccess` nor `OnError` gets called.

### Steps to Reproduce

```
var img = await ImageService.Instance
            .LoadStream(NSTokenField => MyRepo.LoadResourceAsync(MyResource))
            .Success((ImageInformation arg1, LoadingResult arg2) =>
            {
                ...
            }).Error((obj) =>
            {
                ...
            })
            .CacheKey(k)
            .WithCache(CacheType.All)
            .AsNSImageAsync();
```

### Expected Behavior

`img` should be a `NSImage`

### Actual Behavior

`img` is `null`

- Version with issue: 2.4.4.859
- Platform: Xamarin.Mac

**Comment by daniel-luberda** [comment]
I can't reproduce it with current stable: 

```C#
var a = await ImageService.Instance.LoadStream(async (arg) =>
{
    var resolver = new BundleDataResolver();
    var result = await resolver.Resolve("loading.png", TaskParameter.FromCompiledResource("loading.png"), CancellationToken.None);

    return result.Stream;
})
    .CacheKey("aaaa")
    .Success((arg1, arg2) => Debug.WriteLine("Success!!!!!!!!!!!!!!!!!"))
    .AsNSImageAsync();
```

![Screenshot 2019-04-30 at 17 50 50](https://user-images.githubusercontent.com/13569983/56975225-a0375200-6b70-11e9-9bdb-d2b1a570d37e.png)

**Comment by nor0x** [comment]
okay thanks for the reply! i will try it with the latest stable version and my reopen if it happens again
