### ISSUE TITLE
Image CrossFading not working on Android on cached images (again)

### ISSUE THREAD

**Issue by ElD4n1** [luberda-molinet/FFImageLoading#1173]
### Description

I know this has been asked many times but I didn't get it working after reading through the existing issues and it also is not clear to me now what the actual intended behaviour is.
Is the config FadeAnimationForCachedImages meant only for disk cached images or also for memory cached images? There is a different behaviour on iOS and Android, i.e. on iOS cross fading always works with that option enabled and on android it stops fading after the image has been shown one time.

I tried different things like setting the options globally in MainActivity on Android:

	FFImageLoading.ImageService.Instance.Initialize(new FFImageLoading.Config.Configuration()
	{
		FadeAnimationEnabled = true,
		FadeAnimationDuration = 100,
		FadeAnimationForCachedImages = true
	});

But without any effect.

My current workaround is to clear the cache every time the images are loaded:

	if (Device.RuntimePlatform == Device.Android)
	{
		await ImageService.Instance.InvalidateCacheAsync(CacheType.Memory);
	}

But this results in some stuttering/lagging, which would be mitigated if the images were in memory cache. (Note: I have 29 images that get crossfaded stepwise according to some calculated difference, i.e. in the worst case image 1 is crossfaded to image 29 by loading every image in between in 100ms steps).

Please bear with me.

### Steps to Reproduce

XAML:

	<ffimageloading:CachedImage 
		Source="{Binding ImageSrc}"
		FadeAnimationEnabled="True"
		FadeAnimationDuration="100"
		FadeAnimationForCachedImages="True"
		DownsampleToViewSize="True"/>

Cycle through multiple images and set delay to AnimationDuration like this:

	for (int i = 0; i <= numImages; i++)
	{
		ImageSrc = ImageSource.FromResource(String.Format("Project.Images.Image{0}.png", i));
		await Task.Delay(100);
	}

### Expected Behavior

Crossfading works always no matter how often the loop is executed and on any platform (Android and iOS in my case)

### Actual Behavior

Crossfading only works always on iOS and stops working on Android if the currently loaded image is already in memory cache.

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: only tested above version
- Platform: Xamarin.Forms 4.0.0.8055-pre1 (Android 8.0.0 + iOS 11.4)

**Comment by daniel-luberda** [comment]
Could you try latest alpha?

**Comment by maxyhi** [comment]
This is still and issue in 2.4.11.982. Was a solution found for this issue?
