### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by AbuMandour** [luberda-molinet/FFImageLoading#1174]
### Description

i can't run my unit test application after use FFImageLoading plugin, and can't get a sample including unit test

### Steps to Reproduce

1-create Xamarin form app and add FFImageLoading and use CachedImage, everything running well. 
2-Add Unit Test project and init my test config "Include Moq for my services and Mocks for Xamarin Forms.
2- Create a test method that init a new App and runs my test code like

`        [TestMethod]
        public void TestLoginFromViewModel()
        {
            //Arange
            Xamarin.Forms.Mocks.MockForms.Init();
            Application.Current = new App();           
            var secureStorageMock = new Mock<ISecureStorage>();
            var secureStorge = secureStorageMock.Object;
            var connectivityMock = new Mock<IConnectivity>();
            var connectivity = connectivityMock.Object;
            var loginViewModel = new LoginViewModel(new LoginService(secureStorge), new NavigationService(), connectivity);
            //Act
            var loginResult = loginViewModel.Login("mandour", "123").GetAwaiter().GetResult();
            //Assert
            Assert.IsTrue(loginResult);
        }`
3- in app.cs in portable class i call this property:
`            ImageService.EnableMockImageService = true;
`
### Expected Behavior

method run with errors

### Actual Behavior

I get this error: Could not load file or assembly 'FFImageLoading.Platform, Version=2.4.4.859, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: 2.4.4.859
- Platform: unit test project

**Comment by AbuMandour** [comment]
any help?

**Comment by daniel-luberda** [comment]
It's in the docs: https://github.com/luberda-molinet/FFImageLoading/wiki/Unit-Testing----how-to-enable
