### ISSUE TITLE
[iOS] SVG Opacity change has a delay when the app is cold started

### ISSUE THREAD

**Issue by adrianknight89** [luberda-molinet/FFImageLoading#1176]
I show an embedded SVG to the user the first time my app is run. The opacity of this file is set to 0.25. On Android, the system sets the opacity BEFORE the image is shown to the user. On iOS, it sets it AFTER; thus, creating a visual lag. See the reproduction.

[AppTestiOS.zip](https://github.com/luberda-molinet/FFImageLoading/files/2708831/AppTestiOS.zip)

**Comment by EmilAlipiev** [comment]
are you using the latest version? which version you had better performance last?

**Comment by daniel-luberda** [comment]
Should be fixed. Thanks for a repo! :)
