### ISSUE TITLE
FFImageLoading.Forms does not work on HTC Desire 820n

### ISSUE THREAD

**Issue by AhmedSalahKhodair** [luberda-molinet/FFImageLoading#1177]
I'm using FFImageLoading.Forms:CachedImage and it works fine on iOS simulator, Android emulator and Samsung with marshmello OS device and so far so good, But when I run it on HTC Desire 820n that has marshmello OS too, it didn't work.

**Comment by daniel-luberda** [comment]
I don't have that device. Can't help you without additional info.
