### ISSUE TITLE
Not Able to bind SVG image from ViewModel in xamarin.forms android

### ISSUE THREAD

**Issue by praveenBaruri** [luberda-molinet/FFImageLoading#1178]
### Description

I am using FFImageloading version: 2.4.3.840     and xamarin.forms: 2.4.0.282 

I have given SVG file in
Android
Resources->Drawable->Image1.svg
iOS
Resources->Image1.svg

I have added code as below

Main Activity and AppDelegate
  CachedImageRenderer.Init(true);
 var ignore = typeof(SvgCachedImage);

    <ContentView.Resources>
        <ResourceDictionary>
            <ffimageloadingsvg:SvgImageSourceConverter x:Key="SvgImageSourceConverter"></ffimageloadingsvg:SvgImageSourceConverter>
        </ResourceDictionary>
    </ContentView.Resources>

   <ffimageloadingsvg:SvgCachedImage x:Name="bodyMapImage" Source="{Binding SvgFileName, Converter={StaticResource SvgImageSourceConverter}}" Grid.Column="0" WidthRequest="200" HeightRequest="600" ReplaceStringMap="{Binding BodyMapreplceStrings}" />

and  from ViewModel

        public string SvgFileName
        {
            get { return _svgFileName; }
            set
            {
                _svgFileName = value;
                OnPropertyChanged();
            }
        }

SvgFileName="Image1.svg"

Everything is working fine with iOS but I am not able see the svg when I run the application in android device.

**Comment by daniel-luberda** [comment]
Please attach a repo, then I'll reopen this. Cheers.
