### ISSUE TITLE
[need info] about usage

### ISSUE THREAD

**Issue by rafsanulhasan** [luberda-molinet/FFImageLoading#1180]
I have 2 queries

1. Can I use it with Prism?
2. Can I use it for lazy loading or load more options? 
    To be more specific, I want to implement a ListView in which I want to load more items when the user has scrolled down to the last item of the ListView. Can I achieve this with this control? 

I'm asking this because someone from **Xamarin Developers** group at **Facebook** suggested me this control for the 2nd purpose...

Anyway I highly appreciate the effort. Thanks.

**Comment by daniel-luberda** [comment]
> 1. Can I use it with Prism?

Yes, it has no external dependencies. 

> 2\. Can I use it for lazy loading or load more options?

Yes, it's its primary use-case. See this: https://github.com/luberda-molinet/FFImageLoading#features

also check properties like "Delay" (image loading delay)
