### ISSUE TITLE
FFImageLoading .gif not loading from local resources in shared project android

### ISSUE THREAD

**Issue by DnyaneshWahiley** [luberda-molinet/FFImageLoading#1182]
when i use .gif from URL its working like below
<ff:CachedImage x:Name="Gif" WidthRequest="50" HeightRequest="50" Source="https://media.giphy.com/media/L0oczv4EnhA08/giphy.gif" />
but when i assigned from my local drawable resource its not loading
<ff:CachedImage x:Name="Gif" WidthRequest="50" HeightRequest="50" Source="giphy.gif" />

**Comment by jolugbo** [comment]
am experiencing this issue as well, any update

**Comment by daniel-luberda** [comment]
Can you make a working repo?

**Comment by jolugbo** [comment]
> Can you make a working repo?

Thanks for your response @daniel-luberda i realised the cause was the size of the image i was using, however after reducing the size of the GIF file it works fine.
