### ISSUE TITLE
CachedImage with ColorFillTransformation flips the final result vertically on iOS. Android works fine.

### ISSUE THREAD

**Issue by PRopia99** [luberda-molinet/FFImageLoading#1185]
### Description

On iOS, application of the `ColorFillTransformation` flips the resulting image vertically. (Result is upside down). I am fixing this currently by applying a `FlipTransformation` only on iOS, however, that is not ideal.

### Steps to Reproduce

1. Create a new CachedImage, and apply the `ColorFillTransformation` to it. 
2. Run on iOS and observe the image as flipped vertically.
3. Android works as expected.

### Expected Behavior

1. **iOS**: Only the `ColorFillTransformation` should be applied.
2. **Android**: Only the `ColorFillTransformation` should be applied.

### Actual Behavior

1. **iOS**: The original image has the `ColorFillTransformation` applied to it, but the image is flipped vertically.
2. **Android**: Works as expected.

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: I see that there have been no changes to the `ColorFillTransformation` before this version.
- Platform: iOS

### Screenshots

![l7ukzkzgsfw8wtbb ahtmq_thumb_9](https://user-images.githubusercontent.com/42378642/51100537-9164a380-17fc-11e9-8397-77d5c67e734e.jpg)

![xuttnqwirewin9vw mpphw_thumb_a](https://user-images.githubusercontent.com/42378642/51100545-99244800-17fc-11e9-8742-53a1fddc96da.jpg)

### Reproduction Link / Code

```
public class CircleCachedImage : CachedImage
    {
        public CircleCachedImage()
        {
            this.Transformations = new System.Collections.Generic.List<FFImageLoading.Work.ITransformation>();

            this.Transformations.Add(new ColorFillTransformation());

            this.Transformations.Add(new CircleTransformation());

            // color fill transformation (in combination with circleTransformation?) is flipping the final image..
            if (DeviceOS.Is(ApplicationLayer.Core.Enums.Platform.iOS))
            {
                this.Transformations.Add(new FlipTransformation(FlipType.Vertical));
            }
        }
    }
```

**Comment by minaairsupport** [comment]
I have the same issue in iOS image flip down , android working just fine

**Comment by shoeIT** [comment]
any news on this? Got the same error....

**Comment by RaFaGG** [comment]
+1 Same here...

**Comment by daniel-luberda** [comment]
Here's the code: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Touch/ColorFillTransformation.cs#L23-L47

```C#
        protected override UIImage Transform(UIImage sourceBitmap, string path, ImageSource source, bool isPlaceholder, string key)
        {
            double sourceWidth = sourceBitmap.Size.Width;
            double sourceHeight = sourceBitmap.Size.Height;

            UIGraphics.BeginImageContextWithOptions(new CGSize(sourceWidth, sourceHeight), false, (nfloat)0.0);

            try
            {
                using (var context = UIGraphics.GetCurrentContext())
                {
                    CGRect drawRect = new CGRect(0.0, 0.0, sourceBitmap.Size.Width, sourceBitmap.Size.Height);
                    context.SetFillColor(HexColor.ToUIColor().CGColor);
                    context.FillRect(drawRect);
                    context.DrawImage(drawRect, sourceBitmap.CGImage);

                    var modifiedImage = UIGraphics.GetImageFromCurrentImageContext();
                    return modifiedImage;
                }
            }
            finally
            {
                UIGraphics.EndImageContext();
            }
        }
```

Any clues?

**Comment by PRopia99** [comment]
Hi @daniel-luberda ,

Thank you for the code! After looking at this link: https://developer.apple.com/library/archive/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/GraphicsDrawingOverview/GraphicsDrawingOverview.html

I think we can point the issue to be that the `UIGraphics.GetCurrentContext()` returns a context where the origin of the coordinate system is at the upper left corner, instead of the lower left corner. 

The context can be flipped in one way like this:
http://www.informit.com/articles/article.aspx?p=2149190&seqNum=11

Another possibility is to flip the image before giving it to the context for drawing. 

I'll try to post a working solution soon! Thanks again! :)

**Comment by daniel-luberda** [comment]
Fixed, thanks @PRopia99 for the details.
