### ISSUE TITLE
Xamarin.Forms - Embedded Resource SVG not working 2.4.4.859

### ISSUE THREAD

**Issue by nschoenberg** [luberda-molinet/FFImageLoading#1188]
### Description

Recently upgraded from 2.4.3.840 to 2.4.4.859. Since the update embedded resource svg does not work.

### Steps to Reproduce

This code is working fine in 2.4.3.840
```
protected override void OnAppearing() {
  svgimg.Source = SvgImageSource.FromResource("Futura.IA.Resources.Images.boot_sequence_backend_connection.svg", typeof(BootSequencePage).Assembly, 100, 100);
}
```

The SVG im using:

[boot_sequence_backend_connection.svg.zip](https://github.com/luberda-molinet/FFImageLoading/files/2786225/boot_sequence_backend_connection.svg.zip)

It is working with embedded jpg that is located in the same directory.

### Expected Behavior

The image is shown with updated version.

### Actual Behavior
It is not shown in UWP nor Android. iOS Untested (All Xamarin Forms)

### Basic Information

- Version with issue: 2.4.4.859 
- Last known good version: 
Xamarin.FFImageLoading.Svg.Forms Version="2.4.3.840"
Xamarin.FFImageLoading.Transformations Version="2.4.3.840"
Xamarin.Forms" Version="3.4.0.1008975"

**Comment by irongut** [comment]
I notice your SVG has a translation in it:

`transform="translate(-1280 -320)"`

This is probably the same issue as #1157 and the v2.4.5.860-pre prerelease may work for you although it has other issues. See [my coment](https://github.com/luberda-molinet/FFImageLoading/issues/1157#issuecomment-447601446) in that issue.

**Comment by nschoenberg** [comment]
> I notice your SVG has a translation in it:
> 
> `transform="translate(-1280 -320)"`
> 
> This is probably the same issue as #1157 and the v2.4.5.860-pre prerelease may work for you although it has other issues. See [my coment](https://github.com/luberda-molinet/FFImageLoading/issues/1157#issuecomment-447601446) in that issue.

Can confirm it is related to the `transform="translate(-1280 -320)"`. I used the tool that is linked in Wiki "SVG Support" (https://jakearchibald.github.io/svgomg/) to shrink my svg files. For the most SVG files the tool removed the transform code and the result was a fine rendering image. But it has not worked for every SVG so I ended with a custom symbolic font that I use for icons

**Comment by daniel-luberda** [comment]
Fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/df7b058bc8e2ebd2e6a60d4ab4b9fef4c0343d43
![Screen Shot 2019-04-06 at 17 29 08](https://user-images.githubusercontent.com/13569983/55671558-8b2d1300-5891-11e9-9656-5225da263037.png)
