### ISSUE TITLE
Ability to define dimensions for LoadingPlaceholder

### ISSUE THREAD

**Issue by adrianknight89** [luberda-molinet/FFImageLoading#1190]
As of now, it seems that `LoadingPlaceholder` will take up the whole space for `CachedImage`. Any gif I use as a placeholder gets stretched out. It'd be great to have a way to define sizing for this property. Ideally, I'd like to avoid adding `ActivityIndicator` or another workaround to create a loader. I'm getting unreliable Finish/Success events on the `CachedImage` and sometimes `ListView` recycling makes things even worse, so using `LoadingPlaceholder` seems to be the best way.

**Comment by daniel-luberda** [comment]
Hi @adrianknight89  Love the idea. Let's continue here: 
https://github.com/luberda-molinet/FFImageLoading/issues/1196
