### ISSUE TITLE
CachedImage doesn't fit in requested size when AspectFill is set

### ISSUE THREAD

**Issue by roubachof** [luberda-molinet/FFImageLoading#1191]
### Description

[Android] ```CachedImage``` doesn't fit in requested size when ```Aspect="AspectFill"``` is set.

### Steps to Reproduce

```xml
<ffil:CachedImage Grid.Row="0"
                  Grid.RowSpan="4"
                  Grid.Column="0"
                  WidthRequest="80"
                  HeightRequest="80"
                  HorizontalOptions="Center"
                  VerticalOptions="Center"
                  Aspect="AspectFill"
                  DownsampleToViewSize="true"
                  ErrorPlaceholder="m_065_n6_placeholder_image_cheval_manquante_big.png"
                  IsOpaque="True"
                  LoadingPlaceholder="m_065_n6_placeholder_image_cheval_manquante_big.png"
                  Source="{Binding Image}" />
```

### Expected Behavior

The image should stay in the requested bounds (here 80x80).

### Actual Behavior

It "leaks" out of its frame.

### Basic Information

- Version with issue: 2.4.4.859, 2.4.5.860-pre
- Last known good version: 2.4.3.840
- Platform: Android

### Screenshots

![image](https://user-images.githubusercontent.com/596903/52073372-98730c00-2587-11e9-8099-dbd0ef2210ba.png)

![image](https://user-images.githubusercontent.com/596903/52073461-e0922e80-2587-11e9-88ad-259060d6c9e3.png)

### Reproduction Link / Code

Another example:
```xml
<ffil:CachedImage WidthRequest="40"
                  HeightRequest="40"
                  HorizontalOptions="Center"
                  VerticalOptions="Center"
                  AbsoluteLayout.LayoutBounds="0,0.5,50,50"
                  AbsoluteLayout.LayoutFlags="PositionProportional"
                  Aspect="AspectFill"
                  DownsampleToViewSize="true"
                  DownsampleUseDipUnits="true"
                  DownsampleWidth="40"
                  ErrorPlaceholder="m_065_n6_placeholder_image_cheval_manquante_big"
                  LoadingPlaceholder="m_065_n6_placeholder_image_cheval_manquante_big"
                  Source="{Binding HorseImage}" />
```

**Comment by rredoh** [comment]
Hi.. Kindly check here https://github.com/luberda-molinet/FFImageLoading/issues/1148

**Comment by daniel-luberda** [comment]
It should be fixed (use prerelease nuget) https://github.com/luberda-molinet/FFImageLoading/pull/1170

**Comment by adrianknight89** [comment]
@daniel-luberda I updated to 2.4.5.880-pre, but all of my SVG images disappeared.

**Comment by sniemuth-equiniti** [comment]
@daniel-luberda I had the same problem when upgrading to 2.4.5.880-pre, all of my SVG images disappeared. I deleted obj and bin folders as well to confirm it was clean.
