### ISSUE TITLE
SetPauseWork(true) has no effect

### ISSUE THREAD

**Issue by devopsone** [luberda-molinet/FFImageLoading#1192]
### Description

SetPauseWork(true) has no effect. CachedImage still triggers download of url resources

### Steps to Reproduce

Use SetPauseWork(true) and for example display a list with cached image items. After you move the list the images start to load.

### Expected Behavior

Images should not load until SetPauseWork(false) is set.

### Actual Behavior

Images start to load

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: 
- Platform: Tested on Xamarin Droid

**Comment by daniel-luberda** [comment]
Currently `PauseWork` is implemented in a way which stops loading of new image loading requests, not existing ones. See: https://github.com/luberda-molinet/FFImageLoading/blob/bd411cea6330b669569c84e6307c139104c9cd38/source/FFImageLoading.Common/Work/WorkScheduler.cs#L206

Is it what you experience?

**Comment by devopsone** [comment]
I use it for fast scrolling as described in the documentation. While fast scrolling i can see that the backend gets dozens of incoming new request (not already running ones). It's true that the files are not loaded over the net but the requests still arrive on the backend.

**Comment by daniel-luberda** [comment]
You should probably use `SetExitTasksEarly` which also cancels all tasks. I know it's name is misleading, I'll have  to change it.

**Comment by devopsone** [comment]
Hi Daniel, I will try that, thanks

**Comment by daniel-luberda** [comment]
FFImageLoading 2.4.6:

obsoleted `SetExitTasksEarly` added new methods with better naming: 
```C#
ImageService.Instance.SetPauseWork(bool pauseWork, bool cancelExisting = false)
ImageService.Instance.SetPauseWorkAndCancelExisting(bool pauseWork)
```
