### ISSUE TITLE
Success event does not execute

### ISSUE THREAD

**Issue by eclipsed4utoo** [luberda-molinet/FFImageLoading#1195]
### Description

When creating a `CachedImage` in code and giving it a `Source`, neither the `Success` not `Error` events fire. I am attempting to find the height/width ratio of an image that was retrieved/taken using the Media plugin. I have tried using `ImageSource.FromUri`, `ImageSource.FromString`, and `ImageSource.FromFile`, and none of them fire the 2 events.

### Steps to Reproduce

See code below. The task never completes because neither event fires.

### Expected Behavior

The `Success` or `Error` event should fire.

### Actual Behavior

Neither the Success not Error events fire.

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: N/A
- Platform: iOS

### Reproduction Link / Code

    private async Task<double> GetImageRatio()
    {
        var ratio = 0d;
        var cachedImage = new CachedImage {
            WidthRequest = 500,
            HeightRequest = 500,
            DownsampleToViewSize = true
        };

        var task = new TaskCompletionSource<double>();
        cachedImage.Success += (sender, e) =>
        {
            var h = e.ImageInformation.OriginalHeight;
            var w = e.ImageInformation.OriginalWidth;

            var r = w / h;
            task.TrySetResult(r);
        };

        cachedImage.Error += (sender, e) => {
            task.TrySetException(e.Exception);
        };

        cachedImage.Source = ImageSource.FromFile(_selectedFile.Path);// ImageSource.FromStream(() => _selectedFile.GetStream());

        ratio = await task.Task;

        return ratio;
    }

**Comment by daniel-luberda** [comment]
`cachedImage` is not added to views hierarchy. It won't work as it's not displayed. 

Maye you should use fluent API instead? See this: https://github.com/luberda-molinet/FFImageLoading/wiki/API

**Comment by flamecrow** [comment]
> ### Description
> When creating a `CachedImage` in code and giving it a `Source`, neither the `Success` not `Error` events fire. I am attempting to find the height/width ratio of an image that was retrieved/taken using the Media plugin. I have tried using `ImageSource.FromUri`, `ImageSource.FromString`, and `ImageSource.FromFile`, and none of them fire the 2 events.
> 
> ### Steps to Reproduce
> See code below. The task never completes because neither event fires.
> 
> ### Expected Behavior
> The `Success` or `Error` event should fire.
> 
> ### Actual Behavior
> Neither the Success not Error events fire.
> 
> ### Basic Information
> * Version with issue: 2.4.4.859
> * Last known good version: N/A
> * Platform: iOS
> 
> ### Reproduction Link / Code
> ```
> private async Task<double> GetImageRatio()
> {
>     var ratio = 0d;
>     var cachedImage = new CachedImage {
>         WidthRequest = 500,
>         HeightRequest = 500,
>         DownsampleToViewSize = true
>     };
> 
>     var task = new TaskCompletionSource<double>();
>     cachedImage.Success += (sender, e) =>
>     {
>         var h = e.ImageInformation.OriginalHeight;
>         var w = e.ImageInformation.OriginalWidth;
> 
>         var r = w / h;
>         task.TrySetResult(r);
>     };
> 
>     cachedImage.Error += (sender, e) => {
>         task.TrySetException(e.Exception);
>     };
> 
>     cachedImage.Source = ImageSource.FromFile(_selectedFile.Path);// ImageSource.FromStream(() => _selectedFile.GetStream());
> 
>     ratio = await task.Task;
> 
>     return ratio;
> }
> ```

Any tips on this?
