### ISSUE TITLE
ImageInformation not populated on Success Event for Animated Gifs on Android

### ISSUE THREAD

**Issue by DKWaters** [luberda-molinet/FFImageLoading#1197]
### Description
On a minimal repo, without any additional libraries or components installed, Animated GIFs (and this may apply to non-animated GIFs but I have not tested) do not provide ImageInformation on the Success callback on Android only.  It works perfectly on iOS.  It does not seem to matter what type of control or layout is used.  I thought maybe there was an order of operations issue with the rendering/sizing/inflation order depending on the layout but that does not seem to be the case.   

### Steps to Reproduce

1. Create an empty XamForms project. 
2. Add a CachedImage with a URL source to an animated GIF.
3. Add Success callback, inspect ImageInformation.

### Expected Behavior

ImageInformation should be populated

### Actual Behavior

ImageInformation has 0 values for OriginalWidth, CurrentWidth, OriginalHeight and CurrentHeight.

### Basic Information

- Version with issue: 2.4.4.850
- Last known good version: Unknown
- Platform: Android

### Code

[BugDemo.zip](https://github.com/luberda-molinet/FFImageLoading/files/2869692/BugDemo.zip)

**Comment by DKWaters** [comment]
**Update:** I have a working fix for this issue which I will submit a PR for.  Don't want to commit to a timeline for it, though.  Hopefully I get around to it in the next few days.

**Comment by kenchan97** [comment]
+1 same issue

**Comment by daniel-luberda** [comment]
@DKWaters Looking forward for a PR :)

**Comment by DKWaters** [comment]
Wow, can't believe it's been 21 days.  Time flies.  I will get this pushed up in the next 24 hours.  Competing priorities…as always.  :-)
