### ISSUE TITLE
v2.4.5.867-pre, Android FastRenderer - no background color

### ISSUE THREAD

**Issue by pkolosov** [luberda-molinet/FFImageLoading#1198]
### Description

v2.4.5.867-pre, Xamarin.Forms 3.5.0, Android 8.1.

No background color where

FFImageLoading.Forms.Platform.CachedImageRenderer.Init(**enableFastRenderer: true**);

If **enableFastRenderer: false**, then background color is presented.

### Basic Information

- Version with issue: v2.4.5.867-pre
- Last known good version: 2.4.2 + Xamarin.Forms 3.1
- Platform: Xamarin.Forms 3.5 + Android

**Comment by adrianknight89** [comment]
I could confirm that the image has no background color on Android when fast renderers are enabled.
