### ISSUE TITLE
XF Android Distortion Issue

### ISSUE THREAD

**Issue by barrysohl** [luberda-molinet/FFImageLoading#1199]
I'm having an odd issue with FFImageLoading images in XF Android. The first time the image is displayed, everything is perfect. But then for all subsequent displays (anywhere in the app), the image is oddly distorted. See the attached screenshots of the same image displayed the first time normally and then distorted the second time (after leaving the page and returning to it, which uses a new image instance).

If I simply re-layout the content, there is no problem. It only happens when there is a new instance with the same image being displayed. The problem does not happen at all on iOS.

I am using 2.4.4.859.

Any ideas? Thanks in advance!

![normal](https://user-images.githubusercontent.com/9275704/53053970-c7c6bb80-3457-11e9-8cf4-52813e9d667c.jpg)
![skewed](https://user-images.githubusercontent.com/9275704/53053981-d01ef680-3457-11e9-81dc-54418e6168c2.jpg)

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#downsampletoviewsize-bool-default-false
