### ISSUE TITLE
[Question] Is it possible to change the scaling algorithm?

### ISSUE THREAD

**Issue by Sebastian1989101** [luberda-molinet/FFImageLoading#1202]
Is there a way to change the algorithm used for image scaling? It would be a great option to choose between Bicubic, Pixelated and Bilinear. I didn't find any option like that and if I scale my images to a bigger size, all images looks pretty much washed out while all of them are pixel art so a pixelated upscaling would be perfect in my case.

**Comment by daniel-luberda** [comment]
Unfortunately it can only be done on iOS and Windows, see custom configuration: `DownsampleInterpolationMode`. On Android it can't be implemented easily, as we use entirely different downsampling strategy (bitmap insample size)
