### ISSUE TITLE
User feedback on SVG button

### ISSUE THREAD

**Issue by mkgitalia** [luberda-molinet/FFImageLoading#1207]
Hello,
I am using a lot of SVG icons for buttons in my Xamarin.Forms App, however, users havent a feedback when pressed It. Can you suggest me a simple way to make it?
Thanks

**Comment by mkgitalia** [comment]
Ops, I'm using MVVM pattern...

**Comment by daniel-luberda** [comment]
We plan to implement CachedButton soon.
