### ISSUE TITLE
How to get disk cache path

### ISSUE THREAD

**Issue by Inrego** [luberda-molinet/FFImageLoading#1214]
I am using ffimageloading to show image thumbnails with cache to disk enabled. I want to tap on an image, and then send the cached image to another view which shows the photo in full screen with pinch and pan functionality (or possibly open default photo viewer app on device by opening uri).

I just can't figure out how to get it. Here's what I've tried:

I created a CachedKeyFactory which I am using on the thumbnails like this:

    <forms:CachedImage Source="{Binding Url}" CacheType="Disk" CacheDuration="30" DownsampleToViewSize="True">
      <forms:CachedImage.CacheKeyFactory>
        <helpers:CachedPhotoKeyFactory />
      </forms:CachedImage.CacheKeyFactory>
      <forms:CachedImage.GestureRecognizers>
        <TapGestureRecognizer Command="{Binding Path=ViewModel.PhotoTappedCommand, Source={x:Reference CurrentPage}}" CommandParameter="{Binding .}" />
      </forms:CachedImage.GestureRecognizers>
    </forms:CachedImage>

This KeyFactory simply just returns the original filename, since it already includes a unique ID.
I've set breakpoint in my KeyFactory to be certain that it is indeed used, and I see breakpoint being hit for every shown thumbnail.

However, when I check the values of _entries in `ImageService.Instance.Config.DiskCache`, I see all the images, but not with the keys specified from my KeyFactory. All the keys have default KeyFactory values like these: `1A9938FCC52A4BFC9E42330AA33CE3AB`

Also checking the /data/user/0/com.companyname.appname/cache/FFSimpleDiskCache folder, there are files for each thumbnail, with those keys (not my own).

I expect possible solutions to be either:

* Find the cache key by providing uri (without custom CachedKeyFactory).
* Find file path of cached photos by my own cache key from my custom CachedKeyFactory

But other solutions for my problem, are also welcome.

Edit: On another note, I even tried sticking with FFImageLoading for the full-screen image. But the performance for pinch and pan was abysmal and not usable at all. I used the same implementation as here: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/Transformations/CropTransformationPage.xaml

**Comment by daniel-luberda** [comment]
To get filename by key use this:

```C#
ImageService.Instance.MD5Helper.MD5("https://yourfileUrlOrKey")
```

**Comment by Inrego** [comment]
@daniel-luberda I don't see `MD5Helper` on `ImageService.Instance`?
I am using Xamarin.Forms with FFImageLoading version 2.4.4.859

**Comment by Inrego** [comment]
NVM, I found it! It's in `ImageService.Instance.Config.MD5Helper`
