### ISSUE TITLE
TransparencyEnabled is gone?

### ISSUE THREAD

**Issue by EmmanVazz** [luberda-molinet/FFImageLoading#1215]
I might be blind but TransparencyEnabled seems to be gone CachedImage for Forms in the code. Is there a replacement for it?

**Comment by EmmanVazz** [comment]
Ah wiki still refers to https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#transparencyenabled-bool-default-null when it should be updated for BitmapOptimizations

**Comment by daniel-luberda** [comment]
I'll update the wiki. Thanks for noticing.

BTW: everyone can edit wiki. Cheers.
