### ISSUE TITLE
SvgCachedImage has some sort of padding

### ISSUE THREAD

**Issue by ZARk-be** [luberda-molinet/FFImageLoading#1218]
### Description

I quickly prototyped my app with png exports of svg files. Now that i found FFImageLoading as a great way to load svg, i'm replacing them with their svg files. But now my layouts have changed. I have checked, and the viewbox defined in the svg covers just the paths.

### Steps to Reproduce

export a svg file to png.
Add it once with CachedImage and once with SvgCachedImage.
SvgCachedImage will have some hidden margin.
### Expected Behavior

Normally, with CachedImage, the parent grid would size to fit the image.

### Actual Behavior

with svgCachedImage the grid suddenly becomes bigger, as if a there was a Margin.
The xaml was only changed to use a SvgCachedImage instead of CachedImage

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: xxxxxxx
- Platform:  Android

### Screenshots

![svg_normal](https://user-images.githubusercontent.com/2575335/54376448-632c0480-4683-11e9-8141-37c9877c0235.png)

![svg_error](https://user-images.githubusercontent.com/2575335/54377560-a7200900-4685-11e9-97f3-fb6fc41b420f.png)

### Reproduction Link / Code
```

<?xml version="1.0" encoding="UTF-8"?>
<Grid xmlns="http://xamarin.com/schemas/2014/forms" 
      xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
      xmlns:forms="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
      xmlns:forms1="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
      x:Class="SaturdayMan.SMButton"
      Margin="0" Padding="0" RowSpacing="0" x:Name="Grid" SizeChanged="ContentView_SizeChanged" VerticalOptions="Start" BackgroundColor="AliceBlue">



    <forms1:SvgCachedImage x:Name="bgImage" Aspect="AspectFit" Margin="0" VerticalOptions="Start" />
    <BoxView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" x:Name="measureViewBox" />
        <Label x:Name="Label" FontFamily="{StaticResource NormalFont}" HorizontalTextAlignment="Center" VerticalTextAlignment="Center" VerticalOptions="Center" HorizontalOptions="Center" TextColor="White" Margin="0" />
    
</Grid>

```

**Comment by daniel-luberda** [comment]
- Please attach your SVG file
- Please notice, that SVG text support had a lot of fixes / improvements in recent 2.4.6 version.
