### ISSUE TITLE
Xamarin.Android sample code for round corner

### ISSUE THREAD

**Issue by hasanhd1355** [luberda-molinet/FFImageLoading#1219]
### Description

I need a sample code for rounded tranformation on a FFImageLoading.Views.ImageViewAsync.

thanks

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform:

**Comment by daniel-luberda** [comment]
See: 

ViewModel: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.MvvmCross.Sample/FFImageLoading.MvvmCross.Sample.Core/ViewModels/Image.cs#L12

iOS: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.MvvmCross.Sample/FFImageLoading.MvvmCross.Sample.iOS/CustomTableViewCell.cs#L37

Android: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.MvvmCross.Sample/FFImageLoading.MvvmCross.Sample.Droid/Resources/layout/item_image.axml#L7-L10
