### ISSUE TITLE
[Question] Handling cached downsampled/transformed images in disk

### ISSUE THREAD

**Issue by RedasP** [luberda-molinet/FFImageLoading#1221]
Hello, I have exactly the same problem as stated in #837, #260 and #532 - in short I want to cache the downsampled image, but I have an additional question.

In #837 it was suggested to do it like this: 

```
using (var stream = await ImageService.Instance.LoadFile("/Path").DownSample(width: 200).AsJPGStreamAsync())
{
//save stream to disk and use that path later as image source
}
```

But if I save the stream to disk and load the image later using CachedImage, will CachedImage remove it from cache and disk when duration is expired or will I have to manually remove from these places when it's expired?

**Comment by daniel-luberda** [comment]
Hi @RedasP 

> But if I save the stream to disk and load the image later using CachedImage, will CachedImage remove it from cache and disk when duration is expired or will I have to manually remove from these places when it's expired?

It won't automatically delete it, but you use your disk cache  implementation on your own:

```C#
ImageService.Instance.Config.DiskCache.AddToSavingQueueIfNotExistsAsync(AddToSavingQueueIfNotExistsAsync(string key, byte[] bytes, TimeSpan duration, Action writeFinished = null);

ImageService.Instance.Config.DiskCache.GetFilePathAsync(string key);

// etc...
```

**Comment by RedasP** [comment]
Thanks for your response, @daniel-luberda 

I think I've resolved this issue kind of differently. I did this by creating my own instance of SimpleDiskCache and registering it to DependencyService. 

Then I do something like this:

```
using (var stream = await ImageService.Instance.LoadFile("/Path").DownSample(width: 200).AsJPGStreamAsync())
{
     DependencyService.Get<IDiskCache>().AddToSavingQueueIfNotExistsAsync(...);
}
```

1. Would this handle the deletion of image?
2. Do you think it's a valid alternative to implementing my own methods?

**Comment by daniel-luberda** [comment]
> Would this handle the deletion of image?
Yes, it would clean old files automatically, but make sure you register it as a singleton. 

> Do you think it's a valid alternative to implementing my own methods?
It's just as good solution. You would have a separate cache for resized files if you provide different path.
