### ISSUE TITLE
Transformations are not clear on documentation

### ISSUE THREAD

**Issue by titonton** [luberda-molinet/FFImageLoading#1222]
I'm not sure if I'm the only one, but the documentation on transformations is not very clear. I'm not exactly sure how to apply them or where the class is being housed in the assembly. Am I missing something or am I just blind?

**Comment by titonton** [comment]
Apologies I figured it out. I was just blind and I wasn't following the tutorial correctly. I forgot to install the  package. I had only installed the Xamarin.FFImageLoading.Forms and Xamarin.FFImageLoading.Transformations packages without Xamarin.FFImageLoading package. Thanks for the your hard work guys!

**Comment by adrianknight89** [comment]
@titonton @daniel-luberda Can this be closed?

**Comment by titonton** [comment]
@adrianknight89 yes it can. Sorry for the late reply

**Comment by daniel-luberda** [comment]
BTW: anyone can edit wiki (feel free to update it). Cheers.
