### ISSUE TITLE
Android crash on startup 

### ISSUE THREAD

**Issue by ndastur** [luberda-molinet/FFImageLoading#1224]
### Description

I have updated to XF 3.6.0 and now the android app crashes on startup throwing a TypeLoadException

Could not load list of method overrides due to Method not found: void Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)

I have tried a project clean and deletion of bin/obj with no effect

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: 2.4.4.859 did work with XF 3.5.x
- Platform: Android

**Comment by marcioreck** [comment]
+1

**Comment by marcioreck** [comment]
FFImageLoading preRelease v2.4.5.870 works with XF 3.6.0.264807.

**Comment by marcioreck** [comment]
FFImageLoading preRelease v2.4.5.870 works with XF 3.6.0.264807 too!

**Comment by ndastur** [comment]
Thank you. The pre-release version does work. Thank you.

**Comment by PeteVasi** [comment]
@daniel-luberda : Any news on when this pre-release might become a real release?

**Comment by daniel-luberda** [comment]
@PeteVasi I'll try to release it by this weekend. Meanwhile, I'll close it as it's fixed. Cheers.
