### ISSUE TITLE
Run fade animation each time the Source changes

### ISSUE THREAD

**Issue by goldmont** [luberda-molinet/FFImageLoading#1226]
- Platform: Android
- Version with issue: 2.4.3.840

Hi,

we're making a gallery App and we need to display some images in a graceful way. Currently we have just one instance of CachedImage in our XAML and we were wondering whether it's possible to run the fade animation each time we change the Source property because, when the image is already loaded, it changes with no animation. Waiting for a prompt reply. Thank you for your efforts.

Best regards.

**Comment by daniel-luberda** [comment]
It should work with a custom config: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Config/Configuration.cs#L21
