### ISSUE TITLE
SVG not rendered properly

### ISSUE THREAD

**Issue by thisisthekap** [luberda-molinet/FFImageLoading#1227]
### Description

The atttached SVG file is not rendered properly with FFImageLoading 2.4.5.870-pre (but rendered properly with FFImageLoading 2.4.4.859).

### Steps to Reproduce

Upgrade to FFImageLoading 2.4.5.870-pre.

### Expected Behavior

SVG rendered as when using FFImageLoading 2.4.4.859.

### Actual Behavior

SVG not rendered properly.

### Basic Information

- Version with issue: 2.4.5.870-pre
- Last known good version: 2.4.4.859.
- Platform: Xamarin.Android

### Screenshots

**Expected:**

<img width="525" alt="proper" src="https://user-images.githubusercontent.com/9071974/54939815-cb070880-4f29-11e9-9adc-c945ec156fa9.png">

**Actual:**

<img width="532" alt="failed" src="https://user-images.githubusercontent.com/9071974/54939839-d9edbb00-4f29-11e9-9878-af1ee97bcdb7.png">

### Reproduction Link / Code

The used SVG:
[ActivitiesSelectionCampaignBackground.svg.txt](https://github.com/luberda-molinet/FFImageLoading/files/3004616/ActivitiesSelectionCampaignBackground.svg.txt)

**Comment by ysmoradi** [comment]
I've the same issue )-:

**Comment by PWaliaDev** [comment]
I've also same issue. SVG images are not rendering correctly. :(

**Comment by ysmoradi** [comment]
I uploaded my svg to some sites to convert them into png file. Interestingly some sites's returned a problematic png (With exactly the same problem as this issue) and some of them were able to produce a beautiful png! ;D

**Comment by daniel-luberda** [comment]
Fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/df7b058bc8e2ebd2e6a60d4ab4b9fef4c0343d43

**Comment by thisisthekap** [comment]
The fix is available in version 2.4.5.880-pre (https://www.nuget.org/packages/Xamarin.FFImageLoading/2.4.5.880-pre). Thanks @daniel-luberda for your work!
