### ISSUE TITLE
Do you still recommend using OnBindingContextChanged instead of setting Source through XAML?

### ISSUE THREAD

**Issue by adrianknight89** [luberda-molinet/FFImageLoading#1228]
@daniel-luberda I was just reading [this page](https://github.com/luberda-molinet/FFImageLoading/wiki/Advanced-Usage) and would like to understand if you still recommend using `OnBindingContextChanged` instead of setting the `Source` property through XAML. I also saw your [comment](https://forums.xamarin.com/discussion/105393/listview-not-performing-good) about `OneTime` bindings on the XF forum. I'm currently seeing performance degradation due to both images and `FormattedString` and would like to keep it minimal. :)

**Comment by daniel-luberda** [comment]
Hi @adrianknight89 

It should have similar performance. IMO I should mention `BindingMode.OneTime` on the wiki here: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#usage-in-listview-with-listviewcachingstrategyrecycleelement-enabled
