### ISSUE TITLE
SetStateMachine System.InvalidOperationException: The builder was not properly initialized.

### ISSUE THREAD

**Issue by mclillill** [luberda-molinet/FFImageLoading#1229]
### Description

CachedImageFastRenderer+<ImageLoadingSizeChanged>d__46.SetStateMachine (System.Runtime.CompilerServices.IAsyncStateMachine stateMachine)
System.InvalidOperationException: The builder was not properly initialized.
    AsyncMethodBuilderCore.SetStateMachine (System.Runtime.CompilerServices.IAsyncStateMachine stateMachine)
    AsyncVoidMethodBuilder.SetStateMachine (System.Runtime.CompilerServices.IAsyncStateMachine stateMachine)
    CachedImageFastRenderer+<ImageLoadingSizeChanged>d__46.SetStateMachine (System.Runtime.CompilerServices.IAsyncStateMachine stateMachine)
    AsyncVoidMethodBuilder.AwaitUnsafeOnCompleted[TAwaiter,TStateMachine] (TAwaiter& awaiter, TStateMachine& stateMachine)
    AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state)
    QueueUserWorkItemCallback.WaitCallback_Context (System.Object state)
    ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
    IThreadPoolWorkItem.ExecuteWorkItem ()
    ThreadPoolWorkQueue.Dispatch ()
    _ThreadPoolWaitCallback.PerformWaitCallback ()

### Steps to Reproduce

Don't know

### Expected Behavior

Does not crash

### Actual Behavior

Crashes

### Basic Information

- Version with issue: 2.4.5.860-pre
- Last known good version: -
- Platform: Android

### Screenshots

-

### Reproduction Link / Code

-

**Comment by daniel-luberda** [comment]
Could you make a repo?
