### ISSUE TITLE
Enhancement - GlideX support

### ISSUE THREAD

**Issue by Pinox** [luberda-molinet/FFImageLoading#1230]
Hi Daniel,

I use FFimageloading extensively in my XF Android app. Thank you.  Recently stumbled upon GlideX for XF Android.

As Glide is recommended even by google for images in Android the performance gains is huge especially in memory consumption as can be seen on their GitHub page.

https://github.com/jonathanpeppers/glidex

please consider as an option glidex compatibility in future enhancements of FFimageloading as I think it will make this lib super performant on Android.

**Comment by daniel-luberda** [comment]
It's a nice idea, but to allow things like cross platform transformations and shared configuration it won't be easy to integrate. I would prefer to replicate the same mechanisms as glidex uses for image caching. I have already started working on this, but don't have much free time lately.

**Comment by daniel-luberda** [comment]
BTW: new prerelease nuget should be a lot more performant, especially on Android.

**Comment by daniel-luberda** [comment]
Currently, FFImageLoading's memory cache cache works the same as Glide's memory cache (LRU bitmap cache + reusable bitmap drawables cache). What we should concentrate is:
- optimize code and limit .NET objects creation to prevent a lot of GC calls. 
- Tune default settings as `DecodingMaxParallelTasks`, `SchedulerMaxParallelTasks`, default cache size, etc

BTW: You can now easily use FFImageLoading with standard views like Xamarin.Forms.Image. Just call this after `Xamarin.Forms.Init` call:

- `CachedImageRenderer.InitImageViewHandler()` on Android
- `CachedImageRenderer.InitImageSourceHandler()` on iOS / Mac and others

**Comment by Pinox** [comment]
Thanks @daniel-luberda , enjoy the coffee ;)   

I assume we can then replace CachedImageRenderer.Init() with CachedImageRenderer.InitImageViewHandler()  to do both existing functionality + Xamarin.Forms.Image  ?

**Comment by daniel-luberda** [comment]
Thanks! Yes, both are needed :)
