### ISSUE TITLE
FFImageLoading not working with Xamarin.Forms Material Visual

### ISSUE THREAD

**Issue by LeoJHarris** [luberda-molinet/FFImageLoading#1234]
Hi all, a new feature added to Xamarin is Xamarin.Forms Material Visual, you can find it here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual

When I add Material Visual library library to a project using this library I am getting a run-time exception:

Constructor on type 'FFImageLoading.Forms.Platform.CachedImageFastRenderer' not found.

I tested with Xamarin Forms: 3.6.0.293080, Xamarin.FFImageLoading.Forms (and Xamarin.FFImageLoading.Transformations): 2.4.5.870-pre

Attached is the Stacktrace:

[stacktrace.txt](https://github.com/luberda-molinet/FFImageLoading/files/3041263/stacktrace.txt)

Anyone else seeing this issue?

**Comment by InquisitorJax** [comment]
yup - seeing this as well. Rolling back works:
XF: 3.6.0.293080
FFImageLoading: 2.4.4.859

**Comment by LeoJHarris** [comment]
@InquisitorJax That didn't work for me, deleted the bin and obj folders:

Still getting:

System.TypeLoadException: Could not load list of method overrides due to Method not found: void Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)

Im using
XF & Visual.Material: 3.6.0.293080
FFImageLoading: 2.4.4.859

**Comment by LeoJHarris** [comment]
@InquisitorJax Sorry the above issue when rolling back might have to do https://github.com/luberda-molinet/FFImageLoading/issues/1154#issuecomment-480989539 this time.

**Comment by Kiitoksia** [comment]
Also experiencing this issue.  Rolling back solved this.
To solve the TypeLoadException, roll back to 2.3.6 for android (other projects can remain on 2.4+).  I haven't been able to get any updates later than this to work at all.

**Comment by InquisitorJax** [comment]
In another project referencing the Xamarin Forms 4 pre builds, I had to downgrade all the packages to 2.3.6.
Downgrading only the android reference didn't work for me.

**Comment by bentmar** [comment]
Visual="Default" add this to you images  and it will work

**Comment by bentmar** [comment]
(havent looked at code) But it seems like a bold upgrade from xf team to assume that every visual element has a default implementation of Materialrenderers and throws an uncoverable exception if they dont

**Comment by daniel-luberda** [comment]
Here's the fix: https://github.com/luberda-molinet/FFImageLoading/pull/1246 - but I didn't test it yet.

**Comment by daniel-luberda** [comment]
Fixed
