### ISSUE TITLE
I have Asset in drawable-xxxhdpi folder but unable to load image as ErrorPlaceHolder

### ISSUE THREAD

**Issue by VIKAS9899** [luberda-molinet/FFImageLoading#1236]
ImageService.Instance.LoadUrl(url, AppConstant.Static.ImageCacheTimeSpan)
                    .LoadingPlaceholder(placeholder, ImageSource.CompiledResource)
                    .ErrorPlaceholder(errorPlaceholder, ImageSource.CompiledResource)
                    .WithCache(FFImageLoading.Cache.CacheType.Disk)
                    .IntoAsync(imageView);

**Comment by daniel-luberda** [comment]
Could you attach a repo? It can be anything.
