### ISSUE TITLE
how can i add the lastest ver to my shared proect ?

### ISSUE THREAD

**Issue by kenchan97** [luberda-molinet/FFImageLoading#1237]
i try different method ,
and it show me an error  i had referenced a portable version FFimageloading.
and it exited?

**Comment by albilaga** [comment]
Do you already install it in your specific project (Android, and iOS) and also initialize it?

**Comment by daniel-luberda** [comment]
It's all described here: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#step-1
