### ISSUE TITLE
Fallback URI when Image Source not found

### ISSUE THREAD

**Issue by nicolasdeory** [luberda-molinet/FFImageLoading#1238]
I am aware of `ErrorPlaceholder`, but it's not exactly what I'm looking for.

Is there a way to specify a fallback URI so if the first one fails (URL not found), it tries the second one? If both fail then `ErrorPlaceholder` would be loaded instead.

Maybe an option could be to specify the second URI as the ErrorPlaceholder. But how could I load the real error placeholder if the second `URIImageSource` fails? Perhaps there is a way to know when the second URI fails so the placeholder image can manually be set?

**Comment by daniel-luberda** [comment]
Hi @nicolasdeory 

- There's no such option. I don't think we should implement it as it isn't widely used scenario. 
- You should be able to implement it easily by handling `Error` callbacks.
