### ISSUE TITLE
Loading Placeholders don't work properly

### ISSUE THREAD

**Issue by nicolasdeory** [luberda-molinet/FFImageLoading#1239]
Loading Placeholders take a while to load (they are local images), and when they appear the real image has almost finished loading so the placeholder is seen for less than half a second.

### Steps to Reproduce

Create a `CachedImage`, specify an `URIImageSource` as `Source`, a local path as `LoadingPlaceholder`, and load a list of ~90 images at the same time.

### Expected Behavior

Before, they would almost appear at once, as ~90 loading placeholders, which then would progressively fade into the actual images.

### Actual Behavior

Now the list takes a while to populate, indicating that `CachedImage`s are taking a while to display anything at all. However, when they finally appear (about 0.5s-1s), the image is almost fully loaded so it almost instantly fades to the `URIImageSource` image, with the loading placeholder barely visible, for ~0.4s.

### Basic Information

- Version with issue: Both 2.4.5.870-pre and 2.4.5.880-pre
- Last known good version:  2.3.6 (not entirely sure)
- Platform: XF 3.6.0

### Screenshots

I can't post pictures right now, but if the issue is not described clearly enough I can post them later in the day.

**Comment by daniel-luberda** [comment]
1. There's a default delay enabled. You can disable it via custom config. It's useful in list view scenarios. 
`DelayInMs = 10; //Task.Delay resolution is around 15ms`
2. If it's other reason, please attach a repo.

**Comment by nicolasdeory** [comment]
I'm out of town until the weekend. I will post back then.

**Comment by daniel-luberda** [comment]
Fixed
