### ISSUE TITLE
Tizen Support

### ISSUE THREAD

**Issue by tomh4** [luberda-molinet/FFImageLoading#1243]
Is Tizen still supported ? 
I am getting the following error : 
System.IO.FileLoadException: Could not load file or assembly 'FFImageLoading.Transformations, Version=2.4.4.859, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Tizen : 5.0.0.14562
FFImageLoading : 2.4.4.859
Forms : 3.5.0.169047

**Comment by daniel-luberda** [comment]
It should work, are you sure your referenced all necessary packages in all projects? Eg. if you referenced `Transformations` in shared project, you should also do the same in a Tizen's platform specific project.
