### ISSUE TITLE
Gif not working if view size is not set

### ISSUE THREAD

**Issue by PierreLucB** [luberda-molinet/FFImageLoading#1247]
### Description
The CachedImageControl doesn't display gif but png and jpeg works well.

Also, I have weird behaviors in general with GIF with FFImageLoading. Some cases works well in UWP and Android, some cases works only in UWP, sometimes I have to set the width and height of the image to have Android working well with the Gif but no needs in UWP.

But the following case never display the Gif :

### Steps to Reproduce
There is the code : 
<code>
            string base64Image = "image gif as base64";

            View imageControl = new CachedImage
            {
                Aspect = Aspect.AspectFit,
                Source = ImageSource.FromStream(() => new MemoryStream(Convert.FromBase64String(base64Image)))
            };

            this.Content = new ContentView
            {
                Content = imageControl,
                HorizontalOptions = LayoutOptions.Fill,
                VerticalOptions = LayoutOptions.Fill
            };
</code>

The parent call my view like this inside a Grid : 

    <Grid>
            <controls:BackgroundImage Base64Image="{Binding Base64Image}"></controls:BackgroundImage>
</Grid>

If I set a base64 png image it works, but gif doesn't appear.

It's not working on UWP, neither Android.

There are the packages used : 
  Xamarin.FFImageLoading.Forms  Version="2.4.4.859" 
  Xamarin.FFImageLoading.Svg.Forms Version="2.4.4.859"
  Xamarin.FFImageLoading.Transformations Version="2.4.4.859"
 Xamarin.Forms Version="3.4.0.1008975"

Do you encounter the trouble ? What can I do to help you reproduce ?

**Comment by daniel-luberda** [comment]
Hi @PierreLucB,

- On Windows GIF support is not yet implemented
- Loading GIFs as base64 strings is a bad idea, gifs file are huge, you're probably hitting platform memory size limits (`OOM exceptions or so`) when multiple images are used
- also when you use `StreamImageSource` without setting custom cache key, you're not using memory cache at all which could be bad for your app performance / memory issues

**Comment by daniel-luberda** [comment]
I just noticed that you didn't mention `animated` anywhere. It it the case that you use static gifs only?

**Comment by PierreLucB** [comment]
I'm using the component to set a Background Gif animation, which is dynamic, the user upload his image as gif, png, jpeg.. and I set it in Background.

The problem I encounter is I have no exceptions from the component, and in certains cases I have to specify height and width (only for gif) whereas there is not the problem with png/jpeg files.

**Comment by PierreLucB** [comment]
I did not look at the code, but I was believing that the CachedImage was managing his own cache..

**Comment by daniel-luberda** [comment]
> I did not look at the code, but I was believing that the CachedImage was managing his own cache..

It's described on WIKI: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#using-imagesourcefromstream-streamimagesource

Not having any error logs is really strange. Could you attach a repo?

**Comment by PierreLucB** [comment]
yes I can attach a repo !!
Thank you for asking. I will come back when it's done. I hope today.

**Comment by PierreLucB** [comment]
I reproduce the bug in the following repo : https://github.com/PierreLucB/FFImageLoadingGifBugRepro

**Comment by PierreLucB** [comment]
So do you reproduce too ?

**Comment by daniel-luberda** [comment]
@PierreLucB 

You referenced only `Xamarin.FFImageLoading.Svg.Forms` package in your projects. You should reference all necessary packages like: `Xamarin.FFImageLoading`, `Xamarin.FFImageLoading.Forms`, etc in ALL your projects. 

Other than that - your example worked just fine for me.

**Comment by PierreLucB** [comment]
The example is with a png image...
You just had to comment the CachedImage with the png file and uncomment the cachedimage with the gif file in order to reproduce.

Anyway, I did the comment/uncomment for you, and updated the android csproj who was missing references, I thought my Visual Studio had done this when I installed all the packages.

Please let me inform.

**Comment by daniel-luberda** [comment]
@PierreLucB  As you see on the screenshot I took SVG and tested it on FFIL repo sample to be sure that SVG file is working with latest codebase. So SVG is working fine 100%

**Comment by daniel-luberda** [comment]
> I thought my Visual Studio had done this when I installed all the packages.

From my experience, it should, but there are a lot of cases when it just fails to do it

**Comment by PierreLucB** [comment]
What screen shot ? I clearly have the bug with only one very poor sample in the repo I pushed.

**Comment by PierreLucB** [comment]
Have you look at the code ?

**Comment by PierreLucB** [comment]
Well, I have found a better solution, Gifs works very well with SkiaSharp. There is no strange behavior at all, it's a canvas, you can manipulate everything.

**Comment by daniel-luberda** [comment]
- Your example worked just fine, just please make sure you have all necessary packages installed in all projects, as described here: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#step-1
- I also took `tenor.gif` and included it in a FFImageLoading sample app, it also worked fine.

**Comment by PierreLucB** [comment]
You have close the bug you don't wanna accept. There are a lots with gifs.

It's a pity for you.

Good luck with your component.

**Comment by PierreLucB** [comment]
All packages are installed in every projects, please read me

**Comment by daniel-luberda** [comment]
Please note I'm not a paid support, the library is open for everyone, MIT licensed, everyone can debug it and submit a PR. I had an info that you gif was not working correctly, I tested it (the file) on a FFImageLoading's sample app and it worked fine, so I assumed it's working fine. It's really not easy to handle / test / debug such amount of issues here as a one person.

> All packages are installed in every projects, please read me

There are a lot of issues here which are just as plain as this: https://github.com/PierreLucB/FFImageLoadingGifBugRepro/commit/798760f862ea00d752db1a4fb5b76f22b251943a   
Please not that:
- Those packages weren't present in initial repo (added few days after)
- You reference SVG packages even if your repo is about GIF (some versions of Visual Studio don't install dependencies correctly and you must explicitly install all base packages)

I just assumed you were missing some packages. 

I tested it once again:

Doesn't work:
```XML
            <forms:CachedImage Aspect="AspectFill" BackgroundColor="Red"
                           Source="tenor.gif" HorizontalOptions="Center" VerticalOptions="Center"></forms:CachedImage>
```

Does work:

```XML
            <forms:CachedImage Aspect="AspectFill" BackgroundColor="Red"
                           Source="tenor.gif"></forms:CachedImage>
```

I'll need to investigate it when I'll have some time.

**Comment by daniel-luberda** [comment]
Fixed
