### ISSUE TITLE
Xamarin.Forms 3.6 (Android) - Linker issue in Release configuration: "Failed to resolve System.Void SkiaSharp.SKPath::AddRoundRect"

### ISSUE THREAD

**Issue by peter-raehse** [luberda-molinet/FFImageLoading#1249]
### Description

When trying to compile in VSTO Release configuration with activated linker I get this exception:

Mono.Linker.MarkException: Error processing method: 'SkiaSharp.SKPath FFImageLoading.Svg.Platform.SKSvg::ReadElement(System.Xml.Linq.XElement,System.Collections.Generic.Dictionary`2<System.String,System.String>)' in assembly: 'FFImageLoading.Svg.Platform.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void SkiaSharp.SKPath::AddRoundRect(SkiaSharp.SKRect,System.Single,System.Single,SkiaSharp.SKPathDirection)
   bei Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   bei Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   bei Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   bei Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Mono.Linker.Steps.MarkStep.ProcessQueue()
   bei Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   bei Mono.Linker.Steps.MarkStep.Process()
   bei MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   bei Mono.Linker.Pipeline.Process(LinkContext context)
   bei MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   bei Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   bei Xamarin.Android.Tasks.LinkAssemblies.Execute()
   bei Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   bei Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

### Steps to Reproduce
Add the NuGet packages Xamarin.FFImageLoading.Forms, Xamarin.FFImageLoading.Svg.Forms, Xamarin.FFImageLoading.Transformations to all projects of a Xamarin.Forms solution. Switch VSTO to Release configuration. Try to build the Android project.

### Expected Behavior

Should build in Release config with linker activated. (In Debug config everything works fine.)

### Actual Behavior

Shows exception during compile time.

### Basic Information

- Version with issue: FFImageLoading 2.4.5.909-pre with Xamarin.Forms 3.6.0.344457, Android Target: 9.0 Pie
- Last known good version: ???
- Platform: Xamarin.Forms, Xamarin.Android

Only with activated linker.

### Screenshots

n/a

### Reproduction Link / Code

n/a

**Comment by daniel-luberda** [comment]
- Do you have SkiaSharp package installed? Which version do you use?
- Are you sure you have the same FFIL packages version in all projects?

**Comment by peter-raehse** [comment]
No, I didn't install SkipSharp package. I followed this wiki: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API.

All packages had the same version 2.4.5.909-pre in all projects.

**Comment by daniel-luberda** [comment]
You must install `SkiaSharp`, it's a library dependency. It should be installed by Visual Studio automatically, but as you see sometimes there are problem with that.

**Comment by peter-raehse** [comment]
Simple as that :-) Thank you very much!
One last question: where is the place to post general questions about things I can't find an answer in the documentation?

**Comment by daniel-luberda** [comment]
I think asking as a separate issue should be fine. Also note, that our wiki is open for edits for everyone, feel free to update it if you think that information would be useful for anyone. Cheers.
