### ISSUE TITLE
Xamarin.Forms (Android) - System.TypeLoadException

### ISSUE THREAD

**Issue by HugoTruffe** [luberda-molinet/FFImageLoading#1252]
Hi peoples:

I am using the version 2.4.4.859 (Xamarin.FFImageLoading.Forms , Xamarin.FFImageLoading.Svg.Forms and Xamarin.FFImageLoading.Transformation) with Xamarin.Forms 3.6.0.344457

I added in MainActivity

`FFImageLoading.Forms.Platform.CachedImageRenderer.Init(true);`

but the app Jump the next problem (only Android)

**Could not load list of method overrides due to Method not found: void Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)**

So, I changed the version to **2.4.5.909-pre**. Now the problem is resolved but all images are not visible (iOS and Android, all images are not show).

Are there with the same problem?

**Comment by diriarte2111** [comment]
Same exception in Android "Could not load list of method overrides due to Method not found: void Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)", I have the respective line in MainActivity, why is this happening? (iOS is working fine).

**Comment by daniel-luberda** [comment]
- Please use latest prerelease nuget package
- Please make sure you have the same package versions in all projects
- delete `bin`/`obj` folders and rebuild

**Comment by daniel-luberda** [comment]
Any news?

**Comment by HugoTruffe** [comment]
Hi Daniel:

The problem is resolved.

I read the new steps [https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API ] and Problem Resolved

Thx!
