### ISSUE TITLE
FromResource with ReplaceStringMap no longer working

### ISSUE THREAD

**Issue by abailie** [luberda-molinet/FFImageLoading#1254]
### Description

I created a simple image button around SvgCachedImage version 2.4.5.900-pre that allowed for color change through the ReplaceStringMap. On updating to 2.4.5.909 that code no longer works. 

My button has a bindable Image property, and a bindable ForeColor property, when either of those changed, the Source of the image (SvgCachedImage) war recreated using the SvgImageSource.FromResource(). In version 2.4.5.900 this always showed the SVG image in the ForeColor, in version 2.4.5.900 the image appears in its original color
### Steps to Reproduce

in xaml
```
                <ffimageloadingsvg:SvgCachedImage x:Name="image"
                                                    Aspect="AspectFit"
                                                    VerticalOptions="Fill"
                                                    HorizontalOptions="Fill"
                                                    BackgroundColor="Transparent"/>
```

in code behind

```
image.Source =
                    SvgImageSource.FromResource(resource: Image.Substring(11));
                    replaceStringMap: _replacementStringMap);
```

I worked around this by changing the code to 

```
image.Source =
                    SvgImageSource.FromResource(resource: Image.Substring(11));

                image.ReplaceStringMap = _replacementStringMap;
```

### Expected Behavior

the replacement string should act on the SVG file to replace the Fill color.

### Actual Behavior

no replacement took place.

### Basic Information

- Version with issue: 2.4.5.909
- Last known good version: 2.4.5.900
- Platform: iOS simulator only tested

### Screenshots

This close-up image shows how the button appears black, using version 2.4.5.9009
<img width="77" alt="Screenshot 2019-04-26 at 13 09 42" src="https://user-images.githubusercontent.com/6578425/56806698-9934da80-6824-11e9-9d27-e847372fd7fd.png">

This is how the image appears with version 2.4.5.900, and with the code modified to set the replacement string map after initialisation.
<img width="100" alt="Screenshot 2019-04-26 at 13 08 32" src="https://user-images.githubusercontent.com/6578425/56806695-96d28080-6824-11e9-8057-80c63c3f8262.png">

Just to clarify, the button image should be white

**Comment by daniel-luberda** [comment]
Thanks for detailed description. Fixed :)

**Comment by abailie** [comment]
Thanks :)
