### ISSUE TITLE
Fuzzy borders on SVG render

### ISSUE THREAD

**Issue by mateuswolkmer** [luberda-molinet/FFImageLoading#1256]
### Description
I'm opening a new issue because other issues related to fuzzy SVG are closed.
So, what I've notices is that all my SVGs seem to have a low resolution render when no `HeightRequest` and `WidthRequest` is explicitly informed.

My problem is I'm using a AbsoluteLayout with proportional size on the `SvgCachedImage`, and setting a fixed size would not work when working with devices of multiple sizes. I was using another method to render before and had to stop using because it didn't render rounded borders correctly, so I've started using FFImageLoading since then.

My main issue is if it is possible or not to display a `SvgCachedImage` without setting a fixed size. I've tried using a frame around it `VerticalOptions` and `HorizontalOptions` set to `Fill` and `FillAndExpand` but the result was the same.

### Basic Information

- Version with issue: 2.4.5.929 (it seems that it got worse since updated from 2.4.5.922)
- Platform: Xamarin.Forms (rendered on Android)

### Comparison of sharp custom render (left) and fuzzy SvgCachedImage render (right)
![image](https://user-images.githubusercontent.com/20559356/56989342-9873af80-6b68-11e9-8156-83ea3db46e14.png)

### XAML code of both implementations

```
<components:SvgIconView
	AbsoluteLayout.LayoutFlags="All"
	AbsoluteLayout.LayoutBounds="0.2, 0.5, 0.4, 0.4"
        ResourceName="logo.svg"/>

<ffimageloadingsvg:SvgCachedImage 
	AbsoluteLayout.LayoutFlags="All"
	AbsoluteLayout.LayoutBounds="0.9, 0.5, 0.4, 0.4"
        Source="resource://Vectors.logo.svg"/>
```

### Custom render code (using SKCanvas)

```
using System;
using System.IO;
using System.Reflection;
using SkiaSharp;
using SkiaSharp.Views.Forms;
using Xamarin.Forms;
using SKSvg = SkiaSharp.Extended.Svg.SKSvg;

namespace EcoMind.Custom
{
    /** Source: https://www.pshul.com/2018/01/25/xamarin-forms-using-svg-images-with-skiasharp/ */
    class SvgIconView : Frame
    {
        private readonly SKCanvasView _canvasView = new SKCanvasView();

        public static readonly BindableProperty ResourceNameProperty = BindableProperty.Create(
            nameof(ResourceName), typeof(string), typeof(SvgIconView), default(string), propertyChanged: RedrawCanvas);

        public string ResourceName
        {
            get => (string)GetValue(ResourceNameProperty);
            set => SetValue(ResourceNameProperty, value);
        }

        public SvgIconView()
        {
            Padding = new Thickness(0);

            HasShadow = false;
            BackgroundColor = Color.Transparent;

            Content = _canvasView;
            _canvasView.PaintSurface += CanvasViewOnPaintSurface;
        }

        private static void RedrawCanvas(BindableObject bindable, object oldvalue, object newvalue)
        {
            SvgIconView svgIcon = bindable as SvgIconView;
            svgIcon?._canvasView.InvalidateSurface();
        }

        private void CanvasViewOnPaintSurface(object sender, SKPaintSurfaceEventArgs args)
        {
            SKCanvas canvas = args.Surface.Canvas;
            canvas.Clear();

            if (string.IsNullOrEmpty(ResourceName))
                return;

            using (Stream stream = GetType().Assembly.GetManifestResourceStream("Vectors." + ResourceName))
            {
                SKSvg svg = new SKSvg();
                svg.Load(stream);

                SKImageInfo info = args.Info;
                canvas.Translate(info.Width / 2f, info.Height / 2f);

                SKRect bounds = svg.ViewBox;
                float xRatio = info.Width / bounds.Width;
                float yRatio = info.Height / bounds.Height;

                float ratio = Math.Min(xRatio, yRatio);

                canvas.Scale(ratio);
                canvas.Translate(-bounds.MidX, -bounds.MidY);

                canvas.DrawPicture(svg.Picture);
            }
        }
    }
}
```

**Comment by daniel-luberda** [comment]
Hi @mateuswolkmer 

You need to specify at least one fixed size `WidthRequest` or `HeightRequest` for now. I'll need to find solution how to get view expanded dimension in XF before image loading. `CachedImage`/`SvgCachedImage`, uses same code for measuring view's dimension from `Image`, see this: https://github.com/luberda-molinet/FFImageLoading/blob/519060dfa9befad753278f197555b6756db5808b/source/FFImageLoading.Forms/CachedImage.cs#L470-L527

**Comment by mateuswolkmer** [comment]
I see @daniel-luberda, not an easy task, I supose. The implementation I'm using (the custom render using SKCanvas) extends `Xamarin.Forms.Frame`, maybe it does something different from `Image` while calculating the width and height? That's the code in which it is calculated:
```
SKImageInfo info = args.Info;
canvas.Translate(info.Width / 2f, info.Height / 2f);

SKRect bounds = svg.ViewBox;
float xRatio = info.Width / bounds.Width;
float yRatio = info.Height / bounds.Height;

float ratio = Math.Min(xRatio, yRatio);

canvas.Scale(ratio);
canvas.Translate(-bounds.MidX, -bounds.MidY);
```
It's something to investigate, would contribute if I had more time.

**Comment by daniel-luberda** [comment]
@mateuswolkmer It turned out to be simpler than I thought. Implemented. 🎆

**Comment by mateuswolkmer** [comment]
Confirmed that it now renders perfectly, thank you @daniel-luberda!
