### ISSUE TITLE
Some gifs showing solid color areas and animating too quickly in Android

### ISSUE THREAD

**Issue by natevarghese** [luberda-molinet/FFImageLoading#1257]
### Description

Some gifs show solid color bars over the gifs in android. They are always at the bottom of the image. Additionally, gifs sometimes animate too fast. 

You can open the links below directly in your browser to confirm those solid color bars should not exist. They do not show in iOS.

I did not test outside iOS and Android.

### Steps to Reproduce

Edit the SimpleGifPageModel class setting the ImageUrl variable in the Reload function as follows;

ImageUrl = "https://media.giphy.com/media/f7YngNsFRFXSVME6ze/giphy.gif";
(Solid colored areas)

OR

ImageUrl = "https://media.giphy.com/media/fQAbert673DmY6mrq7/giphy.gif";
(Too fast and solid color area on bottom)

Run the FFImageLoading.Forms.Sample.Droid sample code and navigate to Simple Gif Example (at the bottom of the list) 

Notice behavior

### Expected Behavior

Render the gif correctly so it appears as it does in a browser or iOS.

### Actual Behavior

Some gifs show solid color bars over the gifs in android. They are always at the bottom of the image. Additionally, gifs sometimes animate too fast. 

### Basic Information

- Version with issue: 2.4.6.929
- Last known good version: Unknown 
- Platform: Android

### Screenshots

![Screen Shot 2019-05-01 at 12 36 09 PM](https://user-images.githubusercontent.com/4398571/57038030-b8a97a00-6c0d-11e9-8851-4bf1523ddbce.png)

### Reproduction Link / Code

N/A

**Comment by daniel-luberda** [comment]
# First issue

- It may be related to transparency. Code is here: https://github.com/luberda-molinet/FFImageLoading/blob/87c69858b4546d8734968ae40fac4e616d256514/source/FFImageLoading.Common/Helpers/GifHelperBase.cs#L604-L608
- Similar issues in Glide:  https://github.com/bumptech/glide/issues/1068

Any ideas?

# Second issue

Fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/01d30bdccd5148772076619c22bedc1c0c412bfe

**Comment by natevarghese** [comment]
This commit looks right 
https://github.com/bumptech/glide/pull/1090/commits/dbb7be3b1af133bc8ad401ba825a91f0b7648677

but i'm having a tough time translating it into GifHelperBase.CS

**Comment by natevarghese** [comment]
I found this package that looks like it is the decoder that Glide uses. 

https://www.nuget.org/packages/Karamunting.Android.BumpTech.GlideGifDecoder/

Maybe we can use this somehow? It's called StandardGifDecoder. 
https://github.com/bumptech/glide/blob/master/third_party/gif_decoder/src/main/java/com/bumptech/glide/gifdecoder/StandardGifDecoder.java

I tried for some time to take the code in StandardGifDecoder.java and translate it to our GifHelperBase.cs but it didn't work out.  

It's important to know that that Nuget only installs on android so you will have to bait and switch probably. I think it's already being done in iOS that way.

**Comment by natevarghese** [comment]
Created pull request #1261

**Comment by daniel-luberda** [comment]
Merged and fixed :) Thanks @natevarghese 
BTW: I rewrote gif decoder to pure c# :)

**Comment by natevarghese** [comment]
Can we update the NuGet sometime soon?

Also thank you very much. I'm a big fan of your work and this library.

**Comment by daniel-luberda** [comment]
Thanks. New nuget today :) Cheers.
