### ISSUE TITLE
Can not load Image from local in iOS

### ISSUE THREAD

**Issue by albilaga** [luberda-molinet/FFImageLoading#1265]
### Description

When using `FFImageLoading.Forms.Platform.CachedImageRenderer.InitImageSourceHandler();` in iOS and then using Image Souce from local resource it will not show anything. In Android it works fine. If I remove that line, it also works fine. 

### Steps to Reproduce

1. In AppDelegate set
```
 FFImageLoading.Forms.Platform.CachedImageRenderer.Init();
            FFImageLoading.Forms.Platform.CachedImageRenderer.InitImageSourceHandler();
```
2. Call Image from local using `<Image Source="placeholder/>`

### Expected Behavior

Image should be displaying

### Actual Behavior

Image not displaying

### Basic Information

- Version with issue:2.4.9.961
- Last known good version: -
- Platform: iOS

**Comment by daniel-luberda** [comment]
Could you attach a sample project with your issue?

**Comment by albilaga** [comment]
Well this is weird. In my project that is definitely happen but when try recreating new project and mock that it works fine. Will try again later

**Comment by daniel-luberda** [comment]
I'll close this then. Cheers :)

**Comment by gastonBoulanger** [comment]
@albilaga I have this same problem. How did you solve this?

**Comment by albilaga** [comment]
Nope. I am not solve this @gastonBoulanger 
I still have this issue in my project but can't replicate it in another project. For now I am not setting `InitImageSourceHandler()`
