### ISSUE TITLE
SVG not showing on Xamarin Forms 3.6.x [Android]

### ISSUE THREAD

**Issue by ricardoaijon** [luberda-molinet/FFImageLoading#1268]
### Description

[TheLittleThingsPlayground-master.zip](https://github.com/luberda-molinet/FFImageLoading/files/3161840/TheLittleThingsPlayground-master.zip)
SVG images are not shown.

### Steps to Reproduce

Create a Xamarin Forms 3.6.x project with FFImageLoading + FFImageLoading.Svg

### Expected Behavior
All the svg images are displayed
### Actual Behavior

No one image is rendered , only blank or background color of the image are displayed.

### Basic Information

- Version with issue:  2.4.9.x
- Last known good version: 2.4.4.859 with issues on Xamarin 3.4.0 and Android 9.0
- Platform: Xamarin Forms Android 9.0 + PCL .Net Standard 2.0

### Screenshots
![configproject](https://user-images.githubusercontent.com/14821720/57449555-8676c880-725c-11e9-9165-0c1c04936395.png)

![Screenshot_20190509-131950](https://user-images.githubusercontent.com/14821720/57450161-10736100-725e-11e9-9d09-fd6b5de22f12.png)

### Reproduction Link / Code
In the example project go to "Card" section .

**Comment by daniel-luberda** [comment]
Works fine for me.

Please make sure you:

- removed all `bin`/`obj` folders from your projects
- have the same packages version in all projects

**Comment by daniel-luberda** [comment]
Forgot about one thing:

You should use `SvgCachedImage` instead `CachedImage`
