### ISSUE TITLE
Android GIFs very laggy when in collection. Might be memory leak

### ISSUE THREAD

**Issue by natevarghese** [luberda-molinet/FFImageLoading#1270]
### Description

Loading a ListView of gifs shows a very obvious performance hit in Android even with the FastCellRenderer. Performance hit seems to persist after leaving the page with the ListView. iOS is beautiful. 

### Steps to Reproduce

Edit the ListHeavePageViewModel to always point to a random gif url. I will post a bunch at the end of this post. 

### Expected Behavior

Behave like iOS. 

### Actual Behavior

Slow and laggy. Possibly a memory leak.

### Basic Information

- Version with issue: 2.4.9.961
- Last known good version: Unknown
- Platform: Android 

### Reproduction Link / Code

// replacement ListHeavePageModel Reload Function:
public void Reload()
		{
			var list = new List<ListHeavyItem>();

			string[] images = new string[50];

			for (int i = 0; i < images.Length; i++)
			{
				images[i] = Helpers.GetUrlFromList(i);
			}

			var howMuch = images.Length;
			var howManyTimes = 10;

			for (int j = 0; j < howManyTimes; j++)
			{
				for (int i = 0; i < howMuch; i++)
				{
					var item = new ListHeavyItem()
					{
						Image1Url = Helpers.GetUrlFromList(i),
						Image2Url = Helpers.GetUrlFromList(i),
						Image3Url = Helpers.GetUrlFromList(i),
						Image4Url = Helpers.GetUrlFromList(i)
					};

					list.Add(item);
				}
			}

			Items = new ObservableCollection<ListHeavyItem>(list);
		}

-------------------------------------------------------------------------------------------

//static helper to get a random gif url. inside Helpers.cs
static Random r = new Random();
		public static string GetUrlFromList(int i)
		{
			var choices = new List<string>()
			{
				"https://media2.giphy.com/media/AFrQe3lRh85RC/200.gif",
				"https://media3.giphy.com/media/YP1Y7kqNhMgLzvP5yq/200.gif",
				"https://media2.giphy.com/media/l378nXMQQwDZT51iU/200.gif",
				"https://media2.giphy.com/media/8Am4Njdu7imzLbnIhc/200.gif",
				"https://media1.giphy.com/media/Yq20ilY5ZhgvYghu9q/200.gif",
				"https://media2.giphy.com/media/eusQH73gAwPCmt7Ash/200.gif",
				"https://media1.giphy.com/media/3o7aD1ssITY8YCtiUM/200.gif",
				"https://media3.giphy.com/media/5QTLUeoefMiTpl8h8V/200.gif",
				"https://media0.giphy.com/media/MCp8gOuteryTTOKDRL/200.gif",
				"https://media2.giphy.com/media/fo2dhRTmaULbStoFkX/200.gif",
				"https://media2.giphy.com/media/xT8qB7u5XikjS4OGzK/200.gif",
				"https://media3.giphy.com/media/kFNX3cf9nUPRK5kICe/200.gif",
				"https://media0.giphy.com/media/uVsU9lfPSWPBV8yhzi/200.gif",
				"https://media2.giphy.com/media/l1J9C7tZSbwmuuN6o/200.gif",
				"https://media1.giphy.com/media/toqGVvQvutnJEDuCDq/200.gif",
				"https://media1.giphy.com/media/1isby8fcCFc4zC21Bj/200.gif",
				"https://media3.giphy.com/media/VdoHzRzT666PNouvYe/200.gif",
				"https://media3.giphy.com/media/fw2OFjoqtNv5G5Vw8O/200.gif",
				"https://media0.giphy.com/media/LQtj7adprclbp06w8f/200.gif",
				"https://media2.giphy.com/media/8Ac77elQ1a0De/200.gif",
				"https://media0.giphy.com/media/UX4YAJb3lEG8lZ9gQw/200.gif",
				"https://media0.giphy.com/media/hWptJSPlhOSzLhC4Ky/200.gif",
				"https://media3.giphy.com/media/1oITHzUzap4tQw2XL5/200.gif",
				"https://media3.giphy.com/media/Ky4SbUDqKhZWZGvlUz/200.gif",
				"https://media0.giphy.com/media/fs3Bg5BUAXLmVpvFh7/200.gif",
				"https://media2.giphy.com/media/37R9DQmQZHckhydtl0/200.gif",
				"https://media3.giphy.com/media/PR7zNUghf2Ku3Nbta5/200.gif",
				"https://media0.giphy.com/media/fHrMxfxpWaElLvH6ek/200.gif",
				"https://media0.giphy.com/media/1zlUgRXapM2YUYEfPi/200.gif",
				"https://media1.giphy.com/media/LRr6yL5taOzovnKLm8/200.gif",
				"https://media3.giphy.com/media/1qWlkOaMFHQGOfKQVn/200.gif",
				"https://media0.giphy.com/media/HH2bb3Pjq5IB2/200.gif",
				"https://media3.giphy.com/media/fYkYhw2ANU1I4/200.gif",
				"https://media1.giphy.com/media/emwNa7im5sht6/200.gif",
				"https://media1.giphy.com/media/t6Kf2qs5fgWiAlOig5/200.gif",
				"https://media0.giphy.com/media/40a8jFMt0sc73UtpaH/200.gif",
				"https://media1.giphy.com/media/zaiY6UOCHP8NG/200.gif",
				"https://media2.giphy.com/media/cdZAGXI45pQ6Q/200.gif",
				"https://media2.giphy.com/media/95PromoujUIuj3ROiP/200.gif",
				"https://media0.giphy.com/media/82LGQT2QKKMPBbkEkg/200.gif",
				"https://media2.giphy.com/media/EJOdcxm52IWNq/200.gif",
				"https://media1.giphy.com/media/Eqc7RhbdSEqYut8vDc/200.gif",
				"https://media1.giphy.com/media/kwHJyJkrAoAIE/200.gif",
				"https://media3.giphy.com/media/cOR2fPCZgErzi6COcG/200.gif",
				"https://media1.giphy.com/media/IQebREsGFRXmo/200.gif",
				"https://media2.giphy.com/media/55DUoWF4HeKhG/200.gif",
				"https://media1.giphy.com/media/31vamYdZV5ISQ/200.gif",
				"https://media1.giphy.com/media/kuWN0iF9BLQKk/200.gif",
				"https://media2.giphy.com/media/2y0bDtmlrJtg4/200.gif",
				"https://media2.giphy.com/media/z8OcWLLk4SrpS/200.gif",
				"https://media1.giphy.com/media/27wc7vMWPvvJC/200.gif",
				"https://media2.giphy.com/media/jM4bWFBKpSFeo/200.gif",
				"https://media3.giphy.com/media/Myp2C0iWDMh2g/200.gif",
				"https://media2.giphy.com/media/3CWaVWrNJv27P4sPHR/200.gif",
				"https://media0.giphy.com/media/SGGHAPCjED1OcW6ixv/200.gif",
				"https://media3.giphy.com/media/FcGKYdJSGDykU/200.gif",
				"https://media3.giphy.com/media/e7Pkc6DwN6IWHvvizL/200.gif",
				"https://media3.giphy.com/media/w6YCfXHS6QZjeHlVpI/200.gif",
				"https://media2.giphy.com/media/yQzS5KXVcDomA/200.gif",
				"https://media2.giphy.com/media/n31H48lHjiTUk/200.gif",
				"https://media0.giphy.com/media/1wpxG15ZRRwUo94ytP/200.gif",
				"https://media0.giphy.com/media/l1fzJpEQHwXwjLcjJw/200.gif",
				"https://media2.giphy.com/media/87aLO68Fi4nX4llnnQ/200.gif",
				"https://media0.giphy.com/media/DJM88aCmEeaNG/200.gif",
				"https://media1.giphy.com/media/1hCn9kUdtA65wDSvXI/200.gif",
				"https://media2.giphy.com/media/dZCpA5HM1Dv6yTDsvR/200.gif",
				"https://media2.giphy.com/media/GltC4HZLjJLvq/200.gif",
				"https://media1.giphy.com/media/2hjLGgaDSxbws/200.gif",
				"https://media0.giphy.com/media/11LkxpJX5Eex7q/200.gif",
				"https://media3.giphy.com/media/2w4M7YOoLyLmbiRPPg/200.gif",
				"https://media1.giphy.com/media/2sjwBnNlY4CPyr8goo/200.gif",
				"https://media1.giphy.com/media/3dbEAOOmPXnTpMqgF5/200.gif",
				"https://media2.giphy.com/media/uYPf4VZYUlMOc/200.gif",
				"https://media1.giphy.com/media/ZtQZXCXd3ICLm/200.gif",
				"https://media2.giphy.com/media/wIkGlPFEjzy8qykkUJ/200.gif",
				"https://media0.giphy.com/media/oV1KNfhBbogI8/200.gif",
				"https://media2.giphy.com/media/fns1AVKMOc20U/200.gif",
				"https://media1.giphy.com/media/v3kINmQVvPH4A/200.gif",
				"https://media0.giphy.com/media/55jOowTAknOXC/200.gif",
				"https://media0.giphy.com/media/hN729Fld8nhwk/200.gif",
				"https://media1.giphy.com/media/OjraDCulT8NSP56tcI/200.gif",
				"https://media0.giphy.com/media/AmHM5RAg1VmbS/200.gif",
				"https://media3.giphy.com/media/g209OEWtBA8wg/200.gif",
				"https://media3.giphy.com/media/hnKfJWq5wFHbi/200.gif",
				"https://media0.giphy.com/media/35LH6GkOzEXuw/200.gif",
				"https://media1.giphy.com/media/lBscWj24YJqw/200.gif",
				"https://media0.giphy.com/media/KDCeTkQql6ifS/200.gif",
				"https://media2.giphy.com/media/RLS73NJaJdDqM/200.gif",
				"https://media2.giphy.com/media/l1BgSbJuPVcLJClmo/200.gif",
				"https://media1.giphy.com/media/12O97LMADeWCKk/200.gif",
				"https://media2.giphy.com/media/OAyJnE9DCIfuw/200.gif",
				"https://media0.giphy.com/media/iMbLVrwJER7d6/200.gif",
				"https://media3.giphy.com/media/InbbEb9hEnRQI/200.gif",
				"https://media1.giphy.com/media/ndV2Xk35V7bCE/200.gif",
				"https://media2.giphy.com/media/RLflocYLauiJ2/200.gif",
				"https://media3.giphy.com/media/6CQciStBBmfTO/200.gif",
				"https://media1.giphy.com/media/Ka1AUlHhI3z2M/200.gif",
				"https://media0.giphy.com/media/hYc3cpeOtPLX2/200.gif",
				"https://media2.giphy.com/media/I9d6FIxIygs0M/200.gif",
				"https://media0.giphy.com/media/s79yB2EkYahfG/200.gif",
				"https://media2.giphy.com/media/EUcKlaja5qQWA/200.gif",
				"https://media2.giphy.com/media/xiQBcVTYJLP0s/200.gif",
				"https://media3.giphy.com/media/xuvECl1pwniZa/200.gif",
				"https://media3.giphy.com/media/q4RahsFvkpVKw/200.gif",
				"https://media0.giphy.com/media/BU95dRJJQ6BC8/200.gif",
				"https://media3.giphy.com/media/l49JZ1oF2qHawdmzm/200.gif",
				"https://media2.giphy.com/media/3oFzmbZh2IX2XFk3Ti/200.gif",
				"https://media2.giphy.com/media/lWROhHdtfpoCA/200.gif",
				"https://media0.giphy.com/media/7eR9XFuWVbBLi/200.gif",
				"https://media1.giphy.com/media/qH3BFJya6c5So/200.gif",
				"https://media1.giphy.com/media/xT0xezFBXCEjE7JzzO/200.gif",
				"https://media0.giphy.com/media/3eUQXPop5VjgYv3r0s/200.gif",
				"https://media1.giphy.com/media/3oFzmsANNWiz1ENuVy/200.gif",
				"https://media2.giphy.com/media/92MpFQ5Yq9tD2/200.gif",
				"https://media0.giphy.com/media/CFsVo5sSlpcPK/200.gif",
				"https://media2.giphy.com/media/IE7mmA2PAZGww/200.gif",
				"https://media1.giphy.com/media/ssm0SSwVbICGc/200.gif",
				"https://media3.giphy.com/media/l1KdaRPTyb9sKnUbe/200.gif",
				"https://media2.giphy.com/media/FFcTkM1aqFIJi/200.gif",
				"https://media1.giphy.com/media/2Zm5Gd6aCOTU4/200.gif",
				"https://media1.giphy.com/media/l49JRUtu1LUWugpJm/200.gif",
				"https://media2.giphy.com/media/7UCHnR2kB1rAk/200.gif",
				"https://media0.giphy.com/media/3oFzlYuazAesniYNVe/200.gif",
				"https://media3.giphy.com/media/uJrdgHANd85RC/200.gif",
				"https://media0.giphy.com/media/tz8RyTZ9GszW8/200.gif",
				"https://media1.giphy.com/media/MD9BDk7SkOO6k/200.gif",
				"https://media1.giphy.com/media/h9RbPUfANqUYo/200.gif",
				"https://media1.giphy.com/media/OU7oFgKhXPihy/200.gif",
				"https://media0.giphy.com/media/k0fRyoEmcNTzO/200.gif",
				"https://media1.giphy.com/media/128cFIx0vlouKQ/200.gif",
				"https://media2.giphy.com/media/Vp7Q2mGvcOsA8/200.gif",
				"https://media3.giphy.com/media/eEbiAqk9YUT5e/200.gif",
				"https://media0.giphy.com/media/hqlNCTsbBw7orH6MSq/200.gif",
				"https://media1.giphy.com/media/dxh66L8gjiqPOh869O/200.gif",
				"https://media1.giphy.com/media/jL7cmBKJqnyG4/200.gif",
				"https://media2.giphy.com/media/e7QNtU35A497EPrtKZ/200.gif",
				"https://media0.giphy.com/media/35xM6Pg1UTxSTS3nuY/200.gif",
				"https://media3.giphy.com/media/NPqQwwGJIxNEtEiNLZ/200.gif",
				"https://media3.giphy.com/media/MSSGmXf8blqZGSbg0q/200.gif",
				"https://media1.giphy.com/media/ja0UTQ5GKw1ZIJkH4u/200.gif",
				"https://media1.giphy.com/media/JrklbzC1C4X4rSgFzF/200.gif",
				"https://media2.giphy.com/media/US1xW1DOrKJfgLa0xA/200.gif",
				"https://media1.giphy.com/media/LS3xwMKIMUHNocYoM4/200.gif",
				"https://media2.giphy.com/media/Vh2tJzl93GKj7wxirb/200.gif",
				"https://media3.giphy.com/media/Vi0JqPEyxztPoicIup/200.gif",
				"https://media2.giphy.com/media/JrMyqcNznjfx8g5sr2/200.gif",
				"https://media2.giphy.com/media/dWlLf9EAC8u5Nd0ku4/200.gif",
				"https://media3.giphy.com/media/iJK5YBzQRSNjRMqQXb/200.gif",
				"https://media0.giphy.com/media/JNP5ki0CAETgotei8h/200.gif",
				"https://media1.giphy.com/media/dwM5YAv9nZ48mDJaPl/200.gif",
				"https://media1.giphy.com/media/XptnA9cgVoRvTLtDwY/200.gif",
				"https://media1.giphy.com/media/3ohhwApnoNfHaWb2b6/200.gif",
				"https://media2.giphy.com/media/3o7aD6sVgUureq74v6/200.gif",
				"https://media0.giphy.com/media/1JhqiWq25DGPInlxxA/200.gif",
				"https://media3.giphy.com/media/l378w2NKt3URm6w5W/200.gif",
				"https://media1.giphy.com/media/psmJf376CrS92Dy5wf/200.gif",
				"https://media3.giphy.com/media/i2tLw5ZyikSFdkeGHT/200.gif",
				"https://media0.giphy.com/media/9D1iQsxllOXcnIXp6X/200.gif",
				"https://media2.giphy.com/media/pqtDYNh7kG1zP54LDM/200.gif",
				"https://media1.giphy.com/media/GFuPjQFrGgiE8/200.gif",
				"https://media1.giphy.com/media/3o7aD2d7hy9ktXNDP2/200.gif",
				"https://media2.giphy.com/media/4EF5FG8ZRK0hctDPse/200.gif",
				"https://media0.giphy.com/media/WysKxC4FjN51mAYolG/200.gif",
				"https://media1.giphy.com/media/l4pTdGsfEtSSwE9oc/200.gif",
				"https://media1.giphy.com/media/pNTwWXmIcZzrgVEXp2/200.gif",
				"https://media0.giphy.com/media/3o7aDbtL8gZk9xW5lS/200.gif",
				"https://media1.giphy.com/media/wI8slaPx5Ry6AxFmHR/200.gif",
				"https://media3.giphy.com/media/l0IsH4gOXAV0CvuN2/200.gif",
				"https://media0.giphy.com/media/3ov9k1ZNTELhynEI2A/200.gif",
				"https://media2.giphy.com/media/35nU79vBbeOm4/200.gif",
				"https://media1.giphy.com/media/3ohhwiY7Wke9briEqk/200.gif",
				"https://media0.giphy.com/media/3o7aCQNE8LAwzhucRW/200.gif",
				"https://media2.giphy.com/media/pVVKJJuEQre3219fLh/200.gif",
				"https://media0.giphy.com/media/kWMu5NER8omrXjKpVB/200.gif",
				"https://media2.giphy.com/media/f9R7zLHJQkhNcUzuFU/200.gif",
				"https://media3.giphy.com/media/105fcjJ9jm4XPq/200.gif",
				"https://media1.giphy.com/media/d3aCHTQOTZ3kQyPu/200.gif",
				"https://media3.giphy.com/media/l1J9HYRd5q9ITYfqE/200.gif",
				"https://media0.giphy.com/media/3o7aDePqG9xQTC7Sus/200.gif",
				"https://media3.giphy.com/media/3bztvLmRibRUaaYNC3/200.gif",
				"https://media3.giphy.com/media/l4pTnRYy834h8b1Ha/200.gif",
				"https://media0.giphy.com/media/xThta0s4bWwX42oI6Y/200.gif",
				"https://media2.giphy.com/media/xUOwGoY1pVXYd2D7gY/200.gif",
				"https://media3.giphy.com/media/xUOwFXqk6NpqplqJos/200.gif",
				"https://media3.giphy.com/media/l1BgRjlqtdRPHIEjm/200.gif",
				"https://media1.giphy.com/media/3gWLLzrfCfGb6FB7Rh/200.gif",
				"https://media0.giphy.com/media/xUPGcfC1V8ntYvJsUU/200.gif",
				"https://media3.giphy.com/media/xThtahvhI95NfAwrio/200.gif",
				"https://media2.giphy.com/media/l0HlGeTBdTqMll15u/200.gif",
				"https://media3.giphy.com/media/8Ac77elQ1a0De/200.gif",
				"https://media1.giphy.com/media/KVFt9PYrE84Ruj0muv/200.gif",
				"https://media2.giphy.com/media/68O3K8YoyQRvG/200.gif",
				"https://media0.giphy.com/media/1ncSQT6Keb3t7QPhoa/200.gif",
				"https://media2.giphy.com/media/xThtajOZXWYceQdMpq/200.gif",
				"https://media0.giphy.com/media/l0IyfURyJDqZrXIFG/200.gif",
				"https://media2.giphy.com/media/3ohzdJK3bLXd7MpvLa/200.gif",
				"https://media1.giphy.com/media/24FIhU6feRweuAnN7O/200.gif",
				"https://media3.giphy.com/media/5fBH6zrcIiOs65zXCtG/200.gif",
				"https://media0.giphy.com/media/xUPGcfX9rag7PiNyuY/200.gif",
				"https://media1.giphy.com/media/2cehsMpM3VxjbBB0TG/200.gif",
				"https://media2.giphy.com/media/xUPGcheURV7DHb5rtC/200.gif",
				"https://media1.giphy.com/media/xUPGcu27jqnR0mFrUI/200.gif",
				"https://media2.giphy.com/media/7KF2emV47HfEY/200.gif",
				"https://media3.giphy.com/media/oMluJkUKzgD6/200.gif",
				"https://media2.giphy.com/media/xUPGczbQ2ayznWktry/200.gif",
				"https://media2.giphy.com/media/MUEqGQEVXbMnL2uiIr/200.gif",
				"https://media0.giphy.com/media/3ohzdW3JZ4FcvLepeo/200.gif",
				"https://media3.giphy.com/media/26DMTpbfiRAt0fg1q/200.gif",
				"https://media3.giphy.com/media/8L0Pb4b92CFOhougNu/200.gif",
				"https://media3.giphy.com/media/26DMUfIe2MyNEiCBy/200.gif"
			};
			var index = r.Next(choices.Count);
			return choices[index];
		}'

**Comment by daniel-luberda** [comment]
Should be fixed. See https://github.com/luberda-molinet/FFImageLoading/commit/aa5b58e8c7b350a5af7d5a1cc94d6a3f30361ba4

**Comment by natevarghese** [comment]
seems much better.

**Comment by natevarghese** [comment]
Can I have an updated Nuget please?

**Comment by natevarghese** [comment]
Friendly request reminder for a new nuget please

**Comment by daniel-luberda** [comment]
Released
