### ISSUE TITLE
Crop Transformation Demo

### ISSUE THREAD

**Issue by abrantie1z** [luberda-molinet/FFImageLoading#1284]
### Basic Information

- Version with issue: 
- Last known good version: 
- Platform:

**Comment by abrantie1z** [comment]
Kudus to you and your team for a great work done. But can u please point me out to a demo on the crop transformation ? i want to achieve what you have in your ReadMe file. Thanks

**Comment by daniel-luberda** [comment]
Sure: 

- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/Transformations/CropTransformationPage.xaml
- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/Transformations/CropTransformationPage.xaml.cs
- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/Transformations/CropTransformationPageModel.cs

Also this: https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/ImageCropView

**Comment by abrantie1z** [comment]
Hi, thanks for the quick reply, how do i achieve the image attached below? i tried the example in Transformation demo, but wasnt able to achieve this.
![ffimageloading_large](https://user-images.githubusercontent.com/19966094/58480170-47e07980-8149-11e9-8377-433c4cd3355a.png)

**Comment by daniel-luberda** [comment]
Those are literally screenshots from sample app, everything is here: https://github.com/luberda-molinet/FFImageLoading/tree/master/samples/ImageLoading.Forms.Sample/Shared/Pages

**Comment by abrantie1z** [comment]
<ffimageloading:CachedImage HorizontalOptions="Center" VerticalOptions="Center"
                    LoadingPlaceholder="loading.png" ErrorPlaceholder="error.png" DownsampleToViewSize="true"
                    Aspect="AspectFit" HeightRequest="400" WidthRequest="400" Source="{Binding ImageUrl}">
                    <ffimageloading:CachedImage.Transformations>
                        <fftransformations:CornersTransformation
                            CornersTransformType="BottomLeftCut,TopRightRounded"
                            BottomLeftCornerSize="20"
                            TopRightCornerSize="30"/>
                    </ffimageloading:CachedImage.Transformations>
                </ffimageloading:CachedImage>


I copied this from your corners transformation sample, but i ddnt get the image above. Please check for me

**Comment by abrantie1z** [comment]
@daniel-luberda Good morning. Please have you taken a look at the XAML i sent?
