### ISSUE TITLE
Xamarin 4.0 and FFImageLoading

### ISSUE THREAD

**Issue by HugoTruffe** [luberda-molinet/FFImageLoading#1287]
Hi People.

I am updating my project to Xamarin 4.0, and I am using skiaSharp 1.68.0 but I have this problem.

/Users/Enzo/Projects/Clarika/Imperial-ClienteFiel/ClienteFiel.Forms.iOS/MTOUCH: Error MT0009: Error while loading assemblies: /Users/hugo/.nuget/packages/skiasharp/1.68.0/runtimes/win-x86/native/libSkiaSharp.dll (MT0009) (ClienteFiel.Forms.iOS)

My question.

Does FFImageLoading support the new version o Xamarin?

Thx!

**Comment by daniel-luberda** [comment]
- Make sure you have the same package version in every project
- Make sure you have SkiaSharp package installed in every project
- remove all `bin`/`obj` folders
https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#step-1

**Comment by HugoTruffe** [comment]
Hi Daniel.

Yes, I did all the step, but the bug continues.

**Comment by HugoTruffe** [comment]
In Android is running correctly, only in iOS is the bug

**Comment by rens-andrew** [comment]
I am having the same issue. All package versions are the same in all projects, Android builds correctly, and iOS fails while trying to load libSkiaSharp.

**Comment by daniel-luberda** [comment]
See this: https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support#important-skiasharp-issue-httpsgithubcomxamarinxamarin-maciosissues5265

Thanks to @HugoTruffe for finding it.

**Comment by HugoTruffe** [comment]
Hi Daniel!!!!

Thanks!!!!! Now I can implement the rest jejejeje.
