### ISSUE TITLE
Please call CachedImageRenderer.Init method in a platform specific project to use FFImageLoading!

### ISSUE THREAD

**Issue by PabloSanzRodrigues** [luberda-molinet/FFImageLoading#1291]
### Description

Im using the last stable version for ffImageLoading, SkiaSharp and Xamarin Forms. I have the "inits" for platform especific (MainActivity and AppDelegate). In Android works, but in IOS it shows this error : 
Unhandled Exception:

System.Exception: Please call CachedImageRenderer.Init method in a platform specific project to use FFImageLoading! occurred

### Steps to Reproduce

Update all to last versions and try to run in iOS

**Comment by daniel-luberda** [comment]
- Make sure inits are called before any usage of FFImageLoading code
- Make sure you added all FFImageloading packages to all projects (shared & platform specific)
- Make sure you have same package versions in all projects
- Remove bin&obj directories
- Reopen solution & build

... and let me know.

**Comment by PabloSanzRodrigues** [comment]
Hi Daniel, thank you for the quick answer. I resolved the issue. The problem was that the inits were called after the initis of the APP:
`global::Xamarin.Forms.Forms.Init();`
