### ISSUE TITLE
Is it still possible to use Svg without Height or Width Request or FillAndExpand

### ISSUE THREAD

**Issue by torturegenitale** [luberda-molinet/FFImageLoading#1308]
### Description

Since I updated Xamarin.Forms to its 4th version I cannot render any Svg without specifying a HeightRequest or WidthRequest specific value or FillAndExpand to the SvgCachedImage view. Nothing is displayed at all. I have not tested on IOS but the scenario is the same for Android or UWP.

### Steps to Reproduce

Read Description

### Expected Behavior

Read Description

### Actual Behavior

Read Description

### Basic Information

- Version with issue: 
 Xamarin.Forms 4.0.0.497661
 FFImageLoading 2.4.11.892
 Skiasharp 1.68.0

- Last known good version:
Xamarin.Forms 3.6.0.344457

- Android 6 Api 23

**Comment by EEstevanell** [comment]
Is it possible?
