### ISSUE TITLE
[Android][2.4.11.982] System.DllNotFoundException: libjnigraphics.so

### ISSUE THREAD

**Issue by Huaba93** [luberda-molinet/FFImageLoading#1328]
### Description
Problem with ffimageloading v. 2.4.11.982:
`System.DllNotFoundException: libjnigraphics.so ` when using a CustomDataResolver in a release build. The problem only occurs on  Android 5.0 devices. It is working on Android 7, 8. Not tested on Android 9 & 6.

It is working on debug build (shared runtime). 
Proguard active or inactive makes no difference. 

```
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: at.funmusic.sepp.mobile, PID: 5485
[AndroidRuntime] android.runtime.JavaProxyThrowable: System.DllNotFoundException: libjnigraphics.so
[AndroidRuntime]   at (wrapper managed-to-native) Android.Runtime.JNIEnv.AndroidBitmap_lockPixels(intptr,intptr,intptr&)
[AndroidRuntime]   at Android.Runtime.JNIEnv.AndroidBitmap_lockPixels (System.IntPtr jbitmap, System.IntPtr& addrPtr) <0xa0ecef18 + 0x0003f> in <5010eb69cfde4496ac53ba6fa07e154f>:0 
[AndroidRuntime]   at Android.Graphics.Bitmap.LockPixels () <0xa0e20170 + 0x00043> in <5010eb69cfde4496ac53ba6fa07e154f>:0 
[AndroidRuntime]   at SkiaSharp.Views.Android.SKCanvasView.OnDraw (Android.Graphics.Canvas canvas) <0x9fb5bc84 + 0x001f3> in <a6c14eed3af3471db7c51e05d420f851>:0 
[AndroidRuntime]   at Android.Views.View.n_OnDraw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) <0xa0db0e68 + 0x0008b> in <5010eb69cfde4496ac53ba6fa07e154f>:0 
[AndroidRuntime]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.56(intptr,intptr,intptr)
[AndroidRuntime] 	at md5f24c356e1394bd37d0c871b61b28ee61.SKCanvasView.n_onDraw(Native Method)
[AndroidRuntime] 	at md5f24c356e1394bd37d0c871b61b28ee61.SKCanvasView.onDraw(SKCanvasView.java:46)
[AndroidRuntime] 	at android.view.View.draw(View.java:15256)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14192)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14187)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14187)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14187)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14187)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14187)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14187)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14187)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.draw(View.java:15259)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14192)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:14187)
[AndroidRuntime] 	at android.view.View.getDisplayList(View.java:14214)
[AndroidRuntime] 	at android.view.View.draw(View.java:14984)
[AndroidRuntime] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
[AndroidRuntime] 	at android.view.View.updateDisp

```

### Steps to Reproduce
Deploye to a Android 5.0 Device with these Build settings:
![image](https://user-images.githubusercontent.com/21239003/62352261-0765f900-b508-11e9-8b60-90d529be578b.png)

and use a custom data Resolver like this:
`ImageService.Instance.LoadCompiledResource("testimage.svg").WithCustomDataResolver(new SvgDataResolver(0, 200)).Preload();
`

### Basic Information

- Version with issue: 2.4.11.982
- Last known good version: 2.3.6 with Xamarin.Forms 4.1
- Platform: Android (API Level 21)

**Comment by eugie17** [comment]
This issue is happening for me too, I am suddenly having crashes in production. except it's happening on Android 6.1, 6.0 ,5.1, and 5.0 had to revert back to  2.3.6 please fix

**Comment by monolara** [comment]
Same for me here. I'm using SvgCachedImage, I'm getting the error below just for **Android Release**;

> Image loading failed: resource://ProjectName.Resources.svgImage.svg?assembly=ProjectName,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x600,type=SvgDataResolver)
System.DllNotFoundException: libjnigraphics.so
  at (wrapper managed-to-native) Android.Runtime.JNIEnv.AndroidBitmap_lockPixels(intptr,intptr,intptr&)
  at Android.Runtime.JNIEnv.AndroidBitmap_lockPixels (System.IntPtr jbitmap, System.IntPtr& addrPtr) [0x00005] in <23759d1f567c406da462106e6aa39779>:0 
  at Android.Graphics.Bitmap.LockPixels () [0x00006] in <23759d1f567c406da462106e6aa39779>:0 
  at FFImageLoading.Svg.Platform.SvgDataResolver.Decode (SkiaSharp.SKPicture picture, SkiaSharp.SKBitmap bitmap, FFImageLoading.Work.DataResolverResult resolvedData) [0x00114] in <abbbca1a40c84694bf7ea1ccd5f2f827>:0 
  at FFImageLoading.Svg.Platform.SvgDataResolver.Resolve (System.String identifier, FFImageLoading.Work.TaskParameter parameters, System.Threading.CancellationToken token) [0x00674] in <abbbca1a40c84694bf7ea1ccd5f2f827>:0 
  at FFImageLoading.DataResolvers.WrappedDataResolver.Resolve (System.String identifier, FFImageLoading.Work.TaskParameter parameters, System.Threading.CancellationToken token) [0x00098] in <a159011f32534c8eb0455a9cf0bad5a7>:0 
  at FFImageLoading.Work.ImageLoaderTask`3[TDecoderContainer,TImageContainer,TImageView].RunAsync () [0x0034a] in <a159011f32534c8eb0455a9cf0bad5a7>:0

**Comment by Huaba93** [comment]
Ok, the problem occurs only when building with the new mono version.
Tested with:
- Mono JIT compiler version 6.4.0.81 (2019-06/f55e0a671c0 Mon Jul  1 13:17:57 EDT 2019)


everything works well when building with our build agent who uses
![image](https://user-images.githubusercontent.com/21239003/62685866-c8cab580-b9c3-11e9-94f2-a11e8afb5da2.png)

I think it is related to [xamarin.android issue #3441](https://github.com/xamarin/xamarin-android/issues/3441)
