### ISSUE TITLE
On iOS, embedded png images are loaded with opacity 1 and then set to their developer specific opacity

### ISSUE THREAD

**Issue by adrianknight89** [luberda-molinet/FFImageLoading#133]
Android doesn't seem to have this issue, but I have a png file with opacity 0.5. When the page is first loaded, opacity is loaded with 1.0 and set to 0.5. in less than a second, but the transition is still visible to the user.

**Comment by daniel-luberda** [comment]
I added some possible fix, but I'm not sure it would be enough. We'll have to test it.

**Comment by molinch** [comment]
@daniel-luberda I would suggest rolling alpha nugets and letting Adrian test it. What do you think?

**Comment by daniel-luberda** [comment]
@adrianknight89  I released 2.0.7-alpha1 nuget package. Could you test it?

**Comment by adrianknight89** [comment]
Unfortunately, the issue still persists with alpha1.

**Comment by daniel-luberda** [comment]
@adrianknight89  Will you be able to provide a repro project?

**Comment by adrianknight89** [comment]
For some reason, I can't attach a zip file to the comment section here. I posted it on http://forums.xamarin.com/discussion/59431/ffimageloading-does-not-display-images-properly#latest

**Comment by daniel-luberda** [comment]
I was able to reproduce it, but don't know why is it happing (i suppose some iOS issue). @Community? :)

**Comment by molinch** [comment]
I debugged it and for me this issue comes from XF. I have no idea how to fix it.

Basically when the UIImage is assigned to the UIImageView with the fading transition occurs, ie here: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Touch/Work/UIImageViewTarget.cs#L31
In that case the UIImageView layer has opacity set to 1.

After the fading transition, when the assignment is done, the opacity is then set to the view's layer.

**Comment by daniel-luberda** [comment]
@adrianknight89  Do you still experience it on `2.1.9-pre-168-core-r`?

**Comment by adrianknight89** [comment]
@daniel-luberda Hi. Sorry for getting back to you late. I will test this tonight and update you.

**Comment by adrianknight89** [comment]
I can't believe I opened this ticket nearly a year ago. Time passes very quickly. :)

The issue seems to be fixed. It can be closed now.

**Comment by daniel-luberda** [comment]
Thanks for your help!

**Comment by sebastianolafhandjojo** [comment]
I still have this problem, I try to modify an existing Custom Renderers , from Xlabs Image button, 
and try to replace it with this, the PNG image became black. It happened in IOS only
I use FFImageLoading version 2.2.5
