### ISSUE TITLE
Corner Transformation Changes Aspect Ratio

### ISSUE THREAD

**Issue by VaslD** [luberda-molinet/FFImageLoading#1336]
### Description

A rectangular image of W/H ratio 16:9 after Corner Transformation results in a square image. Is this implied behavior or a bug?

### Steps to Reproduce

```csharp
ImageService.Instance.LoadUrl(imageUri)
            .Transform(new CornersTransformation(10, CornerTransformType.AllRounded))
            .Into(previewCell.Image);
```

### Expected Behavior

Only corners are cut or rounded. The image loaded maintains original aspect ratio.

### Actual Behavior

The image loaded is a square image with round corners.

The image does maintain AR if loaded without `.Transform()` call.

### Basic Information

- Version with issue: 2.4.11.982
- Last known good version: Unknown
- Platform: iOS

### Reproduction Link / Code

See above.

**Comment by Jcook65** [comment]
I am having the same issue. I would love to see some feedback on this ticket!

**Comment by Jcook65** [comment]
For anyone still having this issue I found that if you don't specify the CropHeight and CropWidth Ratios then they will not default to 0 but 1 or something like that. To keep the aspect ratio of the image you must specify that the Crop Ratios are 0.

**Comment by VaslD** [comment]
Thanks, Jcook. Although I no longer interested in using the library this way, it’s good to check some unknowns off my list.
