### ISSUE TITLE
[iOS] Sometimes images in a ViewCell do not show even though they are written to the cache

### ISSUE THREAD

**Issue by adrianknight89** [luberda-molinet/FFImageLoading#1339]
This is an intermittent issue for me, and I cannot create reproduction code because I do not know how or why the issue occurs. I have a `CachedImage` in a `ViewCell` and every once in a while, some cells are missing their image. Image sources are set to URLs. This only happens on iOS. Just wondering if anyone else has experienced this issue? I'm on XF 4.2 with FF 2.4. The `ListView` is using `RecycleElementAndDataTemplate` strategy.

Surprisingly, the missing images are somehow cached to the cache store. So when I refresh the `ListView`, the same exact cells are still missing images. The only way to bring them back is to clear the cache.

**Comment by bcaceiro** [comment]
I have been having issues with loading Images in general in iOS. Not from URL, but from resources. Take so long to load. this does not happen in Android (not sure if it is all related).

**Comment by lapoPaolacci** [comment]
Hi, I've the same problem, how did you solve this problem?
