### ISSUE TITLE
DownsampleToViewSize and quality

### ISSUE THREAD

**Issue by Naografix** [luberda-molinet/FFImageLoading#1384]
Hello!

I trying to display 15 photos taken by my camera with a small size (150 width and heigth) (like thumbnail) and without "DownsampleToViewSize" I got this error:

> java.lang.OutOfMemoryError: Failed to allocate a 17978124 byte allocation with 9999280 free bytes and 9MB until OOM

So, I put "DownsampleToViewSize" to true but quality is really bad.
I want to know if a possibility exists to downsample my photos without loosing to much quality.

Thanks

**Comment by adrianknight89** [comment]
I ran into this issue before as well. My workaround was to use `Bitmap.Compress()` method to compress the Android image to reduce its size to my preference.

**Comment by Naografix** [comment]
Fixed with HeigthRequest/WidthRequest at 130 and DownsampleHeight/DownsampleWidth at 300
