### ISSUE TITLE
Implement a Fit method

### ISSUE THREAD

**Issue by molinch** [luberda-molinet/FFImageLoading#14]
The method would work as Picasso Fit() method : it will downsample bitmap to match it's ImageView container.
## Android

On Android this implies to know the ImageView dimensions. Since we don't control when they are calculated we should listen to ImageView.ViewTreeObserver PreDraw.
Something similar to what is done in Picasso: https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/DeferredRequestCreator.java
## iOS

On iOS I think that we can force calculation of the UIImageView size + constraint calculation. It should be enough to access container size.

``` c#
imageView.SetNeedsLayout();
imageView.LayoutIfNeeded();
```

Note: DownSample() will need to be implemented on iOS prior to this.

If anybody has any other idea or remarks please comment

**Comment by daniel-luberda** [comment]
I could do it for Xamarin.Forms (width/height can be read easily). The problem is I need to make a property for this because Forms renderer uses own aspect ratio enumeration (which is included in Forms). Will `DownsampleToViewSize` name be ok?

**Comment by daniel-luberda** [comment]
It is working in Xamarin.Forms (`DownsampleToViewSize` property)

**Comment by molinch** [comment]
Very cool !
It'll be very useful & powerful for users 😉

2015-12-06 19:05 GMT+01:00 Daniel Luberda <notifications@github.com>:

**Comment by xleon** [comment]
What about Android? is it implemented somehow? I tried ScaleToFit = true, but this is adjusting the height creating an square image. The width does not get adjusted

**Comment by daniel-luberda** [comment]
It isn't implemented for iOS and Android yet. @molinch suggested possible implementations but it isn't done yet.

**Comment by molinch** [comment]
Even though it's easy to provide the DownSample width or height.

**Comment by daniel-luberda** [comment]
To summarize: 

| Platform | Xamarin Forms | Windows | iOS | Android |
|:-----------------------------------------------:|---------------|-----------|---------------|---------------|
| Manual Downsampling (fixed width/height values) | supported | supported | supported | supported |
| Auto Downsampling (image view size) | supported | supported | not supported | not supported |

**Comment by xleon** [comment]
Well, yesterday I was trying to adjust in Android to the view container, using a fixed DownSample and it didn´t work. Maybe because I was also using rounded corners. I got always a square

**Comment by daniel-luberda** [comment]
Yes it's because of that. RoundedTransformations has additional constructor overrides to set width/height proportions: `public RoundedTransformation(double radius, double cropWidthRatio, double cropHeightRatio)`. Just use them and you can control that.

**Comment by xleon** [comment]
I´ll try that

**Comment by daniel-luberda** [comment]
Actually it did work but default RoundedTransformation constructor forces image to be a square:
```
		public RoundedTransformation(double radius) : this(radius, 1d, 1d)
		{
		}
```

**Comment by xleon** [comment]
Should be something like this?  
```
.Transform(new RoundedTransformation(7, 200, 120))
.DownSample(200, 120)
```

**Comment by daniel-luberda** [comment]
```C#
.Transform(new List<ITransformation> {
		new RoundedTransformation(7, 200, 120))
	}
.DownSample(200, 0)
```
or
```C#
.Transform(new List<ITransformation> {
		new RoundedTransformation(7, 200, 120))
	}
.DownSample(0, 120)
```
DownSample always maintain original image aspect ratio. If you do `.DownSample(200, 120)` one of parameters is ignored.

**Comment by xleon** [comment]
I got it working with 
```
.Transform(new CornersTransformation(5, CornerTransformType.AllRounded, 200, 120))
.DownSample(200, 120)
´´´
But your example also works. Thanks!
BTW. This library is really cool. I´m using it in Mvvmcross and it´s working like a champ

**Comment by daniel-luberda** [comment]
Ok, but please mind: DownSample always maintain original image aspect ratio. If you do .DownSample(200, 120) one of parameters is ignored.  

I'll remove some posts to keep conversation within correct subject.

**Comment by antferr** [comment]
How do it in XAML? Thanks
