### ISSUE TITLE
Using SVG Icon into a Shell FlyoutItem

### ISSUE THREAD

**Issue by yodaimon** [luberda-molinet/FFImageLoading#1445]
Hi, 
i´m trying to show svg icons into a Xamarin Forms Shell Flyout using this:

`<FlyoutItem Title="Comprar" 
                      Icon="{Binding Source=comprar.svg, Converter={StaticResource 
                      SvgImageSourceConverter}}" >`

but this isn´t showing the svg icon...If i use a .png icon works well...
What am i doing wrong?
Thanks in advance

**Comment by yodaimon** [comment]
Found it!

**Comment by PAOLAMARTINME** [comment]
Hola, como lo has encontrado?

**Comment by RyuX51** [comment]
Man, don't just write "Found it!"
Share your enlightenment with the community. I'm having the same problem as you did and I'm happy for you that you found a solution, but that information doesn't help me at all.

**Comment by iouadghiri** [comment]
> Man, don't just write "Found it!" Share your enlightenment with the community. I'm having the same problem as you did and I'm happy for you that you found a solution, but that information doesn't help me at all.

Same here
