### ISSUE TITLE
Add pre-delay before starting to fetch images

### ISSUE THREAD

**Issue by eladmarg** [luberda-molinet/FFImageLoading#161]
sometimes when user is scrolling fast long list,  we shouldn't even start to download the image.
a pre-delay parameter can help to prevent this

**Comment by molinch** [comment]
We can have a Fluent Delay() method.
By default it wouldn't delay but people could specify one.

**Comment by eladmarg** [comment]
Thanks, is it possible to export it globally? so instead of pause we can set the delay?

for instance:
`ImageService.SetDelay(100);`

instead of:

`case ScrollState.Fling:
      // all image loading requests will be silently canceled
      ImageService.SetPauseWork(true); 
      break;`

**Comment by molinch** [comment]
Shouldn't be an issue to add a global parameter too.

**Comment by molinch** [comment]
@daniel-luberda it is implemented now, we just the Xamarin Forms counterpart. Could you do it?

**Comment by daniel-luberda** [comment]
@molinch Sure :)

**Comment by daniel-luberda** [comment]
It's currently implemented.
