### ISSUE TITLE
Windows: A COM call to an ASTA was blocked

### ISSUE THREAD

**Issue by sebastian-frysztak** [luberda-molinet/FFImageLoading#166]
When starting my app as share target (for those unfamiliar with Windows - for example when selecting an image in gallery and sharing), it crashes with the message:

> A COM call to an ASTA was blocked because the call chain originated in or passed through another ASTA. This call pattern is deadlock-prone and disallowed by apartment call control.
> 
> A COM call (IID: {638BB2DB-451D-4661-B099-414F34FFB9F1}, method index: 6) to an ASTA (thread 4392) was blocked because the call chain originated in or passed through another ASTA (thread 4112). This call pattern is deadlock-prone and disallowed by apartment call control.

And here's stacktrace:

```
   at Windows.ApplicationModel.Core.CoreApplicationView.get_CoreWindow()
   at FFImageLoading.Helpers.MainThreadDispatcher.<Post>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
```

So the problem arises somewhere in [here](https://github.com/molinch/FFImageLoading/blob/e165d7102c63e32f9da4bd477597a2f1f41a6cc5/source/FFImageLoading.Windows/Helpers/MainThreadDispatcher.cs#L23). I really don't know why Windows feels so upset about accessing CoreApplication at this point.
Share target activation event is almost exactly the same as regular launch event (there are two differences: app retrieves selected files and navigates to a different page).

**Comment by daniel-luberda** [comment]
@sebastian-frysztak Hi, it's probably because of that: http://stackoverflow.com/a/34978672

Replace: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Windows/Helpers/MainThreadDispatcher.cs#L29
With: 
`CoreApplication.GetCurrentView().Dispatcher`

Could you try it? I can't reproduce it.

**Comment by daniel-luberda** [comment]
@sebastian-frysztak Any news?

**Comment by molinch** [comment]
By the way FFImageLoading 2.1.0-alpha2 nuget has been released.
Could you give it a try to see if this issue is gone?

**Comment by sebastian-frysztak** [comment]
I can't check it now, as I don't have access to Windows anymore.
Thank you for taking the time to investigate the issue. I'll report back as soon as I'll be able to (might be days or weeks).

**Comment by daniel-luberda** [comment]
That fix doesn't work. Any help appreciated.

**Comment by molinch** [comment]
@daniel-luberda Have you looked into XF code how they do it?

**Comment by molinch** [comment]
That's how they do it in XF:
- [WP8](https://github.com/xamarin/Xamarin.Forms/blob/2d9288eee6e6f197364a64308183725e7bd561f9/Xamarin.Forms.Platform.WP8/WP8PlatformServices.cs#L21)
- [RT and UWP](https://github.com/xamarin/Xamarin.Forms/blob/2d9288eee6e6f197364a64308183725e7bd561f9/Xamarin.Forms.Platform.WinRT/WindowsBasePlatformServices.cs#L42)

**Comment by daniel-luberda** [comment]
So after investigating it it uses `Window.Current.Dispatcher` method to get dispatcher.

**Comment by moonClimber** [comment]
Please, have a look to issue #424, I think is not the same and I've added some notes even if it's closed.
Thanks

**Comment by alexkrafts** [comment]
I've got the same issue using CacheType.Disk or CacheType.All for a set of images. Works fine for CacheType.Memory. Here is a stacktrace

The message filter indicated that the application is busy.

A COM call (IID: {638BB2DB-451D-4661-B099-414F34FFB9F1}, method index: 6) to an ASTA (thread 12292) appears deadlocked and was timed out. --> System.Runtime.InteropServices.COMException (0x8001010A): The message filter indicated that the application is busy.

A COM call (IID: {638BB2DB-451D-4661-B099-414F34FFB9F1}, method index: 6) to an ASTA (thread 12292) appears deadlocked and was timed out.
   at Windows.ApplicationModel.Core.CoreApplicationView.get_CoreWindow()
   at FFImageLoading.Helpers.MainThreadDispatcher.<Post>d__3.MoveNext()

**Comment by daniel-luberda** [comment]
Can you reproduce it with 2.2.10?

**Comment by daniel-luberda** [comment]
In the recent 2.2.10 stable build there was some fix related to Windows `MainThreadDispatcher`. Please reopen if you still can reproduce that bug. Thanks.
