### ISSUE TITLE
Enhancement: iOS Behavior with Xamarin Forms

### ISSUE THREAD

**Issue by RanaInside** [luberda-molinet/FFImageLoading#167]
Nutshell: While the image is loading, placeholder image is not displayed.

On a page, I have a cached image with LoadingPlaceholder, ErrorPlaceholder, and Source set; I've tried both binding method or directly specifying the values;

On device, I initially get a white box area (I have specified image width and height; page has white background); then web image loads and I see the image; But while the image is loading, placeholder image is not displayed.

**Comment by daniel-luberda** [comment]
Hi @RanaInside, would you be able to make a reproduction? I am not aware of any issues regarding placeholders.

**Comment by daniel-luberda** [comment]
@RanaInside  Feel free to reopen this issue if you have some new informations.
