### ISSUE TITLE
Caching downsampledtoview image

### ISSUE THREAD

**Issue by patook** [luberda-molinet/FFImageLoading#185]
Hi - not sure what you're currently doing but I had the following problem:

1- Display 500 times the same cachedimage on Android -> often crash, out of memory, but when it succeeds it is fast.
2- As (1) but with DownsampleToview=1. No crash but very slow performance.

Do you have any idea what might be happening? All views are the same size.

**Comment by molinch** [comment]
@patook Could you send us a sample and also tell us where it fails? simulator, real device (which one?)

Thanks!

**Comment by daniel-luberda** [comment]
@patook Can you define "slow performance"? Is it slow loading? Or something else?

**Comment by molinch** [comment]
@patook It would be really great if you could give more context here.
We are definitely interested to check into it but we need more info.
Thanks!

**Comment by molinch** [comment]
Closing since we have no news since 20 days.
Please reopen if you have more informations to share.
