### ISSUE TITLE
Feature Request: Consolidate Nuget packages

### ISSUE THREAD

**Issue by ravensorb** [luberda-molinet/FFImageLoading#187]
Has there been any thought to consolidating the nuget packages?

If you look at 
https://i.imgur.com/HSG3Qus.png

There are 6 packages and it is really difficult to determine which one to include when.  

Maybe combine FFImageLoading.Windows with Xamarin.FFImageLoading?

**Comment by molinch** [comment]
@ravensorb In fact there are only 4. I have no idea why somebody created 2 alternative packages (they end with f3).

**Comment by ravensorb** [comment]
ok - it was/is still a little confusing :)  

Thanks

**Comment by molinch** [comment]
I contacted the package owner and he seem to have removed f3 nuget packages.
So now we have only 4 packages visible via search.

Having windows in the same package won't be complicated.

**Comment by ravensorb** [comment]
Any thoughts on combing the Windows version into a the main package?

**Comment by molinch** [comment]
It is a very good idea, it is planned for 2.2.

**Comment by molinch** [comment]
2.1 released which has only 3 nugets now.
Old windows package has been unlisted, it will take a few hours to be visible.

**Comment by molinch** [comment]
And thanks for your help !! 👍
