### ISSUE TITLE
CircleTransformation with border

### ISSUE THREAD

**Issue by TravyDale** [luberda-molinet/FFImageLoading#190]
I am pretty sure you have support for a border with CircleTransformation, but how do you set this up in XAML? I cannot figure this out. Please assist.

**Comment by daniel-luberda** [comment]
Just use something like: 
```XML
<fftransformations:SomeTransformation>
    <x:Arguments>
      <x:String>
        stringConstructorValue
      </x:String>
    </x:Arguments>
</fftransformations:SomeTransformation>
```

or 

make a custom class which inherits from transformation: 

```C#
public class MyTransformation : SomeTransformation
{
  public MyTransformation() : base("someParameter")
  {
  }
}
```

then use it in XAML as: `<local:MyTransformation/>`

**Comment by TravyDale** [comment]
Hmm it isnt working for CircleTransformation. Here is my XAML:

```
<ffImage:CachedImage.Transformations>
          <fftransformations:CircleTransformation>
            <x:Arguments>
              <x:Double>2</x:Double>
              <x:String>#FF8A07</x:String>
            </x:Arguments>
          </fftransformations:CircleTransformation>
```

I dont see any errors when debugging. I even see this in my debug messages:
`05-07 18:35:15.802 D/ReuseBitmapDrawableCache( 1246): OnEntryAdded(key = https://www.someurl.com/83.jpeg;CircleTransformation,borderSize=2,borderHexColor=#FF8A07)`

**Comment by daniel-luberda** [comment]
That's strange, it should work. As you see FFImageLoading is using correct transformation (`CircleTransformation,borderSize=2,borderHexColor=#FF8A07`). Do you have any reproduction?

**Comment by TravyDale** [comment]
Sorry, I'm not sure I follow what you mean with your question -- Are you sure you changed image source after you set Transformations?

I am new to your library so maybe I missed something I was supposed to do. All I do is bind my Source property to what I have in my ViewModel and then also in my XAML I have what I gave you above for the CircleTransformation. I see the Circle Image but just no border. I am using your Alpha-2 version if that helps.

**Comment by daniel-luberda** [comment]
@TravyDale If you set `CachedImage.Source` property first then set `CachedImage.Transformations` the image will be without transformations. You have to set `CachedImage.Transformation` property first, then set `CachedImage.Source` property.

**Comment by TravyDale** [comment]
How would I do this via XAML then? My property in my ViewModel doesnt get set until my 'NavigatedTo' method is called. I'd think that would re-set my Source proprety when the RaisePropertyChanged is fired. I am assuming the Transformation is already set at that point. Especially since I am seeing the debug message trying to use the borderSize and borderHexColor.

**Comment by daniel-luberda** [comment]
Yes, I see from logs that transformation is set correctly (`https://www.someurl.com/83.jpeg;CircleTransformation,borderSize=2,borderHexColor=#FF8A07)`, so it should be working fine. I would uninstall all nugets and re-add them, don't forget about Transformations package. If it won't work disable assembly linking in project settings.

**Comment by TravyDale** [comment]
RC2 seems to have fixed it. Thanks!
