### ISSUE TITLE
Display non-animated .gif

### ISSUE THREAD

**Issue by P0rKnPiK** [luberda-molinet/FFImageLoading#191]
Hi everyone,

I try to find how to display a .GIF picture non-animated. 
It's weird i know, but i don't have the choice. I already tried to use ImageView and MvxImageView but it doens't work.
If anyone has a solution, thanks in advance.

**Comment by daniel-luberda** [comment]
You should parse that bitmap from gif file manually and load it to your image instance as a stream image source.
