### ISSUE TITLE
Rare crash in StrongLruCache: System.NullReferenceExceptionObject reference not set to an instance of an object

### ISSUE THREAD

**Issue by patook** [luberda-molinet/FFImageLoading#192]
2 occurrences in 30,000 sessions.

<pre>
FFImageLoading.Collections.StrongLruCache<TKey, TValue>.Add(TKey key, TValue value, bool overwrite)
FFImageLoading.Collections.StrongLruCache<TKey, TValue>.Add(TKey key, TValue value)
FFImageLoading.Cache.ReuseBitmapDrawableCache.DemoteDisplayedEntryToReusePool(SelfDisposingBitmapDrawable value)
FFImageLoading.Cache.ReuseBitmapDrawableCache.OnEntryNoLongerDisplayed(object sender, EventArgs args)
FFImageLoading.Drawables.SelfDisposingBitmapDrawable.SetIsDisplayed(bool isDisplayed)
FFImageLoading.Views.ManagedImageView.UpdateDrawableDisplayedState(Drawable drawable, bool isDisplayed)
FFImageLoading.Views.ManagedImageView.Dispose(bool disposing)
Java.Lang.Object.Dispose()
</pre>

**Comment by molinch** [comment]
@patook By any chance do you know the device model and API version?
Any extra information would help.

**Comment by patook** [comment]
Yes, this is Android 4.2, device RCT6103W46 

 

It is running XF2.1 and the FFImageLoading from just before you updated to XF2.2.

**Comment by molinch** [comment]
If you get it with 2.1 could you post the error message too?
We added some arguments check so it will be easier to track it down: https://github.com/molinch/FFImageLoading/blob/017541135eba42fee001b11016556231e8524772/source/FFImageLoading.Droid/Collections/StrongLruCache.cs#L118

**Comment by patook** [comment]
Yes. I will push out a build with 2.1 to Android app store as soon as XLabs is stable on Android with XF2.2. Hopefully by next week.

 

Thank you for your time in responding to this.

**Comment by daniel-luberda** [comment]
@patook  2.1.0-alpha2 should work on any Xamarin.Forms version. You can test it as it has some fixes related to this issue.

**Comment by molinch** [comment]
@patook Have you received it with 2.1? By the way we just release RC2 prelease nuget.

**Comment by molinch** [comment]
Closing since 2.1 is now released. Feel free to reopen if you still have the issue.
