### ISSUE TITLE
Finish Custom Transformations Wiki

### ISSUE THREAD

**Issue by Zeraceee** [luberda-molinet/FFImageLoading#193]
I would love to be able to create custom color filters with FFImageLoading, but sadly the "Custom Transformations" section of the wiki is marked as "TODO". I understand y'all are busy updating and fixing up the library at any given time, but I feel as though this documentation would be useful for many people.

**Comment by daniel-luberda** [comment]
A lot of docs need rewriting, I'll try to do it soon. There are some examples how to use color filters in samples here: https://github.com/molinch/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/PageModels/TransformationPageModel.cs#L88

You can create own color matrices. Some build-in are here: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Common/Transformations/FFColorMatrix.cs

**Comment by Zeraceee** [comment]
@daniel-luberda I'll experiment around with it here soon, and if I can, write up a little contribution document myself. Thanks for giving me a solid start.

**Comment by daniel-luberda** [comment]
No problem, if you need any help - just ask here. Thanks @Zeraceee, any contribution is very appreciated.

**Comment by molinch** [comment]
@Zeraceee have you managed to do your custom transformation?
If yes, then it would be super nice if you managed to add a Wiki description :+1:

**Comment by Zeraceee** [comment]
@molinch I have not gotten around to it yet, sorry. Hopefully I will within the next 2 weeks.
