### ISSUE TITLE
Image Cache Windows UWP Xaml

### ISSUE THREAD

**Issue by vime-o** [luberda-molinet/FFImageLoading#195]
Hi everyone,
How to implement image cache using xaml? There are a property call CacheDuration in xaml but the documentation doesn't clear. Do you have some example with CacheDuration=2 days?
I would like download images only each 2 days.
Thanks.

**Comment by daniel-luberda** [comment]
When using Windows UWP XAML `CacheDuration` is an `int` which means number of days.

**Comment by vime-o** [comment]
@daniel-luberda Thanks!! I don't understood this, so, I have this code for two days:
<ff:FFImage LoadingPlaceholder="loading.png" ErrorPlaceholder="error.png" Source="{Binding img}" RetryCount="3" RetryDelay="200" CacheDuration="2" />
Now, I undestand!
And How do I set the images stored in cache? It is auto? Thanks. :)

**Comment by daniel-luberda** [comment]
No problem :) Yes, it's automatically cached in memory and disk (for offline usage).

**Comment by vime-o** [comment]
@daniel-luberda  Oh thanks!! :)

**Comment by molinch** [comment]
@vime-o can we close this?
