### ISSUE TITLE
FFImageLoading.Forms.Droid does not exists on v2.0.7.1

### ISSUE THREAD

**Issue by egeaydin** [luberda-molinet/FFImageLoading#196]
Hello there, when I try to intiliaze FFImageLoading on android project the library FFImageLoading.Forms.Droid does not exists on version 2.0.7.1. However when I downgraded it to V2.0.6 it does exists. I wonder if it got moved to somewhere and I cannot find where it is.

Regards

**Comment by molinch** [comment]
@egeaydin Never had this issue or heard anything similar. 2.0.7.1 should work fine it's there since a while.
Can you try to uninstall the nugets, then reinstall them ?

**Comment by molinch** [comment]
@egeaydin Any news?

**Comment by daniel-luberda** [comment]
It happens sometimes, but it's IDE / issue (not FFImageLoading specific). Just remove package and install it once again.

**Comment by BurningAXE** [comment]
Just restarting the IDE (Visual Studio for Mac 7.1) helped in my case.
