### ISSUE TITLE
151 issues in Xamarin Forms Android

### ISSUE THREAD

**Issue by alexrainman** [luberda-molinet/FFImageLoading#197]
I cannot use the library. It's giving me 151 resources errors like this one: 
```
/Users/alexrainman1975/Downloads/HSEMobile-XPlat-Dev/Droid/Resources/Resource.designer.cs(144,144):
Error CS0117: `HSEMobile.Droid.Resource.Dimension' does not contain a definition for
`mr_media_route_controller_art_max_height' (CS0117) (HSEMobile.Droid)
```
Is there any requirement i am missing? I am using Support packages 23.3.0, Xamarin.Forms 2.2.0.31

**Comment by alexrainman** [comment]
I downloaded the source code. Updated to latest Android packages, compiled a released and used as reference in my project and it works so, you may do a new release.

**Comment by molinch** [comment]
@alexrainman That is fixed in our prerelease nugets. We will deliver a final release in the coming days.
