### ISSUE TITLE
Issue: Unable to read package:  File contains corrupted data

### ISSUE THREAD

**Issue by ravensorb** [luberda-molinet/FFImageLoading#199]
I just tried to update and now I am getting the following

```
Unable to read package from path 'Xamarin.FFImageLoading.2.1.0-rc1\Xamarin.FFImageLoading.2.1.0-rc1.nupkg'.
  File contains corrupted data.
Unable to read package from path 'Xamarin.FFImageLoading.2.1.0-rc1\Xamarin.FFImageLoading.2.1.0-rc1.nupkg'.
  File contains corrupted data.
```

I have tried to re-download the packages and that is not help either.

**Comment by ravensorb** [comment]
From looking at the nuspec that is stored inside the package, there are a few things that look a bit off.

Example:
* There is a folder for MonoAndroid10, Xamarin.ios10, and a portal profile, however each folder has exactly the same assemblies by name.  Isn't it normal to have platform specific named assemblies to prevent collisions?
* There is a reference to dependencies only for MonoAndroid1.0 and Xmarin.iOS1.0 in the nuspec, however the one for MonoAndroid doesn't actually contain any dependencies

**Comment by daniel-luberda** [comment]
Thanks for the info.  I'll analyze that and release rc2 today/tommorow

**Comment by ravensorb** [comment]
if it helps, I have been using the [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) for most of my nuspec editing lately.  It is good enough were I can do the minor fixes by hand.

**Comment by ravensorb** [comment]
Looks like the same issue exists for the Xamarin Forms alpha build

**Comment by molinch** [comment]
That is quite strange: nobody else complained about the nuget packages. We will check it.

@ravensorb We use [Bait & Switch](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/) so it is mandatory to have the same assembly name/namespaces for each platform.

**Comment by daniel-luberda** [comment]
@ravensorb New nugget released. If you still have issues, please reopen the issue. Thanks.
