### ISSUE TITLE
Example of XAML Usage in ListView with ListViewCachingStrategy.RecycleElement enabled using normal ViewCell

### ISSUE THREAD

**Issue by Korayem** [luberda-molinet/FFImageLoading#200]
I tried following instructions on [this page](https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced) and [that page too](https://developer.xamarin.com/guides/xamarin-forms/user-interface/listview/performance/#RecycleElement) but both show code-behind implementation (non XAML). In case of XAML, if I have the following `list view` with normal `view cell`,  what should I do to set `OnBindingContextChanged` of ViewCell to be compatible with `Recycle` Caching Strategy?

```
	<ListView x:Name="listView" CachingStrategy="RecycleElement">
				<ListView.ItemTemplate>
					<DataTemplate>
						<ViewCell>
							<ViewCell.View>
								<StackLayout Orientation="Horizontal">
                                                              <ffimageloading:CachedImage HorizontalOptions="Center" VerticalOptions="Center"  WidthRequest="300" HeightRequest="300" DownsampleToViewSize="true" />
									<Label Text="{Binding Name}"/>
								</StackLayout>
							</ViewCell.View>
						</ViewCell>
					</DataTemplate>
				</ListView.ItemTemplate>
			</ListView>
```

Thanks

**Comment by molinch** [comment]
@Korayem This is described in the wiki: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced

**Comment by Korayem** [comment]
Thanks @molinch for the detailed explanation

My issue with using custom view cell is that my viewcell is implemented in XAML and has other elements like labels, stacklayout etc.. along with FFImage. From the custom cell implementation you linked too, it assumes the viewcell only contains FFImage which is not in my case.

**Comment by Korayem** [comment]
It's described with no mention of XAML and using Custom View

**Comment by molinch** [comment]
@daniel-luberda Could you answer? I have not enough knowledge of XF.

**Comment by daniel-luberda** [comment]
@Korayem You should create separate XAML view for a cell (separate file: Add File -> Forms ContentView XAML), then use it in your page:

```C#
<ListView x:Name="listView" CachingStrategy="RecycleElement">
	<ListView.ItemTemplate>
		<DataTemplate>
			<ViewCell>
				<ViewCell.View>
					<local:YourCustomView/>
				</ViewCell.View>
			</ViewCell>
		</DataTemplate>
	</ListView.ItemTemplate>
</ListView>
```

Then override `OnBindingContextChanged` method in `YourCustomView.xaml.cs` file.

**Comment by molinch** [comment]
@daniel-luberda Maybe wiki could be improved regarding Recycle strategy? So we have the XAML example too

**Comment by daniel-luberda** [comment]
@molinch Yes, definitely. There're much more things to update in Wiki for Forms. I'll try to do that when I'll have some time.

**Comment by michaeldimoudis** [comment]
Don't want to open up another issue, as my question is related to this. So I have a ViewCell in XAML, in the xaml.cs code behind I did put OnBindingContextChanged. I named the CachedImage and I tried to set the source in the code behind, but the source was never set. Only way I could get it to work is in XAML Source={Binding MyImage} etc.

Any tips on this?

**Comment by db-007** [comment]
How would you use FFImageLoading with a ListView.ImageCell?
