### ISSUE TITLE
FFImageLoading 2.2 changes - please give us your opinion

### ISSUE THREAD

**Issue by daniel-luberda** [luberda-molinet/FFImageLoading#202]
We want to release 2.2 soon, it's a good occasion to do some changes. 
- Is there any API refactoring necessary?
- Are there any library defaults that should be changed? 
- Is there any feature you're missing? 
- etc. 

Feel free to give us your opinion.

**Comment by daniel-luberda** [comment]
Some my ideas: 

- Transparency should be enabled by default for images loaded from application resources (Android specific) as this is a common usage scenario. 
- better Transformations XAML support (Xamarin.Forms specific) - we could use XAML constructor parameter as here: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ListView.cs#L70
- Windows transformations BitmapHolder optimization - it will force some modifications of existing custom transformations as BitmapHolder class will change.

**Comment by owlstack** [comment]
Hi, thank you so much for your work. I am waiting for stable release so that I can use the preload method soon :) The only other thing I am wondering about is... I reuse grid cells for images and I notice that when the view loads, some of the old images appear briefly for a sec before the new images load. I am wondering, is the best situation to fix this issue is to add a placeholder image for LoadingPlaceholder? I am also thinking about clearing to cells by setting the images to null first before loading the new images. However, I am wondering if there's another way to do this. 

This mostly happens with low/bad connectivity

What do you recommend? Thanks :)

**Comment by NVentimiglia** [comment]
+1

**Comment by patook** [comment]
Is there a way to apply the transformations post aspect ratio fitting?

For example, I want to have 10pixel radius corners for my images, but since I've set AspectFill, the transformation gets aspect fitted as well.

**Comment by krisrok** [comment]
is only partially related to this issue, but what i don't get.. how do we know which xamarin.forms version is this (or really any xamarin.forms pcl) build with/for?

i'm on forms 2.2.0.31 (latest stable at time of writing) and on android it just worked, installed via nuget -IncludePrerelease. on ios i get the exception "Could not load file or assembly 'FFImageLoading.Forms' or one of its dependencies".

from my earlier tinkering with your library i know i could probably get it to work by compiling the sources against forms 2.2.0.31 (though i haven't tried).

any help is greatly appreciated!

**Comment by daniel-luberda** [comment]
@patook Two ways:
- Some of the transformations have alternative constructors which allow to set aspect ratio. 
- You can use **multiple transformations**, so you could add `CropTransformation` first (which lets you control size / aspect ratio), then another one, like `CircleTransformation`.

@krisrok 
FFImageLoading 2.2 should work on **any** Xamarin.Forms version. 
- You must include `CachedImageRenderer.Init()` call in every platform specific project as stated here: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#important
- Are you sure all nuget packages installed successfully? You should have Xamarin.FFImageLoading and Xamarin.FFImageLoading.Forms in every project (shared and platform specific). Also please try to uninstall all packages and add them again (sometimes XS have some issues with packages)

**Comment by daniel-luberda** [comment]
@owlstack The solution is here: 
- https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#usage-in-listview-with-listviewcachingstrategyrecycleelement-enabled
- https://developer.xamarin.com/guides/xamarin-forms/user-interface/listview/performance/#RecycleElement

**Comment by patook** [comment]
@daniel-luberda Since you're asking for our feedback, is there any chance FFImageLoading can resolve the longstanding animated GIF problem with Xamarin? I would like nothing better than just put a CachedImage with Source = GIF file and have it play automatically.

**Comment by daniel-luberda** [comment]
@patook I think it's possible but it's quite a lot of work.

- Picasso and Glide loaders for Android support it
- For iOS there's https://github.com/Flipboard/FLAnimatedImage

Maybe you could create an issue for that?

**Comment by CliffCawley** [comment]
I upgraded from 2.0 to 2.1 and noticed that DownloadImageAndAddToDiskCacheAsync is missing. Is it possible to add it back for 2.2 or should I do something else?

**Comment by NVentimiglia** [comment]
We had to disable the fade animation as we load from cache. It was somewhat ugly to have that show up on every reload of the page for cached images.

**Comment by molinch** [comment]
@daniel-luberda I don't remember here: is @NVentimiglia 's feedback an issue or just a config parameter that we should most likely default to true?

**Comment by molinch** [comment]
@CliffCawley You should now use ImageService.Instance.xxx methods

**Comment by owlstack** [comment]
@molinch I'm having an issue when I upgraded to 2.1.2, my images are cached loaded with a black background and some of the images are appearing in the wrong slots. This wasn't happening before with 2.1.0. So now the same images is loaded several times in a row even though it was not like so before. Did anything change?

**Comment by molinch** [comment]
@owlstack could you try the latest prerelase?

**Comment by owlstack** [comment]
I can't use prelease for my project :( But I can try 2.1.3. waiting for a new stable release after PR. Btw, I forgot to mention, this only happens in a scrollview when swiping between pages.

**Comment by molinch** [comment]
it's not possible to give it a try? then bring back stable version?

**Comment by owlstack** [comment]
ah ok, I will give it a try thanks :)

**Comment by owlstack** [comment]
@molinch It actual seems to happen intermittantly. I will try the prelease :S

**Comment by molinch** [comment]
Thanks for your feedback @owlstack
I'm waiting for @highplains too.
If it's fine for both then we can release it.

**Comment by owlstack** [comment]
One more thing... the time it takes  for images to be cached for future uses takes a a while. I have about 100 images I need to preload and I noticed if I have a fast internet, they all load in 2 mins or less. If I have a slow connection, it takes the images to preload in 8 mins or less. Is there something I can do to prove the performance for images to be preloaded?

**Comment by molinch** [comment]
How do you preload, can you show some code?
Please create a separate issue. Thanks!

**Comment by rusty21** [comment]
One thing that I've noticed is ImageViews flashing on reload. Say I have a listview on android and lets say updated the backing model of the listview and i want to do a adapter.NotifyDataSetChanged(), all of my images loaded with FFImageLoading flash. It would be nice if somehow FFImageLoading could know that the image its about to load is the same image already in the ImageView. Therefore nothing needs to get loaded so no image flash.

**Comment by daniel-luberda** [comment]
@rusty21  There's a new prerelease of FFImageLoading (2.1.8-pre-150) which introduces some stability & performance improvements (eg. image is not cleared when image source is not changed), so there is no flashing.
