### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by chkrishna2001** [luberda-molinet/FFImageLoading#204]
Recently I am getting error in resource designer, I have areoud 1591 errors like this please help. not sure what is causing this issue

<pre>
global::FFImageLoading.Forms.Droid.Resource.String.mr_media_route_button_content_description = global::Sthotraani.Droid.Resource.String.mr_media_route_button_content_description;
global::FFImageLoading.Forms.Droid.Resource.String.mr_media_route_chooser_searching = global::Sthotraani.Droid.Resource.String.mr_media_route_chooser_searching;
global::FFImageLoading.Forms.Droid.Resource.String.mr_media_route_chooser_title = global::Sthotraani.Droid.Resource.String.mr_media_route_chooser_title;
global::FFImageLoading.Forms.Droid.Resource.String.mr_media_route_controller_disconnect = global::Sthotraani.Droid.Resource.String.mr_media_route_controller_disconnect;
global::FFImageLoading.Forms.Droid.Resource.String.mr_media_route_controller_no_info_available = global::Sthotraani.Droid.Resource.String.mr_media_route_controller_no_info_available;
global::FFImageLoading.Forms.Droid.Resource.String.mr_media_route_controller_pause = global::Sthotraani.Droid.Resource.String.mr_media_route_controller_pause;
global::FFImageLoading.Forms.Droid.Resource.String.mr_media_route_controller_play = global::Sthotraani.Droid.Resource.String.mr_media_route_controller_play;
global::FFImageLoading.Forms.Droid.Resource.String.mr_media_route_controller_settings_description = global::Sthotraani.Droid.Resource.String.mr_media_route_controller_settings_description;
global::FFImageLoading.Forms.Droid.Resource.String.mr_media_route_controller_stop = global::Sthotraani.Droid.Resource.String.mr_media_route_controller_stop;
</pre>

**Comment by molinch** [comment]
@chkrishna2001 Can you please add some context? We can't help without more detailed information.
Thanks!

**Comment by chkrishna2001** [comment]
Whenever i build the project I get many resource not found errors and all are pointing to the resources used by FFImage loading

`'Resource.Attribute' does not contain a definition for 'mediaRouteSettingsDrawable'	
'Resource.Color' does not contain a definition for 'design_textinput_error_color'	
'Resource.Dimension' does not contain a definition for 'design_fab_content_size'	`
Please let me know if you need anything

**Comment by daniel-luberda** [comment]
Are you using the preview 2.1.0-rc2 nuget release?

**Comment by chkrishna2001** [comment]
No.
I am using 2.0.7.1 stable  version

**Comment by daniel-luberda** [comment]
Please use the preview version

**Comment by chkrishna2001** [comment]
okay will try that. Thank you

**Comment by chkrishna2001** [comment]
After adding the preview app is just shutting down. build is successful but not debugging at all. after deplyment it's shutting down, not sure whether this is the cause or not
`Android application is debugging.
The application could not be started. Ensure that the application has been installed to the target device and has a launchable activity (MainLauncher = true).

Additionally, check Build->Configuration Manager to ensure this project is set to Deploy for this configuration.`
that's what I see in output window. Please help me.

**Comment by chkrishna2001** [comment]
No I am unable to remove the prerelease version :(

Unable to read package from path 'Xamarin.FFImageLoading.Forms.2.1.0-rc2\Xamarin.FFImageLoading.Forms.2.1.0-rc2.nupkg'.
  File contains corrupted data.
Unable to read package from path 'Xamarin.FFImageLoading.Forms.2.1.0-rc2\Xamarin.FFImageLoading.Forms.2.1.0-rc2.nupkg'.
  File contains corrupted data.
Unable to read package from path 'Xamarin.FFImageLoading.Forms.2.1.0-rc2\Xamarin.FFImageLoading.Forms.2.1.0-rc2.nupkg'.
  File contains corrupted data.
Unable to read package from path 'FFImageLoading.Windows.2.1.0-rc2\FFImageLoading.Windows.2.1.0-rc2.nupkg'.
  File contains corrupted data.
Unable to read package from path 'FFImageLoading.Windows.2.1.0-rc2\FFImageLoading.Windows.2.1.0-rc2.nupkg'.
  File contains corrupted data.

**Comment by molinch** [comment]
The last issue will be fixed with RC3. It should be submitted soon.

**Comment by molinch** [comment]
@chkrishna2001 That may be an issue in your Nuget cache. You can see:
http://stackoverflow.com/questions/19601350/strange-nuget-error-while-enabling-nuget-package-restore

Can you try to remove FFImageLoading packages from your cache: %localappdata%\NuGet\Cache

**Comment by molinch** [comment]
Fixed with the 2.1 release
