### ISSUE TITLE
Placeholder Images get streched/shrinked if actual Source Image has a different aspect ratio

### ISSUE THREAD

**Issue by bspinner** [luberda-molinet/FFImageLoading#208]
We're using FFImageLoading with placeholder images which are shown during loading (as you likely will know).

When those placeholder images fade to the actual source image after its loaded via http, the placeholder images are stretched to the source image's aspect ratio during that fade.

**Comment by molinch** [comment]
Yes, I think we have the same issue as https://github.com/square/picasso/issues/427
I have no idea yet how to fix it.

**Comment by Slava8991** [comment]
+1 for Xamarin.Forms. Solution may be not cross-fade (placeholder disappear and image appear the same time) but do it step-by-step - placeholder disappear with animation, image view resize itself, image appear with animation. Currently cross-fade don't look good, sequence may looks better :)

**Comment by daniel-luberda** [comment]
Here's the code for fading on Android: https://github.com/luberda-molinet/FFImageLoading/blob/28ca8b323215a5fbbdcb5fd0b7f3274f0dda7af4/source/FFImageLoading.Droid/Drawables/FFBitmapDrawable.cs#L29-L66

**Comment by daniel-luberda** [comment]
Should be fixed in `2.1.9-pre-168-core-r`. Please reopen it if doesn't work for you.
