### ISSUE TITLE
CachedImage shows placeholder only

### ISSUE THREAD

**Issue by NVentimiglia** [luberda-molinet/FFImageLoading#209]
I have a xamarin forms app and this is replicated on IOS and Android. I have a dashboard with about a dozen images in a scroll list. I have two issues.

On the initial load, the first image never loads (showing nothing), and the rest of the images load fine. I noticed a few other images are missing in my app. The missing images appear to be local PNGs. 

After a few navigations around the app, I will notice that all of the loaded images 'reset' to the placeholder image. Retry is enabled. Tried with cache set to default and 00:00:00. The data source for these is a url.

- How can we debug why the first image does not load, or show an error / loading state
- How can we debug why the image resets to the placeholder image ?

**Comment by NVentimiglia** [comment]
Using 2.1 with XamForms 2.2

**Comment by daniel-luberda** [comment]
@NVentimiglia  Do you still experience those issues on Android / iOS in 2.1? Is related to usage of camera (email) or is it another issue?

**Comment by NVentimiglia** [comment]
More detail, the issue was caused when backgrounding the app (such as opening the camera). We fixed this by removing the 'end task early' feature from our application class.

`ImageService.Instance.SetExitTasksEarly(false);`

**Comment by NVentimiglia** [comment]
Re-opened.

Might want to fix this, or update the documentation.

**Comment by molinch** [comment]
I guess you were using SetExitTasksEarly while scrolling in lists right?

**Comment by NVentimiglia** [comment]
yes

**Comment by molinch** [comment]
Would it be possible to have a simple repro for it?

**Comment by NVentimiglia** [comment]
The solution is to not call ImageService.Instance.SetExitTasksEarly(true); and ImageService.Instance.SetExitTasksEarly(false); To replicate load a few images in a Xamarin forms scrollable list

**Comment by molinch** [comment]
Could you give a try to 2.1.1? if it still occurs I will make a sample.

**Comment by molinch** [comment]
@NVentimiglia Could you please upload a sample?
Once we have one it will be easy to check & fix.

**Comment by molinch** [comment]
Hi @NVentimiglia Could you upload a sample?
Otherwise we won't look at this issue.

**Comment by molinch** [comment]
@NVentimiglia I'm definitely keen on fixing this however I really need a sample. Could you upload one?

**Comment by NVentimiglia** [comment]
I don`t have a sample right now, and I don`t have the time for a sample at the moment.

You can close the issue if you like, I appreciate your vigor.
