### ISSUE TITLE
LoadFile not work  with path gallery image in xamarin android

### ISSUE THREAD

**Issue by vsarnataro** [luberda-molinet/FFImageLoading#211]

**Comment by molinch** [comment]
@vsarnataro This is clearly not enough for us to debug it.
Can you add some context:
- What is your loading request?
- Android API version?
- Device model?

Thanks

**Comment by vsarnataro** [comment]
with 4.4.2 and 5.0 on s4 mini and nexus 5 emulator.
I get  photo with:

                imageIntent.SetType("image/*");

                imageIntent.SetAction(Intent.ActionGetContent);

                StartActivityForResult(Intent.CreateChooser(imageIntent, "Select photo"), 0);

and try put it in asyncImageView 
                   ` ImageService.Instance.LoadFile(data.Data.Path).Transform(new CircleTransformation(10, "#FFFFFF")).Into(userImage);`

with normal ImageView this code work

**Comment by molinch** [comment]
Many thanks !
Can you give me a path example? ie what you have inside: `data.Data.Path`

**Comment by vsarnataro** [comment]
`/external/images/media/625`

**Comment by molinch** [comment]
Could you upload a basic sample that demos this issue?
It should not be difficult to fix once we reproduce it.
