### ISSUE TITLE
Windows Phone CachedImage initialization exception

### ISSUE THREAD

**Issue by MarcorOnline** [luberda-molinet/FFImageLoading#212]
Hello.
I'm using your component, from NuGet, on Android, iOS and Windows Phone, with Xamarin Forms, but it doesn't works on Windows Phone (8.1 RT).

When I try to use the CachedImage (both via XAML or C#) I have this exception:

The type initializer for 'FFImageLoading.Forms.CachedImage' threw an exception.

"Could not load type 'FFImageLoading.Work.LoadingPriority' from assembly 'FFImageLoading, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.":"FFImageLoading.Work.LoadingPriority"

I've placed CachedImageRenderer.Init() in the App constructor.

Can you help me?

Best regards
Marco

**Comment by daniel-luberda** [comment]
@MarcorOnline Could you try if it would work without Init call? (Windows is the only platform which doesn't require it, method is empty on that platform)

**Comment by MarcorOnline** [comment]
@daniel-luberda thanks, I've removed the Init call and a new exception appeared:
"You are referencing the Portable version in your App - you need to reference the platform (iOS/Android) version"

I've removed the portable version from WP project, and now no more exception when I try to create a CachedImage, but no image appears. I can see only a white box.

I'm using this image for testing:
http://blog.iconosquare.com/wp-content/uploads/2014/08/ice-bucket-challenge-1940x1091.jpg

I've tryied both with and without Transformations.

Thanks for your support

**Comment by MarcorOnline** [comment]
@daniel-luberda Hello, sorry for the double post, do you think there's a solution to the problem?

Thank you

**Comment by daniel-luberda** [comment]
See this: https://github.com/luberda-molinet/FFImageLoading/issues/213

**Comment by MarcorOnline** [comment]
@daniel-luberda thanks for your support! The fix is uninstall/reinstall everygthings!

best regards
Marco

**Comment by daniel-luberda** [comment]
Nice to hear you solved it :)
