### ISSUE TITLE
App Crashed with class FFImageLoading.Views.ImageViewAsync could not be loaded exception

### ISSUE THREAD

**Issue by AlchemySolutionsPvtLtd** [luberda-molinet/FFImageLoading#213]
@daniel-luberda  @molinch 

Hi,
I tried to implement FFImage with Carousel Control. My app compiled successfully but as soon as I tried to run it, it crashed with the message : _**The class FFImageLoading.Views.ImageViewAsync could not be loaded, used in FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null**_
I have added the nuget packets : **FFImageLoading** and **FFImageLoading.Forms** in Cross Platform Project, **FFImageLoading.Platform**  got added along with FFImageLoading.Forms and 
**FFImageLoading**, **FFImageLoading.Forms** in Droid project.
Please let me know, what am I missing there.
Here is the stack trace/ output messages for the same: 

```
05-25 18:31:52.298 D/Mono    ( 4696): Assembly Ref addref FFImageLoading.Forms[0xb803ee10] -> System.Runtime[0xb806bf28]: 5
05-25 18:31:52.298 D/Mono    ( 4696): Assembly Ref addref FFImageLoading.Forms.Droid[0xb803fcf0] -> mscorlib[0xb7fcb350]: 27
05-25 18:31:52.298 D/Mono    ( 4696): Assembly Ref addref FFImageLoading.Forms.Droid[0xb803fcf0] -> Xamarin.Forms.Platform.Android[0xb804fef8]: 4
05-25 18:31:52.298 D/Mono    ( 4696): Assembly Ref addref FFImageLoading.Forms[0xb803ee10] -> Xamarin.Forms.Core[0xb804eeb0]: 6
05-25 18:31:52.298 D/Mono    ( 4696): Assembly Ref addref FFImageLoading.Forms.Droid[0xb803fcf0] -> FFImageLoading.Forms[0xb803ee10]: 2
05-25 18:31:52.298 D/Mono    ( 4696): Assembly Ref addref FFImageLoading.Forms.Droid[0xb803fcf0] -> FFImageLoading.Platform[0xb80815f0]: 2
05-25 18:31:52.298 W/Mono    ( 4696): The class FFImageLoading.Views.ImageViewAsync could not be loaded, used in FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
In mgmain JNI_OnLoad
05-25 18:31:52.298 W/Mono    ( 4696): The class FFImageLoading.Views.ImageViewAsync could not be loaded, used in FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
05-25 18:31:52.298 E/mono    ( 4696): Unhandled loader error: 7, (null) FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null FFImageLoading.Views.ImageViewAsync
05-25 18:31:52.298 F/        ( 4696): * Assertion: should not be reached at /Users/builder/data/lanes/3053/a94a03b5/source/mono/mono/metadata/loader.c:298
05-25 18:31:52.298 F/libc    ( 4696): Fatal signal 6 (SIGABRT) at 0x00001258 (code=-6), thread 4696 (DiosaApp.Droid)
```

>

**Comment by daniel-luberda** [comment]
@AlchemySolutionsPvtLtd 

- You must include `CachedImageRenderer.Init()` call in every platform specific project as stated here: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#important
- Are you sure all nuget packages installed successfully? You should have Xamarin.FFImageLoading and Xamarin.FFImageLoading.Forms in every project (shared and platform specific). Also please try to uninstall all packages and add them again (sometimes XS have some issues with packages)

**Comment by molinch** [comment]
@AlchemySolutionsPvtLtd Any news ?

**Comment by AlchemySolutionsPvtLtd** [comment]
@molinch  ya re-installing the packages resolved it... 
thanks a lot :)
