### ISSUE TITLE
Is it possible to use all transformations in Xaml?

### ISSUE THREAD

**Issue by ravensorb** [luberda-molinet/FFImageLoading#214]
I saw a sample for the grey scale transformation in xaml, however when I try to use others like CornersTransformation I get an error about "no default constructor found".  Am I missing something?

**Comment by daniel-luberda** [comment]
@ravensorb  Just use something like: 
```XML
<fftransformations:SomeTransformation>
    <x:Arguments>
      <x:String>
        stringConstructorValue
      </x:String>
    </x:Arguments>
</fftransformations:SomeTransformation>
```

or 

make a custom class which inherits from transformation: 

```C#
public class MyTransformation : SomeTransformation
{
  public MyTransformation() : base("someParameter")
  {
  }
}
```

then use it in XAML as: `<local:MyTransformation/>`

**Comment by ravensorb** [comment]
Ok, thanks -- that was were I was heading. If I have time, I might take a shot at the properties and do a PR this weekend :)

**Comment by daniel-luberda** [comment]
Sure, If you have something feel free to make a PR :)

**Comment by molinch** [comment]
If you submit a PR we will accept it with pleasure :)
