### ISSUE TITLE
Placeholder image double loads in latest build

### ISSUE THREAD

**Issue by ravensorb** [luberda-molinet/FFImageLoading#215]
I am using the following in an application (bellow is simplified)

```
<DataTemplate>
      <ViewCell>
                 <ffimageloading:CachedImage DownsampleToViewSize="true"
                          Error="ffimageloadingError"
                          ErrorPlaceholder="Assets/icons/Video-Default.png"
                          HeightRequest="150"
                          HorizontalOptions="Center"
                          LoadingPlaceholder="Assets/icons/Video-Loading.png"
                         Source="{Binding ThumbnailUrl}"
                         VerticalOptions="Center"
                         WidthRequest="{Binding Converter={StaticResource DeviceSizeConverter},
                         ConverterParameter=width}" />
      </ViewCell>
</DataTemplate>   
```

And I have noticed that the "LoadingPlaeholder" seems to load AFTER the control shows up on the screen, and then the image shows up, flickers, and loads again.  Then if the image cannot be displayed the "ErrorPlaceholder" does the same thing.  So it will sometimes happen that there are 4 "flickers" before rendering the new image.  The other thing that I have noticed is that in a DataBinding scenario there is a MASSIVE lag between individual CachedImages loading -- it almost seems like they are loading in sequence rather than in parallel.

Any thoughts?

Note: This is a Xamarin Forms app leveraging Xaml and targeting the Windows UWP platform (Windows 10 mobile emulator)

**Comment by molinch** [comment]
Are you using a placeholder from internet or a local one?

**Comment by ravensorb** [comment]
Local -- marked as "Content"

**Comment by molinch** [comment]
For the flickering I think @daniel-luberda should have a look at it.

@ravensorb We did a lot of improvements around performance & scheduler, these are only in https://github.com/luberda-molinet/FFImageLoading/tree/scheduler-changes branch currently.

I am not able to make a nuget package right now, would you be able to give it a try?

**Comment by molinch** [comment]
@ravensorb Could you give a try to our 2.1.1 prerelease package?

**Comment by ravensorb** [comment]
It is not as bad in this build however I am still seeing a double load (or at least a "flickering").  when there are multiple images on a screen.

**Comment by molinch** [comment]
The flickering happens on iOS or Android?
Also does it happen on real device only or you can reproduce with simulator?

> It is not as bad in this build 
Can you detail what you should be improved, in your opinion, apart from the flickering?

**Comment by molinch** [comment]
@ravensorb Even though I cannot exactly reproduce what you describe #236 should really improve this.
