### ISSUE TITLE
Old image is displayed before new one when scrolling

### ISSUE THREAD

**Issue by molinch** [luberda-molinet/FFImageLoading#216]
Scrolling a list shows old image then new one on iOS.
@michaeldimoudis reported in #206:
> scrolling in a ListView in iOS still shows wrong images briefly during the scrolling.

**Comment by molinch** [comment]
This one is tricky to tackle, we'll need to investigate.

**Comment by daniel-luberda** [comment]
It's related to how bindings are working on Xamarin.Forms. Solution here: 

- https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#usage-in-listview-with-listviewcachingstrategyrecycleelement-enabled
- https://developer.xamarin.com/guides/xamarin-forms/user-interface/listview/performance/#RecycleElement
- https://github.com/luberda-molinet/FFImageLoading/issues/200

**Comment by molinch** [comment]
I'm not 100% sure it is only that.
I think that I experienced it in a non XF app.
I will check, but consider it as a low priority for now.

**Comment by daniel-luberda** [comment]
On Forms it should be better after this: https://github.com/luberda-molinet/FFImageLoading/commit/423f4418cbf294602f4510a807cba61e236c1ba5 (Images are now set to null as soon as source changes, before image loading tasks, the same as in Forms `Image` lately)

**Comment by molinch** [comment]
@michaeldimoudis: do you still experience it with 2.1.1?

**Comment by michaeldimoudis** [comment]
Nop I haven't experienced this again in 2.1.1 👍🏼

**Comment by molinch** [comment]
Thanks !

**Comment by leenephi** [comment]
As of version 2.2.7 I am experiencing this same issue. 
I can confirm the normal forms Image type does not show the recycled image, but CachedImage shows the recycled image when I use both Xaml binding as well as the suggestion in the Wiki linked above.

**Comment by daniel-luberda** [comment]
@leenephi  Could you share your code which sets image source?

**Comment by leenephi** [comment]
Hey @daniel-luberda - thanks for the quick response!
Wanted to also mention that we're only running this on Android currently.    

    `public class PlayersPageViewCell : ViewCell
    {
        private CachedImage _avatarImage;

        public PlayersPageViewCell()
        {
            var absoluteLayout = new AbsoluteLayout();
            absoluteLayout.Padding = new Thickness(5);

            var ratingLabel = new Label();
            ratingLabel.SetBinding(Label.TextProperty, "Rating");

            _avatarImage = new CachedImage();
            _avatarImage.DownsampleToViewSize = true;
            _avatarImage.Aspect = Aspect.AspectFit;

            absoluteLayout.Children.Add(ratingLabel, new Rectangle(0, 0, .2, 1), AbsoluteLayoutFlags.SizeProportional);
            absoluteLayout.Children.Add(_avatarImage, new Rectangle(.25, 0, .2, 1), AbsoluteLayoutFlags.All);

            this.View = absoluteLayout;
        }

        protected override void OnBindingContextChanged()
        {
            var playersPageItem = BindingContext as PlayersPageItemViewModel;
            if (playersPageItem == null) return;

            _avatarImage.Source = playersPageItem.AvatarUrl;

            base.OnBindingContextChanged();
        }
    }`

**Comment by daniel-luberda** [comment]
@leenephi Your code looks good. 

Last versions have some optimisations, I made some tests and average image loading time dropped. It may be the reason old images are shown sometimes as it is assigned to a view before loading task is cancelled (via `OnBindingContextChanged` method when new image source is assigned). 

What might help (but I am not sure) is: 

```C#
    protected override void OnBindingContextChanged()
    {
        _avatarImage.Source = null;
        var playersPageItem = BindingContext as PlayersPageItemViewModel;
        if (playersPageItem == null) return;

        _avatarImage.Source = playersPageItem.AvatarUrl;

        base.OnBindingContextChanged();
    }
```

**Comment by leenephi** [comment]
Thanks @daniel-luberda 

Setting the source to null immediately before setting it to the new binding context item indeed works.

How exactly can I see the optimizations made in the pre-release or latest version? In general, I'm having very poor performance when only having 2 or 3 total CachedImages in my list view cell. They all pull from URLs, but even when scrolling back up with memory cache, the list view is dropping frames like crazy. I'm also still using an absolute layout as shown above with recycle caching strategy. Wondering if I'm gonna have to explore a custom renderer for the list cell...! :( haha

**Comment by daniel-luberda** [comment]
You can review all commits. If you replace `CachedImage` with eg. `BoxView`, do you still experience performance issues? Also please download our Xamarin.Forms sample (from repo), there are many ListView examples there. They're all quite fast, I didn't notice any lags. Or if you give me you `ViewCell` code, maybe I could help.

**Comment by leenephi** [comment]
@daniel-luberda Heyy. Replacing with box views has it scrolling smoothly/normally. With the three image views, I even notice that while loading from the memory cache (scrolling up from the bottom) the poor performance is the same. At first I thought it was just a Nexus 5 I was testing, but even the Nexus 6P stutters just as much.

Anyway! Let me get you some code. I'll add the XAML, View Cell, and the initialization in the MainActivity.

```
        <ContentPage.Content>
		<ListView x:Name="PlayersList"
				ItemsSource="{Binding Players}"
				SelectedItem="{Binding SelectedItem}"
				CachingStrategy="RecycleElement"
				HasUnevenRows="false"
				RowHeight="50">
			<ListView.ItemTemplate>
				<DataTemplate>
					<views:PlayersPageViewCell />
				</DataTemplate>
			</ListView.ItemTemplate>
		</ListView>
	</ContentPage.Content>


public class PlayersPageViewCell : ViewCell
    {
        private CachedImage _image1;
        private CachedImage _image2;
        private CachedImage _image3;

        public PlayersPageViewCell()
        {
            var absoluteLayout = new AbsoluteLayout();
            absoluteLayout.Padding = new Thickness(10, 5);

            //var boxView1 = new BoxView();
            //boxView1.Color = Color.Blue;
            //var boxView2 = new BoxView();
            //boxView2.Color = Color.Red;
            //var boxView3 = new BoxView();
            //boxView3.Color = Color.Purple;
            //var boxView4 = new BoxView();
            //boxView4.Color = Color.Black;

            var label = new Label();
            label.TextColor = Color.Black;
            label.VerticalTextAlignment = TextAlignment.Center;
            label.HorizontalTextAlignment = TextAlignment.Center;
            label.SetBinding(Label.TextProperty, "Rating");
            //ratingLabel.SetBinding(GradientLabel.GradientStartColorProperty, "RatingGradientStart");
            //ratingLabel.SetBinding(GradientLabel.GradientEndColorProperty, "RatingGradientEnd");

            _image1 = new CachedImage();
            _image1.HeightRequest = 45;
            _image1.DownsampleToViewSize = true;
            _image1.ErrorPlaceholder = ImageSource.FromFile("player_avatar_placeholder.png");

            _image2 = new CachedImage();
            _image2.HeightRequest = 22;
            _image2.DownsampleToViewSize = true;

            _image3 = new CachedImage();
            _image3.HeightRequest = 22;
            _image3.DownsampleToViewSize = true;

            absoluteLayout.Children.Add(label, new Rectangle(.05, .5, .085, .75), AbsoluteLayoutFlags.All);
            absoluteLayout.Children.Add(_image1, new Rectangle(.15, .5, .2, 1), AbsoluteLayoutFlags.All);
            absoluteLayout.Children.Add(_image2, new Rectangle(.4, 0, .15, .5), AbsoluteLayoutFlags.All);
            absoluteLayout.Children.Add(_image3, new Rectangle(.4, 1, .15, .5), AbsoluteLayoutFlags.All);

            //absoluteLayout.Children.Add(boxView1, new Rectangle(.05, .5, .085, .75), AbsoluteLayoutFlags.All);
            //absoluteLayout.Children.Add(boxView2, new Rectangle(.15, .5, .2, 1), AbsoluteLayoutFlags.All);
            //absoluteLayout.Children.Add(boxView3, new Rectangle(.4, 0, .15, .5), AbsoluteLayoutFlags.All);
            //absoluteLayout.Children.Add(boxView4, new Rectangle(.4, 1, .15, .5), AbsoluteLayoutFlags.All);

            this.View = absoluteLayout;
        }

        protected override void OnBindingContextChanged()
        {
            var playersPageItem = BindingContext as PlayersPageItemViewModel;
            if (playersPageItem == null) return;

            _image1.Source = null;
            _image1.Source = playersPageItem.Image1Url;

            _image2.Source = null;
            _image2.Source = playersPageItem.Image2Url;

            _image3.Source = null;
            _image3.Source = playersPageItem.Image3Url;

            base.OnBindingContextChanged();
        }
    }


            CachedImageRenderer.Init();
            ImageService.Instance.Initialize(new Configuration
            {
                VerboseLogging = true,
                VerbosePerformanceLogging = true,
                Logger = new ImageCacheLogger()
            });
```

**Comment by daniel-luberda** [comment]
Some comments:

```C#
            ImageService.Instance.Initialize(new Configuration
            {
                VerboseLogging = true, // this can hurt performance a lot as it's spamming console with a lot of data, please try to disable it
                VerbosePerformanceLogging = true, // this can hurt performance a lot as it's spamming console with a lot of data, please try to disable it
                Logger = new ImageCacheLogger()
            });
```


```C#          
 _image1.Source = null; // this can hurt performance as it can cause Forms layout cycle.
_image1.Source = playersPageItem.Image1Url;
```

BTW: Also read this: https://github.com/luberda-molinet/FFImageLoading/wiki/Native-Http-handlers-=-better-performance
