### ISSUE TITLE
FFImageLoading stops loading images

### ISSUE THREAD

**Issue by molinch** [luberda-molinet/FFImageLoading#218]
Reported by @michaeldimoudis in #206. It occured with 2.1.1 pre1.

> Sometimes on iOS images in a ListView refused to load, I did a hard close, reopened the app and the images downloaded again.

**Comment by owlstack** [comment]
Not sure if this is related but I got version 2.1.0 of FFImageLoading and I'm using Preload() method and the images are blank, they are not loaded. I debugged and the url is passed in but the images are not showing up.

**Comment by molinch** [comment]
@owlstack I'll check

**Comment by molinch** [comment]
@michaeldimoudis unfortunately I couldn't reproduce it.
By any chance do you know a scenario? Or have extra infos?

**Comment by michaeldimoudis** [comment]
It was on a fresh app reinstall when updated to pre where it had to download a lot of images again and got stuck. I only experienced it once. You can close if you want, if it happens again I can open a new issue?

**Comment by molinch** [comment]
Thanks for the quick feedback!
It's fine, let's keep it open for a few more days, maybe you will reproduce it (or maybe not hopefully!).

**Comment by molinch** [comment]
Fixed in git, a new prerelease will be delivered soon.

**Comment by michaeldimoudis** [comment]
Great thanks for that, much appreciated all the work you guys are doing.

**Comment by daniel-luberda** [comment]
FFImageLoading 2.1.1 nuget released.
