### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by molinch** [luberda-molinet/FFImageLoading#219]
Now that we have AppVeyor CI integration (thanks again @mattleibow 👍 ) we can write some units tests that will automatically run.

Things that can be tested:
- WorkScheduler
- SimpleDiskCache
- DownloadCache

There may be some open issues with xUnit2 and AppVeyor: http://help.appveyor.com/discussions/problems/677-xunit-20-support

**Comment by molinch** [comment]
Started in 610a05700b5678177ef7c91e93d0bd6cae5c70cb

**Comment by molinch** [comment]
@daniel-luberda would be nice if you can configure AppVeyor and add the badge on homepage!

**Comment by molinch** [comment]
Continue in https://github.com/luberda-molinet/FFImageLoading/commit/5cdbcac00d84e086626058b3a2c1e244f968b572

**Comment by daniel-luberda** [comment]
@molinch It's working :) https://ci.appveyor.com/project/daniel-luberda/ffimageloading/build/tests

**Comment by molinch** [comment]
Thanks @daniel-luberda !

**Comment by molinch** [comment]
@daniel-luberda One test fails, see https://ci.appveyor.com/project/daniel-luberda/ffimageloading/build/tests

Right now GenericPriorityQueue is not enumerating by priority. Is it correct?
My test assumes the opposite, which would make sense since first is the highest priority.

**Comment by daniel-luberda** [comment]
@molinch Yes, it's by design. Only `Dequeue` method guarantees this :)

**Comment by molinch** [comment]
Thanks!

**Comment by daniel-luberda** [comment]
Currently, I've added mock platform implementation, which can be enabled by setting: `EnableMockImageService = true` and also added some basic unit tests here: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/Tests/FFImageLoading.Tests/ImageService/ImageServiceBaseTests.cs

Feel free to add more.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/861
