### ISSUE TITLE
Preloaded images do not show up in view cells until after a considerable time 

### ISSUE THREAD

**Issue by owlstack** [luberda-molinet/FFImageLoading#221]
When preloading images, the images do not get preloaded/shown in the view cells until after a considerable time. I was wondering why there is this delay and if anyone else is getting it?

**Comment by owlstack** [comment]
Sorry, it was related to something else. Closing this issue.

**Comment by zjxeditor** [comment]
Hi, how do you solve the problem? I come up to the same problem.
