### ISSUE TITLE
FFImageLoading picking wrong image scale for app resources

### ISSUE THREAD

**Issue by marlonconstante** [luberda-molinet/FFImageLoading#222]
Xamarin.FFImageLoading.Forms: Invalid height and width for images with no fixed size in iOS.

Problem is occurring in the latest release: **_2.1.0_**.
In version **_2.0.6_** it worked perfectly on both platforms (iOS and Android).
Currently the expected result is presented only on Android, but not on iOS.

I believe the correct behavior in this case is to show the image with original size, as previously.

The following screen print comparing versions for better understanding:

![screen](https://cloud.githubusercontent.com/assets/6370612/15747592/ca97f93c-28b1-11e6-9395-9423a601971a.png)

**Comment by molinch** [comment]
@marlonconstante So you use Xamarin Forms, you don't have a size defined, before it worked as expected and now the size is incorrect, am I right?

@daniel-luberda Any idea?

**Comment by marlonconstante** [comment]
@molinch @daniel-luberda Right, that's it.

**The following example of a code snippet:**
```
new Frame {
	WidthRequest = 200d,
	HeightRequest = 200d,
	Content = new CachedImage {
		HorizontalOptions = LayoutOptions.Center,
		VerticalOptions = LayoutOptions.Center,
		FadeAnimationEnabled = true,
		TransparencyEnabled = false,
		CacheDuration = TimeSpan.FromDays(5d),
		Source = "Image.png"
	}
}
```
In this case above, in version _2.1.0_, the image will be of same size defined in frame,
even if it is smaller than that.

The expected here would center the image in frame respecting its original size as it was in version _2.0.6_.

**Comment by daniel-luberda** [comment]
@marlonconstante Xamarin.Forms only supports 3 types of aspect ratio: 

```C#
	public enum Aspect
	{
		AspectFit, // Fits the container (without cutting) maintaining aspect ratio
		AspectFill, // Fills the container (with cutting) maintaining aspect ratio
		Fill, // Fills the container (without cutting) not maintaining aspect ratio
	}
```

You're forcing the size of image to be **200d x 200d**, so it's a correct behavior. I don't think we changed anything related to aspect ratio, it's rather a Xamarin.Forms renderer change.

**Comment by daniel-luberda** [comment]
After giving it a second thought. @molinch Could it be related to iOS picking up the wrong scale?

**Comment by marlonconstante** [comment]
@molinch @daniel-luberda The following is a practical example to demonstrate the problem.
I also added a native image for comparison purposes (Both are included within the same context).

**Code:**
```c#
public class App : Application
{
	public App()
	{
		MainPage = new ContentPage {
			Content = new StackLayout {
				HorizontalOptions = LayoutOptions.Center,
				VerticalOptions = LayoutOptions.Center,
				Orientation = StackOrientation.Horizontal,
				Children = {
					new ContentView {
						WidthRequest = 150d,
						HeightRequest = 150d,
						BackgroundColor = Color.Lime,
						Content = new StackLayout {
							HorizontalOptions = LayoutOptions.Center,
							VerticalOptions = LayoutOptions.Center,
							Children = {
								new Image {
									Source = "FidelityCard.png"
								},
								new Label {
									Text = "Xamarin.Forms\nImage (2.2.0)",
									HorizontalTextAlignment = TextAlignment.Center,
									FontSize = 12d
								}
							}
						}
					},
					new ContentView {
						WidthRequest = 150d,
						HeightRequest = 150d,
						BackgroundColor = Color.Yellow,
						Content = new StackLayout {
							HorizontalOptions = LayoutOptions.Center,
							VerticalOptions = LayoutOptions.Center,
							Children = {
								new CachedImage {
									Source = "FidelityCard.png"
								},
								new Label {
									Text = "FFImageLoading.Forms\nCachedImage (2.1.1)",
									HorizontalTextAlignment = TextAlignment.Center,
									FontSize = 12d
								}
							}
						}
					}
				}
			}
		};
	}
}
```
**Preview:**
![images](https://cloud.githubusercontent.com/assets/6370612/15796699/9ab9df86-29d9-11e6-8de6-97f2b25e2c30.png)

**Comment by molinch** [comment]
Many thanks @marlonconstante with your feedback it's now crystal clear.
I will look into it ASAP.

**Comment by molinch** [comment]
Very weird I just reproduced what you did, and I get the expected result with 2.1.1.

These are the images I used (@3x, @2x and normal):
![fidelitycard 3x](https://cloud.githubusercontent.com/assets/5130190/15801929/651760f8-2aa4-11e6-88cf-a13efbba412b.png)
![fidelitycard 2x](https://cloud.githubusercontent.com/assets/5130190/15801930/6519b4e8-2aa4-11e6-938e-ec7cd0574288.png)
![fidelitycard](https://cloud.githubusercontent.com/assets/5130190/15801931/651af7a4-2aa4-11e6-8c09-5937fdc3e343.png)

And this is the result I have:
![image](https://cloud.githubusercontent.com/assets/5130190/15801945/d960182e-2aa4-11e6-935c-dcb2c359a924.png)

If you reproduce with 2.1.1 could you upload a sample?
Also could you indicate which Xamarin Forms you use?

**Comment by molinch** [comment]
The result is bit strange. On the left iOS, on the right Android.
Any idea @daniel-luberda ?

![image](https://cloud.githubusercontent.com/assets/5130190/15802248/6d5bb3f6-2aac-11e6-860c-562209944c98.png)

**Comment by molinch** [comment]
Remark, even when explicitely defining size, ie:
```c#
new CachedImage {
   Source = "fidelitycard.png",
   WidthRequest = 70d,
   HeightRequest = 70d,
}
```

We observe at small difference:
![image](https://cloud.githubusercontent.com/assets/5130190/15805337/3b21bc66-2b27-11e6-99cf-69d82c20dabe.png)

**Comment by molinch** [comment]
This prerelease nuget package contains the fix https://www.nuget.org/packages/Xamarin.FFImageLoading/2.1.4-pre-85
could you give it a try ?

**Comment by marlonconstante** [comment]
@molinch @daniel-luberda Worked perfectly!
Thanks for attention and quickness to resolve this issue.

**Comment by marlonconstante** [comment]
@molinch @daniel-luberda Problem back in version 2.2.0.
Can check?

**Comment by daniel-luberda** [comment]
Yes, it should be fixed soon, more here: https://github.com/luberda-molinet/FFImageLoading/issues/349
