### ISSUE TITLE
ImageService.Instance.Initialize(config) doesn't work

### ISSUE THREAD

**Issue by Slava8991** [luberda-molinet/FFImageLoading#223]
Thank for great project first!

We try to change the default configuration but changes doesn't apply any way.

Xamarin.FFImageLoading.Forms.2.1.0-rc1

Our project is XF 2.1 for Android.

We tried to place ImageService.Instance.Initialize before and after CachedImageRenderer.Init() without any effect.

Full code (from MainActivity.cs)

`base.OnCreate(bundle);`
            `FFImageLoading.Forms.Droid.CachedImageRenderer.Init();`
                `var config = new Configuration`
                `{`
                    `HttpClient = new HttpClient(new ModernHttpClient.NativeMessageHandler()),`
                    `DelayInMs = 500,`
                    `DownsampleInterpolationMode = InterpolationMode.High,`
                    `FadeAnimationForCachedImages = false,`
                    `FadeAnimationDuration = 250,`
                    `FadeAnimationEnabled = false`
               ` };`
                `FFImageLoading.ImageService.Instance.Initialize(config);`

**Comment by daniel-luberda** [comment]
@Slava8991 Hi, could you give more details? What are the signs that custom config doesn't work? Did yo try to uninstall all nuget packages and install them again in all projects (shared + platform specific)? Thanks.

**Comment by Slava8991** [comment]
@daniel-luberda We don't see any behavior changes after custom Initialize. Also we checked ImageService.Instance.Config property before and after initialize - no changes. We also commented FFImageLoading.Forms.Droid.CachedImageRenderer.Init(); and app started and worked fine. It seems like FFImageLoading initialize itself before manual init.

We didn't try to re-install FFImageLoading packages. Will try it. Thank!

**Comment by Slava8991** [comment]
After re-installing package we are able to change configuration that way:

FFImageLoading.ImageService.Instance.Config.FadeAnimationDuration = 250;

But Initialize() still don't work.

**Comment by daniel-luberda** [comment]
There was a bug, I fixed it. Thanks for a help! :) Nugets coming soon.

**Comment by daniel-luberda** [comment]
FFImageLoading 2.1.1 nuget released.
