### ISSUE TITLE
Don't show placeholder for cached images

### ISSUE THREAD

**Issue by Slava8991** [luberda-molinet/FFImageLoading#224]
Is it possible to implement any config option to withdraw loading placeholder for cached images? We want cached images should be visible as soon as possible without any animations and currently there are some flickering between placeholder and cached image.

**Comment by molinch** [comment]
That's done in 2.1.1 unfortunately it's a prerelease only, so not stable yet.

**Comment by Slava8991** [comment]
Great! Waiting for stable release! Thank you!

**Comment by daniel-luberda** [comment]
FFImageLoading 2.1.1 nuget released.
