### ISSUE TITLE
Setting a cached image source from Uri not working 2.1.1

### ISSUE THREAD

**Issue by joelsantos** [luberda-molinet/FFImageLoading#227]
Hi there.

There seems to be an issue when trying to set a CachedImage source from an Uri on version 2.1.1. No image appears. 

If I try to load using any of the other methods it works, however setting the source to an URL through code or XAML directly fails.

Reverted to 2.1.0 and it's working.

Any ideas on what might be happening?

Kind regards and keep up the good work.

**Comment by molinch** [comment]
@daniel-luberda Any idea? Sounds strange to me since I don't expect changes here

**Comment by daniel-luberda** [comment]
I don't expect it either.  Could you give me your code?

**Comment by joelsantos** [comment]
Hi there.
Just tested and confirmed on an empty project. Created a new repository for it as well.

I can confirm that the issue is happening on all Windows platforms.
Please check https://github.com/joelsantos/TestFFImage/blob/master/TestFFImage/TestFFImage/App.cs

Here's a picture of the issue https://onedrive.live.com/redir?resid=A69DDA9C53B62B67!888341&authkey=!AKSG29rRApTQ0IY&v=3&ithint=photo%2cpng

Now that I think about it.. I am not sure it works with 2.1.0 either. Let me check again and I'll let you know.

Cheers,
Joel

**Comment by molinch** [comment]
@joelsantos It works fine. The issue is that you don't call the init method in your platform projects:
```c#
CachedImageRenderer.Init();
````
See: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#important

**Comment by joelsantos** [comment]
@molinch Sorry I forgot to add that to this sample project, but I was doing that on my original project.

I added   CachedImageRenderer.Init(); to the multiple Windows projects and it still doesn't work.

I am doing it on App.xaml.cs, after Xamarin.Forms.Forms.Init(e); (were we are usually advised to do it), however it is still not working. I tried moving the initialization around, but I still don't see any pictures.

You couldn't repro the issue?

**Comment by molinch** [comment]
@daniel-luberda I cannot test on WP but on iOS/Android I confirm that everything works as expected.
Could you give it a try?

**Comment by daniel-luberda** [comment]
@joelsantos There was a bug in all windows releases. I'm currently fixing it. Thanks!

**Comment by joelsantos** [comment]
Thank you @daniel-luberda :+1:  glad I could help

**Comment by daniel-luberda** [comment]
Hi @joelsantos , it's already fixed. Just download 2.1.2 nuget.

**Comment by joelsantos** [comment]
I can now confirm that the issue is solved. Thank's once again :+1:
