### ISSUE TITLE
FF2.1.2 Crash

### ISSUE THREAD

**Issue by patook** [luberda-molinet/FFImageLoading#232]
Stack trace below, relative rare.

System.Collections.Generic.KeyNotFoundExceptionThe given key was not present in the dictionary.
Raw
null
System.Collections.Generic.KeyNotFoundExceptionThe given key was not present in the dictionary.
System.ThrowHelper.ThrowKeyNotFoundException()
System.Collections.Generic.Dictionary<TKey, TValue>.get_Item(TKey key)
FFImageLoading.Work.WorkScheduler.<QueueTaskAsync>d__32.MoveNext()
FFImageLoading.Work.WorkScheduler.<QueueTaskAsync>d__32.MoveNext()

**Comment by patook** [comment]
Thanks, that was fast. Any chance you can get Nugets up with that fix? I'd like to push a fix to the app store

**Comment by daniel-luberda** [comment]
You can use our packages from AppVeyor which are build for every commit: https://ci.appveyor.com/project/molinch/ffimageloading/build/artifacts

**Comment by patook** [comment]
Thank you - will do.

**Comment by tobiasschulz** [comment]
Can you please upload a public nuget?

Why are there so many dictionary problems lately...

**Comment by daniel-luberda** [comment]
It's because work scheduler was completely reimplemented, sorry for that. 2.1.3 released.

**Comment by patook** [comment]
@daniel-luberda I pushed out 2.1.3 and it is still happening


  at System.ThrowHelper.ThrowKeyNotFoundException () <0x9c3e8000 + 0x00010> in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (System.Collections.Generic.TKey key) <0x9f8a4a70 + 0x00053> in <filename unknown>:0 
  at FFImageLoading.Work.WorkScheduler+<QueueTaskAsync>d__32.MoveNext () <0x9c3e0578 + 0x003cf> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9c94b578 + 0x00024> in <filename unknown>:0 
  at FFImageLoading.Work.WorkScheduler+<QueueTaskAsync>d__32.MoveNext () <0x9c3e0578 + 0x0128b> in <filename unknown>:0

**Comment by patook** [comment]
It won't let me re-open this issue. But same as above with FF2.1.3

**Comment by daniel-luberda** [comment]
@patook 2.1.3 is now in official nuget channel. Did you try it? Did you clean project and rebuild it?

**Comment by patook** [comment]
@daniel-luberda 
The one I have on the app store is from AppVeyor (the link you sent me). Right clicking on it shows 2.1.3 version. However, if there are other changes between that time and the official FF2.1.3 then I can push those out as well. Let me know and I'll submit it.

**Comment by daniel-luberda** [comment]
If the version is exactly 2.1.3 it should be the same.

**Comment by daniel-luberda** [comment]
@patook  Could you try the newest nuget? It's building now (2.1.4.83).

**Comment by patook** [comment]
Yes, I will push it to the app store today.
