### ISSUE TITLE
2.1.2 Occasionaly pictures stop loading till app restart

### ISSUE THREAD

**Issue by highplains** [luberda-molinet/FFImageLoading#233]
Video Demo....

https://www.dropbox.com/s/02ajku5ss7f5qcc/ff212noload.mov?dl=0

PS. I know those images are already cached because they were working fine 5 min ago.

**Comment by daniel-luberda** [comment]
Did you try 2.1.3? There was a missed dictionary lock issue

**Comment by highplains** [comment]
Still happening in 2.1.3

**Comment by daniel-luberda** [comment]
@highplains Could you try the newest nuget? It's building now (2.1.4.83).

**Comment by highplains** [comment]
Testing now, ill get back to you.

**Comment by highplains** [comment]
Still happening.

**Comment by molinch** [comment]
@highplains Unfortunately I cannot reproduce with our samples.
Is it possible to share your sources via private email? Or to customize the samples so they are closer to your situation?

**Comment by molinch** [comment]
@highplains I managed to reproduce the issue.
It should be fixed now and I uploaded new prerelease nugets https://www.nuget.org/packages/Xamarin.FFImageLoading/2.1.4-pre-85

**Comment by molinch** [comment]
@highplains any feedback?

**Comment by highplains** [comment]
So far this looks good. I'll reopen if I notice it again.

**Comment by molinch** [comment]
Great !
Thanks for the feedback

**Comment by molinch** [comment]
Stable nuget 2.1.5, that contains the fix has been released.
