### ISSUE TITLE
2.1.3 IsLoading remains true after image is finished loading

### ISSUE THREAD

**Issue by highplains** [luberda-molinet/FFImageLoading#234]
https://www.dropbox.com/s/z3nezj7igddew1t/ff213loading.mov?dl=0

**Comment by molinch** [comment]
Thanks for the feedback! It is really nice to have videos.

Does it happen for all images?
Could you check it with our latest prerelease too?

**Comment by owlstack** [comment]
@highplains is this still true with the prerelease?

**Comment by molinch** [comment]
So @highplains ?

**Comment by highplains** [comment]
Trying to push a release. I'll check it out real quick

**Comment by highplains** [comment]
2.1.4-pre-85 looking good so far. Going to my TestFlight beta testers tonight.

**Comment by molinch** [comment]
I'm closing it, please reopen if needed.

**Comment by highplains** [comment]
This still happens occasionally.

**Comment by molinch** [comment]
@daniel-luberda I have no idea how the XF IsLoading is implemented. Do you have any idea?

**Comment by molinch** [comment]
Fix available in https://www.nuget.org/packages/Xamarin.FFImageLoading/2.1.6-pre-96
