### ISSUE TITLE
Not Bug - Preload

### ISSUE THREAD

**Issue by highplains** [luberda-molinet/FFImageLoading#235]
Is there an example of how to do this in forms? I see the property but am a bit confused on how to use it. Thanks!

**Comment by molinch** [comment]
@highplains 
From anywhere you can call:
```c#
ImageService.Instance.LoadUrl(urlToImage).Preload();
```

**Comment by highplains** [comment]
<img width="478" alt="screen shot 2016-06-08 at 2 01 39 pm" src="https://cloud.githubusercontent.com/assets/1825076/15909003/9f90387e-2d81-11e6-9192-7d77d53ed689.png">

**Comment by molinch** [comment]
It's an extension method see: https://github.com/luberda-molinet/FFImageLoading/blob/017541135eba42fee001b11016556231e8524772/source/FFImageLoading.Droid/TaskParameterExtensions.cs#L73

Do you have the usings?

**Comment by highplains** [comment]
Ya trying from a PCL.

**Comment by molinch** [comment]
I'll add a method using Bait & Switch, so you'll be able to do that in a PCL.

**Comment by highplains** [comment]
appreciate it!

**Comment by molinch** [comment]
Nuget 2.1.5 released which contains it.

**Comment by molinch** [comment]
Please let me know if you tried it.
Thanks !

**Comment by highplains** [comment]
Does preload ignore downloading the file if its already cached?

**Comment by molinch** [comment]
Yes. If it's already there it should not download it again.
Also note that it will put it in memory cache.

**Comment by highplains** [comment]
Nice, anyway in a future release to be able to select disk cache?

**Comment by highplains** [comment]
Also this seems to block.

Example.
Api call downloads 50 profiles with images to display in list.
Preload() is called on each pic to speed up load times when scrolling the list.
The first few cells that are displayed, the loading of the image is "blocked" while the preloads are happening in the background.

This sound correct? Perhaps a priority switch is needed?

**Comment by molinch** [comment]
Yes that is how it behaves now.

But you are right: the default priority, for preloaded tasks should probably be lowered.
Meanwhile you can still increase the priority of other tasks.

**Comment by highplains** [comment]
Changing images to high priority and letting preload run at normal priority did the trick. Would be nice if we could set the default to lower on preload.

Preload is awesome! Thanks!

**Comment by molinch** [comment]
I just checked the code, in fact you can already do it like:
```c#
ImageService.Instance.LoadUrl(urlToImage)
.Priority(LoadingPriority.Low)
.Preload();
```

I already pushed a change https://github.com/luberda-molinet/FFImageLoading/commit/66857b1793cc56ad42ee136d95bc81f82844c945 so in the future if no priority is defined it will be low by default.

**Comment by molinch** [comment]
Available in https://www.nuget.org/packages/Xamarin.FFImageLoading/2.1.6-pre-96

**Comment by highplains** [comment]
Thanks! Another question... Is there a way to clear the preload queue?

Scenario:
1. Api call downloads 50 records. Preload is called on the 50 records image.
2. User switches screens in app, preload queue still working on previous screens images.
3. Wipe preload queue
4. Api call on new screen
5. Preload called on new screens images.

**Comment by molinch** [comment]
Now there is in solution for your use case in prerelease nuget: https://www.nuget.org/packages/Xamarin.FFImageLoading/2.1.6-pre-102

You can cancel tasks using a predicate
`ImageService.Instance.Cancel(t => t.Preloaded)`

**Comment by highplains** [comment]
I can see the "Cancel" method but don't really understand how to pass "Preloaded" all I see is "Completed"

**Comment by ManhDucIT** [comment]
Dear @molinch ,

I have a specific case is for all times, the image must be displayed immediately even the first time. So I tried using:

// In this example urlToImage will be added to cache without being assigned to any target.
ImageService.Instance.LoadFile([PATH_TO_IMAGE]).Preload();

But it still slowly appear on the first time. The image I used has 6MB in size and ran in low performance device.

Could you please give me a detail sample code for this case so that I can resolve my issue as soon as possible?
