### ISSUE TITLE
Display loading placeholder straight away if in cache

### ISSUE THREAD

**Issue by molinch** [luberda-molinet/FFImageLoading#236]
If the placeholder is in cache it should be delivered straight away on UI thread.
There is no need to wait for anything in that case.

Remark: this is already done for images but not for the loading placeholder itself.

**Comment by molinch** [comment]
@daniel-luberda Why have you closed it? It's an enhancement not a bug

**Comment by daniel-luberda** [comment]
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Work/ImageLoaderTask.cs#L549
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Touch/Work/ImageLoaderTask.cs#L411
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Windows/Work/ImageLoaderTask.cs#L412
