### ISSUE TITLE
CachedImage in ListView items sometimes don't appear

### ISSUE THREAD

**Issue by stefffdev** [luberda-molinet/FFImageLoading#238]
I am encountering a caching issue in a (super simple) Xamarin.Forms UWP app.
I am navigating to a page containing only one XAML element:
`<ffimageloading:CachedImage x:Name="img"/>`

In the OnNavigatedTo event I am loading a Image resided in my LocalState path:
```
protected override void OnAppearing()
{
	base.OnAppearing();

        var basePath = FileSystem.Current.LocalStorage.Path;
        img.Source = Path.Combine(basePath, "test.jpg");
}
```

This is working fine the first time (when the file is loaded from the disk) but randomly failing every time the page is navigated to another time - the "success" event is raised, but the image is not displayed.
Trying a few more times makes the image appear again, but I can't find any pattern when the loading fails.

When I clear the cache before I load the image this problem doesn't occur:
`ImageService.Instance.InvalidateCacheAsync(FFImageLoading.Cache.CacheType.All);`

**Comment by molinch** [comment]
Thanks for the feedback.
Could you please try with the latest prerelease nuget?

**Comment by stefffdev** [comment]
Thank you for your response!
I tried with the version 2.1.4-pre85, the problem persists.

**Comment by molinch** [comment]
Thanks for the feedback.
Could you upload a sample so we look at it?

**Comment by stefffdev** [comment]
Sample Project: https://comtechit-my.sharepoint.com/personal/ss_comtech_at/_layouts/15/guestaccess.aspx?guestaccesstoken=3miBmAc66ls4LeO1%2fa%2f%2bQeN2TyxbTznjFVh9SuoiiOk%3d&docid=1766d9f1f34e04ce4bd07cd2f8e51b4aa

You'll need a "test.jpg" file in the LocalState directory, so please put it there manually after you first launched the app.
I have noticed that the problem only seems to occur when the CachedImage is inside a StackLayout, sorry I forgot to mention this in my initial post.

**Comment by molinch** [comment]
@stefffdev Many thanks for the sample, it's highly appreciated!

@daniel-luberda Could you have a look at it? I cannot play with WP unfortunately :(

**Comment by daniel-luberda** [comment]
I'll look at it by the weekend.

**Comment by daniel-luberda** [comment]
It's because of this: https://bugzilla.xamarin.com/show_bug.cgi?id=41087

As you see that method is not available in current stable Xamarin.Forms for Windows. If I include it, it will make Windows package not compatible with older Xamarin.Forms versions.

**Comment by daniel-luberda** [comment]
I fixed it with a hack. Good news it works for older (stable) Forms versions. Bad news, it uses reflection, but it's not called very often, so performance hit is not important. Nugets soon. That was a tricky one.

**Comment by daniel-luberda** [comment]
Prerelease NuGet package containing the fix released. Could you test it?

**Comment by stefffdev** [comment]
With the current prerelease nuget everything works as expected.
Good Job!
