### ISSUE TITLE
Issue on iOS with Xamarin Forms

### ISSUE THREAD

**Issue by scub4r** [luberda-molinet/FFImageLoading#241]
Im encountering an issue with FFImageLoading and iOS.
Xamarin Forms Version: 2.2.0.45
FFImageLoading Version: 2.1.5

> The type or namespace name 'Touch' does not exist in the namespace 'FFImageLoading.Forms'

AppDelegate.cs:

```
public override bool FinishedLaunching (UIApplication app, NSDictionary options)
		{
                        FFImageLoading.Forms.Touch.CachedImageRenderer.Init();
                        Forms.Init ();
			LoadApplication (new App ());
			ImageCircleRenderer.Init();

			return base.FinishedLaunching (app, options);
		}
```

I have added FFImageLoading to both iOS and Android projects.

The Android project recognizes the FFImageLoading.Forms.Droid namespace

**Comment by molinch** [comment]
@scub4r Could you try to uninstall all FFImageloading nuget packages from the iOS project.
Then try to install again FFImageLoading Forms.

**Comment by scub4r** [comment]
This solved it, thank you
