### ISSUE TITLE
Image from file not loading fast enough on first time

### ISSUE THREAD

**Issue by asafHorvitz** [luberda-molinet/FFImageLoading#242]
I have image from file i want to use as background.

I am using relative layout,  and i strech the image  all over the screen (the first child) and later i add some labels and entries to the relative layout.

The first time I loads it (using the cacheImage) a black screen appears with the labels and the entries presented and after around 1 second the image appears.

The second time I loads the screen the image is presented immediately - I guess the image is already in the cache.

How do I load the image to the cache in the first time ?

**Comment by molinch** [comment]
The first time your image is retrieved from disk and added to memory cache.
The time you see is the time to load from disk or to decode your image, it is independant from the library.

If you want to preload the image into memory cache you can use:
```c#
ImageService.Instance.LoadUrl(urlToImage).Preload();
```
However I doubt it will really help your scenario.
