### ISSUE TITLE
Occasionally an already loaded image goes through HttpClient to load again

### ISSUE THREAD

**Issue by michaeldimoudis** [luberda-molinet/FFImageLoading#243]
Hi, firstly thanks for 2.1.5 it has sped up things a lot.

I have an issue to report I've noticed before but haven't tried to find out what's going on yet. Basically this is the scenario, and note it doesn't happen all the time.

1. Images are loaded in a ListView (Xamarin Forms app here, testing on iOS atm) 
2. When I click an item in the ListView, that same image is shown on the next page (detail page).
3. Occasionally a HTTP hit is requested to load that already downloaded image again. If I have lots of images in the ListView still loading images (or another network call is happening), there is no network thread immediately available to show that image (which is already downloaded, but sometimes FFImageLoading hits the HttpClient again).
4. When there is a free network thread, the image loads up, or if I go back to the ListView and then back to the detail page.

Reason I noticed a network call is sometimes (not always) made on an already downloaded image, is because authentication is needed to download my images, and I was debugging some auth stuff in my custom HttpClient, and watched this happen.

Thanks

**Comment by molinch** [comment]
Awesome debugging info @michaeldimoudis 👍 
We will look into it

**Comment by daniel-luberda** [comment]
I'll close this one as here https://github.com/luberda-molinet/FFImageLoading/issues/326 are more details for the same issue.
