### ISSUE TITLE
Images are not loaded in RecyclerView

### ISSUE THREAD

**Issue by chamamo** [luberda-molinet/FFImageLoading#244]
Hello,

I am using the latest version (2.1.5) and I have problem when I have images in RecyclerView.

The images are not loaded the first time, I must scroll and return to the concerned images to see them load.

I did not have this problem when I was using the version 2.1.0

Thank you in advance.

**Comment by molinch** [comment]
We also have a sample with RecyclerView and it works fine: https://github.com/luberda-molinet/FFImageLoading/tree/master/samples/ImageLoading.Sample

Do you have more information to communicate? Could you upload or email your project so we have a look at it?

**Comment by chamamo** [comment]
I thank it happen when I have a nul (or empty) url in the list, I think It affect the rest.

**Comment by daniel-luberda** [comment]
@chamamo Could you write more details?
