### ISSUE TITLE
iOS System.IO.FileNotFoundException: Could not load file or assembly 'FFImageLoading.Transformations' or one of its dependencies

### ISSUE THREAD

**Issue by snaderi** [luberda-molinet/FFImageLoading#245]
Very similar to issue #170 except I'm calling the init in AppDelegate.cs.

`	[Register ("AppDelegate")]
	public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
	{
		public override bool FinishedLaunching (UIApplication app, NSDictionary options)
		{
			CachedImageRenderer.Init ();
			
			global::Xamarin.Forms.Forms.Init ();

			Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init ();

			LoadApplication (new App ());

			return base.FinishedLaunching (app, options);
		}
	}`

<img width="525" alt="screen shot 2016-06-13 at 12 52 36 pm" src="https://cloud.githubusercontent.com/assets/8563481/16021641/a3462bdc-3168-11e6-91df-a8cec3fc78b6.png">

![screen shot 2016-06-13 at 1 34 21 pm](https://cloud.githubusercontent.com/assets/8563481/16022473/e8896610-316c-11e6-9b13-01837d39a3e0.png)

I've tried to uninstall and re-install all FFImageLoading packages and dependencies (because I saw it suggested elsewhere) from the common project and iOS project but didn't help.

**Comment by molinch** [comment]
Any idea @daniel-luberda ?

**Comment by tomcrusader** [comment]
I have exactly this error, which of course is a major blocker

**Comment by daniel-luberda** [comment]
@tomcrusader @snaderi 
- Do you have FFImageLoading.Transformations added to both shared and platform specific projects? 
- If yes, it's Xamarin Linking problem, the assembly is cut out by the linker. To avoid that, you can add this  just after  `CachedImageRenderer.Init();` in a **platform specific project** (important):

```C#
var ignore = new CircleTransformation();
```

**Comment by snaderi** [comment]
@daniel-luberda That resolved it. Thank you.

**Comment by tomcrusader** [comment]
Might want to remark this in the documentation

**Comment by nicolabeghin** [comment]
I solved by adding a reference to missing type before `LoadApplication`
```csharp
// workaround for iOS compilation
// @url  https://github.com/UXDivers/Grial-UI-Kit-Support/issues/52#issuecomment-230461937
var workaround = typeof(CustomControls.ExtendedPicker);

```
as in https://github.com/UXDivers/Grial-UI-Kit-Support/issues/52
