### ISSUE TITLE
Upsampling/show image larger than image size?

### ISSUE THREAD

**Issue by WillemMali** [luberda-molinet/FFImageLoading#250]
Hi,

I'm working on a Xamarin.Forms app, and I think I've walked into an issue with ffImageLoading:

Whenever a CachedImage is set to be scaled up (with Width/HeightRequest or Vertical/HorizontalOptions="Fill"), it does take up the amount of space a Xamarin Image would, but draws the image in the top-left corner of the region of space it occupies, at the size of its source.

I.e., when I have a high resolution screen and a low resolution header image, I can't make the header scale up to fill the entire page width.

Am I doing something wrong myself? Is this a known issue/non-feature? Can I help fix this issue somehow?

I really like this library, but this is making it impossible to use in all situations (I don't always control the images I display, sometimes they're fetched from the web, and then I have to make do with whatever resolution image I receive).

I'm at work and on a tight schedule so sadly I can't make and submit a minimal sample right now :(

**Comment by daniel-luberda** [comment]
Vertical/HorizontalOptions="Fill" will give you original image size, so it's an expected behavior. What you're looking for is
- `FillAndExpand` OR
- `WidthRequest / HeightRequest` (setting one of those is enough)

**Comment by WillemMali** [comment]
No, in Xamarin.Forms "Fill" will make an element fill the parent element, and if Fill is specified on only one axis it will preserve aspect ratio; FillAndExpand will fill the parent element, and if the pixel size of the image is larger than the parent element it will expand the parent element. The behavior from ffImageLoading differs from the behavior of the Image class; it results in a different layout.

**Comment by daniel-luberda** [comment]
@WillemMali 

- Preservation of aspect ratio is defined by `AspectRatio` property
- The difference between `Fill` and `FillAndExpand` is that it will get the extra space distributed between other views which also have `Expand` set, so maybe you have other view that is interfering with `CachedImage`. 

Please:
- Change `CachedImage` to `Image` and see it it behaves differently.
- Please include a reproduction, so I could analyze it. 

Thanks.
