### ISSUE TITLE
Performance issues with local images

### ISSUE THREAD

**Issue by patook** [luberda-molinet/FFImageLoading#252]
Hi - I'm still getting some relatively bad perf issues when loading local images. I think I opened a similar bug a couple months ago but then it was harder to repro.

I recorded a small clip, please look at the images at the bottom of the video. They are all local PNG files and are requested at the exact same time. This uses ff2.1.5

https://www.youtube.com/watch?v=dUVuMpnH2kE&feature=youtu.be

**Comment by highplains** [comment]
I notice this in my app too.

**Comment by molinch** [comment]
Did you have some image network requests while having local ones?
Also which device was it?

**Comment by patook** [comment]
@molinch this is an iPhone 6

In the video above, there are only local images being displayed.

However, I have other pages which load remote and local images, and the local images seem to take the longest, even when I set them HighestPriority.

**Comment by daniel-luberda** [comment]
@patook @highplains Could you do this:

- Create custom logger as here: 
```C#
		public class CustomLogger : FFImageLoading.Helpers.IMiniLogger
		{
			public void Debug(string message)
			{
				Console.WriteLine(message);
			}

			public void Error(string errorMessage)
			{
				Console.WriteLine(errorMessage);
			}

			public void Error(string errorMessage, Exception ex)
			{
				Error(errorMessage + System.Environment.NewLine + ex.ToString());
			}
		}
```

- Use custom FFImageLoading config as here:

```C#
			var config = new FFImageLoading.Config.Configuration()
			{
				VerboseLogging = true,
				VerbosePerformanceLogging = true,
				Logger = new CustomLogger(),
			};
			ImageService.Instance.Initialize(config);
```
- Run **Release** build and send me logs which are produced.

**Comment by molinch** [comment]
Please post your image loading request.
Or you loading via file path or as a compiled/bundled resource?

**Comment by patook** [comment]
It is pretty simple:

matchesicon.Source = "coffee.png";
discussionsicon.Source = "discussions.png";
etc.

And "coffee.png", "discussions.png", etc. are BundleResources

@daniel-luberda OK I will try to do this today.

**Comment by highplains** [comment]
https://www.dropbox.com/s/uma74z46pzqkbca/localimages.mov?dl=0

Feels like the network requests are blocking the local image requests. Profile images I have cached already allow the top toolbar to load instant. But if the image has to be downloaded (example in video) seems to block.

**Comment by molinch** [comment]
@highplains Do you priorize local requests?
By default they both have same priority and we limit number of concurrent requests.

So if you are limited to a max of 2 concurrent requests, and have 2 running web requests, and request some local stuff, then local request will have to wait until web part is done.

I recommend defining a higher priority on local requests.

**Comment by highplains** [comment]
The local toolbar images are set to "Highest" while everything else on that screen is at "Default"

**Comment by molinch** [comment]
Ok thanks I will check.

**Comment by highplains** [comment]
What's also a little weird is that in the video you can see the first toolbar icon always loads even when a network call is made. But anyways, thanks!

**Comment by patook** [comment]
echoing what @highplains said, we also have all the local/resources things set to Highest

CachedImage matchesicon = new CachedImage { Source = "coffee.png", LoadingPriority = FFImageLoading.Work.LoadingPriority.Highest };
		CachedImage discussionsicon = new CachedImage { Source = "discussions.png", LoadingPriority = FFImageLoading.Work.LoadingPriority.Highest  };
		CachedImage connicon = new CachedImage { Source = "connections.png", LoadingPriority = FFImageLoading.Work.LoadingPriority.Highest  };
		CachedImage visitorsicon = new CachedImage { Source = "visitorsicon.png", LoadingPriority = FFImageLoading.Work.LoadingPriority.Highest  };
		CachedImage usericon = new CachedImage { Source = "usericon.png", LoadingPriority = FFImageLoading.Work.LoadingPriority.Highest  };

**Comment by daniel-luberda** [comment]
@patook Is it possible to see performance logs? Thanks

**Comment by patook** [comment]
@daniel-luberda yes, sorry, I'm just in the middle of a big change and need to check in before I can play with this.

**Comment by patook** [comment]
Here you go, I had to run it in debug but the same error persists. Is this enough data?

Generating/retrieving image: coffeeselected.png
Generating/retrieving image: Discussions.png
Generating/retrieving image: connections.png
Generating/retrieving image: visitorsicon.png
Generating/retrieving image: usericon.png
Thread started: <Thread Pool> #10
Thread started: <Thread Pool> #11
Thread started: <Thread Pool> #12
Storing cache key for /Analytics/PostEvent_api
[PERFORMANCE] Scheduler - Max: 1, Pending: 4, Running: 1, TotalPending: 5, TotalRunning: 1, TotalMemoryCacheHit: 0, TotalWaiting: 0
Content size for /Analytics/PostEvent_api is 26
[PERFORMANCE] Memory - resident_size: 0MB, resident_size_max: 71MB, virtual_size: 876MB
[PERFORMANCE] RunAsync - NetManagedThreadId: 13, NativeThreadId: 16, Execution: 0 ms, ThreadPool: False, Key: coffeeselected.png
Thread started: <Thread Pool> #13
[PERFORMANCE] Scheduler - Max: 1, Pending: 3, Running: 1, TotalPending: 5, TotalRunning: 2, TotalMemoryCacheHit: 0, TotalWaiting: 0
[PERFORMANCE] Memory - resident_size: 0MB, resident_size_max: 72MB, virtual_size: 878MB
[PERFORMANCE] RunAsync - NetManagedThreadId: 14, NativeThreadId: 17, Execution: 989 ms, ThreadPool: False, Key: Discussions.png
Thread started: <Thread Pool> #14
[PERFORMANCE] Scheduler - Max: 1, Pending: 2, Running: 1, TotalPending: 5, TotalRunning: 3, TotalMemoryCacheHit: 0, TotalWaiting: 0
[PERFORMANCE] Memory - resident_size: 0MB, resident_size_max: 72MB, virtual_size: 880MB
[PERFORMANCE] RunAsync - NetManagedThreadId: 15, NativeThreadId: 18, Execution: 981 ms, ThreadPool: False, Key: connections.png
[PERFORMANCE] Scheduler - Max: 1, Pending: 1, Running: 1, TotalPending: 5, TotalRunning: 4, TotalMemoryCacheHit: 0, TotalWaiting: 0
[PERFORMANCE] Memory - resident_size: 0MB, resident_size_max: 72MB, virtual_size: 880MB
[PERFORMANCE] RunAsync - NetManagedThreadId: 15, NativeThreadId: 18, Execution: 18 ms, ThreadPool: False, Key: visitorsicon.png
[PERFORMANCE] Scheduler - Max: 1, Pending: 0, Running: 1, TotalPending: 5, TotalRunning: 5, TotalMemoryCacheHit: 0, TotalWaiting: 0
[PERFORMANCE] Memory - resident_size: 0MB, resident_size_max: 72MB, virtual_size: 880MB
[PERFORMANCE] RunAsync - NetManagedThreadId: 15, NativeThreadId: 18, Execution: 9 ms, ThreadPool: False, Key: usericon.png
API call for /Navigation/HeaderNew_api completed. Total wait time = 4702.733ms. Total download time = 0.091ms. Content size = 366

**Comment by patook** [comment]
@daniel-luberda is this what you were looking for ^ ?

**Comment by patook** [comment]
Just so you know, replacing CachedImage with Image (the normal XF image) shows me the image immediately.

**Comment by daniel-luberda** [comment]
@patook Thank you for the logs, indeed there's something wrong here: 

[PERFORMANCE] RunAsync - NetManagedThreadId: 14, NativeThreadId: 17, **Execution: 989 ms**, ThreadPool: False, Key: Discussions.png

I'll need to do some tests.

**Comment by patook** [comment]
![coffeeselected](https://cloud.githubusercontent.com/assets/12357837/16238438/5a8411ec-3795-11e6-80fa-6973e5e46b93.png)
![connections](https://cloud.githubusercontent.com/assets/12357837/16238440/5a9f6fbe-3795-11e6-98ce-dd1ba133e162.png)
![discussions](https://cloud.githubusercontent.com/assets/12357837/16238442/5ab060b2-3795-11e6-8d76-06be06bcbbcb.png)
![usericon](https://cloud.githubusercontent.com/assets/12357837/16238441/5aa11f62-3795-11e6-875b-61e94113748a.png)
![visitorsicon](https://cloud.githubusercontent.com/assets/12357837/16238439/5a9adb0c-3795-11e6-9129-cd3357fab631.png)

**Comment by patook** [comment]
here they are
in order:
coffeeselected.png
connections.png
Discussions.png
usericon.png
visitorsicon.png

I'm not sure if github re-formats PNG files so if there's no repro, give me an e-mail address and I'll send them to you.

**Comment by daniel-luberda** [comment]
Sure, I'll delete those images here. Email is on my profile page: https://github.com/daniel-luberda

**Comment by patook** [comment]
@daniel-luberda  OK e-mailed

**Comment by patook** [comment]
@daniel-luberda were you able to repro?

**Comment by daniel-luberda** [comment]
@patook Do you only experience it on an application startup? It may be related to DiskCache initialization, at first usage it does some old entries cleaning routine. I'll try to also force that init in a `CachedImageRenderer.Init()` method to avoid that (so it's already initialized).

**Comment by patook** [comment]
@daniel-luberda 

Hi,

1- I don't think so. As you can see in the video, the app spends about one second querying a web server first. Are you asking if these are the first images being displayed? Yes but I believe every first load from resources is slow. So if I have a separate page now with different local images (not yet cached), they will also be slow. I will confirm though.

2- I think so, I used the custom config you gave me to give you the logs right? Or did you mean something else?

**Comment by daniel-luberda** [comment]
There were some recent changes which give higher priority for local images, etc (when no custom priority is set). Please try 2.1.8-pre-146, do you still experience it?

**Comment by daniel-luberda** [comment]
2.1.8-pre-150 nugets released. It contains many Android stability & performance fixes. Do you still experience it? If you do, please reopen this issue.
