### ISSUE TITLE
Is CachedImage supporting .NET Native Compilation?

### ISSUE THREAD

**Issue by ThumbGen** [luberda-molinet/FFImageLoading#253]
Hi

Although my Xamarin Forms app works perfectly in debug mode it fails loading any images when compiled using .NET Native for Release. I couldn't find any relevant logs or info. None of the CachedImage events are triggered. I played a lot with the Default.rd.xml in my UWP app but without success.

I am trying to load images both as embedded resource from a different PCL and as normal image from the Xamarin App PCL. 

Any hints?

**Comment by daniel-luberda** [comment]
https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/universal/#Target_Invocation_Exception_when_using_Compile_with_.NET_Native_tool_chain

> If your UWP app is referencing multiple assemblies (for example third party control libraries, or your application itself is split into mulitple PCLs), Xamarin.Forms may be unable to load objects from those assemblies (such as custom renderers).
> 
> This might occur when using the Compile with .NET Native tool chain which is an option for UWP apps in the Properties > Build > General window for the project.
> 
> You can fix this by using a UWP-specific overload of the Forms.Init call in App.xaml.cs as shown in the code below (you should replace ClassInOtherAssembly with an actual class your code references):
> 
> ```
> // you'll need to add `using System.Reflection;`
> List<Assembly> assembliesToInclude = new List<Assembly>();
> 
> //Now, add in all the assemblies your app uses
> assembliesToInclude.Add(typeof (ClassInOtherAssembly).GetTypeInfo().Assembly);
> 
> //Also do this for all your other 3rd party libraries
> 
> Xamarin.Forms.Forms.Init(e, assembliesToInclude);
> // replaces Xamarin.Forms.Forms.Init(e);
> ```
> Add a reference to each assembly that is referenced by the app.

**Comment by ThumbGen** [comment]
I've already applied those suggestion but it seems I forgot one of the libs (the Platform).

Thank you!
