### ISSUE TITLE
Add Anti-Aliasing to Circle/Rounded Transformations algorithm

### ISSUE THREAD

**Issue by tomcrusader** [luberda-molinet/FFImageLoading#254]
On Windows 8.1 using an CircleTransformation (in ListView) cause the image to be distorted.

Removing the Transformation fixes the issue.

![Example](https://dl.dropboxusercontent.com/u/1027259/Examples/ffimage_win81.png)

**Comment by daniel-luberda** [comment]
- The algorithm for rounded corners on windows platform is a really basic one (without anti-aliasing) : https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Windows/RoundedTransformation.cs#L47
- The image resolution is low 100pixels.
- Set `DownsampleUseDipUnits` to `true` for a better results. The image size will be not 100px but 100 device independent pixels

**Comment by daniel-luberda** [comment]
@tomcrusader Did you manage to fix it?

**Comment by tomcrusader** [comment]
Worked around it by removing Transformation. Still not that good. But Win is very secondary for the project

**Comment by daniel-luberda** [comment]
Could you write more about your environment / device,  etc? Thanks.

**Comment by tomcrusader** [comment]
Environment / Device
- Windows 10
- Visual Studio 2015 Upd 2

Project:
- Windows 8.1 / Android / iOS / UWP
- Xamarin.Forms 2.3.0.107
- FFImageLoading.Forms 2.1.5
- Prism.Forms 6.1.0-pre6

**Comment by YZahringer** [comment]
@daniel-luberda I have the same issue with UWP, the quality of rounding is really bad. Using Clipping on Control could not solve the problem of anti-aliasing?

Clipping example: [https://blog.xamarin.com/elegant-circle-images-in-xamarin-forms/](https://blog.xamarin.com/elegant-circle-images-in-xamarin-forms/)
Fill ellipse example: [https://github.com/jamesmontemagno/ImageCirclePlugin/blob/9555c55c13375a144bcedf1da1b189aff471d709/src/ImageCircle.Forms.Plugin.UWP/ImageCircleRenderer.cs#L41](https://github.com/jamesmontemagno/ImageCirclePlugin/blob/9555c55c13375a144bcedf1da1b189aff471d709/src/ImageCircle.Forms.Plugin.UWP/ImageCircleRenderer.cs#L41)

I tried the last plugin, the rendering is really good.

**Comment by daniel-luberda** [comment]
@YZahringer Unluckily, clipping can't be used with FFImageLoading, as transformations on Windows are implemented as raw bitmap pixels modifications. We just need a better algorithm.

**Comment by daniel-luberda** [comment]
Something like using Xiaolin Wu's algorithm: 

- http://create.stephan-brumme.com/antialiased-circle/
- https://rosettacode.org/wiki/Xiaolin_Wu%27s_line_algorithm#C.23

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/858
