### ISSUE TITLE
Image appaers only after waiting for serveral minutes

### ISSUE THREAD

**Issue by lhaussknecht** [luberda-molinet/FFImageLoading#255]
I have an odd phenomenon.

We have a Xamarin.Froms Android app. All images are loaded with FFImageLoading over http(s). The images are not displayed directly. Leaving the device alone for say 10 to 20 minutes and the images appear.

Any ideas, what could lead to this behavior (and how to fix it)?

**Comment by daniel-luberda** [comment]
It's really hard to predict what it might be without a reproduction. Could upload one? Is it on every platform?

**Comment by lhaussknecht** [comment]
Hi. We are currently on Android (KitKat).

Here's some more info about our problem. We attached a MiniLogger and the output (after several minutes) is this:

```
06-22 08:43:05.618 I/mono-stdout( 7527): Debug: [PERFORMANCE] Scheduler - Max: 1, Pending: 4, Running: 1, TotalPending: 5, TotalRunning: 1, TotalMemoryCacheHit: 0, TotalWaiting: 0
Debug: [PERFORMANCE] Scheduler - Max: 1, Pending: 4, Running: 1, TotalPending: 5, TotalRunning: 1, TotalMemoryCacheHit: 0, TotalWaiting: 0
Debug: [PERFORMANCE] Memory - Free: 230MB (28%), Total: 832MB, Heap - Free: 6MB (6%), Total: 96MB
06-22 08:43:05.628 I/mono-stdout( 7527): Debug: [PERFORMANCE] Memory - Free: 230MB (28%), Total: 832MB, Heap - Free: 6MB (6%), Total: 96MB
```

I think there is something in the scheduler blocking. I forked the repo and will add a lot of debug calls.

**Comment by molinch** [comment]
@lhaussknecht Any progress on your debugging?

**Comment by lhaussknecht** [comment]
I found the problem!

The first image we load in our app is a profile picture. The service, which provides it is not working at the moment. So a GET on that url throws an exception!

After I removed the image from our xaml every other image is loading directly. 

Maybe there is a bug somewhere in the ImageLoaderTask where the StreamResolver is called and the exception occurs.

**Comment by lhaussknecht** [comment]
I have another update. The request is not just failing, it is hanging. The response sends a wrong content-length header. The content is smaller then the given content-length, so the request hangs (for about 10 minutes) before a timeout and an exception occurs.

I'm wondering why the default HttpReadTimeout of 30 (seconds?) has no effect?

**Comment by daniel-luberda** [comment]
@lhaussknecht I'll try to review code that is responsible for handling that case. Many thanks for debugging.

> I'm wondering why the default HttpReadTimeout of 30 (seconds?) has no effect?

It may be some mono `HttpClient` bug. I experienced it several times too.

**Comment by daniel-luberda** [comment]
HttpReadTimeout was ignored / not working. It's fixed, thanks.

**Comment by lhaussknecht** [comment]
Great! Will give it a try tomorrow! Thank's for the cool lib!

**Comment by daniel-luberda** [comment]
@lhaussknecht Prerelease NuGet containing the fix released. You can test it with it. Cheers.
