### ISSUE TITLE
CachedImage in ListView items sometimes don't appear 

### ISSUE THREAD

**Issue by labretrox** [luberda-molinet/FFImageLoading#256]
I develop Xamarin.Forms app for iOS, WP and Android. I tried to use CachedImage to show images in items of ListView (one image per item)., Images dowanload successfully from the network but sometimes they not appear in items. Interesting thing is that image appears if I tap on item where it previously didn't appear after download. Platform: WP 8.1.

**Comment by molinch** [comment]
@labretrox  Could you upload a sample ?

**Comment by daniel-luberda** [comment]
It's because of this: https://bugzilla.xamarin.com/show_bug.cgi?id=41087

As you see that method is not available in current stable Xamarin.Forms for Windows. If I include it, it will make Windows package not compatible with older Xamarin.Forms versions.

**Comment by daniel-luberda** [comment]
Please continue here as it's the same issue: https://github.com/luberda-molinet/FFImageLoading/issues/238

**Comment by daniel-luberda** [comment]
Prerelease NuGet package containing the fix released. Could you test it?
