### ISSUE TITLE
FFImage RotateTransformation is not rotating the Image along with border.

### ISSUE THREAD

**Issue by rsvsakthi** [luberda-molinet/FFImageLoading#257]
I am using the below code to rotate the image, it is rotating the image but not the border of the image.

Setting the border to the image
viewHolder.UpImage.SetBackgroundResource(Resource.Layout.TileBorderStyle);

TileBorderStyle:
<?xml version="1.0" encoding="utf-8" ?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
  
  <stroke
      android:width="5dp"
      android:color="#08488e" >
  </stroke>
  <padding
      android:left="4dp"
      android:top="4dp"
      android:right="4dp"
      android:bottom="4dp"    >
  </padding>
  <corners
      android:radius="5dp"   >
  </corners>
</shape>

Setting the rotation:
ImageService.Instance.LoadUrl(item.UpImage).Transform(new RotateTransformation(7))
               .Retry(3, 200)
               .DownSample(180, 180)
               .LoadingPlaceholder("PlaceholderTile.png", FFImageLoading.Work.ImageSource.CompiledResource)
               .ErrorPlaceholder("PlaceholderTile.png", FFImageLoading.Work.ImageSource.CompiledResource)
               .Into(viewHolder.UpImage);

**Comment by rsvsakthi** [comment]
Xamarin.Forms: I have tried the rotation in the xaml page Rotation property but it is giving the distortion in the border. It is not smooth. Also, I have tried setting the Anti Aliasing property to true in Android but the same result.

![imagerotate1](https://cloud.githubusercontent.com/assets/20108469/16303208/2b76cbb8-396d-11e6-8605-f48d0cabe53a.png)
![imagerotate2](https://cloud.githubusercontent.com/assets/20108469/16303209/2b77dbd4-396d-11e6-96bf-a73047357cae.png)

**Comment by daniel-luberda** [comment]
- The first approach won't work with `RotateTransformation` in FFImageLoading as the transformation is constructed in a way that it preserves original image border. 

- You can create your own `CustomRotateTransformation` with border support, basing on RoundedTransformation which has border support. Code here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Droid/RoundedTransformation.cs#L94-L118

**Comment by rsvsakthi** [comment]
Hi Daniel,

Thank you! I tired the approach mentioned in the link provided in your comment. Now it is working fine. I am getting Out Of Memory issue at the line,
Bitmap bitmap = Bitmap.CreateBitmap((int)desiredWidth, (int)desiredHeight, Bitmap.Config.Argb8888);

Can you please help me in resolving the issue? I have a screen where I deal with lot of images and it is happening there when I load the page for the second time.

Thank you,
Sakthivel R

**Comment by daniel-luberda** [comment]
Could you share your code? That line, looks just fine. It must be something different.
