### ISSUE TITLE
[Question] Save transformed images

### ISSUE THREAD

**Issue by deman4ik** [luberda-molinet/FFImageLoading#260]
There is a method to access image source with all transformations applied?

**Comment by deman4ik** [comment]
Find out GetImageAsJPG in source

**Comment by daniel-luberda** [comment]
There's a new API for such purposes: 
```C#
var stream = ImageService.Instance.LoadUrl("http://example.org/test.png")
 .DownSampleInDIP(width: 200)
 .Transform(new CircleTransformation())
 .AsPNGStreamAsync(); // or AsJPGStreamAsync
```

Then just save content of a stream to the disk :)

**Comment by Ikhlas06** [comment]
how would you save new re-sized image stream into cache or app data folder?
