### ISSUE TITLE
New transformation for tint color

### ISSUE THREAD

**Issue by lolohouse** [luberda-molinet/FFImageLoading#261]
Hi, I made the class TintColorTransformation if you want, you can add it to your library.
Thanks

[TintColorTransformation.zip](https://github.com/luberda-molinet/FFImageLoading/files/334528/TintColorTransformation.zip)

**Comment by daniel-luberda** [comment]
@lolohouse Thanks for a collaboration :) We'll need to add also another platforms implementations, I'll see what I ca do with it. Once again, thanks.

**Comment by daniel-luberda** [comment]
`TintTransformation` is now implemented for all platforms.

**Comment by MosCD** [comment]
TintTransformation works good but in XAML I am using App resource dictionary for theming my App
so I use
<Application.Resources>
        <ResourceDictionary>
            <Color x:Key="BrandColor">#13a3d7</Color>
 </ResourceDictionary>
</Application.Resources>

and inside Xaml I use the keyword Color ="{StaticResource BrandColor}" .. that works fine every where
except for the TintTransformation Hex property
 <fftransformations:TintTransformation  EnableSolidColor="true" HexColor="{StaticResource BrandColor}" />
that doesn't work and throws an error

**Comment by daniel-luberda** [comment]
@MosCD `HexColor` is a string property, so you must use: 

```XML
<Application.Resources> <ResourceDictionary> <x:String x:Key="BrandColor">#13a3d7</x: String> </ResourceDictionary> </Application.Resources>
```
