### ISSUE TITLE
Bitmap recycle() usage in FFImageLoading

### ISSUE THREAD

**Issue by eddnav** [luberda-molinet/FFImageLoading#262]
Hi, I know that the use of `recycle()` in newer versions of Android is not encouraged, but does the cache/rendering strategies of FFImageLoading make use of `recycle()` in any way?

**Comment by daniel-luberda** [comment]
@eddnav 
- Yes, we do recycle bitmaps in FFImageLoading. 
- We use self disposing bitmaps implementation. It means that if there are no views which use a specific bitmap, it's recycled / destroyed.

**Comment by eddnav** [comment]
@daniel-luberda  thank you very much for the info, daniel, will be closing this.
