### ISSUE TITLE
Can't change BackgroundColor from Tap Gesture Command

### ISSUE THREAD

**Issue by mike-rowley** [luberda-molinet/FFImageLoading#265]
I am unable to change the background color of a CachedImage from a Tap Gesture Command on iOS and Android.  I am able to change the background color of a standard Image using the exact same code. 
I have broken the issue down to an easily reproducible set of code to create a form with two images, the white one being a CachedImage and the Grey one being a regular Image.  When you tap the White  CachedImage it should go Red, but doesn't.  When you tap the Grey Image it goes Blue as expected.

```
    public partial class BGColorTest : ContentPage
    {
        public BGColorTest()
        {
            InitializeComponent();
            var layout = new StackLayout() {Orientation = StackOrientation.Vertical};
            var cimg = new CachedImage() { HeightRequest = 100, HorizontalOptions = LayoutOptions.Fill, BackgroundColor = Color.White};
            cimg.GestureRecognizers.Add(new TapGestureRecognizer() { Command = new Command(() => cimg.BackgroundColor = Color.Red) });
            layout.Children.Add(cimg);
            var img = new Image() { HeightRequest = 100, HorizontalOptions = LayoutOptions.Fill, BackgroundColor = Color.Gray};
            img.GestureRecognizers.Add(new TapGestureRecognizer() { Command = new Command(() => img.BackgroundColor = Color.Blue) });
            layout.Children.Add(img);
            Content = layout;
        }

    }

```

Any thoughts on what might be happening here?
Thanks
M

**Comment by daniel-luberda** [comment]
It was a bug. It's fixed now. Thanks!

**Comment by daniel-luberda** [comment]
Prerelease NuGet package containing the fix released. Could you test it?

**Comment by mike-rowley** [comment]
Looks good, I tested it on the iOS and Android sample project I had and it is fixed in the prerelease

Thanks
M
