### ISSUE TITLE
Package dependency issue

### ISSUE THREAD

**Issue by tamasszadvari** [luberda-molinet/FFImageLoading#267]
I can't add the package to my Android project, because it needs to different versions of the same Xamarin.Android.Support.V4 package. (See the log below)

"Adding Xamarin.FFImageLoading.Forms...
Attempting to resolve dependency 'Xamarin.FFImageLoading (≥ 2.1.6-pre-126)'.
Downloading Xamarin.FFImageLoading 2.1.6-pre-126...
Downloading Xamarin.FFImageLoading.Forms 2.1.6-pre-126...
Attempting to resolve dependency 'Xamarin.Forms (≥ 1.4.4.6392)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (= 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.Design (= 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v7.AppCompat (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (= 23.3.0)'.
Attempting to resolve dependency 'Xamarin.Android.Support.Design (= 23.3.0)'.
Updating 'Xamarin.Android.Support.v4 23.0.1.3' to 'Xamarin.Android.Support.v4 23.3.0' failed. Unable to find a version of 'Xamarin.Forms' that is compatible with 'Xamarin.Android.Support.v4 23.3.0'."

**Comment by daniel-luberda** [comment]
@tamasszadvari 

- FFImageLoading doesn't rely on any specific Xamarin.Forms / Xamarin.Android.Support packages versions. 
- Do you use Xamarin Studio or Visual Studio?
- Did you try to uninstall and then reinstall all packages? (including Xamarin.Forms)

**Comment by tamasszadvari** [comment]
@daniel-luberda 
I've noticed that, that's why I don't understand the error.
I use Xamarin Studio.
No, I haven't tried, but thanks for the suggestion, I'll try. Do you have any idea what can be the source of the problem?

**Comment by daniel-luberda** [comment]
I noticed that Xamarin Studio has sometimes problems with package updates. Uninstalling and installing all packages again usually resolves it.

**Comment by tamasszadvari** [comment]
I've deleted all of my references, and uninstalled all of my packages, and after that, I've tried to install the FFImageLoading.Forms package, and the issue is still there:
"Adding Xamarin.FFImageLoading.Forms...
Attempting to resolve dependency 'Xamarin.FFImageLoading (≥ 2.1.6)'.
Attempting to resolve dependency 'Xamarin.Forms (≥ 1.4.4.6392)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (= 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.Design (= 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v7.AppCompat (≥ 23.0.1.3)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (= 23.4.0)'.
Updating 'Xamarin.Android.Support.v4 23.0.1.3' to 'Xamarin.Android.Support.v4 23.4.0' failed. Unable to find a version of 'Xamarin.Forms' that is compatible with 'Xamarin.Android.Support.v4 23.4.0'."

I use the latest stable version of the Xamarin Studio and Xamarin.Android too.

**Comment by daniel-luberda** [comment]
Did you have Xamarin.Forms package installed before adding Xamarin.FFImageLoading.Forms? What version?

**Comment by tamasszadvari** [comment]
Oh, I've managed to solve this problem. The problem was that in the packages folder I had two different versions of the Xamarin.Forms package, and one of them was an early (I think around version 2.0) version. After I've deleted the early version, I successfully installed the FFImageLoading package.
Maybe this will be a useful information in the future for others too. :)

**Comment by daniel-luberda** [comment]
Great. Thanks for the info.

**Comment by tamasszadvari** [comment]
Your welcome. This problem gave me a lot of headache. Maybe it would be useful to mention this in the readme file, but this is just an advice (because now I have to reinstall every other package, and I had a lot :) ). Package version conflicts are always a pain in the... :)
