### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by ryanherman** [luberda-molinet/FFImageLoading#268]
My Xamarin.Forms project is using FFImageLoading 2.1.6 and here is my stack trace, not sure whats up.

07-08 11:24:55.824 E/mono-rt ( 1660): Stacktrace:
07-08 11:24:55.824 E/mono-rt ( 1660): 
07-08 11:24:55.824 E/mono-rt ( 1660):   at <unknown> <0xffffffff>
07-08 11:24:55.824 E/mono-rt ( 1660):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_static_object_method_a (intptr,intptr&,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00012>
07-08 11:24:55.824 E/mono-rt ( 1660):   at Java.Interop.JniEnvironment/StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00069] in /Users/builder/data/lanes/3415/ffca580c/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12645
07-08 11:24:55.824 E/mono-rt ( 1660):   at Java.Interop.JniPeerMembers/JniStaticMethods.InvokeObjectMethod (string,Java.Interop.JniArgumentValue*) [0x0001b] in /Users/builder/data/lanes/3415/ffca580c/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97
07-08 11:24:55.824 E/mono-rt ( 1660):   at Android.Graphics.BitmapFactory.DecodeStream (System.IO.Stream,Android.Graphics.Rect,Android.Graphics.BitmapFactory/Options) [0x00070] in /Users/builder/data/lanes/3415/ffca580c/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Graphics.BitmapFactory.cs:745
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTask/<GetDrawableAsync>d__16.MoveNext () <IL 0x005bb, 0x02b17>
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<FFImageLoading.Work.WithLoadingResult`1<FFImageLoading.Drawables.SelfDisposingBitmapDrawable>>.Start<FFImageLoading.Work.ImageLoaderTask/<GetDrawableAsync>d__16> (FFImageLoading.Work.ImageLoaderTask/<GetDrawableAsync>d__16&) [0x00031] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTask.GetDrawableAsync (string,FFImageLoading.Work.ImageSource,bool,bool,System.IO.Stream) <IL 0x00051, 0x0030b>
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTask/<RetrieveDrawableAsync>d__19.MoveNext () <IL 0x00091, 0x00502>
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<FFImageLoading.Work.WithLoadingResult`1<FFImageLoading.Drawables.SelfDisposingBitmapDrawable>>.Start<FFImageLoading.Work.ImageLoaderTask/<RetrieveDrawableAsync>d__19> (FFImageLoading.Work.ImageLoaderTask/<RetrieveDrawableAsync>d__19&) [0x00031] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTask.RetrieveDrawableAsync (string,FFImageLoading.Work.ImageSource,bool,bool) <IL 0x00048, 0x00293>
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTask/<TryGeneratingImageAsync>d__13.MoveNext () <IL 0x000ae, 0x005bb>
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<FFImageLoading.Work.GenerateResult>.Start<FFImageLoading.Work.ImageLoaderTask/<TryGeneratingImageAsync>d__13> (FFImageLoading.Work.ImageLoaderTask/<TryGeneratingImageAsync>d__13&) [0x00031] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTask.TryGeneratingImageAsync () <IL 0x00027, 0x0020f>
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTaskBase/<>c__DisplayClass46_0/<<RunAsync>b__0>d.MoveNext () <IL 0x00030, 0x00156>
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<FFImageLoading.Work.ImageLoaderTaskBase/<>c__DisplayClass46_0/<<RunAsync>b__0>d> (FFImageLoading.Work.ImageLoaderTaskBase/<>c__DisplayClass46_0/<<RunAsync>b__0>d&) [0x00031] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTaskBase/<>c__DisplayClass46_0.<RunAsync>b__0 () <IL 0x00027, 0x001f3>
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTaskBase/<RunAsync>d__46.MoveNext () <IL 0x000cd, 0x0055c>
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<FFImageLoading.Work.ImageLoaderTaskBase/<RunAsync>d__46> (FFImageLoading.Work.ImageLoaderTaskBase/<RunAsync>d__46&) [0x00031] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTaskBase.RunAsync () <IL 0x00027, 0x0020f>
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.WorkScheduler/<QueueTaskAsync>d__34.MoveNext () <IL 0x003bf, 0x0176e>
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<FFImageLoading.Work.WorkScheduler/<QueueTaskAsync>d__34> (FFImageLoading.Work.WorkScheduler/<QueueTaskAsync>d__34&) [0x00031] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.WorkScheduler.QueueTaskAsync (FFImageLoading.Work.WorkScheduler/PendingTask,bool) <IL 0x00037, 0x00277>
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.WorkScheduler/<RunAsync>d__33.MoveNext () <IL 0x00201, 0x00e07>
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<FFImageLoading.Work.WorkScheduler/<RunAsync>d__33> (FFImageLoading.Work.WorkScheduler/<RunAsync>d__33&) [0x00031] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.WorkScheduler.RunAsync () <IL 0x00027, 0x001fb>
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.WorkScheduler/<Run>d__31.MoveNext () <IL 0x00010, 0x000af>
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<FFImageLoading.Work.WorkScheduler/<Run>d__31> (FFImageLoading.Work.WorkScheduler/<Run>d__31&) [0x00031] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.WorkScheduler.Run (FFImageLoading.Work.WorkScheduler/PendingTask) <IL 0x00027, 0x0022f>
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.WorkScheduler.QueueAndGenerateImage (FFImageLoading.Work.IImageLoaderTask) <IL 0x000b3, 0x004df>
07-08 11:24:55.824 E/mono-rt ( 1660):   at FFImageLoading.Work.WorkScheduler/<LoadImageAsync>d__27.MoveNext () <IL 0x001c6, 0x00bdb>
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.InvokeMoveNext (object) [0x00000] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1089
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x0008d] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/executioncontext.cs:957
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/executioncontext.cs:904
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.Run () [0x0003b] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1070
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action,bool,System.Threading.Tasks.Task&) [0x00025] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:821
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Threading.Tasks.Task.FinishContinuations () [0x0007a] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:3624
07-08 11:24:55.824 E/mono-rt ( 1660):   at System.Threading.Tasks.Task.FinishStageThree () [0x00045] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2366
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.Tasks.Task`1<bool>.TrySetResult (bool) [0x00058] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:488
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>.SetResult (bool) [0x0004b] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:608
07-08 11:24:55.828 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTask/<PrepareAndTryLoadingFromCacheAsync>d__6.MoveNext () <IL 0x0025a, 0x00f77>
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.InvokeMoveNext (object) [0x00000] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1089
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x0008d] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/executioncontext.cs:957
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/executioncontext.cs:904
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.Run () [0x0003b] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1070
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action,bool,System.Threading.Tasks.Task&) [0x00025] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:821
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.Tasks.Task.FinishContinuations () [0x0007a] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:3624
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.Tasks.Task.FinishStageThree () [0x00045] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2366
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.Tasks.Task`1<bool>.TrySetResult (bool) [0x00058] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Future.cs:488
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>.SetResult (bool) [0x0004b] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:608
07-08 11:24:55.828 E/mono-rt ( 1660):   at FFImageLoading.Work.ImageLoaderTask/<LoadPlaceHolderAsync>d__17.MoveNext () <IL 0x003de, 0x01863>
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.InvokeMoveNext (object) [0x00000] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1089
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x0008d] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/executioncontext.cs:957
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/executioncontext.cs:904
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.Run () [0x0003b] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1070
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x0000b] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:720
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/threadpool.cs:857
07-08 11:24:55.828 E/mono-rt ( 1660):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/threading/threadpool.cs:1212
07-08 11:24:55.828 E/mono-rt ( 1660):   at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) <IL 0x0001f, 0x00052>
07-08 11:24:55.828 E/mono-rt ( 1660): 
07-08 11:24:55.828 E/mono-rt ( 1660): Attempting native Android stacktrace:
07-08 11:24:55.828 E/mono-rt ( 1660): 
07-08 11:24:55.836 E/mono-rt ( 1660): 
07-08 11:24:55.836 E/mono-rt ( 1660): =================================================================
07-08 11:24:55.836 E/mono-rt ( 1660): Got a SIGSEGV while executing native code. This usually indicates
07-08 11:24:55.836 E/mono-rt ( 1660): a fatal error in the mono runtime or one of the native libraries 
07-08 11:24:55.836 E/mono-rt ( 1660): used by your application.
07-08 11:24:55.836 E/mono-rt ( 1660): =================================================================
07-08 11:24:55.836 E/mono-rt ( 1660): 
07-08 11:24:55.836 F/libc    ( 1660): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 1708 (Threadpool work)

**Comment by daniel-luberda** [comment]
It's probably a device / emulator problem : http://stackoverflow.com/questions/14023291/fatal-signal-11-sigsegv-at-0x00000000-code-1-phonegap
