### ISSUE TITLE
Android: The class FFImageLoading.Views.ImageViewAsync could not be loaded

### ISSUE THREAD

**Issue by jamesatgithub** [luberda-molinet/FFImageLoading#269]
I'm using FFImageLoading with a Xamarin.Forms app (PCL based) and installed all nuget on both the Forms and the Android projects, but  got a strange error on android app starting:

_The class FFImageLoading.Views.ImageViewAsync could not be loaded, used in FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null_

But with dotPeek I can see the ImageViewAsync class in the FFImageLoading.Platform.dll which is referenced by the android project. In the android MainActivity.cs, I followed the sample code to init the lib, so what could be the reason of this error? Thanks

**Comment by topsites** [comment]
I can confirm - I was getting the exact same error; deleted obj + bin folder under droid and that solved it.

**Comment by jamesatgithub** [comment]
Thanks! deleting the obj + bin folder fixed it.
