### ISSUE TITLE
Configurable offline mode

### ISSUE THREAD

**Issue by Puffdot** [luberda-molinet/FFImageLoading#270]
I'd like to see a configurable setting that makes it possible to disable all network traffic for image downloading, and restrict loading images to cached images only. If a user is on a limited data plan, they may want to opt out of image downloading, but cached images should still be loaded.

**Comment by daniel-luberda** [comment]
It's very easy to do with a newest prerelease version. You have different options:

- provide your own `IDownloadCache` implementation when setting custom configuration options. 
- provide your own `IDataResolverFactory` implementation when setting custom configuration options. Something like: 

```C#
public class CustomDataResolverFactory : IDataResolverFactory
{
	public IDataResolver GetResolver(string identifier, ImageSource source, TaskParameter parameters, Configuration configuration)
	{
		switch (source)
		{
			case ImageSource.ApplicationBundle:
				return new BundleDataResolver();
			case ImageSource.CompiledResource:
				return new ResourceDataResolver();
			case ImageSource.Filepath:
				return new FileDataResolver();
			case ImageSource.Url:
			{
				if (offline)
					return new OfflineUrlPlaceholder();
				return new UrlDataResolver(configuration);
			}
			case ImageSource.Stream:
				return new StreamDataResolver();
			default:
				throw new ArgumentException("Unknown type of ImageSource");
		}
	}
}
```
