### ISSUE TITLE
TintTransformation doesn't work on IOS

### ISSUE THREAD

**Issue by mike-rowley** [luberda-molinet/FFImageLoading#271]
The new TintTranslation is working on Android but on IOS I get no images loading.

Is there something special I need on IOS to make it work, I am using the same line of code from a PCL on both platforms

this.fimg_Icon.Transformations.Add(new TintTransformation(0, 38,85, 1));

**Comment by daniel-luberda** [comment]
Hi @mike-rowley 

- Do you have `FFImageLoading` & `FFImageloading.Forms` & `FFImageLoading.Transformations` (important) packages in a Android specific project? 
- Do you have `CachedImageRenderer.Init();` in `MainActivity.cs`?

**Comment by mike-rowley** [comment]
In my iOS project I have version 2.1.6 of FFImageLoading, FFImageLoading.Forms, FFImageLoading.Touch, FFImageLoading.Platform and FFImageLoading.Tranformations loaded.  I have verified that 2.1.6 is also referenced in the PCL.

I have tried using a Hex code (with and without the pound sign, no pound sign doesn't work on Android either) and I have tried the RGB values and get no image appearing.

I do have CachedImageRenderer.Init(); in my App Delegate for iOS

**Comment by mike-rowley** [comment]
Any suggestion on a work around for this or should I not use the TintTransformation at this point?

Thanks
M

**Comment by daniel-luberda** [comment]
Hi. I'll look into this today. It's a bug, but easy to fix.

**Comment by daniel-luberda** [comment]
Fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/e64fd8e9cc3cda292d9ea5c7e5e11aa07e280bd9

Sorry for a delay.
