### ISSUE TITLE
LoadingPlaceholder no longer works

### ISSUE THREAD

**Issue by roberthewitt** [luberda-molinet/FFImageLoading#275]
Hi, 

I use the Droid part of your library, and as of 2.1.1 the LoadingPlaceholder is no longer functioning. 
It worked as of 2.1.0. 

Steps: 
+ Use the LoadUrl method, to load an asset from the internet
+ Use the LoadingPlaceholder referencing a drawable using ImageSource.CompiledResource
+ wait for the remote asset to load. 

Expected: 
While loading the image from the internet, I would expect to see the placeholder asset

Actual: 
The LoadingPlaceholder asset is only used to transition to the downloaded image upon loading of the asset from the network. 

Notes: 
I have tested using the latest version of the library (2.1.6) and this issue still exists.
I regressed the versioning to find the last point this actually worked which might help you track down the cause of the problem.

**Comment by daniel-luberda** [comment]
Are you sure? Please clone repo, run sample Xamarin.Forms app and see that's working fine.

**Comment by kamelmojawaz1** [comment]
Hi all,

I have the same issue as well , but I'm using Forms. placeholders are not working and I'm on the latest update .

**Comment by daniel-luberda** [comment]
You have to provide more info, do you use stable Android channel? Xamarin.Android Version: 6.1.1.1

**Comment by roberthewitt** [comment]
Hi, 

I have created a test project that shows the error
https://github.com/roberthewitt/FFImageExample

Please also find attached my Xamarin -> About -> Details output. 

I use Genymotion, using a Nexus 5, on 6.0.0 , api23. 
This bug also happens on any device that I deploy it to so, in my eyes, is unrelated to the emulator. 

Thanks, 
Rob

[xamarin_about.txt](https://github.com/luberda-molinet/FFImageLoading/files/390239/xamarin_about.txt)

**Comment by roberthewitt** [comment]
@daniel-luberda  did you need any more details or is what I provided ok? 

Cheers, 
Rob

**Comment by daniel-luberda** [comment]
Hi. I'll look into this today.

**Comment by wqi** [comment]
Any updates on the status of a fix?

**Comment by daniel-luberda** [comment]
It's fixed now, sorry for a delay.

**Comment by roberthewitt** [comment]
Thanks for the fix, 

Is this being rolled into a public release?
