### ISSUE TITLE
[UWP] Problem with FFImage control in new instance of app

### ISSUE THREAD

**Issue by konradkalemba** [luberda-molinet/FFImageLoading#276]
Hi, I tried to open xaml Page (which contains FFImage xaml control) in new window using [this code from Template10](https://github.com/Windows-XAML/Template10/blob/8451536a80ca9008f100414d982dbaca5a43f6b5/Template10%20(Library)/Services/ViewService/ViewService.cs#L31). Unfortunately it throws System.Exception: 

> System.Exception: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD)) 
![wp_ss_20160729_0002](https://cloud.githubusercontent.com/assets/8682104/17247659/fe041d54-5594-11e6-9925-acedc1c4d6f5.png)

It'd be great if someone could help me with this. 😃 
Regards.

**Comment by daniel-luberda** [comment]
It's this: https://github.com/luberda-molinet/FFImageLoading/issues/166
