### ISSUE TITLE
Clicked event in CachedImage

### ISSUE THREAD

**Issue by cuong1024** [luberda-molinet/FFImageLoading#277]
Hi, I use your sample at "ListPage". I want show big picture when I click Image in listview, but I can't find event "Clicked" of CachedImage. How can I do it? 
Thanks.

**Comment by daniel-luberda** [comment]
Just as any other Xamarin.Forms view - uou should just assign a new TapGestureRecognizer for it. Here: https://developer.xamarin.com/guides/xamarin-forms/user-interface/gestures/tap/
