### ISSUE TITLE
[Xamarin Forms CachedImage] https images doesn't change!

### ISSUE THREAD

**Issue by fravezzimattia** [luberda-molinet/FFImageLoading#278]
When I use https instead http for image source, and change image on the server,  application doesn't show new image!  

but if I use http in source it works fine!

`  <forms:CachedImage Source="{Binding ImmagineLarga, StringFormat='http**s**://www.miosito.com{0}'}" CacheDuration="1">
`

**Comment by daniel-luberda** [comment]
- Images are cached by default, that's why you see old image. 
  - You can control this with CacheDuration property
  - You can clear cache with cache invalidation methods
  - You can disable cache globally or per view
  - You can use custom caching keys strategy
