### ISSUE TITLE
Performance issue in ListView

### ISSUE THREAD

**Issue by zjxeditor** [luberda-molinet/FFImageLoading#279]
Hi, I am developing with Xamarin Forms. As for a ListView with lots of images (about 10 image in each cell), it suffers from scrolling lag. Note, I have done all the optimization for the ListView to speed it up (include recycle cell strategy). After some experiments, I find the bottleneck is the image loading process. When I scroll the ListView up or down, image source of the recycled view cell will be updated. Then it will cause a short pause. This impose a serious influence on the user experience. So, how to fix this problem? (I thought the visited image will be cached automatically, hence there should not be any performance issue when I scroll back to show the images before, what's wrong? )

**Comment by daniel-luberda** [comment]
- All loaded images are cached by default. 
- It's probably something with your layout design. It's hard to tell without any sample reproduction. 
- Another tip for fast cells: don't use bindings, use cell's `OnBindingContextChanged` override.

**Comment by zjxeditor** [comment]
The layout design is all right. Experiment shows that this issue will occur only when I change the binding image source for every view cell. I will try to remove bindings and put everything in OnBindingContextChanged.

**Comment by zjxeditor** [comment]
Hi, I haven't solved this problem yet. To make things clear, I am showing my code now. I test on a Nexus 5.0 with Android 6.0.

- Here is the ListView config:
![image](https://cloud.githubusercontent.com/assets/16350631/17514603/190cd436-5e66-11e6-889b-c416842a99f1.png)

- Here is the ListView code:
![image](https://cloud.githubusercontent.com/assets/16350631/17514667/74ac6a18-5e66-11e6-80b0-ca06e124b3c3.png)

- Here is the ViewCell code
   `public class PostViewCell : ViewCell` 
    `{`
        `private List<CachedImage> _collections; `
 
        public PostViewCell() 
        {
            _collections = new List<CachedImage>()
            {
                new CachedImage()
                {
                    Aspect = Aspect.AspectFill,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                    CacheDuration = TimeSpan.FromDays(30),
                    TransparencyEnabled = false,
                },
                new CachedImage()
                {
                    Aspect = Aspect.AspectFill,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                    CacheDuration = TimeSpan.FromDays(30),
                    TransparencyEnabled = false,
                },
                new CachedImage()
                {
                    Aspect = Aspect.AspectFill,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                    CacheDuration = TimeSpan.FromDays(30),
                    TransparencyEnabled = false,
                },
                new CachedImage()
                {
                    Aspect = Aspect.AspectFill,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                    CacheDuration = TimeSpan.FromDays(30),
                    TransparencyEnabled = false,
                },
                new CachedImage()
                {
                    Aspect = Aspect.AspectFill,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                    CacheDuration = TimeSpan.FromDays(30),
                    TransparencyEnabled = false,
                },
                new CachedImage()
                {
                    Aspect = Aspect.AspectFill,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                    CacheDuration = TimeSpan.FromDays(30),
                    TransparencyEnabled = false,
                },
                new CachedImage()
                {
                    Aspect = Aspect.AspectFill,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                    CacheDuration = TimeSpan.FromDays(30),
                    TransparencyEnabled = false,
                },
                new CachedImage()
                {
                    Aspect = Aspect.AspectFill,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                    CacheDuration = TimeSpan.FromDays(30),
                    TransparencyEnabled = false,
                },
                new CachedImage()
                {
                    Aspect = Aspect.AspectFill,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                    CacheDuration = TimeSpan.FromDays(30),
                    TransparencyEnabled = false,
                }
            };

            var grid = new Grid()
            {
                HorizontalOptions = LayoutOptions.Fill,
                VerticalOptions = LayoutOptions.Fill,
                RowSpacing = 10,
                ColumnSpacing = 10,
                HeightRequest = 300,
                Margin = new Thickness(0, 20, 0, 0)
            };
            grid.RowDefinitions.Add(new RowDefinition() {Height = GridLength.Star });
            grid.RowDefinitions.Add(new RowDefinition() {Height = GridLength.Star });
            grid.RowDefinitions.Add(new RowDefinition() { Height = GridLength.Star });
            grid.ColumnDefinitions.Add(new ColumnDefinition() {Width = GridLength.Star});
            grid.ColumnDefinitions.Add(new ColumnDefinition() {Width = GridLength.Star});
            grid.ColumnDefinitions.Add(new ColumnDefinition() {Width = GridLength.Star});

            int index = 0;
            for (int i = 0; i < 3; i++)
            {
                for (int j = 0; j < 3; j++)
                {
                    Grid.SetRow(_collections[index], i);
                    Grid.SetColumn(_collections[index], j);
                    grid.Children.Add(_collections[index]);
                    index++;
                }
            }

            View = grid;
        }

        protected override void OnBindingContextChanged()
        {
            foreach (var image in _collections)
            {
                image.Source = "https://farm9.staticflickr.com/8625/15806486058_7005d77438.jpg";
            }
        }
    }

- Problem
As you can see, each cell own 9 images. When the BindingContext changed, I simply reassign the image source. Then a scroll lag will occur. Note I use the same image url for all CachedImages just for test.

**Comment by Emasoft** [comment]
I have the same problem with my ListView. The scroll lags happen when the image is loaded or OnBindingContextChanged is called.

**Comment by zjxeditor** [comment]
Any solutions or suggestions?

**Comment by daniel-luberda** [comment]
There's a new prerelease (2.1.8) nuget which contains some fixes / enhancements. One of them is ability to set maximum concurrent image loading tasks through config (`SchedulerMaxParallelTasks` property). You could try it and tune FFImageLoading to your needs. https://github.com/luberda-molinet/FFImageLoading/commit/9687b42eb1664c4b6b78b1008244fc1fb7a48875

**Comment by zjxeditor** [comment]
I will fully debug this problem these days and give the result soon.

**Comment by daniel-luberda** [comment]
2.1.8-pre-150 nugets released. It contains many Android stability & performance fixes. Do you still experience it? If you do, please reopen this issue.
