### ISSUE TITLE
Potential build issue: FFImageLoading.dll references System.Net.Http version 1.5.0.0 and FFImageLoading.Platform.dll references System.Net.Http version 4.0.0.0

### ISSUE THREAD

**Issue by jasonCodesAway** [luberda-molinet/FFImageLoading#280]
Hello,

Thanks for the great library. Unfortunately I'm having a build issue with the latest nugets using VS2015. I'm probably doing something bone-headed, here is how you can repro...what am I doing wrong here?

Thank you in advance!

Cheers from Florida,
Jason

1. Visual Studio -> New Project -> Cross-Platform -> Blank Xaml App (Xamarin.Forms.Portable).     
  1. when prompted, I selected UWP Project Windows 10 Anniversary Edition for Minimum and Target version, but I'm 99.99% sure that's irrelevant
1. Manage nuget packages for solution, update Xamarin Forms to 2.3.1.114 (latest stable, as of now)
1. Add 'Xamarin.FFImageLoading' to your Droid Project (version 2.1.6 as of now)
  1. You can also add it to your iOS project if desired
1. Add 'Xamarin.FFImageLoading.Forms" to your Xamarin Forms Project
1. Visual Studio -> Tools -> Options -> Projects & Solutions -> Build and Run -> MS Build project output verbosity: Diagnostic
1. Build and see the below diagnostic output in the logs. Without diagnostic output all you get is this unhelpful warning in VS's Error List:

`Warning	Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>	Test.Droid	C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	2221	
`

And here is the helpful info from the diagnostic-level build log that tells me that FFImageLoading.dll references System.Net.Http version 1.5.0.0 but FFImageLoading.Platform.dll references System.Net.Http version 4.0.0.0

>  There was a conflict between "**System.Net.Http, Version=4.0.0.0**, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "**System.Net.Http, Version=1.5.0.0,** Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". (TaskId:276)
2>      "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it had a higher version. (TaskId:276)
2>      **References which depend on "System.Net.Http, Version=4.0.0.0**, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll]. (TaskId:276)
2>          C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.Forms.2.3.1.114\lib\MonoAndroid10\Xamarin.Forms.Platform.Android.dll (TaskId:276)
2>            Project file item includes which caused reference "C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.Forms.2.3.1.114\lib\MonoAndroid10\Xamarin.Forms.Platform.Android.dll". (TaskId:276)
2>              C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.Forms.2.3.1.114\lib\MonoAndroid10\Xamarin.Forms.Platform.Android.dll (TaskId:276)
2>              C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.Forms.2.3.1.114\lib\MonoAndroid10\Xamarin.Forms.Xaml.dll (TaskId:276)
2>              C:\Users\codeMonkey\Projects\tmpNew\Test\Test\bin\Debug\Test.dll (TaskId:276)
2>              C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.Forms.2.3.1.114\lib\MonoAndroid10\Xamarin.Forms.Core.dll (TaskId:276)
2>              C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.Forms.2.3.1.114\lib\MonoAndroid10\Xamarin.Forms.Platform.dll (TaskId:276)
2>              C:\Users\codeMonkey\Projects\tmpNew\Test\Test.Droid\bin\Debug\Test.Droid.dll (TaskId:276)
2>          C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.FFImageLoading.2.1.6\lib\MonoAndroid10\\**FFImageLoading.Platform.dll** (TaskId:276)
2>            Project file item includes which caused reference "C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.FFImageLoading.2.1.6\lib\MonoAndroid10\FFImageLoading.Platform.dll". (TaskId:276)
2>              C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.FFImageLoading.2.1.6\lib\MonoAndroid10\\**FFImageLoading.Platform.dll** (TaskId:276)
2>      **References which depend on "System.Net.Http, Version=1.5.0.0**, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" []. (TaskId:276)
2>          C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.FFImageLoading.2.1.6\lib\MonoAndroid10\\**FFImageLoading.dll** (TaskId:276)
2>            Project file item includes which caused reference "C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.FFImageLoading.2.1.6\lib\MonoAndroid10\FFImageLoading.dll". (TaskId:276)
2>              C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.FFImageLoading.2.1.6\lib\MonoAndroid10\FFImageLoading.dll (TaskId:276)
2>              C:\Users\codeMonkey\Projects\tmpNew\packages\Xamarin.FFImageLoading.2.1.6\lib\MonoAndroid10\\**FFImageLoading.Platform.dll** (TaskId:276)
2>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning. (TaskId:276)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2221,3): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
2>Done executing task "ResolveAssemblyReference". (TaskId:276)
2>Done building target "_ResolveSatellitePaths" in project "Test.Droid.csproj".: (TargetId:231)

**Comment by daniel-luberda** [comment]
Hi, 

https://forums.xamarin.com/discussion/40732/dependent-assembly-version-conflict-binding-redirects

**Comment by jasonCodesAway** [comment]
That's not very satisfying, but my whole Xamarin experience has been far from easy. I'll close this out. Thanks.
