### ISSUE TITLE
CachedImageRenderer - Which namespace?

### ISSUE THREAD

**Issue by zuckerthoben** [luberda-molinet/FFImageLoading#281]
I am trying out FFImageLoading. The documentation says that you have to put "CachedImageRenderer.Init();" on every platform. Could you say to which namespace this belongs? VS cant resolve it for me and I looked through the classes with IntelliSense but could not find this specific class. So where is it and could you also update the documentation to be more specific in this case? It helps newer developers.

**Comment by daniel-luberda** [comment]
- You must have `Xamarin.FFImageLoading.Forms` nuget package installed in a platform specific project. 
- The namespace is the same: `Xamarin.FFImageLoading.Forms`
- `CachedImageRenderer.Init();` also need to be called from a platform specific project

**Comment by DesenEnterprises** [comment]
Hi Daniel, I've installed all xamarin.ffimageloading.* nuget packages v.2.2.25 and I only have a ffimageloading namespace that does not have CachedImageRenderer in it anywhere... what am I doing wrong?

![image](https://user-images.githubusercontent.com/34489471/34910846-75c7f91a-f88b-11e7-9fc9-87d8dcd88e53.png)

![image](https://user-images.githubusercontent.com/34489471/34910861-a1c3201c-f88b-11e7-9144-b9a074b41cfa.png)

**Comment by mylojp** [comment]
I think that you have to append the Platform flavor like this

using FFImageLoading.Forms.Mac;   
using FFImageLoading.Forms.Droid;

**Comment by DesenEnterprises** [comment]
Yes, I found that and did some NuGet version manipulation and got it working, but it did not make any difference for images loading in Android.  Was hoping it would.  :(

Thank you for your reply!
