### ISSUE TITLE
What is correct path for loading placeholders in Xamarin Android projects?

### ISSUE THREAD

**Issue by jsauvexamarin** [luberda-molinet/FFImageLoading#283]
I have an image in a Xamarin Android project that does not seen to load. In the console, I'm getting

`Not found: placeholderProfileImage.png from Filepath`

every time an image view comes onto the screen.

My call looks like this:

```
// use FFImageLoading library to asynchronously:
ImageService.Instance
	.LoadUrl(acquaintance.SmallPhotoUrl, TimeSpan.FromHours(Settings.ImageCacheDurationHours))  // get the image from a URL
	.LoadingPlaceholder("placeholderProfileImage.png")                                          // specify a placeholder image
	.Transform(new CircleTransformation())                                                      // transform the image to a circle
	.Error(e => System.Diagnostics.Debug.WriteLine(e.Message))									// if there is an error loading the image, print it to debug console
	.IntoAsync(viewHolder.ProfilePhotoImageView);                                               // load the image into the ImageView
```

The `placeholderProfileImage.png` exists as an Android resource in both the drawable and mipmap folders, but FFImageLoading can't seem to find it. Do I need to provide a full path?

This all works great in my Xamarin Forms project, with the same placeholder image in the drawable folder.

**Comment by daniel-luberda** [comment]
@jsauvexamarin Hi, try without extension. I'll modify code to handle both cases as it's a little misleading.

**Comment by daniel-luberda** [comment]
Also you need to use second parameter of LoadingPlaceholder method which tells FFImageLoading what source is (you should set it to `CompiledResource` or `ApplicationBundle`)

**Comment by jsauvexamarin** [comment]
Awesome. Many thanks!

**Comment by daniel-luberda** [comment]
I've just checked `CompiledResource` resolver and it handles both cases (with or without extension), so no changes are required. 

Also please note, that there was a little placeholder bug which is fixed in current prerelease nuget (it will be released as stable soon).

**Comment by aspyct** [comment]
Ha, I've been looking for this for the past 30 minutes. Is it documented somewhere else than in this issue?

**Comment by daniel-luberda** [comment]
What do you want to achieve?

`ImageService.Instance.LoadUrl("http://sdadasada").LoadingPlaceholder("file.png", Work.ImageSource.Filepath);` etc

**Comment by aspyct** [comment]
Specifically,

```
ImageService
    .Instance
    .LoadUrl(article.CoverUrl)
    .LoadingPlaceholder("article_placeholder", FFImageLoading.Work.ImageSource.CompiledResource)
    .Into(viewHolder.ImageView);
```

I couldn't find much documentation about how to use Resource placeholders on Android.

**Comment by daniel-luberda** [comment]
On Android:

- CompiledResource = Drawables (eg. Resources->Drawable folder)
- ApplicationBundle = Assets

What's not working for you?

**Comment by aspyct** [comment]
Oh, it is working. It's just that I couldn't find that in the documentation.

**Comment by daniel-luberda** [comment]
I understand :) Wiki can be edited by anyone, so feel free to add it if you want. I didn't have time yet to update all the docs.

**Comment by aspyct** [comment]
Ha alright then, I'll try and find some time to do that properly. Cheers!

**Comment by CDrosos** [comment]
The team must really have fight with the documentations or they try to get the gold medal on "everyone trying to find it and noone cant"

**Comment by kernel-coder** [comment]
@daniel-luberda  Can I specify placeholder-image per CachedImage? If yes, please how I can do it?

**Comment by kernel-coder** [comment]
CachedImage::LoadingPlaceholder I think?
