### ISSUE TITLE
Cropping enhancements

### ISSUE THREAD

**Issue by Spierki** [luberda-molinet/FFImageLoading#284]
Hello, 

I have a question about the cropping functionnality.

I try your example and I also tried with a local picture on the phone. And it seems that each time I make a pan/pinch gesture, the view disappear for a few second (5 -6sec) and appear again (crop like I want). 

Is it normal that the image disappear ? Because if yes I think it's really to slow for me to use it in production ? 
In android I was using this library : https://github.com/jdamcd/android-crop 
I would like to have a square that the user can move to decide which part of the picture to crop, do you plan to implement something like that ? If not, maybe I can try but I'm a little bit new to Xamarin.

Thanks in advance

**Comment by daniel-luberda** [comment]
FFImageLoading is multi purpose image view, it's not a specialized cropping tool. Someone will need to create a specialized crop control on top of that (any collaboration welcome). 

See this thread for more information about cropping with FFImageLoading and possible solutions: https://forums.xamarin.com/discussion/comment/207655/#Comment_207655

**Comment by Spierki** [comment]
I'm gonna look to implement this control when I have time, come back to you when I have any news

**Comment by daniel-luberda** [comment]
@Spierki There's a new prerelease of FFImageLoading (2.1.8-pre-150) which introduces some performance improvements (eg. image is not cleared when image source is not changed). This will lead to better overall experience in CropTransformation sample.

**Comment by Spierki** [comment]
@daniel-luberda I'm gonna try this very soon

**Comment by molinch** [comment]
Closing since this was handled
