### ISSUE TITLE
On Android TransparencyEnabled = false on a PNG shows transparency 

### ISSUE THREAD

**Issue by lecnierfreeman** [luberda-molinet/FFImageLoading#285]
If you open the FFImageLoading Sample app and click on Basic example option but before go to the source code of that page and replace the source of the CachedImage for a PNG with alpha channel([ I used this one](https://s3.amazonaws.com/tkibetu/products/Wizard%20-%20Frog.png/0de702a116ebe1fdc91f927fbe2d113a/Wizard%20-%20Frog.png)) with the option TransparencyEnabled = false on Android should show the image without transparency.
Tested on VS Simulator and Samsung Note 4

**Comment by lecnierfreeman** [comment]
I was checking the source code and I think the problem is because you are only setting the desired pixel format in the preferred decoder options: options.InPreferredConfig = Bitmap.Config.Rgb565; (ImageLoaderTask.cs Ln:371) but this doesn't force the decoder to use that format.
 I located this line:	
bitmap = BitmapFactory.DecodeStream(stream, null, options);
and tried to add this after:
<pre>
				    if (options.InPreferredConfig == Bitmap.Config.Rgb565 && bitmap.HasAlpha)
				    {
				        var newBitmap = Bitmap.CreateBitmap(bitmap.Width, bitmap.Height, Bitmap.Config.Rgb565);
                        var c = new Canvas(newBitmap);
                        c.DrawColor(Color.White);
				        var p = new Paint();
				        c.DrawBitmap(bitmap, 0, 0, p);
                        bitmap.Recycle();
				        bitmap = newBitmap;				        
				    }</pre>

and now I get the desired image without alpha channel and looks similar to IOS behavior.

**Comment by daniel-luberda** [comment]
Read this: http://stackoverflow.com/questions/14633003/rgb565-for-sprites
It's in preferred decoder options because of performance reasons.
