### ISSUE TITLE
Cannot draw XML vector CompiledResource on Android

### ISSUE THREAD

**Issue by yeah568** [luberda-molinet/FFImageLoading#286]
We currently have a few ImageViews that are drawn with a vector XML from our resources/drawable folder. However, trying to load these into ImageViewAsync results in no image showing up - is this a bug or is drawing vectors not supported? Thanks!

**Comment by daniel-luberda** [comment]
Hi @yeah568 @wqi,

Is it possible you could create a reproduction so I could debug/fix it?

**Comment by daniel-luberda** [comment]
Is it possible to have a working reproduction? Thanks

**Comment by yeah568** [comment]
Hey Daniel, unfortunately, I don't have access to the codebase any more, as I was an intern working over the summer. I'll try and get a sample, but I don't have anything right now, unfortunately.

**Comment by fedemkr** [comment]
Hi, I created a repo with the reproduction of the issue, hope it helps

https://github.com/D-Genix/FFILXmlVectorTest

**Comment by daniel-luberda** [comment]
https://github.com/D-Genix/FFILXmlVectorTest/blob/master/FFILXmlVector/FFILXmlVector.Droid/MainActivity.cs#L33-L36

FFImageLoading doesn't support loading xml drawables through its loader. You can do it like that:

`imageView.SetDrawable(Resources.GetDrawable(Resource.Drawable.YourVectorDrawable));`

**Comment by rusanov-vladimir** [comment]
If you load vector drawable bypassing FFImageLoading, then transformations cannot be applied. Any way to overcome this limitation?
