### ISSUE TITLE
can't load image with cdn custom style  url  

### ISSUE THREAD

**Issue by ReinhardHsu** [luberda-molinet/FFImageLoading#287]
http://cdn.aa.com/bb.webp                   this image url is work.
http://cdn.aa.com/bb.webp/width90    this image url not work.
http://cdn.aa.com/bb.webp?imageView2/2/w/90/h/90/format/webp/interlace/0/q/80    this image url not work.
http//cdn.aa.com/bb.webp-width90    this image url not work.

**Comment by daniel-luberda** [comment]
FFImageLoading is using standard http client with all default behaviors. Some questions: 

- Do you use any custom http client handler?
- What platforms is this? 
- Are you able to download file with standard net `HttpClient` `GetAsync` method? Maybe the server only support post calls?
