### ISSUE TITLE
Can't get FFImageLoading to work with version 2.3.1.114 of Xamarin.Forms

### ISSUE THREAD

**Issue by nicknijenhuis** [luberda-molinet/FFImageLoading#288]
I can't get FFImageLoading to work with  the latest version (2.3.1.114) of Xamarin.Forms, when I use version 2.3.0.107 it does work.

The actual error I get is: `The "XamlCTask" task failed unexpectedly.`

I tried deleting all packages, I tried clean, rebuild and everything else that is proposed as a solution here: https://forums.xamarin.com/discussion/54790/the-xamlctask-task-failed-unexpectedly

**Comment by daniel-luberda** [comment]
It's not an FFImageLoading issue, rather Xamarin Forms / Xamarin Studio issue.
