### ISSUE TITLE
MissingMemberException: Method 'CachedImage.InvalidateViewMeasure' not found.

### ISSUE THREAD

**Issue by ronpf** [luberda-molinet/FFImageLoading#289]
Just updated to FFImageLoading version 2.1.6
Android (simulator only) build throwing "System.MissingMemberException" with the message 
"Method 'CachedImage.InvalidateViewMeasure' not found." 

No problem with iOS builds or Android devices.

Xamarin.Forms version 2.3.1.114

Console output:
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.MissingMethodException: Method 'CachedImage.InvalidateViewMeasure' not found.
[MonoDroid]   at FFImageLoading.Forms.Droid.CachedImageRenderer+<>c__DisplayClass9_0.<UpdateBitmap>b__0 (IScheduledWork work) [0x00011] in <filename unknown>:0 
[MonoDroid]   at FFImageLoading.Work.ImageLoaderTaskBase+<>c__DisplayClass51_3.<ConfigureParameters>b__5 () [0x00000] in <filename unknown>:0 
[MonoDroid]   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3540/1cf254db/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36 
[MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3540/1cf254db/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:81 
[MonoDroid]   at (wrapper dynamic-method) System.Object:d882cb90-a0e3-4926-9113-99ed20e0041f (intptr,intptr)

[mono] Unhandled Exception:
[mono] System.MissingMethodException: Method 'CachedImage.InvalidateViewMeasure' not found.
[mono]   at (wrapper dynamic-method) System.Object:d882cb90-a0e3-4926-9113-99ed20e0041f (intptr,intptr)
[mono]   at (wrapper native-to-managed) System.Object:d882cb90-a0e3-4926-9113-99ed20e0041f (intptr,intptr)
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'CachedImage.InvalidateViewMeasure' not found.
[mono-rt]   at (wrapper dynamic-method) System.Object:d882cb90-a0e3-4926-9113-99ed20e0041f (intptr,intptr)
[mono-rt]   at (wrapper native-to-managed) System.Object:d882cb90-a0e3-4926-9113-99ed20e0041f (intptr,intptr)

**Comment by timbrand** [comment]
I can confirm this. Having the same issue on my Android emulator. No real Android device nearby at the moment, so will test that tomorrow.

**Comment by daniel-luberda** [comment]
@ronpf @timbrand  Hi, did you try to uninstall app from emulator first?

**Comment by ronpf** [comment]
@daniel-luberda  Cleaning, deletion of the obj folder, and uninstalling appears to have fixed the problem. 
It seemed to be isolated to the Xamarin XAP emulators but I'm not seeing it there anymore.
Thanks!
