### ISSUE TITLE
Resizing image 

### ISSUE THREAD

**Issue by sevontheedge** [luberda-molinet/FFImageLoading#292]
Hey, I'm having some doubts about the get png and jpg methods that return a byte array. I need to resize the image before sending it to a REST service. I need the image to have a maximum of 1MB and if it is larger I use these methods passing the desired width and height required that would make the image have aproximatelly the size I need. When I check the service the image is way smaller than it should be.

Do you have any ideas of this behaviour or are there any methods that would allow me to pass the desired quality?

Thanks in advance

**Comment by daniel-luberda** [comment]
Is it Android? If yes, for performance reasons we resize it using insample size. Read more here: https://developer.android.com/training/displaying-bitmaps/load-bitmap.html#load-bitmap
