### ISSUE TITLE
FFImageLoading is unable to generate image.

### ISSUE THREAD

**Issue by rusty21** [luberda-molinet/FFImageLoading#293]
On Android I have an ImageViewAsync inside of an ListView that I am loading an image into as follows:

```
ImageService.Instance.LoadUrl(item.CoverPhoto)
.Retry(3,200)
.ErrorPlaceholder(placeholder.ToString(), ImageSource.CompiledResource)
.LoadingPlaceholder (placeholder.ToString (), ImageSource.CompiledResource)
.Error (exception => 
{ 
    #if DEBUG 
    Debugger.Break (); 
    #endif
});
```
The error action here occasionally fires as I'm scrolling around the ListView with a generic exception and the message says "FFImageLoading is unable to generate image." The exception has no stack trace. I can give you the call stack when the application pauses on Debugger.Break();

```
TaskExtensions.AnonymousMethod__0(System.Exception exception)
FFImageLoading.Work.ImageLoaderTaskBase.()
Java.Lang.Thread.RunnableImplementor.Run()
Java.Lang.IRunnableInvoker.n_Run(System.IntPtr jnienv, System.IntPtr native__this)
object.3b1001b5-a37b-4833-ae9e-3ebf9fc57b0e (arg0, arg1)
```

I have a short list only 30 items or so. All the images seem to download fine, but it seems there is a problem loading the image into the ImageViewAsync. Testing on a physical device, Moto G running Android 5.1, but getting reports on other phones and OS versions too. Any ideas as to why this would be?

**Comment by daniel-luberda** [comment]
Hi @rusty21,

I can't reproduce it. Can you attach a sample project? 

Thanks

**Comment by daniel-luberda** [comment]
2.1.8-pre-150 nugets released. It contains many Android stability & performance fixes. Do you still experience it? If you do, please reopen this issue.
