### ISSUE TITLE
Using FFImageLoading with other controls

### ISSUE THREAD

**Issue by chamamo** [luberda-molinet/FFImageLoading#296]
Hi,

I use the library for several months and I find it awesome.

On Android I always used ImageViewAsync control. Now I would use other controls, for example download the image with FFImageLoading and use the Drawable as background for other controls (Button, FloatingActionButton...etc.)

Is it possible? Thank you in advance.

**Comment by daniel-luberda** [comment]
Yes, it's possible. FFImageLoading supports multiple targets, it already has multiple targets for iOS: 

- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Touch/Work/UIBarItemTarget.cs
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Touch/Work/UIButtonTarget.cs
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Touch/Work/UIImageViewTarget.cs

Currently, on Android there's only one target: 

- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Work/ImageViewTarget.cs

If you could give complete list of potential targets, I could implement it and include it in FFImageLoading.

**Comment by daniel-luberda** [comment]
I made some initial changes to support this universally: 

With https://github.com/luberda-molinet/FFImageLoading/commit/d706b2d60bc1ce3a72b98236fee3f59a641b78a1 you can retrieve native bitmaps as:

- Android: `var nativeBitmapDrawable = await ImageService.Instance.LoadUrl("http://myimage.png").AsBitmapDrawableAsync();`
- iOS: `var nativeUIImage = await ImageService.Instance.LoadUrl("http://myimage.png").AsUIImageAsync();`

etc
