### ISSUE TITLE
[UWP] In release mode doesn't show up the images

### ISSUE THREAD

**Issue by mariolobar** [luberda-molinet/FFImageLoading#298]
I tried to uncheck the option "Compile with .NET native tool chain" and I can see the images but with this configuration my app fails in WACK testing so I think that I can not submit to the store.
Is there any solution for this problem?

**Comment by mariolobar** [comment]
I solved it adding the assemblies of FFImageLoading with this lines:

 List<Assembly> assembliesToInclude = new List<Assembly>();
 assembliesToInclude.Add(typeof(CachedImage).GetTypeInfo().Assembly);
 assembliesToInclude.Add(typeof(CachedImageRenderer).GetTypeInfo().Assembly);
 Xamarin.Forms.Forms.Init(e, assembliesToInclude);

Thank you!!

**Comment by daniel-luberda** [comment]
Thanks, I'll add that info to our Wiki page.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#windows-uwp---compile-with-net-native-tool-chain-note

**Comment by senkia** [comment]
I've tried adding the 
`typeof(FFImageLoading.Forms.WinUWP.ImageSourceBinding).GetTypeInfo().Assembly`
line but the problem remains. I've also checked the release output directory and I can see the proper FFImageLoading.Transformations dll targeting .NET Core.
