### ISSUE TITLE
Android: Image not appearing in correct rotation [2.1.6]

### ISSUE THREAD

**Issue by CliffCawley** [luberda-molinet/FFImageLoading#300]
I've created an example to reproduce this. Just load the project, switch to Droid and run and the image will appear rotated as though it's a landscape photo.

Do the same for the iOS project and it correctly displays portrait.

Viewing in an external viewer will show correctly as portrait.

The ExIf data suggests that there is a 90CCW rotation, so I assume this isn't being applied correctly on Android?

[TestImageRotation.zip](https://github.com/luberda-molinet/FFImageLoading/files/446235/TestImageRotation.zip)

**Comment by daniel-luberda** [comment]
Hi @CliffCawley, 

```C#
		public TestImageRotationViewModel()
		{
			var assembly = this.GetType().GetTypeInfo().Assembly;
			ImageResource = ImageSource.FromResource("TestImageRotation.TestImage.jpg", assembly);
		}
```

`ImageSource.FromResource` returns a `Stream`. There's no easy way to read EXIF data from it (`ExifInterface`, which is used in FFImageLoading, relies on file paths). FFImageLoading only supports EXIF orientation from local / downloaded files. Streams are always used "as is".
