### ISSUE TITLE
Heap corruption detected by dlmalloc / Android 6.0 

### ISSUE THREAD

**Issue by tjugg** [luberda-molinet/FFImageLoading#302]
public class ImageServiceViewHolder : Java.Lang.Object
        {
            public FFImageLoading.Views.ImageViewAsync Img;
            public ImageView SetFavorite;

            public int Position;
            public string AuthUrl;
            public string Url;
        }

        private View ImageServiceView(int position, ImageServiceGridItem item, View convertView)
        {
            ImageServiceViewHolder holder = null;

            var view = convertView;

            if (null != view)
                holder = view.Tag as ImageServiceViewHolder;

            if (null == holder)
            {
                holder = new ImageServiceViewHolder();

                view = LayoutInflater.Inflate(Resource.Layout.image_service_grid_item, null);

                holder.Img = view.FindViewById<FFImageLoading.Views.ImageViewAsync>(Resource.Id.imageServiceImg);
                holder.Img.Click += (sender, args) => HandleImgClick(holder);

                holder.SetFavorite = view.FindViewById<ImageView>(Resource.Id.imageServiceFavorite);
                holder.SetFavorite.Click += (sender, args) => HandleFavoriteClick(holder);

                holder.Img.LayoutParameters.Height = _width;
                holder.Img.LayoutParameters.Width = _width;

                view.Tag = holder;
            }

            ImageService.Instance.LoadUrl(item.AuthUrl)
                .Retry(10, 200)
                .DownSample(175, 175)
                .Into(holder.Img);

            holder.Position = position;
            holder.AuthUrl = item.AuthUrl;
            holder.Url = item.Url;
         }

There is the code what is causing the issue. Crash is occuring when I refresh the content of the gridview I am using the library with. The refresh buttons clears the observable collection that holds the urls that the adapter loads. Only error I get in console is: "Heap corruption detected by dlmalloc". The crash also seems to happen only if I refresh the page when some of the the images are still loading.

**Comment by daniel-luberda** [comment]
@tjugg  Is it possible I could get complete log with stack trace. There must be some more info there, you can email it privately to me.

**Comment by daniel-luberda** [comment]
2.1.8-pre-150 nugets released. It contains many Android stability fixes. Do you still experience it? If yes, please reopen this issue.

**Comment by tjugg** [comment]
I got around the error by calling  ImageService.Instance.SetPauseWork(true) before refreshing the listview. Does it make any sense why?

**Comment by daniel-luberda** [comment]
It just stops image loading. From my experience, a lot of `Heap corruption detected by dlmalloc` were caused by abnormal cpu/memory usage. 

BTW: Anyway, the newest prerelease nuget fixes a lot of Android issues. You should try it.
