### ISSUE TITLE
Android: Can't install on latest Xamarin Forms 2.3.0.107

### ISSUE THREAD

**Issue by joaoasilva** [luberda-molinet/FFImageLoading#303]
Unable to resolve dependencies. 'Xamarin.Android.Support.Design 23.4.0.1' is not compatible with 'Xamarin.Forms 2.3.0.107 constraint: Xamarin.Android.Support.Design (= 23.3.0)'.

Thanks

**Comment by daniel-luberda** [comment]
Hi @joaoasilva Did you resolve it? What was the cause of it? FFImageLoading doesn't use any specific support packages.
