### ISSUE TITLE
Bitmapdescriptor with ffimageloading ?

### ISSUE THREAD

**Issue by kitkat14** [luberda-molinet/FFImageLoading#304]
readonly Pin _pin = new Pin()
		{
			Type = PinType.Place,
			Label = AppResources.AppResources.DragMe,
			IsDraggable = true,
			Icon = BitmapDescriptorFactory.FromBundle("stop.png")
		};

If I load 50 pins it crashes with out of memory error on android (iphone works fine), the 1G trick doesnt work. So I was hoping I could use FFImageLoading ...but I dont know if it is possible..

**Comment by daniel-luberda** [comment]
Yes, it's possible, FFImageLoading supports multiple targets as destinations. It'll require custom `ITarget` implementation. I'll prepare it soon and post it here.

**Comment by daniel-luberda** [comment]
With https://github.com/luberda-molinet/FFImageLoading/commit/d706b2d60bc1ce3a72b98236fee3f59a641b78a1 you can retrieve native bitmaps as:

- Android: `var nativeBitmapDrawable = await ImageService.Instance.LoadUrl("http://myimage.png").AsBitmapDrawableAsync();`
- iOS: `var nativeUIImage = await ImageService.Instance.LoadUrl("http://myimage.png").AsUIImageAsync();`

Then you can use it like this on Android: 

```C#
readonly Pin _pin = new Pin()
{
Type = PinType.Place,
Label = AppResources.AppResources.DragMe,
IsDraggable = true,
Icon = BitmapDescriptorFactory.FromBitmap(nativeBitmapDrawable?.Bitmap)
};
```
