### ISSUE TITLE
Use with CarouselView

### ISSUE THREAD

**Issue by Karuna30** [luberda-molinet/FFImageLoading#305]
Thanks for the great library. I am having trouble using it with CarouselView.

I get the below error:
Binding: 'imageURL' property not found on 'Item',  target property: 'FFImageLoading.Forms.CachedImage.Source'

What should be the 'Source' of CachedImage, if it is within a carousel view?

**Comment by daniel-luberda** [comment]
I don't understand. Could you post some code sample here? Thanks.

**Comment by Karuna30** [comment]
Sorry, it is just a warning that xamarin forms give even if I use regular "Image", got confused with that.
