### ISSUE TITLE
XAML Bind Image from URI 

### ISSUE THREAD

**Issue by LuigiMaestrelli** [luberda-molinet/FFImageLoading#306]
Is it possible to bind the Source property to an URI?

I'm trying to do this inside a ViewCell.

```
<forms:CachedImage HorizontalOptions="Start" VerticalOptions="Center" WidthRequest="80" HeightRequest="80" Source="{Binding FotoUrl}">
</forms:CachedImage>
```

The FotoUrl contains a URL like this http://192.168.2.72/apiuseall/api/UseUsuarios/Foto?id=1
Initially, the FotoUrl was a string property with that URL. But I also tried with UriImageSource and ImageSource.

**Comment by daniel-luberda** [comment]
@LuigiMaestrelli Yes it's possible. There are many examples with url in our sample app: https://github.com/luberda-molinet/FFImageLoading/tree/master/samples/ImageLoading.Forms.Sample/Shared
