### ISSUE TITLE
Apply transformations to error and placeholder image

### ISSUE THREAD

**Issue by modplug** [luberda-molinet/FFImageLoading#307]
I want to be able to apply a circle and color (tint) transformation to my error and placholder images.
Basically I want my whatever image that comes out of my Load() method (image, error, placeholder) to be run through the transformations I apply.

Is there an easy way of doing this?

**Comment by daniel-luberda** [comment]
Hi @modplug,

Yes it's possible. Transformations are applied to placeholders by default. What is you platform? XF/Android/iOS/Windows?

```C#
ImageService.Instance.LoadCompiledResource("myPhoto.png")
  .LoadingPlaceholder("loading.png", Work.ImageSource.ApplicationBundle)
  .ErrorPlaceholder("error.png", Work.ImageSource.ApplicationBundle)
  .Transform(new List<ITransformation>() { new TintTransformation(), new CircleTransformation() } )
  .TransformPlaceholders(true) // you can enable/disable it here
  .Into(yourView);
```

**Comment by modplug** [comment]
`await ImageService.Instance.LoadUrl(settings.Url)
		.LoadingPlaceholder(defaultImageName, ImageSource.CompiledResource)
		.Transform(new RoundedWithFillTransformation(0, 10, settings.BackgroundColor.ToHex()))
		.FadeAnimation(settings.Effect == ImageLoadEffect.Fade, false)
		.ErrorPlaceholder(defaultImageName, ImageSource.CompiledResource)
		.Transform(new RoundedWithFillTransformation(0, 10, settings.BackgroundColor.ToHex()))
		.DownSample(size.Width, size.Height)
		.IntoAsync(_imageView);`

This is on Android and this is how I've set up my pipeline

**Comment by modplug** [comment]
I managed to tweak my custom transformation to do what I want so this can be closed now.

Peace!

**Comment by parinparikh-nv** [comment]
This library works absolutely awesome for image loading.Is there any option to set color in place of image in LoadingPlaceHolder?

**Comment by jorgenstorlie** [comment]
Is it possible for you to post the code for 
CircledWithFillTransformation?

**Comment by daniel-luberda** [comment]
@modplug Latest FFImageLoading prerelease allows to write custom selectors for transformation (you can decide if you want to apply transformation on placeholder only too). See example here: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/Transformations/TransformationsSelectorPageModel.cs#L21-L43

@parinparikh-nv. I want to add `BackgroundColorTransformation` soon, which can be applied to any (even fully transparent) png. But... if you're using Xamarin.Forms you can bind `BackgroundColor` property of `CachedImage` to its `IsLoading` property and set custom color basing on its value.
