### ISSUE TITLE
Images not loading on Forms.iOS platform

### ISSUE THREAD

**Issue by VikasN0204** [luberda-molinet/FFImageLoading#309]
I have included updated  FFImageLoading v2.1.7 from Nuget to my App, and images not loading on iOS application (on Emulator). I can see images on Android tab. I am working on Xamarin.forms App. I am not getting any error. But i unable to see the image  on cached image control. I even tried the the nuget sample code. I still gets same result for iOS.
As i wanted to give black tinted effect over image, i even ffimage tranformation from nuget. 
Here are my observation:-
On Android:-
1. tinttransformation() -- greenyish shade over image.
2. tinttransformation(different hex value) - turns black over image and unable to view image
3. tinttransformation(r,g,b,a) - no effect 

On iOS:-
Images not loading on Screen.

**Comment by VikasN0204** [comment]
@daniel-luberda ,
Now it is also working on iOS.
On Android/iOS, i can able to see the image but tinttransformation(black tint shade) doesnt work over image.
How to user alpha channel with example.

**Comment by daniel-luberda** [comment]
@VikasN0204 Ok, so I'll close this.

> On Android/iOS, i can able to see the image but tinttransformation(black tint shade) doesnt work over image.
> How to user alpha channel with example.

Just use eg. `#AARRGGBB` format instead `#RRGGBB`, where AA is alpha hex value.
