### ISSUE TITLE
Occasional threading issue when used with Xamarin.Android

### ISSUE THREAD

**Issue by jsauvexamarin** [luberda-molinet/FFImageLoading#311]
I'm seeing a threading issue that seems to be originating from where I'm using FFImageLoading in a Xamarin.Android project.

```
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
at System.Threading.Tasks.TaskCompletionSource`1[TResult].SetException(System.Exception exception)(<filename unknown>: 0)
at FFImageLoading.TaskParameterExtensions+<>c__DisplayClass1_0.<IntoAsync>b__0(System.Exception ex)(<filename unknown>: 0)
at FFImageLoading.Work.ImageLoaderTaskBase+<>c__DisplayClass51_2.<ConfigureParameters>b__3()(<filename unknown>: 0)
at Java.Lang.Thread+RunnableImplementor.Run()(<filename unknown>: 0)
at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)(<filename unknown>: 0)
at (wrapper dynamic-method) System.Object:4166226e-46b7-4fce-818f-a59c12835ae5(intptr,intptr)(: )
```

This is the place in code where I'm using it:
https://github.com/xamarinhq/app-acquaint/blob/master/App/Acquaint.Native/Acquaint.Native.Droid/Activities/AcquaintanceListActivity.cs#L254-L260

Here's some Xamarin Test Cloud runs that demonstrate the seemingly random nature of these errors:

https://testcloud.xamarin.com/test/acquaint-n_03ee5a38-3b21-45ac-89e1-ec2afcc6233c/

https://testcloud.xamarin.com/test/acquaint-n_e61a4094-1020-4ecc-848d-5518bd9e9bb8/

I'm not suggesting that something is wrong in the FFImageLoading implementation. I'm sure it's just something I'm doing wrong, but I'm just not sure what.

I've marked `OnBindViewHolder()` as `async` so that I can use the `IntoAsync()` method of the ImageService.
https://github.com/xamarinhq/app-acquaint/blob/master/App/Acquaint.Native/Acquaint.Native.Droid/Activities/AcquaintanceListActivity.cs#L229

**Comment by daniel-luberda** [comment]
Hi @jsauvexamarin, 

Thanks for such a detailed description. There was an issue which is fixed now. Please mind that `IntoAsync` method throws image loading exceptions (including bad connection, etc), you probably want to use `Into` method (it also isn't affected with a bug you described). 

Thanks,
Daniel

**Comment by jsauvexamarin** [comment]
Cool, thanks, I'll try `Into()`. I already tried that, actually, but I'll give it another shot. IIRC, I was seeing some other issue with the non-async call.

I'll keep an eye out for the releases that contains d7324d8. Thanks!

**Comment by jsauvexamarin** [comment]
It seems I'm still having intermittent errors, even with `Into()`. The message is the generic "FFImageLoading is unable to generate image", which it appears can be caused by a wide variety of things. (https://github.com/luberda-molinet/FFImageLoading/blob/ce1442dc8d7c9a6376da2f73b9723d726642a9ac/source/FFImageLoading.Shared/Work/ImageLoaderTaskBase.cs#L281)

I didn't mention this in my original comments, but I'm also using FFImageLoading with four other versions of the app which target Xamarin-native iOS, Xamarin.Forms iOS, Xamarin.Forms Android, and Xamarin.Forms UWP. And I have nightly XTC test runs that run against all those (except UWP). None of those other targets are having problems with loading the exact same image resources from the exact some URLs. It's just Xamarin-native Android that's giving me trouble, regardless of whether I'm using `Into()` or `IntoAsync()`.

**Comment by daniel-luberda** [comment]
I'll review you Xamarin.Android example once again and see if I missed something. 

BTW: FFImageLoading 2.1.8-pre-146 nuget which contains discussed issues released.

**Comment by daniel-luberda** [comment]
Xamarin.Android project issues may be related to this: https://github.com/luberda-molinet/FFImageLoading/pull/322

It's merger now & prerelease nuget is released.

**Comment by jsauvexamarin** [comment]
Awesome, thank you. I'll give it a try today.

**Comment by jsauvexamarin** [comment]
Woohoo! Looks like 2.1.8-pre-150 fixed it for me! Specifically, I am no longer seeing `FFImageLoading is unable to generate image` in any of my Xamarin Test Cloud runs on any of the Android devices I'm testing!

Kudos to @klaaspolinder for a great PR!
