### ISSUE TITLE
Xamarin.Forms 2.3.3.152-pre2 Could not load type 'FFImageLoading.Forms.Droid.CachedImageRenderer' 

### ISSUE THREAD

**Issue by jjchiw** [luberda-molinet/FFImageLoading#313]
Hi!

I upgraded `Xamarin.Forms` to  `2.3.3.152-pre2` and the application started to crash with.
```
System.TypeLoadException: Could not load type 'FFImageLoading.Forms.Droid.CachedImageRenderer' from assembly 'FFImageLoading.Forms.Droid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
```
after `CachedImageRenderer.Init();` I wanted to try the version  `2.3.3.152-pre2` because of this bug https://forums.xamarin.com/discussion/comment/220535 that it seems its fixed in this version https://forums.xamarin.com/discussion/77854/xamarin-forms-2-3-3-pre2#latest (43530 - "[Android] Resuming app throws IllegalStateException from fragment manager" )

I just tested in android with `FFImageLoading.Forms.Droid` version  `2.1.7`

I downgrade to this version `2.3.2.127` and it's working again...

I think it's not that important since it's a `pre` of `Xamarin.Forms`

But well just to let it know

Thanks for the great library

**Comment by adrianknight89** [comment]
Also see https://github.com/PrismLibrary/Prism/issues/770

**Comment by imkow** [comment]
yeh, I got the same problem

**Comment by kentcb** [comment]
Got the same problem and really keen to try the XF pre-release to resolve other issues. Will there be a pre-release of FFIL to address this?

**Comment by daniel-luberda** [comment]
I tried to debug it, but didn't found the cause yet. Any clues what could it be?

**Comment by daniel-luberda** [comment]
```
FFImageLoading.Forms.Droid/CachedImageRenderer.cs(15,15): Error CS0534: `FFImageLoading.Forms.Droid.CachedImageRenderer' does not implement inherited abstract member `Xamarin.Forms.Platform.Android.ViewRenderer<FFImageLoading.Forms.CachedImage,FFImageLoading.Forms.Droid.CachedImageView>.CreateNativeControl()' (CS0534) (FFImageLoading.Forms.Droid)
```

I think it's a Xamarin.Forms issue as it breaks compatibility with all other renderers.

**Comment by daniel-luberda** [comment]
FFImageLoading 2.1.8-pre-146 nuget which contains discussed issues released.
