### ISSUE TITLE
Wrong image displayed when using DownsampleHeight

### ISSUE THREAD

**Issue by Karuna30** [luberda-molinet/FFImageLoading#316]
I am using version 2.1.7 in my Xamarin Forms PCL Project. I have included the dependency in my platform projects too. I use CachedImage in my XAML to add images.

One of the things I have noticed is that as soon as I add DownsampleHeight to CachedImage I see wrong images getting displayed.

It is happening almost 90% of times when images are loaded first time and about 20% once the images are cached and the UI is reloaded.

Nothing special in my code:

XAML
```
<ffimageloading:CachedImage 
			Source="{Binding topImageURL}" 
			HeightRequest="100"
			Aspect="AspectFit"
			DownsampleHeight="100"
			/>
```
MainActivity.cs

```
FFImageLoading.Forms.Droid.CachedImageRenderer.Init();

			var config = new FFImageLoading.Config.Configuration()
			{
				VerboseLogging = false,
				VerbosePerformanceLogging = false,
				VerboseMemoryCacheLogging = false,
				VerboseLoadingCancelledLogging = false,
				FadeAnimationForCachedImages = false,
				MaxMemoryCacheSize = 100	,
				FadeAnimationDuration = 500

				//Logger = new CustomLogger(),
			};
			FFImageLoading.ImageService.Instance.Initialize(config);
```

**Comment by daniel-luberda** [comment]
`MaxMemoryCacheSize = 100` that setting is extremely low (100 bytes) and can cause FFImageLoading not working correctly. Is there any reason? I'll modify code to ignore that setting if it's set too low.

**Comment by Karuna30** [comment]
My bad, I misunderstood the parameter. After setting a higher value it works great.
