### ISSUE TITLE
Callback when an image starts downloading

### ISSUE THREAD

**Issue by reyalpsirc** [luberda-molinet/FFImageLoading#318]
I need to invoke an Action when an image starts downloading from Internet and this Action should never be invoked when the image exists on cache (either memory or disk).
I though I could access the caches through a key but, since I'm using Xamarin.Forms, I saw that the Memory cache is internal to the Assembly and so, I can't access it...

Is there some other way to invoke a callback when an image starts downloading from web?

**Comment by daniel-luberda** [comment]
Yes, just provide a custom `HttpClient` handler implementation (just override `SendAsync` method). Something like: 
```C#
var config = new FFImageLoading.Config.Configuration()
{
	VerboseLogging = false,
	VerbosePerformanceLogging = false,
	VerboseMemoryCacheLogging = false,
	VerboseLoadingCancelledLogging = false,
	Logger = new CustomLogger(),
	HttpClient = new System.Net.Http.HttpClient(new YourCustomHttpClientHandler())
};
ImageService.Instance.Initialize(config);
```

**Comment by reyalpsirc** [comment]
Hmm, but that way how do I know which object of `CachedImage` invoked the HttpClient @daniel-luberda ?

**Comment by daniel-luberda** [comment]
You could add some prefixes in urls, and then remove them in a custom http client handler implementation, etc.
