### ISSUE TITLE
Use OriginalString instead ToString() when using UrlImageSource

### ISSUE THREAD

**Issue by zjxeditor** [luberda-molinet/FFImageLoading#319]
Hi, I use "PreLoadAsync" method to get some web image. There are 25 images to be downloaded. If I call "await PreLoadAsync" for each image url, everything goes well. Finally, all the images are downloaded. However, I want to use "Task.WhenAll" method. So I add each "PreLoadAsync" call to a Task list and then call "Task.WhenAll". Many images cannot be downloaded, which is very strange. Lots of "Retry loading operation for key" debug message occurred. Then it will throw an exception "FFImageLoading is unable to generate image". What's the matter?

**Comment by daniel-luberda** [comment]
Hi @zjxeditor,

Could you make a sample project which reproduces this, so I could debug it?

**Comment by zjxeditor** [comment]
Please wait. I will fully debug the my program today to find out whether it is the library's problem.

**Comment by zjxeditor** [comment]
I find the problem. Let me make it clear:
1. Assign a image url string to CachedImage's source property
2. The ImageSourceConverter will call
    Uri uri;
    Uri.TryCreate(org, UriKind.Absolute, out uri);
    var source = Xamarin.Forms.ImageSource.FromUri(uri);
3. The the image is being loaded, it will call the following to get the final load url string
    var uriImageSource = source as UriImageSource;
    var uri = uriImageSource.Uri?.ToString();

So, the problem is, my image url contain "%3A" for authentication, while, the final load url string will just decode "%3A" to ":" automatically. Hence, the image cannot be fetched.

**Comment by zjxeditor** [comment]
Definitely, it is the .Net issue. But I think we should use "uriImageSource.Uri?.OrigianlString" instead of "uriImageSource.Uri?.ToString".

**Comment by daniel-luberda** [comment]
Yes, I also think it should be changed. Will push a commit soon. Thanks for debugging.

**Comment by zjxeditor** [comment]
I am waiting for a new NuGet package release.

**Comment by daniel-luberda** [comment]
FFImageLoading 2.1.8-pre-146 nuget which contains discussed issues released.

**Comment by zjxeditor** [comment]
Thanks.
