### ISSUE TITLE
PCL EmbeddedResource assets support

### ISSUE THREAD

**Issue by alanspires** [luberda-molinet/FFImageLoading#320]
If you try to use a EmbeddedResource from the PCL and set the loading/error...

LoadingPlaceholder = ImageSource.FromResource("Blah.Resources.placeholder_default_1.png")

you will never see the placeholder. But if you put it in the platform's resource folder and reference it by name it will work.

LoadingPlaceholder = "placeholder_default_1.png"

**Comment by daniel-luberda** [comment]
@alanspires Currently, FFImageLoading only supports native assets on Android/iOS. PCL resources are not implemented yet.

**Comment by alanspires** [comment]
Gotcha. The type being an ImageSource made me assume it would work. All good though, thanks!

**Comment by daniel-luberda** [comment]
I checked some code and it should work: 

https://github.com/xamarin/Xamarin.Forms/blob/74cb5c4a97dcb123eb471f6b1dffa1267d0305aa/Xamarin.Forms.Core/ImageSource.cs#L63-L85

As you see, that method returns a `StreamImageSource` which is supported by FFImageLoading. If it doesn't work for you, it's rather a Xamarin.Forms issue.
