### ISSUE TITLE
PNG banding on Android

### ISSUE THREAD

**Issue by kentcb** [luberda-molinet/FFImageLoading#321]
Hi,

I'm getting banding on PNG images with gradients on Xamarin.Forms Android. There is no issue with same resources on iOS, nor if I use a normal `Image` control instead of `CachedImage` (but obviously that has its own problems!).

A short while ago, this was reported in [this thread](https://forums.xamarin.com/discussion/52530/cachedimage-ffimageloading-for-xamarin-forms/p7) but I haven't been able to track down any resolution. The thread includes this sample image that exhibits the problem.

![image](https://cloud.githubusercontent.com/assets/1901832/18732072/818dc71c-809f-11e6-9032-cc503ccb76e7.png)

Is this something that can be addressed?

**Comment by daniel-luberda** [comment]
Hi @kentcb,

Did you try setting `TransparencyEnabled` to true? 

Thanks,
Daniel

**Comment by kentcb** [comment]
@daniel-luberda I hadn't, but I just tried and it made no difference.

**Comment by daniel-luberda** [comment]
This is how image is decoded in FFImageLoading: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Work/ImageLoaderTask.cs#L419
This is how image is decoded in Xamarin.Foms: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/ImageLoaderSourceHandler.cs#L17

Available options here: 
https://developer.android.com/reference/android/graphics/BitmapFactory.Options.html

Any clues?

**Comment by daniel-luberda** [comment]
@kentcb I enabled dithering with https://github.com/luberda-molinet/FFImageLoading/commit/d79f81427921f07d25b2b2b8b5c3bdce44273be6

Could you check newest prerelease nugets if it's better now? (2.1.8-pre-155)

**Comment by kentcb** [comment]
@daniel-luberda yes, this fixes it. Thanks very much!
