### ISSUE TITLE
How to add TapGestureRecognizer?

### ISSUE THREAD

**Issue by moogiis** [luberda-molinet/FFImageLoading#323]
How to add TapGestureRecognizer?

**Comment by moogiis** [comment]
LIKE THIS?
<Image HeightRequest="35"
             Source="deld.png"
             WidthRequest="35">
             <Image.GestureRecognizers>
                    <TapGestureRecognizer CommandParameter="{Binding .}" Tapped="delete" />
             </Image.GestureRecognizers>
</Image>

**Comment by daniel-luberda** [comment]
Yes, just as any other Xamarin.Forms view, but replace `Image` with `ffimageloading:CachedImage` where `ffimageloading` is your defined namespace.
