### ISSUE TITLE
[XF] [UWP] Invalid parameter relative path

### ISSUE THREAD

**Issue by tomcrusader** [luberda-molinet/FFImageLoading#324]
Now I've been developing Xamarin.Forms for a while and working with images I try to use a hiearchy whenever possible. Mostly this applies to UWP, where subfolders for images are actually allowed :)

So I was surprised to get an error from CachedImage saying somepath\subdir\image.png "is not an absolute path and relative paths are not allowed".

Before I tried to switch to FFImageLoading this worked fine. With it my app crash on UWP.
Not much of an stacktrace (FFImageLoading.Forms.WinUWP.dll GetImageSourceBinding) and PDB is not included with the NuGet package so that's all I have.

What's up?

**Comment by daniel-luberda** [comment]
@tomcrusader Did you try to use `/` instead `\`?

**Comment by tomcrusader** [comment]
Hm. Can't replicate anymore, so unsure what I was doing wrong before - both \ and / seem to work even if the source says otherwise. Curious

**Comment by daniel-luberda** [comment]
Ok, I'll close it then. If you experience it again, please reopen it and post some details. Thanks :)
