### ISSUE TITLE
Xamarin iOS is using GetTempPath instead Library/Caches folder by default

### ISSUE THREAD

**Issue by michaeldimoudis** [luberda-molinet/FFImageLoading#326]
I updated to Xamarin iOS Cycle 8 Service Release 0, and updated FFImageLoading from 2.1.7 to 2.1.8, and my images are not cached in the app. I thought it was due to the FFImageLoading update and some other changes I did, so downgraded back to 2.1.7 and it still didn't work.

So in Git I reverted back to the version that's out in the app store, with 2.1.7, and the same issue happens.

Hence why I am wondering it's an issue with Xamarin iOS Cycle 8 Service Release 0. 

I am thinking of testing another physical device later, and if it's still exhibiting the same issue, downgrading Xamarin iOS.

Has anyone else experienced this?

**Comment by daniel-luberda** [comment]
Hi @michaeldimoudis,

What do you mean by saying that images are not cached? Could you give more details? I tested `FFImageLoading` with `Xamarin iOS Cycle 8 Service Release 0` and everything works goos so far for me. Do you use any custom `FFImageLoading` config?

**Comment by michaeldimoudis** [comment]
Hi @daniel-luberda 

I've been doing some testing, and yea it seems images are re downloaded if the app is started cold, even though they are in the cache. To test this, I opened up my iOS simulator folder path to observe the cache.

I added DownloadStarted event handlers with break points, and confirmed that, even if the image is already in the cache, it downloads the image again when started from cold, and saves it as the same filename. If the app is in memory, and I scroll the list view or go to different pages with different images, if they are in the cache they don't re-download. But on a cold start they do.

I don't think this issue exists on Android. Looks like no one else is reporting it? So not sure why my set up is playing up, as I've been running FFImageLoading with the same config for a few months.

The only custom FFImageLoading config I have is HttpClient as we need an AuthenticatedHttpImageHandler, but exact same code works on Android.

Weird one :( when I have time I might download the repo and try to help solving this issue, see exactly where it's going wrong. Do you have any ideas?

Cheers.

**Comment by daniel-luberda** [comment]
My type: https://github.com/luberda-molinet/FFImageLoading/issues/239

**Comment by michaeldimoudis** [comment]
Ohhhh that rings a bell now. I'm going to have to do that. Thanks for reminding me.

**Comment by daniel-luberda** [comment]
I'll change the path in 2.2. I didn't want to do it in 2.1 as it's kind of a breaking change (all images must be re-downloaded after this)

**Comment by michaeldimoudis** [comment]
Do you have any suggestions where to put the new cache folder? And should I change anything on the Android side too? My app isn't heavily used yet, but will be in a couple of weeks time, so I can do a straight out change right now without a big impact.

**Comment by daniel-luberda** [comment]
You don't need to change anything on Android

```C#
var documents = Environment.GetFolderPath (Environment.SpecialFolder.MyDocuments);
var libdir = Path.Combine(documents,"..", "Library");
```

**Comment by michaeldimoudis** [comment]
Hi @daniel-luberda 

Unfortunately that didn't work. I believe I've always had issues with the cache in FFImageLoading, no matter how long I set the DiskCacheDuration, there always seems to be unnecessary web calls made to download already downloaded images.

I managed to get around this in my app and cached images are displayed near instant now.
The way I got around it was, my app supports people uploading photos from their device. So if they did that (I check if the file exists locally), I always set that Source to the locally stored file. Obviously when they download images the Source was always the URL. This as stated above doesn't work as expected for me. So I now also do a check if the file exists in the FFImageLoading disk cache, using MD5 filenames with a ".0" at the end (FYI mine are always .0). So now, if the image is locally, either uploaded by the user or locally in the FFImageLoading cache, I set Source to that file path. If not, only then I set the ImageSource to the url.

And now my app is extremely more faster with no unnecessary web calls made.

It's weird I've been experiencing this issue while others haven't.

So now I've set the disk cache to ~/Library/Caches/FFSimpleDiskCache with this technique, and also updated the Android app to use the same technique.

Thanks

**Comment by daniel-luberda** [comment]
@michaeldimoudis Look at this: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Shared/Cache/SimpleDiskCache.cs#L93

The part after `.` is cache validity duration in seconds. You have to set it to 0 somewhere (global config or per image view config).

**Comment by michaeldimoudis** [comment]
According to https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API it says default cache duration is 90 days. So I'm not sure that the default is working properly, as I don't specify any cache duration in my images or config, as the 90 days suits my app fine.

**Comment by daniel-luberda** [comment]
Are you sure you didn't override that setting somewhere? eg. `ImageService.Init` method?

**Comment by daniel-luberda** [comment]
The newest alpha should solve those issues. Please reopen if it didn't work for you. Thanks. The default duration is 30 days, there's an error on wiki.
