### ISSUE TITLE
how to add BlurredTransformation radius?

### ISSUE THREAD

**Issue by moogiis** [luberda-molinet/FFImageLoading#327]
```
<ffimageloading:CachedImage x:Name="ProfilePhoto"
                            DownsampleToViewSize="true"
                            HeightRequest="50"
                            Source="{Binding Image}"
                            VerticalOptions="CenterAndExpand"
                            WidthRequest="50">
                                                
                            <ffimageloading:CachedImage.Transformations>
                                    <fftransformations:BlurredTransformation /> <------------HERE
                            </ffimageloading:CachedImage.Transformations>

</ffimageloading:CachedImage>
```

**Comment by daniel-luberda** [comment]
<ffimageloading:CachedImage x:Name="ProfilePhoto"
                            DownsampleToViewSize="true"
                            HeightRequest="50"
                            Source="{Binding Image}"
                            VerticalOptions="CenterAndExpand"
                            WidthRequest="50">

                            <ffimageloading:CachedImage.Transformations>
                                    <fftransformations:BlurredTransformation Radius="20"/>
                            </ffimageloading:CachedImage.Transformations>

</ffimageloading:CachedImage>

**Comment by moogiis** [comment]
Thank you so much

**Comment by moogiis** [comment]
![capture22](https://cloud.githubusercontent.com/assets/21235622/19011520/e30edeb8-87ca-11e6-8753-9fad6c81ded5.PNG)

**Comment by moogiis** [comment]
How to fix this?
