### ISSUE TITLE
[iOS] Is there a way to load image from UIImage object?

### ISSUE THREAD

**Issue by dkornev** [luberda-molinet/FFImageLoading#328]
I want to use a transformation for my image and also want to use same API to load it by FFImageLoaded. Is it possible somehow?

**Comment by daniel-luberda** [comment]
Hi @dkornev,

I didn't understand. Could you write more details?

**Comment by dkornev** [comment]
Hi @daniel-luberda,

Sorry. I mean that it would be nice to have a LoadDrawable method to load images from iOS UIImage:

`UIImage uiImage;`
`ImageService.Instance.LoadDrawable(uiImage).Transform(new CircleTransformation()).Into(ivImage);`

Can it be done with current version?

**Comment by daniel-luberda** [comment]
Not currently, but you can do something similar: 

- Get image data `var stream = uiImage.AsPNG().AsStream();`
- Load that stream with `ImageService.Instance.LoadStream` method

**Comment by dkornev** [comment]
OK, got it.

Thank you very much for you help!
