### ISSUE TITLE
FFImageLoading exception in basic Xamarin Forms MvvmCross iOS application

### ISSUE THREAD

**Issue by ossentoo** [luberda-molinet/FFImageLoading#331]
Hi all,

I'm trying to get FFImageLoading component to work in our app. Unfortunately I get an exception:

**System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.**

and am not sure why this is.

Does anyone have any ideas?

I have knocked together a very simple iOS application that can be found here:

https://github.com/ossentoo/st-mobile

I'd be grateful for any pointers

**Comment by daniel-luberda** [comment]
At first look you're missing this: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#important

**Comment by ossentoo** [comment]
Thanks for coming back to me Daniel.

I've tried adding those command to AppDelegate, but am still getting the same exception.

See:

[https://github.com/ossentoo/st-mobile/blob/master/source/mobile/ST.iOS/AppDelegate.cs](AppDelegate.cs)

**Comment by ossentoo** [comment]
Managed to resolve this thanks.  Something must have been wrong with the xamarin project. I recreated it from scratch and when I ran it first time it worked!

thanks team. very useful tool.
