### ISSUE TITLE
No Images loaded in listview

### ISSUE THREAD

**Issue by slai47** [luberda-molinet/FFImageLoading#332]
Attempting to load images from a third party server. I am using the UWP project to test out the Windows Forms apps. I have put the:

var assembliesToInclude = new List<Assembly>()
                {
                    typeof(CachedImage).GetTypeInfo().Assembly,
                    typeof(CachedImageRenderer).GetTypeInfo().Assembly
                };
                Xamarin.Forms.Forms.Init(e, assembliesToInclude);
in the app.xaml.cs in the OnLaunched method.

I put the CachedImageRenderer.Init(); just a few lines after it.

This is my listview xaml code. The binding image is a string. I have tried using a UriImageSource also.
`<ListView
        x:Name="vListView"
        >
        <ListView.ItemTemplate>
          <DataTemplate>
            <ViewCell>
              <StackLayout 
                Orientation="Horizontal">
                <ffimageloading:CachedImage
                       Source="{Binding image}"
                       HeightRequest="200"
                       WidthRequest="200"
                       DownsampleToViewSize="true"
                ></ffimageloading:CachedImage>
                <StackLayout Orientation="Vertical">
                  <Label Text="{Binding name}"/>
                  <Label Text="{Binding battles}"/>
                </StackLayout>
              </StackLayout>
            </ViewCell>
          </DataTemplate>
        </ListView.ItemTemplate>
      </ListView>`

No images are showing up for me. What am I missing?

**Comment by daniel-luberda** [comment]
It's rather a Forms issue. Look here: https://forums.xamarin.com/discussion/58567/issue-image-in-listviews-viewcell-on-uwp

**Comment by tomcrusader** [comment]
Actually, images in a list works for me, while FFImage does not (2.1.8)

**Comment by daniel-luberda** [comment]
@tomcrusader Could test newest prerelease and see if it solves your issues? Thanks.

**Comment by tomcrusader** [comment]
@daniel-luberda Testing 2.2.0-pre-170. Works in debug nicely, but in Release / Native tool chain (x86) I just get blank where the images are suppose to be.

**Comment by daniel-luberda** [comment]
Native tool chain fix is explained here: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#windows-uwp---compile-with-net-native-tool-chain-note
