### ISSUE TITLE
Can not load cache when network is disconnected

### ISSUE THREAD

**Issue by AllenMeex** [luberda-molinet/FFImageLoading#333]
I use a URL as the image source. First, I load the image with good netwok. The image can be shown well.  Then I disconnect the network and restart App, the ImageView show Error placeholder.

The first time I load the image, it should have been cached. But why it can't be shown when the network is disconnect?

I use the FFImageLoading for Xamarin Forms package  from Nuget, version is v2.1.8.

Xamarin Studio Community
Version 6.1.1 (build 15)
Xamarin.Android
Version: 7.0.1.3 (Xamarin Studio Community)

Any help please... Thanks.

I test it with a simple project, only have a Page.

App.xaml.cs
```C#
using Xamarin.Forms;

namespace FFImageLoadingTest
{
	public partial class App : Application
	{
		public App()
		{
			InitializeComponent();

			MainPage = new FFImageLoadingTestPage();
		}

		protected override void OnStart()
		{
			// Handle when your app starts
		}

		protected override void OnSleep()
		{
			// Handle when your app sleeps
		}

		protected override void OnResume()
		{
			// Handle when your app resumes
		}
	}
}

```

FFImageLoadingTestPage.xaml
```xml
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:FFImageLoadingTest" x:Class="FFImageLoadingTest.FFImageLoadingTestPage" xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
    Title="Basic XAML Example">
	
	<ffimageloading:CachedImage HorizontalOptions="Center" VerticalOptions="Center"
			WidthRequest="300" HeightRequest="300"
			DownsampleToViewSize="true"
			Source = "http://a.hiphotos.baidu.com/zhidao/pic/item/f9dcd100baa1cd11aa2ca018bf12c8fcc3ce2d74.jpg">
		</ffimageloading:CachedImage>
</ContentPage>
```
FFImageLoadingTestPage.xaml.cs
```C#
using Xamarin.Forms;

namespace FFImageLoadingTest
{
	public partial class FFImageLoadingTestPage : ContentPage
	{
		public FFImageLoadingTestPage()
		{
			InitializeComponent();
		}
	}
}

```

I am a novice in Xamarin. If I use FFImageLoading with a wrong method? 

Thanks

**Comment by owlstack** [comment]
I'm having the same issue as this person. I will post another issue with more details.

**Comment by antonyrey** [comment]
Hi,

I'm facing the same issue here.


Thanks

**Comment by EmmanVazz** [comment]
I had this issue on iOS, I fixed it by manually setting the cache path.

**Comment by AllenMeex** [comment]
I tested it with a custom cache path, but still not work...
I tested on Android.

MainActivity.cs
```C#
namespace FFImageLoadingTest.Droid
{
	[Activity(Label = "FFImageLoadingTest.Droid", Icon = "@drawable/icon", Theme = "@style/MyTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
	public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
	{
		protected override void OnCreate(Bundle bundle)
		{
			TabLayoutResource = Resource.Layout.Tabbar;
			ToolbarResource = Resource.Layout.Toolbar;

			base.OnCreate(bundle);

			FFImageLoading.Forms.Droid.CachedImageRenderer.Init();

			var config = new FFImageLoading.Config.Configuration()
			{
				VerboseLogging = true,
				VerboseMemoryCacheLogging = true,
				DiskCache = new FFImageLoading.Cache.SimpleDiskCache("/sdcard/ccc")
			};
			FFImageLoading.ImageService.Instance.Initialize(config);

			global::Xamarin.Forms.Forms.Init(this, bundle);

			LoadApplication(new App());
		}
	}
}
```

**Comment by owlstack** [comment]
@daniel-luberda Have you taken a look at this issue for Xamarin.Forms - Android?

**Comment by daniel-luberda** [comment]
There's a new prerelease coming today or tommorow with completely redesigned core (refactored code). I'll write more details soon.

**Comment by owlstack** [comment]
Thank you so much for looking into this! Once it's up, I'll start testing and let you know how it goes.

**Comment by AllenMeex** [comment]
@daniel-luberda hi, will the new release resolve the bug?

**Comment by daniel-luberda** [comment]
@AllenMeex @owlstack 

Yes, the new version which is now released as a prerelease should solve those issues. Could you try it?
