### ISSUE TITLE
FFimageloading.transformations doesnt work on win phone

### ISSUE THREAD

**Issue by vovaromaniuk** [luberda-molinet/FFImageLoading#335]
FFimageloading.transformations doesnt work on win phone 8.1. I tried to unistall/reinstall package and added diferent links to package, but it still throws exception :"You are referencing the Portable version in your App - you need to reference the platform (iOS/Android) version".  What should I do to fix it?

**Comment by daniel-luberda** [comment]
You need to add `Xamarin.FFImageLoading.Transformations` to both, shared and platform specific projects. The `Exception` you're getting suggests that you didn't do that. Also read this: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#windows-uwp---compile-with-net-native-tool-chain-note

**Comment by vovaromaniuk** [comment]
![links](https://cloud.githubusercontent.com/assets/15131903/19310500/0c5c488e-9093-11e6-9138-4e3a475dc2e0.png)
I did it. But it doesn't helps

**Comment by daniel-luberda** [comment]
What are your projects PCL profiles?

**Comment by vovaromaniuk** [comment]
Android and WinPhone

**Comment by daniel-luberda** [comment]
- PCL profile is represented as a number
- Did you call `CachedRenderer.Init`?

**Comment by vovaromaniuk** [comment]
I have PCL profile #111.

**Comment by vovaromaniuk** [comment]
And yes, I did.

**Comment by daniel-luberda** [comment]
It's really hard to help anything more without further details. It should work. You could try to remove nuget packages and install them once again.
