### ISSUE TITLE
2.1.8 TintTransformation color is not correct

### ISSUE THREAD

**Issue by swansca79** [luberda-molinet/FFImageLoading#336]
I'm trying to use the TintTransformer to color the icons I use in my app.  However it's not working correctly on Android or iOS.  I've attached an image to show the results on both platform.  Android applies the tint and blends it with the existing color, and iOS seems to apply the tint behind the original image.

```
<ffimageloading:CachedImage Source="{Binding Icon}" DownsampleToViewSize="true" TransparencyEnabled="false" WidthRequest="40">
    <ffimageloading:CachedImage.Transformations>
        <fftransformations:TintTransformation HexColor="#389DC6" />
    </ffimageloading:CachedImage.Transformations>
</ffimageloading:CachedImage>
```

I can pretty easily achieve the desired results with a custom renderer, but I'd much rather have the benefits of the CachedImage and be able to change the colors of my images.

Custom Renderer Android Code

```
ThemeImage themeImage = e.NewElement as ThemeImage;
Control.ImageTintMode = Android.Graphics.PorterDuff.Mode.SrcAtop;
Control.ImageTintList = ColorStateList.ValueOf(themeImage.ImageColor.ToAndroid());
```

Custom Renderer iOS Code

```
 ThemeImage themeImage = e.NewElement as ThemeImage;
 Control.TintColor = themeImage.ImageColor.ToUIColor();
 if (Control.Image != null) { 
     Control.Image = Control.Image.ImageWithRenderingMode (UIImageRenderingMode.AlwaysTemplate);
 }
```

![screenshot_20161013-135023 copy](https://cloud.githubusercontent.com/assets/17572520/19363071/95abdf4e-914e-11e6-9023-ff30b8490192.png)

**Comment by daniel-luberda** [comment]
There's a new version coming soon (refactored core,  better performance).  I'll try to debug it and l include fixes to 'TintTransformation' soon.  Meanwhile,  you can could apply also alpha channel to the transformation (intead '#ffaabb'  use '#ffaabbee',  where 'ee'  is an alpha channel value.

**Comment by swansca79** [comment]
Ok so playing around in the code, if I change the ColorToTintMatrix to this, it works.  I guess that makes sense since the current method is dividing the RGBA by half to apply a tint to an actual image, where as this version is simply changing the color of the entire image.  So instead of changing TintTransformation, maybe just make a new transformation called ColorChangeTransformation and use this method?

I tried adding a custom transformation, it compiles but at runtime gets a weird error.  Are these officially supported yet?? 

```
        public static float[][] ColorToTintMatrix(int r, int g, int b, int a)
        {
            return new float[][]
            {
                new [] { r, 0f, 0f, 0f, 0f },
                new [] { 0f, g, 0f, 0f, 0f },
                new [] { 0f, 0f, b, 0f, 0f },
                new [] { 0f, 0f, 0f, a, 0f },
                new [] { 0f, 0f, 0f, 0f, 1f },
            };
        }
```

**Comment by EmmanVazz** [comment]
I am facing the same issue and neither of these methods work for me. Also I think Daniel means "instead '#ffaabb' use '#**ee**ffaabb', where 'ee' is an alpha channel value."

swansca are your images white to start off with?

**Comment by swansca79** [comment]
@EmmanVazz I tried with white or dark images.  The TintTransformation is not going to completely replace a color with the supplied color.  For my purposes of theming my app icons, the modified matrix above will work, but if you need to completely replace colors in actual images, I'm not sure how that would happen.  It will probably take a more complex color to matrix method.

**Comment by swansca79** [comment]
@daniel-luberda I was able to get a custom transformation going for color change, but then I realized it doesn't work either when I tried my specific color (#389DC6).  So I compared it to the TintTransformation and got the same results, I just extended your ColorSpaceTransformation.  When I try random images from the web it seems to work ok, so maybe it's something with my icons.  They are just material design icons from [Google](https://design.google.com/icons/).  Another side effect I noticed is the transformation doesn't respect the original image size, and the edges get a little sloppy.

![simulator screen shot oct 19 2016 8 06 12 am](https://cloud.githubusercontent.com/assets/17572520/19520232/1ef23980-95d5-11e6-8eec-71a132a7812b.png)

**Comment by swansca79** [comment]
Ok I was able to solve this by bypassing ColorSpaceTransformation in my custom transformer.  Here is the code.

**Android**
```
        public IBitmap Transform(IBitmap source)
        {
            Bitmap sourceBitmap = source.ToNative();
            var config = sourceBitmap.GetConfig();
            if (config == null) { 
                config = Bitmap.Config.Argb8888;
            }
            
            int width = source.Width;
            int height = source.Height;

            Bitmap bitmap = Bitmap.CreateBitmap(width, height, config);

            using (Canvas canvas = new Canvas(bitmap)) { 
                using (Paint paint = new Paint()) {
                    PorterDuffColorFilter cf = new PorterDuffColorFilter(HexColor.ToColor(), PorterDuff.Mode.SrcAtop);                    
                    paint.SetColorFilter(cf);
                    canvas.DrawBitmap(sourceBitmap, 0, 0, paint);
                    return new BitmapHolder(bitmap);  
                }
            }
        }
```

**iOS**
```
public IBitmap Transform(IBitmap source)
        {
            UIImage imageSource = source.ToNative();
            UIImage tintedImage = null;
        
            CGRect drawRect = new CGRect(0.0, 0.0, imageSource.Size.Width, imageSource.Size.Height);
            
            UIGraphics.BeginImageContext (imageSource.Size);
            using (var context = UIGraphics.GetCurrentContext()) {
                context.TranslateCTM(0, drawRect.Size.Height);
                context.ScaleCTM(1.0f, -1.0f);
                context.ClipToMask(drawRect, imageSource.CGImage);
                context.SetFillColor(HexColor.ToUIColor().CGColor);
                context.FillRect(drawRect);
                tintedImage = UIGraphics.GetImageFromCurrentImageContext();
                UIGraphics.EndImageContext();
                return new BitmapHolder(tintedImage);
            }
        }
```

**Comment by daniel-luberda** [comment]
@swansca79 Thanks for such detailed info. 

> When I try random images from the web it seems to work ok, so maybe it's something with my icons. They are just material design icons from Google. 

Those images are 60-70% transparent by default. Maybe it's the cause of it?

**Comment by swansca79** [comment]
Yea it may be the alpha channel on the material design images. I messed around with it for a while, but I don't know enough about the color matrix to really debug it.  I've been testing the solution I posted above, it's working really well.  It's nice not having to change the image color every time I grab a new one. 

I'm using my custom transformation in conjunction with this class so I don't have to set the transformation manually everywhere.
```
    public class ThemeImage : CachedImage
    {
        bool TransformationSet = false;
    
        public ThemeFFImage() {
            DownsampleToViewSize = true;
            TransparencyEnabled = false;
        }
        
        protected override void OnPropertyChanged(string propertyName = null) {
            base.OnPropertyChanged(propertyName);
            if (Equals(propertyName, SourceProperty.PropertyName) && !TransformationSet) {
                TransformationSet = true;
                Transformations.Add(new ColorChangeTransformation("#FF0000")); //your theme color here
            }
        }
    }
```

**Comment by daniel-luberda** [comment]
I think your solution could be a more universal one as we don't need to worry about transparency. Would you mind if I use your code to add a new type of transformation? eg. `ColorChangeTransformation`

**Comment by EmmanVazz** [comment]
@swansca79 How were you able to get a custom Transformation? The wiki is currently blank :(

**Comment by daniel-luberda** [comment]
`TintTransformation` has now a `EnableSolidColor` property. When it's enabled it will use solid color for color replacement (the same as in your custom transformations). Nuget will be published today.

**Comment by EmmanVazz** [comment]
Oh okay, I tried the prerelease yesterday and didn't find that option. I will try the new version when it is released. Thanks!
