### ISSUE TITLE
Xamarin forms xaml example not working as expected.

### ISSUE THREAD

**Issue by ossentoo** [luberda-molinet/FFImageLoading#337]
Hi,

I've got a Xaml example with a listview and FFLoadingControl.  However, I can't get the form images loading as expected.

I have tried to convert this example:

https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/ListPage.cs

I've got the example here:

https://github.com/ossentoo/st-mobile

I'm not sure why this xaml listview is not loading the images. Please can you help?

thnaks

**Comment by daniel-luberda** [comment]
Could you write more details? Do images load when you replace them with standard `Image`control from Xamarin.Forms?

**Comment by ossentoo** [comment]
thanks for responding.

I'm trying to get remote images (i.e. like you have in your example) loading into a listview control, using the most basic functionality.  When i look at the way the example is implemented where you have just code based page (ListPage.cs), all you do is set this binding:

`            listView.SetBinding<ListPageModel>(ListView.ItemsSourceProperty, v => v.Items);`

and then in ListExampleCell,

`				image.SetBinding<ListExampleItem>(CachedImage.SourceProperty, v => v.ImageUrl); `

you are binding the property.  

I'm trying to get something similar working but using Xaml, but am having trouble getting it to render as expected.

I'm using MvvmCross, but I don't think that's the main problem.  I appear to have some syntax not defined correctly in the page xaml, but I can't understand where.

thanks

**Comment by EmmanVazz** [comment]
Hello, everything works as expected. I was taking a look at your code and it seems like you missed implementation a PageModel, as the ListPage example derives from ContentPage and IBasePage<ListPageModel>. Here is his ListPageModel https://github.com/luberda-molinet/FFImageLoading/blob/ca1fa0296dc21e40f7d5f746b76fbf9c639d9d7c/samples/ImageLoading.Forms.Sample/Shared/PageModels/ListPageModel.cs . Without this v.Items evaluates to nothing, resulting in you not seeing anything.

**Comment by daniel-luberda** [comment]
@EmmanVazz Thanks for checking this! :) 👍
