### ISSUE TITLE
Different behaviour inside a Grid than Xamarin.Forms 

### ISSUE THREAD

**Issue by escamoteur** [luberda-molinet/FFImageLoading#338]
Hi Daniel,

just stumbeld upon a strange effect. I have here a reproproject.

https://github.com/escamoteur/ImageGridTest

If you change CachedImage to Image the Images fill the whole screen. When using CachedImage there is a GAP inbetween.

FYI: The with of the Columns is set at runtime in the Code behind file.

Thomas

**Comment by softclickbr** [comment]
I experienced this problem in the 1st moment that I tried FFImageLoading, exactly the same issue.

I resolved using WithRequest and HeightRequest inside ffimageloadin:CachedImage.  I hate to use absolute values, but this used grid exceptionally had 3 lines 25 dpi and 1 column 75 dpi. The Image uses 3 rows (rowspan 3), so the available space was 75x75. I put widht and height request to 75x75 and the used space comes equal as Image tag. Resolved, bad, but resolved.

**Comment by daniel-luberda** [comment]
It's probably because we're calling `InvalidateMeasute` method after image loading... and `Image` uses `InvalidateMeasureInternal` method which also calls some internal stuff and it's `internal` as name suggests. https://github.com/xamarin/Xamarin.Forms/blob/74cb5c4a97dcb123eb471f6b1dffa1267d0305aa/Xamarin.Forms.Core/VisualElement.cs#L651-L655

The only way to fix this is to use reflection.

**Comment by daniel-luberda** [comment]
@escamoteur  Could you test the newest prerelease? There were some changes to `ImageViewAsync`.

**Comment by daniel-luberda** [comment]
Hi @escamoteur,

I tested your sample and the behaviour of FFImageLoading is correct. Xamarin.Forms `Image` behaviour is incorrect though. Please notice that you've set `AspectFit` which means that whole image should be shown and that's exactly what `CachedImage` is doing. See screenshots: 

## `CachedImage` with `AspectFill`
![screenshot_1482413375](https://cloud.githubusercontent.com/assets/13569983/21427262/cfb84074-c853-11e6-88f4-162d376a2416.png)

## `CachedImage` with `AspectFit`
![screenshot_1482413402](https://cloud.githubusercontent.com/assets/13569983/21427272/e6c7af3e-c853-11e6-9d44-8524e212ce59.png)

## `Image` shows the same result for both `AspectFill` / `AspectFit`
