### ISSUE TITLE
Updated image is displayed in the app before cache duration when the image was cached previously

### ISSUE THREAD

**Issue by owlstack** [luberda-molinet/FFImageLoading#339]
That is, I have set the images to be cached for a duration of 14 days. When I first load my app, the images should be cached. Then, a day or few days later, I update the image from my remote service to a new image for that specific item. The new image is shown for that item and not the cached image. The image should be updated to the new image after 14 days right and not before? 

This happens on Xamarin.Forms.

**Comment by daniel-luberda** [comment]
Hi @owlstack,

Does it happen on Android / iOS / Windows or all of them? It can be related to this: https://github.com/luberda-molinet/FFImageLoading/issues/239

**Comment by owlstack** [comment]
@daniel.... looks like all of them. 

However, my company's project structure is: 

Xamarin.Forms: Android

Xamarin.iOS 

So it does not work for both Xamarin.Forms (Android) and Xamarin.iOS. 

Those are the only two apps we are testing with this library.

**Comment by daniel-luberda** [comment]
@owlstack The new version is coming, it has some issues fixed / rewritten core logic / improved performance. Would you mind testing it soon? I think it solves that issue too.

**Comment by owlstack** [comment]
ok let me know when the new version is out and I'll test it. Thanks :)

**Comment by daniel-luberda** [comment]
Should be fixed in `2.1.9-pre-168-core-r`. Please reopen it if doesn't work for you.
