### ISSUE TITLE
Add configuration to allow adding a placeholder when path is null

### ISSUE THREAD

**Issue by fedemkr** [luberda-molinet/FFImageLoading#340]
Hi,

thanks for this awesome library, we are using it a lot in our projects and it's great.

As an enhancement, could a configuration be added to allow having a particular placeholder (or using the ErrorPlaceholder) instead of a transparent background when the path to load the image is null?

thanks again

**Comment by daniel-luberda** [comment]
Hi @fedemkr, 

Do you use it with Xamarin.Forms or native? With Forms, you could just use custom `IValueConverter` which will return deafult file when `null` string is found.

**Comment by fedemkr** [comment]
Hi, I use it with Native

Thanks again

**Comment by molinch** [comment]
Hi @fedemkr,
Thanks for the positive feedback.
FFImageLoading should not handle such scenarios, these are very easy to handle from the app logic if you make some helper classes.
