### ISSUE TITLE
FFImage 2.1.8, ImageService.Instance.LoadUrl(url).DownloadOnly() fails on android 

### ISSUE THREAD

**Issue by nevalenny** [luberda-molinet/FFImageLoading#341]
FFImage 2.1.8
PCL
Android API 19
Samsung SM-T530

Given code snippet:

`  foreach (var coverUrl in from bag in serverBooks select bag.Cover)
            {
                ImageService.Instance.LoadUrl(coverUrl).Finish((a) =>
                {
                    System.Diagnostics.Debug.WriteLine(string.Format("File: {0}, Completed: {1}, Cancelled: {2}", coverUrl, a.Completed, a.IsCancelled));
                }).DownloadOnly();
            }`

Result log:
`File: https://dl.lecta.ru/f563f9a20ef5da8277c97b087c8c30389d0db1056397aac1a72cf4719b78f095/8125.png, Completed: False, Cancelled: False
File: https://dl.lecta.ru/79cb6945f94ee56aec073c3877c5076a5bf25aba1a33d4526a48e5c11ff0d63d/8180.png, Completed: False, Cancelled: False
File: https://dl.lecta.ru/d8b1069527527889dfbf76fed3f451e906fedc6aa78c77794d1e8ab7c03aa4ce/8260.png, Completed: False, Cancelled: False
File: https://dl.lecta.ru/9848e530f67b29ddf1384849e46835c713969d1cd2c339f065da7fea02e8957b/8123.png, Completed: False, Cancelled: False
File: https://dl.lecta.ru/3bb68aac315d6a94da92b1702a9111b92d3a6280e8f8fc89aed2ebaaeac98c7f/8261.png, Completed: False, Cancelled: False`

and then only setting CachedImage.Source property triggers loading properly.

And also after app restarting no disk cache appears to be available since images start to load again.

**Comment by owlstack** [comment]
I'm having a similar issue with DownloadOnly() and Preload(). The methods do not work on Android and iOS properly. It seems to work occasionally only. The moment when it does not work is when the images start to load but they get suck on DownloadStart() and they never finish downloading.

**Comment by daniel-luberda** [comment]
@owlstack New prerelease will fix this. All image loading logic is now in one PCL shared class. Currently, there was a lot of different image loading paths, all implemented for each platform with different ways, it was quite bug-prone. We will also have much more details about exceptions.

**Comment by daniel-luberda** [comment]
Should be fixed in `2.1.9-pre-168-core-r`. Please reopen it if doesn't work for you.
