### ISSUE TITLE
ImageService.Instance.SetPauseWork(true) appears to cancel tasks, rather then to pause them

### ISSUE THREAD

**Issue by nevalenny** [luberda-molinet/FFImageLoading#342]
FFImage 2.1.8
PCL
Android API 19

the same code snippet as previous issue (https://github.com/luberda-molinet/FFImageLoading/issues/341) results in all the tasks finish instantly with Cancelled: True when I trigger ImageService.Instance.SetPauseWork(true).

ImageService.Instance.SetPauseWork(false) subsequent call does not restore the tasks either.

**Comment by daniel-luberda** [comment]
The method name is quite misleading. It actually cancels all tasks. I think we must obsolete that method name and add some new methods for pausing / cancelling work.

**Comment by nevalenny** [comment]
Thanks for fast reply!

I would really appreciate if you can implement the initial idea since i try to improve RecyclerView performance with the recomendations from wiki - https://github.com/luberda-molinet/FFImageLoading/wiki/Advanced-Usage#scroll-high-performances

**Comment by daniel-luberda** [comment]
The original idea was to add image loading tasks once again manually. Notice this: 

```C#
      // Here you should have your custom method that forces redrawing visible list items
      _myListView.ForcePdfThumbnailsRedraw();
```

But I agree, that could be solved with a simpler way. Eg. leaving only last `N` loading tasks and cancelling the others, etc, etc.

**Comment by daniel-luberda** [comment]
It's fixed, you can test it in newest nuget prerelease.
