### ISSUE TITLE
ImageService.Instance.LoadUrl(url).DownloadOnly() not found XF

### ISSUE THREAD

**Issue by eopeter** [luberda-molinet/FFImageLoading#343]
DownLoadOnly() or DownLoadOnlyAsync() not available in shared project. How Do I call it? Using Xamarin Forms. On Latest version on Nuget as of yesterday

**Comment by daniel-luberda** [comment]
`ImageService.Instance.LoadUrl("http://myurl/myimg.jpeg").DownloadOnly();`
