### ISSUE TITLE
Web images are not loaded when a proxy is setted

### ISSUE THREAD

**Issue by ericleroy01** [luberda-molinet/FFImageLoading#344]
as explain in title, when a proxy is setted on a device, FFImageLoading does not access to web images.

this issue was detected by using CachedImage object

**Comment by daniel-luberda** [comment]
Ok. 

BTW: with newest prerelease you can configure more things (you can even replace whole `DownloadCache` implementation or use custom DataResolverFactory to use multiple path loading logic). Cheers.

**Comment by acaliaro** [comment]
@ericleroy01 I have the same problem. How have you solved it?
