### ISSUE TITLE
iOS 8.1, 8.3 forms app crash

### ISSUE THREAD

**Issue by alexpetin** [luberda-molinet/FFImageLoading#346]
Hi!

Xamarin.Forms app crashes on startup after installing Xamarin.FFImageLoading.Forms package.
Log:
----------------------
Oct 27 22:20:21 focus-mac com.apple.CoreSimulator.SimDevice.812ACCD1-26F3-438D-A00B-C64AB4F790F3.launchd_sim[25784] (UIKitApplication:com.samaritan.jericho[0xd90f][25876]): Service exited due to signal: Trace/BPT trap: 5
Oct 27 22:20:21 focus-mac.samaritan.ru SpringBoard[25798]: Application 'UIKitApplication:com.samaritan.jericho[0xd90f]' crashed.
Oct 27 22:20:21 focus-mac assertiond[25802]: assertion failed: 16B2555 12F70: assertiond + 14647 [D82D8D7B-5253-3300-B083-B6F739F68355]: 0x1
----------------------

Min iOS version the app with Xamarin.FFImageLoading.Forms  works - 9.0.

**Comment by daniel-luberda** [comment]
I've just ran sample app on older iOS versions and all is working fine. Are you sure it's FFImageLoading issue? Please try to clean project / remove all `bin` or `obj` folders and compile it once again.

**Comment by alexpetin** [comment]
Yes, I'm sure - uninstalling the package fix the problem.
I've tried your sample forms app and xamarin.ios app - the same behaviour.

Did you try 8.1?

**Comment by alexpetin** [comment]
2.1.8 -> 2.2.0-pre-170 - no difference.

**Comment by owlstack** [comment]
I think this is the same issue I am having as well. I will send you the complete stacktrace a bit later when I run it again. But yes, the app crashes on startup for Xamarin.Forms Android.

**Comment by alexpetin** [comment]
Xcode 8.0, SDK version 10.0.
There is no problems with Xamarin.Forms Android app for me.

**Comment by daniel-luberda** [comment]
Found the issue. Just call ImageService.Instance.Initialize() before using FFImageLoading. 

I'll fix this.

**Comment by daniel-luberda** [comment]
It's fixed, just download `2.2.0-pre-171` package. The exception was thrown when no custom logger was provided. Sorry for that.

**Comment by alexpetin** [comment]
Unfortunately it's not fixed.
I've tried to add "ImageService.Instance.Initialize()", tried 2.2.0-pre-173 - nothing changed.

It seems an app crashes before executing "FFImageLoading.Forms.Touch.CachedImageRenderer.Init();"
Visual studio debugger does not show any exception, just:
---
Launch succeeded. The app  'Jericho.iOS' has been successfully launched on 'iPhone 4s iOS 8.1'.
The app has been terminated.
---

Simulator device log:
---
Oct 28 15:14:25 focus-mac assertiond[28730]: assertion failed: 16B2555 12B411: assertiond + 13690 [F3233EFE-D6AB-32E3-BB3E-2CC6D0333C88]: 0x1
Oct 28 15:14:25 focus-mac com.apple.CoreSimulator.SimDevice.2183D3C9-1BE5-433A-AE56-A6FC3F8C6669.launchd_sim[28715] (UIKitApplication:com.samaritan.jericho[0x37a1][32749]): Service exited due to signal: Trace/BPT trap: 5
Oct 28 15:14:25 focus-mac.samaritan.ru SpringBoard[28726]: Application 'UIKitApplication:com.samaritan.jericho[0x37a1]' crashed.
Oct 28 15:14:25 focus-mac assertiond[28730]: assertion failed: 16B2555 12B411: assertiond + 13690 [F3233EFE-D6AB-32E3-BB3E-2CC6D0333C88]: 0x1
---

The similar thing with your sample "Simple.iOS.Sample":
---
Oct 28 16:01:44 focus-mac assertiond[28730]: assertion failed: 16B2555 12B411: assertiond + 13690 [F3233EFE-D6AB-32E3-BB3E-2CC6D0333C88]: 0x1
Oct 28 16:01:44 focus-mac com.apple.CoreSimulator.SimDevice.2183D3C9-1BE5-433A-AE56-A6FC3F8C6669.launchd_sim[28715] (UIKitApplication:com.ffimageloading.simple-ios.sample[0x6b04][34144]): Service exited due to signal: Trace/BPT trap: 5
Oct 28 16:01:44 focus-mac.samaritan.ru SpringBoard[28726]: Application 'UIKitApplication:com.ffimageloading.simple-ios.sample[0x6b04]' crashed.
Oct 28 16:01:44 focus-mac assertiond[28730]: assertion failed: 16B2555 12B411: assertiond + 13690 [F3233EFE-D6AB-32E3-BB3E-2CC6D0333C88]: 0x1
---
Second try:
---
Oct 28 16:02:27 focus-mac assertiond[28730]: assertion failed: 16B2555 12B411: assertiond + 13690 [F3233EFE-D6AB-32E3-BB3E-2CC6D0333C88]: 0x1
Oct 28 16:02:27 focus-mac.samaritan.ru SpringBoard[28726]: LICreateIconForImage passed NULL CGImageRef image
Oct 28 16:02:27 focus-mac com.apple.CoreSimulator.SimDevice.2183D3C9-1BE5-433A-AE56-A6FC3F8C6669.launchd_sim[28715] (UIKitApplication:com.ffimageloading.simple-ios.sample[0x7f51][34150]): Service exited due to signal: Trace/BPT trap: 5
Oct 28 16:02:28 focus-mac.samaritan.ru SpringBoard[28726]: Application 'UIKitApplication:com.ffimageloading.simple-ios.sample[0x7f51]' crashed.
Oct 28 16:02:28 focus-mac assertiond[28730]: assertion failed: 16B2555 12B411: assertiond + 13690 [F3233EFE-D6AB-32E3-BB3E-2CC6D0333C88]: 0x1
---

But today (updated repo?) "FFImageLoading.Forms.Sample.iOS" successfully started and works. However the log contains a lot of errors, including "assertion failed: 16B2555 12B411", maybe it can help:
---
Oct 28 16:14:15 focus-mac assertiond[28730]: assertion failed: 16B2555 12B411: assertiond + 13690 [F3233EFE-D6AB-32E3-BB3E-2CC6D0333C88]: 0x1
Oct 28 16:14:15 focus-mac.samaritan.ru SpringBoard[28726]: LICreateIconForImage passed NULL CGImageRef image
Oct 28 16:14:15 focus-mac com.apple.CoreSimulator.SimDevice.2183D3C9-1BE5-433A-AE56-A6FC3F8C6669.launchd_sim[28715] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.
Oct 28 16:14:15 focus-mac.samaritan.ru FFImageLoadingFormsSampleiOS[34180]: Xamarin.iOS: Socket error while connecting to IDE on 127.0.0.1:10000: Connection refused
Oct 28 16:14:15 focus-mac FFImageLoadingFormsSampleiOS[34180]: assertion failed: 16B2555 12B411: libxpc.dylib + 69090 [A854576A-3D30-3BF9-B2EC-B36C4B9E393C]: 0x7d
Oct 28 16:14:16 focus-mac assertiond[28730]: assertion failed: 16B2555 12B411: assertiond + 13690 [F3233EFE-D6AB-32E3-BB3E-2CC6D0333C88]: 0x1
Oct 28 16:14:16 --- last message repeated 1 time ---
Oct 28 16:14:16 focus-mac.samaritan.ru SpringBoard[28726]: [MPUSystemMediaControls] Updating supported commands for now playing application.
Oct 28 16:14:16 focus-mac.samaritan.ru FFImageLoadingFormsSampleiOS[34180]: Error loading /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib:  dlopen(/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib, 262): no suitable image found.  Did find:
		/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib: mach-o, but not built for iOS simulator
Oct 28 16:14:16 focus-mac.samaritan.ru FFImageLoadingFormsSampleiOS[34180]: Cannot find function pointer IOHIDLibFactory for factory 13AA9C44-6F1B-11D4-907C-0005028F18D5 in CFBundle/CFPlugIn 0x7c60a410 </System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin> (bundle, not loaded)
Oct 28 16:14:16 focus-mac.samaritan.ru FFImageLoadingFormsSampleiOS[34180]: Error loading /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib:  dlopen(/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib, 262): no suitable image found.  Did find:
		/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib: mach-o, but not built for iOS simulator
Oct 28 16:14:16 focus-mac.samaritan.ru FFImageLoadingFormsSampleiOS[34180]: Cannot find function pointer IOHIDLibFactory for factory 13AA9C44-6F1B-11D4-907C-0005028F18D5 in CFBundle/CFPlugIn 0x7c60a410 </System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin> (bundle, not loaded)
Oct 28 16:14:16 focus-mac.samaritan.ru FFImageLoadingFormsSampleiOS[34180]: Error loading /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib:  dlopen(/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib, 262): no suitable image found.  Did find:
		/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib: mach-o, but not built for iOS simulator
Oct 28 16:14:16 focus-mac.samaritan.ru FFImageLoadingFormsSampleiOS[34180]: Cannot find function pointer IOHIDLibFactory for factory 13AA9C44-6F1B-11D4-907C-0005028F18D5 in CFBundle/CFPlugIn 0x7c60a410 </System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin> (bundle, not loaded)
Oct 28 16:14:16 focus-mac.samaritan.ru FFImageLoadingFormsSampleiOS[34180]: Error loading /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib:  dlopen(/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib, 262): no suitable image found.  Did find:
		/System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib: mach-o, but not built for iOS simulator
Oct 28 16:14:16 focus-mac.samaritan.ru FFImageLoadingFormsSampleiOS[34180]: Cannot find function pointer IOHIDLibFactory for factory 13AA9C44-6F1B-11D4-907C-0005028F18D5 in CFBundle/CFPlugIn 0x7c60a410 </System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin> (bundle, not loaded)
---

**Comment by daniel-luberda** [comment]
I don't think it's an FFImageLoading issue anymore. I can't reproduce it. Did you try to delete all `bin` & `obj` folders from solution?

**Comment by alexpetin** [comment]
>I can't reproduce it.
Please try to start your Simple.iOS.Sample on iOS 8.1...

I've found the reason.

**Comment by daniel-luberda** [comment]
What is the reason?

**Comment by alexpetin** [comment]
Deployment Target > 7.1 = crash on start on iOS < 9.0.
The problem actually in WebP.Touch.1.0.2.

**Comment by daniel-luberda** [comment]
Ok,  thanks for the info.  So you're using webp images? What is the source? Local file?

**Comment by alexpetin** [comment]
No. Linking with webp is enough to crash on app loading.

**Comment by alexpetin** [comment]
It contains native modules compiled for 7.0.
The crash occurs before any program code - on the loading executable stage.

**Comment by alexpetin** [comment]
If you set Deployment Target to 6.0 you will see a warning about that.

**Comment by daniel-luberda** [comment]
But why would it work correctly earlier?  Webp support relies on external nuget package and it wasn't changed at all since 2.0

**Comment by alexpetin** [comment]
Probably you did not change Deployment Target, it's 6.0 by default.

**Comment by alexpetin** [comment]
6.0 gives the warning, but working :)
8.0+ gives no warning and crashes...

**Comment by daniel-luberda** [comment]
Thanks for the debug.  I'll change that then before release.  :)
