### ISSUE TITLE
UIKit Consistency error

### ISSUE THREAD

**Issue by sevontheedge** [luberda-molinet/FFImageLoading#351]
When I try to set the IsRunning property of an ActivityIndicator to false inside a CachedImage's FinishCommand I get the following error:

"UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread."

I'm currently using version 2.2.0, but have already tried updating to a pre-release version, but with same results.

Due to that error the app crashes. I attached the stack trace to help debugging. Are there any workaround for this issue?

Thanks.

[ExceptionLog.txt](https://github.com/luberda-molinet/FFImageLoading/files/562698/ExceptionLog.txt)

**Comment by daniel-luberda** [comment]
You should wrap the call with `Device.BeginInvokeOnMainThread` call. Currently, `OnFinish` is not invoked on main thread as it was affecting performance a little. I'll write about it in the release description.

**Comment by daniel-luberda** [comment]
Now, this behavior can be changed with configuration property `ExecuteCallbacksOnUIThread` (disabled by default)
