### ISSUE TITLE
Android incorrect aspect ratio while animating from placeholder to actual image

### ISSUE THREAD

**Issue by wouterroos** [luberda-molinet/FFImageLoading#353]
I have the following code in place:

```
<ContentPage.Content>
	<Grid>
		<ScrollView IsVisible="{Binding HasData}">
			<Grid>
				<Grid.RowDefinitions>
					<RowDefinition Height="260" />
					<RowDefinition Height="Auto" />
					<RowDefinition Height="Auto" />
				</Grid.RowDefinitions>
				<forms:CachedImage Aspect="AspectFill"
								   LoadingPlaceholder="{x:Static projectX:AppConstants.DetailsFallbackImage}"
								   Source="{Binding ImageUrl}" />
				<controls:Gradient Grid.Row="0" Aspect="AspectFill" />
			</Grid>
		</ScrollView>
	</Grid>
</ContentPage.Content>
```
The first time the image control is shown the loading image is shown and is then faded to the actual image. However, the aspect ratio of the actual image is not correct (see image). If I re-open the same page again the aspect ratio is correct, so I guess it has something to do with replacing the loading image with the actual image, since it doesn't show the loading image the second time due to the caching of the actual image. Is there any way to fix this? 

NOTE: The image used is a panorama which causes it to be squashed.

![image](https://cloud.githubusercontent.com/assets/5137829/19886783/160574f4-a025-11e6-9c68-5b4d96ac968d.png)

**Comment by daniel-luberda** [comment]
What version of FFImageLoading are you using?

**Comment by wouterroos** [comment]
<package id="Xamarin.FFImageLoading" version="2.2.1" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.1" targetFramework="portable45-net45+win8+wpa81" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.1" targetFramework="portable45-net45+win8+wpa81" />

**Comment by daniel-luberda** [comment]
Could you test v2.2.2 and see if it solves your issue?

**Comment by wouterroos** [comment]
I updated to `v2.2.2 `but unfortunately the issue still remains. I did some further testing and found that the issue **doesn't** occur when I set `FadeAnimationEnabled="False"`. Maybe there is something wrong with the animated transition between the LoadingPlaceHolder and the actual image?

**Comment by daniel-luberda** [comment]
Could you make a reproduction? Thanks.

**Comment by daniel-luberda** [comment]
The source of the problem is here: 
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Drawables/FFBitmapDrawable.cs#L122-L154 (returns drawable size)
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Drawables/FFBitmapDrawable.cs#L94-L97 (animation ends)

Somehow, drawable is not invalidated correctly after animation ends. Any ideas how could we fix this? 

There are some new modifications to this in 2.1.3 (prerelease). Could you test it?

**Comment by wouterroos** [comment]
I tested the `v2.2.3-pre-197` but the issue still remains. I created a repro case (using `v2.2.3`) which you can find [here](https://github.com/wouterroos/FFImageLoading-AspectRatioIssue-Repro). 

Steps to reproduce:

1. Start the app on Android
2. Click the _Navigate_ button
3. A page will be shown which shows a fallback image (square) and then fades to the actual image (wide) with the **incorrect** aspect ratio.
4. Click the _back_ button
5. Click the _Navigate_ button
6. The page will now show the actual image with the **correct** aspect ratio

Please let me know if there is anything else I can do to help.

**Comment by daniel-luberda** [comment]
I made some initial changes for that: https://github.com/luberda-molinet/FFImageLoading/commit/c048b7b838af5c702cd580ffbdc3b880c63377ae

We're going to switch to using `TransitionDrawable` internally, just the same as Glide library for Android does it. It should solve those issues.

**Comment by wouterroos** [comment]
Nice! When can we expect the fix on NuGet?

**Comment by wouterroos** [comment]
I tested `v2.2.4` and the actual image is now shown with the proper aspect ratio after fading. However, I now see that, while fading from the fallback image to the actual image, the fallback image aspect ratio quickly changes to the actual image fallback ratio (thus distorting the fallback image) before fading. I've updated the [repro case](https://github.com/wouterroos/FFImageLoading-AspectRatioIssue-Repro) to illustrate the issue.

**Comment by daniel-luberda** [comment]
Hi @wouterroos Thanks for debugging.

**Comment by daniel-luberda** [comment]
Hi @wouterroos, Thanks for debugging. The cause is here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Drawables/FFBitmapDrawable.cs#L109-L121

Any ideas how to improve that?

**Comment by ChocolateTan** [comment]
@daniel-luberda thx, help! But i still have problem with 2.3.5 . Please watch my video file, thx!
placeholder image
![imageholder](https://user-images.githubusercontent.com/3889632/38069182-9ac2a8e0-3347-11e8-8f9f-361692fe1dbb.jpg)
video file
[gg.mp4.zip](https://github.com/luberda-molinet/FFImageLoading/files/1858527/gg.mp4.zip)

**Comment by daniel-luberda** [comment]
Fixed
