### ISSUE TITLE
iTunes Store prevents app from uploading with sensitive data access

### ISSUE THREAD

**Issue by nevalenny** [luberda-molinet/FFImageLoading#357]
With update to latest FFImage release 2.2.1 (From 2.1.8) our app was prevented from uploading to iTunes Connect Testflight.

Reason: 
> We have discovered one or more issues with your recent delivery for "******". To process your delivery, the following issues must be corrected:
> 
> This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.

Usually i used "Link SDK assemblies" to get app passed (because Xamarin SDK has all the references to privacy APIs, like Siri etc), but now it does not help.

**Comment by daniel-luberda** [comment]
Wow, that's strange. I'll have to take a closer look on it.

**Comment by daniel-luberda** [comment]
Are you sure it's related to `FFImageLoading`? We don't use `NSPhotoLibrary`

**Comment by daniel-luberda** [comment]
Found the issue, it should be: `string tmpPath = Path.Combine(documents, "..", "Library", "Caches");` instead `string tmpPath = Path.Combine(documents, "..", "Library");`

**Comment by nevalenny** [comment]
Thanks for fast response and the great job you do! The control is awesome!

**Comment by james-lavery** [comment]
@daniel-luberda I'm getting this same rejection using FFImageLoading 2.2.9.

I assume your change above needed to be incorporated into a new release. Does the latest version (2.2.13) have this fixed?

**Comment by daniel-luberda** [comment]
@james-lavery Yes, it is. I deployed a lot of apps using FFImageLoading recently, none of them got rejected.

BTW: you can set custom disk cache path (`ImageService.Instance.Initialize`).

**Comment by james-lavery** [comment]
@daniel-luberda - great, thanks. I've just updated to 2.2.13 so hopefully this will now be fixed. Do you know if it wasn't fixed in 2.2.9?

**Comment by daniel-luberda** [comment]
I'm sorry, but I don't remember :)

**Comment by james-lavery** [comment]
Hmm... updating to 2.2.13 hasn't fixed the problem. I think it's another library which is triggering this iTunes Connect issue.
