### ISSUE TITLE
Not load images after the new update

### ISSUE THREAD

**Issue by Muriet96** [luberda-molinet/FFImageLoading#362]
Hi
After the Xamarin's update, my app does not load images.
Whereas before he did.
I want to know why? Please help me.

Sometimes loads the image, but after he does more.

I used CachedImageRenderer.Init();

**[Before update](https://scontent-mia1-1.xx.fbcdn.net/v/t34.0-12/14958716_10207631327641079_1707534982_n.png?oh=18a8cdafced385f7a81afcf4f3aea8d8&oe=581EBBB4)**

**[After update](https://scontent-mia1-1.xx.fbcdn.net/v/t34.0-12/14971176_10207634376557300_1829416530_n.png?oh=9199bb0106dced9e780f9e92ec935d27&oe=581E88EE)**

**Comment by daniel-luberda** [comment]
Try to uninstall packages,  remove bin, obj folders,  install them again and see if it works

**Comment by Muriet96** [comment]
I did it. 
I created a new solution and is the same result.

**Comment by softclickbr** [comment]
I saw many problems occouring when used IsVisible, Binding with some values, etc. I needed to put and retire each parameter to test the problems to load images. Anything wrong or strange, just the image not loaded. May be, your code had some error that not resulted in broken images and after the upgrade is not ignored more. Do you use XAML? What is the code?

**Comment by daniel-luberda** [comment]
Could you make a reproduction?

**Comment by Muriet96** [comment]
This is the code

```
                var Icono = new CachedImage()
                {
                    DownsampleToViewSize = true,
                    CacheDuration = TimeSpan.FromDays(30)
                };             

                var Nombre = new Label();
                var actividadAux = new Actividad();
                actividadAux = aux;
                Icono.Source = ImageSource.FromFile(aux.Icono);
                Icono.Transformations.Add(new RoundedTransformation(25));
                Nombre.Text = aux.Nombre;
                Nombre.TextColor = Color.White;
                Nombre.VerticalTextAlignment = TextAlignment.End;
                Nombre.HorizontalTextAlignment = TextAlignment.Center;
                
                gActividades.Children.Add(Nombre, column, row);
                gActividades.Children.Add(Icono, column, row);
```

**Comment by daniel-luberda** [comment]
The sample works fine for me. Did you try the newest alpha (2.2.5-pre-209 alpha)?

**Comment by daniel-luberda** [comment]
@Muriet96 Any news?

**Comment by Muriet96** [comment]
Same result :(
I noticed that does not load when I use "Xam.MediaPlugin"

**Comment by alanspires** [comment]
Try the latest pre-release. Think this was fixed. #403,#395

**Comment by daniel-luberda** [comment]
@Muriet96 Did you try the newest prerelease?

**Comment by daniel-luberda** [comment]
Please reopen if you still experience this.
