### ISSUE TITLE
FFImageLoading failed to load images

### ISSUE THREAD

**Issue by rajeshkumar1229** [luberda-molinet/FFImageLoading#364]
I am using FFImageLoading 2.2.4 for Xamarin Android application. I am using this library for getting netwrok images and cahing and it is working fine except for one scenario. FFImageLoading library is throwing runtime exception at times. If I uninstall and install the xamarin application sometimes in repetition and start this application then FFImageLoading is getting failed to load the network images. The Exception logs are as follows
11-04 12:40:13.334  9359 12425 I mono-stdout: Image loading failed: https://lpostest.xyz.com/static-test/productImages/4/29.jpg;322x0
11-04 12:40:13.334  9359 12425 I mono-stdout: System.AggregateException: One or more errors occurred. ---> System.FieldAccessException: Field `System.Net.HttpWebRequest:ResendContentFactory' is inaccessible from method `System.Net.Http.HttpClientHandler/<SendAsync>c__async0:MoveNext ()'
11-04 12:40:13.334  9359 12425 I mono-stdout: 
11-04 12:40:13.334  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x00031] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471 
11-04 12:40:13.335  9359 12425 I mono-stdout:   at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0001f] in <1f815edaaf4f498fac92ea3424f688b8>:0 
11-04 12:40:13.335  9359 12425 I mono-stdout:   at System.Net.Http.HttpMessageInvoker.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/System.Net.Http/System.Net.Http/HttpMessageInvoker.cs:68 
11-04 12:40:13.335  9359 12425 I mono-stdout:   at System.Net.Http.HttpClient.<SendAsync>__BaseCallProxy0 (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x786f36f640 + 0x0005f> in <1f815edaaf4f498fac92ea3424f688b8>:0 
11-04 12:40:13.335  9359 12425 I mono-stdout:   at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x00071] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:272 
11-04 12:40:13.335  9359 12425 I mono-stdout: --- End of stack trace from previous location where exception was thrown ---
11-04 12:40:13.335  9359 12425 I mono-stdout:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
11-04 12:40:13.335  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
11-04 12:40:13.335  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
11-04 12:40:13.335  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
11-04 12:40:13.336  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
11-04 12:40:13.336  9359 12425 I mono-stdout:   at FFImageLoading.Cache.DownloadCache+<DownloadAsync>d__13.MoveNext () [0x000c4] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:81 
11-04 12:40:13.336  9359 12425 I mono-stdout: --- End of stack trace from previous location where exception was thrown ---
11-04 12:40:13.336  9359 12425 I mono-stdout:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
11-04 12:40:13.336  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
11-04 12:40:13.336  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
11-04 12:40:13.336  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
11-04 12:40:13.336  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
11-04 12:40:13.336  9359 12425 I mono-stdout:   at FFImageLoading.Cache.DownloadCache+<>c__DisplayClass12_0+<<DownloadAndCacheIfNeededAsync>b__0>d.MoveNext () [0x00050] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:52 
11-04 12:40:13.337  9359 12425 I mono-stdout: --- End of stack trace from previous location where exception was thrown ---
11-04 12:40:13.337  9359 12425 I mono-stdout:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
11-04 12:40:13.337  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
11-04 12:40:13.337  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
11-04 12:40:13.337  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
11-04 12:40:13.337  9359 12425 I mono-stdout:   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
11-04 12:40:13.337  9359 12425 I mono-stdout:   at FFImageLoading.Retry+<DoAsync>d__0`1[T].MoveNext () [0x00047] in C:\projects\ffimageloading\source\FFImageLoading.Common\Helpers\Retry.cs:17 
11-04 12:40:13.337  9359 12425 I mono-stdout:    --- End of inner exception stack trace ---

**Comment by daniel-luberda** [comment]
Hi @rajeshkumar1229,

It's not a bug, this error is thrown when network request times out. It should be a log-only information.
