### ISSUE TITLE
Listview - Circle Transformation Border

### ISSUE THREAD

**Issue by aherrick** [luberda-molinet/FFImageLoading#366]
I'm on the latest stable bits of FFImageLoading.

I'm trying to add a border to my CircleTransformation. My ListView ItemTemplate looks like below.

The circle transformation **is** being applied, but I see no border. What's wrong here? Note I am testing with Xamarin Forms UWP

```
    public partial class GenericListItemTemplate : ViewCell
    {
        public GenericListItemTemplate()
        {
            InitializeComponent();

            img.Transformations = new List<FFImageLoading.Work.ITransformation>()
            {
                new CircleTransformation(4, "#333333")
            };

            img.LoadingPlaceholder = "https://www.google.com/favicon.ico";
            img.ErrorPlaceholder = "https://www.google.com/favicon.ico";
        }


        protected override void OnBindingContextChanged()
        {
            var item = BindingContext as GenericListItem;

            if (item == null)
                return;

            img.Source = item.ImageURL;

            base.OnBindingContextChanged();
        }
    }
```

**Comment by daniel-luberda** [comment]
Hi @aherrick,

I'll try to debug this soon. Meanwhile, this is the code responsible for drawing border: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Windows/RoundedTransformation.cs#L117-L139

Do you see anything wrong there? Maybe the extension method `ToColorFromHex` fails (and it fails back to transparent by default) https://github.com/luberda-molinet/FFImageLoading/blob/ca1fa0296dc21e40f7d5f746b76fbf9c639d9d7c/source/FFImageLoading.Windows/Extensions/ColorExtensions.cs#L26

**Comment by aherrick** [comment]
Hey thanks for the response. FYI I just tried with iOS and the border DOES show... however it seems the thickness isn't changing either.

**Comment by aherrick** [comment]
Update here. I had to make the thickness "14" for it to show. However it is very jagged in UWP. ALSO, I'm not able to see a `LoadingPlaceholder` show up, even with a simple PNG/JPG URL in UWP. `ErrorPlaceholder ` however DOES show if the image fails to load. Any thoughts there?

**Comment by daniel-luberda** [comment]
> Update here. I had to make the thickness "14" for it to show. However it is very jagged in UWP. 

It's because of this: https://github.com/luberda-molinet/FFImageLoading/issues/254. Does anyone have a good algorithm for drawing circles / elipses with anti-aliasing pixel by pixel? **Any help needed.** 

> I'm not able to see a LoadingPlaceholder show up, even with a simple PNG/JPG URL in UWP.

Could you write more details and create separate issue for that?
