### ISSUE TITLE
Is there a way to cancel all Preload requests from the PCL?

### ISSUE THREAD

**Issue by alanspires** [luberda-molinet/FFImageLoading#367]

**Comment by daniel-luberda** [comment]
Try the newest alpha. `Preload` and `DownloadOnly` now return a task, which can be cancelled (`Cancel()` method).

**Comment by alanspires** [comment]
Ok im storing all the tasks in a collection and using the Finish method to remove itself from the collection.

`                    _preloads.TryAdd(i, ImageService.Instance.LoadUrl(i, TimeSpan.FromDays(daysToCache)).WithPriority(priority).Finish((obj) => RemoveItem(i)).DownloadOnly());`

Whenever "Finish" is called the Task shows IsCompleted = false && IsCancelled = false. Shouldn't IsCompleted = true? 

This might be occurring when the image is already in the cache.

**Comment by daniel-luberda** [comment]
Yes, it should. It's a bug. It should be fixed now. Nice catch, thanks (see commit above).

**Comment by daniel-luberda** [comment]
You can test it on 2.2.5-pre-211

**Comment by alanspires** [comment]
Good to go
