### ISSUE TITLE
Initialize Cache from Bundle?

### ISSUE THREAD

**Issue by DarthDerrr** [luberda-molinet/FFImageLoading#368]
I'm working on an app which can have many images with urls known at build time. I've been encouraged to attempt to preload our image cache with many of these images when the app starts from a bundle file which will be part of our app.

Is there a recommended way to preload images which map to a url from a file?

I believe I can do this by implementing an IDownloadCache which contains an instance of DownloadCache and doing some really hackish things but that doesn't seem optimal.

**Comment by daniel-luberda** [comment]
It should be an easy to do with custom `IDataResolver` (you can set it through config). Here's the default one: 

- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Touch/DataResolvers/DataResolverFactory.cs#L20
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/DataResolvers/DataResolverFactory.cs#L20

Identifier = file path / string
Source = file type

**Comment by DarthDerrr** [comment]
@daniel-luberda I'm not really sure how the resolvers help. I ended up finding a much different way to do this - a colleague pointed out that the cache key may be the url and it turned out not hit the network for the image the first time it was used:

`ImageService.Instance.LoadFileFromApplicationBundle("testImage.png").CacheKey(testUrl).Preload();`
...
`ImageService.Instance.LoadUrl(testUrl)...Into(imgTest);`

I suspect my question wasn't clear in the first place. Now that I put it this way, does this seem like a good way to accomplish my goal?

**Comment by daniel-luberda** [comment]
I though you want to use a different loading logic, eg. if image name in url contains `someImage.png` instead loading it from web, load it from app bundle, or something similar. 

Yes, custom cache keys will solve your problem too.
