### ISSUE TITLE
Android listview fade animation not finishing

### ISSUE THREAD

**Issue by rusty21** [luberda-molinet/FFImageLoading#370]
I've got a listview that uses FFImageLoading. When the listview initially loads I have multiple cells attempting to load the same image with FFImageLoading. I've got a sample where I'm loading the same image into 7 cells. It appears though 2 of the cells are fully opaque. But the other 5 cells look mostly transparent. I can still tell it tried to load the image but the animation seems to stop before it completes. 

After testing multiple times it seems very consistent that 2 images load just fine but any additional images don't seem to animate in correctly. Setting FadeAnimation(false) seems to fix the problem but I don't want to disable fade animations.  Heres a image cropped to the image portion of the cell. Each cell is attempting to load the same sample image. As you can see all but 2 look correct the others do not. You can ignore the grey image as that cell does not have an image to load.

![badimages](https://cloud.githubusercontent.com/assets/10209880/20186146/6dadc614-a734-11e6-9592-5c5058b15513.jpg)

Using FFImageLoading version 2.2.4, current test phone: Samsung Galaxy j3 running Android 6
Issue does not appear to happen on iOS, only Android.

**Comment by daniel-luberda** [comment]
It's already fixed in current prerelease nuget :)

**Comment by rusty21** [comment]
Any feelings on when this fixed will be part of a stable build? As a temporary solution we are disabling the fade animation.

**Comment by daniel-luberda** [comment]
Max 2 days.
