### ISSUE TITLE
Best Practices for Preloading Images?

### ISSUE THREAD

**Issue by highplains** [luberda-molinet/FFImageLoading#373]
I'm trying to figure out the best way to preload a bunch of images while not interfering with the user as they navigate to screens that have to download and display images as well.

1. `ImageService.Instance.LoadUrl(url, TimeSpan.FromDays(daysToCache)).WithPriority(LoadingPriority.Lowest).DownloadOnly()`

This seems to be the most straightforward way to go about it. The assumption here is that by setting the loading priority to "Lowest" the UI will still be responsive while the user navigates to other images that need to also be downloaded. 

Scenario with Questions: 
  App loads, data store is queried for image URL's in a profile table. This queues up 100+ preloads using the "Lowest" priority and "DownloadOnly". Does preloading take up all of the download slots? If the user navigates to another screen in the app where the default priority on a CachedImage is higher does the image begin to load immediately or are we waiting for a slot to open? Also what happens if this image is already queued from the initial preload routine, does the service add it with a new priority or wait for the initially queued item to finish?

Depending on the behavior cancelling images set to preload might be beneficial, or not so just curious.

**Comment by daniel-luberda** [comment]
Hi @highplains,

`ImageService.Instance.LoadUrl(url, TimeSpan.FromDays(daysToCache)).DownloadOnly();` is enough as preloading has lowest possible priority by default (which is even lower than `LoadingPriority.Lowest`). Also local images have higher priority than http downloaded images by default.

> Does preloading take up all of the download slots? 

Up to this day: Yes. When any of the task finishes, it takes task with the highest priority as next to run. 

BUT: 

I made some modifications (see commit above)) which now prevent from starving when downloading & preloading a lot. When all slots are taken by preloading tasks, scheduler will allow additional (max of `MaxParallelTasks / 2`). The same optimization applies to loading local files, when downloading other files. 

So the answer is that with the newest prerelease you don't need to worry about it.

**Comment by highplains** [comment]
Very Cool! Thanks!
