### ISSUE TITLE
UWP pixelated image with DownsampleToViewSize

### ISSUE THREAD

**Issue by luccasclezar** [luberda-molinet/FFImageLoading#374]
Its really what the title says.

I have a xamarin.forms application with a ListView with images. These images have DownsampleToViewSize set to true and are fine in Android, but it looks like in UWP it gets downsampled to a value lower than the size of the View itself.

Also in UWP, I'm experiencing this issue:
![issuephoto](https://cloud.githubusercontent.com/assets/12024080/20197715/08b52bcc-a788-11e6-8b10-b574a7306abf.png)
I think it's because this image has opacity.

**Comment by daniel-luberda** [comment]
Hi @luccasclezar 

> I have a xamarin.forms application with a ListView with images. These images have DownsampleToViewSize set to true and are fine in Android, but it looks like in UWP it gets downsampled to a value lower than the size of the View itself.

- What is original image size?
- What is downsampled image size?
- What is image view size?


> Also in UWP, I'm experiencing this issue: issuephoto I think it's because this image has opacity.

- Could you send original image, so I could test it?
- Is the issue with transformation enabled, disabled or both?

**Comment by luccasclezar** [comment]
Hi,

> What is original image size?

I've tested with several sizes and ratios, some of them were 1600x1000, 858x536, 1400x888, 672x420, etc. The only one that displayed correctly was 1200x1500. The difference that I saw trying to understand this issue was in the ratio, as the only picture that was correct had its width smaller than its height.

> What is downsampled image size?

Sorry, I didn't look at the image size when it got downsampled and I can't look right now either. I'll update you when I can.

> What is image view size? 

It's 50x50 (Width/Height Request, so it's scaled to native size).

> Could you send original image, so I could test it?

Sorry, I don't think I can. But probably any image with this kind of glow will do (like this one http://media-s3-us-east-1.ceros.com/orange-tap/images/2015/02/17/940bc608c29100865617d8de607964d8/glowbox.png, I'll test with it as soon as I can).

> Is the issue with transformation enabled, disabled or both?

Enabled (rounded corners set to 100), I don't think I tested it with transformation disabled.

Sorry to not being able to fully help.

**Comment by luccasclezar** [comment]
Hello again, 

I noticed that this issue is still with the "more info needed" label, is this just because of short time to look into it or more info is really needed?

**Comment by daniel-luberda** [comment]
I wasn't available, so I hadn't looked into this issue yet, sorry for that. Does it still happen on newest prerelease?

**Comment by luccasclezar** [comment]
No problem, but yes, it still happens. I checked the version today and it was up to date.

**Comment by luccasclezar** [comment]
Now I noticed that this issue is happening only when the picture is in a ListView.

**Comment by daniel-luberda** [comment]
@luccasclezar I'll close this one, as FFImageLoading `DownsampleToViewSize` is based on Forms `WidthRequest`/`Width` values and we can't change its behavior. It's very easy to avoid that by using `DownsampleWidth` / `DownsampleHeight` properties instead.

**Comment by EmilAlipiev** [comment]
I am having same issue in UWP generally but some cases also in Android when it is in ListView in forms project.  for example, 
my datatemplate in listview is as below. If I dont use DownsampleToViewSize, image is display fine but when Using it, Image is pixelated. It occurs in UWP and Android. Original Image size is around 800x600

    <```
Grid RowSpacing="0" ColumnSpacing="0" InputTransparent="True"  BackgroundColor="Transparent">
        <Grid.HeightRequest>
            <OnPlatform x:TypeArguments="x:Double">
                <OnPlatform.Android>
                    <OnIdiom x:TypeArguments="x:Double" Phone="100" Tablet="150" />
                </OnPlatform.Android>
                <OnPlatform.iOS>
                    <OnIdiom x:TypeArguments="x:Double" Phone="100" Tablet="150" />
                </OnPlatform.iOS>
                <OnPlatform.WinPhone>
                    <OnIdiom x:TypeArguments="x:Double" Phone="100" Tablet="150" Desktop="200" />
                </OnPlatform.WinPhone>
            </OnPlatform>
        </Grid.HeightRequest>

        <ffimageloading:CachedImage  FadeAnimationEnabled="True"	Aspect="AspectFit"  CacheType="Disk"   BackgroundColor="Transparent" Margin="5"   CacheDuration = "120"  
                           LoadingPlaceholder="loading.gif"             RetryCount="1"   ErrorPlaceholder="exercise_thumb.png"    TransparencyEnabled = "false"   InputTransparent="True"  
                                              Source="{Binding image, Converter={StaticResource thumbnailConvertor}}"
                            />
```
