### ISSUE TITLE
FadeAnimationForCachedImages = true doesn't seem to work.

### ISSUE THREAD

**Issue by highplains** [luberda-molinet/FFImageLoading#376]
Here is a demo video

https://www.dropbox.com/s/z5qu1802b01bkv6/NoFadeAnimation.mov?dl=0

As you can see the images are cached but they just slam right in when they load, no animation. Also I did step thru and verify that FadeAnimation = true before Source is assigned.

**Comment by Puffdot** [comment]
"FadeAnimationForCachedImages = false" also does not work (tested on iOS 10.0). Result: The images fade in if they are in disk cache, but not if they are in RAM cache.

"FadeAnimationEnabled = false" does work.

I've tried FFImageLoading version 2.2.4 and 2.2.5. It used to work with 2.1.8.

**Comment by daniel-luberda** [comment]
![screen shot 2016-11-12 at 18 40 49](https://cloud.githubusercontent.com/assets/13569983/20239757/35177eb4-a908-11e6-8194-9c39f43cd163.png)
You're just setting it wrong. Config must always be initialized with `ImageService.Instance.Initialize(config);` method.

**Comment by alanspires** [comment]
Lol right on

**Comment by alanspires** [comment]
ImageService.Instance.Initialize(new Configuration {
FadeAnimationForCachedImages = true });

Still seems to have no effect.

**Comment by daniel-luberda** [comment]
Can you make a reproduction? I just tested on sample app from repository and it works good.

**Comment by daniel-luberda** [comment]
@alanspires Any news?

**Comment by alanspires** [comment]
No good news, looks like I'm going to have to burn a day creating repos.

**Comment by daniel-luberda** [comment]
If you can provide more details, I'll also try to help.

**Comment by alanspires** [comment]
Let me grab some caffeine and I'll work on the Preload UI thread, this and "Picky" image loading. Cheers.

**Comment by alanspires** [comment]
It appears that when an image is loaded from Url or Disk -> Memory -> Image the animations work correctly (Generating/retrieving image). If the image is already in the memory cache (Image loaded from cache) then the animation doesn't happen anymore.

So to clarify is this fade animation only suppose to happen on intial load/appearing into the memory cache? Or does "FadeAnimationForCachedImages" also suppose to include images that already exist in the memory cache?

**Comment by alanspires** [comment]
Here is a video demo

https://www.dropbox.com/s/25beadqlj1mkkx5/fadeanimation.mov?dl=0

As you can see as I scroll down and the images are fetched from the disk cache the animation plays. As I scroll back up which reloads the images from the RAM cache the animations no longer display.

**Comment by alanspires** [comment]
@Puffdot I'm seeing the same thing

**Comment by Puffdot** [comment]
I was assuming that "FadeAnimationForCachedImages" was for images cached in local storage/disc. If "FadeAnimationForCachedImages" is only meant for RAM-cached images, then it looks like it's working correctly.

If this is the case, I would like an option to disable the fade animation for images cached in local storage, while keeping fading when loading from a URL.

**Comment by alanspires** [comment]
> I was assuming that "FadeAnimationForCachedImages" was for images cached in local storage/disc. If "FadeAnimationForCachedImages" is only meant for RAM-cached images, then it looks like it's working correctly.

@Puffdot My testing has shown that "FadeAnimationForCachedImages" works for new downloads and Disk cache but does not work once the image is loaded into RAM cache.

**Comment by daniel-luberda** [comment]
@highplains @Puffdot Is the behaviour correct in the newest prerelease? There were some issues fixed  that could affect this one too.

**Comment by Drutol** [comment]
Hello, I'm experiencing the same issue and this prerelease build doesn't seem to help. 
I couldn't get these animation to work at all though :( (Android 5.0+)

**Comment by daniel-luberda** [comment]
More info here: https://github.com/luberda-molinet/FFImageLoading/issues/536

Let's move to that thread.
