### ISSUE TITLE
InvalidOperationException - TaskCompletionSource.SetException

### ISSUE THREAD

**Issue by keshavkaul** [luberda-molinet/FFImageLoading#378]
Getting an exception of type System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
This happened when iOS device was offline. 
I'm using library version 2.1.7

Stack trace from Hockey App - 
> System.Threading.Tasks.TaskCompletionSource<TResult>.SetException(Exception exception)
FFImageLoading.TaskParameterExtensions.<>c__DisplayClass11_0.<IntoAsync>b__0(Exception ex)
FFImageLoading.Work.ImageLoaderTaskBase.<>c__DisplayClass51_2.<ConfigureParameters>b__3()
CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context)
CoreFoundation.DispatchQueue.static_dispatcher_to_managed(intptr)(wrapper native-to-managed)
UIKit.UIApplication.UIApplicationMain(int, string[], intptr, intptr)(wrapper managed-to-native)
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName)
iOS.Application.Main(string[] args)

**Comment by daniel-luberda** [comment]
Hi @keshavkaul  2.1.7 is quite old release. It's already fixed now.

**Comment by keshavkaul** [comment]
@daniel-luberda Thanks, which version has the fix?

**Comment by daniel-luberda** [comment]
I don't remember but I would suggest using the newest one, it has a better performance.
