### ISSUE TITLE
Memory cache - Image Pinning to prevent eviction of specific images

### ISSUE THREAD

**Issue by alanspires** [luberda-molinet/FFImageLoading#381]
Is there a way to "pin" images so they are never removed from the memory cache? I noticed that local images sometimes reload from disk which causes them not to display momentarily. This create delays in things like dashboard images which looks funny. Thanks!

**Comment by daniel-luberda** [comment]
Currently, there's no such feature. What OS?

**Comment by alanspires** [comment]
iOS so far.

**Comment by molinch** [comment]
@alanspires This wouldn't be so hard to do if you are interested to implement it :)

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/859
