### ISSUE TITLE
Images sometimes don't load on android

### ISSUE THREAD

**Issue by rusty21** [luberda-molinet/FFImageLoading#382]
Alright so I'm still seeing this error occur on android and it causes images not to get loaded into image views. 

    Image loading failed: https://s3.amazonaws.com/fanlete/uploads/dee371d0c35a816d22b067d8862b9cfd2db062c8.png System.NullReferenceException: Object reference not set to an instance of an object.
    at FFImageLoading.Collections.StrongLruCache`2[TKey, TValue].Add (TKey key, TValue value, System.Boolean overwrite) [0x000ae] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Collections\StrongLruCache.cs:146 
    at FFImageLoading.Collections.StrongLruCache`2[TKey, TValue].Add (TKey key, TValue value) [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Collections\StrongLruCache.cs:113 
    at FFImageLoading.Cache.ReuseBitmapDrawableCache.Add (System.String key, FFImageLoading.Drawables.ISelfDisposingBitmapDrawable value) [0x0006a] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:352 
    at FFImageLoading.Cache.ImageCache.Add (System.String key, FFImageLoading.Work.ImageInformation imageInformation, FFImageLoading.Drawables.ISelfDisposingBitmapDrawable bitmap) [0x00042] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ImageCache.cs:95 

I figured to track this down I was going to need to download the FFImageloading source and add it to my project so I could step through the code and figure out where things were going wrong. Here's what I think I've learned. The error occurs in this block of code in StrongLruCache.cs

	145         while (CheckEvictionRequired()) {
	146		OnWillEvictEntry(list.First.Value, dict[list.First.Value]);
	147
	148		evictions = evictions ?? new Dictionary<TKey, TValue>();
	149		evictions[list.First.Value] = dict[list.First.Value];
	150
	151		dict.Remove(list.First.Value);
	152		list.RemoveFirst();
	153
	154		raiseEntryRemovedDueToEviction = true;
	155	    }

The error occurs on line 146. The LinkedList<T> list variable is empty. So list.First is null and list.First.Value throws the null reference exception error.

You can correct me if I'm wrong but what it appears is happening is the StrongLruCache class is a base class for ByteBoundStrongLruCache. This class I believe attempts to keep track of the number of total bytes in the StrongLruCache. 

In the ByteBoundStrongLruCache there is an override for CheckEvictionRequired() which looks like:

	protected override bool CheckEvictionRequired()
	{
		lock (monitor) {
			if (current_cache_size > high_watermark) {
				has_exceeded_high_watermark = true;
				return true;
			} else if (has_exceeded_high_watermark && current_cache_size > low_watermark) {
				return true;
			}
			has_exceeded_high_watermark = false;
		}
		return false;
	}

To me this basically is saying if we exceeded the high water mark keep saying we need to evict entries until we've reached the low water mark. The logic here seems sound. It appears as though the variable current_cache_size is somehow not correctly keeping track of the actual number of bytes held onto by the StrongLruCache. When the null reference exception is generated the LinkedList<T> list is empty, and current_cache_size is greater than low_watermark. If the LinkedList is empty then it stands to reason that current_cache_size should also be 0. 

The effect of all of this is that the ByteBoundStrongLruCache keeps telling the StrongLruCache to evict entries when there are no entries to evict, causing the null reference exception. 

Testing and Moto g Android 5.1 with VS2015. If theres anything else you need from me let me know.

**Comment by daniel-luberda** [comment]
That's some impressive debugging, thanks for that - it helped a lot. I did some changes (see above). I replaced whole LRUCache implementation. Could you test it?

**Comment by rusty21** [comment]
Been testing on various phones and views and things are looking good. I haven't had a single image throw an exception.

**Comment by daniel-luberda** [comment]
That's really nice! :)

**Comment by daniel-luberda** [comment]
I've made some more changes to android memory cache.
