### ISSUE TITLE
WebP.Touch iOS Failed to resolve

### ISSUE THREAD

**Issue by mfranc28** [luberda-molinet/FFImageLoading#383]
In iOS when I compile I get this error: 
"Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to resolve assembly: 'WebP.Touch, Version=1.0.5923.35383, Culture=neutral, PublicKeyToken=null"

**Comment by mfranc28** [comment]
Seems resolved when I downgrade component version to prevoious release

**Comment by daniel-luberda** [comment]
@mfranc28 What is your project Target Version?

**Comment by mfranc28** [comment]
Android 6

Best.

Michelangelo Franco
Xamarin Certified Mobile Developer
michelangelo.franco@gmail.com<mailto:michelangelo.franco@gmail.com>



Il 22 nov 2016 3:48 PM, "Daniel Luberda" <notifications@github.com<mailto:notifications@github.com>> ha scritto:

@mfranc28<https://github.com/mfranc28> What is your project Target Version?

**Comment by shnaz** [comment]
Having the same issue, and @mfranc28's workaround doesnt work for me.

Error MT2002: Failed to resolve assembly: 'WebP.Touch, Version=1.0.5923.35383, Culture=neutral, PublicKeyToken=null' (MT2002) (MyApp.iOS)

**Comment by jlord-ifs** [comment]
I'm also experiencing this exact issue and seem to be unable to resolve it.

**Comment by sebastianhaas** [comment]
Same issue here. I had to uninstall `FFImageLoading` first, manually select `WebP.Touch` and then `FFImageLoading` again. After that it worked, although it seems I have to repeat that process once in a while 🙄

**Comment by daniel-luberda** [comment]
- Update Webp package to the newest version
- Clean build & remove all `bin` / `obj` project folders.
- Rebuild
