### ISSUE TITLE
InvertColorMatrix bug?

### ISSUE THREAD

**Issue by 3-50** [luberda-molinet/FFImageLoading#384]
I created 3 png files: 8 bit, 24 bit and 32 bit.  Applying "InvertColorMatrix" function. File png 8bit reverse wrong. The program paint.net is inverted correctly.
![image](http://i.imgur.com/t3cT12A.png)

FFImageLoading v2.2.5, v2.2.6-pre-233

**Comment by 3-50** [comment]
after using "new TintTransformation(226,255,0,128)"
![image](http://i.imgur.com/L2y5Ek6.png)

**Comment by daniel-luberda** [comment]
It's the code responsible for:
- ColorSpace transformation, which is used by `TintTranformation` by default: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Windows/ColorSpaceTransformation.cs#L86-L124
- `TintTranformation` with `EnableSolidColor=true` https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Windows/TintTransformation.cs#L76-L102
- `GetPixelAsInt`: https://github.com/luberda-molinet/FFImageLoading/blob/9995530ff03cf456eb3769eaf1b982f3790dcf2a/source/FFImageLoading.Windows/Work/BitmapHolder.cs#L51-L60

Any clues what that might be?

**Comment by 3-50** [comment]
8 bit PNG can have no more than 256 colors. A part of the PNG file structure holds pointers to 256 colors and then each pixel in the image gets its color from one of those pointers. Thus each pixel only consumes one bytem its 0-255 value pointing to its color on the palette. On the other hand, a 32 bit PNG is 4 bytes per pixel and each pixel can represent a different ARGB color value.

**Comment by daniel-luberda** [comment]
It should be fixed in the newest version. Please reopen if it's still happening.
