### ISSUE TITLE
Simple usage questions

### ISSUE THREAD

**Issue by EmmanVazz** [luberda-molinet/FFImageLoading#385]
I have looked at the source code but can't seem to find easy ways to do these two task.

1) Can you set the Forms Cached Image to not cache an image? I have tried setting the CacheDuration to zero and that didn't work. My current solution is to create a SucessCommand that calls CachedImage.InvalidateCache for that image. 

2) Is there a way to check if something is already in the cache? I am preloading a bunch of images that might have already been preloaded, not sure since the previous preload might have fail or not have had time to run. FFImage resolves these correctly but you can notice a glitch in the apps UI so maybe I can detect if I need to send it to FFImage if it has already been preloaded.

**Comment by daniel-luberda** [comment]
> Can you set the Forms Cached Image to not cache an image? I have tried setting the CacheDuration to zero and that didn't work. My current solution is to create a SucessCommand that calls CachedImage.InvalidateCache for that image. 

Not currently, I'll try to add `None` to `CacheType` enum / property. You can only disable disk cache with `CacheType=CacheType.Memory` now.

> Is there a way to check if something is already in the cache? I am preloading a bunch of images that might have already been preloaded, not sure since the previous preload might have fail or not have had time to run. FFImage resolves these correctly but you can notice a glitch in the apps UI so maybe I can detect if I need to send it to FFImage if it has already been preloaded.

- There's no harm with calling `Preload` multiple times for the same item. If the item is already in cache, preloading will simply not do anything.
- You can check it with:
  - `ImageService.Config.MemoryCache.Get(string key)` for memory cache. It will return null when not found.
  - `ImageService.Config.DiskCache.ExistsAsync(string key)` for disk cache.

**Comment by EmmanVazz** [comment]
Actually CacheType. Memory makes more sense now that I think of it, thanks I will use that. 
Also I know that it doesn't do harm but ImageService.Config.DiskCache.ExistsAsync(string key) is what I am looking for. Thanks!

**Comment by daniel-luberda** [comment]
One more thing I forgot to mention, keys for disk cache are encoded representation, so you should call it like that: 

`var key = ImageService.Config.MD5Helper.MD5(yourNormalKey);`
