### ISSUE TITLE
Preload Blocking

### ISSUE THREAD

**Issue by alanspires** [luberda-molinet/FFImageLoading#386]
ImageService.Instance.LoadUrl(i, TimeSpan.FromDays(10)).DownloadOnly();

Must be called from the UI thread or it blocks, this seems counter intuitive to the concept of preloading which ideally should happen in the background.

Thanks!

**Comment by EmmanVazz** [comment]
Are you trying to preload the image for future use? If so you should be using this method instead https://github.com/luberda-molinet/FFImageLoading/wiki/API#preload

**Comment by daniel-luberda** [comment]
> Must be called from the UI thread or it block

Are you sure? I don't think it's the requirement as preloading works as any other image loading task. Does it throw exceptions? How do you know it requires UI thread? Could you make a reproduction?

**Comment by alanspires** [comment]
He is some ugly code in a video that demos this. You can see that On initial run inside of "BeginInvokeOnMainThread" everything goes fine. But once that is commented out everything locks/blocks.

https://www.dropbox.com/s/82obdqwsb1k2hsj/PreloadUI.mov?dl=0

**Comment by alanspires** [comment]
I've seen this before in lib's that use ConfigureAwait(false) heavily, but I'm not sure what it is.

**Comment by alanspires** [comment]
@EmmanVazz .Preload() loads into the memory cache as well, I am trying to preload into disk cache and let the lib handle loading into memory cache based off how the user interacts with the app.

**Comment by EmmanVazz** [comment]
Hmm maybe we need another parameter for Preload to tell it to just store is in disk cache? I have an app that has a similar format and I think I would like it to preload just into disk as well, kind of skipped my mind that Preload() may cache to memory.

**Comment by alanspires** [comment]
I believe .DownloadOnly() has the desired effect.

**Comment by daniel-luberda** [comment]
@EmmanVazz You have `DownloadOnly` for that, which is a shortcut for `Preload` with `CacheType=CacheType.DiskOnly` specified.

@alanspires Could you test the newest alpha? 2.2.6-pre-241

**Comment by EmmanVazz** [comment]
@daniel-luberda @alanspires Okay thanks.

**Comment by alanspires** [comment]
2.2.6-pre-241 is working.

**Comment by daniel-luberda** [comment]
Cool, could you test the other issue with it?

**Comment by alanspires** [comment]
My apologizes I had a "return;" in the routine. I am still having the same effect in latest pre release

**Comment by daniel-luberda** [comment]
Could you paste the exceptions stack trace when the error occurs?

**Comment by alanspires** [comment]
Sure, not an exception per say, thread block, but here is the call stack on the block.

`CoreFoundation.DispatchQueue.dispatch_sync_f() in 
CoreFoundation.DispatchQueue.DispatchSync(System.Action action) in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/src/CoreFoundation/Dispatch.cs:393
FFImageLoading.Helpers.MainThreadDispatcher.Post(System.Action action) in 
FFImageLoading.Helpers.ScaleHelper.<>c.<.cctor>b__3_0() in 
System.Lazy<System.nfloat>.CreateValue() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/Lazy.cs:437
System.Lazy<System.nfloat>.LazyInitValue() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/Lazy.cs:388
System.Lazy<System.nfloat>.get_Value() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/Lazy.cs:339
FFImageLoading.Helpers.ScaleHelper.get_Scale() in 
FFImageLoading.Work.PlatformImageLoaderTask<object>..ctor(FFImageLoading.Work.Target<UIKit.UIImage,object> target, FFImageLoading.Work.TaskParameter parameters, FFImageLoading.ImageService imageService, FFImageLoading.Config.Configuration configuration, FFImageLoading.Helpers.MainThreadDispatcher mainThreadDispatcher) in 
FFImageLoading.TaskParameterExtensions.CreateTask<object>(FFImageLoading.Work.TaskParameter parameters, float imageScale, FFImageLoading.Work.Target<UIKit.UIImage,object> target) in 
FFImageLoading.TaskParameterExtensions.Preload(FFImageLoading.Work.TaskParameter parameters) in 
FFImageLoading.TaskParameterExtensions.DownloadOnly(FFImageLoading.Work.TaskParameter parameters) in 
RollRandom.Helpers.PreloadHelper.PreloadExperiences() in /Users/alan/Dropbox/Projects/RollRandom/RollRandom/Helpers/PreloadHelper.cs:39
System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(RollRandom.Helpers.PreloadHelper stateMachine) in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1089
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, RollRandom.Helpers.PreloadHelper state, bool preserveSyncCtx) in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, RollRandom.Helpers.PreloadHelper state, bool preserveSyncCtx) in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904
System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1070
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, System.Threading.Tasks.Task currentTask) in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:821
System.Threading.Tasks.Task.FinishContinuations() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3624
System.Threading.Tasks.Task.FinishStageThree() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2366
System.Threading.Tasks.Task.FinishStageTwo() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2339
System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted) in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2239
System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task currentTaskSlot) in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2834
System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2760
System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2707
System.Threading.ThreadPoolWorkQueue.Dispatch() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:854
ObjCRuntime.Runtime.ThreadPoolDispatcher(System.Func<bool> callback) in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/src/ObjCRuntime/Runtime.cs:238
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1206`

**Comment by mike-rowley** [comment]
A week ago I finally got back to an app I had been working on a couple months back, when I ran it on Android no issues, when I ran it on IOS it stalled at the splash screen and the app never loaded.  It took me a week to back trace the issue to the Preload function being kicked off by a Task.Factory.StartNew
I happened across this post this morning and switched the call to a Device.BeginInvokeOnMainThread and the app loads properly.

There is certainly something that is creating a blocking if Preload is not called from the UI Thread.  I was also getting no exception thrown, the app simply stalled indefinitely.

The first thing I did a week ago was create a stand alone test, which didnt fail as I wasnt preloading.  I have updated that stand alone project with the code that works and fails in Page1.cs
https://www.dropbox.com/s/r6saqxicrosatc0/2016-11-16%20-%20CachedImage.zip?dl=0

Let me know if there is anything else I can do to help with this issue.
Thanks
M

**Comment by alanspires** [comment]
After downloading the source, updating FFImage and my project to use the latest stable Forms nuget, I can no longer re produce this, hmmmmm. @mike-rowley  what version of Forms are you running?

**Comment by alanspires** [comment]
Def not a version issue. Found it while debugging. #400

**Comment by alanspires** [comment]
@mike-rowley PR tested with your repo.

**Comment by daniel-luberda** [comment]
You can download newest prerelease which has the PR included (thanks @alanspires)
