### ISSUE TITLE
LoadingPlaceholder not showing in first cell of ListView (Xamarin.Forms)

### ISSUE THREAD

**Issue by shineon84** [luberda-molinet/FFImageLoading#389]
Hi, I have a problem using FFImageLoading with Xamarin.Forms.
I have a ListView, where every cell has an CachedImage. The source of this images is a http url.

In the cell, I've setted a LoadingPlaceholder and a ErrorPlaceholder.

In iOS everything is right. 
But in Android, when the ListView is showed, every cell has a LoadinPlaceholder (this is correct, because the images of the cells must be downloaded), except for the image of the first cell, which is empty (white).

This problem appear only the first time I open the listview. If I go back and then open again the listview, everythig is right (even the first cell is showing the LoadingPlaceholder image).

How can I solve this problem?
Thank you!

**Comment by alanspires** [comment]
I've been seeing something similar in iOS as well.

#387

**Comment by daniel-luberda** [comment]
Is it possible I could get some reproduction?

**Comment by daniel-luberda** [comment]
@shineon84  Do you still experience it on the newest prerelease?

**Comment by daniel-luberda** [comment]
@shineon84 Any news?

**Comment by rickgregory1905** [comment]
I don't know if it is related or not but I can reproduce similar behavior. When I stay at 2.1.8, the placeholder is presented as expected. But when I upgrade to 2.2.* the placeholder fails to render. I was looking over the BikeSharing360 Microsoft sample at https://github.com/Microsoft/BikeSharing360_MobileApps. You can pull that project, unzip it and run it. Keeping the FFImageLoading at 2.1.8 will render the placeholder. Upgrading to 2.2.* will cause the placeholder to not render.

**Comment by daniel-luberda** [comment]
@rickgregory1905 Sample app doesn't work for me as I don't have any login credentials. Do you have any other reproduction, so I could try to fix this?

**Comment by rickgregory1905** [comment]
I should have thought about that. The backend and everything needs to be deployed. Let me see if I can scale down a reproduction.
