### ISSUE TITLE
List Recycling Mixed Images where some rows have no image

### ISSUE THREAD

**Issue by markmni** [luberda-molinet/FFImageLoading#392]
Hi,
 
This might be similar to #354, which was about images in a list with recycling being mixed up. Thank you for your fix there, it did solve that problem.
 
I've noticed one other scenario though, and that is if some items in the list should not have an image set, the images for the items which are intended to be blank can contain the images for other rows, after scrolling.
 
I've created a repro for this with FFImageLoading 2.2.5 [here](https://github.com/markmni/FFImageTesting), where I am loading images from a local webserver only for even numbered rows, but the results can be like below.
 
![image](https://cloud.githubusercontent.com/assets/736783/20562405/530325d8-b17b-11e6-92db-54170681179b.png)
 
Many thanks for any guidance.

**Comment by daniel-luberda** [comment]
You should cancel previous image loading when using recycler views:

```C#
    IScheduledWork _imageLoading;

    public override View GetView(int position, View convertView, ViewGroup parent)
    {
        var view = convertView ?? _context.LayoutInflater.Inflate(Resource.Layout.ListItem, null);

        var item = _items[position];

        view.FindViewById<TextView>(Resource.Id.Itemname).Text = item.ToString();

        var imageView = view.FindViewById<ImageViewAsync>(Resource.Id.icon);

        _imageLoading?.Cancel();
        imageView.SetImageDrawable(null);


        if (item%2 == 0)
        {
            _imageLoading = ImageService.Instance.LoadUrl($@"http://192.168.0.33:8011/{item}.png").Into(imageView);
        }

        return view;
    }
```

**Comment by daniel-luberda** [comment]
Please
