### ISSUE TITLE
Bitmap too large to be uploaded into a texture 

### ISSUE THREAD

**Issue by NVentimiglia** [luberda-molinet/FFImageLoading#394]
11-24 09:37:08.974 W/OpenGLRenderer(24176): Bitmap too large to be uploaded into a texture (4160x2340, max=4096x4096)

Getting this spammed into my output. Does FFImage not support dynamic resizing of content ? Should we be handling this manually ?

**Comment by molinch** [comment]
You can either specify the downsample width/height, or when using Xamarin Forms, set `DownsampleToViewSize` to true.

**Comment by flchaux** [comment]
I encounter the same issue and DownsampleToViewSize doesn't seem to work to prevent the error.

**Comment by NVentimiglia** [comment]
@flchaux This fixed the issue for me. What type of image is this ? how are you using the control ?
