### ISSUE TITLE
DiskCacheDuration is always Zero for Image Loaded via URL in XAML 

### ISSUE THREAD

**Issue by Karuna30** [luberda-molinet/FFImageLoading#396]
I tried to debug and found that my DiskCacheDuration is never honoured. 

DownloadCache
```
var duration = parameters.CacheDuration.HasValue ? parameters.CacheDuration.Value : configuration.DiskCacheDuration;
```
Task Parameters have Cache Duration value of Zero and not null.
I am not setting it anywhere in my code.

I am still getting used to C#, but I guess the problem is in setting CacheDuration in CachedImage.

**Comment by MrClockOff** [comment]
Hi there,

I can confirm the same behaviour on Windows 8.1. When I navigate to cache folder \TempState\FFSimpleDiskCache all files have *.0 extension which means files are cached for 0 days. Setting CacheDuration in XAML individually for each item does the trick.

**Comment by bmacombe** [comment]
I noticed the same problem in a UWP Xamarin Forms app.  Ignored the global setting, but worked when the property was set on the control.  I subclassed CachedImage as a work around.

**Comment by daniel-luberda** [comment]
Nice catch! It's fixed now. Thanks!
