### ISSUE TITLE
Blocked UI thread with BlurredTransformation?

### ISSUE THREAD

**Issue by EmmanVazz** [luberda-molinet/FFImageLoading#397]
I have a xamarin forms project where I am apply a blurred transformation to the loading placeholder image and then remove the transformation on SuccessCommand. 

I am playing with the iOS project and notice that the first time loading up this view takes a while, after the first time it is faster. I tried my own blurred image render and got the same affect when copying the BlurredTransformation code. That code runs on the UI thread so I believe that is why sometimes it take a while for the view to render. I found [this](https://github.com/TheRealAdamKemp/BlurredImageTest/blob/master/iOS/BlurredImageRenderer.cs).  It seem to only run on the UI thread to apply the new image, would something like that be better?

I tried reproducing this issue with your sample project but had no luck. Has one else ran into this?

**Comment by alanspires** [comment]
@EmmanVazz so everything is working you are just trying to increase the performance of this?

**Comment by EmmanVazz** [comment]
Correct as it seems to lag a bit for me.

**Comment by alanspires** [comment]
Why don't you download the project and test it with the other code. If it's better submit a PR.

**Comment by EmmanVazz** [comment]
I tried reproducing my issue with the sample FF project really quick but no luck. When I have more time I can try changing to code to see if I can get better performance. Just wanted to see if anyone had similar issues or recommendations first.

**Comment by daniel-luberda** [comment]
@EmmanVazz Blur transformations are generally quite resources heavy operations. Current implementation doesn't use UI thread at all, see: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Touch/BlurredTransformation.cs#L33-L42

Maybe thing could be improved by tuning `PriorityRequestLow` property, eg.

`using (var context = CIContext.FromOptions(new CIContextOptions { UseSoftwareRenderer = false, PriorityRequestLow = true, }))`

Anyone willing to test it?

**Comment by EmmanVazz** [comment]
I will try it when I have some time.

**Comment by EmmanVazz** [comment]
I will close this issues just to clear the issue queue. I will re open if I find anything that helps. Thanks for the help.
