### ISSUE TITLE
Images with Aspect.Fill on Android are no longer filling after app resume.

### ISSUE THREAD

**Issue by coletronzero** [luberda-molinet/FFImageLoading#399]
Hi first I'd like to say thank you for the time you've put into this package.  The problem I'm having arises after an app resume on android.  I'm using images as a background to some containers on my UI.  It seems as though after a resume some of the backgrounds have taken the shape of other backgrounds using the same image.  Is there a way I could have multiple CachedImages using the same image source with the aspect property set to Aspect.Fill in different sized containers?  I do see that you are using the same instance of Bitmap for each reference to a single image and this might be causing this side effect.

**Comment by daniel-luberda** [comment]
Yes, you can do this. Just use a custom key factory, and assign a different key for each image. 

Here's an example: 

- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/CustomCacheKeyPage.cs#L51-L81
- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/CustomCacheKeyPage.cs#L99
