### ISSUE TITLE
Xamarin Form CachedImage doesn't appear to honor the global cache duration

### ISSUE THREAD

**Issue by bmacombe** [luberda-molinet/FFImageLoading#402]
I set it in the Init config to be 90 days and it was always zero.  Set CachedImage CacheDuration in XAML and the correct duration was set on the temp file (looked at the temp path in a UWP app)

This doesn't seem like the intended behavior?

**Comment by MrClockOff** [comment]
Seems like duplicate for https://github.com/luberda-molinet/FFImageLoading/issues/396

**Comment by bmacombe** [comment]
Your right, sorry I missed that!

**Comment by bmacombe** [comment]
Closed since it was a dup
