### ISSUE TITLE
Load Image from url to cache

### ISSUE THREAD

**Issue by PereAlmendro** [luberda-molinet/FFImageLoading#404]
I'm trying to save an image from url into cache but this local path is not being created in mobile 
/data/users/0/my.pack.age/cache/FFSimpleDiskCache/A3CBFAC7AE59767C88B81F90AD9F9D47.432000

ImageService
.Instance
.LoadUrl(Url, new TimeSpan(5, 0, 0, 0))
.Success((arg1, arg2) => { 
	localpath= arg1.FilePath;
}).DownloadOnly();

what i'm doing wrong ? thanks

**Comment by alanspires** [comment]
When a file is saved to disk from library it is put into a Queue. Thus when the download finishes the file might still be pending in the queue and not written to disk yet. I've asked @daniel-luberda for help on this same issue regarding a GIF PR I'm working on.

Here is a hack that might help you, stick this in your .Success
`await Task.Delay(1000);
var key = ImageService.Instance.Config.MD5Helper.MD5(arg1.Path);
localpath = await ImageService.Instance.Config.DiskCache.GetFilePathAsync(key);`

**Comment by PereAlmendro** [comment]
@alanspires first of all,  thank you for your reply. your solution is not doing the trick for me, returns empty string and with the code as i post it returns a string /Data/users/0/package/cachew/etc.... but  ...../0/(from here) the path is not existing in the phone.... Maybe you know why ?, well i'm doing a bit of research to understand a bit more what you tried so I can adapt it to my case  thank You .

**Comment by alanspires** [comment]
Can you post your updated code example as well as the URL?

**Comment by PereAlmendro** [comment]
axml
```

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:local="http://schemas.android.com/apk/res-auto"
    android:orientation="horizontal"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:padding="20dp">
    <FFImageLoading.Cross.MvxImageLoadingView
        android:layout_width="100dp"
        android:layout_height="100dp"
        local:MvxBind="DrawableName Poster" />
    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1"
        local:MvxBind="Text Title" />
</LinearLayout>
```

View Model 

```
MvxObservableCollection<Search> _results;
public MvxObservableCollection<Search> results
{
	get { return _results; }
	set { 
		_results = value;
		RaisePropertyChanged(() =>results);
	}
}
void searchByTitle()
{
	if (!_titleToSearch.Equals(""))
	{
				
		page = 1;
		var service = new Service();
		var items = service.searchByTitle(searchkey, page);

		if (items != null)
		{
			foreach (var item in items.Search)
			{
				if (!item.imageURL.Equals("N/A"))
				{
					ImageService
						.Instance
						.LoadUrl(item.imageURL,new TimeSpan(5, 0, 0, 0))
						.CacheKey(item.ID)
						.DownSample(100,100)
						.Success((arg1, arg2) =>
						{
							item.imageURL = arg1.FilePath;
						}).Preload();
				}		
			}
			results = new MvxObservableCollection<Myclass>(items.Search);
			page++;
		}
		else showNotFound();
	}
	else showNotFound();
}
```

Note that i'm new at xamarin.

**Comment by daniel-luberda** [comment]
@alanspires  The solution could be adding a new callback, eg. `OnFileWriteEnded`. What do you think?

**Comment by alanspires** [comment]
That would be very useful, been a while since I've been in the code but I would think that would be fine.

**Comment by daniel-luberda** [comment]
Closing as it's implemented.
