### ISSUE TITLE
Cache download problem

### ISSUE THREAD

**Issue by Ingenator** [luberda-molinet/FFImageLoading#406]
Hey guys!

I'm having a problem when a listview with CachedImage when scrolling. Debugger shows something like

```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: NotFound
12-01 21:13:55.330 I/mono-stdout( 5788): Image loading failed: http://myserver/img/p/2067/T_931_0.jpgCircleTransformation,borderSize=0,borderHexColor=
12-01 21:13:55.330 I/mono-stdout( 5788): System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: NotFound
12-01 21:13:55.330 I/mono-stdout( 5788):   at FFImageLoading.Cache.DownloadCache+<DownloadAsync>d__13.MoveNext () [0x0014a] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:88 
12-01 21:13:55.330 I/mono-stdout( 5788): --- End of stack trace from previous location where exception was thrown ---
```
This particular line tries to fetch the image from my server but it attaches some data:
`http://myserver/img/p/2067/T_931_0.jpgCircleTransformation,borderSize=0,borderHexColor=`

It's obvious that there's an error with the URL but why are those properties added to the URL?
Any ideas?

**Comment by flchaux** [comment]
I have the same issue with a long URL (more than 90 characters) but without any parameters. My URL looks like : https://static.myserver.com/clients/215_da529f7a00a67363fd60e4589ddaa094/documents/1258.jpg

**Comment by daniel-luberda** [comment]
I checked the source and can't see any potential code that could append parts of keys to **image loading path**. Are you sure that you're not using string which is created from previous image load key? Please notice, **image loading key != image loading path**, as it contains additional informations (as transformations, downsampling, etc)

**Comment by daniel-luberda** [comment]
Please reopen if you have more info or still experience it when using newest prerelease nuget. Thanks.

**Comment by hvaughan3** [comment]
The URL that gets put in the Output window has random stuff at the end of it in the error output, perhaps the random stuff is being added to the error/exception message and not to the URL property itself?
