### ISSUE TITLE
How to use FFImageLoading?

### ISSUE THREAD

**Issue by ShahriatHossain** [luberda-molinet/FFImageLoading#410]
Do I need to install it from Nuget package or how can I do it?

**Comment by molinch** [comment]
Hi,

Yes it should be installed from Nuget into the relevant projects.
Please read the related Wiki sections: 
https://github.com/luberda-molinet/FFImageLoading/wiki

If you use Xamarin Forms then you should initialize the library:
https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#important

**Comment by ShahriatHossain** [comment]
DownsampleToViewSize what this feature do if I make it true?

**Comment by molinch** [comment]
@ShahriatHossain It is written in the wiki: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#downsampling-properties

It will automatically downsample the image according to it's visible width, hence reducing memory consumption.

**Comment by ShahriatHossain** [comment]
I am trying to use image url from remote like https://imageurl.com (from amazon s3 file storage) but getting exception: System.Net.Http.HttpRequestException: BadRequest and more. Below is my custom cell with Cashed Image implemented code:

public class ChannelCustomCell : ViewCell
    {
        readonly CachedImage cachedImage = null;
        public ChannelCustomCell()
        {
            cachedImage = new CachedImage()
            {
                HorizontalOptions = LayoutOptions.Center,
                VerticalOptions = LayoutOptions.Center,
                WidthRequest = 300,
                HeightRequest = 300,
                CacheDuration = TimeSpan.FromDays(30),
                DownsampleToViewSize = true,
                RetryCount = 0,
                RetryDelay = 250
            };
            View = cachedImage;
        }

        
        public static readonly BindableProperty ImageUrlProperty =
            BindableProperty.Create("ImageUrl", typeof(string), typeof(ChannelCustomCell), "ImageUrl");

        public string ImageUrl
        {
            get { return (string)GetValue(ImageUrlProperty); }
            set { SetValue(ImageUrlProperty, value); }
        }

        
        protected override void OnBindingContextChanged()
        {
            base.OnBindingContextChanged();

            if (BindingContext != null)
            {
                cachedImage.Source = ImageUrl;
            }
        }

    }

and my xaml code:

<ListView.ItemTemplate>
        <DataTemplate>
          <cntrl:ChannelCustomCell ImageUrl="{Binding OrgLogo}"/>
        </DataTemplate>
      </ListView.ItemTemplate>

what I am doing wrong here?

**Comment by ShahriatHossain** [comment]
Do you have any answer for this sir?

**Comment by daniel-luberda** [comment]
@ShahriatHossain  `System.Net.Http.HttpRequestException: BadRequest` on S3 usually means that you didn't configured S3 folder privileges for this url. It's not an FFImageLoading issue.
