### ISSUE TITLE
Hard crash on Android when Layout.Children.Clear() includes CachedImage

### ISSUE THREAD

**Issue by scottkdavis** [luberda-molinet/FFImageLoading#411]
It took nearly 8 hours, but we finally tracked down an issues that crashed our app with no global exception handling and no Xamarin Insights reports.  We have an Absolute layout that includes many nested layouts and CachedImages.  On a Moto E phone, when we called _myLayout.Children.Clear(); approximately 1 to 2 seconds later, the app would hard crash.  It appears that something is happening in garbage collection. Since it is not happening on the calling thread, the exception is untrapable, and the app terminates.  Here is the stack trace.  All of our images are loaded via FFImageLoader  I hope it helps.

12-07 14:12:59.830 E/mono-rt (25965): Stacktrace:
12-07 14:12:59.830 E/mono-rt (25965): 
12-07 14:12:59.830 E/mono-rt (25965):   at <unknown> <0xffffffff>
12-07 14:12:59.831 E/mono-rt (25965):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_static_object_method_a (intptr,intptr&,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00053>
12-07 14:12:59.832 E/mono-rt (25965):   at Java.Interop.JniEnvironment/StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00069] in /Users/builder/data/lanes/3511/ce955cc0/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12645
12-07 14:12:59.833 E/mono-rt (25965):   at Java.Interop.JniPeerMembers/JniStaticMethods.InvokeObjectMethod (string,Java.Interop.JniArgumentValue*) [0x0001b] in /Users/builder/data/lanes/3511/ce955cc0/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97
12-07 14:12:59.833 E/mono-rt (25965):   at Android.Graphics.BitmapFactory.DecodeStream (System.IO.Stream,Android.Graphics.Rect,Android.Graphics.BitmapFactory/Options) [0x00070] in /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Graphics.BitmapFactory.cs:745
12-07 14:12:59.833 E/mono-rt (25965):   at Android.Graphics.BitmapFactory/<DecodeStreamAsync>c__AnonStoreyA.<>m__0 () [0x00000] in /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Graphics.BitmapFactory.cs:754
12-07 14:12:59.834 E/mono-rt (25965):   at System.Threading.Tasks.Task`1<TResult_REF>.InnerInvoke () [0x00012] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:680
12-07 14:12:59.834 E/mono-rt (25965):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502
12-07 14:12:59.834 E/mono-rt (25965):   at System.Threading.Tasks.Task.ExecutionContextCallback (object) [0x00007] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2865
12-07 14:12:59.835 E/mono-rt (25965):   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x0008d] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957
12-07 14:12:59.835 E/mono-rt (25965):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904
12-07 14:12:59.835 E/mono-rt (25965):   at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task&) [0x0005f] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2827
12-07 14:12:59.836 E/mono-rt (25965):   at System.Threading.Tasks.Task.ExecuteEntry (bool) [0x0006f] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2760
12-07 14:12:59.836 E/mono-rt (25965):   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2707
12-07 14:12:59.836 E/mono-rt (25965):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:854
12-07 14:12:59.837 E/mono-rt (25965):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1209
12-07 14:12:59.837 E/mono-rt (25965):   at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) <IL 0x0001f, 0x0007b>
12-07 14:12:59.837 E/mono-rt (25965): 
12-07 14:12:59.837 E/mono-rt (25965): Attempting native Android stacktrace:
12-07 14:12:59.837 E/mono-rt (25965): 
12-07 14:12:59.899 E/mono-rt (25965):   at ???+1064962 [0x40508002]
12-07 14:12:59.899 E/mono-rt (25965):   at SkScaledBitmapSampler::next(unsigned char const*)+30 [0x405082d3]
12-07 14:12:59.900 E/mono-rt (25965):   at SkPNGImageDecoder::onDecode(SkStream*, SkBitmap*, SkImageDecoder::Mode)+582 [0x4050598b]
12-07 14:12:59.900 E/mono-rt (25965):   at SkImageDecoder::decode(SkStream*, SkBitmap*, SkBitmap::Config, SkImageDecoder::Mode)+36 [0x40501a15]
12-07 14:12:59.900 E/mono-rt (25965):   at ???+483565 [0x401de0ed]
12-07 14:12:59.900 E/mono-rt (25965):   at ???+483993 [0x401de299]
12-07 14:12:59.900 E/mono-rt (25965):   at dvmPlatformInvoke+112 [0x415813cc]
12-07 14:12:59.900 E/mono-rt (25965):   at dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398 [0x415b1eeb]
12-07 14:12:59.900 E/mono-rt (25965):   at ???+170080 [0x4158a860]
12-07 14:12:59.901 E/mono-rt (25965):   at dvmMterpStd(Thread*)+76 [0x41591b68]
12-07 14:12:59.901 E/mono-rt (25965):   at dvmInterpret(Thread*, Method const*, JValue*)+184 [0x4158f200]
12-07 14:12:59.901 E/mono-rt (25965):   at dvmCallMethodA(Thread*, Method const*, Object*, bool, JValue*, jvalue const*)+354 [0x415c437f]
12-07 14:12:59.901 E/mono-rt (25965):   at ???+315435 [0x415ae02b]
12-07 14:12:59.901 E/mono-rt (25965):   at java_interop_jnienv_call_static_object_method_a+40 [0x546be58c]
12-07 14:12:59.901 E/mono-rt (25965): 
12-07 14:12:59.901 E/mono-rt (25965): =================================================================
12-07 14:12:59.901 E/mono-rt (25965): Got a SIGSEGV while executing native code. This usually indicates
12-07 14:12:59.901 E/mono-rt (25965): a fatal error in the mono runtime or one of the native libraries 
12-07 14:12:59.901 E/mono-rt (25965): used by your application.
12-07 14:12:59.901 E/mono-rt (25965): =================================================================
12-07 14:12:59.901 E/mono-rt (25965): 
12-07 14:12:59.902 F/libc    (25965): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 26158 (qr.android.blue)

**Comment by DOWONLEE** [comment]
If you use downsample or Transformations, stop it and test again

**Comment by daniel-luberda** [comment]
Hi @scottkdavis 

After some digging, I am almost sure that it's an Xamarin.Android issue. It's quite hard to debug / reproduce it for me. I'll need some help with that.

**Comment by daniel-luberda** [comment]
Please reopen if you have more info. Thanks.

**Comment by xevilboss** [comment]
Same problem.

**Comment by daniel-luberda** [comment]
@xevilboss I think it should be submitted to Xamarin bugzilla
