### ISSUE TITLE
Best approach to show a progress bar while downloading

### ISSUE THREAD

**Issue by moonClimber** [luberda-molinet/FFImageLoading#412]
Hello and thanks for your work.
I'd like to add a progress bar (even indeterminate) close the ImageView to indicate to user when the image is downloading from internet and not loaded from local cache.

In your opinion, what is the best approach to implement this behavior?
I guess that an OnStart action beside the OnFinish could be helpful.

Thanks

**Comment by EmmanVazz** [comment]
I am showing the progress of image downloads while using this project. 

Basically what we did is copied ModernHtttpClient  HttpClientHandler (https://github.com/paulcbetts/ModernHttpClient/blob/master/src/ModernHttpClient/iOS/NSUrlSessionHandler.cs) and modified registeredProgressCallbacks to be <String, ProgressDelegate> so we can just register for progress update with the request url. Then we pass in the modified HttpClientHandler into FF as part of the config as the HttpClient, using a custom HttpClientHandler is explained on this wiki page https://github.com/luberda-molinet/FFImageLoading/wiki/Authentication-Support . 

Then you make your ProgressDelegate update what value you are binding your progress bar to. 

Hope that helps.

**Comment by moonClimber** [comment]
Thanks

**Comment by EmmanVazz** [comment]
Np, let me know if you have any questions.

**Comment by daniel-luberda** [comment]
I think we could implement some callback for that eg. `OnDownloadProgress`. 

We need to replace
- this: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Cache/DownloadCache.cs#L97-L101 
- with something like this: http://stackoverflow.com/a/27422691/5064986

**Comment by EmmanVazz** [comment]
That would be a great addition imo.

**Comment by EmmanVazz** [comment]
Hello @daniel-luberda,

I have been testing the new DownloadProgressCommand. Firstly great work! 

I found one small issue tho. If I preload the image by calling DownloadOnly() before creating the Cached Image, the progress doesn't seem to be reported. The Success Command is called when it is done but progress is not being reported while the download is happening. If I stop preloading images everything works great.

Any ideas?

Thanks.

**Comment by daniel-luberda** [comment]
Preloading is a separate image loading task and every task handles its own events, so: 

```C#
ImageService.Instance.LoadUrl("http://loremflickr.com/600/600/nature?filename=simple.jpg")
			.DownloadProgress((obj) =>
			{
				//TODO
			})
			.DownloadOnly();
```

**Comment by EmmanVazz** [comment]
Well I don't want the download progress of the preloading task, I want it for the Cached Image. It just seems like the DownloadProgress doesn't persist when a preloading task is converted to a normal request via a CachedImage initiation. Is that not how it should work?

**Comment by EmmanVazz** [comment]
I made a fork of the repo to show what I am talking about. I added this to see the download progress get reported (https://github.com/EmmanVazz/FFImageLoading/commit/cc31275aa0b4bce6f468c7a9b86e4bb04201b6e0).
 
However it never gets trigger, even when I slow down the connection to the simulator (Mac network link conditioner set to Edge). I also tried removed the DownloadOnly() call, that didn't seem to get it to trigger either.

**Comment by daniel-luberda** [comment]
@EmmanVazz It's a correct behaviour. If another loading task is running for the same image, `CachedImage` waits for its results - it doesn't download anything on its own. Why should it show any download progress if it's not downloading anything?

**Comment by EmmanVazz** [comment]
I can see how you want to keep the old loading task but I think the download progress should propagate to the CachedImage call as when I create the CachedImage I still want the progress of the task downloading that image. 

Separate question: If I call DownloadOnly()(Low = priority) for an image, then later I create CachedImage(Normal = priority) for that same image. Does that bump up the priority on the initial task up to Normal or does it wait for that low priority task to complete?

**Comment by daniel-luberda** [comment]
> I can see how you want to keep the old loading task but I think the download progress should propagate to the CachedImage call as when I create the CachedImage I still want the progress of the task downloading that image.

That would involve some kind of progress values `Dictionary` for all current downloads. It's an additional overhead, but it could be implemented. I have to think how it's best to do, any ideas?. It's a nice enhancement though. 

>Separate question: If I call DownloadOnly()(Low = priority) for an image, then later I create CachedImage(Normal = priority) for that same image. Does that bump up the priority on the initial task up to Normal or does it wait for that low priority task to complete?

Thanks to you PR, yes :) Thanks for that.

**Comment by EmmanVazz** [comment]
I will open another issue.
