### ISSUE TITLE
App crash on Android in Release. Works in Debug though

### ISSUE THREAD

**Issue by 0rupp** [luberda-molinet/FFImageLoading#413]
I tried the latest nuget 2.2.6-pre-241. Initialized the lib in MainActivity with `CachedImageRenderer.Init();`. Works fine in Debug, but crashes in Release mode. logcat provides the following error (sorry no copy&paste in VS log viewer...)

![error](https://cloud.githubusercontent.com/assets/7384861/21073946/ff860496-beec-11e6-9989-03799eef4f48.PNG)

**Comment by daniel-luberda** [comment]
Hi @0rupp,

It looks like Xamarin Multi-Dex feature related issue, not FFImageLoading. You can try to delete bin & obj folders, maybe it would help.
