### ISSUE TITLE
FFImageLoading used along with FlowListview slows down scrolling on iOS device

### ISSUE THREAD

**Issue by sujithrajan** [luberda-molinet/FFImageLoading#414]
Please find the code below.

<controls:FlowListView SeparatorVisibility="None" HasUnevenRows="true" FlowColumnMinWidth="110" x:Name="FlowListViewDemo" FlowColumnExpand="Proportional" RowHeight="-1" FlowItemAppearing="OnItemAppearingList" FlowItemDisappearing="FlowListViewDemo_OnFlowItemDisappearing">
      <controls:FlowScrollCell></controls:FlowScrollCell>
      <controls:FlowListView.FlowColumnTemplate>
        <DataTemplate>

        <gestures:Grid BackgroundColor="White" Padding="1" RowSpacing="0" VerticalOptions="Fill" LongPressed="OnLongPressImage" Tapped="OnImageTapped">
            <gestures:Grid.RowDefinitions>
              <RowDefinition Height="Auto" />
            </gestures:Grid.RowDefinitions>
            <gestures:Grid.ColumnDefinitions>
              <ColumnDefinition Width="*" />
            </gestures:Grid.ColumnDefinitions>
            
            <forms:CachedImage
              BackgroundColor="#888888"
          HeightRequest="{Binding CustomHeight}"
          WidthRequest="{Binding CustomHeight}"
          x:Name="CachedImage1"
          Aspect="AspectFill"
          DownsampleToViewSize="False"
          RetryCount = "2"
          RetryDelay = "250"
          ErrorPlaceholder="image_loading.png"
          Source="{Binding thumbnail}"
          CacheDuration="30"
          DownsampleHeight="110"
          DownsampleUseDipUnits="False"
          CacheType="Disk"
          LoadingPriority="Highest"
         VerticalOptions="FillAndExpand"
          DownsampleWidth="110"
         TransparencyEnabled="False"
          FadeAnimationEnabled="False"
          BitmapOptimizations="True"
          >
            </forms:CachedImage>
            <Label x:Name="Label" HorizontalOptions="Fill" HorizontalTextAlignment="Center" VerticalOptions="End" TextColor="#000000"
              BackgroundColor="Silver" Opacity="0.5" Text="{Binding channel}"/>
                            
          </gestures:Grid>

        </DataTemplate>
      </controls:FlowListView.FlowColumnTemplate>

    </controls:FlowListView>

**Comment by elertan** [comment]
It is due to the HasUnevenRows that causes the slowing down if you have a lot of items in your listview. I dont know why that is...

**Comment by sujithrajan** [comment]
thanx elertan .. 'Now the scrolling has improved but there is little vibration on images as u scroll the list

**Comment by daniel-luberda** [comment]
FlowListView relies on Xamarin.Forms layout system, it has some performance issues sometimes, can't bypass that. You can also try setting `flowListView.FlowUseAbsoluteLayoutInternally = true;` which can be faster.
