### ISSUE TITLE
Configuration.MaxMemoryCacheSize not working correctly

### ISSUE THREAD

**Issue by franzdevel** [luberda-molinet/FFImageLoading#415]
The Configuration.MaxMemoryCacheSize parameter does not limit the ImageCache size as expected.

In the ImageCache constructor, the following line of code

`_cache.TotalCostLimit = (nuint)Math.Max((NSProcessInfo.ProcessInfo.PhysicalMemory * 0.05d), maxCacheSize);`

should be changed to

`_cache.TotalCostLimit = (nuint)Math.Min((NSProcessInfo.ProcessInfo.PhysicalMemory * 0.05d), maxCacheSize);`

**Comment by daniel-luberda** [comment]
@franzdevel Good catch! Thanks. It's fixed now.
