### ISSUE TITLE
Xamarin Forms XAML Preview support

### ISSUE THREAD

**Issue by vlkam** [luberda-molinet/FFImageLoading#418]
When I try to open XAML in Form Previewer "Initializing renderer" runs infinitely long

**Comment by daniel-luberda** [comment]
XAML Previewer is a Prerelease. I don't have any informations about supporting custom renderers in it (which `CachedImage` is).  If someone has any info about that, please let me know. Meanwhile, you can use `Image` and then after prototyping replace it with `CachedImage` which has the same basic properties.

**Comment by vlkam** [comment]
Thanks a lot for answer and the excellent library! 

Yes, alfa version Previewer supports custom renderers. 
But when I try to use FFImageCache in XAML, for example <ffimageloading:CachedImage/>  I catch an exception in Previewer   
_Invalid XAML The type initializer for FFImageLoading.Forms.CachedImage threw an exception._
Unfortunately, logs do not show  any problem. I'm trying to find problem in constructor of CachedImage, but it is very simple an clear.

**Comment by daniel-luberda** [comment]
@vlkam Thanks. 

Did you try to check /Users/username/Library/Logs folder? Maybe those logs would give some more informations.

**Comment by vlkam** [comment]
> Did you try to check /Users/username/Library/Logs folder? 

It's FFImageLoading's folder ? I cannot found it.

I created an empty solution, ran it and made a snapshot of logs from 
C:\Users\username\AppData\Local\Xamarin\Logs\14.0
then I added ffimageloading:CachedImage into XAML, caught error and again made the snapshot, compared these snapshots and I found no significant differences

The Previewer uses only PCL part of solution and custom renders from platform specific part. Previewer does not create the AppDelegate. May be problem is that ?

sorry for my english, I'm working on it :-)

**Comment by vlkam** [comment]
Ohh.... I'm so sorry, I don tell you, I work in Visual Studio (windows)

**Comment by vlkam** [comment]
I have checked, double checked and triple checked the CachedImage class code, removed all suspicious fragments, tried to create a very simple instance of it but got an exception every time.   
I have no idea what it could be.

**Comment by daniel-luberda** [comment]
Hi @vlkam 

If it's Windows, you could use VS help menu, Xamarin > Logs. Open the last .svclog file. There should be some log entry about your issue.

**Comment by molinch** [comment]
@vlkam Do you have news on this topic?

**Comment by tilutza** [comment]
This is the exception that occurs on a Windows machine:
2017-05-22 11:06:12.3] INFO: : Initializing the previewer with Android API level 25.
Xamarin.Designer|Information|0|
[2017-05-22 11:06:41.2] ERROR: : The renderer encountered an error while rendering this file: System.TypeInitializationException: The type initializer for 'FFImageLoading.Forms.CachedImage' threw an exception.
at MyProject.Pages.User.UserProfile..ctor () in D:\MyProjects\MyProject_git\MyProject\MyProject\Pages\User\UserProfile.xaml.cs:21
at MyProject.Pages.Navigation.UserMenuMasterDetailPage..ctor () in D:\MyProjects\MyProject_git\MyProject\MyProject\Pages\Navigation\UserMenuMasterDetailPage.cs:15
at MyProject.Phone.App..ctor () in D:\MyProjects\test\MyProject\MyProject\App.cs:54
at <unknown method> at offset 12 in file:line:column <filename unknown>:0:0
at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) in :0


and my setup is:

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Xamarin   4.4.0.34 (3f99c5a)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Inspector Support   1.0.0.0 (1f3067d)
Adds support for inspecting Xamarin and WPF apps.

Xamarin.Android   7.2.0.7 (b16fb82)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   10.8.0.174 (7656cc6)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by tilutza** [comment]
Does anyone from the FFImage library has any idea why this is happening ? I assume that Xamarin Previwer does not load the Android Render .... but is there any way to disable this ?

**Comment by tilutza** [comment]
Finally I was able to get a full stacktrace of the exception. The error is a ObjectNullReferenceException and the stack trace is:
![image](https://cloud.githubusercontent.com/assets/5718468/26376925/f4f59dce-4016-11e7-8830-2f27c4bf7d07.png)

I will keep digging trying to find a workaround

**Comment by daniel-luberda** [comment]
It's fixed in the latest prerelease nuget :) Thanks @tilutza for https://github.com/luberda-molinet/FFImageLoading/pull/612

**Comment by nazgul87** [comment]
Hi, have somebody did make it work using xaml previwer?
I'm trying to use an SvgCachedImage on my app but I'm getting this exception:

ERROR: : The renderer encountered an error while rendering this file: System.TypeInitializationException: The type initializer for 'FFImageLoading.Forms.CachedImage' threw an exception.
at FFImageLoading.Svg.Forms.SvgCachedImage.set_DownsampleUseDipUnits (System.Boolean value) in C:\projects\ffimageloading\source\FFImageLoading.Svg.Forms.Shared\SvgCachedImage.cs:15
at <unknown method> at offset 12 in file:line:column <filename unknown>:0:0
at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) in :0

And when I run the app, the image is not visible.

Any ideas about what I'm doing wrong?

**Comment by ammarMheir** [comment]
We seem to be observing an issue with Xamarin Previewer with the latest FFImageLoading package. We first observed this on the previewer for both Android and iOS however after updating to latest FFImageLoading release, we only observe this on iOS. Getting an error: 

An exception occurred while rendering the control.
System.TypeInitializationException was thrown.
The Type Initializer for "FFImageLoading.Forms.CachedImage" threw an exception.

##Version Information
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.0.1 (build 24)
Installation UUID: 294bd613-94d8-444e-8fd2-8714ab8fb459
Runtime:
                Mono 5.0.1.1 (2017-02/5077205) (64-bit)
                GTK+ 2.24.23 (Raleigh theme)

                Package version: 500010001

=== NuGet ===

Version: 4.0.0.2323

=== Apple Developer Tools ===

Xcode 8.3.3 (12175.1)
Build 8E3004b

=== Xamarin.Mac ===

Version: 3.4.0.36 (Visual Studio Enterprise)

=== Xamarin.Android ===

Version: 7.3.1.2 (Visual Studio Enterprise)
Android SDK: /Users/joseluizlacerdasoares/Library/Developer/Xamarin/android-sdk-macosx
                Supported Android versions:
                                6.0 (API level 23)
                                7.0 (API level 24)
                                7.1 (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 26.0.0

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.iOS ===

Version: 10.10.0.36 (Visual Studio Enterprise)
Hash: d2270eec
Branch: d15-2
Build date: 2017-05-22 16:30:53-0400

=== Build Information ===

Release ID: 700010024
Git revision: 7ab1ca2ced6f584e56b7a0d4d321d00775cd95c9
Build date: 2017-05-19 05:44:51-04
Xamarin addins: 08d17158f3365beee5e60f67999e607cce4b3f93
Build lane: monodevelop-lion-d15-2

=== Operating System ===

Mac OS X 10.12.5
Darwin 16.6.0 Darwin Kernel Version 16.6.0
    Fri Apr 14 16:21:16 PDT 2017
    root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Comment by castrojr913** [comment]
Indeed, this bug has not been fixed yet.

**Comment by vlkam** [comment]
I think it's not necessary anymore
LiveXAML much better than XAML previewer 
http://www.livexaml.com/

**Comment by molinch** [comment]
@vlkam so what you mean is that it works fine with LiveXAML? so no need to do anything in the end

**Comment by vlkam** [comment]
Xamarin XAML previewer has a lot of limitation, bugs and requires the design time data.
LiveXAML works directly in simulators and devices, with real data and practically hasn't the limitation and doesn't require the design time data. LiveXAML works even with Fody and Realm
Therefore, by my opinion,  no reason for using Xamarin XAML previewer and no reason for solving this issue

**Comment by daniel-luberda** [comment]
@molinch @vlkam We should fix the official XAML Previewer anyway as @vlkam is a third party solution. I'll debug it later.

**Comment by daniel-luberda** [comment]
After trying to debug it, i got nowhere as Visual Studio for Mac IDE logs are not very useful. Could someone send me some full stack trace from Windows so I could move on?

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/860
