### ISSUE TITLE
Image Reload issue

### ISSUE THREAD

**Issue by johnjore** [luberda-molinet/FFImageLoading#419]
Duplicate of #282?  Problems reloading images.

This is the relevant snippet:
```
                var image = new CachedImage()
                {
                    DownsampleToViewSize = false,
                    CacheDuration = TimeSpan.FromMilliseconds(1000),
                    Aspect = Aspect.AspectFill,
                    RetryCount = 0,
                    RetryDelay = 250,
                    BitmapOptimizations = true,
                    Source = item.url
                };
                grid.Children.Add(image, px, px + sx, py, py + sy);

                // Start the refresh timer
                if (item.refresh != string.Empty)
                {
                    int refresh = Convert.ToInt32(item.refresh);
                    if (refresh > 0)
                    {
                        Device.StartTimer(TimeSpan.FromMilliseconds(refresh), () =>
                        {
                            Debug.WriteLine("Refresh Image: " + image.Id.ToString());
                            try
                            {
                                image = new CachedImage()
                                {
                                    DownsampleToViewSize = false,
                                    CacheDuration = TimeSpan.FromMilliseconds(1000),
                                    Aspect = Aspect.AspectFill,
                                    RetryCount = 0,
                                    RetryDelay = 250,
                                    BitmapOptimizations = true,
                                    Source = item.url
                                };
                                image.ReloadImage();
                                grid.Children.Add(image, px, px + sx, py, py + sy);
                            }
                            catch (Exception ex)
                            {
                                Debug.WriteLine("Failed to refresh Image: " + ex.ToString());
                            }
                            return true;
                        });
                    }
                }
```

Every  5 seconds I get this, showing the refresh routine is running:

> [0:] Refresh Image: 16a4f712-1792-4243-b806-d48d642e3917

but cell in Grid is not updating with new image. The URL behind this is `https://source.unsplash.com/category/technology/1600x900`
That URL spits out a new image each time, and I do get a new image each time app is restarted.

I use the same concept to update labels with new data (date/time), and it works without needing to re-load the label into the grid. Snippet above is a latest attempt as a belt and braces approach... Image does not change. 

I've also loaded images from a couple of cameras, same problem. The only time they update is when application is restarted.

I also tried to add a 2nd image variable with a different image and had that load into the grid in the refresh rutine, grid updates to show image1, but image1 also stays static, and never updates (wifi camera). Something similar to this;
> image1 = new CachedImage()
>                                 {
>                                     DownsampleToViewSize = false,
>                                     CacheDuration = TimeSpan.FromMilliseconds(1000),
>                                     Aspect = Aspect.AspectFill,
>                                     RetryCount = 0,
>                                     RetryDelay = 250,
>                                     BitmapOptimizations = true,
>                                     Source = "http://something  new"
>                                 };
> image1.ReloadImage();
> grid.Children.Add(image1, px, px + sx, py, py + sy);

Any ideas?

--
So, the "fix" is to add
`ImageService.Instance.InvalidateCacheAsync(CacheType.All);`
to the start of the refresh routine.

Final working version:
>                 var image = new CachedImage()
>                 {
>                     DownsampleToViewSize = false,
>                     CacheDuration = TimeSpan.FromMilliseconds(1000),
>                     Aspect = Aspect.AspectFill,
>                     RetryCount = 0,
>                     RetryDelay = 250,
>                     BitmapOptimizations = true,
>                     Source = item.url
>                 };
>                 grid.Children.Add(image, px, px + sx, py, py + sy);
> 
>                 // Start the refresh timer
>                 if (item.refresh != string.Empty)
>                 {
>                     int refresh = Convert.ToInt32(item.refresh);
>                     if (refresh > 0)
>                     {
>                         Device.StartTimer(TimeSpan.FromMilliseconds(refresh), () =>
>                         {
>                             ImageService.Instance.InvalidateCacheAsync(CacheType.All);
> 
>                             Debug.WriteLine("Refresh Image: " + image.Id.ToString());
>                             try
>                             {
>                                 image.ReloadImage();
>                             }
>                             catch (Exception ex)
>                             {
>                                 Debug.WriteLine("Failed to refresh Image: " + ex.ToString());
>                             }
>                             return true;
>                         });
>                     }
>                 }
> 

Long post, but hopefully it helps someone else. Anyway, thanks for the library! Needed it as it supports authentication.

JJ

**Comment by daniel-luberda** [comment]
Hi @johnjore,

FFImageLoading cache images by default. You can clear cache for a specified key with `CachedImage. InvalidateCache` or `ImageService.Instance.InvalidateCacheEntryAsync` method. `ImageService.Instance.InvalidateCacheAsync(CacheType.All);` will clear the whole cache, which is most often not a desired solution. 

Cheers.

**Comment by johnjore** [comment]
My bad. I though

>  "CacheDuration = TimeSpan.FromMilliseconds(1000)," 

would expire the cache, for this specific image, after 1000ms and a re-download would take place.

JJ

**Comment by daniel-luberda** [comment]
@johnjore I understand :) Old entries are purged automatically only at fresh app start (before first image loading operation).

**Comment by Raj123456788** [comment]
@johnjore Thank you so much for your comment!

**Comment by Raj123456788** [comment]
@johnjore : If I am reloading and getting images from timer. It just go back to old image. eg: If I get an image 1:53:00 the very next image I see is 1:52:33. Why is this happening?
