### ISSUE TITLE
IOS compile fail

### ISSUE THREAD

**Issue by lengluo** [luberda-molinet/FFImageLoading#420]
I'm sure I have get this lib from nuget for IOS project, But it happens blow when i compiles the project:
<img width="405" alt="xxxx" src="https://cloud.githubusercontent.com/assets/7494920/21254783/b79edd5a-c3a2-11e6-87c1-64c61602d0d8.png">

**Comment by daniel-luberda** [comment]
Hi @lengluo,

- What architectures are selected in your project build configuration?
- Do you use any special iOS project build arguments?
- Did you try to remove all `bin` & `obj` folders?

**Comment by lengluo** [comment]
@daniel-luberda Sorry for my late reply. I create the IOS project(blank App iphone) in Visual Studio 2015 and get the ffimageloading(Xamarin.FFImageLoading.Forms) from nuget, then build it with default normal way. I have tried to remove all bin and obj folders and it still have the same compile error.

**Comment by lengluo** [comment]
@daniel-luberda  Aha, I‘m so sorry to waste of your time to see this issue, it’s finally found  i had made a silly mistake that i added 'Mono.Android' dll to my PCL project, by removing this dll, it's complied fine.

**Comment by daniel-luberda** [comment]
@lengluo Sure, no problem, it happens. Maybe the build files were cached somewhere, so the build was successful before.
