### ISSUE TITLE
IsCompleted cannot be found at runtime [Android]

### ISSUE THREAD

**Issue by PaulARoy** [luberda-molinet/FFImageLoading#422]
Hi!

I am using FFImageLoading on Android and I am trying to use the property IsCompleted on a IScheduledWork.

Problem is it can not be found at runtime. When looking at old code, I can see a « Completed » that seems to have been renamed to « IsCompleted » (or the other way around?). Is it possible that the interface and the implementation do not share the same code ?

```
Method 'FFImageLoading.Work.IScheduledWork.get_IsCompleted' not found.
```

Repro:
Install latest version on a new Android project.
Use
```
var work = await ImageService.LoadUrl("an image").IntoAsync(MyView);
var completed = work.IsCompleted;
```

**Comment by daniel-luberda** [comment]
>  Is it possible that the interface and the implementation do not share the same code ?

I don't think so. Maybe you have mixed dll's (before changes and after changes) somewhere? Did you update all nuget packages? 

BTW: You also can Use `Success` (`LoadingResult` param) or `Finish` (`IScheduledWork` param) events for that.

**Comment by daniel-luberda** [comment]
Any news?

**Comment by PaulARoy** [comment]
I am sorry to make you wait, I have been stuck out of work for a few days. I will test that next week and close the issue if it is irrelevant. 
I already had issues like that before on other packages, it is indeed probably nothing.

**Comment by daniel-luberda** [comment]
Sure, I'll close this one. Please, reopen the issue if you you'll still experience it. Cheers :)

**Comment by PaulARoy** [comment]
Uninstalling / reinstalling the packages did the trick.
Something probably messed up the DLLs. Sorry for the bug report.
