### ISSUE TITLE
Not able to show image for local path

### ISSUE THREAD

**Issue by softsan** [luberda-molinet/FFImageLoading#423]
I have xamarin.forms app which uses camera to capture image. The captured image is stored in private folder path as shown below(on iOS):

`/var/mobile/Containers/Data/Application/21731669-A90E-4BC4-B5CA-9AD4B68E180E/Documents/Sample/img_19f1388a-407c-4310-b721-06d6396f0398.jpg`

But when i tried to load the above path image in ffimageloading it throws exception that it does not find the above file. I downloaded iOS app containers and i can see that the captured file is there on that path.  If i take default image control of xamarin.forms then it shows that image.

I am using code as follow in Xaml:
```
<forms:CachedImage x:Name="img" 
		              VerticalOptions="FillAndExpand"
		              HorizontalOptions ="FillAndExpand"
		              FadeAnimationEnabled="False" 
					Success="OnImageLoadSuccess"
			/>
```

and setting source in my code behind file:
`img.Source= source; // source is file path of captured image.`

I get following exception:
```
Image loading failed: /var/mobile/Containers/Data/Application/21731669-A90E-4BC4-B5CA-9AD4B68E180E/Documents/Sample/img_19f1388a-407c-4310-b721-06d6396f0398.jpg
System.IO.FileNotFoundException: /var/mobile/Containers/Data/Application/21731669-A90E-4BC4-B5CA-9AD4B68E180E/Documents/Sample/img_19f1388a-407c-4310-b721-06d6396f0398.jpg
  at FFImageLoading.DataResolvers.BundleDataResolver+<Resolve>d__1.MoveNext () [0x00456] in <f866fc50aabd449da0e25c454a95fbec>:

```
So any suggestion/thoughts on this?
Thanks.

**Comment by daniel-luberda** [comment]
Because of performance reasons, all files are saved to the disk using queue to allow loading images before it gets saved to the disk. By using newest prerelease you can use `FileWriteFinished` event / command which is called after file is successfully saved to the disk.

**Comment by softsan** [comment]
Thanks @daniel-luberda.

I used `xam media plugin` to capture image from camera or gallery and that plugin returns the storage path of captured image. So in that case the path is `/var/mobile/Containers/Data/Application/21731669-A90E-4BC4-B5CA-9AD4B68E180E/Documents/Sample/img_19f1388a-407c-4310-b721-06d6396f0398.jpg`

and i simply assign the above path to ffimage.source.

**Comment by daniel-luberda** [comment]
Please use the newest prerelease nuget. There was an issue which was fixed recently.

**Comment by softsan** [comment]
The latest version 2.2.6 has fix it for iOS. Thanks.

**Comment by Nullstr1ng** [comment]
can I re-open this issue? I am using version 2.3.4 and I am not able to load the image saved in LocalStorage in iOS. The image Is saved using LocalStorage using PCLStorage and the path looked like this "/var/mobile/Containers/Data/Application/121745DA-AEED-4434-B105-91D1F755DDB5/Documents/../Library/16-03-10-2018-02-17-01_tn.jpg" 

that path contains an invalid name, that they say it was a "bug" https://github.com/dsplaisted/PCLStorage/issues/49

so I have to remove the /../Library but still, the image is not loading. I have already checked if the file exists, and they do exists using PCLStorage CheckExistsAsync method.
