### ISSUE TITLE
Android TIFF decoding support

### ISSUE THREAD

**Issue by kingsj0405** [luberda-molinet/FFImageLoading#426]
There's no Error.
Viewing Well in iOS.
When change to image format jpg, rending well.

https://developer.android.com/guide/topics/media/media-formats.html

According to that page, Android can't support tiff.
Is there some way to render TIFF image?

**Comment by daniel-luberda** [comment]
Hi @kingsj0405,

We use native Android image decoding, so we are dependent on that. If you have any working implementation of `TIFF` file decoding on Android, we can add it, but currently it's not supported.

**Comment by molinch** [comment]
Honestly I think it's better to close this but accept/welcome any PR for it.
