### ISSUE TITLE
How to create custom transformation?

### ISSUE THREAD

**Issue by kyurkchyan** [luberda-molinet/FFImageLoading#427]
I want to create my own transformation. If I create custom transformation classes in iOS and Android which derive from `TransformationBase` how I would register them to be able to use them inside Forms project?

**Comment by daniel-luberda** [comment]
You don't need to register it. You need to use Bait&Switch PCL Technique. You just need to reference empty PCL implementation in shared project, and platform specific implementations (dlls) in Android/iOS projects. 

More here: http://log.paulbetts.org/the-bait-and-switch-pcl-trick/

**Comment by kyurkchyan** [comment]
@daniel-luberda it doesn't seem I can do the same without creating separate library project? I mean If I have a Forms app structured like MyApp.Forms, MyApp.Droid, MyApp.iOS, I can't place the "bait" inside my forms app project, and implement it in my MyApp.Droid and MyApp.iOS and make the system reference code from platform project not PCL. Is that true? Do I need to create separate Library.Forms, Library.iOS, Library.Droid projects with same namespace structure and assembly name?

**Comment by daniel-luberda** [comment]
You can have only one additional project by using Shared project, instead multiple PCL projects.
