### ISSUE TITLE
Reporting DownloadProgress to Similar Tasks

### ISSUE THREAD

**Issue by EmmanVazz** [luberda-molinet/FFImageLoading#431]
This is a continuation of https://github.com/luberda-molinet/FFImageLoading/issues/412

The issue is having similar calls for the same image will result in only the first task getting download progress reported, the other just know when the task is complete. I will be looking at the code to see what the best way to implement this is.

**Comment by EmmanVazz** [comment]
So this seems to work, 

 ```
similarRunningTask.ImageLoadingTask.Parameters.DownloadProgress((DownloadProgress obj) =>
                        {
                            similarRunningTask.ImageLoadingTask.Parameters.OnDownloadProgress(obj);
                            task.Parameters.OnDownloadProgress(obj);
                        });
 ```

inside the else if (similarRunningTask.ImageLoadingTask != null && task.Parameters.Priority.HasValue) statement.

However it would be nice to see if task actually has a non null DownloadProgress and a non null DownloadProgressCommand, basically meaning something is listening to the Download Progress. That way we can avoid doing that logic if it is not necessary.  We would also need to add OnDownloadProgress = null to the Dispose method for TaskParameter class to properly clean it up.

**Comment by daniel-luberda** [comment]
Great! I'll try to include it before releasing stable :) Thanks for your help.

**Comment by daniel-luberda** [comment]
It should be working now. See https://github.com/luberda-molinet/FFImageLoading/commit/bc4b6b5c79dd6bc3f2f62e7980067afd2c08477b

**Comment by EmmanVazz** [comment]
That seems like a great solution. I will test the pre-release later today. Thanks.
