### ISSUE TITLE
UWP - AggregateException_ctor_DefaultMessage

### ISSUE THREAD

**Issue by liptonbeer** [luberda-molinet/FFImageLoading#432]
Hi Everybody,
In my UWP app for some time I've been getting AggregateException_ctor_DefaultMessage logged by Hockeyapp api. Here is a stacktrace:
'FFImageLoading.Retry.<DoAsync>d__0$1<System.__Canon>.MoveNext(Void* InstParam) in C:\projects\ffimageloading\source\FFImageLoading.Common\Helpers\Retry.cs at 31:13
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs at 61:13
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 187:25
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 156:42
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 128:17
FFImageLoading.Cache.DownloadCache.<DownloadAndCacheIfNeededAsync>d__12.MoveNext() in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs at 16707566:0
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs at 61:13
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 187:25
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 156:42
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 128:17
FFImageLoading.DataResolvers.UrlDataResolver.<Resolve>d__7.MoveNext() in C:\projects\ffimageloading\source\FFImageLoading.Windows\DataResolvers\UrlDataResolver.cs at 16707566:0
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs at 61:13
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 187:25
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 156:42
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 128:17
FFImageLoading.Work.ImageLoaderTask$2<System.__Canon,System.__Canon>.<RunAsync>d__109.MoveNext(Void* InstParam) in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs at 16707566:0'

I'm using FFImageLoading librarty only in XAML views. Here is my XAML declaration:
<ff:FFImage Width="80" Height="80" Source="{x:Bind Pictures.MediumMobile, Mode=OneWay}" DownsampleToViewSize="True" 
                                        LoadingPlaceholder="LoadingPlaceholder.png" ErrorPlaceholder="ErrorPlaceholder.png" RetryDelay="200" RetryCount="3" CacheDuration="2">
                                <i:Interaction.Behaviors>
                                    <core:IncrementalUpdateBehavior Phase="3"/>
                                </i:Interaction.Behaviors>
                            </ff:FFImage>

Could someone help me with this exception?

**Comment by daniel-luberda** [comment]
`AggregateException` thrown by `FFImageLoading.Retry` are handled exceptions, which are just logged to notify you that an error occurred during image download (as connection error, network unavailable, etc). That's all. Why `AggregateException`? It' because you can specify how many times, FFImageLoading should try to retry if an `Exception` occurs, so you can have multiple `Exceptions`.

**Comment by liptonbeer** [comment]
Hi, thanks for your answer. I've added AggregateException to known errors in my app :)

**Comment by daniel-luberda** [comment]
👍 Please mind, that `AggregateException` is a standard net type and it can be also used by some non FFImageLoading related code too.
