### ISSUE TITLE
FFImageLoading url parser.

### ISSUE THREAD

**Issue by ScorpDiesel** [luberda-molinet/FFImageLoading#434]
Hey:

I'm using www.randomuser.me to populate the control with a random image but, error.png displays after a few attempts to download the image.  When I try an image from a *.com site, the image is downloaded and displayed in the control.  I have no problem downloading the json payload from the site and using other objects within it.  I'm also able to display the image in a browser.  Please advise.

To recreate:

https://randomuser.me/api/portraits/med/women/13.jpg
https://s-media-cache-ak0.pinimg.com/236x/4f/3c/d8/4f3cd8d78fec4427ad32c0ce96ff3afd.jpg

**Comment by daniel-luberda** [comment]
You should get some errors in application output. Could you paste it? Also you can configure own FFImageLoading logger as here: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Droid/MainActivity.cs#L21-L51

**Comment by ScorpDiesel** [comment]
Here's the dump.  I'll configure the logger and get back to you.

1-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-03 17:31:59.060 I/mono-stdout(18161):   at FFImageLoading.Retry+<DoAsync>d__0`1[T].MoveNext () [0x00047] in C:\projects\ffimageloading\source\FFImageLoading.Common\Helpers\Retry.cs:17 <---
01-03 17:31:59.060 I/mono-stdout(18161): ---> (Inner Exception #5) System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ---> System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
01-03 17:31:59.060 I/mono-stdout(18161):   at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x0003a] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/RecordProtocol.cs:430 
01-03 17:31:59.060 I/mono-stdout(18161):   at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:256 
01-03 17:31:59.060 I/mono-stdout(18161):   at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:418 
01-03 17:31:59.060 I/mono-stdout(18161):    --- End of inner exception stack trace ---
01-03 17:31:59.060 I/mono-stdout(18161):   at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x00035] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslClientStream.cs:396 
01-03 17:31:59.060 I/mono-stdout(18161):   at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:101 
01-03 17:31:59.060 I/mono-stdout(18161):    --- End of inner exception stack trace ---
01-03 17:31:59.060 I/mono-stdout(18161):   at Mono.Security.Protocol.Tls.SslStreamBase.EndRead (System.IAsyncResult asyncResult) [0x00051] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/SslStreamBase.cs:883 
01-03 17:31:59.060 I/mono-stdout(18161):   at Mono.Net.Security.Private.LegacySslStream.EndAuthenticateAsClient (System.IAsyncResult asyncResult) [0x00011] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/System/Mono.Net.Security/LegacySslStream.cs:475 
01-03 17:31:59.060 I/mono-stdout(18161):   at Mono.Net.Security.Private.LegacySslStream.AuthenticateAsClient (System.String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection clientCertificates, System.Security.Authentication.SslProtocols enabledSslProtocols, System.Boolean checkCertificateRevocation) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/System/Mono.Net.Security/LegacySslStream.cs:445 
01-03 17:31:59.060 I/mono-stdout(18161):   at Mono.Net.Security.MonoTlsStream.CreateStream (System.Byte[] buffer) [0x0004e] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/System/Mono.Net.Security/MonoTlsStream.cs:106 
01-03 17:31:59.060 I/mono-stdout(18161):    --- End of inner exception stack trace ---
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x0005e] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/System/System.Net/HttpWebRequest.cs:1023 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00014] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/FutureFactory.cs:550 
01-03 17:31:59.060 I/mono-stdout(18161): --- End of stack trace from previous location where exception was thrown ---
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-03 17:31:59.060 I/mono-stdout(18161):   at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x003ce] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:379 
01-03 17:31:59.060 I/mono-stdout(18161): --- End of stack trace from previous location where exception was thrown ---

**Comment by daniel-luberda** [comment]
You don't need to `System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.) ` is obvious. Read this: https://forums.xamarin.com/discussion/10405/the-authentication-or-decryption-has-failed-in-the-web-request

**Comment by ScorpDiesel** [comment]
I'm using modernhttpclient:

 using (var client = new HttpClient(new NativeMessageHandler()))
            {
                jsonString = client.GetStringAsync(randomProfile).Result;
            }

**Comment by daniel-luberda** [comment]
Just put this before you app initialization (`AppDelegate.cs`):
`ServicePointManager.ServerCertificateValidationCallback += (o, certificate, chain, errors) => true;`

BTW: 
`jsonString = client.GetStringAsync(randomProfile).Result;` can cause deadlocks, it's better to decorate method with `async` and change it to: `jsonString = await client.GetStringAsync(randomProfile);`

**Comment by ScorpDiesel** [comment]
DL:

I added the ServicePointManger to the Droid project (also to the PCL to be
sure) and it didn't work.  It seemed too much of a hassle just for mockups
so, I found another random api generator.  Thanks for your assistance.

**Comment by daniel-luberda** [comment]
👍 Ok, I'll close this one as it's not related to FFImageLoading, but rather https handling / security settings on iOS. Cheers.
