### ISSUE TITLE
SVG - Opacity always renders at 100%

### ISSUE THREAD

**Issue by flanakin** [luberda-molinet/FFImageLoading#436]
I have 100+ SVGs that I need to use and most of them use opacity for coloring/shading, but it seems like all semitransparent paths are rendered as 100% opaque. Is this a known bug?

**Comment by daniel-luberda** [comment]
Hi @flanakin,

FFImageLoading uses SkiaSharp under the hood for SVGs.

The class used for parsing SVG files is here: https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Svg/SkiaSharp.Svg/SKSvg.cs

- Do you use 'fill-opacity' attribute for transparency? It should be supported: https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Svg/SkiaSharp.Svg/SKSvg.cs#L673
- Does issue apply to all platforms? 

The code used for SVG parsing is here: 
https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SvgDataResolver.cs#L80-L101

**Comment by jj09** [comment]
Looks like opacity does not work, but <b>fill-</b>opacity works. e.g.,
```<svg width='50' height='50' viewBox='0 0 50 50'><rect width='50' height='50' fill='#000' opacity='0.5' /></svg>```
renders black rect

but this:
```<svg width='50' height='50' viewBox='0 0 50 50'><rect width='50' height='50' fill='#000' fill-opacity='0.5' /></svg>``` 
renders proper grayish one

Should FFImage or SkiaSharp fix this?

**Comment by daniel-luberda** [comment]
@jj09 Thanks for the info. It should definitely be fixed in SkiaSharp, I always incroporate the newest SkSvg class from there into FFImageLoading. 

BTW: Google released Skia roadmap and one of the point is to have advanced SVG parser, I hope it'll be done soon. https://docs.google.com/document/d/1C9w8qpPpdgNGThqmgNnTToLZ5UYK4TsUGl5X3B_q6oM/edit
