### ISSUE TITLE
Pre-Release versions (Appveyor CI)

### ISSUE THREAD

**Issue by petersondrew** [luberda-molinet/FFImageLoading#438]
Would it be possible to mark the Appveyor builds as pre-release builds, and append the build number as a postfix? E.g. Xamarin.FFImageLoading.2.2.6-pre282

This would make it easier to update to the latest pre-release in Visual Studio as currently the version published to Appveyor's nuget is the same as what's on nuget.org.

**Comment by daniel-luberda** [comment]
Hi @petersondrew It's already configured like that, but there was a stable release recently and there are no newer prerelease builds yet, so it shows stable as last prerelease too.

**Comment by petersondrew** [comment]
Ah, so the 2.2.6.282 build is what's on nuget.org currently? I just saw multiple 2.2.6 builds there and assumed that one of them, other than the very latest, was what was published to nuget.org.

**Comment by daniel-luberda** [comment]
Yes, if appveyor finds release github tag, then nuget is packed as a stable, otherwise it's always a prerelese :)

**Comment by petersondrew** [comment]
Ok, that clears it up then. Sorry to bug you 😃

**Comment by daniel-luberda** [comment]
No problem, if you have any questions just ask. Cheers :)
