### ISSUE TITLE
More verbose memory cache logging

### ISSUE THREAD

**Issue by franzdevel** [luberda-molinet/FFImageLoading#443]
This is just a nice-to-have feature request but I believe it would be helpful. In case of `Configuration.VerboseMemoryCacheLogging = true`, whenever an image is (i) loaded into or (ii) invalidated from the memory cache, could you include logging output indicating the current amount of data in the cache (i.e. sum of the sizes of all currently cached images)? That would be a great help in my case to better assess the impact of using FFImageLoading on memory, and to determine sensible values for `Configuration.MaxMemoryCacheSize`.

**Comment by daniel-luberda** [comment]
👍 I want to rewrite logging to contain more useful information, that would be a nice to have. I'll need some more free time to do that though :)

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/859
