### ISSUE TITLE
FFImageLoading Blur Transformation not showing on android

### ISSUE THREAD

**Issue by elertan** [luberda-molinet/FFImageLoading#444]
Hey, I'm building a xamarin forms application that has blurred backgrounds for the shown video material's included poster image.

Here's the code I used:
https://puu.sh/tgxHu/fa5c1cc5a9.png

This is what it looks like on iOS for example:
https://puu.sh/tgxM7/a38cf68890.png

This is what it looks like on android:
https://puu.sh/tgyJe/750c45fc5f.png

As you can see the image I had put there is not showing, here is proof that I have the transformation library installed in both projects.
https://puu.sh/tgyOu/ce494de60a.png

Am I missing something? Thanks for helping out.

**Comment by daniel-luberda** [comment]
@elertan Hi,

- What are you linker settings? https://developer.xamarin.com/guides/android/advanced_topics/linking/
- Do you test on emulator or a device? If device? What type / OS version? 
- Did you try different Radius settings for Android? (higher value)

**Comment by elertan** [comment]
Linker settings:
https://puu.sh/tizng/3662a655fb.png
On an emulator and real device, real device is running 4.4.2 and the emulator API level 19, I have also tested 23. Which none are working.

Changing the radius setting doesn't change on android at all, it looks like the image isnt even there

**Comment by elertan** [comment]
Update: the image does show on android when no transformation(s) are given

**Comment by daniel-luberda** [comment]
@elertan Did you try to download sample project from our repository? There's blur transformation example there, it works on all platforms. It's quite hard to help without any reproduction. https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/PageModels/TransformationPageModel.cs#L72

**Comment by elertan** [comment]
I've taken a look at your examples and instead of using the xaml approach I've used code, which wasn't working in the first place causing the image to dissappear again, however after some trial and error I got it working, I don't know what was causing the issue at first. Thank you!
