### ISSUE TITLE
BorderHexColor ignored?

### ISSUE THREAD

**Issue by hardcodet** [luberda-molinet/FFImageLoading#445]
Hi there

First of all thanks for a great control - it's been a pleasure to work with it!

I have a small issue: It didn't get the BorderHexColor of a `CircleTransformation `to work, no matter what I assigned to it. When searching for that property here on GitHub, I see only property assignments, but no code that actually would do anything with it. Did I miss anything, or Is this property obsolete or yet to get an actual implementation.

Thanks,
Philipp

**Comment by daniel-luberda** [comment]
Hi @hardcodet,

It should be working, `CircleTransformation` uses `RoundedTransformation` internally:

- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Droid/RoundedTransformation.cs#L94-L106
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Touch/RoundedTransformation.cs#L95-L110
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Windows/RoundedTransformation.cs#L117-L139

You must set `BorderSize` for it to work. Did you do this?

**Comment by hardcodet** [comment]
Duh. I feel very stupid now - it's working. I tried it late, but with a very small value. Only just now realized that I need smth more like "20" than "2" for the BorderSize.

Thanks for the quick feedback, Daniel :)

**Comment by daniel-luberda** [comment]
No problem. I think it would be nice to add some default minimal / max values to avoid confusion in future anyway. Cheers :)
