### ISSUE TITLE
FileWriteFinished is never being called

### ISSUE THREAD

**Issue by Almis90** [luberda-molinet/FFImageLoading#446]
The image url is [http://media2.giphy.com/media/26BROh4qLWbwq7A1a/200w_d.gif](http://media2.giphy.com/media/26BROh4qLWbwq7A1a/200w_d.gif)
```
 var control = itemView.FindViewById<GifImageView>(Resource.Id.giphy_gif_image_view);
 var vm = DataContext as Giphy;

ImageService.Instance.LoadUrl(vm.Images.FixedWidthDownsampled.Url, TimeSpan.FromHours(1)).Success(async (arg1, arg2) =>
{
    await Task.Delay(2000);
    if (arg1.FilePath != null)
    {
        control.SetBytes(File.ReadAllBytes(arg1.FilePath));
        control.StartAnimation();
    }
}).FileWriteFinished((fwi) => {

})
```

I put breakpoint but it not breaks there.

**Comment by EmmanVazz** [comment]
You need put that image into a view. So you need a .Into(_imageView) at the end of the LoadUrl,  [like in the wiki](https://github.com/luberda-molinet/FFImageLoading/wiki/API).

**Comment by Almis90** [comment]
It may work but why it should fire only when you loading into a view? The method name suggests that it will fire whenever file finishes writing.

**Comment by daniel-luberda** [comment]
@Almis90 @EmmanVazz 

Calling just `ImageService.Instance.LoadUrl` only creates image loading task, doesn't run it. To run task you have to call: 

- `DownloadOnly()` methods
- `Preload()` methods
- `Into()` methods

`Preload` /  `DownloadOnly ` will allow you to load image without loading it into a view.

**Comment by Almis90** [comment]
Sorry I don't know how I missed it from my code but at the end I already have `DownloadOnly()`

**Comment by akshay2000** [comment]
I have a similar problem. I have the image already assigned to an `ImageView` but also want to download it. I see following behavior:

- If the image is fully displayed into a view and then I trigger the download using `DownloadOnly` the `Success` callback is called. Other callbacks like `Progress` and `FileWriteFinished` are not called.
- If the image is not yet displayed into a view but process has started using `Into` and then I trigger `DownloadOnly` for the same Url, none of the callbacks are called. However, if I do `DownloadOnly` on the same Url after the image is displayed, `Success` is called.

The behavior above is on Android.
