### ISSUE TITLE
Image loading failed

### ISSUE THREAD

**Issue by AntonisSt** [luberda-molinet/FFImageLoading#447]
Hi I am using ffImageLoading in an Android application. I want to show some images I download from the web in a viewpager. I have used the code that is given in the official documentation using viewpager with ffimageloading. If I wait for the first image to be downloaded everything works flawlessly. But if I scroll to another one before the first one gets loaded then it throws a dispatchexceptioninfo and every retry(count, delay) fails. I have tried changing the retrycount and retrydelay but it didn't work. Do you have any idea what it might be wrong? I use the following code:

```
public class CarouselFragment : Android.Support.V4.App.Fragment
{
        private readonly string _image;
        public CarouselFragment() {}

        public CarouselFragment(string image)
        {
            _image = image;
        }
        

        public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
        {
            // Use this to return your custom view for this Fragment
            // return inflater.Inflate(Resource.Layout.YourFragment, container, false);
            var rootView = inflater.Inflate(Resource.Layout.fragment_carousel, null, false);

            var imgBackground = rootView.FindViewById<ImageViewAsync>(Resource.Id.imgCarousel);

            ImageService.Instance.LoadUrl(_image, TimeSpan.FromMinutes(5))
                .Retry(3, 200)
                .FadeAnimation(true, true)
                .Into(imgBackground);
          
            return rootView;
        }
        

}
```

**Comment by daniel-luberda** [comment]
@AntonisSt Could you give me a full stack trace? It may be connection problems related.

**Comment by AntonisSt** [comment]
My log for one image. As I scroll, the respective message shows up in my log for all the images.
`
01-11 09:39:27.160 I/mono-stdout( 9132): Image loading failed: https://sslphotos.jato.com/PHOTO400/SSCD/MERCEDES/E-CLASS/2017/4SA.JPG
01-11 09:39:27.160 I/mono-stdout( 9132): FFImageLoading.DownloadAggregateException: One or more errors occurred. ---> System.FieldAccessException: Field `System.Net.HttpWebRequest:ResendContentFactory' is inaccessible from method `System.Net.Http.HttpClientHandler/<SendAsync>c__async0:MoveNext ()'
01-11 09:39:27.160 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x00031] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471 
01-11 09:39:27.160 I/mono-stdout( 9132):   at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0001f] in <6e92ad09d0bd49b996fe288564eee203>:0 
01-11 09:39:27.160 I/mono-stdout( 9132):   at System.Net.Http.HttpMessageInvoker.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/System.Net.Http/System.Net.Http/HttpMessageInvoker.cs:68 
01-11 09:39:27.160 I/mono-stdout( 9132):   at System.Net.Http.HttpClient.<SendAsync>__BaseCallProxy0 (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x7f69502da8 + 0x0005f> in <6e92ad09d0bd49b996fe288564eee203>:0 
01-11 09:39:27.161 I/mono-stdout( 9132):   at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x00071] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:272 
01-11 09:39:27.161 I/mono-stdout( 9132): --- End of stack trace from previous location where exception was thrown ---
01-11 09:39:27.162 I/mono-stdout( 9132):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-11 09:39:27.162 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-11 09:39:27.162 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-11 09:39:27.162 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-11 09:39:27.162 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-11 09:39:27.162 I/mono-stdout( 9132):   at FFImageLoading.Cache.DownloadCache+<DownloadAsync>d__13.MoveNext () [0x000ef] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:96 
01-11 09:39:27.162 I/mono-stdout( 9132): --- End of stack trace from previous location where exception was thrown ---
01-11 09:39:27.162 I/mono-stdout( 9132):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-11 09:39:27.162 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-11 09:39:27.163 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-11 09:39:27.163 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-11 09:39:27.163 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-11 09:39:27.163 I/mono-stdout( 9132):   at FFImageLoading.Cache.DownloadCache+<>c__DisplayClass12_0+<<DownloadAndCacheIfNeededAsync>b__0>d.MoveNext () [0x00060] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:55 
01-11 09:39:27.163 I/mono-stdout( 9132): --- End of stack trace from previous location where exception was thrown ---
01-11 09:39:27.163 I/mono-stdout( 9132):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-11 09:39:27.163 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-11 09:39:27.163 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-11 09:39:27.163 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-11 09:39:27.163 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-11 09:39:27.163 I/mono-stdout( 9132):   at FFImageLoading.Retry+<DoAsync>d__0`1[T].MoveNext () [0x00047] in C:\projects\ffimageloading\source\FFImageLoading.Common\Helpers\Retry.cs:17 
01-11 09:39:27.163 I/mono-stdout( 9132):    --- End of inner exception stack trace ---
01-11 09:39:27.163 I/mono-stdout( 9132):   at FFImageLoading.Retry+<DoAsync>d__0`1[T].MoveNext () [0x0016f] in C:\projects\ffimageloading\source\FFImageLoading.Common\Helpers\Retry.cs:31 
01-11 09:39:27.163 I/mono-stdout( 9132): --- End of stack trace from previous location where exception was thrown ---
01-11 09:39:27.164 I/mono-stdout( 9132):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-11 09:39:27.164 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-11 09:39:27.164 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-11 09:39:27.164 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-11 09:39:27.164 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-11 09:39:27.164 I/mono-stdout( 9132):   at FFImageLoading.Cache.DownloadCache+<DownloadAndCacheIfNeededAsync>d__12.MoveNext () [0x00425] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:54 
01-11 09:39:27.164 I/mono-stdout( 9132): --- End of stack trace from previous location where exception was thrown ---
01-11 09:39:27.165 I/mono-stdout( 9132):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-11 09:39:27.165 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-11 09:39:27.165 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-11 09:39:27.165 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-11 09:39:27.165 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-11 09:39:27.166 I/mono-stdout( 9132):   at FFImageLoading.DataResolvers.UrlDataResolver+<Resolve>d__7.MoveNext () [0x00048] in C:\projects\ffimageloading\source\FFImageLoading.Droid\DataResolvers\UrlDataResolver.cs:23 
01-11 09:39:27.166 I/mono-stdout( 9132): --- End of stack trace from previous location where exception was thrown ---
01-11 09:39:27.166 I/mono-stdout( 9132):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-11 09:39:27.166 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-11 09:39:27.166 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-11 09:39:27.166 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-11 09:39:27.166 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-11 09:39:27.166 I/mono-stdout( 9132):   at FFImageLoading.Work.ImageLoaderTask`2+<RunAsync>d__109[TImageContainer,TImageView].MoveNext () [0x0022e] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:407 
01-11 09:39:27.166 I/mono-stdout( 9132): ---> (Inner Exception #0) System.FieldAccessException: Field `System.Net.HttpWebRequest:ResendContentFactory' is inaccessible from method `System.Net.Http.HttpClientHandler/<SendAsync>c__async0:MoveNext ()'
01-11 09:39:27.166 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x00031] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471 
01-11 09:39:27.167 I/mono-stdout( 9132):   at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0001f] in <6e92ad09d0bd49b996fe288564eee203>:0 
01-11 09:39:27.167 I/mono-stdout( 9132):   at System.Net.Http.HttpMessageInvoker.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/System.Net.Http/System.Net.Http/HttpMessageInvoker.cs:68 
01-11 09:39:27.167 I/mono-stdout( 9132):   at System.Net.Http.HttpClient.<SendAsync>__BaseCallProxy0 (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x7f69502da8 + 0x0005f> in <6e92ad09d0bd49b996fe288564eee203>:0 
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x00071] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:272 
01-11 09:39:27.168 I/mono-stdout( 9132): --- End of stack trace from previous location where exception was thrown ---
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-11 09:39:27.168 I/mono-stdout( 9132):   at FFImageLoading.Cache.DownloadCache+<DownloadAsync>d__13.MoveNext () [0x000ef] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:96 
01-11 09:39:27.168 I/mono-stdout( 9132): --- End of stack trace from previous location where exception was thrown ---
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-11 09:39:27.168 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-11 09:39:27.169 I/mono-stdout( 9132):   at FFImageLoading.Cache.DownloadCache+<>c__DisplayClass12_0+<<DownloadAndCacheIfNeededAsync>b__0>d.MoveNext () [0x00060] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:55 
01-11 09:39:27.169 I/mono-stdout( 9132): --- End of stack trace from previous location where exception was thrown ---
01-11 09:39:27.169 I/mono-stdout( 9132):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
01-11 09:39:27.169 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
01-11 09:39:27.169 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
01-11 09:39:27.169 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
01-11 09:39:27.169 I/mono-stdout( 9132):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
01-11 09:39:27.169 I/mono-stdout( 9132):   at FFImageLoading.Retry+<DoAsync>d__0`1[T].MoveNext () [0x00047] in C:\projects\ffimageloading\source\FFImageLoading.Common\Helpers\Retry.cs:17 <---
`

**Comment by molinch** [comment]
Hi @AntonisSt 
This has nothing to do with FFImageLoading it seems to be related to HttpClient on Mono or to ModernHttpClient.

See: https://github.com/paulcbetts/ModernHttpClient/issues/228
and Couchbase Lite similar issue: https://github.com/couchbase/couchbase-lite-net/issues/777

**Comment by AntonisSt** [comment]
Ok thx

**Comment by molinch** [comment]
In fact it is a Xamarin bug see: https://bugzilla.xamarin.com/show_bug.cgi?id=46176
