### ISSUE TITLE
An HttpWebRequest was added to the ConnectionGroup queue because the connection limit was reached

### ISSUE THREAD

**Issue by JeremyBP** [luberda-molinet/FFImageLoading#449]
Hi and thanks fo your work!
This error appears only with the FF.XF 2.2.6 and only on iOS like discribed in this previous [issue](https://github.com/luberda-molinet/FFImageLoading/issues/182#issuecomment-217867185).
Downgrading to 2.2.5 (seems to) solved the problem.

**Comment by daniel-luberda** [comment]
`ConnectionGroup queue issue` is definitely not related to FFImageLoading. It's related to mono .NET http client implementation. You could try to use ModernHttpClient HttpClientHandler which could be provided in a custom FFImageLoading config: 

```C#
var config = new FFImageLoading.Config.Configuration()
{
    HttpClient = new HttpClient(new NativeClientHandler),
};
ImageService.Instance.Initialize(config);
```

**Comment by JeremyBP** [comment]
Ok thank you for your time, will give a try.

**Comment by daniel-luberda** [comment]
I reviewed code once again as I was curious why 2.2.5 works for you and 2.2.6 doesn't. There was a small change in Download implementation. Instead `response.Content.ReadAsByteArrayAsync()`, I replaced it with `response.Content.ReadAsStreamAsync()` to allow DownloadProgress support. I made some changes to use old method if no download progress is defined.

**Comment by JeremyBP** [comment]
I just updated to 2.2.7 and implemented ModernHttpClient.
Actualy, it appears to throw sometimes (not everytime), on any platform (Android & iOS), with message (no more connection limit):
`01-11 12:19:35.580 I/mono-stdout(23025): An error occured while writing to disk cache for 927492C3881B4937749D9E018165B55B
An error occured while writing to disk cache for 927492C3881B4937749D9E018165B55B
01-11 12:19:35.580 I/mono-stdout(23025): System.NullReferenceException: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
  at FFImageLoading.Cache.DownloadCache+<>c__DisplayClass12_0.<DownloadAndCacheIfNeededAsync>b__2 () [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:71 
  at FFImageLoading.Cache.SimpleDiskCache+<>c__DisplayClass14_0+<<AddToSavingQueueIfNotExistsAsync>b__0>d.MoveNext () [0x001de] in C:\projects\ffimageloading\source\FFImageLoading.Shared\Cache\SimpleDiskCache.cs:107 
01-11 12:19:35.580 I/mono-stdout(23025):   at FFImageLoading.Cache.DownloadCache+<>c__DisplayClass12_0.<DownloadAndCacheIfNeededAsync>b__2 () [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:71 
01-11 12:19:35.580 I/mono-stdout(23025):   at FFImageLoading.Cache.SimpleDiskCache+<>c__DisplayClass14_0+<<AddToSavingQueueIfNotExistsAsync>b__0>d.MoveNext () [0x001de] in C:\projects\ffimageloading\source\FFImageLoading.Shared\Cache\SimpleDiskCache.cs:107`

Don't know if you want me to open a new issue about it.
Tell me if you want me to ref project directly to get more debug details.

**Comment by daniel-luberda** [comment]
@JeremyBP It should be fixed with this: https://github.com/luberda-molinet/FFImageLoading/commit/f07420ed1c0930762e96517c9a56c03984c69d61

**Comment by JeremyBP** [comment]
Nice! I'll try it as soon as available on nuget (if you plan to push it or just tell me if not and I'll do it by proj ref).
