### ISSUE TITLE
Disk cache not working 

### ISSUE THREAD

**Issue by TheAndroidMachine** [luberda-molinet/FFImageLoading#450]
I have noted that at least on Android using Xamarin Forms the disk cache is not working.

To reproduce the issue:
1- Open the app and load some images from the web
2- Press home
3- Kill the app with the task manager
4- Kill the internet connection (airplane mode)
5- Reopen the app
Result: No images are shown.

Do I need to configure or initialize something? Are additional permissions need?

**Comment by daniel-luberda** [comment]
As you see from here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Shared/Cache/SimpleDiskCache.cs#L55-L58 the cache is stored in temp cache directory. Are you sure you don't clear it between app deploy?

**Comment by molinch** [comment]
@TheAndroidMachine any news?

**Comment by TheAndroidMachine** [comment]
Yes, sorry for my delay. 
It is actually working now but I can not tell why it wasn't working before. The only thing I'm doing differently is specifying the path when initializing the service. But it shouldn't make any difference since it is also done internally if no path is specify.

**Comment by daniel-luberda** [comment]
@TheAndroidMachine Is the path you specify the same as a default one?

**Comment by TheAndroidMachine** [comment]
Yes, think so. 
On Android MainActivity:
`string tmpPath = this.CacheDir.AbsolutePath;`
`string cachePath = System.IO.Path.Combine(tmpPath, "myapp");`
`var config = new FFImageLoading.Config.Configuration()
            {
                VerboseLogging = false,
                VerbosePerformanceLogging = false,
                VerboseMemoryCacheLogging = false,
                VerboseLoadingCancelledLogging = false, 
                HttpClient = new System.Net.Http.HttpClient(new Xamarin.Android.Net.AndroidClientHandler()),
                DiskCachePath = cachePath,
            };`
`FFImageLoading.ImageService.Instance.Initialize(config);`
