### ISSUE TITLE
CachedImage on 2.2.7 slow to stuck on iOS

### ISSUE THREAD

**Issue by leaguefun** [luberda-molinet/FFImageLoading#453]
I was using CachedImage ver 2.2.5 on Xamarin.Form iOS project and everthing working fine .... but updated to 2.2.7 yesterday ... the performance for disk cache was terrible, especially on the CacheImage within viewcell in listview. The application struck while refreshing the image during scrolling among the listview :(

**Comment by daniel-luberda** [comment]
@leaguefun What if you downgrade? Does performance get better? Is it possible, you can make a reproduction?

> the performance for disk cache was terrible

There weren't any changes to disk cache implementation.

**Comment by leaguefun** [comment]
There's very strange ... I am using CachedImage all over the application for image loading, after updated to 2.2.7, it's obviously take time to load image than before (2.2.5). I didn't made any change to my code ...

**Comment by leaguefun** [comment]
Did 2.2.7 come with any addition configurations ?

**Comment by daniel-luberda** [comment]
@leaguefun But did you try to downgrade and see it gets better again? 

> Did 2.2.7 come with any addition configurations ?
No.

**Comment by leaguefun** [comment]
Yes, downgraded to 2.2.5 (since I used before) then resumed normal

**Comment by daniel-luberda** [comment]
Is it possible you could send me some simple reproduction, so I could test it & fix it?

**Comment by leaguefun** [comment]
I will try to get the application output for the scenario, and send it to you if possible, many thanks.

**Comment by daniel-luberda** [comment]
Also please read this: https://github.com/luberda-molinet/FFImageLoading/wiki/Native-Http-handlers-=-better-performance

**Comment by daniel-luberda** [comment]
Any news?

**Comment by lecnierfreeman** [comment]
I can confirm in IOS even with version 2.2.8 the first time you open the app loading already cached images takes a few more seconds compared with version 2.2.5. In my case I'm displaying 8 images at the same time and is really noticeable. After the first run you close the app and then open it again with version 2.2.8 the images takes more than 5 seconds, maybe is some change to the loading images form cache? I tested in real device iphone 7+ debug with NSUrlSession in HttpClientHandler option.

**Comment by daniel-luberda** [comment]
@lecnierfreeman  I noticed that too. It can be easily solved by preloading any file on app startup. Any ideas? Maybe there's a deadlock somewhere.

**Comment by alanspires** [comment]
I'm seeing this too. Has to be blocking somewhere.

**Comment by daniel-luberda** [comment]
Found it :) Fixed, stable soon.

**Comment by candidodmv** [comment]
Hi @daniel-luberda This strange behavior was fixed? Because I'm with the same problem.
Thanks !

**Comment by daniel-luberda** [comment]
Hi @candidodmv Yes, it was fixed in 2.2.9, but there's also one similar fix which didn't get into stable yet: https://github.com/luberda-molinet/FFImageLoading/commit/7fc0fdfeea300cefba1a83ac7effba68502b7bac

**Comment by candidodmv** [comment]
All right, maybe this commit fix this issue. Thanks for quick answer. I'm waiting for this release stable commit.

**Comment by candidodmv** [comment]
@daniel-luberda has date to the refered commit will be pull to release? Thanks

**Comment by daniel-luberda** [comment]
@candidodmv Did newest prerelease fix the issue for you?

**Comment by candidodmv** [comment]
@daniel-luberda I'm was waiting for release version, but I've installed the pre-release version, and problem is going on. There is a freeze behavior when navigate to a page that make usage of FFImageLoading for more or less 5 seconds until show up the content page.
