### ISSUE TITLE
Invalidating cache entry with downsampling doesn't work

### ISSUE THREAD

**Issue by adusak** [luberda-molinet/FFImageLoading#454]
Hello,

I have an issue with removing image that was downsampled from cache, even if I set the removeSimilar parameter to true. If I don't use downsampling invalidating the cache key works and the image reloads.

Usage example:
`ImageService.Instance.LoadFile(page.PreviewImage.Path).FadeAnimation(true, true).DownSampleInDip((int)newView.Frame.Width, (int)newView.Frame.Height).Into(newView.ImageView);`

And the cache invalidation:
`await ImageService.Instance.InvalidateCacheEntryAsync(Page.PreviewImage.Path, FFImageLoading.Cache.CacheType.All, true);
`

I am using the latest version from nuget and iOS.

**Comment by daniel-luberda** [comment]
Hi @adusak Could you test 2.2.8-pre-303 if it also has the same issue? There were some changes.

**Comment by daniel-luberda** [comment]
Any news?

**Comment by adusak** [comment]
Hello, sorry for the delayed response. I just tried with version 2.2.8 and it seems to be working well.
