### ISSUE TITLE
FFImageLoading crash on CancelLoading() if scrolling fast from top to bottom and viceversa

### ISSUE THREAD

**Issue by palla89** [luberda-molinet/FFImageLoading#455]
Hi! I have this problem in android while scrolling as soon as my Page appears and it's loading:

![schermata 2017-01-16 alle 13 04 30](https://cloud.githubusercontent.com/assets/12301205/21982433/9487e26e-dbec-11e6-9872-a3f438c3aa86.png)

I'm loading images from file, and using FlowListView to display them! On iOS it seems working fine, on Android I must wait to scroll and cells content appear wrong for a fraction of second. Can you help me?

**Comment by daniel-luberda** [comment]
@palla89 You have mixed different FFImageLoading dlls versions. Please remove all nuget packages, delete `bin`/`obj` folders, clean solution and install packages once again.
