### ISSUE TITLE
.SVG in xamarin.forms using SvgImageSourceConverter and system resources

### ISSUE THREAD

**Issue by iWeaverMan** [luberda-molinet/FFImageLoading#456]
Would you please show an example of .SVG in XAML xamarin.forms usage with SvgImageSourceConverter and an image from ios, android, and UWP resources? I seem fail to do that.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/SvgSamplePage.xaml

Here's an example. You can clone the project and test it on your own.

**Comment by iWeaverMan** [comment]
Thanks! The exaple has helped me enormously.
