### ISSUE TITLE
Resize image into view

### ISSUE THREAD

**Issue by mscrocdile** [luberda-molinet/FFImageLoading#458]
Is it possible to automatically resize image in dynamically sized view?
`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"`
`            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"`
`             xmlns:forms="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"`
`             x:Class="SmileShow.Pages.Test">`
`  <forms:CachedImage  Source = "any bigger png"`
`  ></forms:CachedImage>`
`</ContentPage>`
It means show the picture in mobile phone small, in landscape mode bigger, in tablet big by the current contentpage/view size? I tried multiple options but no success. Only if i make this:
`<AbsoluteLayout>`
`  <forms:CachedImage  Source = "any bigger png"`
`  ></forms:CachedImage>`
`</AbsoluteLayout>`
it starts to do what i need but if orientation is changed from portrait to landscape it breaks again.
I'm using android and xamarin forms.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#downsampletoviewsize-bool-default-false
