### ISSUE TITLE
App crashes when attempting to load a PNG with transparency

### ISSUE THREAD

**Issue by pauldiston** [luberda-molinet/FFImageLoading#459]
We have deployed our application on to rugged devices (Honeywell CT50), these devices have been repaired, which I believe has involved some software upgrade, as the build numbers are slightly different. Our application installs successfully however when it is launched the app crashes. After debugging through this I have found that if I try and load PNG images with transparency then the app crashes. 

The output window lists the following :-
01-18 11:19:56.559 E/mono-rt (16051): Attempting native Android stacktrace:
01-18 11:19:56.559 E/mono-rt (16051): 
01-18 11:19:56.579 E/mono-rt (16051):   at ???+0 [0x0]
01-18 11:19:56.579 E/mono-rt (16051):   at SkBitmapProcShader::shadeSpan(int, int, unsigned int*, int)+160 [0x405967bc]
01-18 11:19:56.579 E/mono-rt (16051):   at SkARGB32_Shader_Blitter::blitRect(int, int, int, int)+406 [0x404ceb0f]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+876985 [0x404f81b9]
01-18 11:19:56.579 E/mono-rt (16051):   at SkScan::FillIRect(SkIRect const&, SkRegion const*, SkBlitter*)+222 [0x404f829b]
01-18 11:19:56.579 E/mono-rt (16051):   at SkScan::FillRect(SkRect const&, SkRegion const*, SkBlitter*)+136 [0x404f8361]
01-18 11:19:56.579 E/mono-rt (16051):   at SkScan::FillRect(SkRect const&, SkRasterClip const&, SkBlitter*)+52 [0x404f844d]
01-18 11:19:56.579 E/mono-rt (16051):   at SkDraw::drawRect(SkRect const&, SkPaint const&) const+216 [0x404d8e37]
01-18 11:19:56.579 E/mono-rt (16051):   at SkDraw::drawBitmap(SkBitmap const&, SkMatrix const&, SkPaint const&) const+360 [0x404da391]
01-18 11:19:56.579 E/mono-rt (16051):   at SkCanvas::internalDrawBitmap(SkBitmap const&, SkMatrix const&, SkPaint const*)+106 [0x404d3667]
01-18 11:19:56.579 E/mono-rt (16051):   at SkCanvas::drawBitmap(SkBitmap const&, float, float, SkPaint const*)+76 [0x404d3709]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+175751 [0x40c13e87]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+176221 [0x40c1405d]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+177473 [0x40c14541]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+131357 [0x40c0911d]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+93817 [0x40bffe79]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+83239 [0x40bfd527]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+82971 [0x40bfd41b]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+119203 [0x40c061a3]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+423973 [0x401e6825]
01-18 11:19:56.579 E/mono-rt (16051):   at dvmPlatformInvoke+112 [0x4154334c]
01-18 11:19:56.579 E/mono-rt (16051):   at dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398 [0x41573fcf]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+169952 [0x4154c7e0]
01-18 11:19:56.579 E/mono-rt (16051):   at dvmMterpStd(Thread*)+76 [0x41553c6c]
01-18 11:19:56.579 E/mono-rt (16051):   at dvmInterpret(Thread*, Method const*, JValue*)+184 [0x41551304]
01-18 11:19:56.579 E/mono-rt (16051):   at dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+392 [0x41586715]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+439835 [0x4158e61b]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+169952 [0x4154c7e0]
01-18 11:19:56.579 E/mono-rt (16051):   at dvmMterpStd(Thread*)+76 [0x41553c6c]
01-18 11:19:56.579 E/mono-rt (16051):   at dvmInterpret(Thread*, Method const*, JValue*)+184 [0x41551304]
01-18 11:19:56.579 E/mono-rt (16051):   at dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336 [0x41586431]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+314295 [0x4156fbb7]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+319155 [0x401cceb3]
01-18 11:19:56.579 E/mono-rt (16051):   at android::AndroidRuntime::start(char const*, char const*, bool)+358 [0x401cdbdf]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+4195 [0x40089063]
01-18 11:19:56.579 E/mono-rt (16051):   at __libc_init+50 [0x400b54a3]
01-18 11:19:56.579 E/mono-rt (16051):   at ???+3456 [0x40088d80]
01-18 11:19:56.579 E/mono-rt (16051): 
01-18 11:19:56.579 E/mono-rt (16051): =================================================================

I am not sure what has changed between the two builds but PNG images with transparency load successfully on the older build.

Do you have any idea what the problem might be?

**Comment by daniel-luberda** [comment]
@pauldiston Are you sure those devices don't have RAM issues?

**Comment by pauldiston** [comment]
As the same code works successfully on an older build of device then I am not sure whether there are RAM issues, unless the newer build has put more of a demand on the RAM.

**Comment by daniel-luberda** [comment]
It's really hard to reproduce / debug as it looks like it's a device specific issue. Here are some similar threads: 

- http://stackoverflow.com/questions/18284525/android-4-3-specific-crash-calling-packagemanager-getdrawable
- http://stackoverflow.com/questions/36507316/app-random-crashes-with-fatal-signal-7-sigbus-code-2-or-fatal-signal-11-sigs

**Comment by molinch** [comment]
@pauldiston Which device is it?
