### ISSUE TITLE
Can't add Xamarin.FFImageLoading.Svg to UWP project

### ISSUE THREAD

**Issue by akonovalov** [luberda-molinet/FFImageLoading#461]
Hi,
Trying to add Xamarin.FFImageLoading.Svg to my UWP project

Install-Package Xamarin.FFImageLoading.Svg -Version 2.2.7 

Result:
Install-Package : Unable to resolve System.Xml.Linq (>= 4.0.0) for UAP,Version=v10.0.
At line:1 char:1
+ Install-Package Xamarin.FFImageLoading.Svg -Version 2.2.7
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Any pointers at what I'm missing?

**Comment by daniel-luberda** [comment]
Could you test the newest pre? It should be fixed, it was a nuspec file issue

**Comment by akonovalov** [comment]
Daniel,
Yes, can confirm that the issue has been resolved in the pre version.

**Comment by daniel-luberda** [comment]
Thanks for info 👍
