### ISSUE TITLE
FFTransformation: can't seem to get it to work correctly 

### ISSUE THREAD

**Issue by LukasThijs** [luberda-molinet/FFImageLoading#463]
Hey,

I am  using your component to render a image and I want to combine this with the blur transformation that you are providing. 

I have downloaded and installed the Nuget package and it seems to find the package itself. But somehow the image won't show up and a white page is shown. 

I am using the sample code that you have provided in this Git. When I for example remove the transformation part the image is shown.

The code example below results in image being shown in the middle:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:forms="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             xmlns:controls="clr-namespace:BNApp.Controls;assembly=BNApp"
             xmlns:transformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
             x:Class="BNApp.Tests.test">
    <ContentPage.Content>
        <ScrollView>
            <StackLayout>

                <forms:CachedImage HorizontalOptions="Center" VerticalOptions="Center"
				     DownsampleToViewSize="true"
					Aspect="AspectFit" HeightRequest="400" WidthRequest="400" Source="BNAppLoginBackground.jpg">
                 
                </forms:CachedImage>

                <Label Text="BlurredTransformation" HorizontalTextAlignment="Center"/>

                <Button Text="Load another image" Command="{Binding LoadAnotherCommand}"/>

            </StackLayout>
        </ScrollView>
    </ContentPage.Content>
    </ContentPage>
```

And this code shows nothing when used:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:forms="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             xmlns:controls="clr-namespace:BNApp.Controls;assembly=BNApp"
             xmlns:transformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
             x:Class="BNApp.Tests.test">
    <ContentPage.Content>
        <ScrollView>
            <StackLayout>

                <forms:CachedImage HorizontalOptions="Center" VerticalOptions="Center"
				     DownsampleToViewSize="true"
					Aspect="AspectFit" HeightRequest="400" WidthRequest="400" Source="BNAppLoginBackground.jpg">
                    <forms:CachedImage.Transformations>
                        <transformations:BlurredTransformation Radius="40"/>
                    </forms:CachedImage.Transformations>
                </forms:CachedImage>

                <Label Text="BlurredTransformation" HorizontalTextAlignment="Center"/>

                <Button Text="Load another image" Command="{Binding LoadAnotherCommand}"/>

            </StackLayout>
        </ScrollView>
    </ContentPage.Content>
    </ContentPage>
```

I have uploaded screenshots to for the following example and I do hope someone could help me out to fix this problem. http://imgur.com/a/l7qng

Also I am using Xamarin.Forms.

Thanks in advance and have a great weekend!

Luuk

**Comment by daniel-luberda** [comment]
It's probably Xamarin.Forms linker issue. Just reference you transformation in a platform specific project. Something like this: 

`var ignore = new BlurredTransformation()`

**Comment by LukasThijs** [comment]
I have added a reference to the transformation in the platform specific project maps. Still it didn't work sadly ;/

**Comment by LukasThijs** [comment]
Well let me be more specific the issue only happens when using the blurred transformation all other transformations work.

**Comment by daniel-luberda** [comment]
@LukasThijs 
- What is you app target / min SDK version?
- Is it device specific? 
- Does it work in Debug builds?
- Please note that it's very important to add Transformations packages to both PCL / platform specific projects.

**Comment by LukasThijs** [comment]
@daniel-luberda 

1. What is you app target / min SDK version?

The target level is set to API level 23 , SDK 6.0 and higher.

2. Is it device specific?

I don't know I am using the Android emulator. Tried both on Tablet and phone emulator still no result.

3. Does it work in Debug builds?

I am using debug build it's not release yet.

4. Please note that it's very important to add Transformations packages to both PCL / platform specific projects.

I have used the Nuget to install this and I have double checked of the reference is added to the project. Also I have the following information inside the .Droid packages file:

```
  <package id="Xamarin.FFImageLoading" version="2.2.8-pre-311" targetFramework="monoandroid60" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.8-pre-311" targetFramework="monoandroid60" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.8-pre-311" targetFramework="monoandroid60" />
  <package id="Xamarin.Forms" version="2.3.4.184-pre1" targetFramework="monoandroid60" />
```

Even inside the MainActivity.cs is the following:

` var blurred =new BlurredTransformation();`

**Comment by LukasThijs** [comment]
I have as you can see included the Xamarin.Forms package version so maybe that's usefull :)

**Comment by daniel-luberda** [comment]
@LukasThijs I made some additional fixes. New nuget should be released today. Could you try it? If it still won't work for you, you could use a legacy mode. Just set (in Android project): `BlurredTrasnformation.LegacyModel = true`.

**Comment by LukasThijs** [comment]
Hey!

Excuse me for the late reply, had a day off. Anyway I can confirm that the latest pre-release fixes the issue and the transformation now works properly!

Thanks for your help and time!

Luuk

**Comment by daniel-luberda** [comment]
Thanks for info! 👍
