### ISSUE TITLE
CacheKeyFactory problem

### ISSUE THREAD

**Issue by LuigiMaestrelli** [luberda-molinet/FFImageLoading#464]
I'm trying to use CacheKeyFactory to control some invalidade cache logic.
On the cached image, I set up the CacheKeyFactory to new CustomCacheKeyFactory();
My CustomCacheKeyFactory class, is returning correctly the new key.

But when I called `await ImageService.Instance.InvalidateCacheEntryAsync(cacheKey, FFImageLoading.Cache.CacheType.All);` and try to download the image again from the same URL, it uses the image stored on cache.

To test the CacheKeyFactory, I'm listening the Success event and the CacheKey and UserCustomCacheKey are both null.

What am I missing?

Update: I tested on Android with the version 2.2.7 and 2.2.8-pre-305

**Comment by daniel-luberda** [comment]
I made some refactorings, but I don't thing that it will fix your issue. If on `Success` callback reports `CacheKey=null`, then you didn't assign custom cache key correctly. Could you show your code?

**Comment by LuigiMaestrelli** [comment]
My image constructor looks like this:

```
var myImage = new CachedImage {
            CacheDuration = TimeSpan.FromDays(30),
            DownsampleToViewSize = true,
            RetryCount = 3,
            RetryDelay = 250,
            LoadingPlaceholder = "ic_person_grey.png",
            ErrorPlaceholder = "ic_person_grey.png",
            CacheKeyFactory = new MyCacheKeyFactory()
};
```

And my CacheKeyFactory is like this:

```
public class UseallCacheKeyFactory : ICacheKeyFactory
    {
        public string GetKey(ImageSource imageSource, object bindingContext)
        {
            if (imageSource == null)
                return null;

            var uriImageSource = imageSource as UriImageSource;
            if (uriImageSource != null)
                return uriImageSource.Uri.ToString();

            var fileImageSource = imageSource as FileImageSource;
            if (fileImageSource != null)
                return fileImageSource.File;

            var streamImageSource = imageSource as StreamImageSource;
            if (streamImageSource != null)
                return streamImageSource.Stream.GetHashCode().ToString();

            return null;
        }
    }
```

Debugging, this class return the right key

**Comment by daniel-luberda** [comment]
Looks good. Did you try the latest prerelease if it solves your issue? Otherwise, I think I'll need some reproduction.

**Comment by LuigiMaestrelli** [comment]
@daniel-luberda 

I've attached a really simple app to reproduce and I tried just on on Android. 
I came across this issue when I was trying to invalidate a disk and memory cache to force the CachedImage to download the new picture.

[TestFFImage.ZIP](https://github.com/luberda-molinet/FFImageLoading/files/735670/TestFFImage.ZIP)

**Comment by LuigiMaestrelli** [comment]
@daniel-luberda 

Did you find anything about it?

**Comment by daniel-luberda** [comment]
@LuigiMaestrelli Not yet :(

**Comment by daniel-luberda** [comment]
@LuigiMaestrelli  Can you reproduce it with 2.2.10?

**Comment by LuigiMaestrelli** [comment]
No, I can't reproduce with the new version.

Thank you.

**Comment by daniel-luberda** [comment]
Great :)
