### ISSUE TITLE
Not all SVG Images are parsed correctly

### ISSUE THREAD

**Issue by brepetti** [luberda-molinet/FFImageLoading#465]
I am trying to load some SVG images but I am not having any luck with Xamarin Forms for iOS / Android.

I'm simply calling:  _Image.Source = SvgImageSource.FromFile("jack.svg");

I've tried putting the svg file in multiple places.  What is the correct location?  In the drawable folder or the root of the Android app?

**Comment by brepetti** [comment]
Looks like this could be because the SVG file is not compatible with SkiaSharp.

I tried another svg file produced from inkscape and did not have any trouble loading.

The svg files that give me trouble were exported from Adobe Illustrator using an SVG plugin.

I will see if our designer can use a different program to output the svg.

**Comment by daniel-luberda** [comment]
Yes, the SVG parser is quite simple right now, here's the class that is used: https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Svg/SkiaSharp.Svg/SKSvg.cs
