### ISSUE TITLE
Some suspicious code 

### ISSUE THREAD

**Issue by 3-50** [luberda-molinet/FFImageLoading#466]
Hi guys. Code check please.
**The return value of function 'Insert' is required to be utilized.** 
FFImageLoading.Touch\Extensions\ColorExtensions.cs 16
`                        hexColor.Insert(0, "#");`
correct code:                        `hexColor = hexColor.Insert(0, "#");`

FImageLoading.Droid\Extensions\ColorExtensions.cs 16
                        `hexColor.Insert(0, "#");`

FFImageLoading.Transformations.Windows\RoundedTransformation.cs 128
                        `borderHexColor.Insert(0, "#");`

**Expression 'similarRunningTask != null' is always true.** 
FFImageLoading.Common\Work\WorkScheduler.cs 213
```
            similarRunningTask = PendingTasks.FirstOrDefaultByRawKey(task.KeyRaw);
            if (similarRunningTask == null)
            {
                Interlocked.Increment(ref _statsTotalPending);
                Enqueue(task);
            }
            else if (similarRunningTask != null)
            {....
```

**Expression 'sdDrawable' is always not null.** 
FFImageLoading.Droid\Targets\BitmapTarget.cs 38
```
SelfDisposingBitmapDrawable drawable = null;
                _drawableWeakReference.TryGetTarget(out drawable);
                var sdDrawable = drawable as SelfDisposingBitmapDrawable;

                if (sdDrawable != null)
                {
                    sdDrawable?.SetIsDisplayed(true);
                }
```

**Possible infinite recursion inside 'Aspect' property.** 
FFImageLoading.Forms\CachedImage.cs 37
```
		public Aspect Aspect
		{
			get
			{
				return (Aspect)GetValue(AspectProperty);
			}
			set
			{
				SetValue(AspectProperty, value);
			}
		}

```

**Comment by daniel-luberda** [comment]
Thanks, it's refactored now, but I don't see any `infinite recursion inside 'Aspect' property`.
