### ISSUE TITLE
SvgImageSource.FromFile() firing "Unhandled Exception"

### ISSUE THREAD

**Issue by chapeti** [luberda-molinet/FFImageLoading#467]
Hi Daniel.

Trying to use `SvgImageSource.FromFile("filename.svg")`:

> You are referencing the Portable version in your App - you need to reference the platform (iOS/Android) version

My PCL profile is : 

> .NET Framework 4.5
ASP .Net Core 1.0
Windows 8
Xamarin.Android
Xamarin.iOS
Xamarin.iOS (Classic)
Xamarin.Mac

I added `CachedImageRenderer.Init()` into both: `AppDelegate.cs` and ` MainActivity.cs`.

My PCL project has references to:

1. `Xamarin.FFImageLoading`
2. `Xamarin.FFImageLoading.Forms`
3. `Xamarin.FFImageLoading.Svg`
4. `Xamarin.FFImageLoading.Svg.Forms`

And my targets projects:

1. `Xamarin.FFImageLoading`
2. `Xamarin.FFImageLoading.Forms`

Removed and reinstalled all NuGet packages in all projects using:

`Update-Package -Reinstall -ProjectName [ProjectName]`

What am I doing wrong?

**Comment by daniel-luberda** [comment]
You have to reference all packages in both PCL & platform specific projects (SVG packages too).

**Comment by chapeti** [comment]
Thx Daniel.

Btw, and just for the records:

I referenced all packages in all projects, but it did not work yesterday.

Today it works like a charm. Maybe my VS is not working well.

Cheers.
