### ISSUE TITLE
Enhancement: spinner animated placeholder?

### ISSUE THREAD

**Issue by shayo** [luberda-molinet/FFImageLoading#468]
Is it possible to add an animated placeholder spinner?

**Comment by alanspires** [comment]
This is easily done using a custom control. I made one using a grid, cached image with a activity indicator. But it would be handy to have this built in too.

**Comment by shayo** [comment]
Can you please share your solution until this is integrated? Thank you!

**Comment by alanspires** [comment]
Here you go buddy.

http://pastebin.com/rXr60aDH

**Comment by daniel-luberda** [comment]
Thanks @alanspires 

@shayo Also, in recent versions FFImageLoading supports `DownloadProgress` callback which can be used to show image download progress.
