### ISSUE TITLE
TintTransformation Property Not Working

### ISSUE THREAD

**Issue by ubaidsaeed** [luberda-molinet/FFImageLoading#474]
this is my code
 CachedImage category_item_image = new CachedImage()
                        {
                            LoadingPlaceholder = "category_placeholder.png",
                            ErrorPlaceholder = "category_placeholder.png"
                        };
                        category_item_image.Transformations = new List<FFImageLoading.Work.ITransformation>() {
                            new TintTransformation("#ffffff")
                        };
                        if (!string.IsNullOrWhiteSpace(record.MobileIconPath))
                        {
                            category_item_image.Source = record.MobileIconPath;
                        }
                       
                        category_grid.Children.Add(category_item_image, 0, 0);

image added successfully but tint color not changed

**Comment by daniel-luberda** [comment]
@ubaidsaeed

You must add `Xamarin.FFImageLoading.Transformations` to both PCL & platform specific projects. Did you do that?

**Comment by ubaidsaeed** [comment]
yes i already did that

**Comment by daniel-luberda** [comment]
Did you try to look at example project? It works fine. I'll need more info.

**Comment by ubaidsaeed** [comment]
yes i saw now it is showing the tint color only on loading image not source
image i just cut the transformation code before loading image error image
and source image code

please see the attachment code and video


Thank You

**Comment by stopiccot** [comment]
For me TintTransform seems to be not working with svg images

**Comment by daniel-luberda** [comment]
Please reopen if you still experience it.

**Comment by vkhadyka** [comment]
I'm experiencing the same difficulties with TintTransformation for. Xamarin.IOS. Especially with black color + alpha channel.
