### ISSUE TITLE
iOS - Possible bug with loading file from Documents directory

### ISSUE THREAD

**Issue by marcin-solvenet** [luberda-molinet/FFImageLoading#479]
When loading file from app documents directory using  CachedImage, seems library create BundleDataResolver instead of FileDataResolver.
It works good on Andriod platform. I
Tested using FFImageLoading 2.2.5 and 2.2.8. Issue exists on the device and simulator.

System.IO.FileNotFoundException: /Users/solvenet/Library/Developer/CoreSimulator/Devices/323306BF-0038-4487-AC2D-84C6C8577C5E/data/Containers/Data/Application/620689CF-4818-458E-BE35-89E2DECEA49D/Documents/temp/ISP_IMG_20170206_134708.jpg
at FFImageLoading.DataResolvers.BundleDataResolver+<Resolve>d__1.MoveNext () [0x00456] in <f866fc50aabd449da0e25c454a95fbec>:0
--- End of stack trace from previous location where exception was thrown ---

**Comment by daniel-luberda** [comment]
@marcin-solvenet Yes, that's a bug: 2.2.8-pre-330 nuget released (fix included). Thanks! :)

**Comment by marcin-solvenet** [comment]
Daniel, thank you for the quick fix :-)
