### ISSUE TITLE
2.2.6 and above, images take up all available space

### ISSUE THREAD

**Issue by swansca79** [luberda-molinet/FFImageLoading#480]
Going from 2.2.5 to 2.2.6, CachedImage wants to take up all available space.  This is happening on Android and iOS.

```
<ffimage:CachedImage Source="ic_desktop_windows_white_24dp" 
    HorizontalOptions="Center" 
    VerticalOptions="Center" 
    DownsampleToViewSize="true" 
    TransparencyEnabled="false" >	
</ffimage:CachedImage>
```

Using 2.2.5, Forms 2.3.3.180
![screen shot 2017-02-06 at 3 15 32 pm](https://cloud.githubusercontent.com/assets/17572520/22666727/6403707e-ec7f-11e6-83ed-8189e189e789.png)

Using 2.2.6, Forms 2.3.3.180
![screen shot 2017-02-06 at 3 15 42 pm](https://cloud.githubusercontent.com/assets/17572520/22666704/4ebf418e-ec7f-11e6-8bb9-f89bcb81f9d4.png)

Images used:
![ic_desktop_windows_black_24dp](https://cloud.githubusercontent.com/assets/17572520/22666852/ea83c0ae-ec7f-11e6-9a1c-046d37f23b4e.png)

White one below
![ic_desktop_windows_white_24dp](https://cloud.githubusercontent.com/assets/17572520/22666872/f7ef74f4-ec7f-11e6-972f-b98b468eb071.png)

**Comment by daniel-luberda** [comment]
Yes, there were some changes. It would be nice if someone could help me with that: 

- Xamarin.Forms code: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Image.cs#L62-L118
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms/CachedImage.cs#L490-L523

Basically if I put the same code as Xamarin.Forms `Image` `CachedImage` doesn't work as suppose to in expandable layouts. I don't know why. Do anyone knows how could we improve that?

**Comment by daniel-luberda** [comment]
Let's continue here: https://github.com/luberda-molinet/FFImageLoading/issues/545
