### ISSUE TITLE
SVG with viewbox not working -- update to SkiaSharp 1.56.1

### ISSUE THREAD

**Issue by flanakin** [luberda-molinet/FFImageLoading#482]
SkiaSharp doesn't currently handle viewbox properly, but they fixed it in 1.56.1. Please update SkiSharp to bring in this fix :-)

https://github.com/mono/SkiaSharp/issues/230

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/commit/6424f79e1da71d20af4c6d27c36a87d1bd41cdc5

**Comment by daniel-luberda** [comment]
2.2.8-pre-330 nuget released.
