### ISSUE TITLE
Question or Bug: CropTransformation always return square images

### ISSUE THREAD

**Issue by bvschie** [luberda-molinet/FFImageLoading#483]
I use CropTransformation in the way demonstrated in the project for Xamarin.Forms.

            Transformations = new List<ITransformation>() {
                new CropTransformation(CurrentZoomFactor, CurrentXOffset, CurrentYOffset)
            };

The XAML looks like this; 

  		<ScrollView>
			<StackLayout>
  				<ffimageloading:CachedImage x:Name="PhotoViewer" HorizontalOptions="Fill" VerticalOptions="Fill"
					Source="{Binding ImageUrl}" 
					Transformations="{Binding Transformations}" CacheType="Disk">
    <ffimageloading:CachedImage.GestureRecognizers>
						<PinchGestureRecognizer PinchUpdated="OnPinchUpdated" />
						<PanGestureRecognizer PanUpdated="OnPanUpdated" />
					</ffimageloading:CachedImage.GestureRecognizers>  
    </ffimageloading:CachedImage>
			</StackLayout>
		</ScrollView>

As soon i apply a CropTransformation to a non-square image; the result is a squared image; Is this a Bug or do I use the Transformation or XAML wrongly ?

Thank you, Bob.
![image](https://cloud.githubusercontent.com/assets/25656835/22784130/20ac4f9c-eecf-11e6-8921-153353168654.png)
![image](https://cloud.githubusercontent.com/assets/25656835/22784136/27cbac28-eecf-11e6-9fb3-4f83b39ff4a2.png)

**Comment by daniel-luberda** [comment]
It's not a bug, `CropTransformation` has `aspect ratio` properties for controlling that.
