### ISSUE TITLE
TintTransform is not working for svg images

### ISSUE THREAD

**Issue by stopiccot** [luberda-molinet/FFImageLoading#485]
title says for itself

**Comment by daniel-luberda** [comment]
SVG are treated just the same as normal images. I don't think it's the case, rather this: 

- Be sure you add Transformations package to both projects (PCL & platform specific)
- Sometime, linker can cut Transformation assembly when using it XAML-only, you can avoid that by adding `var ignore = new TintTransform()`

**Comment by daniel-luberda** [comment]
Please reopen if it won't solve your issue. Thanks.
