### ISSUE TITLE
Impossible to load Source from resources

### ISSUE THREAD

**Issue by tematim** [luberda-molinet/FFImageLoading#486]
Hello,

In my viewModel, I have :  
string Icon = @"\Resources\drawable\phoneJ.svg"
(I use an android device, but I'll add a platform specific test later)

In my xaml (which is a part of a datatemplate), I have : 
forms:CachedImage x:Name="BlockImage" Grid.Row="0" Grid.Column="1"
                   Grid.ColumnSpan="2" VerticalOptions="Center"
                   HorizontalOptions="Center" DownsampleToViewSize="true"
                           RetryCount="0" RetryDelay="250" BitmapOptimizations="False"
                   HeightRequest="50" WidthRequest="50" Source="{Binding Icon}"/

I init the FFImageloading in my MainActivity, and other svgs in the same "page" with Source parameter assigned in my code-behing are well displayed.

Is it possible to help me to display it ?

Regards

**Comment by daniel-luberda** [comment]
`string Icon = @"\Resources\drawable\phoneJ.svg"`
should be:
`string Icon = @"phoneJ.svg"`

**Comment by tematim** [comment]
I try, but I keep having exceptions like : 
02-11 18:48:25.707 I/MonoDroid(23551): UNHANDLED EXCEPTION:
02-11 18:48:25.717 I/MonoDroid(23551): System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.ListViewAdapter from native handle 0xbeaea7ac (key_handle 0x350a9a8b). ---> System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.ListViewAdapter::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
02-11 18:48:25.717 I/MonoDroid(23551):    --- End of inner exception stack trace ---
02-11 18:48:25.717 I/MonoDroid(23551):   at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00039] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:304 
02-11 18:48:25.717 I/MonoDroid(23551):   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00138] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:282 
02-11 18:48:25.717 I/MonoDroid(23551):    --- End of inner exception stack trace ---
02-11 18:48:25.717 I/MonoDroid(23551):   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00186] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:289 
02-11 18:48:25.717 I/MonoDroid(23551):   at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000e5] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:459 
02-11 18:48:25.717 I/MonoDroid(23551):   at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x0001a] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:430 
02-11 18:48:25.717 I/MonoDroid(23551):   at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:422 
02-11 18:48:25.717 I/MonoDroid(23551):   at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:416 
02-11 18:48:25.717 I/MonoDroid(23551):   at Android.Widget.BaseAdapter.n_GetCount (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Widget.BaseAdapter.cs:463 
02-11 18:48:25.717 I/MonoDroid(23551):   at (wrapper dynamic-method) System.Object:ac7b4688-b124-491a-97c6-3f1073de64f4 (intptr,intptr)
02-11 18:48:25.747 D/Mono    (23551): DllImport searching in: 'realm-wrappers' ('librealm-wrappers.so').
02-11 18:48:25.747 D/Mono    (23551): Searching for 'object_remove_row'.
02-11 18:48:25.747 D/Mono    (23551): Probing 'object_remove_row'.
02-11 18:48:25.747 D/Mono    (23551): Found as 'object_remove_row'.
02-11 18:48:25.757 D/Mono    (23551): Assembly Ref addref HockeySDK.AndroidBindings[0xb846e920] -> System[0xb85539f0]: 19
02-11 18:48:25.767 W/art     (23551): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable

**Comment by daniel-luberda** [comment]
This exception is not related to FFImageLoading. You have some issues with you list view.

**Comment by tematim** [comment]
I solved the exception, but my svg aren't here : 
02-11 19:04:37.194 D/skia    (24984): image header:[3c 73 76 67 20 77 69 64], stream len = 1500, read byte count = 8, valid byte count = 8, [<svg wid]
02-11 19:04:37.194 D/skia    (24984): --- SkImageDecoder::Factory returned null
02-11 19:04:37.384 D/skia    (24984): image header:[3c 73 76 67 20 77 69 64], stream len = 1500, read byte count = 8, valid byte count = 8, [<svg wid]
02-11 19:04:37.384 D/skia    (24984): --- SkImageDecoder::Factory returned null
02-11 19:04:37.384 D/skia    (24984): image header:[3c 73 76 67 20 77 69 64], stream len = 1500, read byte count = 8, valid byte count = 8, [<svg wid]
02-11 19:04:37.384 D/skia    (24984): --- SkImageDecoder::Factory returned null
02-11 19:04:38.916 D/skia    (24984): image header:[3c 73 76 67 20 77 69 64], stream len = 1500, read byte count = 8, valid byte count = 8, [<svg wid]
02-11 19:04:38.916 D/skia    (24984): --- SkImageDecoder::Factory returned null
02-11 19:04:38.926 D/skia    (24984): image header:[3c 73 76 67 20 77 69 64], stream len = 1500, read byte count = 8, valid byte count = 8, [<svg wid]
02-11 19:04:38.926 D/skia    (24984): --- SkImageDecoder::Factory returned null
02-11 19:04:55.553 D/skia    (24984): image header:[3c 73 76 67 20 77 69 64], stream len = 1500, read byte count = 8, valid byte count = 8, [<svg wid]
02-11 19:04:55.553 D/skia    (24984): --- SkImageDecoder::Factory returned null
02-11 19:04:55.563 D/skia    (24984): image header:[3c 73 76 67 20 77 69 64], stream len = 1500, read byte count = 8, valid byte count = 8, [<svg wid]
02-11 19:04:55.563 D/skia    (24984): --- SkImageDecoder::Factory returned null

**Comment by tematim** [comment]
Please reopen the issue, I still can't see all svg

**Comment by daniel-luberda** [comment]
Cou

**Comment by daniel-luberda** [comment]
@tematim  Could you upload a reproduction?

**Comment by daniel-luberda** [comment]
Let's continue in the second issue
