### ISSUE TITLE
MvxImageLoadingView - notification about image loading finished

### ISSUE THREAD

**Issue by Immons** [luberda-molinet/FFImageLoading#487]
Trying to figure it out how to check if the image has been loaded and cannot find if it is already done or where it sits ? ImageLoaderTask is always null if I set image through DataLocationUri. Any ideas?

**Comment by daniel-luberda** [comment]
Hi @Immons,

Did you try to set those properties:

https://github.com/luberda-molinet/FFImageLoading/blob/fc351f8a7ffc8110c2e172e7e877312c7b40c81a/source/FFImageLoading.Cross/MvxImageLoadingView.cs#L73-L77

?

**Comment by molinch** [comment]
@Immons Any news?

**Comment by daniel-luberda** [comment]
@Immons `MvxImageLoadingView` is now depreciated. Try the new `MvxCachedImageView` which has the callbacks you want. 

Fully working example here: https://github.com/luberda-molinet/FFImageLoading/tree/master/samples/ImageLoading.MvvmCross.Sample
