### ISSUE TITLE
Memory leak while reusing ImageView on Android

### ISSUE THREAD

**Issue by Qonstrukt** [luberda-molinet/FFImageLoading#488]
We've recently upgraded FFImageLoading from 2.1.8 to 2.2.8 and we've noticed an explosion of memory usage on Android in a RecyclerView with a single ViewHolder with two `ImageViewAsync`'s.

The binding code in the ViewHolder:

```
ImageService.Instance.LoadUrl (recipeImageUrl)
    .LoadingPlaceholder ("empty", FFImageLoading.Work.ImageSource.CompiledResource)
    .Into (recipeImage);

ImageService.Instance.LoadUrl (authorImageUrl)
    .LoadingPlaceholder ("empty", FFImageLoading.Work.ImageSource.CompiledResource)
    .Transform (new CircleTransformation ())
    .Into (authorImage)
```

With FFImageLoading 2.1.8 the memory usage stays well below 64MB. With FFImageLoading 2.2.8 the memory usage keeps rising to about ~200MB for the exact same list of items.

Has anything changed in the configuration or prerequisites? We've tried setting 
`MaxMemoryCacheSize = (int)(Java.Lang.Runtime.GetRuntime ().MaxMemory () / 8)`
on the Configuration, but this didn't have any effect, which implies it isn't caused by the cache, but the `ImageViewAsync` itself, which we haven't customised ourself.

If desired I might be able to provide a small example. But maybe it's something obvious that's changed that isn't in the documentation?

**Comment by daniel-luberda** [comment]
Hi @Qonstrukt, Previous Android memory cache was releasing images too early. It's fixed now. You can control memory cache size with `MaxMemoryCacheSize`, but you must provide that value in custom configuration on app startup (IMPORTANT), like here: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Droid/MainActivity.cs#L28-L35

**Comment by Qonstrukt** [comment]
Hi @daniel-luberda, thanks for your response. Unfortunately we've already tried setting `MaxMemoryCacheSize` in the configuration on startup, but this didn't have any effect. 

If I'm understanding correctly, using the sample application you provided, it's always going to crash at some point? Because you're not specifying a `MaxMemoryCacheSize` there, so images will never be removed from memory cache. Doesn't sound like wanted behaviour to me, especially since it's nowhere documented that this is necessary for a well functioning image-heavy app.

**Comment by EmilAlipiev** [comment]
I also tested MaxMemoryCacheSize  and I see that it goes above the cache size I set up. what is the expected behaviour with MaxMemoryCacheSize ?
