### ISSUE TITLE
TransformPlaceholders = false remove transformation from source image

### ISSUE THREAD

**Issue by iWeaverMan** [luberda-molinet/FFImageLoading#490]
2.2.8

**Comment by daniel-luberda** [comment]
Hi @iWeaverMan  Could you give more info?

**Comment by iWeaverMan** [comment]
Image = new CachedImage
			{
				HorizontalOptions = LayoutOptions.Center,
				VerticalOptions = LayoutOptions.Start,
				CacheDuration = TimeSpan.FromDays(30),
				DownsampleToViewSize = true,
				RetryCount = 0,
				RetryDelay = 250,
				ErrorPlaceholder = "error_loading.png",
				LoadingPlaceholder = "loading.png",
				TransformPlaceholders = false,
				BackgroundColor = Color.White,
				Aspect = Aspect.AspectFit,
				BitmapOptimizations = true,
				IsVisible = false,
				Transformations = new System.Collections.Generic.List<ITransformation> {
					new GrayscaleTransformation()
				}
			};
TransformPlaceholders = false, remove apply transformation on main image

**Comment by daniel-luberda** [comment]
But what's not working?

**Comment by iWeaverMan** [comment]
Transformation not apply for main image...

**Comment by daniel-luberda** [comment]
It should be fixed :) Also you can now use something as transformations selectors, see this: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/Transformations/TransformationsSelectorPageModel.cs#L21-L43
