### ISSUE TITLE
Get error when I binde HexColor of Tint transformation

### ISSUE THREAD

**Issue by shahramSo** [luberda-molinet/FFImageLoading#491]
Hi,
I use ffimageloading in the listView with a TintTransformation, so The binding works fine for image source but for HexColor I get error for missing property. I'v defined a string property for HexColor but It dosn't accept such property:

`<flv:FlowListView SeparatorVisibility="None" HasUnevenRows="true" FlowItemTapped="OnItemTapped"
			FlowColumnMinWidth="60" FlowTappedBackgroundColor="Blue" FlowTappedBackgroundDelay="50" FlowItemsSource="{Binding Items}" x:Name="listView">

    <flv:FlowListView.FlowColumnTemplate>
      <DataTemplate>
        <Grid Padding="3">
          <Grid.RowDefinitions>
            <RowDefinition Height="*" />
          </Grid.RowDefinitions>
          <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*" />
          </Grid.ColumnDefinitions>
          
          <ffimageloading:CachedImage x:Name="selectIcon" WidthRequest="50" HeightRequest="50" DownsampleToViewSize="true"
                                      Source = "{Binding IconPath, Converter={StaticResource ImageSourceConverter}}">
            <ffimageloading:CachedImage.Transformations>
              <fftransformations:TintTransformation HexColor="{Binding HexColor}" EnableSolidColor="true"/>
            </ffimageloading:CachedImage.Transformations>
          </ffimageloading:CachedImage>
          
        </Grid>
      </DataTemplate>
    </flv:FlowListView.FlowColumnTemplate>

  </flv:FlowListView>

My model is:
`public class Icons
    {
        public string IconPath { get; set; }
        public string HexColor { get; set; }
    }`

any idea? Thanks

**Comment by EmmanVazz** [comment]
What is the specific error you get and what version of FF are you on?

**Comment by shahramSo** [comment]
The last version I'v used, It is not possible to bind HexColor property, in all of examples, there is no any example for binding TintTransformation.

**Comment by EmmanVazz** [comment]
Oh HexColor is not defined as a bindable property. 

You can make a PR to make it a bindable property, we just made a custom class to wrap that and have a bindable property. 

```
public class TintedCachedImage : CachedImage
	{
		public static BindableProperty TintColorProperty = BindableProperty.Create(nameof(TintColor), typeof(Color), typeof(TintedCachedImage), Color.Transparent, propertyChanged: UpdateColor);

		public Color TintColor
		{
			get { return (Color)GetValue(TintColorProperty); }
			set { SetValue(TintColorProperty, value); }
		}

		private static void UpdateColor(BindableObject bindable, object oldColor, object newColor)
		{
			var oldcolor = (Color)oldColor;
			var newcolor = (Color)newColor;

			if (!oldcolor.Equals(newcolor))
			{
				var view = (TintedCachedImage)bindable;
				var transformations = new System.Collections.Generic.List<ITransformation>() {
					new TintTransformation((int)(newcolor.R * 255), (int)(newcolor.G * 255), (int)(newcolor.B * 255), (int)(newcolor.A * 255)) {
						EnableSolidColor = true
					}
				};
				view.Transformations = transformations;
			}
		}
	}
```

**Comment by shahramSo** [comment]
I guessed, thank you for your solution, and how to bind TintColor of TintedCachedImage class in XAML entire of DataTemplate?

**Comment by EmmanVazz** [comment]
Glad to help!

**Comment by daniel-luberda** [comment]
Yes, transformations properties are not bindable as they must also work in a non Xamarin.Forms projects. But that will change soon, as we're including Transformations packages in a base nugets, so we can add Xamarin.Forms specific Transformations for that which can have bindable properties :) I created issue for this: https://github.com/luberda-molinet/FFImageLoading/issues/499

@EmmanVazz Nice idea! :)

**Comment by JTOne123** [comment]
Hi guys, do you have any news about transformation on the forms?

I'm getting error with next statement HexColor="{StaticResource PrimaryDark}"

**Comment by daniel-luberda** [comment]
@JTOne123 What's error stack trace? `HexColor` must be a string, not XF `Color` struct.

**Comment by JTOne123** [comment]
Be sure, XF color there :) 

I guess, it will be nice to have property for StaticResource :) And you told about XF transformation

```
at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
   at Xamarin.Forms.Xaml.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider)
```

**Comment by daniel-luberda** [comment]
XF transformations are the same as native transformations (cross platform), that's why they can;t use XF specific types as `Color`

**Comment by MosCD** [comment]
@EmmanVazz  solution is perfect
but how if I wanted to add tint color to the SVG image 
while that is easy in code by doing it like
var Icon = new TintedCachedImage();
Icon.Source = SvgImageSource.FromFile(_icon);

Well I don't know how to do it in Xaml

**Comment by MosCD** [comment]
Well
I managed to find a solution for the problem I posted in the recent comment

`
public class TintedCachedImage : CachedImage
    {
        public static BindableProperty TintColorProperty = BindableProperty.Create(nameof(TintColor), typeof(Color), typeof(TintedCachedImage), Color.Transparent, propertyChanged: UpdateColor);

        public Color TintColor
        {
            get { return (Color)GetValue(TintColorProperty); }
            set { SetValue(TintColorProperty, value); }
        }

        private static void UpdateColor(BindableObject bindable, object oldColor, object newColor)
        {
            var oldcolor = (Color)oldColor;
            var newcolor = (Color)newColor;

            if (!oldcolor.Equals(newcolor))
            {
                var view = (TintedCachedImage)bindable;
                var transformations = new System.Collections.Generic.List<ITransformation>() {
                    new TintTransformation((int)(newcolor.R * 255), (int)(newcolor.G * 255), (int)(newcolor.B * 255), (int)(newcolor.A * 255)) {
                        EnableSolidColor = true
                    }
                };
                view.Transformations = transformations;
            }
        }

        //To Support SVG
        public static BindableProperty SvgSourceProperty = BindableProperty.Create(nameof(TintColor), typeof(string), typeof(TintedCachedImage), null, propertyChanged: UpdateSvg);
        public string SvgSource
        {
            get { return (string)GetValue(SvgSourceProperty); }
            set { SetValue(SvgSourceProperty, value); }
        }

        private static void UpdateSvg(BindableObject bindable, object oldVal, object newVal)
        {
            var _instance = bindable as TintedCachedImage;
            _instance.Source = SvgImageSource.FromFile((string)newVal);
        }
    }

`

I added a custom property to enable directly loading sag image from xml

usage

`
 <local:TintedCachedImage Grid.Row="0" SvgSource="reset.svg" TintColor="{StaticResource BrandColor}" />
`

**Comment by AlexSchuetz** [comment]
@MosCD 
> ```
> //To Support SVG
> public static BindableProperty SvgSourceProperty = BindableProperty.Create(nameof(TintColor), ...
>```
Probably you meant:
```
public static BindableProperty SvgSourceProperty = BindableProperty.Create(nameof(SvgSource), ...
```
Thank you anyway.

**Comment by spencerdbos2** [comment]
@MosCD Where do you store "reset.svg" in your project?
