### ISSUE TITLE
Cache StreamImageSource to disk when custom cache key is supplied

### ISSUE THREAD

**Issue by pavel-chehov** [luberda-molinet/FFImageLoading#492]
Hello! I'am trying to download image from server with access token and trying to cach this image with Disk option. But It doesn't work for me. When I use Memory option all works fine. But when I switch to Disk option, cache always stops work, and I can get image only from stream. Please, help.

``` C#
                var driverView = FindViewById<FFImageLoading.Views.ImageViewAsync>(Resource.Id.driverImageView);
                ImageService.Instance.Initialize(new Configuration
                {
                    HttpClient = new HttpClient(new AuthenticatedHttpImageClientHandler(UserContext.Current.AccessToken))
                });

                ImageService.Instance.LoadStream((token) => { return GetImageStream(token); }).WithCache(CacheType.Disk).CacheKey("driver_last_image").Into(driverView);

**Comment by daniel-luberda** [comment]
You can't save `StreamImageSource` to disk :) Disk cache is only used for `UrlImageSource`. 

BTW: To avoid problems, you must call `ImageService.Instance.Initialize` at app startup, only once.

**Comment by daniel-luberda** [comment]
We can add it somewhere in future though. So changing this to be a feature request :)

**Comment by pavel-chehov** [comment]
@ Daniel-luberda Glad to hear it and thanks for the explanation!

**Comment by daniel-luberda** [comment]
I realised that currently we don't need that feature as it can be easily resolved by providing (via custom config) either: 

- Own `HttpClient` or `HttpClientHandler` implementation: https://github.com/luberda-molinet/FFImageLoading/wiki/Authentication-Support
- Own `IDownloadCache` implementation (or overriding some methods of a default one)

**Comment by vvolkgang** [comment]
@daniel-luberda this should be documented then, specially because memory cache works but local doesn't even if you specifically ask for it. #713 might be relevant for documentation
