### ISSUE TITLE
Crash in FFImageLoading 2.2.8 - very rare

### ISSUE THREAD

**Issue by patook** [luberda-molinet/FFImageLoading#493]
I only get it a couple of times out of 10,000 but here is the whole stack from Insights:

System.NullReferenceExceptionObject reference not set to an instance of an object
Raw
FFImageLoading.Concurrency.PendingTasksQueue.<>c__DisplayClass2_0.<Remove>b__0(SimpleNode<TItem, TPriority> v)<f4620c0a205341c78392982edfca72a6>:0

**Comment by daniel-luberda** [comment]
@patook Hi, thanks! Is it possible to get full exception stack?

**Comment by patook** [comment]
@daniel-luberda sorry, that's all I got from Insights, just those two lines. I can't repro locally since it's very rare.
