### ISSUE TITLE
TintTransformation - Unify Android / iOS / Windows behaviour

### ISSUE THREAD

**Issue by kentcb** [luberda-molinet/FFImageLoading#495]
The result of applying a `TintTransformation` on Android can differ quite drastically than on iOS. For example:

<img src="https://cloud.githubusercontent.com/assets/1901832/23197614/74a7dab6-f911-11e6-9433-b8299018f2cc.jpg" width="250"><img src="https://cloud.githubusercontent.com/assets/1901832/23197692/fad73140-f911-11e6-8720-b27112ae9b02.png" width="250">

Android is much darker, as you can see.

I can approximate the correct result by doubling the R, G, and B values on Android. For example:

<img src="https://cloud.githubusercontent.com/assets/1901832/23197614/74a7dab6-f911-11e6-9433-b8299018f2cc.jpg" width="250"><img src="https://cloud.githubusercontent.com/assets/1901832/23197697/01bb54fa-f912-11e6-85c3-9834b820b48c.png" width="250">

It's still not 💯 correct, but much closer.

I've also noticed that the alpha component on Android has no effect once you surpass `127` (I assume it's actually `127.5`, being half of `255`). Not sure if this is related to this problem or not. I tried leaving the R, G, B components as is and halving the A, but that did not yield a match:

<img src="https://cloud.githubusercontent.com/assets/1901832/23197614/74a7dab6-f911-11e6-9433-b8299018f2cc.jpg" width="250"><img src="https://cloud.githubusercontent.com/assets/1901832/23197706/0a061d70-f912-11e6-8cf5-93594ad48912.png" width="250">

Any thoughts on this? I've put my repro code up [here](https://github.com/kentcb/TintRepro) for you.

**Comment by daniel-luberda** [comment]
@kentcb 

Did you try to set `EnableSolidColor` to true? It changes `TintTransformation` behaviour entirely. 

Thanks for such detailed info. I'll try to unify that behaviour.

**Comment by kentcb** [comment]
@daniel-luberda I had not tried that. Just tried it, and it seems to produce a different result altogether (again, somewhat different on both platforms).

**Comment by daniel-luberda** [comment]
It should be fixed in the recent versions. Please reopen otherwise. Thanks.
