### ISSUE TITLE
How to use an Iconic Font?

### ISSUE THREAD

**Issue by nazgul87** [luberda-molinet/FFImageLoading#496]
Hi, I'm searching for something to improve my apps performance while loading lot of images, and this component sounds great, but I'm using an iconic font like font awesome and ionicons. So my question is: Is there any way to load that type of images with this control?

Thanks in advance for your comments.

**Comment by EmmanVazz** [comment]
Have you seen this https://github.com/jsmarcus/Xamarin.Plugins/tree/master/Iconize ? I don't think FF works unless you can extract the svg from these fonts.

**Comment by daniel-luberda** [comment]
@nazgul87 @EmmanVazz It's possible to use Iconic font with FFImageLoading as they provide it also as set of SVG files, you must include them in app bundle (just as normal image). More info here: https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support#xamarinforms
