### ISSUE TITLE
Need a way to bind to ListViewItems in native Windows UWP

### ISSUE THREAD

**Issue by flanakin** [luberda-molinet/FFImageLoading#497]
It seems like Xamarin Forms has a way to bind data to a converter, but native Windows UWP doesn't. Please add this. I had to come up with a hack of using Image.Tag and handlers on Loading and Loaded events to get the right behavior.

**Comment by daniel-luberda** [comment]
This is the code for `FFImage` control: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Windows/FFImage.cs

Indeed, there are some feature missing, but `Source` property is bindable. Could you give more info, what's missing?

**Comment by mrTR24** [comment]
hi 

When I hard code the path in the XAML, it WORKS image is displayed ,but when I bind the path using Binding expression, it does not work . Am working on android

XAML(Hardcoded version) workss
<ffsvg:SvgCachedImage Source="/storage/emulated/0/DCIM/DeliverySVG/pots empty #qte3.svg" WidthRequest="30" HeightRequest="30" Grid.Row="0" Grid.Column="0"/>

BindingVersion 
ViewModel
ListViewItemModel temp = new ListViewItemModel()
                    {
                        // SvgPath = itemList[i].ImageSVGPath,
                        SvgPath = "/storage/emulated/0/DCIM/DeliverySVG/Stepladder 1.svg"
}
                  <ffsvg:SvgCachedImage Source="{Binding Source=SvgPath}" WidthRequest="30" HeightRequest="30" Grid.Row="0" Grid.Column="0"/>
