### ISSUE TITLE
FadeAnimationEnabled & FadeAnimationForCachedImages on Xamarin Forms

### ISSUE THREAD

**Issue by Marco-Montagnani** [luberda-molinet/FFImageLoading#498]
Hi Daniel,
first of all thanks for your great job.
I want report to you an issue on my Android app build with Xamarin Forms version 2.3.3
 
After update the project with FFImageLoading release 2.2.8 from 2.1.8 the fade-in effect is missing and I can’t undestand how restore it!
 
I have already played with settings (FadeAnimationEnabled & FadeAnimationForCachedImages ) but the fade-in still missing.

Could you help me to solve it?.
Best regards.

**Comment by daniel-luberda** [comment]
Hi @Marco-Montagnani  
- Can you give some more details? 
- When do you call `ImageService.Instance.Initialize` method?
- What device?

**Comment by Marco-Montagnani** [comment]
Into the MainActivity.cs OnCreate on App.Droid project
...
        Xamarin.Forms.Forms.Init(this, bundle);

        CachedImageRenderer.Init();

        var config = new Configuration {
          FadeAnimationEnabled = true,
          FadeAnimationDuration = 300,
          FadeAnimationForCachedImages = true,
        };

        ImageService.Instance.Initialize(config);
...

and I use on App.Shared project (PCL) the object 
CachedImage imgFlyer;

      imgFlyer = new CachedImage {

        FadeAnimationEnabled = true,
        DownsampleToViewSize = true,
        Aspect = Aspect.AspectFill,
        HeightRequest = 100,
      };

I use an Android Device 6.0 marshmallow API 23 but the same problem appear on Iphone 5S

**Comment by daniel-luberda** [comment]
It should work. Is it possible to get reproduction? Try delete `obj`&`bin` folders, clean solution and make sure you have the same FFImageLoading package version in each project (PCL & platform specific)

**Comment by Marco-Montagnani** [comment]
Hi Daniel, I have update my project to the last revision 2.2.9 and I cleaned the solution and delete all the directory obj and bin folder but ... nothing has changed, the fade in effect is still missing. 
Where I can send a project to reproduct and see the issue?

**Comment by EmilAlipiev** [comment]
@Marco-Montagnani  did you find a solution for this? I cant make it work either.

**Comment by Marco-Montagnani** [comment]
No,
I have this issue on iphone and Android app build with Xamarin Forms…. 

If you want I can send to you my entire application.

 

BR.

 

Da: EmilAlipiev [mailto:notifications@github.com] 
Inviato: sabato 8 aprile 2017 14:43
A: luberda-molinet/FFImageLoading <FFImageLoading@noreply.github.com>
Cc: Marco Montagnani <marco.montagnani@gmail.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [luberda-molinet/FFImageLoading] FadeAnimationEnabled & FadeAnimationForCachedImages on Xamarin Forms (#498)

 

@Marco-Montagnani <https://github.com/Marco-Montagnani>  did you find a solution for this? I cant make it work either.

**Comment by daniel-luberda** [comment]
Let's move to the other thread as there's the cause there. https://github.com/luberda-molinet/FFImageLoading/issues/536
