### ISSUE TITLE
Xamarin.Forms bindable transformations properties

### ISSUE THREAD

**Issue by daniel-luberda** [luberda-molinet/FFImageLoading#499]
As we're including transformations in a base package we could also have bindable transformations properties. That would be nice.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/860

**Comment by asadullahqmr** [comment]
Any updates if the transformations will bindable anytime soon?

**Comment by carolzbnbr** [comment]
> Any updates if the transformations will bindable anytime soon?

Any news regarding it?
