### ISSUE TITLE
Max disk cache size restrictions

### ISSUE THREAD

**Issue by patook** [luberda-molinet/FFImageLoading#500]
Hey - a lot of our users have uninstalled our app because it was taking too much disk space within a day or two of being downloaded.

I checked and for active users, 100MB-200MB of images/day is not unheard of. Unfortunately, they linger on in the cache and after a few days their app is taking up 1GB of space and they delete it.

Is there a way to:
1- Check current FFImageLoading disk cache size?
2- Delete the least recently used N files?

I can set diskduration to 1 day but it means that moderately active users (i.e. if they don't use the app every day) will get cache misses all the time.

**Comment by daniel-luberda** [comment]
@patook 

> 1- Check current FFImageLoading disk cache size?

All files are in one directory. Those folders by default: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Shared/Cache/SimpleDiskCache.cs#L55-L63

> 2- Delete the least recently used N files?

- Reading `CreationTimeInUTC` attribute. You can remove files which you don't want to use cache anymore.
- Filenames are created like this: `{hashed key}.{cache validity duration in seconds}

Look here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Shared/Cache/SimpleDiskCache.cs#L212-L217

It would be a nice feature to add 
- `CurrentDiskCachePath` property in config file
- `MaxDiskCacheSize` property

+1 for this :)

**Comment by daniel-luberda** [comment]
Disk cache cleaning routine is here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Shared/Cache/SimpleDiskCache.cs#L230-L251

**Comment by AndreiMisiukevich** [comment]
Hi @daniel-luberda 
Is it actual issue?)
I watched code and noticed, that there are these properties :)

**Comment by ryl** [comment]
Setting a maximum disk cache size, and removing the least recently used to make room for new images would be an excellent feature to have.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/859
