### ISSUE TITLE
FFImage on UWP (non-forms) has non-adjustable alignments

### ISSUE THREAD

**Issue by EGoverde** [luberda-molinet/FFImageLoading#501]
In the UWP version (not Xamarin Forms) the Image inside FFImage is given fixed horizontal and vertical alignments of 'Stretch'. The alignments of the FFImage itself can be adjusted, as these are exposed by its base classes. 

Because the actual alignment of the inner image cannot be set, problems occur when one wants to use a stretch of UniformToFill and have the fit occur from the center. Setting the alignment of the FFImage does nothing, as it does not affect the actual image.

Ideally any changes to the FFImage's alignment properties would be passed on to the Image, but I'm not sure that's possible (the properties are part of the framework). An alternative aproach, adding extra bindable properties, is easily done - I'll add a pull request for this.

**Comment by EGoverde** [comment]
I've added a pull request at #502 for a fix

**Comment by EGoverde** [comment]
Any feedback on the suggested enhancements (or alternatives)? I can't release an app on UWP in its current state, unless I compile it together with the the adjusted FFImageLoading source.

**Comment by daniel-luberda** [comment]
It's merged, sorry it took so long.
