### ISSUE TITLE
Incorrect image when scrolling

### ISSUE THREAD

**Issue by Jose7777** [luberda-molinet/FFImageLoading#504]
One of my projects has a photo gallery implemented with a listview, showing about 10 pictures in a screen at the same time (2 columns, 5 rows); pictures are on the storage, so not downloading anything.

With 2.1.5 sometimes when you scroll, for a very very short fraction of sencod, you see can se one image changing from one photo to another due to reusing of the listview; here it is not a problem cause is very short.

I've upgraded to the latest version and with that, this effect is more appreciable; now the effect can be seen with more than one picture and lasts more time.

Is like 2.1.5 was a lot faster than the last version.

Can i do something to speed up?
I have also disabled animations and transparency.

Thank you very much in advance

**Comment by daniel-luberda** [comment]
Older version set image view source image to `null` before each loading operation, now you have to do it manually. (perfomance reasons as that behaviour is not always desirable, eg. frame by frame scenarios)

All you need to do to it to set image source to `null` before loading a new image. That's all.
