### ISSUE TITLE
You are referencing the Portable version in your App

### ISSUE THREAD

**Issue by Kacpur** [luberda-molinet/FFImageLoading#505]
Hi.

I develop an app, where I need circular images. But when I add CircleTransformation() to CachedImage object I get:
'System.Exception: You are referencing the Portable version in your App - you need to reference the platform (iOS/Android) version'

I have FFImageLoading.Transformations installed both in PCL and Android project.

**Comment by EmmanVazz** [comment]
Can you show us your code?

**Comment by Kacpur** [comment]
View file fragment:
```
using FFImageLoading.Forms;
using FFImageLoading.Transformations;

...


CachedImage picture = new CachedImage()
                {
                    Source = _viewModel.FriendsList[i].PictureSmall,
                    HorizontalOptions = LayoutOptions.Center,
                    VerticalOptions = LayoutOptions.Center,
                    Aspect = Aspect.Fill,
                    Margin = new Thickness(App.DeviceScreenWidth * 0.01),
                    Transformations = new List<FFImageLoading.Work.ITransformation>
                    {
                        new CircleTransformation()
                    }
                };

...
```

Without Transformations it works as a simple, square image.

**Comment by EmmanVazz** [comment]
Yeah that seems fine. My only guess is the packages. I would trying to reinstall them to see if that helps.

**Comment by Kacpur** [comment]
I tried reinstall them few times. Neither reinstalling them separately nor all at once helped.

**Comment by EmmanVazz** [comment]
So what packages do you have install in your projects, PCL and Droid?

**Comment by Kacpur** [comment]
In PCL and Droid the same (among others, irrelevant for the problem):

Xamarin.FFImageLoading
Xamarin.FFImageLoading.Forms
Xamarin.FFImageLoading.Transformations

**Comment by daniel-luberda** [comment]
Linker cuts you dll,  try to call 'var ignore = new CircleTransformation()'   in platform specific code

**Comment by Kacpur** [comment]
@daniel-luberda I saw You mentioned that in some Issues but it did not worked for me. And suddenly this time it worked. Thanks.
