### ISSUE TITLE
MD5Helper not thread-safe (occasionally wrong / switched images)

### ISSUE THREAD

**Issue by EGoverde** [luberda-molinet/FFImageLoading#506]
I've pinpointed an issue I've been having to the MD5 helper being used in the DownloadCache.cs. In this helper class an instance of MD5CryptoServiceProvider is made once, which is then being reused to calculate any hashes that get passed to it.

Most of the time this works, but as MD5CryptoServiceProvider is not thread-safe it can sometimes cause issues when two images are being loaded practically at the same time and are also calling the hash function simultaneously. In this case the hash returned to one request might belong to the other, or the same hash is returned twice. Images will then appear switched or at the wrong place.

The chance of this happening seems low, I've only encountered it using in a scenario with cached data, only on iOS and with two images in the same view.

I'll submit a pull request with a fix.

**Comment by EGoverde** [comment]
I've added a pull request at #507 for a fix

**Comment by daniel-luberda** [comment]
@EGoverde Thanks! :) Nice catch. Merged :)
