### ISSUE TITLE
TintTransformation and SVG images

### ISSUE THREAD

**Issue by 3-50** [luberda-molinet/FFImageLoading#509]
I have a 2 files (png and svg), after using TintTransformation the result is different

Code:
```
Image2 = new CachedImage()
{
WidthRequest = 900f,
HeightRequest =900f,
DownsampleToViewSize = true,
CacheType = FFImageLoading.Cache.CacheType.Disk,
CacheDuration = TimeSpan.FromDays(30),
RetryCount = 0,
RetryDelay = 250,
Aspect = Aspect.AspectFit,
};


string output = zUrl.Substring(zUrl.Length - 3, 3);
if (output == "svg")
{
Image2.Source = SvgImageSource.FromUri(new Uri(zUrl));}
else
{
Image2.Source  = zUrl;
};

switcher.Toggled += delegate
{
if (switcher.IsToggled.ToString() == "True")
{
Image2.Transformations = new List<ITransformation>() 
{
//new TintTransformation(255,95,28,128) {EnableSolidColor = true}           
new TintTransformation(255,95,28,128),
new ColorSpaceTransformation(FFColorMatrix.InvertColorMatrix),
new TintTransformation(255,255,255,106)
};
}
else
{
Image2.Transformations = null;
}
};

```
![image](https://cloud.githubusercontent.com/assets/20687048/23365592/6977add4-fd25-11e6-8ad9-6101ed770830.png)

**Comment by daniel-luberda** [comment]
`SvgImageSource.FromUri` has additional parameters for controlling resulting SVG size which affects image quality. Did you try it?

**Comment by 3-50** [comment]
Yep, I have changed the values (0, original size, x2 etc.), but the artifacts do not disappear. Sometime the situation is becoming worse.

![image](https://cloud.githubusercontent.com/assets/20687048/23435369/29a2e476-fe29-11e6-9a44-14af44a53e99.png)

**Comment by daniel-luberda** [comment]
It's probably a SkiaSharp related thing as we use its [`SKSvg`] class (https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Svg/SkiaSharp.Svg.Shared/SKSvg.cs) class for parsing / drawing SVG files. Maybe drawing with transparency should be improved somehow there, but the issue should be fixed on SkiaSharp project side.
