### ISSUE TITLE
Error with Xam.Plugins.Media

### ISSUE THREAD

**Issue by v1rtu41m4n** [luberda-molinet/FFImageLoading#510]
It can't coexist with the component Xamarin.Plugins.Media, when I setup this component then FFImageLoading throws the following error: The type initializer for 'FFImageLoading.Forms.CachedImage' threw an exception. ---> System.UnauthorizedAccessException: Access to the path "/data/user/0/guerrerobook.app.droid/cache/FFSimpleDiskCache" is denied.

It appears a permission issue but I can't figure out how to solve it, any help should be appreciated

This is the complete exception:

02-27 22:46:24.521 E/mono-rt (12326):  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'FFImageLoading.Forms.CachedImage' threw an exception. ---> System.UnauthorizedAccessException: Access to the path "/data/user/0/guerrerobook.app.droid/cache/FFSimpleDiskCache" is denied.
02-27 22:46:24.521 E/mono-rt (12326):   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00053] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/corlib/System.IO/Directory.cs:111 
02-27 22:46:24.521 E/mono-rt (12326):   at System.IO.Directory.CreateDirectory (System.String path) [0x00084] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/corlib/System.IO/Directory.cs:78 
02-27 22:46:24.521 E/mono-rt (12326):   at FFImageLoading.Cache.SimpleDiskCache..ctor (System.String cachePath, FFImageLoading.Config.Configuration configuration) [0x00076] in C:\projects\ffimageloading\source\FFImageLoading.Shared\Cache\SimpleDiskCache.cs:38 
02-27 22:46:24.521 E/mono-rt (12326):   at FFImageLoading.Cache.SimpleDiskCache.CreateCache (System.String cacheName, FFImageLoading.Config.Configuration configuration) [0x0001f] in C:\projects\ffimageloading\source\FFImageLoading.Shared\Cache\SimpleDiskCache.cs:65 
02-27 22:46:24.521 E/mono-rt (12326):   at FFImageLoading.ImageService.InitializeIfNeeded (FFImageLoading.Config.Configuration userDefinedConfig) [0x000cf] in C:\projects\ffimageloading\source\FFImageLoading.Shared\ImageService.cs:130 
02-27 22:46:24.521 E/mono-rt (12326):   at FFImageLoading.ImageService.get_Config () [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Shared\ImageService.cs:41 
02-27 22:46:24.521 E/mono-rt (12326):   at FFImageLoading.Forms.CachedImage..cctor () [0x00229] in C:\projects\ffimageloading\source\FFImageLoading.Forms\CachedImage.cs:269 
02-27 22:46:24.521 E/mono-rt (12326):    --- End of inner exception stack trace ---
02-27 22:46:24.521 E/mono-rt (12326):   at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
02-27 22:46:24.521 E/mono-rt (12326):   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:661 
02-27 22:46:24.521 E/mono-rt (12326):    --- End of inner exception stack trace ---
02-27 22:46:24.521 E/mono-rt (12326):   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext+<>c__DisplayClass1.<GetBuildMethod>b__0 (Microsoft.Practices.ObjectBuilder2.IBuilderContext context) [0x0001b] in <ba86a34b2f2c4964b8c588538e94514f>:0 
02-27 22:46:24.521 E/mono-rt (12326):   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp (Microsoft.Practices.ObjectBuilder2.IBuilderContext context) [0x00000] in <ba86a34b2f2c4964b8c588538e94514f>:0 
02-27 22:46:24.521 E/mono-rt (12326):   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp (Microsoft.Practices.ObjectBuilder2.IBuilderContext context) [0x00064] in <ba86a34b2f2c4964b8c588538e94514f>:0 
02-27 22:46:24.521 E/mono-rt (12326):   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp (Microsoft.Practices.ObjectBuilder2.IBuilderContext context) [0x00023] in <ba86a34b2f2c4964b8c588538e94514f>:0 
02-27 22:46:24.521 E/mono-rt (12326):    --- End of inner exception stack trace ---

**Comment by daniel-luberda** [comment]
http://stackoverflow.com/questions/42500865/android-app-cache-required-storage-permissions

**Comment by daniel-luberda** [comment]
BTW: You can also change default FFImageLoading cache files folder to a custom one (by providing custom configuration in `ImageService.Instance.Initialize` method).
