### ISSUE TITLE
ToolbarItem

### ISSUE THREAD

**Issue by rmenezes** [luberda-molinet/FFImageLoading#512]
Hi guys,

Is there any way to use FFImageLoading on the ToolbarItem Icon? The ToolbarItem works only with FileImageSource so I can't figure-out an way to set it from the available options avaliable options like UriImageSource, ImageSource or StreamImageSource.

Tks 

Raul

**Comment by daniel-luberda** [comment]
You can use `ImageService.Instance.Load[SourceTypeHere).+all other options like transformations.AsPNGStreamAsync()` to get `Stream`

**Comment by rmenezes** [comment]
@daniel-luberda I already tried this but I get the following error:

``` Binding: Xamarin.Forms.StreamImageSource can not be converted to type 'Xamarin.Forms.FileImageSource

**Comment by daniel-luberda** [comment]
As you see, only FileImageSource is supported. If i remember correctly, Xamarin planned to implement other source types (as only app resources were supported), I don't know if it was implemented. You have to check it by yourself. 

You could also try this (which works as I used it personally), but it's a lot of platform specific code.
https://github.com/daniel-luberda/XamarinFormsToolbarCustomFont
