### ISSUE TITLE
FileNotFoundException in SvgDataResolver

### ISSUE THREAD

**Issue by DaneMackier** [luberda-molinet/FFImageLoading#513]
Hi,

I'm using the following code to try and load a url into the image view but it fails every time with a FileNotFoundException.

```
 ImageService.Instance
                  .LoadFile(value)
                  .WithCustomDataResolver(new SvgDataResolver(40, 40, true))
                  .WithCustomLoadingPlaceholderDataResolver(new SvgDataResolver(40, 40, true))
                  .Success(() => { busyLayout.Visibility = ViewStates.Gone; })
                  .Error(
                    (e) => 
                      {
                        Console.WriteLine(e.Message);
                        busyLayout.Visibility = ViewStates.Gone;
                      })
                  .Into(imageView);
```

The value used above for the url is
https://qa.ols.cityvarsityonline.co.za/theme/image.php/cityvarsity/forum/1477920141/icon

If you check that you can see that the svg image does load in the browser.

I couldn't find much on the documentation, could you please advise what I can look at to get this working.

Thank you

**Comment by daniel-luberda** [comment]
Replace `ImageService.Instance.LoadFile(value)` with `ImageService.Instance.LoadUrl(value)`
