### ISSUE TITLE
Error with 2.2.9 on Samsung galaxy Xcover 3

### ISSUE THREAD

**Issue by Ailain** [luberda-molinet/FFImageLoading#517]
Hi

I've encountered a problem with 2.2.9 on my Xcover 3.
I'm using  XF 2.3.3.193 and the phone is running Android 6.0.1.
The only thing i can tell is that it freezes my app without any errors or anything.

Here is the code:
<ffimageloading:CachedImage x:Name="pic" Opacity="{Binding GreyScale}" WidthRequest="80" HeightRequest="80" VerticalOptions="Start"  Source="{Binding ProfilePicUrl}" Aspect="AspectFill" DownsampleToViewSize="true">
	<ffimageloading:CachedImage.Transformations>
		<fftransformations:CircleTransformation/>
	</ffimageloading:CachedImage.Transformations>
</ffimageloading:CachedImage>

It works fine on iOS and my Sony Xperia Z Compact (Android 7.0) and Samsung Galaxy S5 (Android 6.0.1)

**Comment by daniel-luberda** [comment]
@Ailain It may be anything (even not related to FFImageLoading). Please give more details and attach some reproduction and reopen this. Thanks :)
