### ISSUE TITLE
FFImageLoading.Transformations.CircleTransformation() error

### ISSUE THREAD

**Issue by ronpf** [luberda-molinet/FFImageLoading#518]
I just grabbed 2.2.9 and in this line CircleTransformation() is not recognized

new FFImageLoading.Transformations.CircleTransformation(),

**Comment by AndreiMisiukevich** [comment]
Did you install Transformations package? :)

**Comment by daniel-luberda** [comment]
Hi @ronpf,

As @AndreiMisiukevich said, please be sure if `Transformations` package is installed. Also uninstalling packages and installing once again solves a lot of nuget issues.

**Comment by AndreiMisiukevich** [comment]
I will add from myself,  Follow next steps for cleaning project.
1. Remove all FFImage packages from project (You can remove thees ones from packages.config from all projects).
2. Remove them from packages folder (if they exist)
3. Remove all bin & obj folders from your project's directory
4. Add packages again
5. Clean (Just in case) and rebuild project

**Comment by ronpf** [comment]
great, thanks. Things have been running fine lately.
