### ISSUE TITLE
Image was recycle while fling, scrolling in list view Xamarin forms

### ISSUE THREAD

**Issue by phamthanhtong** [luberda-molinet/FFImageLoading#519]
This plugin is great!
But I have a problem: 
My list cells have over 300 cells. When fling or scrolling listview, images are recycled, user can see the old image before the new one loads (about 0.5 ~2 seconds), causing flicker and unpleasant artifacts for the user. This was occured on both Android and iOS.
I'm using viewcell renderer for my listview
Please refer to link https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/viewcell/
I see that this listview loaded imageview in cell and disposed image before the new one loads, maybe that is reason performance faster.

I tried on my listView when using FFImageLoading version 2.2.9 on viewcell renderer.
My viewcell renderer is based on fastcell solution: https://github.com/twintechs/TwinTechsFormsLib
But I don't know how to set dispose image.
How to user can fling with image that is not recycle old image? I want to create a listview the same as loading friends list on Facebook app. That is if the cells's image loaded then when use rescrolling to that cell, it can display image immediately.
Please check it.
Thank you for reading!

Update: I also refer to #216 but set image.Source = null, it will hurt performance in Xamarin Forms.

**Comment by petersondrew** [comment]
We noticed this same issue, our solution was to use a tiny transparent png as the PlaceHolder property and that prevented the previous image from showing in recycled cells while scrolling/flinging

**Comment by daniel-luberda** [comment]
Two solutions: 

- As @petersondrew said, set any placeholder
- Set image source to null before loading:

Xamarin.Forms: 

```C#
cachedImage.Source = null;
```

Native:

```C#
ImageService.Instance.LoadFile(null).Into(imageView);
```

That's all.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/wiki/FAQ#faq

**Comment by phamthanhtong** [comment]
@petersondrew , @daniel-luberda 
Thanks for your help!
I'll try.

**Comment by EmilAlipiev** [comment]
Hi Sorry, i dont understand this. I am using Xaml. how can I set  cachedImage.Source = null; how can we solve this using xaml only with mvvm binding?

**Comment by daniel-luberda** [comment]
It's not FFImageLoading issue, but binding issue. Read this for a solution: 

https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#usage-in-listview-with-listviewcachingstrategyrecycleelement-enabled
