### ISSUE TITLE
EXIF Rotation on iOS

### ISSUE THREAD

**Issue by chisigo** [luberda-molinet/FFImageLoading#520]
Hello,

I have encountered an error when displaying a rotated image in iOS.

I know there is an issue with the same error in android and that is already fixed.
https://github.com/luberda-molinet/FFImageLoading/issues/442

I am using version 2.2.9 of the library.

Thank you very much. This plugin is great!

**Comment by AndreiMisiukevich** [comment]
Do you get images by url from your own server?

**Comment by chisigo** [comment]
I get images by url from Azure.

**Comment by AndreiMisiukevich** [comment]
`
                    // Fix orientation if needed.
                    if (image.PropertyIdList.Contains(OrientationKey))
                    {
                        var orientation = (int)image.GetPropertyItem(OrientationKey).Value[0];
                        switch (orientation)
                        {
                            case NotSpecified: // Assume it is good.
                            case NormalOrientation:
                                // No rotation required.
                                break;
                            case MirrorHorizontal:
                                image.RotateFlip(RotateFlipType.RotateNoneFlipX);
                                break;
                            case UpsideDown:
                                image.RotateFlip(RotateFlipType.Rotate180FlipNone);
                                break;
                            case MirrorVertical:
                                image.RotateFlip(RotateFlipType.Rotate180FlipX);
                                break;
                            case MirrorHorizontalAndRotateRight:
                                image.RotateFlip(RotateFlipType.Rotate90FlipX);
                                break;
                            case RotateLeft:
                                image.RotateFlip(RotateFlipType.Rotate90FlipNone);
                                break;
                            case MirorHorizontalAndRotateLeft:
                                image.RotateFlip(RotateFlipType.Rotate270FlipX);
                                break;
                            case RotateRight:
                                image.RotateFlip(RotateFlipType.Rotate270FlipNone);
                                break;
                        }
                    }`
// image is Bitmap
// You can try something like this on Servers side

**Comment by chisigo** [comment]
I did fixed the error on server side days ago.
Thank you

**Comment by daniel-luberda** [comment]
@chisigo on iOS exif orientation is applied automatically (it's an os feature). IMO, the case was that invalid exif orientation was included in a file, this should be solved on the image source side. If it's not the case, could you attach sample file with bad orientation, so I could examine it? Thanks.
