### ISSUE TITLE
Cannot load a SVG from XAML

### ISSUE THREAD

**Issue by xperseguers** [luberda-molinet/FFImageLoading#526]
According to your doc (https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support), one should write

```
Source="{Binding image.svg, Converter={StaticResource SvgImageSourceConverter}}"
```

But this just does not work. Specifying `image.svg` within the binding will look for an object `image` and bind to its property `svg`. This just cannot work.

Even if that's obvious, `SvgImageSourceConverter` needs to be loaded. Tried following:

```
    ...
    xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"   
    xmlns:svg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
    ...>

    <ContentPage.Resources>
        <ResourceDictionary>
            <svg:SvgImageSourceConverter x:Key="svgImageSourceConverter" />
        </ResourceDictionary>
    </ContentPage.Resources>

    ...
    <ffimageloading:CachedImage Source="{Binding image.svg, Converter={StaticResource svgImageSourceConverter}}" />
```

Tried with `{Binding 'image.svg', ...` but does not help either.

Only way to get it working is to give the `CachedImage` a name and specify the source from code behind (then facing #522 of course).

As you see, I'm using `CachedImage`. From the doc it's not clear whether the converter could be use with a standard `Image` instead but it does not.

**Comment by YZahringer** [comment]
Same issue, only works with Binding

**Comment by riandesign** [comment]
Same problem here.
With `Binding Source`, declared on code, works fine, but it doesn't work if I put directly like `"Binding test.svg"`

**Comment by riandesign** [comment]
Updated: I just updated the nuget and now SVG doesn't work neither if I declare the binding property nor the file name.

**Comment by daniel-luberda** [comment]
There was a typo on wiki page, fixed it. I added `SvgCachedImage` for simpler usage (you don't need to use converters with it):

```XML
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="FFImageLoading.Forms.Sample.SvgSamplePage"
		xmlns:xamvvm="clr-namespace:Xamvvm;assembly=Xamvvm.Forms"
		xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
		xmlns:fftransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
		xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
		Title="SVG">
	
	<ContentPage.Resources>
		<ResourceDictionary>
	  		<ffimageloadingsvg:SvgImageSourceConverter x:Key="SvgImageSourceConverter"></ffimageloadingsvg:SvgImageSourceConverter>
		</ResourceDictionary>
	</ContentPage.Resources>
	
	<ContentPage.Content>
		<StackLayout>
			
			<!-- FIRST APPROACH: -->
			<ffimageloadingsvg:SvgCachedImage WidthRequest="200" HeightRequest="200" Source="sample.svg"/>		

			<!-- SECOND APPROACH: -->
			<ffimageloading:CachedImage WidthRequest="200" HeightRequest="200"
				Source="{Binding Source, Converter={StaticResource SvgImageSourceConverter}}">
			</ffimageloading:CachedImage>
			
		</StackLayout>
	</ContentPage.Content>
</ContentPage>
```

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/commit/635faa58ddff365f87ba8656c7dd4f2d0d8328e7 should fix this.
