### ISSUE TITLE
App crashes if there are no image by uri (iOS)

### ISSUE THREAD

**Issue by AndreiMisiukevich** [luberda-molinet/FFImageLoading#528]
![ffimage](https://cloud.githubusercontent.com/assets/10124814/23666601/878ac1f6-036c-11e7-8d54-da948d7ed667.png)

Hi, I faced with an crash during handling downloaded image. (Xamarin.Forms, iOS)
I investigated this a little time and decided that it is native code-error.

Check attached Application output, pls

I will send pull request with fix (check it)
https://github.com/luberda-molinet/FFImageLoading/pull/529

Thanks a lot

**Comment by AndreiMisiukevich** [comment]
upd.

This issue appearing when Server (namely .NET-server) returns EmptyResult by our Url

**Comment by AndreiMisiukevich** [comment]
Check it, please

**Comment by molinch** [comment]
Hi I reviewed the change and it is fine. However this shouldn't lead to a crash, only to failing image loading.
What did you face?

**Comment by AndreiMisiukevich** [comment]
Oh, sorry. You are right.
Probably, crashes in my app aren't related with this code.

I think, your can close this thread.

Thanks a lot.
