### ISSUE TITLE
Possible high-pri: wrong images and collisions since 2.2.8

### ISSUE THREAD

**Issue by patook** [luberda-molinet/FFImageLoading#530]
Hey I'm not sure what's going on since 2.2.8 (and 2.2.9) but the wrong image is occasionally loaded from the cache (or stored in the cache). This didn't repro before that.

I traced it through my code:

	ImageService.Instance.LoadUrl(ImageSourcePath).Into(ProfilePicture);

ImageSourcePath is correct. I opened the URL on a browser and it shows up correctly. However, ProfilePicture displays a different URL.

This happens when I refresh the app as well (i.e. when loading from memory). But if I kill the app and restart it, it loads the correct image and then occasionally introduces errors in other images.

I suspect it is something at the memory level cache of FFImageLoading.

**Comment by stopiccot** [comment]
#527

**Comment by daniel-luberda** [comment]
Let's continue in the other issue.
