### ISSUE TITLE
Caching Transforms and Downsampling

### ISSUE THREAD

**Issue by michaelstonis** [luberda-molinet/FFImageLoading#532]
I am using FFImageLoading to pull down some images from the web, apply some transforms and downsample the overall image. I noticed that when I had the app in memory, everything loaded up quickly, but after restarting the app hydrating the images from disk took a long time. I did some investigation and it looks as if only the original image is cached off and not the final image after transformation and downsampling. Is it possible to cache off those images as well or is there a built-in mechanism for handling that kind of scenario?

**Comment by daniel-luberda** [comment]
Yes, it's possible: 

```C#
            var stream = ImageService.Instance.LoadCompiledResource("loading.png")
                        .Transform(new CircleTransformation()) /*downsample etc...*/
                        .AsJPGStreamAsync(); // or PNG

then just save the stream to a file and use that file when loading.
```

**Comment by EmilAlipiev** [comment]
hi @daniel-luberda, I am not sure if I understand it correctly. I am just using it in xaml as below and this is inside a listview loaded dynamicly. how can we achieve that for a listview? It will be really difficult to loop through every time with your code above.

```
 <ffimageloading:CachedImage Grid.Column="0" Grid.Row="1"  HorizontalOptions="Start" DownsampleToViewSize="true"
                     BackgroundColor="Transparent" Source="{Binding path}" />
```

on the other hand, for the static images, how does it help to use PreLoad function. Does it to the same job?

`    ImageService.Instance.LoadCompiledResource("image.png").Preload();`
