### ISSUE TITLE
Android - fade animation doesn't work when loading from cache and no placeholder is set

### ISSUE THREAD

**Issue by lukejaylarsen** [luberda-molinet/FFImageLoading#536]
The following code:

ImageService.Instance
.LoadUrl (photoURL)
.FadeAnimation (true, true, 500)
.Into (imageViewAsync);

works correctly in iOS, but in Android the images load instantly without a fade effect. Am I missing something here? Tried simulators and real device using multiple Android API levels...

**Comment by lukejaylarsen** [comment]
Development: fading in an image DOES work as long as I have a placeholder set, however, there is no crossfade from one image to the next (as there is on iOS)...

**Comment by daniel-luberda** [comment]
Yes, that should be fixed to unify behaviour between platforms. Temporary solution could be to set your placeholder to the destination image too.
