### ISSUE TITLE
Cancel cache / invalidate on Xamarin Forms?

### ISSUE THREAD

**Issue by shayo** [luberda-molinet/FFImageLoading#538]
I'm having trouble forcing cache update on an image using Xamarin Forms.
The Documentation API says
Single item

For a single item some static methods exists directly on CachedImage.

But I can't find such method. Is documentation out of date?
I've tried to directly 
ProfileImage.CacheDuration = new TimeSpan(0);
ProfileImage.ReloadImage();

but the image still doesn't refresh.

**Comment by EmmanVazz** [comment]
Is this what you are looking for? 
https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#clear-cache

**Comment by shayo** [comment]
How do I obtain the key when calling to Invalidate cache?

**Comment by shayo** [comment]
Nevermind.I got it. The key is the imagesource.
Things are working now.
