### ISSUE TITLE
Images aren't appearing System.Net.HttpWebRequest:ResendContentFactory' is inaccessible from method

### ISSUE THREAD

**Issue by AndreiMisiukevich** [luberda-molinet/FFImageLoading#539]
Hi again, colleagues.
We faced with an issue during first app launching.
Images aren't showing (Seems like it's caching issue)

We tested app on Samsung Galaxy S4, iPhone 5s and emulators/simulators 
(More often issues is reproduced on Android Devices)

Please, see this app-output

System.FieldAccessException: Field `System.Net.HttpWebRequest:ResendContentFactory' is inaccessible from method `System.Net.Http.HttpClientHandler/<SendAsync>c__async0:MoveNext ()'

 	0xC in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw	C#
 	0x4E in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess	C#
 	0x2F in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification	C#
 	0xC in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd	C#
 	0x6 in System.Runtime.CompilerServices.ConfiguredTaskAwaitable<System.Net.Http.HttpResponseMessage>.ConfiguredTaskAwaiter.GetResult	C#
>	0x13B in FFImageLoading.Cache.DownloadCache.DownloadAsync at C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:96	C#
 	0x38 in System.Runtime.CompilerServices.AsyncTaskMethodBuilder<byte[]>.Start<FFImageLoading.Cache.DownloadCache.<DownloadAsync>d__13>	C#
 	0x48 in FFImageLoading.Cache.DownloadCache.DownloadAsync	C#
 	0x4B in FFImageLoading.Cache.DownloadCache.<>c__DisplayClass12_0.<DownloadAndCacheIfNeededAsync<DownloadAndCacheIfNeededAsync>b__0>d at C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:55,29	C#
 	0x38 in System.Runtime.CompilerServices.AsyncTaskMethodBuilder<byte[]>.Start<FFImageLoading.Cache.DownloadCache.<>c__DisplayClass12_0.<<DownloadAndCacheIfNeededAsync>b__0>d>	C#
 	0x27 in FFImageLoading.Cache.DownloadCache.	C#
 	0x32 in FFImageLoading.Retry.DoAsync<byte[]> at C:\projects\ffimageloading\source\FFImageLoading.Common\Helpers\Retry.cs:17,21	C#
 	0x6 in System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext	C#
 	0x8F in System.Threading.ExecutionContext.RunInternal	C#
 	0x4 in System.Threading.ExecutionContext.Run	C#
 	0x49 in System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run	C#
 	0x26 in System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction	C#
 	0x81 in System.Threading.Tasks.Task.FinishContinuations	C#
 	0x46 in System.Threading.Tasks.Task.FinishStageThree	C#
 	0x59 in System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult	C#
 	0x5B in System.Threading.Tasks.Task.DelayPromise.Complete	C#
 	0x6 in System.Threading.Tasks.Task.AnonymousMethod__1	C#
 	0x13 in System.Threading.Timer.Scheduler.TimerCB	C#
 	0x20 in System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem	C#
 	0x97 in System.Threading.ThreadPoolWorkQueue.Dispatch	C#
 	0x0 in System.Threading._ThreadPoolWaitCallback.PerformWaitCallback	C#

So, I found an interesting link about this [BugZilla](https://bugzilla.xamarin.com/show_bug.cgi?id=46176)

**Comment by AndreiMisiukevich** [comment]
I'm not sure, but my PR, maybe, can help.
Thanks

**Comment by daniel-luberda** [comment]
This is not FFImageLoading issue, rather Xamarin: 
- https://bugzilla.xamarin.com/show_bug.cgi?id=46176
- https://github.com/paulcbetts/ModernHttpClient/issues/228

The workaround is to use native `HttpClient` handlers: https://github.com/luberda-molinet/FFImageLoading/wiki/Native-Http-handlers-=-better-performance
