### ISSUE TITLE
Http-Header-Caching

### ISSUE THREAD

**Issue by Shibynator** [luberda-molinet/FFImageLoading#541]
Hi

First of all gratulation to this awesome library. I'm testing the library right now and I am really impressed so far.:-) But now I have a question. Is the library capable of detecting the cache-duration from a standard Http Header with cache-informations?

Regards 

Daniel

**Comment by EmmanVazz** [comment]
Hmmm not sure but you can implement your own [HttpClientHandler ](https://github.com/luberda-molinet/FFImageLoading/wiki/Authentication-Support), that might give you the ability to extract that cache-duration.

**Comment by Shibynator** [comment]
Well I had this idea too, but with that solution you can only set it globally and not specific for that image.

**Comment by EmmanVazz** [comment]
Something like this would allow you to access the cache settings of each individual request. 

```
public class CacheControlClientHandler : HttpClientHandler
    {
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            HttpResponseMessage response = await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
            var CacheControl = response.Headers.CacheControl;
            return response;
        }
    }
```

You would probably need to keep some struct to that matched urls for image with values from the response. Then you have to bind those values to the CachedImage's CacheDuration property, thankfully it is [bindable](https://github.com/luberda-molinet/FFImageLoading/blob/f88772e65b8d3132be77e7513db9abd34d750069/source/FFImageLoading.Forms/CachedImage.cs#L269).

**Comment by daniel-luberda** [comment]
@Shibynator You can provide your own `IDownloadCache` implementation (via custom config), it's a really simple class: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Cache/DownloadCache.cs

I added a new method which you could override: 

```C#
        protected virtual void ModifyParametersAfterResponse(HttpResponseMessage response, TaskParameter parameters)
        {
            // YOUR CUSTOM LOGIC HERE
            // eg: parameters.CacheDuration = response.Headers.CacheControl.MaxAge;
        }
```

**Comment by Shibynator** [comment]
Realy nice, thx. It's not already on NUGET right?

**Comment by rudacs** [comment]
parameters.CacheDuration can not be set!
