### ISSUE TITLE
Image as attribute

### ISSUE THREAD

**Issue by pooran** [luberda-molinet/FFImageLoading#542]
There are some controls that expect Image as input, and we cannot substitute CachedImage to it. How about having an attribute for the CachedImage class that returns an Image?

**Comment by AndreiMisiukevich** [comment]
I think, the simplest way to implement is creating another package/CachedImageOriginal class, where CachedImage will be inheriting from Image, don't I ?

**Comment by AndreiMisiukevich** [comment]
Maybe, create an interface, smth like ICachedImage..

**Comment by EmmanVazz** [comment]
You can use the ImageService.Instance interface to load an image into views. [It is in the wiki.](https://github.com/luberda-molinet/FFImageLoading/wiki/API). We use it to set tab icons in custom renderers for our Forms project. Do you know what control you are trying to use FF with?

**Comment by daniel-luberda** [comment]
You can also get images as `Stream`:

```C#
var stream = ImageService.Instance.LoadCompiledResource("loading.png")
            .Transform(new CircleTransformation()) /*downsample etc...*/
            .AsJPGStreamAsync(); // or PNG
```

Then it's easy to create own `StreamImageSource` from it.

**Comment by daniel-luberda** [comment]
It's impossible to "convert" `CachedImage` view to `Image` view. They are API compatible, but they differ a lot internally. I'll close this one then. Thanks.
