### ISSUE TITLE
Android XML CircleTransformation with MvxImageLoadingView

### ISSUE THREAD

**Issue by PaulVipond** [luberda-molinet/FFImageLoading#546]
I've successfully used MvxImageLoadingView to bind to a drawable resource as the first step. Now I want to display the images as circles. Is it possible to include the transformation directly in Android XML?

```
  <ffimageloading.cross.MvxImageLoadingView
              android:layout_width="50dp"
              android:layout_height="50dp"
              android:paddingRight="10dip"
              app:MvxBind="DataLocationUri ThumbnailUri">
    <ffimageloading.transformations.CircleTransformation
      app:BorderSize="2dp"/>
  </ffimageloading.cross.MvxImageLoadingView>
```

The BorderSize attribute reference won't compile, and if I leave it out, I just get a blank list.

**Comment by daniel-luberda** [comment]
`MvxImageLoadingView` is depreciated. Please use `MvxCachedImageView`. Fully working sample here: https://github.com/luberda-molinet/FFImageLoading/tree/master/samples/ImageLoading.MvvmCross.Sample

```XML
    <ffimageloading.cross.MvxCachedImageView
        android:layout_width="match_parent"
        android:layout_height="100dp"
        local:MvxBind="Transformations Transformations; DownSampleWidth DownSampleWidth; ImagePath Url" />
```
