### ISSUE TITLE
Wrong image loaded when creating from Stream

### ISSUE THREAD

**Issue by hardcodet** [luberda-molinet/FFImageLoading#550]
I'm running in a bug that seems to have been introduced with 2.2.8 (2.2.9 is the same):

The code below works the first time when I attempt to load an image from my Android's media gallery.
Here's what happens:

* User opens page, system displays image X (good)
* User loads image A from the phone's gallery using the media picker using the code below.
* System replaces image X by image A (good)
* User indicates she wants to change the picture again and selects image B.
* **System "loads" image A again. (bad)**

* User closes the page and reopens it
* System displays image X (good)
* User indicates she wants to change the image, selects image C (or B, doesn't matter).
* **System replaces image X by image A. (bad)**

So the bottom line is: Once I loaded an image through the media picker, any subsequent image will be ignored and always that initially loaded image will be displayed, even if the page and thus the image control are recreated. My money is on the caching here, although playing with CacheType and CacheDurations didn't help.

XAML:

            <forms:CachedImage Source="{Binding ProfilePictureSource}"
                               DownsampleToViewSize="False"
                               HorizontalOptions="Center"
                               HeightRequest="80"
                               WidthRequest="80" />

C#

        public async void ChangeProfilePicture()
        {
            MemoryStream profilePictureStream = await MediaPicker.PickImageAsync();

            ProfilePictureSource = ImageSource.FromStream(() => profilePictureStream);
        }

**Comment by hardcodet** [comment]
Just tested: Same on iOS.

**Comment by daniel-luberda** [comment]
Just disable cache. Set `CacheType` to `Disk`

By default, FFImageLoading uses `Stream` checksums as cache keys, please be sure your file checksum changes or you can disable `Stream` caching (custom config - `StreamChecksumsAsKeys` property).
