### ISSUE TITLE
iOS 10.3 [beta] CachedImageRenderer.Init() in AppDelegate.cs does not get compiled

### ISSUE THREAD

**Issue by mofadevs** [luberda-molinet/FFImageLoading#553]
Hi
It throws the following while compiling and get failed:
**Failed to resolve "Xamarin.Forms.SizeRequest Xamarin.Forms.VisualElement::OnMeasure(System.Double,System.Double)" reference from "Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null"**

**Comment by daniel-luberda** [comment]
Hi @mofadevs 

What version of Xamarin.Forms?
