### ISSUE TITLE
AddBackgroundColor transformation

### ISSUE THREAD

**Issue by jorgenstorlie** [luberda-molinet/FFImageLoading#555]
![colorimage](https://cloud.githubusercontent.com/assets/2240379/24541738/fc2c973e-15f8-11e7-81f7-9fbf4760e548.jpg)
![161l](https://cloud.githubusercontent.com/assets/2240379/24541767/12ce88f8-15f9-11e7-99bd-0dafe944ece2.png)

How can I set the background color on a image that uses CircleTransformation?

The image is transparent, I want to change backgroundcolor and tint.

Here is my code:

var taskImage = ImageService.Instance.LoadFile(filename)
.ErrorPlaceholder("161L.png", ImageSource.ApplicationBundle)
.LoadingPlaceholder("161L.png", ImageSource.ApplicationBundle);

taskImage.Transform(new TintTransformation(255, 95, 28, 128) { EnableSolidColor = true });
taskImage.Transform(new CircleTransformation(10, "#b0e0e6"));
taskImage.Into(imageView);

I want it to be like screenshot attached,

**Comment by EmmanVazz** [comment]
Have you tried setting the background on the imageView?

**Comment by jorgenstorlie** [comment]
Yes, image is coloured, but it not circled. 

I try to make the image colored and circled

**Comment by EmmanVazz** [comment]
so you set the background color, imageView.BackgroundColor, before you use it? If the image is transparent, it should just show the background color of the imageView.

**Comment by jorgenstorlie** [comment]
It have background color but not circled.

Maybe I need to make a new Transformation
like this
CircledWithFillTransformation
https://github.com/luberda-molinet/FFImageLoading/issues/307
?

imageView.BackgroundColor = UIColor.Yellow;
taskImage.Transform(new CircleTransformation(10, "#b0e0e6"));

![simulator screen shot 31 mar 2017 21 03 03](https://cloud.githubusercontent.com/assets/2240379/24565506/bc41279a-1655-11e7-8d63-06f07b36189b.png)

**Comment by EmmanVazz** [comment]
You need to make the actual imageView into a circle. For Xamarin.iOS [this](https://forums.xamarin.com/discussion/24074/circle-around-uimage-how) seems to work.

**Comment by jorgenstorlie** [comment]
OK
I can do this

One more question, is it possible to do a Transformation only on the placeholder image, not the downloaded image?

**Comment by EmmanVazz** [comment]
I saw your other question. I am not sure however you can just change the transformation on the [Success](https://github.com/luberda-molinet/FFImageLoading/wiki/API#success) event.

**Comment by jorgenstorlie** [comment]
I can try that,
Do you have a sample showing how to do this?

**Comment by EmmanVazz** [comment]
Nah I don't happen to have a sample.

**Comment by jorgenstorlie** [comment]
No success

I want to TintTransformation only on ErrorPlaceholder and LoadingPlaceholder
What is wrong?


				var taskImage2 = ImageService.Instance.LoadUrl(imageURL)
 .ErrorPlaceholder("161L.png", ImageSource.ApplicationBundle)
.LoadingPlaceholder("161L.png", ImageSource.CompiledResource)
;

				taskImage2.Success((size, loadingResult) =>
				{
					aSuccess = true;

					//taskImage2.Transform(new TintTransformation(100, 12, 28, 12) { EnableSolidColor = true });

				});


					if (aSuccess != true)
						taskImage2.Transform(new TintTransformation(255, 95, 28, 128) { EnableSolidColor = true });


				taskImage2.Transform(new CircleTransformation(10, "#b0e0e6"));

				taskImage2.Into(imageView);

**Comment by EmmanVazz** [comment]
well you need to change the transformation inside the Success Command. That code is ran when the images is loaded. Anything outside that runs before that so that if (aSuccess != true) statement runs when you create the image not when the success is evaluated. You can also use the other Callbacks: [Error](https://github.com/luberda-molinet/FFImageLoading/wiki/API#error) or [Finish](https://github.com/luberda-molinet/FFImageLoading/wiki/API#process-finished).

**Comment by jorgenstorlie** [comment]
I tried but did not figure out how

How can I remove a TintTransformation inside this?
taskImage2.Success((size, loadingResult) =>
				{
					aSuccess = true;
				
				});

**Comment by EmmanVazz** [comment]
you can't do taskImage2.Transform.Clear() inside of Success?

**Comment by jorgenstorlie** [comment]
I added this:

		taskImage2.Success((size, loadingResult) =>
				{
					aSuccess = true;
				taskImage2.Transformations.Clear();// .Transform.Clear();
				});

the image is still transformed

**Comment by EmmanVazz** [comment]
Try  taskImage2.Transformations = new List<ITransformation>(). Sometimes Clear() doesn't raise the onPropetyChanged event to trigger updating the UI.

**Comment by jorgenstorlie** [comment]
taskImage2.Transformations = new List();
Thus does not compile


I also add this
taskImage2.Transform(new CircleTransformation(10, "#b0e0e6"));
but it does not have any effect


				taskImage2.Success((size, loadingResult) =>
				{
					aSuccess = true;
			//		taskImage2.Transformations = new List();
		 taskImage2.Transformations.Clear();// .Transform.Clear();
					taskImage2.Transform(new CircleTransformation(10, "#b0e0e6"));
				});

**Comment by EmmanVazz** [comment]
I meant = new List<ITransformation>();

**Comment by jorgenstorlie** [comment]
taskImage2.Transformations = new List<ITransformation>();
		
does not compile:

Property or indexer `FFImageLoading.Work.TaskParameter.Transformations' cannot be assigned to (it is read-only) (CS0200) (Simple.iOS.Sample)

**Comment by EmmanVazz** [comment]
Hmm yeah I am out of ideas.

**Comment by jorgenstorlie** [comment]
Seems to be difficult to only add TintTransformation on placeholders

an easy solution is just to skip 
TintTransformation
and add this before loading on the placeholder images

**Comment by AndreiMisiukevich** [comment]
I have one strange idea.
For implementing this you can create a custom control.
Something like this:

`var control = new AbsoluteLayout();
control.Children.Add(imageBackground, new Rectangle(0,0,1,1), Flags.All);
control.Children.Add(mainImage, new Rectangle(0,0,1,1), Flags.All);`

**Comment by jorgenstorlie** [comment]
I have now just one issue
On android the tint color is not saved in the  bitmap I create

Do you see any reason?



		public override void OnBindViewHolder(RecyclerView.ViewHolder viewHolder, int position)
		{
			var item = Items[position];

			var vh = viewHolder as ViewHolder;

			vh.Title.Text = position.ToString();
			vh.ItemView.Tag = position;


			Android.Graphics.Drawables.Drawable drawable = context.Resources.GetDrawable(Resource.Drawable.ic_365);
			drawable.SetTint(Color.Red);

			drawable.SetFilterBitmap(true);


			//		drawable.SetColorFilter(Color.RoyalBlue);


			//	Bitmap bitmap = BitmapFactory.DecodeResource(context.Resources, Resource.Drawable.ic_365);
			//	bitmap. .SetTint(Color.Red);



			Bitmap bitmap = ((BitmapDrawable)drawable).Bitmap;

		//	((BitmapDrawable)drawable).SetTint(Color.Pink);
			//		bitmap.co .SetColorFilter(ImageColor);

			string folder = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
			string localFilename = "ic_365.png";
			string localPath = Path.Combine(folder, localFilename);


	//		File.Delete(localPath);

			if (File.Exists(localPath) == false)
			{
				using (var os = new FileStream(localPath, FileMode.CreateNew))
				{
					bitmap.Compress(Bitmap.CompressFormat.Png, 100, os);
				}
			}


			//	vh.Image.SetBackgroundColor(Color.Green);
			//		vh.Image.SetImageDrawable(drawable);


			GradientDrawable shape2 = new GradientDrawable();

			shape2.SetSize(vh.Image.Width, vh.Image.Width);
			shape2.SetShape(ShapeType.Oval);

			shape2.SetColor(Color.Blue);
			vh.Image.SetBackgroundDrawable(shape2);


			/*
				ImageService.Instance.LoadFile(localPath)
				  .Retry(3, 200)
				  .DownSample(100, 100)
			.Transform(new CircleTransformation(10, "#b0e0e6"))
							.LoadingPlaceholder(localPath, FFImageLoading.Work.ImageSource.Filepath)
				  .ErrorPlaceholder(localPath, FFImageLoading.Work.ImageSource.Filepath)
				  .Into(vh.Image);

		*/
			ImageService.Instance.LoadUrl(item)
			   .Retry(3, 200)
			   .DownSample(100, 100)
							.Transform(new CircleTransformation(10, "#b0e0e6"))
			   .LoadingPlaceholder(localPath, FFImageLoading.Work.ImageSource.Filepath)
			   .ErrorPlaceholder(localPath, FFImageLoading.Work.ImageSource.Filepath)
			   .Into(vh.Image);

		}

**Comment by jorgenstorlie** [comment]
[ImageLoading.Sample.zip](https://github.com/luberda-molinet/FFImageLoading/files/893324/ImageLoading.Sample.zip)

**Comment by jorgenstorlie** [comment]
the drawable has correct tint
the bitmap is not tinted

do you see any reason?

**Comment by jorgenstorlie** [comment]
this worked:

	Bitmap bitmap = Bitmap.CreateBitmap(40, 40, Android.Graphics.Bitmap.Config.Argb8888);

			Canvas canvas = new Canvas(bitmap);
			drawable.SetBounds(0, 0, canvas.Width, canvas.Height);
			drawable.Draw(canvas);

Do you have a better solution?

**Comment by daniel-luberda** [comment]
I can add `AddBackgroundTransformation` which could be used combined with other transformations. What do you think?

**Comment by daniel-luberda** [comment]
And the other enhancement (transformation selector on placeholders / normal images and many other scenarios) is already implemented. Take a look at this: https://github.com/luberda-molinet/FFImageLoading/issues/556

**Comment by daniel-luberda** [comment]
I'll close this one as it's easier to use SVG for such cases (and it's already working).
