### ISSUE TITLE
problem with CachedImage CacheType property

### ISSUE THREAD

**Issue by Mahdad-Baghani** [luberda-molinet/FFImageLoading#557]
Hi @daniel-luberda.
I have something like this in my app: ( I am using the StackedList Control from Microsoft Bikesharing demo app):
` <controls:StackedList>

            <controls:StackedList.ItemTemplate>

                <DataTemplate>
                            <Grid>

                                    <Grid.WidthRequest>

                                        <OnPlatform

                                            x:TypeArguments="x:Double"

                                            iOS="210"

                                            Android="240"/>

                                    </Grid.WidthRequest>

                                    <AbsoluteLayout>

                                        <ffimageloading:CachedImage

                                            Source="{Binding suggestionImagePath}"

                                            CacheType="Disk"

                                            CacheDuration="30"

                                            DownsampleToViewSize="True"

                                            Aspect="AspectFill"

                                            AbsoluteLayout.LayoutFlags="All"

                                            AbsoluteLayout.LayoutBounds="0, 0, 1, 1">

                                            <ffimageloading:CachedImage.LoadingPlaceholder>

                                                <OnPlatform

                                                    x:TypeArguments="ImageSource"

                                                    Android="placeholder_240x170"

                                                    iOS="placeholder_240x170"/>

                                            </ffimageloading:CachedImage.LoadingPlaceholder>

                                        </ffimageloading:CachedImage>

                                    </AbsoluteLayout>

                                </Grid>

                            </DataTemplate>

                        </controls:StackedList.ItemTemplate>

                    </controls:StackedList>`

the problem is that CachedImage just loads the first two Images in my templates, and the others are just blank! it doesn't make any difference if I use a local or remote image Path, it just loads the first two images.
what is the problem!!!???

**Comment by Mahdad-Baghani** [comment]
@daniel-luberda: 
I managed to get the images showing by removing the cache options from the CachedImage. only then the images would appear; however I need the caching functionality. what should I do?

**Comment by daniel-luberda** [comment]
@Mahdad-Baghani I don't understand. Caching is enabled by default, you must disable it specifically. Could you upload a working reproduction?

**Comment by Mahdad-Baghani** [comment]
@daniel-luberda 
I first thought this problem was related to the fact that I was using the cachedImage in a DataTemplate, but then I realized that if I explicitly set CacheType="Disk" and CacheDuration="30" (for instance!), caching function does not work properly.
so if I define a 
`<ffimageloading:CachedImage
                                            Source="{Binding ImagePath}"
                                            CacheType="Disk"
                                            CacheDuration="30"
                                            DownsampleToViewSize="True"
                                            Aspect="AspectFill"
                                            AbsoluteLayout.LayoutFlags="All"
                                            AbsoluteLayout.LayoutBounds="0, 0, 1, 1">
                                        </ffimageloading:CachedImage>`
inside a dataTemplate this would be the result event if I'm connected to internet and I'm 100% positive about the imageSource:
[http://p30up.ir/uploads/f70559274.jpg](url)
[http://p30up.ir/uploads/f76122349.jpg](url)
[http://p30up.ir/uploads/f339871496.jpg](url)

but if I change my cachedImage to this:
`<ffimageloading:CachedImage
                                            Source="{Binding ImagePath}"
                                            CacheDuration="30"
                                            DownsampleToViewSize="True"
                                            Aspect="AspectFill"
                                            AbsoluteLayout.LayoutFlags="All"
                                            AbsoluteLayout.LayoutBounds="0, 0, 1, 1">
                                        </ffimageloading:CachedImage>`
I get this:
[http://p30up.ir/uploads/f53255421.jpg](url)
[http://p30up.ir/uploads/f197843244.jpg](url)

**Comment by daniel-luberda** [comment]
@Mahdad-Baghani FFImageLoading has two cache types implementations: 

- MemoryCache
- DiskCache

Difference here: https://youtu.be/Dca3ksv8esU

When you set disk cache type to disk only, image loading is just slower (it's loaded from the disk every time). By default all cache implementations are enabled. 

Is it what you're experiencing?

**Comment by randalvance** [comment]
I am also experiencing this issue. If I explicitly assign CacheType as disk, some images doesn't load at all.

**Comment by daniel-luberda** [comment]
@randalvance Could you make a sample project with your issue? Without it, I won't be able to help.
