### ISSUE TITLE
[question] Are nightly/beta builds available?

### ISSUE THREAD

**Issue by Shaddix** [luberda-molinet/FFImageLoading#558]
Hi guys,

  It's been a while since the last NuGet package (Feb, 25), and there's a number of major issues fixed (I'm extremely interested in iOS crash/freezing fixes).
  Can you push an update to nuget? Is there any feed we can have latest binaries from?

Thanks for the great lib!

**Comment by EmmanVazz** [comment]
https://www.nuget.org/packages/Xamarin.FFImageLoading Seems like pre-release was pushed today.

**Comment by Shaddix** [comment]
thanks!
Can be closed
