### ISSUE TITLE
ErrorPlaceHolder ErrorCommand not working on Android

### ISSUE THREAD

**Issue by goldenkeyz-plaroche** [luberda-molinet/FFImageLoading#559]
I have a problem with the ErrorPlaceholder on Android.
I set in XAML the ViewCell like under and on iOS it is OK but the ErrorPlaceholder disappear  On Android.
`<StackLayout IsVisible="{Binding VisuelIsVisible}" HeightRequest="{Binding VisuelHeight}" Spacing="0" VerticalOptions="Start">`
		
`<ffimageloading:CachedImage` ErrorCommand="{Binding ErrorLoadingCommand}" Source="{Binding VisuelImageSource}" Aspect="AspectFill" WidthRequest="{Binding VisuelWidth}" HeightRequest="{Binding VisuelHeight}">`

			`<ffimageloading:CachedImage.LoadingPlaceholder>`
				`<OnPlatform x:TypeArguments="ImageSource"`
						              `     iOS="Images/NoPics/error_picture.png"`
						               `     Android="error_picture.png"`
						                  `  WinPhone=""/>`
			</ffimageloading:CachedImage.LoadingPlaceholder>`
			`<ffimageloading:CachedImage.ErrorPlaceholder>`
				`<OnPlatform x:TypeArguments="ImageSource"`
						                  `  iOS="Images/NoPics/error_picture.png"`
						                   ` Android="error_picture.png"`
						                 `   WinPhone=""/>`
			`</ffimageloading:CachedImage.ErrorPlaceholder>`
		`</ffimageloading:CachedImage>`
`</StackLayout>`

Sorry for code indentation .
``

**Comment by goldenkeyz-plaroche** [comment]
More Infos :
iOS fire ErrorCommand while Android fire SuccessCommand on the same broken link uri (image) :(

**Comment by AndreiMisiukevich** [comment]
Hi @goldenkeyz-plaroche 
1) What versions of FFImage and Xamarin.Forms do you use?
2) Could you provide this url link or a small sample project with this issue?

**Comment by goldenkeyz-plaroche** [comment]
Hello, i use the latest version of FFImage 2.2.9 and Xamarin Forms 2.3.3.193.
This is a private project for a client who don't want the source code out on github.
the xaml is this provide upper, the model VisuelImageSource Binding is jsut :
VisuelImageSource = ImageSource.FromUri(new Uri(uri));
Thanks

**Comment by XavierQuincieux** [comment]
Hello,

I have the same issue. Can't see ErrorPlaceholder on Android. 

FFImage version : 2.2.9
Xamarin Forms version : 2.3.4.231

Any thoughts about it ?

Thanks

**Comment by daniel-luberda** [comment]
- Without any reproduction it's hard to guess what may be the cause of it. 
- When image loading fails, exception is logged to the console. Do you have any?

**Comment by XavierQuincieux** [comment]
There's no exception logged to the console when the image loading fails in this case. This is the only log that appears :

[skia] --- SkAndroidCodec::NewFromStream returned null

In my case, it happens when the image (which is hosted on a server) exists but the file is invalid and the data in it does not represent a picture.

Here is an example link : 
http://files-dev.mytennisplayer.com/images/posts/32fdd345-79ab-4ea3-b90a-8f13fb1469d2.jpg

**Comment by goldenkeyz-plaroche** [comment]
Hello,
Thanks to XavierQuincieux to provide us a broken link.

Here is the sample, clearly demonstrate that on Android, the SuccessCommand is trigger with the broken link and not on iOS (ErrorCommand is trigger).

Best reagrds

Paulin.
[FFLoadingTest.zip](https://github.com/luberda-molinet/FFImageLoading/files/986259/FFLoadingTest.zip)

**Comment by AndreiMisiukevich** [comment]
Thanks a lot for help, colleagues! @goldenkeyz-plaroche @XavierQuincieux 

@daniel-luberda , Validate please my PR with potential fix

**Comment by daniel-luberda** [comment]
Hi @AndreiMisiukevich, great fix! I'll merge it. Thanks :)
