### ISSUE TITLE
BlurredTransformation does not appear

### ISSUE THREAD

**Issue by rmlm** [luberda-molinet/FFImageLoading#562]
Hi guys!

I'm trying apply the BlurredTransformation  to an image but I cant make its work :(
I dont know if its relevant, but I'm using Prims to xamarin.forms.

Tested on android simulator with Android 6.0

**Here is my xaml:**

`<ffimageloading:CachedImage Aspect="AspectFill" HorizontalOptions="FillAndExpand" 
                                            HeightRequest="150" FadeAnimationEnabled="True" DownsampleToViewSize="True" IsVisible="{Binding HasCover}"
                                            Source="{Binding Group.CoverPath}">
                    <ffimageloading:CachedImage.Transformations>
                        <fftransformations:BlurredTransformation Radius="20"/>
                    </ffimageloading:CachedImage.Transformations>
                </ffimageloading:CachedImage>`

**MainActivity.cs**

`
protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            CachedImageRenderer.Init();
            var config = new FFImageLoading.Config.Configuration()
            {
                VerboseLogging = false,
                VerbosePerformanceLogging = false,
                VerboseMemoryCacheLogging = false,
                VerboseLoadingCancelledLogging = false,
                Logger = new CustomLogger(),
            };
            ImageService.Instance.Initialize(config);

            global::Xamarin.Forms.Forms.Init(this, bundle);

            UserDialogs.Init(this);
            Xamarin.FormsMaps.Init(this, bundle);

            LoadApplication(new App(new AndroidInitializer()));
        }`

Version of xamarin forms and ffloadingimage:
`  <package id="Xamarin.FFImageLoading" version="2.2.9" targetFramework="monoandroid60" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.9" targetFramework="monoandroid60" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.9" targetFramework="monoandroid60" />
  <package id="Xamarin.Forms" version="2.3.4.224" targetFramework="monoandroid60" />
`

Gives me the following error:

`04-05 21:30:52.676 I/mono-stdout( 4127): Image loading failed: https://sitename.blob.core.windows.net/photos/1400b2d4-6bf2-491a-ab26-9ed6ed698074.jpg;0x300BlurredTransformation,radius=20

04-05 21:30:52.677 I/mono-stdout( 4127): Java.Lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference

04-05 21:30:52.677 I/mono-stdout( 4127):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 

04-05 21:30:52.677 I/mono-stdout( 4127):   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12649 

04-05 21:30:52.677 I/mono-stdout( 4127):   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x0001b] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:97 

04-05 21:30:52.677 I/mono-stdout( 4127):   at Android.Renderscripts.RenderScript.Create (Android.Content.Context ctx) [0x0002c] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Renderscripts.RenderScript.cs:626 

04-05 21:30:52.677 I/mono-stdout( 4127):   at FFImageLoading.Transformations.BlurredTransformation.ToBlurred (Android.Graphics.Bitmap source, Android.Content.Context context, System.Single radius) [0x0003c] in C:\projects\ffimageloading\source\FFImageLoading.Transformations.Droid\BlurredTransformation.cs:45 
04-05 21:30:52.677 I/mono-stdout( 4127):   at FFImageLoading.Transformations.BlurredTransformation.Transform (Android.Graphics.Bitmap source) [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Transformations.Droid\BlurredTransformation.cs:33 

04-05 21:30:52.677 I/mono-stdout( 4127):   at FFImageLoading.Transformations.TransformationBase.Transform (FFImageLoading.Work.IBitmap source) [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Transformations\TransformationBase.cs:13 

04-05 21:30:52.677 I/mono-stdout( 4127):   at FFImageLoading.PlatformImageLoaderTask`1+<PlatformGenerateImageAsync>d__7[TImageView].MoveNext () [0x00618] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Work\PlatformImageLoadingTask.cs:211 
04-05 21:30:52.677 I/mono-stdout( 4127): --- End of stack trace from previous location where exception was thrown ---

04-05 21:30:52.677 I/mono-stdout( 4127):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 

04-05 21:30:52.677 I/mono-stdout( 4127):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 

04-05 21:30:52.677 I/mono-stdout( 4127):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 

04-05 21:30:52.677 I/mono-stdout( 4127):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 

04-05 21:30:52.677 I/mono-stdout( 4127):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 

04-05 21:30:52.677 I/mono-stdout( 4127):   at FFImageLoading.Work.ImageLoaderTask`2+<RunAsync>d__109[TImageContainer,TImageView].MoveNext () [0x003f4] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:428 

04-05 21:30:52.677 I/mono-stdout( 4127):   --- End of managed Java.Lang.NullPointerException stack trace ---

04-05 21:30:52.677 I/mono-stdout( 4127): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference

04-05 21:30:52.677 I/mono-stdout( 4127): 	at android.renderscript.RenderScript.create(RenderScript.java:1433)

04-05 21:30:52.677 I/mono-stdout( 4127): 	at android.renderscript.RenderScript.create(RenderScript.java:1408)

04-05 21:30:52.677 I/mono-stdout( 4127): 	at android.renderscript.RenderScript.create(RenderScript.java:1395)`

What could it be?
Thanks for any help

**Comment by daniel-luberda** [comment]
Probably linker removes transformation code. Put this somewhere in you `MainActivity.cs` `OnCreate` override: `var ignore = new BlurredTransformation()`.

**Comment by daniel-luberda** [comment]
Somehow `new ContextWrapper(Android.App.Application.Context)` returns `null`. Any ideas?

You can set `BlurredTransformation.LegacyMode=true` in an Android specific project (it's a static property). I'll make a workaround which will do it automatically when context is null.
