### ISSUE TITLE
loading images from file are slow

### ISSUE THREAD

**Issue by jorgenstorlie** [luberda-molinet/FFImageLoading#564]
I do this in a recycler view:

	taskImage = ImageService.Instance.LoadFile(localPath)
										.ErrorPlaceholder(localPath, ImageSource.Filepath)
				                        .LoadingPlaceholder(localPath, ImageSource.Filepath);
	
					taskImage.Into(imageView);

I have 2 problems:
1)Loading of images are slow first time loaded
2)Placeholder images are not shown

This works:
imageView.SetImageBitmap(BitmapFactory.DecodeFile(localPath));

Any reason my code should be slow?
Images are just smal icons in png

**Comment by EmmanVazz** [comment]
Are you loading other images with FF? If so make sure you set your priorities properly to prioritize local images before remote images.

**Comment by jorgenstorlie** [comment]
Are you loading other images with FF?
RE : Yes
 
If so make sure you set your priorities properly to prioritize local images before remote images.
RE:
How do I do this?

Added
.WithPriority(LoadingPriority.Highest)  
did not help

Placeholders from ApplicationBundle
  .LoadingPlaceholder(localPath, ImageSource.ApplicationBundle);
are displayed correct, but I want them and the images loaded from file.

**Comment by daniel-luberda** [comment]
@jorgenstorlie 

- Could you define "slow"? Are you loading the same image multiple times ar are these different images? 
- Do you use custom FFImageLoading configuration? 
- If placeholders images are not shown, do you specify it correctly? There should be some logs if there are errors. Could you provide it?

**Comment by jorgenstorlie** [comment]
I missed this:

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

seems to work now
