### ISSUE TITLE
Xamarin.Forms Shared Code - Cannot compile for iOS

### ISSUE THREAD

**Issue by ChrisWoodard** [luberda-molinet/FFImageLoading#565]
I'm probably just missing something really simple here but... I have a shared code Xamarin.Forms project in which I am attempting to use FFImageLoading CachedImage.  The Code compiles and runs fine for android, but when ever I try to do an iOS build I get the following error - 

Error		Failed to resolve assembly: 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

If I remove all references to FFImageLoad the iOS target compiles and runs fine.

Thanks in advance ;-)

**Comment by daniel-luberda** [comment]
It may be a lot of things, without some reproduction, I can't help you. It looks like you're somehow referencing Android specific dlls in iOS project and you shouldn't do that.
