### ISSUE TITLE
[Forms] - FadeAnimation does not work when bound to an ImageSource

### ISSUE THREAD

**Issue by SKLn-Rad** [luberda-molinet/FFImageLoading#566]
Given I create a CachedImage with a binding set to CachedImage.Source
When the ViewModel changes so that the Source is invalidated
Then I expect the FadeAnimation to be triggered

At the moment, the FadeAnimation occurs when the Source is first set. But when the ViewModel changes, it simply updates making it look a tad strange in typical use cases.

Simple solution would be to disable it, but that defeats the point of having it in the first point!

**Comment by daniel-luberda** [comment]
By default fade animation is disabled for bitmaps that are already cached in memory (that's what most of users expect). It's a configurable thing: 

```C#
var config = new FFImageLoading.Config.Configuration()
{
    FadeAnimationForCachedImages = true
};
ImageService.Instance.Initialize(config);
```
