### ISSUE TITLE
Is there a point in still having different resolution images?

### ISSUE THREAD

**Issue by hardcodet** [luberda-molinet/FFImageLoading#570]
I mostly avoided having a ton of differently scaled images (e.g. foo.png, foo@2x.png etc. on iOS) because I'm using icon fonts, but for the remaining ones: FFImageLoading seems to do a splendid job displaying images on the UI based on a single image file - thanks to the team for this! But then, I haven't tested this on many devices yet. Are there good reasons to still have differently scaled versions?

**Comment by daniel-luberda** [comment]
Hi @hardcodet,

For low-end devices initial image loading performance will be better when using smaller size image (less memory / cpu usage during downsample operation). This is noticeable especially on low-end Android devices.  

IMO the best you can do is to switch to SVG's (which FFImageLoading also supports).
