### ISSUE TITLE
( Possibly ) Deadlock when loading images

### ISSUE THREAD

**Issue by Auhmaan** [luberda-molinet/FFImageLoading#571]
I've been getting some users warning me about the app getting locked when they enter in a gallery-style page. I've managed to get the error in debug, and it seems a dead lock in the `RemovePendingTask` method.

This was the call stack when it happened:

	0xF in FFImageLoading.Work.WorkScheduler.RemovePendingTask at C:\projects\ffimageloading\source\FFImageLoading.Common\Work\WorkScheduler.cs:124,17	C#
 	0x7 in FFImageLoading.ImageService.RemovePendingTask at C:\projects\ffimageloading\source\FFImageLoading.Shared\ImageService.cs:270,13	C#
 	0x21 in FFImageLoading.Work.ImageLoaderTask<FFImageLoading.Drawables.SelfDisposingBitmapDrawable,FFImageLoading.Views.ImageViewAsync>.Cancel at C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:236,17	C#
 	0x11 in FFImageLoading.Work.ImageLoaderTask<FFImageLoading.Drawables.SelfDisposingBitmapDrawable,FFImageLoading.Views.ImageViewAsync>.CancelIfNeeded at C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:254,17	C#
 	0x42 in FFImageLoading.Concurrency.PendingTasksQueue.CancelWhenUsesSameNativeControl at C:\projects\ffimageloading\source\FFImageLoading.Common\Concurrency\PendingTasksQueue.cs:45,25	C#
 	0x6D in FFImageLoading.Work.WorkScheduler.QueueImageLoadingTask at C:\projects\ffimageloading\source\FFImageLoading.Common\Work\WorkScheduler.cs:202,17	C#
 	0x3C5 in FFImageLoading.Work.WorkScheduler.LoadImage at C:\projects\ffimageloading\source\FFImageLoading.Common\Work\WorkScheduler.cs:176,17	C#
 	0xAF in FFImageLoading.Work.WorkScheduler.<>c__DisplayClass44_0.<LoadImage<LoadImage>b__0>d at C:\projects\ffimageloading\source\FFImageLoading.Common\Work\WorkScheduler.cs:167,58	C#
 	0x5F8 in FFImageLoading.Work.ImageLoaderTask<FFImageLoading.Drawables.SelfDisposingBitmapDrawable,FFImageLoading.Views.ImageViewAsync>.TryLoadFromMemoryCacheAsync at C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:340,9	C#
 	0x164 in FFImageLoading.Work.ImageLoaderTask<FFImageLoading.Drawables.SelfDisposingBitmapDrawable,FFImageLoading.Views.ImageViewAsync>.TryLoadFromMemoryCacheAsync at C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:366,13	C#
 	0x1C9 in FFImageLoading.PlatformImageLoaderTask<FFImageLoading.Views.ImageViewAsync>.SetTargetAsync at C:\projects\ffimageloading\source\FFImageLoading.Droid\Work\PlatformImageLoadingTask.cs:70,13	C#

Unfortunately, the callstack didn't had any reference to my code, not sure about the origin of this error, if  it's from my side.

**Comment by daniel-luberda** [comment]
It should be fixed with the newest prerelease nuget. Could you check it?

**Comment by Auhmaan** [comment]
I'll check it.

**Comment by alanspires** [comment]
Been waiting on this fix for a while :) Working for me!!!! Thanks @daniel-luberda

**Comment by Auhmaan** [comment]
I can also say that so far I haven't had more problems with it. Seems to be resolved. Closing for now.
