### ISSUE TITLE
Is this code correct (SvgImageSource.cs, 97 and ImageSourceBinding.cs, 72) ?

### ISSUE THREAD

**Issue by 3-50** [luberda-molinet/FFImageLoading#573]
Hi!
Please, check this:
Recursion?
```
public static SvgImageSource FromResource(string resource, Type resolvingType, int vectorWidth = 0, int vectorHeight = 0, bool useDipUnits = true, Dictionary<string, string> replaceStringMap = null)
{
 return FromResource(resource, resolvingType.GetTypeInfo().Assembly, vectorWidth, vectorHeight, useDipUnits, replaceStringMap);
}
```
SvgImageSource.cs, 97

vectorSource.VectorWidth?
` if (vectorSource.VectorHeight == 0 && vectorSource.VectorHeight == 0)`
ImageSourceBinding.cs, 72

**Comment by daniel-luberda** [comment]
Yes, it's correct. It points to the different override:

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Forms.Shared/SvgImageSource.cs#L108
