### ISSUE TITLE
Memory size is greater than image sizes? how to free memory on navigating back?

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#574]
I am displaying 300+ items in a listview and each having image defined as below. Images are retrieved from aws s3 bucket. I profiled memory usage with xamarin profiler and I can see that the more I scroll in the list, memory usage increases which makes sense as each images are cached. But I am going above 300 mb cache. total size of all images physically are not more than 15 mb. 
1) How can it be cached 20 times more than actual size? If I use loading.png for loadingplaceholder, is it also cached for 300 times for each item in the list?

2) When i navigate back from the list, my memory size is not reduced. this is probably expected as some people may want to keep them in memory. Is there an option free the memory in build? a parameter or something? 

```
<ffimageloading:CachedImage  RetryCount="1"	
DownsampleToViewSize="true" 
 TransparencyEnabled = "false"  CacheDuration = "30" 
LoadingPlaceholder="loading_dark.png"    ErrorPlaceholder="error.png"   
Source="{Binding Image, Converter={StaticResource thumbnailConvertor}}"
  Aspect="AspectFit"    />
```

**Comment by 3-50** [comment]
1. In my program, approximately 10,000 images are displayed in ListView or FlowListView, after viewing 500pic - 207mb in the Xamarin profiler.
Are you reading
https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#usage-in-listview-with-listviewcachingstrategyrecycleelement-enabled
?
2. https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#clear-cache
Clears the cache for a specified entry (Memory, Disk, All). Could be an url or filename / file path. If removeSimilar is set to true then it also removes all image cache variants 
**Using an ImageSource** 
`CachedImage.InvalidateCache(ImageSource source, Cache.CacheType cacheType, bool removeSimilar = false)`

**Comment by EmilAlipiev** [comment]
@3-50 
1) after viewing 500pic - 207mb in the Xamarin profiler. that is still a lot isnt it unless your avg. size of your images are 500 kb. I am new in xamarin profiler as well. I check the image attached and there i see bytes and I assume those are images downloaded since  I dont have anything else as byte. Do you know if I can dig into it more specifically ? I just changed to cachetype as disk and performance is still good but when I am still getting high memory consumption. I guess even I use disk, it is sill putting into memory (XF behavior probably)

![snap1](https://cloud.githubusercontent.com/assets/10422347/25104719/b83accf4-23c1-11e7-92b7-a2330f538520.jpg)

**Comment by molinch** [comment]
Just for your info, images loaded into memory may take much more space than on disk (since they aren't compressed anymore). However if they are downscaled, they may take less memory than on disk, it really depends on what are your images and what you do with them.

**Comment by EmilAlipiev** [comment]
@molinch I can understand this but this is quite a lot. much much greater than original total size. you can see around 337 mb is huge.

**Comment by daniel-luberda** [comment]
@EmilAlipiev

You can control memory cache size by yourself :) Just use custom FFImageLoading config: 

```C#
var config = new FFImageLoading.Config.Configuration()
{
    MaxMemoryCacheSize = 9999999,
};
ImageService.Instance.Initialize(config);
```

**Comment by daniel-luberda** [comment]
As @molinch said:

`downloaded file size != bitmap size in memory`

1px = 4 Bytes (Android ARGB_8888)
 1024px x 1024px = 4 Megabytes 
2048px x 2048px = 16 Megabytes
