### ISSUE TITLE
local images and cachetype?

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#575]
Does it even make sense to use  CacheType= FFImageLoading.Cache.CacheType.All or it is better to use 
 CacheType= FFImageLoading.Cache.CacheType.Memory, unless resizing is considered? actually i read in another issue that resized image is not stored in disk unless explicitly defined. so what is the best performance tip for local images?

what happens using Cachetype memory with CacheDuration = TimeSpan.FromDays(30)?

**Comment by daniel-luberda** [comment]
Hi @EmilAlipiev!

- Currently, FFImageLoading disk cache stores only original files, not the resized ones. 
- For local images / embedded resources disk cache is simply not used and all disk cache parameters are ignored. So basically, you don't need to worry about anything.
