### ISSUE TITLE
Timeout value when loading from url

### ISSUE THREAD

**Issue by alicint** [luberda-molinet/FFImageLoading#576]
Hi
Thanks for good library :)

I was wondering whether it is possible to modify the timeout value for loading images from a url? I mean the time the library waits for a response before deciding that this url is broken or not.

and btw what is the default timeout value? :)

Thanks.
Ali

**Comment by AndreiMisiukevich** [comment]
Hi, @alicint 


`var config = new FFImageLoading.Config.Configuration()
			{
				HttpHeadersTimeout = 10, // Default value (seconds)
                                HttpReadTimeout = 30 // Default value
			};
			ImageService.Instance.Initialize(config);`


You can set timeout's values in your project. Something like that (Vide supra)

I hope, it's that you need.

**Comment by alicint** [comment]
yeah that is what I needed exactly, thanks 👍

**Comment by daniel-luberda** [comment]
Thanks @AndreiMisiukevich 👍
