### ISSUE TITLE
Add an ability to Upscale when using .DownSample/DownSampleInDip

### ISSUE THREAD

**Issue by Shaddix** [luberda-molinet/FFImageLoading#577]
It'd be good to have an ability to upscale (at least optional).

I could implement it myself and create a Pull request if agreed on the API.

I see it as either
- AllowUpscale(bool) method (along with AllowUpscaleState get-only property) on TaskParameter
- Adding an optional bool parameter to .DownSample(int width = 0, int height = 0, bool allowUpscale = false) and to .DownSampleInDip.

What are your thoughts? Will you accept such a PR?

**Comment by daniel-luberda** [comment]
Hi @Shaddix, 

That might be useful for some cases, but it should be disabled by default to save memory. If you'll implement it, I could merge that PR :)

My suggestions: 

- Adding an optional bool parameter to .DownSample(int width = 0, int height = 0, bool allowUpscale = false) and to .DownSampleInDip.
- Adding a global configuration option `AllowUpscale`: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Config/Configuration.cs

**Comment by Shaddix** [comment]
Implemented, testing and pull-request will follow.

The only changed to discussed interface is that allowUpscale is nullable in DownSample/DownSampleInDip:
` .DownSample(int width = 0, int height = 0, bool? allowUpscale = null)`

In case of allowUpscale == null the value is taken from the Configuration, where AllowUpscale is false by default (that fact is also reflected in xml-comment for the parameter).
Hope that's ok for you.

https://github.com/Shaddix/FFImageLoading

**Comment by daniel-luberda** [comment]
Thanks to @Shaddix we have now upscale. Thanks one more time! :)
