### ISSUE TITLE
Unable to load svg images in Forms project

### ISSUE THREAD

**Issue by Piteryo** [luberda-molinet/FFImageLoading#579]
Want to use svgCachedImage and get Xamarin.Forms.Xaml.XamlParseException: Position 17:10. Type ffimageloadingsvg:SvgCachedImage not found in xmlns clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms
Have the latest pre version from nuget installed, intellisense sees SvgCachedImage

**Comment by Piteryo** [comment]
Saw that this function works only when you use Xamvvm. Am i able not to use this plugin?

**Comment by RaFaGG** [comment]
I use without Xamvvm. Only add from nuget Xamarin.FFImageLoading.Svg.Forms and then in xaml add xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms" . see the example https://github.com/luberda-molinet/FFImageLoading/tree/master/samples

**Comment by Piteryo** [comment]
@RaFaGG I tried to launch an example and even there - if i delete "IBasePage<...>" from SvgSamplePage.xaml.cs i get an exception

**Comment by RaFaGG** [comment]
Because the example uses Xamvvm but it is not necessary. Try something like this `<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
             x:Class="Example.Example1">
    <ContentPage.Content>
        <StackLayout>            
                <ffimageloadingsvg:SvgCachedImage WidthRequest="100" HeightRequest="100"  Source="image.svg">
                </ffimageloadingsvg:SvgCachedImage>                
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
`

**Comment by Piteryo** [comment]
@RaFaGG tried exactly the same. Maybe i have problems because i use Unity..

**Comment by RaFaGG** [comment]
Can be. I do not use unity so I can not help you but it looks like a dependency problem

**Comment by Piteryo** [comment]
In empty project without unity the issue is still present

**Comment by lhughey** [comment]
I'm also having a problem using an SVG.  I'm using a PRISM forms project which does contain Unity.  The code works with a CachedImage

**Comment by daniel-luberda** [comment]
@Piteryo @lhughey 

Are you sure you're using correct namespace? (`xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"`) as here: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/SvgSamplePage.xaml#L19

**Comment by Piteryo** [comment]
@daniel-luberda Yes, exactly the same. Even in sample project if I don't use xamvvm (delete inheritance from IBasePage) I get an exception

**Comment by daniel-luberda** [comment]
It definitely has nothing to do with `Xamvvm` as it's only an MVVM framework. Could you share a sample solution?

**Comment by michelmoorlag** [comment]
I have exactly the same issue using latest Xamarin Forms with freshmvvm and Xamarin.FFImageLoading.Svg.Forms version 2.2.9: 
Type ffimageloadingsvg:SvgCachedImage not found in xmlns clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms

**Comment by michelmoorlag** [comment]
I added a really basic XF project to demonstrate the issue. When I try to build this in VS2015 I get the above error.
[SvgTest.zip](https://github.com/luberda-molinet/FFImageLoading/files/972991/SvgTest.zip)

**Comment by willowvil** [comment]
Hi,

Same problem here. 

```
using FFImageLoading.Svg.Forms;
SvgCachedImage shipImage = new SvgCachedImage();
```
Error: SvgCachedImage could not be found.

NuGet:

- Xamarin.FFImageLoading 2.2.9
- Xamarin.FFImageLoading.Forms 2.2.9
- Xamarin.FFImageLoading.Svg 2.2.9
- Xamarin.FFImageLoading.Svg.Form 2.2.9

Thanks!

**Comment by daniel-luberda** [comment]
Please try the newest prerelease as it only has `SvgCachedImage` and be sure you updated packages in *every* project.

**Comment by daniel-luberda** [comment]
@michelmoorlag I reviewed your project and you also use stable packages, as I mentioned, you must use 2.2.10 package. :)

**Comment by michelmoorlag** [comment]
Build succeeded :)
Thank you Daniel!

**Comment by HugoTruffe** [comment]
Hi

I have "version 2.2.10-pre-391"

My Content

```
xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
xmlns:fftransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
		xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
```

and the problem is not solution

**"Position 81:10. Type ffimageloadingsvg:SvgCachedImage not found in xmlns clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"**

**Comment by daniel-luberda** [comment]
@HugoTruffe It's fixed in the latest prerelease nuget.

**Comment by sthewissen** [comment]
I'm still getting this in pre-413 :(
