### ISSUE TITLE
Exception in MeasureOverride on UWP

### ISSUE THREAD

**Issue by ozzy1873** [luberda-molinet/FFImageLoading#580]
I am getting an error occasionally on UWP with the latest version of XF. I have not found steps to reproduce it, but I thought I would throw it out there in case you might know what's up:

App_UnhandledException System.Exception: Unspecified error (Excep_FromHResult 0x80004005)Xamarin.Forms.Platform.UWP.VisualElementRenderer<FFImageLoading.Forms.CachedImage,Windows.UI.Xaml.Controls.Image>.MeasureOverride(Foundation.Size availableSize)
   at Xamarin.Forms.TriggerAction.DoInvoke(Object sender)

**Comment by daniel-luberda** [comment]
Thanks for the info. 

I currently don't have much time to debug `UWP` issues. Any help appreciated. I'll get back to this soon.

**Comment by daniel-luberda** [comment]
Could you check FFImageLoading 2.2.14? Does it fix your issues?

**Comment by ozzy1873** [comment]
So far, I no longer see that issue. Thank you!

Sent from Mail for Windows 10

**Comment by daniel-luberda** [comment]
I'll close this one then. Cheers :)
