### ISSUE TITLE
Rounded Corners With Aspect as 'Fill' Compresses Loading image

### ISSUE THREAD

**Issue by kkodan** [luberda-molinet/FFImageLoading#583]
Hi,

I have a listview with ffimageloading image plugin. My requirement is image should be rounded corner while the image shape is rectangular. While the loading image is visible, it is getting compressed when Aspect is 'Fill'. When Aspect is 'AspectFill', the image wont get shrinked. But, the image wont appear with rounded rectangle.
When the image is 'Fill'
<img width="326" alt="screen shot 2017-04-21 at 12 41 51 pm" src="https://cloud.githubusercontent.com/assets/26926951/25266861/5f2959d8-2690-11e7-8509-494453b796a3.png">

When the image is 'AspectFill'
<img width="324" alt="screen shot 2017-04-21 at 12 44 38 pm" src="https://cloud.githubusercontent.com/assets/26926951/25266877/68a28aca-2690-11e7-8d3a-745b24796ebe.png">

Here is my code
<ffimageloading:CachedImage x:Name="NewsImage"   LoadingPlaceholder="default_image2.png"  Grid.Row="1" Grid.RowSpan="7" Grid.Column="1"       Aspect="AspectFill" HorizontalOptions="Fill" VerticalOptions="Fill" MinimumHeightRequest="120" WidthRequest="120" >
<ffimageloading:CachedImage.Transformations >               					 <fftransformations:RoundedTransformation BorderSize="10" BorderHexColor="#C6C8CA"   Radius="60"/>            				
</ffimageloading:CachedImage.Transformations>			
</ffimageloading:CachedImage>

**Comment by sander1095** [comment]
I am sorry for being off topic, but could you share your transformation code with me? I need it myself and I'd love to take a look at yours.

Try using DownsizeToView to fix your problem? I am new to this plugin so I can't be of much help.

**Comment by daniel-luberda** [comment]
`RoundedTransformation` has an additional `CropWidthRatio` and 'CropHeightRatio` parameters used for such purposes (eg `CropWidthRatio=2; CropHeightRatio=1;`). https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations/RoundedTransformation.cs#L29-L30
