### ISSUE TITLE
Porting to NetStandard

### ISSUE THREAD

**Issue by Ingenator** [luberda-molinet/FFImageLoading#584]
Hey guys,

Will FFImageLoading be ported to NetStandard?

**Comment by daniel-luberda** [comment]
Hi @Ingenator, 

Yes, FFImageLoading uses PCL `Profile259`, so it's compatible with .NET Standard >=1.0

**Comment by daniel-luberda** [comment]
The question is if we should migrate to .NET standard or support both for some time.

**Comment by Ingenator** [comment]
I mean if you will support both.

**Comment by daniel-luberda** [comment]
It's implemented. Both PCL & .NET standard are now supported. Cheers :)
