### ISSUE TITLE
Save Images with Transformations

### ISSUE THREAD

**Issue by senenrr** [luberda-molinet/FFImageLoading#585]
Hello, 

How can I save an image after it has been transformed? I've been using your library and Plugin.Media but the uploaded image is the original image without any transformation.

   FotoFF.Transformations.Add(new RotateTransformation(90));
            FotoFF.Transformations.Add(new CircleTransformation());
            FotoFF.ReloadImage();

            byte[] si = await FotoFF.GetImageAsJpgAsync();
            MemoryStream streamcon = new MemoryStream(si);
            
            var content = new MultipartFormDataContent();

            content.Add(new StreamContent(streamcon), "FotoEjem", "FotoEjem");              
            
            var httpClient = new HttpClient();
            var uploadServiceBaseAddress = "http://www.mydominio.com/Lib/api/Uploads";
            var httpResponseMessage = await httpClient.PostAsync(uploadServiceBaseAddress, content);

Thanks.

**Comment by salvador-guerrero** [comment]
Here's a similar issue to yours

https://github.com/luberda-molinet/FFImageLoading/issues/260

**Comment by senenrr** [comment]
Thanks @salvador-guerrero

**Comment by daniel-luberda** [comment]
There's a new API for such purposes: 
```C#
var stream = ImageService.Instance.LoadUrl("http://example.org/test.png")
 .DownSampleInDIP(width: 200)
 .Transform(new CircleTransformation())
 .AsPNGStreamAsync(); // or AsJPGStreamAsync
```

Then just save content of a stream to the disk :)
