### ISSUE TITLE
How to AspectFit Image in ListView?

### ISSUE THREAD

**Issue by Vaylandt** [luberda-molinet/FFImageLoading#586]
How to fill all wight?
However, I do not know in advance neither the picture size nor the size of the screen.

![image](https://cloud.githubusercontent.com/assets/13034274/25368500/9ad9d79e-2985-11e7-9437-fce8f85d05ff.png)

![image](https://cloud.githubusercontent.com/assets/13034274/25368431/11d1b5b6-2985-11e7-834f-cce58654c587.png)

**Comment by AndreiMisiukevich** [comment]
Hi @Vaylandt 
You can try to put your image into AbsoluteLayout with Flags *WidthProportional* and Bounds (0,0,1,-1) (as WorkAround).

**Comment by daniel-luberda** [comment]
Thanks @AndreiMisiukevich for a potential solution. 

@Vaylandt Did you solve it?
