### ISSUE TITLE
Forms/UWP: Local image file not being loaded

### ISSUE THREAD

**Issue by Contract16** [luberda-molinet/FFImageLoading#587]
**Summary**
After saving an image to a local internal folder, then trying to display the image, the image is not displayed and no errors are thrown.

**Repro steps**
1) Save an image in UWP using native libraries at 
```
ApplicationData.Current.Localfolder.CreateFolderAsync("my\\folder\\path");
var file = await dir.CreateFileAsync("myImage.jpg", CreationCollisionOption.ReplaceExisting);
```
2) Pass the file path as an `ImageSource` for a `CachedImage`
3) Image will not be displayed

**Other comments**
If the `CachedImage` is swapped out for a normal `Image` in xaml, the saved image file will load correctly. Also if `path.Replace("\\", "/")` is used, and vice-versa, then the image still isn't loaded (so this isn't related to file path formatting).

This happens for UWP Desktop or Win10 phone, using ffimageloading forms libraries

**Comment by daniel-luberda** [comment]
Any image loading error is reported to the console output. Could you paste it? Also you can use custom logger as here: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Droid/MainActivity.cs#L28-L58

**Comment by Contract16** [comment]
@daniel-luberda Sorry for the massive delay on this, hadn't had time to try and get a repro project up and running until now...

https://github.com/Contract16/FFImagError-UWP

I think it's something to do with transformations on UWP, if I add a transformation, the image won't load in. This is on images in a xaml file in the forms project or inside another library referenced. If you remove the transformation, image loads in fine.

If there's maybe something wrong with my setup for UWP that I've missed then that would explain it, but I can't see anything missing?

I think the main error I was having above was to do with incorrect file location formatting, and that there was actually 2 issues that manifested in the same way.

Thanks

**Comment by Contract16** [comment]
@daniel-luberda Just a quick note, the logs don't show any errors occurring.
