### ISSUE TITLE
Size image after RotateTransformation

### ISSUE THREAD

**Issue by senenrr** [luberda-molinet/FFImageLoading#589]
Hello,

What is the correct configuration after a rotatetransformation? My cachedimage isn't show complete when   degrees = 90 or 270, Only is complete with Degrees = 0 or 180.

I set  DownsampleToViewSize="True"  

Thanks. 
![photo4906923161732360110](https://cloud.githubusercontent.com/assets/16245801/25539243/e2581b02-2c0b-11e7-8b67-926d386eea9f.jpg)

![image](https://cloud.githubusercontent.com/assets/16245801/25539269/06debf3a-2c0c-11e7-8527-576ea0d98daf.png)

![image](https://cloud.githubusercontent.com/assets/16245801/25539288/25c1307c-2c0c-11e7-8286-6ec7f4fd1981.png)

![image](https://cloud.githubusercontent.com/assets/16245801/25539292/2bfbb372-2c0c-11e7-908a-260efe9f34d6.png)

**Comment by daniel-luberda** [comment]
What you probably want is to set transformation's `Resize` parameter to `true`.

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations/RotateTransformation.cs#L30

**Comment by senenrr** [comment]
But  when I put Resize parameter to true the image is crop. What can I do?

**Comment by daniel-luberda** [comment]
What do you want to achieve? Maybe it's easier for you to set `Rotation` property of a view instead using transformations?

**Comment by senenrr** [comment]
I want to save an image after transformations, but when I tried it the image is crop, isn't the original complete with the rotation.

This is my code:

   streammod = await ImageService.Instance.LoadUrl("http://myhosting.mx/Libretas/Uploads/DFK4A4NR.jpg")
                                          .DownSampleInDip(width: 200)
                                          .Transform(new RotateTransformation(grados,false,true))
                                          .AsJPGStreamAsync();

**Comment by mjoehl** [comment]
Hi @daniel-luberda 
I have the same with rotation as described above. I want to rotate the image with a transformation and save the new image. But the image is cropped after the rotation (exactly the same way as the images above).

How can I handle this?
