### ISSUE TITLE
Question: CachedImage.GetImageAsJpgAsync(quality)

### ISSUE THREAD

**Issue by dbolak** [luberda-molinet/FFImageLoading#591]
Calls to GetImageAsJphAsync() with quality (integer) from with every value from 90 to 50 all return similar sized byte arrays. Is this a bug or am I doing something totally wrong ? Running on Xamarin.Forms v 2.3.4.231 and Xamarin.FFImageLoading v2.2.9; basically I am looping to reduce the size of the loaded jpg by adjusting its quality so that I can save it somewhere else where there is a limitation on the size of the jpg (in terms of bytes).

**Comment by daniel-luberda** [comment]
What platform? iOS? Android?

Here are the methods responsible for getting jpg/png: 

- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms.Droid/CachedImageRenderer.cs#L360-L404
- https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms.Touch/CachedImageRenderer.cs#L345-L376

**Comment by dbolak** [comment]
UWP. If you want I can check iOS.

**Comment by daniel-luberda** [comment]
The problem is here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms.WinRT/CachedImageRenderer.cs#L494

That code part doesn't use `quality` parameter at all. We'll need to implement it. I can't implement it on Windows currently as I'm quite busy. Any help appreciated.

**Comment by dbolak** [comment]
Thanks for the update Daniel. Currently, I have bypassed this by modifying the size of the image by changing its width incrementally. I will take a stab at it when I have some spare time.
