### ISSUE TITLE
ImageViewAsync keeping / losing tint color with images saved on resources

### ISSUE THREAD

**Issue by Auhmaan** [luberda-molinet/FFImageLoading#592]
The `ImageViewAsync` keeps / loses it's _tint_ color when used with resources.

What's happening to me is the following:

- Navigate to a `Fragment` where I set a _tint_ to a couple of images via `<ImageViewAsync>.SetColorFilter( <Android.Graphics.Color> );`
- Navigate to another `Fragment` where I need to reset the _tint_ via `<ImageViewAsync>.ClearColorFilter();` due to the tint being preserved
- Navigate back to the initial `Fragment` where I have now the images without the _tint_.

Is there any workaround to this problem? When navigating back, there isn't any piece of code being called to change the _tint_ again.

**Comment by daniel-luberda** [comment]
@Auhmaan Possible solutions: 

- Use different cache keys for each tint state (enabled / disabled)
- Instead using color filter, use `TintTransformation` (probably with `EnableSolidColor` set to `true`
