### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by ericruelas** [luberda-molinet/FFImageLoading#594]
I have tried to run your xaml code to render an svg but no progress has been made. It doesn't even show an error. I'm trying to do this only through XAML and i don't see the Converter ever being used when i was trying to debug this.

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             xmlns:imgcircle="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions"
             xmlns:ihloc="clr-namespace:InteractiveHealth.Mobile.Member.Services;assembly=InteractiveHealth.Mobile.Member"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
	      	 xmlns:fftransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
             xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"             
             prism:ViewModelLocator.AutowireViewModel="True"
             x:Class="InteractiveHealth.Mobile.Member.Views.TestPage"
             Title="Test Page">
		<ContentPage.Content>			
				<ffimageloadingsvg:SvgCachedImage WidthRequest="200" HeightRequest="200" Source="IH.m.m.Images.Elvis.svg"/>	
				</ContentPage.Content>
</ContentPage>

**Comment by daniel-luberda** [comment]
There was a bug in the previous prerelease package, please use the latest one :) Sorry.
