### ISSUE TITLE
Error SvgCachedImage could not be found

### ISSUE THREAD

**Issue by willowvil** [luberda-molinet/FFImageLoading#595]
Hi

I´m getting error:

```
using FFImageLoading.Svg.Forms;
SvgCachedImage myImage = new SvgCachedImage();
```
Error: SvgCachedImage could not be found.

NuGet:

Xamarin.FFImageLoading 2.2.9
Xamarin.FFImageLoading.Forms 2.2.9
Xamarin.FFImageLoading.Svg 2.2.9
Xamarin.FFImageLoading.Svg.Form 2.2.9
Thanks!

**Comment by daniel-luberda** [comment]
It was introduced in 2.2.10. Please use the latest prerelease package. Thanks.
