### ISSUE TITLE
SVG Image loading failed from Uri and Resource

### ISSUE THREAD

**Issue by PCDK** [luberda-molinet/FFImageLoading#596]
When I run the following code either in my own program or in your sample I get a `NullReferenceException`:
`Svg.Forms.SvgImageSource.FromUri(new Uri("https://en.wikipedia.org/wiki/Scalable_Vector_Graphics#/media/File:SVG_logo.svg"));`
It seems to be because `image` is _null_ in the line `using (var image = SKImage.FromBitmap(bitmap))` in the file 
`FFImageLoading-master\source\FFImageLoading.Svg.Shared\SvgDataResolver.cs` on line 149.

Also when I try to load SVG images in my PCL forms project nothing appears. With normal images I can load them if they are a EmbeddedResource. Like [this](https://developer.xamarin.com/guides/xamarin-forms/user-interface/images/#Embedded_Images):
`ImageSource.FromResource("ProjectName.Images.Sample.svg");`
But when I set this as the source for the `SvgCachedImage` nothing happens.

Love your work btw. :)

**Comment by daniel-luberda** [comment]
Thanks!  

Did you update `SkiaSharp` to the newest version? There's a bug here: https://github.com/mono/SkiaSharp/issues/285

If you update to the newest prerelease nuget it should work fine.

**Comment by PCDK** [comment]
I just tried with the newest version of `SkiaSharp` version 1.57.1. I still get the same `NullReferenceException` when loading from Uri.

So how do I use the `SvgCachedImage`? Should the following work?
`var img = new SvgCachedImage()`
`img.Source = ImageSource.FromResource("ProjectName.Images.Sample.svg");`

I use 2.2.10-pre-375

**Comment by daniel-luberda** [comment]
- Are you sure you have the same package versions in all projects?
- `https://en.wikipedia.org/wiki/Scalable_Vector_Graphics#/media/File:SVG_logo.svg` - is it happening only on this url? Did you try others or a local resource file?

> So how do I use the SvgCachedImage? Should the following work?
Yes.

**Comment by PCDK** [comment]
I have tried different other .svg urls as well. The code `SvgDataResolver.cs` and ` SKImage.FromBitmap(bitmap)` gives a null value no matter what. It doesn't matter which version of `SkiaSharp` I use.

**Comment by daniel-luberda** [comment]
Your url is incorrect (not a direct one). It should be: `https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg`

Could you make a reproduction? Works fine for me: 

```XML
<ffimageloadingsvg:SvgCachedImage WidthRequest="200" HeightRequest="200" Source="https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg"/>
```

![simulator screen shot 8 may 2017 20 19 53](https://cloud.githubusercontent.com/assets/13569983/25818725/e4367fd6-342b-11e7-99eb-6bd827acfdb0.png)

**Comment by PCDK** [comment]
Ahh that is my bad, sorry. I stopped trying with different urls when I began trying different version of `SkiaSharp` It also works for me now. Thank you very much.

**Comment by daniel-luberda** [comment]
No problem. Cheers!

**Comment by urvashint** [comment]
@daniel-luberda I'm trying to load this URL "https://sapphire-selector-api-d.hiltisw.com/api/v1/specification/file/Z-19_53-2192_CFS-C-EL_FW_PP_013.svg" but it gives System.FormatException: Input string was not in a correct format.
It works with other SVG URLS.Can you tell me what is wrong here?
