### ISSUE TITLE
Using indeterminate progress bar as loading place holder

### ISSUE THREAD

**Issue by HEBOS** [luberda-molinet/FFImageLoading#600]
Hi,

I'm using MvxCachedImageView and during initialization I set "LoadingPlaceholderImagePath" to indeterminate progress bar, but it does not work.
If I set it to regulare (image) resource it is working.
How to achieve progress bar effect?

This is misbehaving code:
LoadingPlaceholderImagePath = "res:style_circular_indeterminate";

Thanks

**Comment by daniel-luberda** [comment]
Hi @HEBOS,

FFImageLoading only supports images, it won't work with views. What you want is to create a `FrameLayout` with two children: the `MvxCachedImageView` and an indeterminate ProgressBar . 

- `MvxCachedImageView` has a `IsLoading` property which you could bind to. 
- You can simply bind progress bar visibility to its value.
