### ISSUE TITLE
Suggestion Required: Stream an image every 3 sec

### ISSUE THREAD

**Issue by Raj123456788** [luberda-molinet/FFImageLoading#602]
Hello There,
                   I have a requirement to stream an image(https://test/screen.jpg). If I use image controller or webview it still flickers. Can you please guide me how can I this library to acheive my aim for crossplatform. 
Thank you in advance.

**Comment by molinch** [comment]
So what you want is to retrieve an image from a server every 3 seconds, and then display that image.
Is it correct?

**Comment by Raj123456788** [comment]
Yes

**Comment by Raj123456788** [comment]
Is there any sample I can use in FFImageLoading.sln?

**Comment by molinch** [comment]
So if you target Xamarin.Forms then you should use the Cached.Image ([see wiki ](https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#xaml)) and change the Source property every 3 seconds. For example:
```c#
object.Source = null;
object.Source = url;
```

This will force a rebinding, and refresh the image.
You will need to provide a CacheDuration, in your XAML, of less than 3 seconds too:
```c#
CacheDuration = TimeSpan.FromSeconds(2)
```

**Comment by Raj123456788** [comment]
Thank you for the suggestion . I am trying it now. Changing object.source=null will lead to flickering?
https://github.com/xamarin/Xamarin.Forms/blob/74cb5c4a97dcb123eb471f6b1dffa1267d0305aa/Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs#L104

Courtesy:
https://forums.xamarin.com/discussion/58100/how-to-stop-flicker-when-change-image-source-to-use-a-new-image-with-the-same-size-as-the-old-one

I will update you soon.

**Comment by daniel-luberda** [comment]
What you can do to improve refresh rate is to disable calculation of stream crc checksum in a ffimageloading custom config,  that will improve performance a lot. You don't need to set image source to null currently :)

**Comment by daniel-luberda** [comment]
Do you use stream image source at all? Or url image source?

**Comment by Raj123456788** [comment]
I use url image source.

**Comment by Raj123456788** [comment]
Hi, I wrote a timer in ListHeavyPage.cs but  await this.PushPageFromCacheAsync<ListHeavyPageModel>(pm => pm.Reload())  does not update my image?  
Device.BeginInvokeOnMainThread(async () =>
                    {
                        Debug.WriteLine("Inside ScheduleWebRequest");

                        // Update the UI & repeat by scheduling a new request
           
                    });

Also, I do see the flickering!

**Comment by molinch** [comment]
@Raj123456788 could you provide a sample of what you are trying to do?

**Comment by Raj123456788** [comment]
sure. Please find attached .txt.  Stream URLimage without flickering is my aim.
[Stream_Image.txt](https://github.com/luberda-molinet/FFImageLoading/files/1002128/Stream_Image.txt)

**Comment by Raj123456788** [comment]
Any Update?

**Comment by Raj123456788** [comment]
Guys, does it matter with Xamarin version I am using? Waiting for your reply!

**Comment by Raj123456788** [comment]
Below Link would give details of what I am trying to achieve
https://forums.xamarin.com/discussion/58100/how-to-stop-flicker-when-change-image-source-to-use-a-new-image-with-the-same-size-as-the-old-one

**Comment by daniel-luberda** [comment]
- In the newest versions, you don't need to set `Source` to `null` before assigning new image. 
- You probably want to disable `FadeAnimationEnabled` option
- You don't need to set `Source` property on UI Thread, FFImageLoading takes care of those things
- You should disable disk cache (set `CacheType` to `Memory` only)

That should be enough.

**Comment by Raj123456788** [comment]
Daniel, clear cache does not work. I followed above steps but still does not update the image. I saw https://github.com/luberda-molinet/FFImageLoading/issues/624 issue. But it is stream my case it is URi

**Comment by daniel-luberda** [comment]
Try the newest prerelease. It should be fixed.

**Comment by Raj123456788** [comment]
what version 2.2.10-pre-408? I tried that.
