### ISSUE TITLE
How can I add a CachedImage to the background of a content page ?

### ISSUE THREAD

**Issue by kgbuddhima** [luberda-molinet/FFImageLoading#603]
I'm using BackgroundImage property to set a image to the background of my content page.
And I'm using cached images inside of the content page. 
Now I want to add a cached image to the background too. So how can I do it ?

This is the XAML in my content page heaader...

`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MdiChat.View.LoginPage"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             Title="LoginPage" BackgroundImage="CoverC.jpg"
             >`

**Comment by AndreiMisiukevich** [comment]
Hello @kgbuddhima 
I think, it's very strange idea.
Are you sure you need it? :)

CachedImage is View, but BackgroundImage property of Page is ImageSource.
You aren't able to set CachedImage into this property.

But you are able to add AbsoluteLayout as ParentView of your page, then add CachedImage as first child with Bounds (0,0,1,1) and flags All. So, you can get result by this way.

But I want to repeat -> it's very strange idea)

**Comment by kgbuddhima** [comment]
Hello Andrei,

Thank you very much for your solution !
And I'll try like this. 

Thank you again !

**Comment by daniel-luberda** [comment]
@AndreiMisiukevich  Thanks for a proposed solution. @kgbuddhima You can also use `Grid`/ `StackLayout` for that.
