### ISSUE TITLE
ListView scroll resets scroll position of child items (CachedImage inside horizontal scrollview) 

### ISSUE THREAD

**Issue by mofadevs** [luberda-molinet/FFImageLoading#607]
Good Day
First of all, great library, can't live without it. Here is the issue. 
Am using Xamarin.Forms. I have a ListView. Every item in ListView is a horizontal scroll view. Every item in the scroll view displays FFImageLoading.CachedImage with couple of labels with very short text. If the ListView is scrolled up or down, the last scroll position of certain ListView items (which is a horizontal scrollview) is reset. The source of the CachedImage is base64string coming from web api. 

Here is the catch, if I do not display CachedImage and only display labels, everything works fine. 

Following is the sample XAML I am using:
<ffimageloading:CachedImage Source="{Binding Base64Logo}" HeightRequest="70" WidthRequest="70" HorizontalOptions="Center"/>

Version Information:
Xamarin Froms: 2.0.0.6482
FFImageLoading Library: 2.2.5

**Comment by daniel-luberda** [comment]
@mofadevs Thanks, I'll need some details first:

- What platform?
- Did you try to update to the latest prerelease nuget?

> the last scroll position of certain ListView items (which is a horizontal scrollview) is reset

Could you write more info?
