### ISSUE TITLE
SvgCahedImage missing in FFImageLoading.Svg.Forms

### ISSUE THREAD

**Issue by fmeneuhe** [luberda-molinet/FFImageLoading#608]
Hi,
I just installed Xamarin.FFImageLoading.Svg.Forms v2.2.9 from nuget (in VS 2017).
I get this error when building:
"ffimageloadingsvg:SvgCachedImage not found in xmlns clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"

Browsing "FFImageLoading.Svg.Forms" from Object Browser I saw "SvgCachedImage" is missing (see screenshot).

![svgmissing](https://cloud.githubusercontent.com/assets/8604933/26217795/f4217dbc-3c08-11e7-9836-1a0926301978.png)

What I am doing wrong?

**Comment by phamthanhtong** [comment]
me too!

**Comment by quakeulf** [comment]
I have this issue too. Is there a workaround?

**Comment by RaFaGG** [comment]
For use ffimageloadingsvg:SvgCachedImage update to 2.2.10-pre-391 in nuget (prerelease)

**Comment by quakeulf** [comment]
@RaFaGG Sorry, but I cannot find it.

**Comment by quakeulf** [comment]
Sorry, I'm getting this now: 

Unhandled Exception:

FreshTinyIoC.TinyIoCResolutionException: Resolve failed: SettingsPage - Reason: Could not resolve type with token 0100004f (from typeref, class/assembly FFImageLoading.Svg.Forms.SvgCachedImage, FFImageLoading.Svg.Forms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)

**Comment by daniel-luberda** [comment]
@quakeulf  You need to update nuget packages to the same version in all projects (it's important).

**Comment by daniel-luberda** [comment]
Also see this: https://github.com/luberda-molinet/FFImageLoading/issues/604#issuecomment-306330945

It should be fixed in the new prerelease that I'm gonna push.

**Comment by quakeulf** [comment]
Ok, it works now, thanks for fixing!

However now the SVGs aren't showing up, but I suspect something else is the problem, lol.
