### ISSUE TITLE
SVG not displaying

### ISSUE THREAD

**Issue by dpineda** [luberda-molinet/FFImageLoading#610]
I'm trying to display this svg in xamarin forms without success
<ffimageloadingsvg:SvgCachedImage WidthRequest="200" HeightRequest="200" Source="calendar.svg"/>	
here's the file

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="52px" height="51px" viewBox="0 0 52 51" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>Group 2</title>
    <desc>Created with Sketch.</desc>
    <defs>
        <rect id="path-1" x="6.66666667" y="23.6111111" width="8.06025835" height="8.06025835"></rect>
        <rect id="path-2" x="6.66666667" y="35.2537065" width="8.06025835" height="8.06025835"></rect>
        <rect id="path-3" x="20.9960148" y="23.6111111" width="8.06025835" height="8.06025835"></rect>
        <rect id="path-4" x="20.9960148" y="35.2537065" width="8.06025835" height="8.06025835"></rect>
        <rect id="path-5" x="35.325363" y="23.6111111" width="8.06025835" height="8.06025835"></rect>
        <rect id="path-6" x="35.325363" y="35.2537065" width="8.06025835" height="8.06025835"></rect>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="1-Get-Started" transform="translate(-1019.000000, -642.000000)">
            <g id="Group-2" transform="translate(1020.000000, 643.000000)">
                <g id="Calendar">
                    <rect id="Rectangle-path" fill="#283541" fill-rule="nonzero" x="20" y="19" width="1.74221472" height="1.7460404"></rect>
                    <rect id="Rectangle-path" fill="#283541" fill-rule="nonzero" x="24.3692945" y="19" width="1.74221472" height="1.7460404"></rect>
                    <rect id="Rectangle-path" fill="#283541" fill-rule="nonzero" x="28.7295583" y="19" width="1.74221472" height="1.7460404"></rect>
                    <g>
                        <path d="M0,10.3888889 L0,14.1666667 L50.0555556,14.1666667 L50.0555556,10.3888889 L50.0555556,5.66666667 L41.5555556,5.66666667 L41.5555556,9.44444444 L36.8333333,9.44444444 L36.8333333,5.66666667 L13.2222222,5.66666667 L13.2222222,9.44444444 L8.5,9.44444444 L8.5,5.66666667 L0,5.66666667 L0,10.3888889 Z" id="Combined-Shape" fill="#68CD96"></path>
                        <g id="Page-1" stroke="#283541">
                            <path d="M50.0933333,15.1111111 L0,15.1111111" id="Stroke-1" stroke-width="2"></path>
                            <polyline id="Stroke-3" stroke-width="2" points="7.514 7.55555556 7.514 10.0740741 13.7756667 10.0740741 13.7756667 7.55555556"></polyline>
                            <polyline id="Stroke-4" stroke-width="2" points="36.3176667 7.55555556 36.3176667 10.0740741 42.5793333 10.0740741 42.5793333 7.55555556"></polyline>
                            <g id="Group-27" stroke-width="1.7">
                                <path d="M7.514,5.03703704 L2.50466667,5.03703704 C1.12083833,5.03703704 0,6.16407407 0,7.55555556 L0,46.5925926 C0,47.9840741 1.12083833,49.1111111 2.50466667,49.1111111 L47.5886667,49.1111111 C48.972495,49.1111111 50.0933333,47.9840741 50.0933333,46.5925926 L50.0933333,7.55555556 C50.0933333,6.16407407 48.972495,5.03703704 47.5886667,5.03703704 L42.5793333,5.03703704 L42.5793333,1.25925926 C42.5793333,0.564148148 42.018288,0 41.327,0 L37.57,0 C36.878712,0 36.3176667,0.564148148 36.3176667,1.25925926 L36.3176667,5.03703704 L13.7756667,5.03703704 L13.7756667,1.25925926 C13.7756667,0.564148148 13.2146213,0 12.5233333,0 L8.76633333,0 C8.07504533,0 7.514,0.564148148 7.514,1.25925926 L7.514,5.03703704 Z" id="Stroke-5"></path>
                            </g>
                        </g>
                        <g id="Rectangle-4">
                            <use fill="#D3D7DA" fill-rule="evenodd" xlink:href="#path-1"></use>
                            <rect stroke="#283541" stroke-width="1.7" x="7.51666667" y="24.4611111" width="6.36025835" height="6.36025835"></rect>
                        </g>
                        <g id="Rectangle-4-Copy-3">
                            <use fill="#D3D7DA" fill-rule="evenodd" xlink:href="#path-2"></use>
                            <rect stroke="#283541" stroke-width="1.7" x="7.51666667" y="36.1037065" width="6.36025835" height="6.36025835"></rect>
                        </g>
                        <g id="Rectangle-4-Copy">
                            <use fill="#D3D7DA" fill-rule="evenodd" xlink:href="#path-3"></use>
                            <rect stroke="#283541" stroke-width="1.7" x="21.8460148" y="24.4611111" width="6.36025835" height="6.36025835"></rect>
                        </g>
                        <g id="Rectangle-4-Copy-4">
                            <use fill="#D3D7DA" fill-rule="evenodd" xlink:href="#path-4"></use>
                            <rect stroke="#283541" stroke-width="1.7" x="21.8460148" y="36.1037065" width="6.36025835" height="6.36025835"></rect>
                        </g>
                        <g id="Rectangle-4-Copy-2">
                            <use fill="#D3D7DA" fill-rule="evenodd" xlink:href="#path-5"></use>
                            <rect stroke="#283541" stroke-width="1.7" x="36.175363" y="24.4611111" width="6.36025835" height="6.36025835"></rect>
                        </g>
                        <g id="Rectangle-4-Copy-5">
                            <use fill="#D8D8D8" fill-rule="evenodd" xlink:href="#path-6"></use>
                            <rect stroke="#283541" stroke-width="1.7" x="36.175363" y="36.1037065" width="6.36025835" height="6.36025835"></rect>
                        </g>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>`

**Comment by dpineda** [comment]
Adding the trace from the Custom logger btw this is for android emulator:

"Image loading failed: calendar.svg;(size=0x50,dip=True)\nSystem.IndexOutOfRangeException: Index was outside the bounds of the array.\n  at FFImageLoading.Svg.Platform.SKSvg.ReadPolyPath (System.String pointsData, System.Boolean closePath) [0x00041] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:856 \n  at FFImageLoading.Svg.Platform.SKSvg.ReadElement (System.Xml.Linq.XElement e, SkiaSharp.SKCanvas canvas, SkiaSharp.SKPaint stroke, SkiaSharp.SKPaint fill) [0x00593] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:276 \n  at FFImageLoading.Svg.Platform.SKSvg.ReadElement (System.Xml.Linq.XElement e, SkiaSharp.SKCanvas canvas, SkiaSharp.SKPaint stroke, SkiaSharp.SKPaint fill) [0x00623] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:300 \n  at FFImageLoading.Svg.Platform.SKSvg.ReadElement (System.Xml.Linq.XElement e, SkiaSharp.SKCanvas canvas, SkiaSharp.SKPaint stroke, SkiaSharp.SKPaint fill) [0x00623] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:300 \n  at FFImageLoading.Svg.Platform.SKSvg.ReadElement (System.Xml.Linq.XElement e, SkiaSharp.SKCanvas canvas, SkiaSharp.SKPaint stroke, SkiaSharp.SKPaint fill) [0x00623] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:300 \n  at FFImageLoading.Svg.Platform.SKSvg.ReadElement (System.Xml.Linq.XElement e, SkiaSharp.SKCanvas canvas, SkiaSharp.SKPaint stroke, SkiaSharp.SKPaint fill) [0x00623] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:300 \n  at FFImageLoading.Svg.Platform.SKSvg.ReadElement (System.Xml.Linq.XElement e, SkiaSharp.SKCanvas canvas, SkiaSharp.SKPaint stroke, SkiaSharp.SKPaint fill) [0x00623] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:300 \n  at FFImageLoading.Svg.Platform.SKSvg.ReadElement (System.Xml.Linq.XElement e, SkiaSharp.SKCanvas canvas, SkiaSharp.SKPaint stroke, SkiaSharp.SKPaint fill) [0x00623] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:300 \n  at FFImageLoading.Svg.Platform.SKSvg.ReadElement (System.Xml.Linq.XElement e, SkiaSharp.SKCanvas canvas) [0x00000] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:177 \n  at FFImageLoading.Svg.Platform.SKSvg.LoadElements (System.Collections.Generic.IEnumerable`1[T] elements, SkiaSharp.SKCanvas canvas) [0x00010] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:171 \n  at FFImageLoading.Svg.Platform.SKSvg.Load (System.Xml.Linq.XDocument xdoc) [0x00400] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:159 \n  at FFImageLoading.Svg.Platform.SKSvg.Load (System.IO.Stream stream) [0x00000] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SkSvg.cs:68 \n  at FFImageLoading.Svg.Platform.SvgDataResolver+<Resolve>d__19.MoveNext () [0x001b1] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Svg.Shared\\SvgDataResolver.cs:73 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 \n  at FFImageLoading.Work.ImageLoaderTask`2+<RunAsync>d__109[TImageContainer,TImageView].MoveNext () [0x0022e] in C:\\projects\\ffimageloading\\source\\FFImageLoading.Common\\Work\\ImageLoaderTask.cs:440 "

**Comment by dpineda** [comment]
I just found the issue and its related with the point values comma separator for polyline

this svg will work fine:
```
<svg height="180" width="500">
  <g fill="none" stroke="#283541" stroke-width="4">
    <polyline points="0,40 40,40 40,80 80,80 80,120" />
  </g>
</svg>
```
this svg will fail 
```
<svg height="180" width="500">
  <g fill="none" stroke="#283541"  stroke-width="4">
    <polyline points="0 40 40 40 40 80 80 80 80 120" />
  </g>
</svg>
```
but both will work fine in a web browser

**Comment by daniel-luberda** [comment]
It's a SCG parser issue. Please submit your issue here: https://github.com/mono/SkiaSharp.Extended as FFImageLoading uses its class [SKSvg.cs](https://github.com/mono/SkiaSharp.Extended/blob/master/SkiaSharp.Extended.Svg/source/SkiaSharp.Extended.Svg.Shared/SKSvg.cs)
