### ISSUE TITLE
StreamImageSource NullReferenceException on Android

### ISSUE THREAD

**Issue by Obvious1992** [luberda-molinet/FFImageLoading#611]
Hey guys, 
I am working with FFImageLoading inside my Telerik Listview (Xamarin Forms App). Due to a Telrik Listview Bug, I can't use byte[] on iOS for Images and therefore I wanted to use the following code for the FFImageControl:
` <ffimageloading:CachedImage
        Aspect="AspectFill"
        Opacity=".7" >
            <ffimageloading:CachedImage.Source>
                <OnPlatform x:TypeArguments="ImageSource">
                    <OnPlatform.iOS>
                        <UriImageSource Uri="{Binding FirstImageURL}"/>
                    </OnPlatform.iOS>
                    <OnPlatform.Android>
                        <StreamImageSource Stream="{Binding FirstImageByteArray, Converter={StaticResource ByteArrayToStream}}"/>
                    </OnPlatform.Android>
                </OnPlatform>
            </ffimageloading:CachedImage.Source>
        </ffimageloading:CachedImage>
 public class ByteArrayToStream : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            try
            {
                if (value != null)
                {
                    return (Func<CancellationToken, System.Threading.Tasks.Task<System.IO.Stream>>)(async(Test)  => new MemoryStream((byte[])value));
                }
            }
            catch (Exception)
            {
                Debug.WriteLine("Error loading Stream from Byte[] ");
            }
            return null;
        }

        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
`
This Code works fine on iOS where the Image get's loaded from the URI. On Android it's crashing with the following exception:

`
05-23 14:32:01.783 I/MonoDroid(15243): UNHANDLED EXCEPTION:
05-23 14:32:01.833 I/MonoDroid(15243): System.NullReferenceException: Object reference not set to an instance of an object.
05-23 14:32:01.833 I/MonoDroid(15243):   at FFImageLoading.Work.ImageLoaderTask`2+<<Init>b__3_0>d[TImageContainer,TImageView].MoveNext () [0x0000a] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:40 
05-23 14:32:01.833 I/MonoDroid(15243): --- End of stack trace from previous location where exception was thrown ---
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at FFImageLoading.Work.ImageLoaderTask`2+<Init>d__3[TImageContainer,TImageView].MoveNext () [0x00075] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:38 
05-23 14:32:01.843 I/MonoDroid(15243): --- End of stack trace from previous location where exception was thrown ---
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at FFImageLoading.Work.WorkScheduler+<LoadImage>d__44.MoveNext () [0x0022e] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\WorkScheduler.cs:163 
05-23 14:32:01.843 I/MonoDroid(15243): --- End of stack trace from previous location where exception was thrown ---
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <d18287e1d683419a8ec3216fd78947b9>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <20a5debecbfd420ba8345429bf71acbe>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <20a5debecbfd420ba8345429bf71acbe>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <20a5debecbfd420ba8345429bf71acbe>:0 
05-23 14:32:01.843 I/MonoDroid(15243):   at (wrapper dynamic-method) System.Object:1e8d8110-654f-4726-a14a-b09a7af2dfb9 (intptr,intptr)
`
With the normal Xamarin Forms Image Control my code works.

I am using the current stable FFImage + Stable Forms.

Best regards
Julian

**Comment by daniel-luberda** [comment]
- Did you try the newest prerelese? 
- It looks like your stream is either invalid or null

**Comment by Obvious1992** [comment]
Hey, 
I tried using the current pre-release.
Still running into the same problem.

The stream is valid and not null. If I bind the entire object to a converter and use a onPlatform in the .cs file it works with this stream. 

Best regards
Julian

**Comment by daniel-luberda** [comment]
Could you test the newest prerelease? (2.2.10.428)
