### ISSUE TITLE
Error inflating class ffimageloading.cross.MvxCachedImageView

### ISSUE THREAD

**Issue by Krupishev** [luberda-molinet/FFImageLoading#613]
I want to try your lib with Android MvvmCross Project.

1. I added Xamarin.FFImageLoading 2.2.9 to Android project
2. Add MvxCachedImageView to layout file
 ```
<ffimageloading.cross.MvxCachedImageView
            android:id="@+id/imageview_product_card"
            android:layout_width="126dp"
            android:layout_height="match_parent"
            app:MvxBind="ImageUrl Image" />
```
3. Сatch an exception

> {Android.Views.InflateException: Binary XML file line #1: Error inflating class ffimageloading.cross.MvxCachedImageView ---> Java.Lang.ClassNotFoundException: Didn't find class "ffimageloading.cross.MvxCachedImageView" on path: DexPathList[[zip file "/data/app/com.Bushe.Droid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.Bushe.Droid-1/lib/x86, /system/fake-libs, /data/app/com.Bushe.Droid-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]

Any ideas?

**Comment by daniel-luberda** [comment]
You must use FFImageLoading prerelease nuget package, sorry for that (it's a new class).
