### ISSUE TITLE
Slow loading images from cache with internet

### ISSUE THREAD

**Issue by Nickolas-** [luberda-molinet/FFImageLoading#614]
Hi, 

I found very interesting behavior , that images loading from cache much faster without internet, when I'm on 3g it take like 1300 ms to load from cache. 

I don't have time right now digging in a code, maybe someone know why do we have such a strange behavior.

Thanks

PS: I'm using latest prerelease version. ImageService.Instance.LoadUrl().WithCache(all).Into(this);

**Comment by Nickolas-** [comment]
Hi, any updates ?

**Comment by daniel-luberda** [comment]
Hi @Nickolas-  I'll need more info / code to debug it. Did you manage to solve it?


BTW: you can remove `.WithCache(all)` as all caches are used by default.
