### ISSUE TITLE
Has preload been depreciated

### ISSUE THREAD

**Issue by ndastur** [luberda-molinet/FFImageLoading#615]
It doesn't seem to be in the official docs, but I found reference to preload on the Xamarin forums. When I try to use preload like `FFImageLoading.ImageService.Instance.LoadUrl(App.userProfile.ProfileUri).Preload();` there is an error that Preload is not a member.

**Comment by patook** [comment]
I think because it is a task extension you need to also put `using FFImageLoading; ` at the top of the file (i.e. it's not enough to do FFImageLoading.ImageService...)

**Comment by daniel-luberda** [comment]
Hi @ndastur,

Yes, @patook is right. It's an extension method. (thanks)
