### ISSUE TITLE
Heap corruption

### ISSUE THREAD

**Issue by lfongaroScp** [luberda-molinet/FFImageLoading#617]
Hi,

I use this library in a single fragment of my app Xamarin.Android where I load a big amount of images. It works fine. I extended the usage to other fragments where I load images. However, if I navigate through these fragments the app crash with heap corruption very soon.

I attach the log I obtain in the Android Device Monitor.

[log.txt](https://github.com/luberda-molinet/FFImageLoading/files/1035189/log.txt)

**Comment by daniel-luberda** [comment]
Hi @lfongaroScp, 

I've quickly reviewed your log and it looks like it's not FFImageLoading related issue. See this:

>>>05-29 09:46:21.669: W/debuggerd(301): type=1400 audit(0.0:20785): **avc: denied { search } for** uid=0 name="**com.google.android.gms**" dev="mmcblk0p42" ino=230 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-29 09:46:21.679: W/debuggerd(301): type=1400 audit(0.0:20786): **avc: denied { search } for uid=0** name="**com.google.android.gms**" dev="mmcblk0p42" ino=230 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-29 09:46:21.679: W/debuggerd(301): type=1400 audit(0.0:20787): **avc: denied { search } for uid=0** name="**com.google.android.gms**" dev="mmcblk0p42" ino=230 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
