### ISSUE TITLE
Preload(), and memory leak.

### ISSUE THREAD

**Issue by ziomagic** [luberda-molinet/FFImageLoading#618]
Hello. 
I am using Xamarin Forms + Prism. I found that my app is not freeing memory taken by CachedImage, when View is closed.
When view is opened, I am preloading all images like this:
```
 try
                {
                    var task = ImageService.Instance.LoadUrl(url, TimeSpan.FromDays(1));
                    task.WithCache(FFImageLoading.Cache.CacheType.Disk);
                    task.BitmapOptimizations(true);

                    await task.Success(() =>
                    {
                        Device.BeginInvokeOnMainThread(() =>
                        {
                            LoadedImages.Add(url);
                            RemoveLoadingReference();

                            // Load first image from list
                            if (ImageUrl == null)
                            {
                                Position = 0;
                            }

                            OnPropertyChanged(() => PositionText);
                        });
                    })
                    .Error((info) =>
                    {
                        Device.BeginInvokeOnMainThread(() =>
                        {
                            RemoveLoadingReference();
                        });

                    }).PreloadAsync();
                }
```
And my CarouselViewControl item template looks like this:
```
          <ffimageloading:CachedImage
            HorizontalOptions="CenterAndExpand"
            VerticalOptions="CenterAndExpand"
            Aspect="AspectFit"
            DownsampleToViewSize="False"
            Source="{Binding .}">
          </ffimageloading:CachedImage>
```
I was testing this on iOS, and Android, and memory was not released in both cases. I was trying to call ImageSerice.Instance.InvalidateCacheAync, but it was freezing my app when called more than one time.

**Comment by ziomagic** [comment]
`ImageSerice.Instance.InvalidateCacheAync` was freezing my app, but using `ImageService.Instance.InvalidateCacheEntryAsync(url, CacheType.Memory);` is freeing memory. So issue can be closed.

**Comment by daniel-luberda** [comment]
Hi @ziomagic 
- You must use `Preload` with caution as device resources are finite. 
- "Not freeing memory" is what `Preload` method is all about, it caches bitmaps in RAM for a quicker access in future.
- Consider using `DownloadOnly` instead.

**Comment by aucompany** [comment]
My ios app also freezes when calling ImageSerice.Instance.InvalidateCacheAync. How to fix it?

**Comment by daniel-luberda** [comment]
@aucompany Could you write more details? How many images? What platform? Sample code?
