### ISSUE TITLE
Gif Image To LoadingPlaceholder

### ISSUE THREAD

**Issue by emrealtann** [luberda-molinet/FFImageLoading#623]
Hello and thanks for the library.
Is there a way to put a gif animation to `LoadingPlaceholder` property?

**Comment by alanspires** [comment]
I just did a quick test and in the latest pre-release it appears to work. Please note that GIF is still in it's infancy in the library and I only tested on iOS.

**Comment by daniel-luberda** [comment]
@emrealtann As @alanspires said,  it's now implemented in prerelease build. You can test it, any feedback is appreciated (some things need to be improved, but the basic support is implemented).
