### ISSUE TITLE
Please specify in the Wiki where to place SVG-images and what to do with them for PCL

### ISSUE THREAD

**Issue by quakeulf** [luberda-molinet/FFImageLoading#628]
Hi, I cannot get SVGs to show because I get so many errors related to me not knowing where to put them and what to do with them.

Placing them in the PCL in its own folder and making them "Embedded Resources" gives me:

`System.IO.FileNotFoundException`

Placing them in Android's Resources' drawable as "AndroidResource" makes the app crash on startup:
```

06-06 12:04:37.017 E/mono-rt ( 5108): =================================================================
06-06 12:04:37.017 E/mono-rt ( 5108): Got a SIGSEGV while executing native code. This usually indicates
06-06 12:04:37.017 E/mono-rt ( 5108): a fatal error in the mono runtime or one of the native libraries 
06-06 12:04:37.017 E/mono-rt ( 5108): used by your application.
06-06 12:04:37.017 E/mono-rt ( 5108): =================================================================
```

So how do people get the SVGs to work? I can't find anything that works. Please help me out. Thank you very much in advance for helping me out.

**Comment by daniel-luberda** [comment]
- Did you try our sample project? It has SVG example. 
- Maybe the SVG file you're using is not supported? Current SVG parser is quite simple. 
- Can you make a reproduction?

**Comment by quakeulf** [comment]
I am using SVGs exported from Illustrator, here's a sample of what a file looks like:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 16 40" enable-background="new 0 0 16 40" xml:space="preserve">
<g>
	<path fill="#333333" d="M4,37c-0.1,0-0.3,0-0.4-0.1c-0.5-0.2-0.7-0.8-0.4-1.3L10.9,20L3.1,4.4C2.9,4,3.1,3.4,3.6,3.1
		c0.5-0.2,1.1,0,1.3,0.4l8,16c0.1,0.3,0.1,0.6,0,0.9l-8,16C4.7,36.8,4.4,37,4,37z"/>
</g>
</svg>
```
I will try the example project now.

**Comment by quakeulf** [comment]
Unfortunately every time I try to build the project located here:

https://github.com/luberda-molinet/FFImageLoading/tree/master/samples/ImageLoading.Forms.Sample/Droid

I get:
```
Error		The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Shared.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	FFImageLoading.Forms.Sample.Droid
```

**Comment by daniel-luberda** [comment]
@quakeulf I've tested it today (On Mac) - it works for sure. Did you recover nuget packages etc?

**Comment by quakeulf** [comment]
It's a Xamarin/Visual Studio-issue. I am downloading the target framework now. Will try again when installed.

**Comment by quakeulf** [comment]
After installing required 4.5.2.NET-frameworks I now have another errors with the FFImageLoading.Forms.Sample.Droid-project:

`Error	CS0234	The type or namespace name 'Droid' does not exist in the namespace 'FFImageLoading.Forms' (are you missing an assembly reference?)	FFImageLoading.Forms.Sample.Droid	D:\delemappe\ffi\samples\ImageLoading.Forms.Sample\Droid\MainActivity.cs	11	Active`

`Error	CS0103	The name 'CachedImageRenderer' does not exist in the current context	FFImageLoading.Forms.Sample.Droid	D:\delemappe\ffi\samples\ImageLoading.Forms.Sample\Droid\MainActivity.cs	27	Active`

I have looked up the "CachedImageRenderer"-reference and found it in two .cs-files, but I cannot understand why it will not want to be referenced in the MainActivity.cs-file.

**Comment by quakeulf** [comment]
Ok, we fixed the error by manually removing and re-adding the reference to that in the References-directory in the Sample.Droid-project, but when building for Android 6.0 and choosing "Simple SVG example" in the menu the app crashes with an unhandled exception.

When opening it again, it worked, but now the SVGs in the emulated app look a bit like this:

https://github.com/luberda-molinet/FFImageLoading/issues/605

**Comment by daniel-luberda** [comment]
@quakeulf It's a knows issue of SkiaSharp library, it's visible only on emulators. It should be fixed soon, and then you only need to update SkiaSharp library to solve it. You can also downgrade SkiaSharp too.

**Comment by daniel-luberda** [comment]
BTW: With the newest version using embedded resource is as easy, as setting `Source` to `resource://your.resource.name`

**Comment by quakeulf** [comment]
Thank you for helping out, will try it out.

**Comment by quakeulf** [comment]
It works, thank you very much.

Sorry for the late reply, but I was away.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support#svg-support
