### ISSUE TITLE
GIF support enhancement

### ISSUE THREAD

**Issue by daniel-luberda** [luberda-molinet/FFImageLoading#629]
- Use FFImageLoading methods for bitmap frames creation, so we have: 
  - better caching
  - downsampling / transformations / others support
- [iOS] Sometimes gif image is not shown (fix needed)
- [Android] Fade animation not working for gifs

**Comment by ninianh** [comment]
hi @daniel-luberda , thank you for supporting gif.
I am using the latest prerelease 2.2.10-pre-408. I just have a small issue with Gif on iOS real device (iOS simulations work fine). The gif is very slow, there is something wrong with frameAnimation.Duration.

**Comment by marlonconstante** [comment]
@daniel-luberda Is it possible to disable gif animation?
It would also be interesting to keep an image frame fixed (first or last for example)

**Comment by daniel-luberda** [comment]
@marlonconstante Yes, you can disble it with custom config `AnimateGif` property

**Comment by marlonconstante** [comment]
@daniel-luberda Thanks!
