### ISSUE TITLE
Xamarin.iOS / SVG -- Image Full Black [need clarification]

### ISSUE THREAD

**Issue by hschmied** [luberda-molinet/FFImageLoading#630]
Pretty sure I am missing something or doing something wrong, so before I look around for another 2 hours, I hope someone can clarify this for me.

I am trying to put an svg graphic, loaded from the internet, into an uiimageview. I got it somewhat to work with the following...

```
var resolver = new SvgDataResolver(60, 60, true);
ImageService.Instance
			.LoadUrl(url)
			.WithCustomDataResolver(resolver)
			.Into(productImageView);
```

... which is invoked on the main thread. Somewhat, because the images loaded are all black, looking as if it's only displaying the alpha/transparency channel. Copy&Pasting the url into my browser, I get an image with colors and everything.

What am I missing? Is it not possible to use FFImageLoading.Svg with UIImageView, is there any other restrictions or do I have to add something?

Thank you & best regards!
-H

**Comment by daniel-luberda** [comment]
Hi @hschmied,

It's possible you use some more complicated SVG file. We use a simple SVG file parser now (from: https://github.com/mono/SkiaSharp.Extended) and it's possible that it isn't parsed correctly. For a possible solution, try to:

- simplify your SVG file
- open it in Inkscape and save as pure SVG 1.0
- etc

**Comment by hschmied** [comment]
Thanks for the quick response -- I'll try that.

**Comment by hschmied** [comment]
Ok -- Update
I tried it with some other SVGs I found on the web and with them it worked.

A broader compatibility of this framework would be of course nice, but for now I'll go back to my guys and tell them we need to figure out how to export our assets to make it work with FFImageLoading.

Thank you, thanks for the help and FFImageLoading!

**Comment by daniel-luberda** [comment]
No problem, if you want to collaborate to SVG parser feel free to do it, here's the class: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SkSvg.cs

**Comment by andyhoyle** [comment]
For others viewing this ticket and wondering how to fix the original SVG in Inkscape: when using File > Save As, choose Optimised Svg. This opens a screen with some options. The default options worked for me.
