### ISSUE TITLE
How to resize an image  by device width and mantain ratio?

### ISSUE THREAD

**Issue by biapar** [luberda-molinet/FFImageLoading#631]
How to resize an image  by device width and mantain ratio?

**Comment by daniel-luberda** [comment]
You need to get device width by yourself. Ratio is always maintained, just set `DownsampleWidth` to your desired size.

**Comment by biapar** [comment]
I read the device width with Application.Current.MainPage.Width and assigned to downsamplewidth?
Is't right?
Is still necessary AspectFill?

**Comment by biapar** [comment]
Any help?
