### ISSUE TITLE
ErrorPlaceholder not shown when url is not valid

### ISSUE THREAD

**Issue by flaviosuardi** [luberda-molinet/FFImageLoading#633]
I have a problem on Android with this Xamarin configuration:
PCL 4.5 - Profile 111
Xamarin Forms 2.3.4.247

I've developed in PCL a CachedImage, its `Source` is an url to an image but sometimes this url not points properly to an image but to a html page (ex: https://www.cellulariusati.net/develop/sites/default/files/styles/inserzioni_api/public/immagini/inserzioni/3763/img_5574.jpg?itok=KIBmyjZ7). I have setted an ErrorPlaceholder and in iOS all works fine (infact I receive in console some exceptions and the ErrorPlaceholder is shown) but when I run the same code in Android the ErrorPlaceholder is not shown. In console output I have this item:

`[skia] --- SkImageDecoder::Factory returned null`

that indicate an error on decoding but no other exception is thrown. Is there a way to catch this error or a fix that thrown an exception to catch for handling this case?

**Comment by beylkhanovdamir** [comment]
@flaviosuardi where you are storing error image in android app?

**Comment by flaviosuardi** [comment]
@beylkhanovdamir the error image is a png file stored in various resolutions (mdi, hdpi, xhdpi, xxhdpi) in the relative `Resources\drawable` folder

**Comment by daniel-luberda** [comment]
We could modify `DownloadCache` to check if the return type is in html format and throw an exception there. That should fix it. 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Cache/DownloadCache.cs#L86-L160

**Comment by daniel-luberda** [comment]
Fixed
