### ISSUE TITLE
Not clearing the image cache with v2.2.9

### ISSUE THREAD

**Issue by vijayMmenlo** [luberda-molinet/FFImageLoading#634]
I am implementing profile pic adding and updating functionality  and trying to update but it's not updating when it comes to the profile screen for the next time. Clearing cache not working for me. I am using below code.
await CachedImage.InvalidateCache(rootObj.data.patron_photo_thumb_url, FFImageLoading.Cache.CacheType.All, removeSimilar: true);
And using the latest version v2.2.9.

Can you help me on this issue.

**Comment by daniel-luberda** [comment]
@vijayMmenlo Please check the newest prerelease as there were some fixes in there and let me know if you're still experiencing it.

**Comment by EaranMaleasi** [comment]
Same problem here with 2.2.10-pre-408

**Comment by Raj123456788** [comment]
@daniel-luberda I am also experiencing same issues with above version.

**Comment by vijayMmenlo** [comment]
@daniel-luberda , Iam still facing the same issue even if I used 2.2.10-pre-408.
Please help me on this as I need to fix this urgently.

**Comment by vijayMmenlo** [comment]
Hey, I just used below code to clear cache.. It's working now
                            ImageService.Instance.InvalidateCacheEntryAsync(rootObj.data.patron_photo_thumb_url, FFImageLoading.Cache.CacheType.All, removeSimilar: true);

**Comment by Raj123456788** [comment]
I am getting Invalidate Cache API only not the one you mentioned above? What version are you using?

**Comment by vijayMmenlo** [comment]
IAM using latest version i.e., v2.2.10 pre-408. Please check with this version. It works

        Vijay Kumar Medisetty
Software Engineer
vijayam@menlo-technologies.com
mobile +91 9000155473


Confidentiality Note:  This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.

________________________________

**Comment by Raj123456788** [comment]
@vijayMmenlo @daniel-luberda : I need image to be updates every sec. Using InvalidateCacheEntryAsync API with CacheType=Memory does not update the image.

**Comment by daniel-luberda** [comment]
Could you test the newest prerelease? (2.2.10.428) It should be fixed now. Please reopen if it's still a valid issue. Thanks
