### ISSUE TITLE
Add EmbeddedResource support for FFImageLoading.Cross

### ISSUE THREAD

**Issue by sabvente** [luberda-molinet/FFImageLoading#635]
Hi, It would be really great if we could use EmbeddedResource in FFImageLoading.Cross. I'm using 2.2.10-pre-408.
```c#
<ffimageloading.cross.MvxCachedImageView
    android:layout_width="100dp"
    android:layout_height="100dp"
    local:MvxBind="ImagePath Image" />
```
where
`Image="resource://MyPclNamespace.myimage.png?assembly=MyPclAssembly"`

Currently, it fails with the following exception `FFImageLoading.DownloadAggregateException: One or more errors occurred. ---> System.ArgumentException: Only http or https scheme is allowed`

Thank you!

**Comment by daniel-luberda** [comment]
@sabvente It should be very easy to add as we already have this working in Xamarin.Forms. I'll implement it by this weekend.

**Comment by lanceking** [comment]
Did this end up making it into the pre-420 release? or still a WIP?

**Comment by lanceking** [comment]
If I knew enough about this project to dig my teeth in I absolutely would...

Any chance that this feature will make it through soon? I'm still seeing the error @sabvente mentioned above.

**Comment by lanceking** [comment]
Welp, I actually dug my teeth in and got this working. I'll fork and submit a PR tonight if I can. Not sure if I did it right but we'll see !

**Comment by daniel-luberda** [comment]
Thanks to @lanceking we have it working now. 👍
