### ISSUE TITLE
Change the color of an SVG?

### ISSUE THREAD

**Issue by ericruelas** [luberda-molinet/FFImageLoading#640]
I am fully aware on how the fill attribute on the path tag changes color but i want to change it via the xaml tag. Is this support coming out soon?

<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="22px" height="22px" viewBox="0 0 22 22" enable-background="new 0 0 22 22" xml:space="preserve">
<title>check-circle-2</title>
<g id="Layer_2">
	<g id="Foreground">
		<path **fill="#25B55E"** d="M11,0C4.9249,0,0,4.9249,0,11s4.9249,11,11,11s11-4.9249,11-11S17.0751,0,11,0z M10.18,17.33l-5.5-4.13
			L6.33,11l3.3,2.47l5.78-7.7l2.2,1.65L10.18,17.33z"/>
	</g>
</g>
</svg>

**Comment by daniel-luberda** [comment]
Replacing parts of SVG's is already supported in latest prerelease. You just define a replacement map dictionary (`Dictionary<string, string>`). 

- `SvgDataResolver`: constructor's `replaceStringMap` parameter
- `SvgImageSource`: constructor's `replaceStringMap` parameter
- `SvgCachedImage`: `ReplaceStringMap` property

**Comment by ericruelas** [comment]
But there isn't a way to change it via the XAML?

**Comment by RaZp29** [comment]
could you give an example of these @daniel-luberda ?

**Comment by quakeulf** [comment]
Yes, an example would be neat. :3

**Comment by vlkam** [comment]
I change color of a SVG from XAML like this

`                            <ffsvg:SvgCachedImage 
                                WidthRequest="40" 
                                HeightRequest="40" 
                                HorizontalOptions="Center"
                                Source="resource://JCabinet.Resources.Icons.qrscan.svg">

                                <ffimg:CachedImage.Transformations>
                                    <fftransf:TintTransformation
                                        HexColor="#ff000000" EnableSolidColor="true"/>
                                </ffimg:CachedImage.Transformations>

                            </ffsvg:SvgCachedImage>
`

**Comment by daniel-luberda** [comment]
There are many ways to achieve it. 

- You can just define `Dictionary<string,string>` with needed key/value items inside `ResourceDictionary`. 
- You can create a static `Dictionary<string,string>` and combine it with `x:Static` 
- etc

Did you try it?

**Comment by satputerohan** [comment]
@daniel-luberda : There is no ReplaceStringMap property available on SvgCachedImage. I am on the latest prerelease 2.2.10-pre-438. Currently going with solution @vlkam provided..

**Comment by biapar** [comment]
Is there an example of Xamarin Forms code or XAML?

**Comment by 1iveowl** [comment]
An example here would indeed be nice. 

I'm geting nowhere with a simple SVG that I want to present as white strokes on a black background. 

 vlkam's XAML example above is not helping.

**Comment by Sokoo92** [comment]
Since everyone needs an example, I'll give you guys one :)
So first we create a Dictionary in our ViewModel and we get the Color we want from our ResourceDictionary.
`public Dictionary<string, string> ReplaceMap { get; set; }
 public Color CircleColor = (Color)Application.Current.Resources["COLOR_YOU_WANT"];`
Then in the Contructor of our ViewModel we construct the Dictionary
`ReplaceMap = new Dictionary<string, string>()
            {
                {"#FILLCOLOR", GetHexString(CircleColor) }
            };`
I've used a method to Convert the color we got from our ResourceDictionary to a HexString, because getting the color as we did gives back a Color object which cannot be inserted into the SVG.
HexString method(I took this from StackOverflow somwhere):
`public static string GetHexString(Xamarin.Forms.Color color)
        {
            var red = (int)(color.R * 255);
            var green = (int)(color.G * 255);
            var blue = (int)(color.B * 255);
            var alpha = (int)(color.A * 255);
            var hex = $"#{alpha:X2}{red:X2}{green:X2}{blue:X2}";

            return hex;
        }`
Now set the Binding of ReplaceMapString to ReplaceMap in your View.xaml and run it.

**Comment by rogihee** [comment]
Here is another example.  Always check your SVG how the colors are inserted, I use Icons8 for example for my SVG icons and they generate files with "style="fill: rgb(0, 0, 0);" in it. I personally always use black as default so you can see them in the file explorer in Windows (https://code.google.com/archive/p/svg-explorer-extension/downloads).

```
var dict = new Dictionary<string, string>();
dict.Add("fill: rgb(0, 0, 0);", GetRGBFill(myXamarinColor));

var icon = new SvgCachedImage
{
     ReplaceStringMap = dict,
     Source = source,
};
```
And a small helper to do the replacement:

```
public static string GetRGBFill(Xamarin.Forms.Color color)
        {
            var red = (int)(color.R * 255);
            var green = (int)(color.G * 255);
            var blue = (int)(color.B * 255);
            // var alpha = (int)(color.A * 255);
            var rgbFill = $"fill: rgb({red},{green},{blue});";
            return rgbFill;
        }

```

**Comment by daniel-luberda** [comment]
@Sokoo92  @rogihee 

Feel free to update our wiki with samples, it could help others to see it.

**Comment by rogihee** [comment]
@daniel-luberda done

**Comment by themronion** [comment]
guys, what about replacing only the color of a part of an image? Like here i have:
 `
<svg width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M7.45185 15.5373C3.41579 9.50333 2.66663 8.88406 2.66663 6.6665C2.66663 3.62893 5.05443 1.1665 7.99996 1.1665C10.9455 1.1665 13.3333 3.62893 13.3333 6.6665C13.3333 8.88406 12.5841 9.50333 8.54807 15.5373C8.28321 15.9318 7.71668 15.9318 7.45185 15.5373Z" fill="#FF9800"/>
<path d="M8 8.5C9.10457 8.5 10 7.60458 10 6.5C10 5.39543 9.10457 4.5 8 4.5C6.89543 4.5 6 5.39543 6 6.5C6 7.60458 6.89543 8.5 8 8.5Z" fill="white"/>
</svg>
`
i want to change the fill color of the first path? Is that still possible somehow?

**Comment by stesvis** [comment]
@daniel-luberda How do you set the `HexColor` using a style?
I tried this but it doesn't work (since `HexColor` is a string I tried it this way).

In my ResourceDictionary:
```xml
<Color x:Key="iconColor_light" x:FactoryMethod="FromHex">
        <x:Arguments>
            <x:String>#000000</x:String>
        </x:Arguments>
</Color>

<Color x:Key="iconColor_dark" x:FactoryMethod="FromHex">
        <x:Arguments>
            <x:String>#ffffff</x:String>
        </x:Arguments>
</Color>
```

And then in XAML:
```xml
<ffimageloadingsvg:SvgCachedImage.Transformations>
    <ffimageloadingTrans:TintTransformation HexColor="{AppThemeBinding Light={StaticResource iconColor_light},
        Dark={StaticResource iconColor_dark}}" EnableSolidColor="true" />
</ffimageloadingsvg:SvgCachedImage.Transformations>
```

Is it even possible to bind it to the AppTheme?

**Comment by Axemasta** [comment]
@stesvis looking at the [source](https://github.com/luberda-molinet/FFImageLoading/blob/bb675c6011b39ddccecbe6125d1853de81e6396a/source/FFImageLoading.Transformations/TintTransformation.cs#L26) its probably not possible to bind this value to an app theme.

I came up with a hack that will work for the current theme of the app, so long as the `OSAppTheme` is never changed at runtime, you won't have any worries:

1. Reference your `SvgCachedImage`
```
<ff:SvgCachedImage x:Name="SvgImage" Source="{x:Static resources:SvgConstants.SwipeRightIcon}"/>
```
2. Add the following method:
```csharp
private void SetTint(OSAppTheme theme)
{
    string hexColor = string.Empty;

    switch (theme)
    {
        case OSAppTheme.Light:
            hexColor = "#3497c5";
            break;

        case OSAppTheme.Dark:
            hexColor = "#ed625c";
            break;
    }

    var tint = new TintTransformation()
    {
        HexColor = hexColor,
        EnableSolidColor = true
    };

    SvgImage.Transformations.Add(tint);
}
```
3. Call the method with the current app theme
```csharp
public YourPage()
{
    InitializeComponent();

    SetTint(Application.Current.RequestedTheme);
}
```

As I said, this won't bind at runtime because the library itself is not doing that. However its a nice enough workaround to at least apply a theme specific tint!
