### ISSUE TITLE
Unable to load Images from Assets Folder

### ISSUE THREAD

**Issue by shabirjan** [luberda-molinet/FFImageLoading#645]
There seem to be an issue when i want to show image from Assets Catalog. It works fine when i display the image from Resource folder but not when i point to Asset Catalog image bundle.

I am using 2.2.9 Version of FFImageLoading , please have a look at my demo project as well.

https://github.com/shabirjan/DemoFFImageLoader

**Comment by henningms** [comment]
Noticing the same problem here as well.

**Comment by henningms** [comment]
It works with the -pre version of 2.2.10

**Comment by CSkoubo** [comment]
Just did a quick look, and I believe this is the reason for your issue, it seems to work pre that:
https://github.com/luberda-molinet/FFImageLoading/issues/479

If i get some spare time over the weekend ill make a fix.

**Comment by daniel-luberda** [comment]
Can you reproduce it with 2.2.10?
