### ISSUE TITLE
FFImageLoading 2.2.10-pre-408 - This Version Makes Android app stuck when loading more items.

### ISSUE THREAD

**Issue by vijayMmenlo** [luberda-molinet/FFImageLoading#646]
I have been working on implementing the Listview with images using FFImageLoading 2.2.10-pre-408 version. Every loadmore I am adding 10 items to the listview. In the process of binding items, Android app gets stucked. Please find below screen shot.

If I remove image completely from listview design, No app stuck. Only problem with Caching images taking more heap memory.

Please help on this.

![listviewwithobservablecollectionandloadmore](https://user-images.githubusercontent.com/29198169/27367578-856b9e34-566b-11e7-8603-728f3bd523a9.PNG)

**Comment by belhunter** [comment]
I checked sample for MvvmCross - the same issue. Setting HttpClient implementation to the native handler didn't help...

**Comment by daniel-luberda** [comment]
Should be fixed in the newest prerelease. Please reopen if it still occurs.
