### ISSUE TITLE
Xamarin.Mac & Xamarin.Forms.Mac support

### ISSUE THREAD

**Issue by YZahringer** [luberda-molinet/FFImageLoading#648]
Currently support for macOS by Xamarin is in beta with version 2.3.5. Would it be possible to provide a pre-release with macOS support?

**Comment by daniel-luberda** [comment]
Thanks to @Sevenish and #723  we have now a basic Mac support.

TODO:

- Xamarin.Forms support
- SVG support
- Transformations support
- WebP, GIF support
- FadeIn support

**Comment by daniel-luberda** [comment]
2.2.12.497 nuget with Mac support released.  (Xamarin.Forms not supported yet)

**Comment by daniel-luberda** [comment]
- I added Xamarin.Forms.Mac project + sample project
- It's not working yet, as somehow renderer is not used. (Does Xamarin.Forms.Mac support custom renderers now?) 

I didn't have time to take a look at this, any help with this appreciated.

**Comment by daniel-luberda** [comment]
XF fixed & Transformations added. All should be implemented now :)

**Comment by daniel-luberda** [comment]
Missing: 

- SVG support
- WebP, GIF support
- FadeIn support

**Comment by YZahringer** [comment]
Thank you, awesome work! I'm doing a Xamarin Forms application on macOS, I'll try this 😃

**Comment by daniel-luberda** [comment]
Thanks! :) Also that might be quite important fix for you: https://github.com/luberda-molinet/FFImageLoading/commit/344480d146c099b76cee4812c1d05c63a662c96a

Now, the behaviour is the same as Xamarin.Forms.Image

**Comment by daniel-luberda** [comment]
Done. Everything is working (including SVG & WebP), only GIF left. 

Gif should be working as it's also implemented. But it doesn't animate. Any Mac experts here? 

Code:

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Shared.IosMac/Work/PlatformImageLoaderTask.cs#L121-L138

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Mac/Targets/NSImageViewTarget.cs#L26-L31

Any clues why it's not animating?
