### ISSUE TITLE
question about Button.Image

### ISSUE THREAD

**Issue by acaliaro** [luberda-molinet/FFImageLoading#649]
Hi guys.
I have a question...

Now I use this code in Xamarin Forms

Button b = new Button();
b.Image = "myimage.png"

Is it possible (or "is it correct") to use something similar to

b.Image = new CachedImage{Source = "myimage.png"};

**Comment by daniel-luberda** [comment]
Not really, FFImageLoading uses its own native view containers. What you can do (if you, for example want to achieve some custom transformations), write the image to the disk with: 

`ImageService.Instance.LoadUrl("http://some.url").AsJPGStreamAsync();`

and then use it as an image source.
