### ISSUE TITLE
Xamarin.Forms - implement fast renderers

### ISSUE THREAD

**Issue by philipag** [luberda-molinet/FFImageLoading#650]
2.3.5 is about to be released and pre5 is now pretty stable.  Would be nice to update FFImageLoading to use fast renderers as this can greatly simplify the Android visual tree and speed things up.

**Comment by mattrichnz** [comment]
I would recommend waiting for the stable release, as there are still known issues with fast renderers related to ObjectDisposedException and GC on Android.

**Comment by daniel-luberda** [comment]
We'll need to think of something to preserve old Forms version compatibility too.

**Comment by EmmanVazz** [comment]
Fast rendered are now in the stable channel of forms. However they are an experimental feature. Most if not all issues have been resolved that happened in the prereleases with them.

**Comment by daniel-luberda** [comment]
I'll need some help:

Do you know how could we enable fast renderers conditionally? Currently, renderers are registered with dependency attribute: `[assembly: ExportRenderer(typeof(CachedImage), typeof(CachedImageRenderer))]`. 

Is it possible to overwrite currently registered renderer by code? Any ideas how could we do it to? 

We'll need it for compatibility reasons. Ideally I want to creare `CachedImageRenderer.Init(bool enableFastRenderers)` override.

**Comment by daniel-luberda** [comment]
Initial implementation (not working yet): [CachedImageFastRenderer.cs](https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms.Droid/CachedImageFastRenderer.cs)

Problems: 

- `ElevationHelper.SetElevation(this, e.NewElement);` is missing (internal xamarin class)
- `_visualElementRenderer = new VisualElementRenderer(this);` - internal xamarin class 
- `_element?.SendViewInitialized(Control);` is missing (internal xamarin class)

**Comment by daniel-luberda** [comment]
It's working now! https://github.com/luberda-molinet/FFImageLoading/commit/f3a706a2121597adf5acbfdfe8ead8b288104223

You can test it by installing prerelease 2.2.23 nuget packages and enable it by calling `CachedImageRenderer(enableFastRenderer: true);`

**Comment by fschwiet** [comment]
Any guidance on when to enable fast renderer?  I mean fast is good right, so why not always have it on?

Well honestly I'm just updating our package reference and am not caring about a perf gain, so maybe I should use false as it might be safer.

Oh, I can also pass in null.
