### ISSUE TITLE
Add a DownsampleMode properties for Forms / Native

### ISSUE THREAD

**Issue by YZahringer** [luberda-molinet/FFImageLoading#652]
Hello,

How to use InterpolationMode.None / NearestNeighbor in Xamarin Forms to have pixelized resized image? I use FFImage.DownsampleMode="None" with UWP, but I can not find any way in Xamarin XAML Forms.

I use this to enlarge a small QrCode image, that's why I need to disable "anti-aliasing". In CSS i use:
````cs
@mixin pixelated {
-ms-interpolation-mode: nearest-neighbor; // IE 7+ (non-standard property)
image-rendering: -webkit-optimize-contrast; // Safari 6, UC Browser 9.9
image-rendering: -webkit-crisp-edges; // Safari 7+
image-rendering: -moz-crisp-edges; // Firefox 3.6+
image-rendering: -o-crisp-edges; // Opera 12
image-rendering: pixelated; // Chrome 41+ and Opera 26+
}
````

Is there any way to do this with FFImageLoading?

**Comment by daniel-luberda** [comment]
Here's the current implementation, I hope it would help: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Windows/Extensions/ImageExtensions.cs#L182-L191

**Comment by JTOne123** [comment]
What was changed in the latest release(2.2.13) with DownsampleToViewSize in forms for UWP?

Issue is: into big CachedImage loads too small sized images

but if set a height and width everything is ok

Is it something was broken or fixed?

**Comment by daniel-luberda** [comment]
@JTOne123 Read this: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#downsampletoviewsize-bool-default-false

I was tired of explaining the same thing multiple times (poor performance), so I put fixed value (which is very low) when view doesn't have a size defined (is expandable). If you experience this, it means than `DownsampleToViewSize` didn't work at all for that view and you should use `DownsampleWidth` / `DownsampleHeight` as described in wiki. I just release 2.2.14 which will additionally will warn about this in logs.

**Comment by JTOne123** [comment]
yep, definitely it is my case, thank for an answer

**Comment by daniel-luberda** [comment]
2.2.14 just released. It will also log an error with explanation. https://github.com/luberda-molinet/FFImageLoading/commit/46e021bb24c15ccc49c0498c7d198532f804fd71

**Comment by daniel-luberda** [comment]
Sorry, wrong issue.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/859
