### ISSUE TITLE
Add a BadgeTransformation implementation

### ISSUE THREAD

**Issue by sbalinder** [luberda-molinet/FFImageLoading#653]
Hello,

I used the library couple of days back and is extremely impressed. You guys have done excellent work and thanks for marking it public. 

Want to know If there isa functionality to show a badge next to a circularTransformed image?

Thanks

**Comment by daniel-luberda** [comment]
You could achieve it by creating a custom transformation which adds a text to the image. The downside is you need to implement it in a platform specific ways. It should be really easy to implement it. If you have something and willing to upload it, I could add it to the official release. You could browse current implementations here: 

- https://github.com/luberda-molinet/FFImageLoading/tree/master/source/FFImageLoading.Transformations.Droid
- https://github.com/luberda-molinet/FFImageLoading/tree/master/source/FFImageLoading.Transformations.Touch

Custom Transformations don't need to be bundled into the library, you can have it in your assembly as all FFImageLoading methods / properties accept just an `ITransformation` interface.

**Comment by daniel-luberda** [comment]
I don't think we still need that as FFImageLoading supports SVG's and it can be easily done with it / or in Xamarin Forms tou can just use grid and stack image and label.
