### ISSUE TITLE
Loading Image from Cache without LoadingPlaceholder

### ISSUE THREAD

**Issue by jorgenstorlie** [luberda-molinet/FFImageLoading#654]
I load images from an URL like this:

   taskImage = ImageService.Instance.LoadUrl(imageURL)
                .CacheKey(ObjectId.ToString())
                                                       .DownSample(width: imageSize)
                                                        .Retry(0, 0)
                                
                                       .Error(exception =>
           {
               AddEmptyImage(ObjectId.ToString());
           })
               .ErrorPlaceholder(localFilename, ImageSource.Filepath)
               .LoadingPlaceholder(localFilename, ImageSource.Filepath);

This works, it displays LoadingPlaceholder and ErrorPlaceholder as expected.

The problem is if i close the application and restart the application.

The image is stored in cache and I expect it be displayed without any LoadingPlaceholder, but the first time the image is loaded the LoadingPlaceholder is shown and causing flickering.
Second time the image is loaded it works.

My question is:
How can I prevent showing LoadingPlaceholder then the image is stored in cache?

**Comment by CSkoubo** [comment]
Could you provide a small sample project and which platforms do you see this issue on?

**Comment by daniel-luberda** [comment]
There are two kind of caches: 

- Disk cache which is responsible for downloading files to the disk
- Memory cache which caches images in memory, so if you use the same image source several times it loads instantly. 

After app restart memory cache is empty and initial loading takes time too (not as much as download, but still). This is the reason you still see a loading placeholder.
