### ISSUE TITLE
What is the cahing strategy in FFImageLoading?

### ISSUE THREAD

**Issue by Motaz-Al-Zoubi** [luberda-molinet/FFImageLoading#657]
Let's say that I have two instances of CachedImage in different classes that are loading the same image from the Disk (same uri).
and let's say that the first instance loads the the image before creating the second instance,
so the first instance will load the image and cache it.
when creating the second instance does it take the image from cache or it loads the image from disk and cache it again.

in simple words, is the caching performed per CachedImage Instance or per some other service provided by FFImageLoading Library

**Comment by daniel-luberda** [comment]
- If there are multiple request for same file, only one loading is done, all others just wait for first loading result. 
- Caching is implemented globally (not per instance), you have a disk cache (for storing downloaded images) and memory cache for already loaded images which reside in device memory (RAM).
