### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by Manu404** [luberda-molinet/FFImageLoading#659]
Hi,

First, well done for the great work !

I need to manage the cache and invalidate certain items in my cache.

I try to find where is the key built, but can't find in the code.

Could you help me ?

**Comment by EmmanVazz** [comment]
This might help. https://github.com/luberda-molinet/FFImageLoading/issues/385

**Comment by daniel-luberda** [comment]
Exactly. Thanks @EmmanVazz once again.
