### ISSUE TITLE
SVG Not Rendering

### ISSUE THREAD

**Issue by Lavinski** [luberda-molinet/FFImageLoading#660]
I'm using `Xamarin.FFImageLoading.Svg.Forms` version `2.2.10-pre-408` to try and render an SVG image. However, cannot see anything, it appears completely transparent (or not drawn at all) but seems to take up height inside the StackPannel.

My setup is in C#, using ` SvgCachedImage`.

```
new SvgCachedImage() {
        Source = ImageSource.FromUri(new Uri("https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg"))
    },
```

I'm also calling init like so
```
Xamarin.Forms.Forms.Init(this, bundle);
CachedImageRenderer.Init();
```

Packages
```
    "Xamarin.FFImageLoading": "2.2.10-pre-408",
    "Xamarin.FFImageLoading.Forms": "2.2.10-pre-408",
    "Xamarin.FFImageLoading.Svg": "2.2.10-pre-408",
    "Xamarin.FFImageLoading.Svg.Forms": "2.2.10-pre-408",
    "Xamarin.Forms": "2.3.4.247"
```

**Comment by quakeulf** [comment]
Check the error log. It's very finicky with how the SVG-syntax is.

Can you post the SVG-code you're trying to render here?

**Comment by daniel-luberda** [comment]
I strongly advice you to use this: https://jakearchibald.github.io/svgomg/ (it can really solve a lot of svg files loading issues).

It's even mentioned on our SVG Wiki page.
