### ISSUE TITLE
Error in Xamarin Forms Previewer

### ISSUE THREAD

**Issue by Lavinski** [luberda-molinet/FFImageLoading#661]
![image](https://user-images.githubusercontent.com/1761789/27989952-517b63c0-648a-11e7-8bd3-03b7d1b9e8d3.png)

**Comment by vlkam** [comment]
I have same problem too unfortunately

**Comment by ahmedelashkerpersonal** [comment]
Same issue here

**Comment by daniel-luberda** [comment]
Did you try the newest prerelease? It was fixed.

**Comment by ahmedelashkerpersonal** [comment]
I last tried at the time I posted my comment. If you have made a new release since that time then I still haven't tried it. Will take a look if so.
