### ISSUE TITLE
InvalidateMemoryCache blocking on iOS.

### ISSUE THREAD

**Issue by fschwiet** [luberda-molinet/FFImageLoading#662]
I am using the Xamarin API and am runnining into an issue when I call FFImageLoading.ImageService.Instance.InvalidateMemoryCache().  The call is just blocking indefinitely.  It is being called from the UI thread.  It repros on iOS but not android.

I am using FFImageLoading v2.2.9.  It repros on physical devices (I am using an iPhone SE and someone on my team saw it on some other iPhones) but the issue is not repro'ing in the simulator (I tried about 6-7 simulators today, mostly on iOS 10.3 but also 8.1 and 9.0).  We are on Xamarin.Forms.2.3.3.193.

There might be something special about our app that is causing this issue, but I don't know what that is to isolate the issue.

I can work around this issue by just not invalidating the memory cache.  We have loaded some PNG images from disk that we won't need anymore- I wonder if I don't clear the cache will those images stay in memory for the lifetime of the app?

**Comment by daniel-luberda** [comment]
Did you try the newest prerelease if it's fixed?

> I can work around this issue by just not invalidating the memory cache. We have loaded some PNG images from disk that we won't need anymore- I wonder if I don't clear the cache will those images stay in memory for the lifetime of the app?

No, it will be removed automatically after some time (when not used or cache filled)
