### ISSUE TITLE
Xamarin.iOS: Unable to locate assembly 'FFImageLoading.Svg.Forms' (culture: '')

### ISSUE THREAD

**Issue by wenyonk** [luberda-molinet/FFImageLoading#663]
Xamarin Forms Project, App compiles and gets deployed, crashed with the following error:
Xamarin.iOS: Unable to locate assembly 'FFImageLoading.Svg.Forms' (culture: '')

Required Permissions??

Android does not crash
Android DEBUG
Min Android APL Level 21
Android Target APL 25
Shared Mono Runtime, No Linking, All ABI's checked, NO AOT, AndroidClientHandler and Native TLS 1.2+

iOS DEBUG
Default SDK
Deployment Target 9.2, Device Family Universal
Link Behavior Link Framework SDK's Only, ARMv7+ARM64, NSURL (iOS 7+), 
 
I have cleaned the solution, deleted / uninstalled the app from the devices, and deleted all the bin and obj folders.

in ContentPage.xaml:
...
xmlns:ffImageLoading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
    xmlns:ffImageLoadingSvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
	xmlns:ffTransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
...
```
<ContentPage.Resources>
        <ResourceDictionary>
            <ffImageLoadingSvg:SvgImageSourceConverter x:Key="SvgImageSourceConverter"/>
        </ResourceDictionary>
    </ContentPage.Resources>
```
...
<ffImageLoadingSvg:SvgCachedImage x:Name="MenuIconImage"
	AbsoluteLayout.LayoutBounds="0.6,0.5,0.6,0.6" 
	AbsoluteLayout.LayoutFlags="SizeProportional,PositionProportional"
        Aspect="AspectFill"
        DownsampleToViewSize="true"
	HeightRequest="15"
	WidthRequest="15" 
        Source="{Binding MenuIcon, Converter={StaticResource SvgImageSourceConverter}}" />

In ContentPage.xaml.cs
using Business.Common.ViewModels;
using Xamarin.Forms;
...
Not other FFImage code 

_Packages Include:
In Shared:
```
<package id="SkiaSharp" version="1.58.1" targetFramework="portable45-net45+win8+wp8" />
<package id="Xamarin.FFImageLoading" version="2.2.10-pre-408" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.10-pre-408" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xamarin.FFImageLoading.Svg" version="2.2.10-pre-408" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xamarin.FFImageLoading.Svg.Forms" version="2.2.10-pre-408" targetFramework="portable45-net45+win8+wp8" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.10-pre-408" targetFramework="portable45-net45+win8+wp8" />
<package id="Xamarin.Forms" version="2.3.4.247" targetFramework="portable45-net45+win8+wp8" />
```

In iOS:
```
<package id="SkiaSharp" version="1.58.1" targetFramework="xamarinios10" />
<package id="Xamarin.FFImageLoading" version="2.2.10-pre-408" targetFramework="xamarinios10" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.10-pre-408" targetFramework="xamarinios10" />
<package id="WebP.Touch" version="1.0.3" targetFramework="xamarinios10" />
  <package id="Xamarin.FFImageLoading.Svg" version="2.2.10-pre-408" targetFramework="xamarinios10" />
  <package id="Xamarin.FFImageLoading.Svg.Forms" version="2.2.10-pre-408" targetFramework="xamarinios10" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.10-pre-408" targetFramework="xamarinios10" />
<package id="Xamarin.Forms" version="2.3.4.247" targetFramework="xamarinios10" />
```

```
In Android:
```
```
<package id="SkiaSharp" version="1.58.1" targetFramework="monoandroid71" />
<package id="Xamarin.FFImageLoading" version="2.2.10-pre-408" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.10-pre-408" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading.Svg" version="2.2.10-pre-408" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading.Svg.Forms" version="2.2.10-pre-408" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.10-pre-408" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.247" targetFramework="monoandroid71" />
```_
```

**Comment by daniel-luberda** [comment]
It's a Xamarin's linking issue: https://developer.xamarin.com/guides/ios/advanced_topics/linker/

You can whitelist the assembly or reference it somewhere in code  (not xaml) to prevent linking.

**Comment by P1T4G0R4S** [comment]
Hello!
Same bug with another dll. Which is the issue with the linker? the docs aren't clear enough :(

**Comment by helzgate** [comment]
@daniel-luberda  Can we have a solid solution to this?   [Here](https://github.com/helzgate/XamStart) is a small example project having the issue.  I tried your suggestions and they aren't working.

Thanks!

**Comment by helzgate** [comment]
I was trying to use a local SVG from a string source in xaml [see this example](https://github.com/helzgate/XamStart) for how I'm using it.  

I tried disabling linking, I tried white listing with `linkskip` directives but nothing was working.  The only thing that worked for me was doing like daniel said and adding this to my app.xaml.cs

    public App ()
    {
	    InitializeComponent();
        var x = new SvgImageSourceConverter();
        // other stuff
    }
