### ISSUE TITLE
SVG Polygon Points

### ISSUE THREAD

**Issue by PCDK** [luberda-molinet/FFImageLoading#666]
When loading points of a polygon the api is expecting the format to look like this:
point="10.33,11.55 12.33,55 0,0"
But in the SVG format you do not need the commas. So something like the following should also be supported:
point="10.33 11.55 12.33 55 0 0"
This however fails with the current api. It can be fixed by changing the method `ReadPolyPath` to something like the following:
```
private SKPath ReadPolyPath(string pointsData, bool closePath)
{
    var path = new SKPath();
    var temp = pointsData.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
    List<string> points = new List<string>();
    foreach (var item in temp)
        foreach (var p in item.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries))
            points.Add(p);

    float x = 0, y = 0;

    for (int i = 0; i < points.Count; i++)
    {
        var point = points[i];

        if (i % 2 == 0)
        {
            x = ReadNumber(point);
            continue;
        }
        else
            y = ReadNumber(point);

        if (i == 0)
            path.MoveTo(x, y);
        else
            path.LineTo(x, y);
    }
    if (closePath)
        path.Close();
    return path;
}
```

**Comment by quakeulf** [comment]
This works with the path's d-attribute:

`<path d="M0,0v-23.8H380.4c-0.7-103.8-37.3-200.6-37.3-200.6s-8.5,0-22.1,0C369.7,223,341.4,465,341.4,465h22.1 c0,0,11.4-89.5,15.8-191h210.2l11.9,191h22.1c0,0-5.3-96.6-0.6-205.7H638.9z" />`

**Comment by daniel-luberda** [comment]
I strongly advice you to use this: https://jakearchibald.github.io/svgomg/ (it can really solve a lot of svg files loading issues).

It's even mentioned on our SVG Wiki page.
