### ISSUE TITLE
Allow for specifying cache folder on Windows SimpleDiskCache

### ISSUE THREAD

**Issue by paulanthonymorris** [luberda-molinet/FFImageLoading#667]
Looks like the SimpleDiskCache for Windows [here](https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Windows/Cache/SimpleDiskCache.cs) does not allow specifying the cache folder. Even if I extend it and override the Init method, the cacheFolder is private so I can't get to it. I have a business reason not to use the Application.Data.TemporaryFolder on Windows so it would be best if I could have the option to set the cache folder location, like you can with the Shared SimpleDiskCache [here](https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Shared/Cache/SimpleDiskCache.cs). Does this seem reasonable?

Perhaps something as simple as:

```
public SimpleDiskCache(StorageFolder rootFolder, string cacheFolderName, Configuration configuration)
{
    initTask = Init(); // Inside Init() we could start from rootFolder and create/open the folder of the given name
}
```
Then do this to construct on Windows:

```
new SimpleDiskCache(ApplicationData.Current.LocalFolder, "MyCache", new MyConfiguration());
```

**Comment by mattrichnz** [comment]
This indeed would be incredibly useful.

**Comment by daniel-luberda** [comment]
Thanks to @paulanthonymorris we have it implemented. Thanks
