### ISSUE TITLE
Color Problem

### ISSUE THREAD

**Issue by Nuada26** [luberda-molinet/FFImageLoading#669]
Hi,

 I have problem with one SVG , this is my code : 
`
<ffimageloadingsvg:SvgCachedImage x:Name="bluetoothconnectioninfo" Aspect="Fill" Source="resource://Mu.Resources.Drawables.Bluetooth.bluetoothyellow.svg"/>`

It's ok image was here but not with correctly color. He's black not yellow.

But when i go on this website for test : 

[Svg previewer](When i go on http://petercollingridge.appspot.com/svg-editor/)

He works correctly.

this is my code of SVG : 
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 57 57" style="enable-background:new 0 0 57 57;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#A8990B;}
</style>
<g>
	<polygon class="st0" points="29.5,43.4 35.1,37 29.5,31.1 	"/>
	<polygon class="st0" points="29.5,13.4 29.5,25.4 35.1,19 	"/>
	<path class="st0" d="M28.5,0c-9.9,0-18,8.1-18,18v21c0,9.9,8.1,18,18,18s18-8.1,18-18V18C46.5,8.1,38.4,0,28.5,0z M37.9,37
		L27.5,48.6l0-18.4l-8.4,7.5l-1.3-1.5l9.2-8.2l-9.2-8.3l1.3-1.5l8.3,7.5l0-17.2L37.9,19l-8.3,9.3L37.9,37z"/>
</g>
</svg>
```

Do u have an idea ?

**Comment by quakeulf** [comment]
Is that all the code for the SVG?

When setting fill you need the "#" when setting hex-values. I don't know how it interprets CSS so you could rather try putting it in the shape you want directly, as in:

`<circle id="testircle" cx="128" cy="128" r="128" fill="A8990B" />`

**Comment by Nuada26** [comment]
No sorry i have an error when i copy/paste my code of svg is that : 

`<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 57 57" style="enable-background:new 0 0 57 57;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#A8990B;}
</style>
<g>
	<polygon class="st0" points="29.5,43.4 35.1,37 29.5,31.1 	"/>
	<polygon class="st0" points="29.5,13.4 29.5,25.4 35.1,19 	"/>
	<path class="st0" d="M28.5,0c-9.9,0-18,8.1-18,18v21c0,9.9,8.1,18,18,18s18-8.1,18-18V18C46.5,8.1,38.4,0,28.5,0z M37.9,37
		L27.5,48.6l0-18.4l-8.4,7.5l-1.3-1.5l9.2-8.2l-9.2-8.3l1.3-1.5l8.3,7.5l0-17.2L37.9,19l-8.3,9.3L37.9,37z"/>
</g>
</svg>
`

**Comment by quakeulf** [comment]
It could be that the style type has issues. Attempt this instead:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 57 57" style="enable-background:new 0 0 57 57;" xml:space="preserve">
<g>
	<polygon class="st0" points="29.5,43.4 35.1,37 29.5,31.1" fill="#A8990B" />
	<polygon class="st0" points="29.5,13.4 29.5,25.4 35.1,19" fill="#A8990B" />
	<path class="st0" d="M28.5,0c-9.9,0-18,8.1-18,18v21c0,9.9,8.1,18,18,18s18-8.1,18-18V18C46.5,8.1,38.4,0,28.5,0z M37.9,37
		L27.5,48.6l0-18.4l-8.4,7.5l-1.3-1.5l9.2-8.2l-9.2-8.3l1.3-1.5l8.3,7.5l0-17.2L37.9,19l-8.3,9.3L37.9,37z" fill="#A8990B"/>
</g>
</svg>
```

**Comment by Nuada26** [comment]
Ok it's works ! Thanks !

**Comment by daniel-luberda** [comment]
I strongly advice you to use this: https://jakearchibald.github.io/svgomg/  (it can really solve a lot of svg files loading issues).

It's even mentioned on our SVG Wiki page.
