### ISSUE TITLE
Border and borderColor

### ISSUE THREAD

**Issue by angelru** [luberda-molinet/FFImageLoading#670]
Hello,

How to added BorderColor and BorderThickness in XAML with CircleTransformation?

**Comment by daniel-luberda** [comment]
There are properties for that: 

```XML
<fftransformations:CircleTransformation BorderColor="#FFFFFF" BorderWidth="5"/>
```

**Comment by ndastur** [comment]
For anyone that comes to this question via Google. It's now
```BorderHexColor="#FFFFFF" BorderSize="1```

**Comment by stesvis** [comment]
How do you set a border for a regular `CachedImage` that does **not** require a `CircleTransformation`?

**Comment by Raystorm7** [comment]
> How do you set a border for a regular `CachedImage` that does **not** require a `CircleTransformation`?

Hi @stesvis 
I have solved with this code:
```
<ffimage:CachedImage.Transformations>
    <fftrans:RoundedTransformation BorderHexColor="#000000" BorderSize="5" Radius="-1" CropHeightRatio="0" CropWidthRatio="0" />
</ffimage:CachedImage.Transformations>
```
Have a nice day! 😄
