### ISSUE TITLE
how can i achieve this transformation?

### ISSUE THREAD

**Issue by pdaniel-frk** [luberda-molinet/FFImageLoading#671]
Hello,

I need to create this transformation. Can someone tell me how can this be done using this great library?

<img width="385" alt="screen shot 2017-07-24 at 02 19 05" src="https://user-images.githubusercontent.com/10430333/28503924-63cfe332-7017-11e7-9831-bb9a4476d52a.png">

**Comment by daniel-luberda** [comment]
What you need is this: https://github.com/luberda-molinet/FFImageLoading/wiki/Transformations-Guide#cornerstransformation
