### ISSUE TITLE
Getting notified when image download process is completed

### ISSUE THREAD

**Issue by peppe130** [luberda-molinet/FFImageLoading#674]
Hi,

could you implement in your library some Events so that a developer can subscribe to an Event and get notified when an operation is completed? For example, in my App, I would start an animation when the image download is finished but there is no event fired for that. Any solution? Thanks in advace

**Comment by EmmanVazz** [comment]
There is the [success event](https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#success) and a [download progress event](https://github.com/luberda-molinet/FFImageLoading/issues/412#issuecomment-268791954).

**Comment by daniel-luberda** [comment]
Exactly as @EmmanVazz wrote (thanks).
