### ISSUE TITLE
[SVG] Does masking, <mask> and <clipPath> work?

### ISSUE THREAD

**Issue by quakeulf** [luberda-molinet/FFImageLoading#675]
Hi,
I am attempting to implement masking of my SVG-paths but so far the masks do not show up through ffimageloading:svg:SvgCachedImage but the SVG-output is correct and works when I try it in my browser or any online SVG-viewers/editors.

The masks I use are defined in <defs> and use a <path> to define up the masked area, then linked to using url(#mask) in the path elsewhere in the code.

Thank you very much in advance for helping out.

**Comment by daniel-luberda** [comment]
Current parser is a really simple one (any collaboration is appreciated). You can use this: https://jakearchibald.github.io/svgomg/ and see id it would work. 


Parser code is here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SkSvg.cs

**Comment by quakeulf** [comment]
Thank you for this. However, the mask works in SVGOMG but not in the app through FFImageLoading. I have not altered the code in any way with regards to the <mask>, <defs>, mask-url and "d"-attributes.

Here's the SVG-code for the test I did that works when shown in SVGOMG but not through FFImageLoading in the app:

```
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1" baseProfile="tiny" width="787.829956054688" height="816.289978027344" xmlns="http://www.w3.org/2000/svg">
  <circle id="templateCircle" cx="393.914978027344" cy="408.144989013672" r="393.914978027344" fill="#EDED91" visibility="visible" />
  <g transform="translate(-1018.28002929688 -438.059997558594) rotate(-7.56 1412.19500732422 846.204986572266)">
    <path id="leftEye" transform="translate(0 0) rotate(0 0 0) scale(1 1) skewX(0) skewY(0)" d="M1157.94995117188 609.119995117188  Q1193.71997070313 590.640014648438 1221.69995117188 580.549987792969 1244.92004394531 591.169982910156 1283.19995117188 614.200012207031 1242.36999511719 623.830017089844 1220.56005859375 624.669982910156 1192.41003417969 622.909973144531 1157.94995117188 609.119995117188z" fill="#ffffff" stroke="none" stroke-width="" stroke-linecap="" stroke-linejoin="" stroke-dasharray="" />
    <circle id="leftEyeIris" cx="1220.68005371094" cy="600.559997558594" r="33.0899963378906" fill="#767629" mask="url(#leftEyeMask)" />
  </g>
  <defs>
    <mask id="leftEyeMask">
      <path d="M1157.94995117188 609.119995117188  Q1193.71997070313 590.640014648438 1221.69995117188 580.549987792969 1244.92004394531 591.169982910156 1283.19995117188 614.200012207031 1242.36999511719 623.830017089844 1220.56005859375 624.669982910156 1192.41003417969 622.909973144531 1157.94995117188 609.119995117188z" fill="#ffffff" />
    </mask>
  </defs>
</svg>
```
