### ISSUE TITLE
Wrong image is cached when a new image is uploaded

### ISSUE THREAD

**Issue by drunkendaddy** [luberda-molinet/FFImageLoading#676]
Thank you for this awesome library.

I've a problem that wrong image is showing from cache when a new row is added to the tableview in iOS. Initially I've a ViewController with TableView whose cells contain images. From there I go the new ViewController, to upload a new image. After uploading, I go back to the previous ViewController by navigationController.popViewController(); and refresh the tableview. Now the first image loads correctly which is the newly uploaded one. But after showing the first image(new uploaded one), the ImageView in the second or third row shows the same image as the newly uploaded one. If I scroll down and come back up, it shows the correct image.

I tried versions 2.6, 2.7, 2.8, 2.9, latest 2.10 pre release as of now. It all has this issue.

**Comment by daniel-luberda** [comment]
If you want to reload images, you should set ImageView image source to null, then reapply previous source, it will load a new picture.

**Comment by drunkendaddy** [comment]
It tried setting the my imageView.Image = null. It did not solve the problem
