### ISSUE TITLE
IMD5Helper refactor?

### ISSUE THREAD

**Issue by paulanthonymorris** [luberda-molinet/FFImageLoading#677]
I would like to open a discussion for a possible change to semantics for the MD5Helper. Here is why:
I have an app that already contains a data store of images along with their SHA-256 hash signatures. I do not control this data it comes from a service. I need to use this SHA-256 signature to key my cached images so that later I can compare the ImageLoaderCache files with the data from my service. So I do not want to hash either the stream or the cache key. Here is what I end up doing in code:

`public class CustomSignatureHelper : IMD5Helper`
`{`
`    public string MD5(string input)`
`    {`
`        return input;`
`    }`
`    etc...`

This is fine but the problem is the whole thing is obfuscated due to the existing semantics. This class is not really an MD5Helper at all. 

So my proposal is this:

Can we deprecate the IMD5Helper interface in favor of a new interface like this?

`public interface ISignatureHelper`
`{`
`string GenerateSignature(string input);`
`string GenerateSignature(Stream input);`
`}`

We would also deprecate the existing MD5Helper, copy it to an new class which implements the new interface and then users of the API can just use this more generic interface to generate any class with rules to affect the file name chosen for what is left of the dot. So, the filename would be like this:

`[whatever the user wants].[the long representing the expiration time span]`

I'm open to suggestions for better naming, etc. but I need to get a feel for whether the main devs for this project are interested in this work.

**Comment by EmmanVazz** [comment]
Have you tried using [custom cache keys](https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced#custom-cache-keys)?

**Comment by paulanthonymorris** [comment]
@EmmanVazz yes I am using a custom cache key but the default behavior appears to be to take that custom key and hash it with the MD5Helper which is no good for my use case. My key is already a hash.

**Comment by EmmanVazz** [comment]
Can you not retrieve your image with your custom key?

**Comment by paulanthonymorris** [comment]
Yes. So to be clear, I've got it to work. My question is about whether some changes to naming might give better driving directions to users of the API. Not every user will want their key to be MD5 hashed but even when using a custom cache key factory, the key gets processed by an "MD5Helper". I think the class that processes the keys should be named something more generic. Does that make sense?

**Comment by molinch** [comment]
@paulanthonymorris Could you propose a PR with what you mean?

**Comment by daniel-luberda** [comment]
@paulanthonymorris That's a really nice idea, we could implement add that interface, but it's an entirely different use-case. Currently, `IMD5Helper` is only used in disk cache implementation, it allows shortening cache keys (hashing them) to have a safe filenames. IMO it should be done internally in disk cache implementation. Somehow in the current code base it's not, and disk cache methods must be used with cache key generated from `IMD5Helper` class.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/859
