### ISSUE TITLE
Throwing Exception in Windows Phone 8.1 

### ISSUE THREAD

**Issue by dkavuri** [luberda-molinet/FFImageLoading#679]
Hello, Daniel Luberda

I got an exception in windows phone 8.1 platform that is 

An exception of type 'System.TypeInitializationException' occurred in FFImageLoading.Forms.DLL but was not handled in user code

Additional information: The type initializer for 'FFImageLoading.Forms.CachedImage' threw an exception.

could you help me to implement in Windows platform?

Thanks in advance.

**Comment by daniel-luberda** [comment]
I'll need more details to help.

**Comment by dkavuri** [comment]
Hi, Daniel

I have downloaded the  FFImageLoading.Forms from NuGet, on Android, iOS, Windows Phone and Xamarin Forms Shared Project , but it doesn't works on Windows Phone 8.1.

I am trying use CachedImage in xaml.cs file in Xamarin(Windows Phone 8.1). tried in both ways such as
     1. created one **CachedImageRenderer** in windows phone platform and that inherits from 
        **ImageRenderer** then I am getting exception like this FFImageLoading.Forms.DLL was not found.
    
     2. var assembliesToInclude = new List<Assembly>()
          {
              typeof(CachedImage).GetTypeInfo().Assembly,
              typeof(CachedImageRenderer).GetTypeInfo().Assembly            
          };           
       I have added this code in **App.xaml.cs** , then I got error like this

      An exception of type 'System.TypeInitializationException' occurred in FFImageLoading.Forms.DLL but 
     was not handled in user code

    Additional information: The type initializer for 'FFImageLoading.Forms.CachedImage' threw an 
    exception.

Is it works for windows  ?.  if it works then how to resolve the issue.

Thanks

**Comment by daniel-luberda** [comment]
You can check our sample project which works fine, see this: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/WinUWP/App.xaml.cs#L66-L68

Please reopen if it won't work for you.
