### ISSUE TITLE
WebP on iOS - vp8 status error for some files

### ISSUE THREAD

**Issue by procopio** [luberda-molinet/FFImageLoading#682]
Hi,

I'm trying to use CachedImage inside a ViewCell to open WEBP. 
On iOS some lines don't open the image and output log pops an error "vp8 status error opening".
I tried to config ImageService with MaxParallesTasks = 1, but no lucky.
I tested only Webp.Touch decode and it give me the same error.

Please, could you help me here?

Thanks,
procopio

**Comment by daniel-luberda** [comment]
It's possible we need to update Webp.Touch project to use the newest webp lib  version. (http://downloads.webmproject.org/releases/webp/index.html)

**Comment by daniel-luberda** [comment]
@procopio  Did new 1.0.4 Webp package solved it for you?

**Comment by daniel-luberda** [comment]
@procopio Could you attach some example files which are not working? I'll try to debug it.

**Comment by procopio** [comment]
Hi @daniel-luberda  thanks a lot! 
You can download it here: http://dropcanvas.com/i8h5r

**Comment by daniel-luberda** [comment]
Those files load fine for me. See this: 

![simulator screen shot 4 sep 2017 21 48 50](https://user-images.githubusercontent.com/13569983/30037427-ea5ba9e4-91ba-11e7-9daa-c513d0efb3c6.png)

**Comment by procopio** [comment]
Hi @daniel-luberda, 
One isolated image works, the problem is with a listview and inside the viewcell there is a ffimageloading.
I believe the problem is when you try to load many webp at same time.
If you could try it I appreciate!
Thanks alot,
Joao

**Comment by daniel-luberda** [comment]
Could you test the newest prerelease nuget? (2.2.11)

**Comment by procopio** [comment]
Hi Daniel, 
I tried with 2.2.11pre486 but the erro still there. :(
This is how my listview looks when loading:

![fullsizeoutput_2](https://user-images.githubusercontent.com/418238/30103420-e8eedef8-92f2-11e7-87f2-141dfb0fedeb.jpeg)
![fullsizeoutput_4](https://user-images.githubusercontent.com/418238/30103419-e8ebfa80-92f2-11e7-87a9-23df3355dc64.jpeg)

**Comment by daniel-luberda** [comment]
I won't be able to help you without reproduction. Can you do that?

**Comment by procopio** [comment]
Yes sure.
just give some time to build a project. 
I get back to you soon. 
Tks!

**Comment by daniel-luberda** [comment]
@procopio Any news?

**Comment by procopio** [comment]
Not yet, i just launched my app using PNG. I realy out of time, but I will create a project to test this issue.

**Comment by daniel-luberda** [comment]
Please reopen if you have a repro. Thanks
