### ISSUE TITLE
Making the LoadingPlaceholder size dynamic

### ISSUE THREAD

**Issue by bordline23** [luberda-molinet/FFImageLoading#684]
Hi,
I have this code in Android:
`FFImageLoading.ImageService.Instance.LoadUrl(message.ImageUrl).LoadingPlaceholder("frame_placeholder", FFImageLoading.Work.ImageSource.CompiledResource).DownSample(height: 200).Transform(new FFImageLoading.Transformations.RoundedTransformation(20, 0, 0)).Into(cell);`

Is it possible to create a dynamic sized placeholder? Given the size of the original image is known beforehand, I would like to have a placeholder with similar size when the actual image loads.

**Comment by daniel-luberda** [comment]
I would just use SVG file.
