### ISSUE TITLE
Any documentation for gif usage?

### ISSUE THREAD

**Issue by trashCoder555** [luberda-molinet/FFImageLoading#685]
I was looking in the Internet for examples, but didn't find one.

How to use gif in Xamarin iOS?

**Comment by jj09** [comment]
+1

**Comment by trashCoder555** [comment]
up

**Comment by daniel-luberda** [comment]
What do you want to know? Currently, GIF support is super easy, you don't need to worry about anything as it works out of the box. Only Android/iOS are now supported. You can disable GIF support with custom configuration (after that GIFS will be just static).

**Comment by jj09** [comment]
E.g., how do you load gif into UIImageView?

**Comment by trashCoder555** [comment]
yes, simple short example

**Comment by daniel-luberda** [comment]
> E.g., how do you load gif into UIImageView?

Just the same as any other image:

```C#
ImageService.LoadUrl("http://domain.com/image.gif")
  .Into(_imageView);
```

You just don't need to worry about anything, gifs are handled automatically. You can also disable gif support with a custom configuration (`AnimateGifs=false)

**Comment by trashCoder555** [comment]
Thanks

**Comment by JFMG** [comment]
Dear @daniel-luberda,
I got an animated gif image which is non looping (works in my browser) but when I use it with FFImageLoading the looping is infinite. Is there any way to loop only once?

**Comment by daniel-luberda** [comment]
@JFMG It's not implemented yet, see: https://github.com/luberda-molinet/FFImageLoading/issues/859

**Comment by JFMG** [comment]
Thanks!
