### ISSUE TITLE
how to use the allowUpscale?

### ISSUE THREAD

**Issue by bordline23** [luberda-molinet/FFImageLoading#687]
@daniel-luberda/@Shaddix, how to use the allowUpscale? I have a 50x50 image and the image is not upscaled at all when loading it into view.

In iOS I have the following code:
`FFImageLoading.ImageService.Instance.LoadUrl(uri).DownSample(height: 200, allowUpscale: true).Into(imageView);`

I expected the image to be stretched to 200x200. I tried debugging the success handler to confirm the Imageinformation CurrentWidth/CurrentHeight is the same with OriginalWidth/OriginalHeight.

My best guess is this line of code from `NSDataExtenstions.ToImage` method:

```
int maxPixelSize = (int)Math.Max(
					Math.Min(sourceSize.Width, targetPixelSize.Width),
					Math.Min(sourceSize.Height, targetPixelSize.Height)
				);
```

That would make the maxPixelSize of 50x50 instead of 200x200.

**Comment by bordline23** [comment]
After testing, it doesn't seem to affect the size by adjusting the maxPizelSize. Did I understand the allUpscale flag correct ?

**Comment by daniel-luberda** [comment]
@bordline23 It was an iOS bug, should be fixed now.
