### ISSUE TITLE
Garbage Collector issue on Finalizers

### ISSUE THREAD

**Issue by Peppegio** [luberda-molinet/FFImageLoading#689]
Hi!
I am using CarouselViewControl with FFImageLoading.
Sometimes, when I scroll fast through the pages (there are also more than 1000 pages), the application deadlocks in GC.WaitForPendingFinalizers method called from inside FF library.
I use a Cancellation token to cancel the loading of the pages to make the app faster.
Any idea?

**Comment by daniel-luberda** [comment]
Could you test the newest prerelease? (2.2.10.428)
