### ISSUE TITLE
ffimageloading:CachedImage losing proportions with ffimageloading:CachedImage.Transformations

### ISSUE THREAD

**Issue by ArtemKumeisha** [luberda-molinet/FFImageLoading#690]
I found the problem: When i used 
<ffimageloading:CachedImage x:Name="ItemImage"
								LoadingPlaceholder="icon.png" 
                                                                ErrorPlaceholder="error.png" 
                                                                DownsampleToViewSize="true"
								Aspect="Fill" >
</ffimageloading:CachedImage>
 view proportions normal 
![screen shot 2017-08-11 at 5 12 22 pm](https://user-images.githubusercontent.com/14937355/29216936-e519c3ea-7eb8-11e7-9892-2c10b13abd67.png). But when i added 
<ffimageloading:CachedImage x:Name="ItemImage"
								LoadingPlaceholder="icon.png" ErrorPlaceholder="error.png" 
                                                                DownsampleToViewSize="true"
								Aspect="Fill" >
								<ffimageloading:CachedImage.Transformations>
									<fftransformations:RoundedTransformation Radius="1"/>
								</ffimageloading:CachedImage.Transformations>
</ffimageloading:CachedImage>
 image in View lost proportions
![screen shot 2017-08-11 at 5 19 54 pm](https://user-images.githubusercontent.com/14937355/29217076-575e0380-7eb9-11e7-966f-73cac3c475a6.png)
Thanks!!

**Comment by daniel-luberda** [comment]
Rounded transformation is designed in such way, that it always changes picture aspect ratio (1:1 by default). You can control it by using `RoundedTransformation` `AspectWidthRatio` and `AspectHeightRatio` properties.

**Comment by ArtemKumeisha** [comment]
Thanks! CropWidthRatio/CropHeightRatio properties resolved problem.
