### ISSUE TITLE
Loading issue from a https url

### ISSUE THREAD

**Issue by dragmawanderer** [luberda-molinet/FFImageLoading#694]
I cannot seem to load from a https url such as:
https://m.rebrickable.com/media/sets/21306-1.jpg

**Comment by daniel-luberda** [comment]
Works fine for me. Please provide more info & then I'll reopen. 

![simulator screen shot 17 aug 2017 13 03 17](https://user-images.githubusercontent.com/13569983/29409480-ab4283da-834c-11e7-85ae-20e43f17f2b3.png)
