### ISSUE TITLE
Xamarin.Forms / crash on Android

### ISSUE THREAD

**Issue by nilsE** [luberda-molinet/FFImageLoading#695]
Xamarin.Forms.iOS is fine, but a simple CachedImage view crashes on Android (tested on API 22 and 23, FFImageLoading + Forms 2.2.10-pre-433) with 

`Method 'FFImageLoading.Work.TaskParameter.DownSampleInDip' not found.`

CachedImageRenderer.Init(); is done in MainActivity.cs, there is no linking, but "multi dex" (issues with Xamarin.Firebase - can't disable this).

Do you have any idea?

Thanks,
Nils

**Comment by daniel-luberda** [comment]
From my experience you should be good to go after:

- ensuring all packages are in the same version (in every project)
- deleting all `obj` & `bin` folders.

**Comment by nilsE** [comment]
thanks, i cleaned & built again and pressed some unknown magic keys ;-) but now it's working!
