### ISSUE TITLE
CachedImageRenderer.Init(); Does not exist

### ISSUE THREAD

**Issue by AlmondMedia** [luberda-molinet/FFImageLoading#697]
CachedImageRenderer.Init(); 
Does not exist, did you by any chance stop using this and haven't updated the documentation or am I missing something?

I installed it via nugget. I can see the namespace and all the other classes but there isn't any class called 
`CachedImageRenderer`.  

I'm using Xamarin forms to develop for android

**Solved**
You may have to manually add the namespace 
`FFImageLoading.Forms.Droid.CachedImageRenderer.Init();`

Visual Studio Fails to fix/ add the using automatically

**Comment by marcosanfilippo** [comment]
Hi, I can't use your solution. How did you installed it?

I installed via NuGet the FFImageLoading.Forms to all projects (PCL)
