### ISSUE TITLE
[Android] Image is downloaded each time the App is launched

### ISSUE THREAD

**Issue by peppe130** [luberda-molinet/FFImageLoading#700]
FFImageLoading version: 2.2.9
Visual Studio version: 15.3.2
Xamarin version: 4.6.0.299
Xamarin.Android SDK version: 7.4.0.21

Hi,

I'm setting the CachedImage source via URL but I noticed that the image gets downloaded each time I launch the App. It's like the image isn't cached. I think it gets downloaded each time because your plugin takes a few seconds before showing me the image and also because when my device is in airplane mode the image is not shown. Since the default value of **_MaxMemoryCacheSize_** is **_0_**, I tried to create a new configuration for ImageService with that value set to **_500 MB_** but with no luck. Could you help me? Thank you in advance.

**Comment by daniel-luberda** [comment]
- Could you make a reproduction? 
- There is `DownloadStarted` callback. Did you check if it's called twice?

**Comment by peppe130** [comment]
This is the CachedImage istantiated via XAML in the `Portable` solution:
```xml
<ffimageloading:CachedImage x:Name="ProfilePicture" CacheType="All" Aspect="AspectFill" AbsoluteLayout.LayoutFlags="PositionProportional" AbsoluteLayout.LayoutBounds="0.5, 0.5, 100, 100" />
```

Then I set the image `Source` via the controller:
```c#
ProfilePicture.Source = "profile_picture_url";
```

And this is my Android `MainActivity`  class:
```c#
public class MainActivity : FormsAppCompatActivity
{
    protected override void OnCreate(Bundle bundle)
    {
        TabLayoutResource = Resource.Layout.Tabbar;
        ToolbarResource = Resource.Layout.Toolbar;
        base.OnCreate(bundle);
        Forms.Init(this, bundle);
        ImageService.Instance.Initialize(new FFImageLoading.Config.Configuration
        {
            MaxMemoryCacheSize = 524288000,
            BitmapOptimizations = true,
            FadeAnimationEnabled = true,
            FadeAnimationForCachedImages = false,
            FadeAnimationDuration = 300,
            TransformPlaceholders = true,
            DownsampleInterpolationMode = InterpolationMode.Default,
            HttpHeadersTimeout = 10,
            HttpReadTimeout = 30,
            VerbosePerformanceLogging = false,
            VerboseMemoryCacheLogging = false,
            VerboseLoadingCancelledLogging = false,
            VerboseLogging = false,
            SchedulerMaxParallelTasks = Math.Min(4, Math.Max(2, (int)(System.Environment.ProcessorCount / 2d))),
            DiskCacheDuration = TimeSpan.FromDays(30d),
            ExecuteCallbacksOnUIThread = false,
            StreamChecksumsAsKeys = true
        });
        CachedImageRenderer.Init();
        LoadApplication(new App());
    }

    protected override void OnPause()
    {
        base.OnPause();
        ImageService.Instance.SetExitTasksEarly(true);
    }

    protected override void OnResume()
    {
        base.OnResume();
        ImageService.Instance.SetExitTasksEarly(false);
    }

    public override void OnTrimMemory([GeneratedEnum] TrimMemory level)
    {
        ImageService.Instance.InvalidateMemoryCache();
        GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
        base.OnTrimMemory(level);
    }
}
```

There is no `DownloadStarted` callback. I'm not using `ImageService` because the `into()` method is not available in the `Portable` solution.

**Comment by daniel-luberda** [comment]
'OnDownloadStarted'  is available everywhere.  Please try it to confirm if the download is started more then once.

**Comment by peppe130** [comment]
`OnDownloadStarted` callback is called each time the App is launched. I've implemented a counter and I noticed that it always increments.

**Comment by daniel-luberda** [comment]
Is the url always the same? Could you make a sample project?

**Comment by peppe130** [comment]
Yes, the URL is always the same. It's hardcoded. By the way, here you are the sample project: [Dropbox](https://www.dropbox.com/s/s7m0cpegp71ksei/CacheSampleProject.zip?dl=1).

**Comment by daniel-luberda** [comment]
I just noticed that you're using old package version. Please use the newest package (>2.2.10-pre-466), it's fixed.

**Comment by peppe130** [comment]
Yeah, now it works fine. When I created this issue, the latest version was 2.2.9. Thank you man!
