### ISSUE TITLE
CachedImageRenderer.Init(): Cannot import FFImageLoading to platform specific code.

### ISSUE THREAD

**Issue by marcosanfilippo** [luberda-molinet/FFImageLoading#701]
Hi, simply I can't use:

CachedImageRenderer.Init();

To the platform specific code. I'm using Xamarin.Forms and after installing the NuGet package I can't import it to my Droid Project.

**Comment by daniel-luberda** [comment]
See this: https://github.com/luberda-molinet/FFImageLoading/issues/697
