### ISSUE TITLE
Deadlock when scrolling in GridView on Windows 10 mobile.

### ISSUE THREAD

**Issue by sskodje** [luberda-molinet/FFImageLoading#704]
When loading images in a 4 column Gridview, like a photo album, the app deadlocks while scrolling. I have tracked the issue down to [the same discussed here](https://stackoverflow.com/questions/31839003/async-await-deadlock). I have [tested the solution proposed](https://github.com/sskodje/FFImageLoading/commit/167ce01d6cdd587ced9a36c1b7eec3e1b1fed71e), and i have been unable to reproduce the issue when caching the Dispatcher.

**Comment by madcreep** [comment]
We've got the similar issue here. Can the solution proposed be included in a test nuget package? Thanks!

**Comment by daniel-luberda** [comment]
Sure, in a few minutes you shoud have a prerelase nuget with proposed fix.

**Comment by EmilAlipiev** [comment]
Hi @daniel-luberda ,

which pre-release is it? is it included in latest stable 2.2.10?

**Comment by daniel-luberda** [comment]
Hi @EmilAlipiev  Yes
