### ISSUE TITLE
SquareTransformation

### ISSUE THREAD

**Issue by chriszirkel** [luberda-molinet/FFImageLoading#705]
Hello,

I'd like to know if there's already a transformation for cropping rectangle images to a square images? The logic should be simple, just compare height and width and then, crop the bigger side.  The CropTransformation should be a good template for that issue.

I tried to implement it and use the CropTransformation:
https://gist.github.com/chriszirkel/e93c96238806c4fb06758fc37d690288

The CropTransformation has two paramaters cropWidthRatio and cropHeightRatio, but I can't figure out what they are used for.

I calculated the offsetX and offsetY variables as starting point for the cropping, but I would also need  the end point (offsetX + desired width; offsetY + desired height).

Could someone help me to get this work?

**Comment by daniel-luberda** [comment]
Just use `CropTransformation` with `cropWidthRatio=1` and `cropHeightRatio =1` and offsets set to `0`

**Comment by chriszirkel** [comment]
What I want to achieve is to "chop" out a square section of the image. For example, if the source image is 600x400px, I would like to chop out a square image of 400x400px, beginning at offsetX=100 and width=400; offsetY=0 and height=400.

![Chop](https://i.stack.imgur.com/kA8C1.png)

It seems like it is not possible with CropTransformation?

**Comment by daniel-luberda** [comment]
Yes,  you should just use a negative xOffset to achieve what you want

**Comment by chriszirkel** [comment]
I'm not sure if I understand that correctly. A negative xOffset would just crop a part of the image, either the left or the right side? But what should I do if I want to get a square from the middle of the image, so crop 100px from the left and right side?

Maybe you could give me an example?

**Comment by daniel-luberda** [comment]
https://raw.githubusercontent.com/molinch/FFImageLoading/master/samples/Screenshots/Transformations/iOS_CropTransformation.png
