### ISSUE TITLE
Problem with gif (appear stopped)

### ISSUE THREAD

**Issue by mfandre** [luberda-molinet/FFImageLoading#709]
Im trying to use GIF but it appear stopped. I need to do any extra configuration?

This is my xaml:

> <?xml version="1.0" encoding="utf-8" ?>
> <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
>              xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
>              xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
>              xmlns:fftransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
>              x:Class="MagicApp.Metamorphosis">
>     <ContentPage.Content>
>         <ContentView HorizontalOptions="Center" VerticalOptions="Center">
>             <ffimageloading:CachedImage HeightRequest="200" DownsampleHeight="200" Source="http://dogoverflow.com/dRX5G8qK">
>                 <ffimageloading:CachedImage.Transformations>
>                     <fftransformations:CircleTransformation/>
>                 </ffimageloading:CachedImage.Transformations>
>             </ffimageloading:CachedImage>
>         </ContentView>
>     </ContentPage.Content>
> </ContentPage>

**Comment by daniel-luberda** [comment]
@mfandre 

- Which FFImageLoading version?
- Which platform? 

I tested it on both Android / iOS and it works just fine.

**Comment by mfandre** [comment]
Version: 2.2.10
Platform: Android

**Comment by daniel-luberda** [comment]
I checked the file you linked and it's working fine. I'll need some reproduction.

**Comment by mfandre** [comment]
I just install ffimageloading by nuget, create this xaml page. The code behind I dont put anything... When I debug the image appear but without animation...

Im using a smartphone model "One Plus One" with Oxygen OS

**Comment by daniel-luberda** [comment]
I can't help you without a reproduction. Try our sample project and put your url there, you'll see that it works.

**Comment by mfandre** [comment]
Ok I will try to create an project

**Comment by mfandre** [comment]
@daniel-luberda in Debug the gif apper stopped, when I change to release the Gif starts animating... Any clue?

Other thing, its possible to change the source of the gif to another gif... I tried now but the gif doesnt change, it still at the first loaded gif...

**Comment by EmilAlipiev** [comment]
I had same problem and after deleting bin, obj folders, clean, rebuilt project fixes it.

**Comment by mfandre** [comment]
@EmilAlipiev and about "Its possible to set the number of repeats?" you would know if its possible?

**Comment by daniel-luberda** [comment]
Yes, 90% of problems are some old dlls mixing with the new one. Just be sure you have same package version in every project, then delete `obj`/`bin` folders as @EmilAlipiev said.

Currently, all gifs are animated in loop. You can add an issue with feature request.
