### ISSUE TITLE
Acces to path is denied Android 7

### ISSUE THREAD

**Issue by h4rdmol** [luberda-molinet/FFImageLoading#711]
Hi guys,

My app on Android 7.0 is crashing with this error:

Xamarin caused by: android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'FFImageLoading.Forms.CachedImage' threw an exception. ---> System.UnauthorizedAccessException: Access to the path "/data/user/0/com.company.myapp/cache/FFSimpleDiskCache" is denied.
System.IO.Directory.CreateDirectoriesInternal(string path)Directory.cs:111
System.IO.Directory.CreateDirectory(string path)Directory.cs:78
FFImageLoading.Cache.SimpleDiskCache.SimpleDiskCache(string cachePath, Configuration configuration)
FFImageLoading.Cache.SimpleDiskCache.CreateCache(string cacheName, Configuration configuration)
FFImageLoading.ImageService.InitializeIfNeeded(Configuration userDefinedConfig)
FFImageLoading.ImageService.get_Config()
at FFImageLoading.Forms.CachedImage..cctor () [0x00229] in C:\projects\ffimageloading\source\FFImageLoading.Forms\CachedImage.cs:269
--- End of inner exception stack trace ---

I've checked this is working fine on Android 6, but now working proberly Android 7,how can i fix it ?

**Comment by daniel-luberda** [comment]
https://developer.android.com/about/versions/nougat/android-7.0-changes.html#perm

Could you check the newest prerelease (2.2.11.475) if it solves your issue?

**Comment by h4rdmol** [comment]
No, it doesnt solves my issue, applicataion still crashing with same error. 
1. Install 2.2.11.437pre 
2. Deleted bin/obj
3. Cleaned up project
4. Rebuilded and ran on Genymotion S8 emulator

**Comment by daniel-luberda** [comment]
We use standard Android 'cacheDir'  l.  What are your app permissions? Maybe you're missing something. Also you can change path to a custom one via custom config. Did you try that?

**Comment by h4rdmol** [comment]
Here is my config for Android, I am using Debug mode, is it related?
Install location: Prefer Internall
READ_EXTERNAL_STORAGE
WRITE_EXTERNAL_STORAGE

Usage: 
 _cachedImage = new CachedImage
                        {
                            Source = (Attachments.First() as Attachment).Content,            
                            Aspect = Aspect.AspectFill
                        };
How can I change path for it? I have not found in documentation this option.. 
What i am doing wrong ?

**Comment by daniel-luberda** [comment]
It's on our wiki.  ImageService. Instance. Initialize  at app startup.

**Comment by h4rdmol** [comment]
I have changed the default path to a custom one and it helped.   Alos I  have researched some information about Android cache and it seems like there is not option to write into cache directory without root rights, probably it will help to improve lib. 

Thank you a lot, Daniel !
