### ISSUE TITLE
first build FFImageLoading.Forms.Sample and get error Xamvvm.NoPageForPageModelRegisteredException: No Page Registered for Type: FFImageLoading.Forms.Sample.MenuNavigationPageModel

### ISSUE THREAD

**Issue by Cheunglik** [luberda-molinet/FFImageLoading#712]
I'm download your prepository.

To demo your FFImageLoading.Forms.Sample quickly,  I remove the reference from source code project(FFImageLoading, FFImageLoading.Forms... project) replace them from nuget Xamarin.FFImage....

When I startup  FFImageLoading.Forms.Sample.Droid project , I get the error:

Xamvvm.NoPageForPageModelRegisteredException: No Page Registered for Type: FFImageLoading.Forms.Sample.MenuNavigationPageModel

![ffimageloading forms sample 0](https://user-images.githubusercontent.com/9160517/30000485-902f652a-90a0-11e7-9625-8d543ec47bf3.jpg)
![ffimageloading forms sample 1](https://user-images.githubusercontent.com/9160517/30000487-94909d50-90a0-11e7-86b9-37d4e9f28ea1.jpg)

**Comment by daniel-luberda** [comment]
@Cheunglik Just downgrade Xamvvm package to 1.0.2. It's a bug, I'll fix it.

**Comment by Cheunglik** [comment]
@daniel-luberda .
Thanks. Use Xamvvm package 1.0.4 now.
