### ISSUE TITLE
Placeholder size

### ISSUE THREAD

**Issue by mcostagonzalez** [luberda-molinet/FFImageLoading#715]
Hi,

We're trying to add an animated gif in order to indicate that the image is loading. The problem is that the placeholder is stretched to fill the element canvas, while we want it to be smaller.

Is there some way to use the placeholder as is?

Thanks in advance.
Best regards.

**Comment by daniel-luberda** [comment]
Is it Xamarin.Forms or native?

BTW: I wouldn't use gifs for placeholders as gifs are quite resource-heavy. Isn't it better to use some kind of loading indicator on top of the image view? You have `IsLoading` property for that, or callbacks (Started, Finished, Error, etc).

**Comment by mcostagonzalez** [comment]
Hi,

Sorry for not answering earlier, I'm talking about Xamarin.Forms. 

Do you have any example of a loading indicator that can be easily implemented in a ListView-like container?

Thanks,
Best regards.

**Comment by daniel-luberda** [comment]
```XML
<Grid>
    <Image x:Name="Primary" Source="{Binding Url}" />
    <ActivityIndicator x:Name="ActivityIndicator" IsRunning="{Binding IsLoading}" IsVisible="{Binding IsLoading}" BindingContext="{x:Reference Name=Primary}" />
</Grid>
```

**Comment by adrianknight89** [comment]
In my case, adding an ActivityIndicator seems more resource heavier than gifs. @daniel-luberda Can we create functionality to define loading gif dimensions?

**Comment by deakjahn** [comment]
I concur. Couldn't be this reopened, Daniel?

First, the ActivityIndicator is different on different platforms (rather puny on UWP, for instance) and not necessarily linked visually to the individual images). You have that nice `LoadingPlaceholder` ready and usablem the only problem is that, unlike the actual content that goes into the `CachedImage`, the placeholder is not supposed to be using the same `Aspect` in many cases but stay at a constant, original size, centered. So, if you could just change the aspect while loading (or allowing us to supply a `LoadingAspect`) would be terrific.
