### ISSUE TITLE
Memory Not Getting Released On Xamarin.Forms.Android

### ISSUE THREAD

**Issue by JRC-BitBull** [luberda-molinet/FFImageLoading#719]
Hi,

I am loading images using CachedImage but when disposing of them the memory is not getting released on Android (haven't checked iOS). I am removing from the cache using...

CachedImage.InvalidateCache (photo.Variants.Large, FFImageLoading.Cache.CacheType.Memory, true);

...this seems to remove from the cache OK as the images get reloaded and memory increases again, but the original memory is not released.

Any help much appreciated! I read something about overriding Java finalizers but I do not understand where to do this, e.g. do I need to extend CachedImage and do it in a custom renderer?

**Comment by daniel-luberda** [comment]
How do you check that memory is not released?

Please note, that after releasing image from memory cache. Existing bitmap could also be reused for some new image decoding operations. Read more by googling: `android inbitmap options`. It's one of the optimisations too. Bitmap would be garbage collected eventually (if not reused), but that process is non-deterministic, Android takes care of it.

**Comment by JRC-BitBull** [comment]
I think actually the issue is with CarouselView - a few quick tests seem to show the memory is getting released if I use the image outside of CarouselView.

To check memory usage I'm just using the methods Java.Runtime.FreeMemory() etc, I realise the memory won't necessarily get reclaimed right away but I can fill the memory up until it crashes simply by flipping between two pages.

This library has really helped though! At the moment I think CarouselView is the culprit...

**Comment by daniel-luberda** [comment]
Yes, it's a known issue: https://github.com/luberda-molinet/FFImageLoading/issues/708

I'll close this one as it must be fixed on `CarouselView`'s side

**Comment by JRC-BitBull** [comment]
Hi,

Actually after more work I’m not sure if it is entirely the CarouselView.

I have managed to figure out a hacky workaround for the CarouselView image leak (removing the image from the DataTemplate before it is disposed) but, though this works with the standard Xamarin.Forms.Image, it does not work with CachedImage.

I am explicitly clearing the memory cache but, using CachedImage, my app still runs out of memory. If I just do a straight swap to Xamarin.Forms.Image everything is fine.  

cheers

====

James Closs, Director, BitBull Ltd

http://www.bitbull.com <http://www.bitbull.com/> 

07771 991171 | @BitBullDotCom

====

Check out the #giantjm trailer: http://bit.ly/1XSStQu <http://http//bit.ly/1XSStQu>

**Comment by daniel-luberda** [comment]
Could write more details about the hacky workaround? I use `CachedImage` in various scenarios and I didn't notice any memory leaks at all. Only problem observed is within `CarouselView` usage which is clearly not FFImageLoading issue. Also please notice, that FFImageLoading uses some poool of old, not used bitmaps for `inbitmap` usage on Android. 

Can you make a reproduction?

**Comment by JRC-BitBull** [comment]
Hi,

I will try and make a simple project that replicates the issue. It could well be pilot error on my part. I’m just finishing off a big project at the moment so it’ll be next week probably.

The hacky workaround is as follows…

The DataTemplate in CarouselView is my own custom class that is a Subclass of Grid, call it MyDataTemplate. When one of these is added to a parent view ( OnSizeAllocated ) I perform a recursive callback to figure out the parent page and register the DataTemplate with the parent page.

When I am sure I don’t need the page any more I loop through all the registered MyDataTemplate instances and call a FreeMemory() method on them, this removes all the children from the Grid (including the Image instances) and seems to prevent any memory leaks.

It’s pretty hacky but it works!

cheers

====

James Closs, Director, BitBull Ltd

http://www.bitbull.com <http://www.bitbull.com/> 

07771 991171 | @BitBullDotCom

====

Check out the #giantjm trailer: http://bit.ly/1XSStQu <http://http//bit.ly/1XSStQu>
