### ISSUE TITLE
Local Image in iOS (Xamarin.Forms) always throws exception.

### ISSUE THREAD

**Issue by marcosanfilippo** [luberda-molinet/FFImageLoading#726]
Hi. I'm using Xamarin.Forms for tabbedview with icon.

I've downloaded icons from "material icon" website, added to Resources in Android and with App Catalog in iOS.

In Android, tabbed viw works fine. In iOS, always get a runtime exception.

Unhandled Exception:

System.Exception: Could not initialize an instance of the type 'UIKit.UIImage': the native 'initWithContentsOfFile:' method returned nil.
It is possible to ignore this condition by setting MonoTouch.ObjCRuntime.Class.ThrowOnInitFailure to false..

Maybe the library can't find the icon.

Any idea?

**Comment by molinch** [comment]
It is most likely a local issue, hence it should be fixed locally rather than putting a workaround in the lib.

https://forums.xamarin.com/discussion/25248/how-to-find-the-image-that-is-not-found-on-ios

> The checklist is:
> 
> you DO have a name mismatch (the file is not added as resource or a name case mismatch)
> clean project
> quit VS/XS and remove all bin/obj paths so the resources are forced to be regenerated (often needed on Android).

Could you try these steps?

**Comment by daniel-luberda** [comment]
Could you post full stack trace?
