### ISSUE TITLE
Gif low framerate on Android

### ISSUE THREAD

**Issue by HugoTruffe** [luberda-molinet/FFImageLoading#728]
HI:

I am using 
**"xmlns:ffimageloading="clr-amespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms""** for read a gif image. (WIth Xamarin.Forms)

`<ffimageloading:CachedImage 
                  HorizontalOptions="FillAndExpand" 
                  VerticalOptions="FillAndExpand"
                  DownsampleToViewSize="true"
                  Aspect="AspectFit" 
                  HeightRequest="80" 
                  WidthRequest="80"
                  Source="logo.gif"/>`

The problem is that the animation of the gif is very very slow. 

Is there some parameter that I am omitting?

**Comment by HugoTruffe** [comment]
The problem is resolved.

I updated to "2.2.12-pre497" and it is correct the animation.

Thanks

**Comment by daniel-luberda** [comment]
I'll close this one then. Thanks.

**Comment by juanagu** [comment]
I try using gif in 2.2.20 and the animation on Android is a little slower. On iOS works very well!
This is the gif:
![loader_garzon](https://user-images.githubusercontent.com/4689126/32552537-0b4bf63c-c473-11e7-984a-965106b88fc1.gif)

**Comment by daniel-luberda** [comment]
You should use 2.2.24 - there was a fix regarding Android gif delay, here: https://github.com/luberda-molinet/FFImageLoading/commit/2b18fd283d82d60f58094df8a5e45c6560bd310b

**Comment by juanagu** [comment]
I'm using 2.2.24.

**Comment by dmmg83** [comment]
I'm using 2.2.25 in Xamarin Forms PCL project, and in android it's too slow

**Comment by daniel-luberda** [comment]
It's because of this: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Helpers/Delay.cs

```C#
public static Task DelayAsync(int miliseconds)
{
    if (miliseconds >= 60)
        return Task.Delay(miliseconds);

    return Task.Factory.StartNew(() => 
    {
        using (var mres = new System.Threading.ManualResetEventSlim(false))
        {
            mres.Wait(miliseconds);
        }
    }, TaskCreationOptions.PreferFairness);
}
```

The thing is `Task.Delay` accuracy is no more than 15ms. Does anyone know how could we improve that?

**Comment by daniel-luberda** [comment]
Fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/3ceeacf49327e3160ea5f16e178f3035e6c365bb
