### ISSUE TITLE
TypeConverter missing in UWP Windows

### ISSUE THREAD

**Issue by db-007** [luberda-molinet/FFImageLoading#729]
Assuming somewhere in app sandbox, I have an image like

`"C:/Users/me/AppData/Local/Packages/f040f23f-de21.../LocalState/se/resources/resources/plugins/spseplugin/myicon.png"`

, and assuming, you set all as required for using FFImageLoading like below steps show:

1. FFImageLoading Nuget package and add it to references of your projects (this is all done by package manager)

2. In UWP App.xaml.cs, I add following as per FFImageLoading GitHub documentation instructions:
```
                        var assembliesToInclude = new List<Assembly>()
                        {
                            typeof(CachedImage).GetTypeInfo().Assembly,
                            typeof(CachedImageRenderer).GetTypeInfo().Assembly
                        };
                        Xamarin.Forms.Forms.Init(e, assembliesToInclude);
```
3. In my UWP MainPage.xaml.cs, add following line in MainPage c-tor just after call to InitializeComponent, also as per FFImageLoading GitHub instructions:
`CachedImageRenderer.Init();`
4. Add xmlns namespace for FFImageLoading library in my XAML:
`xmlns:ff="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"`
5. Add FFImageLoading CachedImage to my StackLayout:
```
        <ff:CachedImage       <-- using CachedImage wont show image. Using Image will show it.
          Source="{Binding ImageUri}"  <--ImageUri is property pointing to the file location specified above
          WidthRequest="20" 
          HeightRequest="20" 
          VerticalOptions="Center" 
          DownsampleToViewSize="True" />
```
Above, ImageUri is a property on my view-model and putting break point on it shows that it is set to the image file path I showed above.
In UWP project, attempt to load this image fails

I believe the reason for this is that the FFImageLoading.Forms/ImageSourceConverter.cs ([https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms/ImageSourceConverter.cs#L17-L47](https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms/ImageSourceConverter.cs#L17-L47) inherits TypeConverter which is not supported in UWP.

My Temp Solution:
I copied the code from FFImageLoading ImageSourceConverter into my own class, removed all attributes and instead inheriting TypeConverter, I implemented IValueConverter (with its method) and used code from ConvertFrom in my Convert method.

**Comment by daniel-luberda** [comment]
`TypeConverter` is an integral Xamarin.Forms class. You either have some corrupted Xamarin.Forms installation or some missing references problem.

**Comment by db-007** [comment]
Are there any requirements on version of Xamarin Forms?  The FFImageLoading documentation is not saying anything about that and the installation steps are next to none but I dont think I have installation problem, it is just a Xamarin.Forms Nuget I installed on entire solution and that added required components by itself to all projects in the solution.  I installed 2.2.10 and that is the one I have this problem with.  
(I also tried 2.2.11 but that one complained because if the line `text.IsDataUrl` in ImageSourceConverter here [https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms/ImageSourceConverter.cs#L17-L47](https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms/ImageSourceConverter.cs#L17-L47))

**Comment by daniel-luberda** [comment]
It works fine on all >2 versions. You must add package to the every project (shared or platform specific).  Also remove all `bin`/`obj` folders then clean & rebuild. 

What I currently don't understand is why you're getting `TypeConverter` exceptions. Could you make a reproduction so I could debug it?

**Comment by db-007** [comment]
Thanks @daniel-luberda , all my PCLs have reference to 3: 

1. FFImageLoading, 
2. FFImageLoading.Forms, and 
3. FFImageLoading.Platform
4. Xamarin.Forms.Core
5. Xamarin.Forms.Platform
6. Xamarin.Forms.Xaml

My Head projects have following:
ANDROID:

1. FFImageLoading
2. FFImageLoading.Forms
3. FFImageLoading.Forms.Droid
4. FFImageLoading.Platform
5. Xamarin.Forms.Core, Platform, Platform.Android, Xaml and number of Android Support libraries

UWP

1. Xamarin.FFImageLoading.Forms
2. Xamarin.Forms

So, in terms of Xamarin.Forms, nothing is missing.  In terms of FFImageLoading, I dont know.  What I listed above is what gets added **when you right-click on your solution (So, entire solution, not head-projects by themselves)** and open NuGet Package Manager and search for FFImageLoading and select Xamarin.FFImageLoading.Forms nuget to add it to the solution.
This adds everything what is needed for each project (PCLs and head-projects) as I described above.

Based on above, I dont think anything is missing.  I am using Windows 10 Build 15063 (Creators Update), Visual Studio 2015, FFImageLoading 2.2.10

**Comment by daniel-luberda** [comment]
> UWP has only one FFImageLoading refrence (but that is how Nuget Packager added it):
> 
> 1. Xamarin.FFImageLoading.Forms
> 2. Xamarin.Forms

That is confusing for me. Why are the rest of the nuget packages not added? (they're necessary) Do you have a list of dlls which are added to that project?

**Comment by daniel-luberda** [comment]
Could you check FFImageLoading 2.2.14? Does it fix your issues?

**Comment by db-007** [comment]
@daniel-luberda Sorry I was away and today is short day, but in terms of 2.2.14, I tried is as I explained above, I was not able to build project with that version of FFIL.  
In terms of your sample project, wasnt able to build it but did not spend to much time on that as I was away.
The explanation above explain exactly waht I did to add FFIL to a solution on Windows machine, including versions, they should be easy to reproduce both ((a) what gets added by nuget manager, and (b) loading a property image)

**Comment by daniel-luberda** [comment]
I don't use UWP very often. It would be great if you had some kind of sample project. Also newest 2.2.16 has some new Windows refactorings and nuspec fixes too.

**Comment by daniel-luberda** [comment]
Does it happen when using latest nuget?

**Comment by daniel-luberda** [comment]
Could you test newest 2.2.21.580 prerelease nuget and confirm if it's fixed?

**Comment by daniel-luberda** [comment]
Please reopen if you still experience it in 2.2.21 stable.
