### ISSUE TITLE
For UWP apps, SVGs not rendering in any version higher than 2.2.10-pre-408 

### ISSUE THREAD

**Issue by tomrb** [luberda-molinet/FFImageLoading#730]
I am writing a Xamarin Forms app that uses SVG images. For UWP apps, SVGs render in version 2.2.10-pre-408 but not in any version higher than that. I have tested in all versions starting at 2.2.10 to latest 2.2.12-pre-497 and SVGs will not be rendered in my UWP app. Everything works fine in my iOS and Android apps.

**Comment by daniel-luberda** [comment]
It's fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/c49248972fd327c3945ddf64726658a098eecf90

Shortly, you must add `NETStandard.Library` package to solve your issues.
