### ISSUE TITLE
use CircleTransformation report error Unhandled Exception

### ISSUE THREAD

**Issue by zjmsky** [luberda-molinet/FFImageLoading#732]
today i updated to 2.2.13 version,when i use CircleTransformation in my xamarin.forms project ,it worked in android,but in iOS it report "Unhandled Exception:
Foundation.MonoTouchException: <Timeout exceeded getting exception details>" ,how can i resolve this problem?thanks !

**Comment by daniel-luberda** [comment]
Could you check FFImageLoading 2.2.14? Does it fix your issues?

**Comment by daniel-luberda** [comment]
Could you check FFImageLoading 2.2.16? Does it fix your issues?

**Comment by daniel-luberda** [comment]
Could you check FFImageLoading 2.2.16? Does it fix your issues?

**Comment by zjmsky** [comment]
hi,sorry i don't say clear,CircleTransformation used in xaml reported error,but i used in code,it worked.Version 2.2.16 i have not try.
