### ISSUE TITLE
UWP: 2.2.14 (System.TypeInitializationException)

### ISSUE THREAD

**Issue by alanspires** [luberda-molinet/FFImageLoading#735]
System.TypeInitializationException: 'The type initializer for 'FFImageLoading.Forms.CachedImage' threw an exception.'

Exception: You are referencing the Portable version in your App - you need to reference the platform (iOS/Android) version

On 2.2.13 this doesn't occur.

**Comment by daniel-luberda** [comment]
There were changes in nuspec files: 
https://github.com/luberda-molinet/FFImageLoading/commit/2a931f8c716d40addee49f8683da0f0dad70b8b7
https://github.com/luberda-molinet/FFImageLoading/commit/8d30a675f523981b24e5bcf084b4cdd3eb4ef2db

Could you write more details about your project?

**Comment by daniel-luberda** [comment]
Fixed
