### ISSUE TITLE
TapGestureRecognizer not firing on Android

### ISSUE THREAD

**Issue by LuigiMaestrelli** [luberda-molinet/FFImageLoading#736]
After updating from 2.2.13 to 2.2.15 the TapGestureRecognizer is not firing on Android.
On iOS it works. 
[App1.zip](https://github.com/luberda-molinet/FFImageLoading/files/1325354/App1.zip)

**Comment by heathbm** [comment]
Same here

**Comment by daniel-luberda** [comment]
Should be fixed with: https://github.com/luberda-molinet/FFImageLoading/commit/fa9c24b273f5809aef6fe1e6a22574e049c0e067

I tested in on the newest prerelease Xamarin.Forms version, and forgot to test it on the older ones. Sorry for that. New build will be released  today.

**Comment by daniel-luberda** [comment]
It should be fixed in 2.2.16 (stable). Please reopen if it didn't work for you. Thanks.
