### ISSUE TITLE
NRE crashes on UWP in FFImageLoading 2.2.14/2.2.15

### ISSUE THREAD

**Issue by mattrichnz** [luberda-molinet/FFImageLoading#737]
First off, thanks for all your hard work on FFImageLoading. We've been using it and have come to rely on it as one of our core libraries.

However, I'm not sure what has happened in 2.2.14+ onwards on UWP. Following "Xamarin.Forms renderers refactorings & improvements", we are now experiencing crashes on UWP when popping pages containing `CachedImage` XAML elements.

The crash is a NullReferenceException thrown seemingly when the page is being cleaned up when popping from the stack. Quite possibly the changes/enhancements to cleanup/dispose in the renderers may be the cause?

**Comment by daniel-luberda** [comment]
Hi @mattrichnz, 

It was already fixed and you can test it in 2.2.16-pre (sorry for that). Could you check if it's working for you?

Best,
Daniel

**Comment by daniel-luberda** [comment]
It should be fixed in 2.2.16 (stable). Please reopen if it didn't work for you. Thanks.

**Comment by mattrichnz** [comment]
Thanks Daniel, can confirm this is resolved in 2.2.16 (stable). Appreciate your hard work!
