### ISSUE TITLE
iOS Config Crash

### ISSUE THREAD

**Issue by gviddy** [luberda-molinet/FFImageLoading#738]
I am getting the following crash on iOS using Xamarin Forms....

Version 2.2.9

Crashed: tid_907
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x0000000003f7b000

Crashed: tid_907
0  AccessMyCommunityApp.iOS       0x180015c FFImageLoading_Config_Configuration_set_DiskCache_FFImageLoading_Cache_IDiskCache (C:\projects\ffimageloading\source\FFImageLoading.Common\Config\Configuration.cs:58)
1  AccessMyCommunityApp.iOS       0x3f7b000 (Missing)
2  AccessMyCommunityApp.iOS       0x18bbd6c FFImageLoading_ImageService_InitializeIfNeeded_FFImageLoading_Config_Configuration (C:\projects\ffimageloading\source\FFImageLoading.Shared\ImageService.cs:132)
3  AccessMyCommunityApp.iOS       0x18bb4a0 FFImageLoading_ImageService_Initialize_FFImageLoading_Config_Configuration (C:\projects\ffimageloading\source\FFImageLoading.Shared\ImageService.cs:95)
4  AccessMyCommunityApp.iOS       0x155474 AccessMyCommunityApp_iOS_AppDelegate_FinishedLaunching_UIKit_UIApplication_Foundation_NSDictionary (C:\Work\MCD AMC\Mobile\AccessMyCommunityApp\AccessMyCommunityApp.iOS\AppDelegate.cs:52)
5  AccessMyCommunityApp.iOS       0x3f8bc4 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 3039659
6  AccessMyCommunityApp.iOS       0x1da5775 mono_jit_runtime_invoke (mini-runtime.c:2526)
7  AccessMyCommunityApp.iOS       0x1e031e5 do_runtime_invoke (object.c:2829)
8  AccessMyCommunityApp.iOS       0x1e0317b mono_runtime_invoke (object.c:2983)
9  AccessMyCommunityApp.iOS       0x13457d native_to_managed_trampoline_9(objc_object*, objc_selector*, _MonoMethod**, UIApplication*, NSDictionary*, unsigned int) (registrar.m:413)
10 AccessMyCommunityApp.iOS       0x134a65 -[AppDelegate application:didFinishLaunchingWithOptions:] (registrar.m:8663)
11 UIKit                          0x292451fd -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 392
12 UIKit                          0x2946bfe5 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3080
13 UIKit                          0x2946febb -[UIApplication _runWithMainScene:transitionContext:completion:] + 1570
14 UIKit                          0x29483b9d __84-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:]_block_invoke3228 + 36
15 UIKit                          0x2946d3ab -[UIApplication workspaceDidEndTransaction:] + 134
16 FrontBoardServices             0x26378c7f -[FBSSerialQueue _performNext] + 230
17 FrontBoardServices             0x26378f71 -[FBSSerialQueue _performNextFromRunLoopSource] + 48
18 CoreFoundation                 0x2505768f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
19 CoreFoundation                 0x2505727d __CFRunLoopDoSources0 + 452
20 CoreFoundation                 0x250555eb __CFRunLoopRun + 794
21 CoreFoundation                 0x24fa8bf9 CFRunLoopRunSpecific + 520
22 CoreFoundation                 0x24fa89e5 CFRunLoopRunInMode + 108
23 UIKit                          0x2923e5bd -[UIApplication _run] + 524
24 UIKit                          0x29238ba1 UIApplicationMain + 144

**Comment by gviddy** [comment]
Oh and to add, only happens on the device, never crashes in the Simulator....

**Comment by daniel-luberda** [comment]
It looks like Xamarin issue, probably not related to FFImageLoading at all.
