### ISSUE TITLE
iOS Image Loader Crash

### ISSUE THREAD

**Issue by gviddy** [luberda-molinet/FFImageLoading#739]
Version 2.2.16 .... Xamarin Forms iOS....

I am loading images in a listview on an iPhone 4S... Am yet to test newer devices.. Does not happen in the iOS Simulator.. I am not scrolling quickly... Just scroll a couple items and the app crashes without any useful debug information in Visual Studio... The only way I can get you the following crash log is from crashlytics....

This is my line of xaml code in my listview data template...
`<ffimageloading:CachedImage Grid.Row="0" Grid.RowSpan="2" Grid.Column="0" Grid.ColumnSpan="3" Source="{Binding Logo}" LoadingPlaceholder="{Binding Placeholder}" CacheDuration="7" DownsampleToViewSize="True" FadeAnimationEnabled="True" Aspect="AspectFill" HorizontalOptions="Fill" VerticalOptions="Fill"/>`

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

Crashed: tid_907
0   AccessMyCommunityApp.iOS       0x96a12c System_Net_WebConnection_InitRead_object (WebConnection.cs:586)
1   AccessMyCommunityApp.iOS       0x972a90 System_Net_WebConnectionStream_Close (WebConnectionStream.cs:805)
2   AccessMyCommunityApp.iOS       0x972a90 System_Net_WebConnectionStream_Close (WebConnectionStream.cs:805)
3   AccessMyCommunityApp.iOS       0x95eb2c System_Net_HttpWebRequest_Abort (HttpWebRequest.cs:1098)
4   AccessMyCommunityApp.iOS       0xe30504 System_Net_Http_HttpClientHandler__c__SendAsyncb__63_0_object (HttpClientHandler.cs:347)
5   AccessMyCommunityApp.iOS       0x27a68c System_Threading_CancellationCallbackInfo_ExecutionContextCallback_object + 1825907
6   AccessMyCommunityApp.iOS       0x2803e8 System_Threading_ExecutionContext_RunInternal_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool + 1849807
7   AccessMyCommunityApp.iOS       0x2801f4 System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool + 1849307
8   AccessMyCommunityApp.iOS       0x280174 System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object + 1849179
9   AccessMyCommunityApp.iOS       0x27a60c System_Threading_CancellationCallbackInfo_ExecuteCallback + 1825779
10  AccessMyCommunityApp.iOS       0x279f10 System_Threading_CancellationTokenSource_CancellationCallbackCoreWork_System_Threading_CancellationCallbackCoreWorkArguments + 1823991
11  AccessMyCommunityApp.iOS       0x279bd8 System_Threading_CancellationTokenSource_ExecuteCallbackHandlers_bool + 1823167
12  AccessMyCommunityApp.iOS       0x27977c System_Threading_CancellationTokenSource_NotifyCancellation_bool + 1822051
13  AccessMyCommunityApp.iOS       0x27898c System_Threading_CancellationTokenSource_Cancel_bool + 1818483
14  AccessMyCommunityApp.iOS       0x278928 System_Threading_CancellationTokenSource_Cancel + 1818383
15  AccessMyCommunityApp.iOS       0x278644 System_Threading_CancellationTokenSource_LinkedTokenCancelDelegate_object + 1817643
16  AccessMyCommunityApp.iOS       0x27a68c System_Threading_CancellationCallbackInfo_ExecutionContextCallback_object + 1825907
17  AccessMyCommunityApp.iOS       0x27a618 System_Threading_CancellationCallbackInfo_ExecuteCallback + 1825791
18  AccessMyCommunityApp.iOS       0x279f10 System_Threading_CancellationTokenSource_CancellationCallbackCoreWork_System_Threading_CancellationCallbackCoreWorkArguments + 1823991
19  AccessMyCommunityApp.iOS       0x279bd8 System_Threading_CancellationTokenSource_ExecuteCallbackHandlers_bool + 1823167
20  AccessMyCommunityApp.iOS       0x27977c System_Threading_CancellationTokenSource_NotifyCancellation_bool + 1822051
21  AccessMyCommunityApp.iOS       0x27898c System_Threading_CancellationTokenSource_Cancel_bool + 1818483
22  AccessMyCommunityApp.iOS       0x278928 System_Threading_CancellationTokenSource_Cancel + 1818383
23  AccessMyCommunityApp.iOS       0x278644 System_Threading_CancellationTokenSource_LinkedTokenCancelDelegate_object + 1817643
24  AccessMyCommunityApp.iOS       0x27a68c System_Threading_CancellationCallbackInfo_ExecutionContextCallback_object + 1825907
25  AccessMyCommunityApp.iOS       0x27a618 System_Threading_CancellationCallbackInfo_ExecuteCallback + 1825791
26  AccessMyCommunityApp.iOS       0x279f10 System_Threading_CancellationTokenSource_CancellationCallbackCoreWork_System_Threading_CancellationCallbackCoreWorkArguments + 1823991
27  AccessMyCommunityApp.iOS       0x279bd8 System_Threading_CancellationTokenSource_ExecuteCallbackHandlers_bool + 1823167
28  AccessMyCommunityApp.iOS       0x27977c System_Threading_CancellationTokenSource_NotifyCancellation_bool + 1822051
29  AccessMyCommunityApp.iOS       0x27898c System_Threading_CancellationTokenSource_Cancel_bool + 1818483
30  AccessMyCommunityApp.iOS       0x278928 System_Threading_CancellationTokenSource_Cancel + 1818383
31  AccessMyCommunityApp.iOS       0x17d1660 FFImageLoading_Work_ImageLoaderTask_2_TImageContainer_REF_TImageView_REF_Cancel (C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:261)
32  AccessMyCommunityApp.iOS       0x19bce8c FFImageLoading_Forms_Touch_CachedImageRenderer_CancelIfNeeded (C:\projects\ffimageloading\source\FFImageLoading.Forms.Touch\CachedImageRenderer.cs:232)
33  AccessMyCommunityApp.iOS       0x19bc1cc FFImageLoading_Forms_Touch_CachedImageRenderer_UpdateImage_UIKit_UIImageView_FFImageLoading_Forms_CachedImage_FFImageLoading_Forms_CachedImage (C:\projects\ffimageloading\source\FFImageLoading.Forms.Touch\CachedImageRenderer.cs:158)
34  AccessMyCommunityApp.iOS       0x19bbc54 FFImageLoading_Forms_Touch_CachedImageRenderer_OnElementPropertyChanged_object_System_ComponentModel_PropertyChangedEventArgs (C:\projects\ffimageloading\source\FFImageLoading.Forms.Touch\CachedImageRenderer.cs:114)
35  AccessMyCommunityApp.iOS       0x9ae420 wrapper_delegate_invoke__Module_invoke_void_object_PropertyChangedEventArgs_object_System_ComponentModel_PropertyChangedEventArgs + 9378311
36  AccessMyCommunityApp.iOS       0x45404c Xamarin_Forms_BindableObject_OnPropertyChanged_string (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:137)
37  AccessMyCommunityApp.iOS       0x57ff30 Xamarin_Forms_Element_OnPropertyChanged_string (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:382)
38  AccessMyCommunityApp.iOS       0x458e08 Xamarin_Forms_BindableObject_SetValueActual_Xamarin_Forms_BindableProperty_Xamarin_Forms_BindableObject_BindablePropertyContext_object_bool_Xamarin_Forms_BindableObject_SetValueFlags_bool (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:591)
39  AccessMyCommunityApp.iOS       0x456c48 Xamarin_Forms_BindableObject_SetValueCore_Xamarin_Forms_BindableProperty_object_Xamarin_Forms_BindableObject_SetValueFlags_Xamarin_Forms_BindableObject_SetValuePrivateFlags (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:388)
40  AccessMyCommunityApp.iOS       0x4667dc Xamarin_Forms_BindingExpression_ApplyCore_object_Xamarin_Forms_BindableObject_Xamarin_Forms_BindableProperty_bool (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:174)
41  AccessMyCommunityApp.iOS       0x465514 Xamarin_Forms_BindingExpression_Apply_object_Xamarin_Forms_BindableObject_Xamarin_Forms_BindableProperty (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:77)
42  AccessMyCommunityApp.iOS       0x46126c Xamarin_Forms_Binding_Apply_object_Xamarin_Forms_BindableObject_Xamarin_Forms_BindableProperty (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Binding.cs:124)
43  AccessMyCommunityApp.iOS       0x457090 Xamarin_Forms_BindableObject_ApplyBindings_bool (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:407)
44  AccessMyCommunityApp.iOS       0x453e24 Xamarin_Forms_BindableObject_ApplyBindings (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:125)
45  AccessMyCommunityApp.iOS       0x453d54 Xamarin_Forms_BindableObject_SetInheritedBindingContext_Xamarin_Forms_BindableObject_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:119)
46  AccessMyCommunityApp.iOS       0x58203c Xamarin_Forms_Element_SetChildInheritedBindingContext_Xamarin_Forms_Element_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:484)
47  AccessMyCommunityApp.iOS       0x57f29c Xamarin_Forms_Element_OnBindingContextChanged (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:323)
48  AccessMyCommunityApp.iOS       0x4a8dac Xamarin_Forms_View_OnBindingContextChanged (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\View.cs:100)
49  AccessMyCommunityApp.iOS       0x566948 Xamarin_Forms_Grid_OnBindingContextChanged (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Grid.cs:140)
50  AccessMyCommunityApp.iOS       0x453d7c Xamarin_Forms_BindableObject_SetInheritedBindingContext_Xamarin_Forms_BindableObject_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:120)
51  AccessMyCommunityApp.iOS       0x58203c Xamarin_Forms_Element_SetChildInheritedBindingContext_Xamarin_Forms_Element_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:484)
52  AccessMyCommunityApp.iOS       0x57f29c Xamarin_Forms_Element_OnBindingContextChanged (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:323)
53  AccessMyCommunityApp.iOS       0x4a8dac Xamarin_Forms_View_OnBindingContextChanged (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\View.cs:100)
54  AccessMyCommunityApp.iOS       0x566948 Xamarin_Forms_Grid_OnBindingContextChanged (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Grid.cs:140)
55  AccessMyCommunityApp.iOS       0x453d7c Xamarin_Forms_BindableObject_SetInheritedBindingContext_Xamarin_Forms_BindableObject_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:120)
56  AccessMyCommunityApp.iOS       0x58203c Xamarin_Forms_Element_SetChildInheritedBindingContext_Xamarin_Forms_Element_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:484)
57  AccessMyCommunityApp.iOS       0x57f29c Xamarin_Forms_Element_OnBindingContextChanged (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:323)
58  AccessMyCommunityApp.iOS       0x4e46d0 Xamarin_Forms_Cell_OnBindingContextChanged (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Cells\Cell.cs:120)
59  AccessMyCommunityApp.iOS       0x45745c Xamarin_Forms_BindableObject_BindingContextPropertyChanged_Xamarin_Forms_BindableObject_object_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:438)
60  AccessMyCommunityApp.iOS       0x458eb0 Xamarin_Forms_BindableObject_SetValueActual_Xamarin_Forms_BindableProperty_Xamarin_Forms_BindableObject_BindablePropertyContext_object_bool_Xamarin_Forms_BindableObject_SetValueFlags_bool (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:592)
61  AccessMyCommunityApp.iOS       0x456c48 Xamarin_Forms_BindableObject_SetValueCore_Xamarin_Forms_BindableProperty_object_Xamarin_Forms_BindableObject_SetValueFlags_Xamarin_Forms_BindableObject_SetValuePrivateFlags (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:388)
62  AccessMyCommunityApp.iOS       0x458714 Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object_bool_bool (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:541)
63  AccessMyCommunityApp.iOS       0x4538e8 Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:84)
64  AccessMyCommunityApp.iOS       0x4526bc Xamarin_Forms_BindableObject_set_BindingContext_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:24)
65  AccessMyCommunityApp.iOS       0x48fc84 Xamarin_Forms_TemplatedItemsList_2_TView_REF_TItem_REF_UpdateContent_TItem_REF_int_object (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\TemplatedItemsList.cs:602)
66  AccessMyCommunityApp.iOS       0x48fee4 Xamarin_Forms_TemplatedItemsList_2_TView_REF_TItem_REF_UpdateContent_TItem_REF_int (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\TemplatedItemsList.cs:615)
67  AccessMyCommunityApp.iOS       0x48ff9c Xamarin_Forms_TemplatedItemsList_2_TView_REF_TItem_REF_Xamarin_Forms_ITemplatedItemsList_TItem_UpdateContent_TItem_REF_int (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\TemplatedItemsList.cs:619)
68  AccessMyCommunityApp.iOS       0xc9e760 Xamarin_Forms_Platform_iOS_ListViewRenderer_ListViewDataSource_GetCell_UIKit_UITableView_Foundation_NSIndexPath (C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.iOS\Renderers\ListViewRenderer.cs:764)
69  AccessMyCommunityApp.iOS       0x3a1f14 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 3036411
70  AccessMyCommunityApp.iOS       0x1da1045 mono_jit_runtime_invoke (mini-runtime.c:2526)
71  AccessMyCommunityApp.iOS       0x1dfeab5 do_runtime_invoke (object.c:2829)
72  AccessMyCommunityApp.iOS       0x1dfea4b mono_runtime_invoke (object.c:2983)
73  AccessMyCommunityApp.iOS       0xe1f03 native_to_managed_trampoline_28(objc_object*, objc_selector*, _MonoMethod**, UITableView*, NSIndexPath*, unsigned int) (registrar.m:1199)
74  AccessMyCommunityApp.iOS       0xe554b -[Xamarin_Forms_Platform_iOS_ListViewRenderer_ListViewDataSource tableView:cellForRowAtIndexPath:] (registrar.m:10713)
75  UIKit                          0x295126bd -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 672
76  UIKit                          0x295127fd -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 68
77  UIKit                          0x29502031 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2272
78  UIKit                          0x29516fcb -[UITableView _performWithCachedTraitCollection:] + 78
79  UIKit                          0x292ba85b -[UITableView layoutSubviews] + 178
80  UIKit                          0x291ccd13 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 714
81  QuartzCore                     0x272cbf99 -[CALayer layoutSublayers] + 128
82  QuartzCore                     0x272c7695 CA::Layer::layout_if_needed(CA::Transaction*) + 348
83  QuartzCore                     0x272c7529 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 16
84  QuartzCore                     0x272c6a49 CA::Context::commit_transaction(CA::Transaction*) + 368
85  QuartzCore                     0x272c66fb CA::Transaction::commit() + 614
86  QuartzCore                     0x273186b7 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 762
87  IOMobileFramebuffer            0x26a0357b IOMobileFramebufferVsyncNotifyFunc + 86
88  IOKit                          0x252e23e9 IODispatchCalloutFromCFMessage + 256
89  CoreFoundation                 0x25045ae9 __CFMachPortPerform + 132
90  CoreFoundation                 0x25057e43 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 34
91  CoreFoundation                 0x25057557 __CFRunLoopDoSource1 + 342
92  CoreFoundation                 0x25055969 __CFRunLoopRun + 1688
93  CoreFoundation                 0x24fa8bf9 CFRunLoopRunSpecific + 520
94  CoreFoundation                 0x24fa89e5 CFRunLoopRunInMode + 108
95  GraphicsServices               0x261f4ac9 GSEventRunModal + 160
96  UIKit                          0x29238ba1 UIApplicationMain + 144
97  AccessMyCommunityApp.iOS       0xe0f520 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr (<unknown>:1)
98  AccessMyCommunityApp.iOS       0xd94bcc UIKit_UIApplication_Main_string___intptr_intptr (UIApplication.cs:79)
99  AccessMyCommunityApp.iOS       0xd94b8c UIKit_UIApplication_Main_string___string_string (UIApplication.cs:63)
100 AccessMyCommunityApp.iOS       0xff0c8 AccessMyCommunityApp_iOS_Application_Main_string__ (C:\Work\MCD AMC\Mobile\AccessMyCommunityApp\AccessMyCommunityApp.iOS\Main.cs:17)
101 AccessMyCommunityApp.iOS       0x3a1f14 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 3036411
102 AccessMyCommunityApp.iOS       0x1da1045 mono_jit_runtime_invoke (mini-runtime.c:2526)
103 AccessMyCommunityApp.iOS       0x1dfeab5 do_runtime_invoke (object.c:2829)
104 AccessMyCommunityApp.iOS       0x1e00e4b do_exec_main_checked (object.c:2983)
105 AccessMyCommunityApp.iOS       0x1d8b257 mono_jit_exec (driver.g.c:1040)
106 AccessMyCommunityApp.iOS       0x1ec78b0 xamarin_main (monotouch-main.m:482)
107 AccessMyCommunityApp.iOS       0xfefa9 main (main.m:135)
108 libdispatch.dylib              0x24c57873 (Missing)

**Comment by daniel-luberda** [comment]
It looks like Xamarin issue, probably not related to FFImageLoading at all.

**Comment by gviddy** [comment]
Closing this one.... Yep looks like it was running out of memory on the iPhone 4s and not related to your image handler...
