### ISSUE TITLE
Yellow Background when CircleTransformation on UWP

### ISSUE THREAD

**Issue by YZahringer** [luberda-molinet/FFImageLoading#741]
I have a yellow background when I use CircleTransformation on UWP with version 2.2.17.

No problem with version 2.2.16-pre-529.

**Comment by daniel-luberda** [comment]
@YZahringer  Do you use any border color?

**Comment by YZahringer** [comment]
No border and transparent background.

**Comment by nikolayDemirev** [comment]
Same here. Attaching the XAML:

`<ffimageloading:CachedImage Source="{Binding Path=ProfilePicture}}"
                                     Aspect="AspectFill" WidthRequest="100" HeightRequest="100"
                                     HorizontalOptions="Center" VerticalOptions="Start">
                            <ffimageloading:CachedImage.Transformations>
                                <fftransformations:CircleTransformation />
                            </ffimageloading:CachedImage.Transformations>
                        </ffimageloading:CachedImage>`

**Comment by daniel-luberda** [comment]
It's fixed, 2.2.18 released. Cheers :)
