### ISSUE TITLE
NullReferenceException in CachedImageRenderer under Android

### ISSUE THREAD

**Issue by philipag** [luberda-molinet/FFImageLoading#742]
Using 2.2.17 under Android (happened with previous versions as well), I get the following exception.  I am compiling my app with the latest Xamarin bits using .net standard 2.0.

09-27 10:12:52.130 I/MonoDroid( 3264): UNHANDLED EXCEPTION:
09-27 10:12:52.149 I/MonoDroid( 3264): System.NullReferenceException: Object reference not set to an instance of an object.
09-27 10:12:52.149 I/MonoDroid( 3264):   at FFImageLoading.Forms.Droid.CachedImageRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x000d1] in C:\projects\ffimageloading\source\FFImageLoading.Forms.Droid\CachedImageRenderer.cs:95 
09-27 10:12:52.149 I/MonoDroid( 3264):   at Controls.Droid.CircleImageRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00001] in C:\z\recorder\apps\Phone\Droid\Controls\CircleImageRenderer.cs:101

**Comment by daniel-luberda** [comment]
It's already fixed, but somehow you're using dlls from older version. Please clean, delete all `obj`/`bin` folders then rebuild.

**Comment by philipag** [comment]
you are right!
