### ISSUE TITLE
FFImageLoading and Android RecyclerView out of memory

### ISSUE THREAD

**Issue by lfongaroScp** [luberda-molinet/FFImageLoading#744]
Hi,
I am not sure if it is a bug of FFImageLoading, however if I use FFimageLoading with a RecyclerView  the app crash with an "OutOfMemory exception" 
I develop my app with Xamarin.Android (not Xamarin.Forms).

I use "Android Monitor" to trace the memory consumption of my app when I scroll the recyclerView and the heap grow and never reduce. 

The problem seems related to a reference not removed to the unused Bitmap. 
If I add these lines before the call to "ImageService.Instance.LoadStream" 
```
            using (var bd = vhInstance.PreviewPoint.Drawable as BitmapDrawable) {
                if (bd?.Bitmap != null) {
                    bd.Bitmap.Recycle();
                    bd.Bitmap.Dispose();
                    vhInstance.PreviewPoint.SetImageBitmap(null);
                }
            }
```
The memory is free regularly, but this can cause another exception ("java.lang.RuntimeException: Canvas: trying to use a recycled bitmap") if the user scroll really fast.

I created and attach a simple project to reproduce the problem and I test it on MotoG3 with Android 6.0.1 . I added some images in the assets/img subfolder. When the app start, it copy the images from assets/img to the disk and create a list with the paths of the images. These list is used by the adapter of the recyclerview.

You can change the images in the asset folder, because the app read all file contained in the subfolder.
Also, if you press the button "show new image" the app add a copy of the List to the old list and update the adapter. The images are pretty big, to force the bug to appear.
I add some comments to the two .cs file.

[TestImmagini.zip](https://github.com/luberda-molinet/FFImageLoading/files/1340429/TestImmagini.zip)

**Comment by daniel-luberda** [comment]
Do you use custom cache keys? Without it, streams are read every time and memory cache is not working. This may lead to OOM exceptions.

**Comment by daniel-luberda** [comment]
I added some code to be sure that stream is disposed. You should be able to test it in the newest prerelease. But if the coe snippet you attached works, I'm quite sure that using custom cache keys will resolve your issues as it means that simply too many bitmap objects are created.

**Comment by daniel-luberda** [comment]
Could you test 2.2.18 if it fixes your issues?

**Comment by lfongaroScp** [comment]
Hi,
In the sample I sent I do not use a custom key, but in my app I use it. I use also DownSample(width, height) method. 

I try the new version, it seems better. The heap stop to grew indefinitely but:
1) There are a lot of warning and error print in logcat. They are all similar to this:
> 09-29 09:40:47.637: W/art(11311): static void art::Dbg::DdmSendHeapSegments(bool) unimplemented Not counting objects in space SpaceTypeImageSpace begin=0x6f521000,end=0x6fc6b838,size=7MB,name="/data/dalvik-cache/arm/system@framework@boot.art"]
> 09-29 09:40:47.637: W/art(11311): static void art::Dbg::DdmSendHeapSegments(bool) unimplemented Not counting objects in space SpaceTypeZygoteSpace begin=0x73799000,end=0x73990000,size=2012KB,name="Zygote space"]
> 09-29 09:40:47.677: E/art(11311): Invalid object in managed heap: 0x73990008
> 09-29 09:40:47.719: E/art(11311): Invalid object in managed heap: 0x73990fe0

2) It seems a called to "NotifyDataSetChanged();" cause a memory leak, I do not understand if it is a problem of RecyclerView or FFImageLoading.

I attach the updated sample app (now use customkey and downsample method, so it is more similar to my real app)
[TestImmagini.zip](https://github.com/luberda-molinet/FFImageLoading/files/1343689/TestImmagini.zip)

**Comment by daniel-luberda** [comment]
It seems you're doing some memory intensive operations. You could try to increase `dalvik.vm.heapsize`, enable `largeHeap` and set it to eg. `512MB` and see if it would solve your issues
