### ISSUE TITLE
System.NotImplementedException when trying to call PreloadAsync()

### ISSUE THREAD

**Issue by dtavlikos** [luberda-molinet/FFImageLoading#749]
When trying to call PreloadAsync(), I get a `System.NotImplementedException` in `FFImageLoading.Common/Work/Target.get_Control()`.

The property is actually not implemented: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Work/Target.cs

This is on Xamarin.Android, with Xamarin.FFImageLoading v2.2.19.

EDIT: With Xamarin.FFImageLoading v2.2.9 (previous version used), I did not have this issue. No code changes.

**Comment by daniel-luberda** [comment]
Yes, it's a regression after this: https://github.com/luberda-molinet/FFImageLoading/commit/f90b5da9531c1d5e303ac5b2d7d0f8184a4f0c92

You can solve this in your current version, simply by disabling animation on Preload task. I'll push a fix now.
