### ISSUE TITLE
Images not rendering in listview - Xamarin.Forms

### ISSUE THREAD

**Issue by jaymarvels** [luberda-molinet/FFImageLoading#752]
I have a Viewcell inside my listview which is bound to my data source, I have read the wiki and it suggested making a custom viewcell to set the image source.

As directed I have done this:

```XML
<ListView x:Name="lstView" HasUnevenRows="True" SeparatorVisibility="None">
	<ListView.ItemTemplate>
		<DataTemplate>
			<helpers:MyCustomCell >
				<Grid Padding="5">
					<Grid.ColumnDefinitions>
					<ColumnDefinition Width="Auto"/>
					<ColumnDefinition/>
					<ColumnDefinition/>
					</Grid.ColumnDefinitions>
					<Grid.RowDefinitions>
					<RowDefinition Height="Auto"/>
					</Grid.RowDefinitions>
					<Label x:Name="CardName" Text="{Binding Name}" VerticalOptions="Start"/>
					<forms:CachedImage Grid.Column="0" x:Name="CardImage" HorizontalOptions="Center" VerticalOptions="Center" WidthRequest="100" HeightRequest="171" DownsampleToViewSize="true" >
					<forms:CachedImage.GestureRecognizers>
					<TapGestureRecognizer Command="{Binding TapCommand}"  CommandParameter="{Binding .}" Tapped="Image_OnTapped"  NumberOfTapsRequired="1" />
					</forms:CachedImage.GestureRecognizers>
					</forms:CachedImage>
					<Label Grid.Column="1" Text="{Binding Name}" LineBreakMode="WordWrap"/>
					<Label Grid.Column="2" Text="{Binding SubType}" LineBreakMode="WordWrap"/>
				</Grid>
			</helpers:MyCustomCell>
		</DataTemplate>
	</ListView.ItemTemplate>
</ListView>
```

My custom view cell is an almost identical replication of the sample:

```C#
public class MyCustomCell : ViewCell
    {
        readonly CachedImage CardImage = null;

        public MyCustomCell()
        {
            CardImage = new CachedImage();
            View = CardImage;
        }

        protected override void OnBindingContextChanged()
        {
            // you can also put cachedImage.Source = null; here to prevent showing old images occasionally
            var item = BindingContext as Card;

            if (item == null)
                return;

            CardImage.Source = item.ImageUrl;

            base.OnBindingContextChanged();
        }
    }
```

The listview displays correctly but without the image, I know the image cell is there because the Gesture is working and being hit. The OnBindingContextChanged is getting hit and setting the string url to the image source without failing, but no image is displayed at all.

Any tips where I am going wrong?

**Comment by daniel-luberda** [comment]
You've basically replaced the view which was defined in `MyCustomCell` with `Grid`. It's not an FFImageloading issue. 

Your xaml should look like this: 

```XML
<ListView x:Name="lstView" HasUnevenRows="True" SeparatorVisibility="None">
	<ListView.ItemTemplate>
		<DataTemplate>
			<helpers:MyCustomCell/>
		</DataTemplate>
	</ListView.ItemTemplate>
</ListView>
```

**Comment by jaymarvels** [comment]
@daniel-luberda  what if I need to a grid to set the layout of the listview item?

**Comment by daniel-luberda** [comment]
You should include that grid in your custom `ViewCell` too. `ViewCells` can also be coded in XAML.

**Comment by jaymarvels** [comment]
@daniel-luberda  if i create a custom viewcell with a grid inside it, won't i just get the same issue as before?

**Comment by daniel-luberda** [comment]
No, just create a new XAML `ContentView` file, change its type to `ViewCell`: 

```XML
<?xml version="1.0" encoding="utf-8" ?>
<ViewCell xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="YourNamespace.MyCustomCell">
    <Grid Padding="5">
        <Grid.ColumnDefinitions>
        <ColumnDefinition Width="Auto"/>
        <ColumnDefinition/>
        <ColumnDefinition/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
        <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <Label x:Name="CardName" Text="{Binding Name}" VerticalOptions="Start"/>
        <forms:CachedImage Grid.Column="0" x:Name="CardImage" HorizontalOptions="Center" VerticalOptions="Center" WidthRequest="100" HeightRequest="171" DownsampleToViewSize="true" >
        <forms:CachedImage.GestureRecognizers>
        <TapGestureRecognizer Command="{Binding TapCommand}"  CommandParameter="{Binding .}" Tapped="Image_OnTapped"  NumberOfTapsRequired="1" />
        </forms:CachedImage.GestureRecognizers>
        </forms:CachedImage>
        <Label Grid.Column="1" Text="{Binding Name}" LineBreakMode="WordWrap"/>
        <Label Grid.Column="2" Text="{Binding SubType}" LineBreakMode="WordWrap"/>
    </Grid>
</ViewCell>
```

Then override its `OnBindingContextChanged`:

```C#
public class MyCustomCell : ViewCell
    {
        readonly CachedImage CardImage = null;

        public MyCustomCell()
        {
            CardImage = new CachedImage();
            View = CardImage;
        }

        protected override void OnBindingContextChanged()
        {
            // you can also put cachedImage.Source = null; here to prevent showing old images occasionally
            var item = BindingContext as Card;

            if (item == null)
                return;

            CardImage.Source = item.ImageUrl;

            base.OnBindingContextChanged();
        }
    }
```

**Comment by jaymarvels** [comment]
@daniel-luberda  and how do I reference the new XMAL within my current listview, just by <></> ?

**Comment by daniel-luberda** [comment]
Yes. I updates my previous answer.

**Comment by jaymarvels** [comment]
@daniel-luberda Ahh I get you now. How about the Gesture in the custom view, would I need to move the method from the parent  contentpage to the customview ?

**Comment by daniel-luberda** [comment]
You can do everything which any other `View` can do. But remember that cells binding context is not your view model binding context, but item model.

**Comment by jaymarvels** [comment]
@daniel-luberda  thanks for all your help. It still isn't working. No list view at all. I guess I am will just have to scrap it all and look for an alternative solution.

**Comment by daniel-luberda** [comment]
It must be working. There's a complete example on out sample repo: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/ListPage.xaml

**Comment by jaymarvels** [comment]
Ok, followed that link and refactored my code slightly to match what your example is doing (minus the mvvm framework you're using) and now I can get the listview to show, albeit without images still! The labels are coming through, which shows the custom view cell is working, just no images.

Also I cannot implement the "Tapped="Image_OnTapped" on the custom viewcell as the tap event needs to happen on the parent content page view.

**Comment by jaymarvels** [comment]
I have cloned your repo, and while your code works out of the box, if I implement it more or less exactly the same (installed Xamvvm), changed everything to viewmodel etc

The only thing I am not doing which you are is 

`				new MenuItem() {
					Section = "Lists",
					Title = "List example",
					Command = new BaseCommand(async (param) =>
					{
						await this.PushPageFromCacheAsync<ListPageModel>(pm => pm.Reload());
					})`

But thats because I have no menu items, it just loads into it. Instead on my contentpage I put:

`var mod = new ListPageModel();
mod.Refresh();`

Everything gets hit apart from the custom cell binding.

So then I add in

`lstView.ItemSource = mod.Items;`

Now the list shows, but still without any images at all.

I dont get why its so hard to get this to work?!

**Comment by jaymarvels** [comment]
@daniel-luberda 

Finally found out the problem...

My images are being served up as https:// and these are erroring, if I change to http they are fine. I find this odd as in my native Android app I am using https:// and the images are fine. And I see in your samples you are too. Is there someway to capture the error or am I missing a setting over allowing https://?

**Comment by jaymarvels** [comment]
Just in case anyone else comes across this issue I finally solved it.

My images were returning: System.Net.WebException: Error: SecureChannelFailure (The authentication or decryption has failed.)

To solve this I used this nuget library: 

https://github.com/paulcbetts/ModernHttpClient

And implemented it in my App.cs:

`		public App ()
		{
		    var config = new FFImageLoading.Config.Configuration()
		    {
		        VerboseLogging = true,
		        VerbosePerformanceLogging = true,
		        Logger = new CustomMiniLogger(),
                HttpClient = new HttpClient(new NativeMessageHandler())
        };
		    ImageService.Instance.Initialize(config);
            MainPage = new NavigationPage(new LoadingPage());
        }`

My images are now loading.

**Comment by daniel-luberda** [comment]
@jaymarvels You can also switch to using native http client handlers through project settings :)

![screen shot 2017-10-06 at 19 17 16](https://user-images.githubusercontent.com/13569983/31289952-055e7612-aacb-11e7-9d65-aaa5eaaaba85.png)

**Comment by jaymarvels** [comment]
@daniel-luberda  I did! But it didn't make a difference!

![image](https://user-images.githubusercontent.com/7057631/31329504-5d8db07e-acd2-11e7-8b28-b6db15c293f1.png)

**Comment by daniel-luberda** [comment]
Also set SSL implementation
