### ISSUE TITLE
SVG tap area definition

### ISSUE THREAD

**Issue by Arsophia** [luberda-molinet/FFImageLoading#754]
Hello,

I am using a lot of SVG icons for buttons in my Xamarin.Forms App, however, even if I set a background for the image, it is very difficult to get the image to respond to taps because it seems to pickup only the events when the tap is made over an area of the image which contains visual elements. The problem seems to be fixed in Android when I set a background color, but in iOS the problem persist. This is the code I am using for rendering images:

`<ffimageloadingsvg:SvgCachedImage Margin="5,0,5,0" WidthRequest="25" HeightRequest="25" 
                        Source="resource://Certificc.Resources.IconShare.svg" BackgroundColor="White">  
                        <ffimageloadingsvg:SvgCachedImage.GestureRecognizers>
                                    <TapGestureRecognizer
                                        Tapped="Share"
                                        NumberOfTapsRequired="1"/>
                        </ffimageloadingsvg:SvgCachedImage.GestureRecognizers>
                        <ffimageloading:CachedImage.Transformations>
                            <fftransformations:TintTransformation HexColor="#27617d" EnableSolidColor="true" />
                        </ffimageloading:CachedImage.Transformations>
                    </ffimageloadingsvg:SvgCachedImage>`

Thanks a lot

**Comment by Arsophia** [comment]
Well by now I solved the issue with this code, putting the SVG inside a Frame object, however as there is a lot of SVG icons in my ViewCell, I would like to know if there is a lighter solution, here the code, thanks:

`<Frame Padding="0,0,0,0" Margin="0,0,0,0" HasShadow="false" >
                        <Frame.GestureRecognizers>
                                        <TapGestureRecognizer
                                            Tapped="Share"
                                            NumberOfTapsRequired="1"/>
                            </Frame.GestureRecognizers>
                        <ffimageloadingsvg:SvgCachedImage Margin="5,0,5,0" WidthRequest="25" HeightRequest="25" 
                            Source="resource://Certificc.Resources.IconShare.svg"> 
                            <ffimageloading:CachedImage.Transformations>
                                <fftransformations:TintTransformation HexColor="#27617d" EnableSolidColor="true" />
                            </ffimageloading:CachedImage.Transformations>
                        </ffimageloadingsvg:SvgCachedImage>
                    </Frame>`

**Comment by Arsophia** [comment]
Hi all,

I found this temporary solution, but as the code is in a ViewCell I hope there is a cleaner solution:

`
                    <Frame  Margin="0,0,0,0" Padding="0,0,0,0" HasShadow="false" BackgroundColor="White" >
                        <Frame.GestureRecognizers>
                                        <TapGestureRecognizer
                                            Tapped="Share"
                                            NumberOfTapsRequired="1"/>
                            </Frame.GestureRecognizers>
                        <ffimageloadingsvg:SvgCachedImage Margin="5,0,5,0" WidthRequest="25" HeightRequest="25" InputTransparent="true"
                            Source="resource://Certificc.Resources.IconShare.svg"> 
                            <ffimageloading:CachedImage.Transformations>
                                <fftransformations:TintTransformation HexColor="#27617d" EnableSolidColor="true" />
                            </ffimageloading:CachedImage.Transformations>
                        </ffimageloadingsvg:SvgCachedImage>
                    </Frame>`

**Comment by daniel-luberda** [comment]
Instead using `Frame` just use `ContentView`, it's more lightweight and it would be a preferred solution IMO.

**Comment by Arsophia** [comment]
Hi Daniel, thanks. In iOS i still having the problem using ContentView, sometimes my tap gets recognized and sometimes not. Even if i Set background in SVG and ContentView, here is my code snippet:

`
                    <ContentView  Margin="0,0,0,0" Padding="0,0,0,0"  BackgroundColor="White" >
                        <ContentView.GestureRecognizers>
                                        <TapGestureRecognizer
                                            Tapped="Share"
                                            NumberOfTapsRequired="1"/>
                            </ContentView.GestureRecognizers>
                        <ffimageloadingsvg:SvgCachedImage Margin="5,0,5,0" WidthRequest="25" HeightRequest="25" InputTransparent="true"
                            Source="resource://Certificc.Resources.IconShare.svg" BackgroundColor="White"> 
                            <ffimageloading:CachedImage.Transformations>
                                <fftransformations:TintTransformation HexColor="#27617d" EnableSolidColor="true" />
                            </ffimageloading:CachedImage.Transformations>
                        </ffimageloadingsvg:SvgCachedImage>
                    </ContentView>
                `

**Comment by daniel-luberda** [comment]
Just set the correct padding for your `ContentView` or correct Margin for `CachedImage`

**Comment by Arsophia** [comment]
Thanks a lot again Daniel, and specially for your great software. By the way, i will share the final snippet just in case someone needs something similar. 

`
                    <ContentView  Margin="0,0,0,0" Padding="5,10,5,5"  BackgroundColor="White" >
                        <ContentView.GestureRecognizers>
                                        <TapGestureRecognizer
                                            Tapped="Share"
                                            NumberOfTapsRequired="1"/>
                            </ContentView.GestureRecognizers>
                        <ffimageloadingsvg:SvgCachedImage Margin="0,0,0,0" WidthRequest="25" HeightRequest="25" InputTransparent="true"
                            Source="resource://Certificc.Resources.IconShare.svg"> 
                            <ffimageloading:CachedImage.Transformations>
                                <fftransformations:TintTransformation HexColor="#27617d" EnableSolidColor="true" />
                            </ffimageloading:CachedImage.Transformations>
                        </ffimageloadingsvg:SvgCachedImage>
                    </ContentView>`
