### ISSUE TITLE
Error loading debugging symbols in release?

### ISSUE THREAD

**Issue by ozzy1873** [luberda-molinet/FFImageLoading#755]
I am seeing this message when compiling for Android in release mode. Is this a problem or something I can ignore?

Failed to read 'MyApp.Android\obj\Release\android\assets\FFImageLoading.Forms.Droid.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.

Get the same error for the other DLLs too:
FFImageLoading.Platform.dll
FFImageLoading.Transformations.dll

**Comment by daniel-luberda** [comment]
We switched to use `portable pdb` files which are not compatible with VS < 2017. They have a lot of advantages over the old ones. Is it your case?

**Comment by ozzy1873** [comment]
I am using the latest VS 2017 preview. My app seems to run fine, but these error messages were cause for concern.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by daniel-luberda** [comment]
VS2017 supports Portable pdb files. It must be something with your visual studio configuration. It won't affect your app, just library errors stack traces would be less readable.

**Comment by ozzy1873** [comment]
Hmmm...ok, can't imagine what that might be ATM, but I'll take a look. Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by daniel-luberda** [comment]
Let me know if you have some more info, thanks :)
