### ISSUE TITLE
UWP: An image is blurry on screen with density 1 [help wanted]

### ISSUE THREAD

**Issue by JTOne123** [luberda-molinet/FFImageLoading#758]
Hi, I need an advice with that because very strange behavior

What I'm doing:

```
var size = [the same for both displays];

var scaleFactor = DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;

var thmbnail = await _asset.GetScaledImageAsThumbnailAsync(ThumbnailMode.PicturesView, (uint)(size * scaleFactor));

ChachedImage.Source = ImageSource.FromStream(()=>thmbnail?.AsStream());
```

On my external monitor with scale factor == 1, I see blurry images
On my MacBook Pro[bootcamp::win10] internal display with scale factor == 2, I see perfect images

**Comment by daniel-luberda** [comment]
`GetScaledImageAsThumbnailAsync` is not FFImageLoading library method. Am I missing something? 

You could use this instead: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Windows/Extensions/ImageExtensions.cs#L147

**Comment by JTOne123** [comment]
Yep, sorry the question definitely don't to you.

For some reason, I thought that GetScaledImageAsThumbnailAsync returns always the same and the issue in the ffimageloading.

But it is not true, FFImageLoading is the best!
