### ISSUE TITLE
Windows missing WebP support

### ISSUE THREAD

**Issue by daniel-luberda** [luberda-molinet/FFImageLoading#76]
- WebP support

**Comment by daniel-luberda** [comment]
- Fade animation code should be here: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Windows/TaskParameterExtensions.cs#L43
- WebP support - We need some C# decoder. If someone have an info about it - let me know.

**Comment by coonmoo** [comment]
This seems to have Windows WebP Support: https://github.com/chenrensong/ImageLib.UWP

**Comment by molinch** [comment]
We accept Pull Requests if anyone is interested to implement it :+1:

**Comment by molinch** [comment]
@daniel-luberda should we care? TBH Windows Phone is a dead market, so I don't think focusing on new features for it is really the best

**Comment by daniel-luberda** [comment]
You're right about Windows Phone, but UWP apps also work on desktop / metro PCs which is quite popular.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/858

**Comment by daniel-luberda** [comment]
All I need is a code / nuget / lib which will decode `Stream` to bitmap / raw pixels / `WriteableBitmap`. Anyone?
