### ISSUE TITLE
GIF Image Out of memory exeption

### ISSUE THREAD

**Issue by vladimir-shirmanov** [luberda-molinet/FFImageLoading#760]
When I try to load gif image from file system it throw system.outofmemory exeption. It hapens when there several gif images with the same name in diffrenet resolutions folders. When I delete all images exept one in drawble folder it loads as expected. Maybe I don't understand some concepts, could you please provide some explanations for this behavior

**Comment by daniel-luberda** [comment]
GIF's are very resource heavy, your device probably can't handle bigger sizes and it throws OOM exceptions. On the other hand, when you deleted larger assets, device uses the smaller ones and you don't get any OOMs.
