### ISSUE TITLE
Not available for Windows Phone 8.1 ?

### ISSUE THREAD

**Issue by NicolasR** [luberda-molinet/FFImageLoading#762]
Hello,

It seems FFImage control is not available anymore for wpa81 since version 2.2.14. 
Is it normal ?

Could not find any information about it.

**Comment by daniel-luberda** [comment]
@NicolasR Could you write more details? It should work, it was only depreciated in favour of  `MvxCachedImageView` / `MvxSvgCachedImageView`

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Windows/FFImage.cs

**Comment by NicolasR** [comment]
@daniel-luberda Steps to reproduce:

1. Create a new **uap8.1** project (Blank App on Universal Windows 8.1).
2. Add nuGet package **Xamarin.FFImageLoading** version **> 2.2.13**.

You can't use **FFImageLoading** or **MvxCachedImageView** because they don't exist on assembly.

Maybe an inclusion error on compilation ?

**Comment by daniel-luberda** [comment]
> Maybe an inclusion error on compilation ?

I don't think so, as the same dll is used on both WinRT and UWP (PCL Profile32). Any clues?

**Comment by NicolasR** [comment]
@daniel-luberda I decompiled dll, I can't find FFImageLoading or MvxCachedImageView inside.

**Comment by daniel-luberda** [comment]
Look at nuspec file, exact same dll is used for both platforms: 

```XML
        <!--Windows UWP-->
		<file src="FFImageLoading.Windows\bin\Release\FFImageLoading.Platform.dll" target="lib\uap10.0\FFImageLoading.Platform.dll" />
		<file src="FFImageLoading.Windows\bin\Release\FFImageLoading.Platform.xml" target="lib\uap10.0\FFImageLoading.Platform.xml" />
		<file src="FFImageLoading.Windows\bin\Release\FFImageLoading.Platform.pdb" target="lib\uap10.0\FFImageLoading.Platform.pdb" />
        <file src="FFImageLoading.Windows\bin\Release\FFImageLoading.dll" target="lib\uap10.0\FFImageLoading.dll" />
        <file src="FFImageLoading.Windows\bin\Release\FFImageLoading.xml" target="lib\uap10.0\FFImageLoading.xml" />
        <file src="FFImageLoading.Windows\bin\Release\FFImageLoading.pdb" target="lib\uap10.0\FFImageLoading.pdb" />

        <!--Windows RT-->
		<file src="FFImageLoading.Windows\bin\Release\FFImageLoading.Platform.dll" target="lib\win81+wpa81\FFImageLoading.Platform.dll" />
		<file src="FFImageLoading.Windows\bin\Release\FFImageLoading.Platform.xml" target="lib\win81+wpa81\FFImageLoading.Platform.xml" />
		<file src="FFImageLoading.Windows\bin\Release\FFImageLoading.Platform.pdb" target="lib\win81+wpa81\FFImageLoading.Platform.pdb" />
        <file src="FFImageLoading.Windows\bin\Release\FFImageLoading.dll" target="lib\win81+wpa81\FFImageLoading.dll" />
        <file src="FFImageLoading.Windows\bin\Release\FFImageLoading.xml" target="lib\win81+wpa81\FFImageLoading.xml" />
        <file src="FFImageLoading.Windows\bin\Release\FFImageLoading.pdb" target="lib\win81+wpa81\FFImageLoading.pdb" />
```

**Comment by daniel-luberda** [comment]
Is your project a net standard project?

**Comment by NicolasR** [comment]
What do you mean by .net standard ? It's a Windows Phone 8.1 project no UWP (I have a project with UWP too but don't have this problem on it).

This is what I get by decompiling dll version 2.2.20:

![ffimage](https://user-images.githubusercontent.com/206826/31619447-d2f03ec8-b294-11e7-9d6c-487f703626cd.png)

I will try to compile sources directly.

**Comment by daniel-luberda** [comment]
Somehow, VS is not picking `FFImageLoading.Platform.dll` file. Is your project compatible with PCL Profile32?

**Comment by daniel-luberda** [comment]
Somehow, VS is not picking correct `FFImageLoading.Platform.dll` file. Is your project compatible with PCL Profile32? It must be nuspec issue

**Comment by NicolasR** [comment]
How to check that my project is compatible PCL Profile 32 ? I don't know what that mean.
I tried to compile sources but failed. There seems to be Visual Studio 2015 and 2017 in same solution ? How is this possible ?

I did more tests: by creation Universal Windows 8.1 project, nuget uses portable-net45+win8+wpa81+wp8 library.

According to nuspec:

````XML
<!--Core PCL-->
<file src="FFImageLoading.Common\bin\Release\FFImageLoading.dll" target="lib\portable-net45+win8+wpa81+wp8\FFImageLoading.dll" />
<file src="FFImageLoading.Common\bin\Release\FFImageLoading.xml" target="lib\portable-net45+win8+wpa81+wp8\FFImageLoading.xml" />
<file src="FFImageLoading.Common\bin\Release\FFImageLoading.pdb" target="lib\portable-net45+win8+wpa81+wp8\FFImageLoading.pdb" />
<file src="FFImageLoading.Mock\bin\Release\FFImageLoading.Platform.dll" target="lib\portable-net45+win8+wpa81+wp8\FFImageLoading.Platform.dll" />
<file src="FFImageLoading.Mock\bin\Release\FFImageLoading.Platform.xml" target="lib\portable-net45+win8+wpa81+wp8\FFImageLoading.Platform.xml" />
````

**Comment by daniel-luberda** [comment]
Could you test newest 2.2.21.580 prerelease nuget and confirm if it's fixed?

**Comment by NicolasR** [comment]
Juste installed and it seems to have worked. Now it's using target "wpa81".

Thank you !
