### ISSUE TITLE
Question, Button.Image and SVG PCL [XF]

### ISSUE THREAD

**Issue by juanagu** [luberda-molinet/FFImageLoading#763]
It's possible set a svg (PCL) icon in button image property?

I try this code:

`<Button BackgroundColor="Transparent" VerticalOptions="Start" HorizontalOptions="Start" Image="ProjectName.Core.Resources.Images.arrow_back.svg, Converter={StaticResource SvgImageSourceConverter}}"/>`

But the icon not displayed.

**Comment by daniel-luberda** [comment]
No, it's not possible, we'll need to make a new implementation, eg. `CachedButton`. The only way is to use our `ImageService` API: 

```C#
var source = ImageSource.FromStream(async () =>
{
    return await ImageService.Instance
                                .LoadEmbeddedResource("ProjectName.Core.Resources.Images.arrow_back.svg")
                                .WithCustomDataResolver(new SvgDataResolver())
                                .AsPNGStreamAsync();
});
```

**Comment by juanagu** [comment]
I try using ImageService API but have a follow error:

Method 'FFImageLoading.Svg.Platform.SvgDataResolver..ctor' not found.
`System.IO.Stream stream = await ImageService.Instance
                                .LoadEmbeddedResource("Garzon.Core.Resources.Images.ic_add.svg")
                .WithCustomDataResolver(new SvgDataResolver())
                                .AsPNGStreamAsync();
`

**Comment by daniel-luberda** [comment]
You must do it in a platform specific code, I didn't add PCL implementation yet (but it should be easy to add this)

**Comment by sethom** [comment]
Is there a way to do this in PCL? I've got SvgDataResolver working in my PCL. However, how am I supposed to get a FileImageSource as opposed to the ImageSource which is returned by:

var natural = ImageSource.FromStream(async () =>
            {
                return await ImageService.Instance
                                            .LoadEmbeddedResource("Namespace.Resources.MyImage.svg")
                                         .WithCustomDataResolver(new SvgDataResolver())
                                         .CacheKey("Namespace.Resources.MyImage.svg") // better performance as it's using cache key
                                            .AsPNGStreamAsync();
            });
