### ISSUE TITLE
XamarinForms UWP Release with native toolchain: application hangs on startup

### ISSUE THREAD

**Issue by PavelK1988** [luberda-molinet/FFImageLoading#765]
![callstack](https://user-images.githubusercontent.com/32894627/31706562-a8814208-b3e9-11e7-9bbc-c9cd27dafb77.png)

Reproduced in 1 of 10 starts approximately.

Checked source code. Static constructor of UnitsExtensions calls InitResolutionScale(), and it looks like for some reason resolutionScale is not initialized and PointsToPixels() is waiting for it indefinitely.

Fixed by calling something like 0.0.PointsToPixels() or setting UnitsExtensions.resolutionScale via reflection before Xamarin.Forms.Forms.Init(e, assembliesToInclude); 
in UWP App.OnLaunched.

Do you know anything about this issue?
What is proper way to fix it?

Version 2.2.20

**Comment by daniel-luberda** [comment]
@PavelK1988 Yes, you're right. Nice catch. I already fixed it with: https://github.com/luberda-molinet/FFImageLoading/commit/23307b05b7f2093d37838be560872d81ba7b3ec1
