### ISSUE TITLE
Improve work scheduler in slow internet connection scenarios

### ISSUE THREAD

**Issue by JTOne123** [luberda-molinet/FFImageLoading#766]
Hi,
Here is an issue

I have 2 xamarin.forms pages:

The first page contains an image with too slow host (failed by 90m timeout)
<ffimageloading:CachedImage Source="{Binding SupperSlowHost_ImageUrl}" />

On the second page, there is <ffimageloading:CachedImage Source="icon.png" />

And I can not see the image on the second page before the first image will be uploaded or failed.

Is that correct behavior?

**Comment by daniel-luberda** [comment]
- By default only a several simultaneous tasks are allowed
- Max parallel tasks are set via config, the default is: `SchedulerMaxParallelTasks = Math.Min(4, Math.Max(2, (int)(Environment.ProcessorCount / 2d)));`

This is the current work scheduler algorithm: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Work/WorkScheduler.cs#L286-L298

Any ideas how could we improve it?

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/859
