### ISSUE TITLE
Advice / Feature Request Re: Fading

### ISSUE THREAD

**Issue by matjd** [luberda-molinet/FFImageLoading#767]
Is there any way to Fade Out or Cross Fade from one image to the next ?

I love the Fade In effect, but when I set a new image, the previous image disappears instantly leaving an odd persistence of vision effect.

**Comment by daniel-luberda** [comment]
FadeIn is already a cross fade effect, but the default behaviour is to not fade already cached images. Is it what you observed? Try to use a custom FFImageLoading configuration and set `FadeAnimationForCachedImages = true`. Does it solve your issue?

**Comment by matjd** [comment]
No difference.  Is there something wrong with my code ?

`Dim sources = From file In New System.IO.DirectoryInfo("Assets").GetFiles().AsParallel() Where ValidExtensions.Contains(file.Extension) Select file.FullName
            ImageService.Instance.Config.FadeAnimationDuration = 2000
            ImageService.Instance.Config.FadeAnimationForCachedImages = True
            For Each file As String In sources
                ImageService.Instance.LoadFile(file).Into(img1)
                Await Task.Delay(TimeSpan.FromSeconds(4))
            Next`

**Comment by daniel-luberda** [comment]
First of all. Don't set config on your own - it's meant to be used with `ImageService.Instance.Init` method only. You should use:

`ImageService.Instance.LoadFile(file).FadeAnimation(true, true, 2000).Into(img1)`

What platform is it?

**Comment by matjd** [comment]
It's a UWP project.

I tried your code and it's still not crossfading.
Any ideas ?

**Comment by daniel-luberda** [comment]
Here's the current code for fade effect on Windows: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Windows/Targets/ImageTarget.cs#L51-L68

Any ideas?

**Comment by matjd** [comment]
That looks like fadeIn, not FadeOut, or am I missing something ?

**Comment by daniel-luberda** [comment]
It may be, I don't use Windows very often. I made this code a long time ago and don't remember details. Any suggestions are welcome.

**Comment by matjd** [comment]
Do you recall if there is a section of code that handles disposing of the image ?

**Comment by daniel-luberda** [comment]
Could you elaborate?

**Comment by matjd** [comment]
Any code that cleans up when the image source changes.  An ImageSourceChanging event would be a good place to put a fadeout animation.

**Comment by daniel-luberda** [comment]
The method I send you is used right before changing image to another source, so it's a correct place for that.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/858
