### ISSUE TITLE
Not working when you change ImageSource type

### ISSUE THREAD

**Issue by ignasbagdonas** [luberda-molinet/FFImageLoading#768]
On Xamarin.Forms (Android) set Binding to ImageSource property. Then in your vm set ImageSource.FromUri(); Everything works fine. Then you take photo with camera and set the same property ImageSource.FromFile(); Image from uri still showing and your new image not.

**Comment by daniel-luberda** [comment]
You'll need to provide some reproduction as bindings / changing image source works just fine in our samples. Maybe it's something with you `INotifyPropertyChanged` implementation?
