### ISSUE TITLE
FFImageLoading in PCL project

### ISSUE THREAD

**Issue by nikolaypopadiuksigma** [luberda-molinet/FFImageLoading#769]
Hello, we use FFImageLoading v 2.2.20.

In PCL project we add only Preload in this way 
` ImageService.Instance.LoadUrl(image.ImageUrl)
                        .Retry(3, 200)
                        .Success(
                        (imageInformation, loadingResult) =>
                        {
                            if (loadingResult == FFImageLoading.Work.LoadingResult.Internet
                            || loadingResult == FFImageLoading.Work.LoadingResult.DiskCache
                            || loadingResult == FFImageLoading.Work.LoadingResult.MemoryCache)
                            {
                                this.ICommunicationService.DBTransport.RemoveCachedImage(image);
                            }
                        })
                        .PreloadAsync();`
on platform we add logic for view.

For Core and platforms we add FFImageLoading from nuget.

And it's work fine if we run build  from Visual Studio 2017, but on CI i need run build from command line.
At first i call restore packages in folder with .sln file

`PS C:\...\>....\MSBuild.exe /t:Restore /p:Configuration=Release`

and this task ends without any errors. After that I try build solution 

`PS C:\...\>....\MSBuild.exe /t:Rebuild /p:Configuration=Release`

and i get error 

"C:\....\XamarinProject.sln" (Rebuild target) (1) ->
"...\XamarinProjectCore\XamarinProject-Core.csproj" (Rebuild target) (2) ->
(CoreCompile target) ->
  Operations\Images\CacheUrlImagesOperations.cs(5,7): error CS0246: The type or namespace name 'FFImageLoading' could not be found (are you missing a using directive or an
assembly reference?) [C:\...\XamarinProject.Library.Core\XamarinProject-Core.csproj]`

But I added FFImageLoading to core in nuget, and see in .csproj and packages.config files.
Also I try add .dlls manually to core project. but it doesn't have any effect

Do you have any ideas way it's work from VisualStudio and don't work from command line?

**Comment by daniel-luberda** [comment]
Look at our AppVeyor build script: https://github.com/luberda-molinet/FFImageLoading/blob/master/MakefileAll.bat

You should call:

```
nuget restore -MsbuildPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
dotnet restore
```

**Comment by daniel-luberda** [comment]
I'll close this one as it's not related to FFImageLoading. Also remember to add FFImageLoading packages to the platform specific projects too. Cheers.
