### ISSUE TITLE
Synchronize loading / generation of bitmap

### ISSUE THREAD

**Issue by Nick1611** [luberda-molinet/FFImageLoading#770]
I am using FFImageLoading in my mvx project. It works great when loading recyclerview. I have an issue when I tried to create downsample bitmaps from a bunch of local files. The bitmap is required immediately to proceed for map marker generation. 

Not sure if I misunderstood something, I found image is not available after the return of both statements:
- ImageService.Instance.LoadFile(xxx).DownSample(width: xxx).Into(imageViewAsync)
- await ImageService.Instance.LoadFile(xxx).DownSample(width: xxx).IntoAsync(imageViewAsync)

The only time that I can use imageViewAsync is after the trigger of .Finish(xxx). However, it is trigger only after the UI thread is free, i.e. after the execution of my current code completes. In that case, I have trouble when I need to load for a consecutive number of times. I spent days to find a workaround with no luck.

Similar to an old issue #59, I need a solution to generate a bitmap synchronizely with dowmsample feature. I guess the solution there was a bit out dated that I am not able to implement. Is there any solution that I can implement with the current version?

Thank you very much for the great work.

**Comment by daniel-luberda** [comment]
Currently, you should use:

- `await ImageService.Instance.LoadFile(xxx).DownSample(width: xxx).AsBitmapDrawableAsync()` for Android
- `await ImageService.Instance.LoadFile(xxx).DownSample(width: xxx).AsUIImageAsync()` for iOS
- `await ImageService.Instance.LoadFile(xxx).DownSample(width: xxx).AsBitmapDrawableAsync()` for Windows (yeah I noticed bad naming, we should change it in future)

**Comment by Nick1611** [comment]
Perfect. Thank you very much.
