### ISSUE TITLE
You are referencing the Portable version in your App - you need to reference the platform

### ISSUE THREAD

**Issue by sanphir** [luberda-molinet/FFImageLoading#771]
I install FFImageLoading v2.20 using nuget. And application was crashed and in stack trace i found this path:
```
"at FFImageLoading.Forms.CachedImage..cctor () [0x00235] in C:\projects\ffimageloading\source\FFImageLoading.Forms\CachedImage.cs:275 "
"...
/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:667 "
```
I do not even have such folders. Looks like it hardcoded

**Comment by sanphir** [comment]
10-20 15:51:09.572 I/MonoDroid(23272): UNHANDLED EXCEPTION:
10-20 15:51:09.620 I/MonoDroid(23272): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'FFImageLoading.Forms.CachedImage' threw an exception. ---> System.Exception: You are referencing the Portable version in your App - you need to reference the platform (iOS/Android) version
10-20 15:51:09.620 I/MonoDroid(23272):   at FFImageLoading.ImageService.get_Instance () [0x00000] in <859dc26eef474ce9baaf88461e867c61>:0 
10-20 15:51:09.621 I/MonoDroid(23272):   at FFImageLoading.Forms.CachedImage..cctor () [0x00235] in C:\projects\ffimageloading\source\FFImageLoading.Forms\CachedImage.cs:275 
10-20 15:51:09.621 I/MonoDroid(23272):    --- End of inner exception stack trace ---
10-20 15:51:09.621 I/MonoDroid(23272):   at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
10-20 15:51:09.621 I/MonoDroid(23272):   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:661 
10-20 15:51:09.621 I/MonoDroid(23272):    --- End of inner exception stack trace ---
10-20 15:51:09.621 I/MonoDroid(23272):   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00012] in /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:667 
10-20 15:51:09.622 I/MonoDroid(23272):   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/corlib/ReferenceSources/RuntimeType.cs:179 
10-20 15:51:09.622 I/MonoDroid(23272):   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/corlib/ReferenceSources/RuntimeType.cs:153 
10-20 15:51:09.622 I/MonoDroid(23272):   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/referencesource/mscorlib/system/rttype.cs:5639 
10-20 15:51:09.622 I/MonoDroid(23272):   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00039] in /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/referencesource/mscorlib/system/activator.cs:201 
10-20 15:51:09.622 I/MonoDroid(23272):   at System.Activator.CreateInstance (System.Type type) [0x00000] in /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/referencesource/mscorlib/system/activator.cs:134 
10-20 15:51:09.622 I/MonoDroid(23272):   at Xamarin.Forms.Xaml.CreateValuesVisitor.Visit (Xamarin.Forms.Xaml.ElementNode node, Xamarin.Forms.Xaml.INode parentNode) [0x001c0] in <128e7066980a4543b3be698424e552c8>:0 
10-20 15:51:09.623 I/MonoDroid(23272):   at Xamarin.Forms.Xaml.ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x000b5] in <128e7066980a4543b3be698424e552c8>:0 
10-20 15:51:09.623 I/MonoDroid(23272):   at Xamarin.Forms.Xaml.ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x0008c] in <128e7066980a4543b3be698424e552c8>:0 
10-20 15:51:09.623 I/MonoDroid(23272):   at Xamarin.Forms.Xaml.RootNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00067] in <128e7066980a4543b3be698424e552c8>:0 
10-20 15:51:09.623 I/MonoDroid(23272):   at Xamarin.Forms.Xaml.XamlLoader.Load (Xamarin.Forms.BindableObject view, System.String xaml) [0x000a5] in <128e7066980a4543b3be698424e552c8>:0 
10-20 15:51:09.623 I/MonoDroid(23272):   at Xamarin.Forms.Xaml.XamlLoader.Load (Xamarin.Forms.BindableObject view, System.Type callingType) [0x0002b] in <128e7066980a4543b3be698424e552c8>:0 
10-20 15:51:09.623 I/MonoDroid(23272):   at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TView] (TView view, System.Type callingType) [0x00000] in <128e7066980a4543b3be698424e552c8>:0 
10-20 15:51:09.624 I/MonoDroid(23272):   at AppAsService.Client.Module.Base.PhotoPageTemplate.InitializeComponent () [0x00001] in I:\Projects\AppFactorieNew\Src\AppAsService.Client.Module.Base\obj\Debug\AppAsService.Client.Module.Base.Templates.PhotoPageTemplate.xaml.g.cs:24 
10-20 15:51:09.624 I/MonoDroid(23272):   at AppAsService.Client.Module.Base.PhotoPageTemplate..ctor () [0x00008] in I:\Projects\AppFactorieNew\Src\AppAsService.Client.Module.Base\Templates\PhotoPageTemplate.xaml.cs:13 
10-20 15:51:09.624 I/MonoDroid(23272):   at AppAsService.Client.Module.Base.PhotosMetaData.GetListSingleEditItemTemplate () [0x00001] in I:\Projects\AppFactorieNew\Src\AppAsService.Client.Module.Base\Module\PhotosMetaData.cs:41 
10-20 15:51:09.624 I/MonoDroid(23272):   at AppAsService.Share.Common.ModulesController.FindListSinglePageTemplateByName (System.String pName) [0x00029] in I:\Projects\AppFactorieNew\Src\Share\AppAsService.Share.Base\Modules\ModulesController.cs:71 
10-20 15:51:09.624 I/MonoDroid(23272):   at AppAsService.Share.Common.ViewModel.BaseListViewTemplateViewModel`1[T].get_ListSinglePageTemplate () [0x00001] in I:\Projects\AppFactorieNew\Src\Share\AppAsService.Share.Base\ViewModel\BaseListViewTemplateViewModel.cs:126 
10-20 15:51:09.624 I/MonoDroid(23272):   at AppAsService.Share.Common.ViewModel.BaseListViewTemplateViewModel`1[T].OnElementTapped (AppAsService.Share.Dal.Content.Abstract.AbstractDataElement pElement) [0x0001d] in I:\Projects\AppFactorieNew\Src\Share\AppAsService.Share.Base\ViewModel\BaseListViewTemplateViewModel.cs:329 
10-20 15:51:09.624 I/MonoDroid(23272):   at AppAsService.Share.Common.Templates.BaseListViewGridOfPhotoPageTemplate.OnItemTapped (System.Object sender, Xamarin.Forms.ItemTappedEventArgs e) [0x00019] in I:\Projects\AppFactorieNew\Src\Share\AppAsService.Share.Base\Templates\ListTemplates\BaseListViewGridOfPhotoPageTemplate.xaml.cs:31 
10-20 15:51:09.625 I/MonoDroid(23272):   at AppAsService.Share.Common.Framework.Forms.ColumnGrid.OnItemTapped (System.Object pItem) [0x00001] in I:\Projects\AppFactorieNew\Src\Share\AppAsService.Share.Base\Framework\Forms\ColumnGrid.cs:435 
10-20 15:51:09.625 I/MonoDroid(23272):   at AppAsService.Share.Common.Framework.Forms.ColumnGrid.AnimationFinished (System.Object sender, System.EventArgs e) [0x00055] in I:\Projects\AppFactorieNew\Src\Share\AppAsService.Share.Base\Framework\Forms\ColumnGrid.cs:350 
10-20 15:51:09.625 I/MonoDroid(23272):   at AppAsService.Share.Common.Framework.Forms.AnimatedGrid+<RunBoxSelectAnimation>d__3.MoveNext () [0x002fc] in I:\Projects\AppFactorieNew\Src\Share\AppAsService.Share.Base\Framework\Forms\AnimatedGrid.cs:93 
10-20 15:51:09.625 I/MonoDroid(23272): --- End of stack trace from previous location where exception was thrown ---
10-20 15:51:09.625 I/MonoDroid(23272):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151 
10-20 15:51:09.625 I/MonoDroid(23272):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
10-20 15:51:09.626 I/MonoDroid(23272):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in /Users/builder/data/lanes/5147/7a6a056e/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:35 
10-20 15:51:09.626 I/MonoDroid(23272):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in /Users/builder/data/lanes/5147/7a6a056e/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
10-20 15:51:09.626 I/MonoDroid(23272):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in /Users/builder/data/lanes/5147/7a6a056e/source/xamarin-android/src/Mono.Android/obj/Release/android-26/mcw/Java.Lang.IRunnable.cs:81 
10-20 15:51:09.626 I/MonoDroid(23272):   at (wrapper dynamic-method) System.Object:91c19d0f-ef28-4e33-a3fe-3973ca21e14e (intptr,intptr)

**Comment by daniel-luberda** [comment]
The error is self explanatory: `System.Exception: You are referencing the Portable version in your App - you need to reference the platform (iOS/Android) version` 

You need to add FFImageLoading nuget packages to the platform specific projects too.
