### ISSUE TITLE
MvxCachedImageView  binding issue

### ISSUE THREAD

**Issue by Nick1611** [luberda-molinet/FFImageLoading#773]
I am building a solution with Xamarin.Android. It uses MvxCachedImageView in MvxRecycler. While it is running on emulator with small pictures from emulator camera, it looks fine. Once I tested it on real phone with some real pictures, the app crashed after a few pages loading in the recycler. 

When I check the debug log, I found that binding for DownSampleWidth is not working. This is the binding in the axml and the message in debug log.

```
    <ffimageloading.cross.MvxCachedImageView
        android:layout_width="@dimen/listitem_route_picture_image_size"
        android:layout_height="@dimen/listitem_route_picture_image_size"
      local:MvxBind="LoadingPlaceholderImagePath 'res:ic_image_grey_700_48dp.png'; ErrorPlaceholderImagePath 'res:ic_error_outline_grey_700_48dp.png'; Transformations Transformations; DownSampleWidth DownSampleWidth; ImagePath PicturePath" />

```

[0:] MvxBind:Warning: 31.15 Failed to create target binding for binding DownSampleWidth for DownSampleWidth

I thought it was an issue with my project at first. However, I found that the DownSampleWidth error also happens in the GitHub sample project. Scrolling down the recycler would also cause loading errors.

The crashing and loading error are most likely due to pictures are not downsampled.

My questions:
1. Would that be something missing in my environment that caused this binding issue? 
2. Is it possible to specify TransparencyChannel in axml?
3. Is it possible to specify DownSampleWidth with resource dimension (@dimen/listitem_route_picture_image_size) instead of hardcoded width in pixel in the class object?

Thank you very much.

**Comment by daniel-luberda** [comment]
Hi @Nick1611,

What is the `DownSampleWidth` property type in your view model? 

>[0:] MvxBind:Warning: 31.15 Failed to create target binding for binding DownSampleWidth for DownSampleWidth

IMO it's rather an issue with MvvmCross than FFImageLoading. 

>Is it possible to specify TransparencyChannel in axml?

This property is depreciated, you should use `BitmapOptimizations` property instead. By default FFImageLoading disables transparency channel if it's not needed, but if the image has transparency channel, it's enabled. 

>Is it possible to specify DownSampleWidth with resource dimension () instead of hardcoded width in pixel in the class object?

Yes, just set `DownsampleUseDipUnits = true`, then density independent points are used

**Comment by Nick1611** [comment]
it is the same as in the github sample:

        public double DownSampleWidth => 200d;

Initially I tried to resolve it from the mvx issue direction too. All other bindings are good except this one. Later on, I found the same error in the sample project.

**Comment by daniel-luberda** [comment]
@Nick1611 Does it work when you disable linking?

**Comment by Nick1611** [comment]
Hi Daniel,

Linking was disabled!

I got a clue from your last answer and looked into the implementation of MvxCachedImageView. The field is defined as DownsampleWidth in MvxCachedImageView, not DownSampleWidth. It would be good to update the sample axml. 

Thank you very much for your great support again. Can't get the same level even with paid service.

**Comment by daniel-luberda** [comment]
Nice catch! Thanks :)
