### ISSUE TITLE
CachedImage Source binding in XAML for a resource:// url throwing errors

### ISSUE THREAD

**Issue by quinnhoener** [luberda-molinet/FFImageLoading#774]
When trying to bind a CachedImage in XAML for Xamarin Forms, I'm getting the following error:

```
Image loading failed: resource://ProjectName.Path.To.Image.png
FFImageLoading.DownloadAggregateException: One or more errors occurred. ---> System.ArgumentException: Only http or https scheme is allowed
```

The stack trace reveals this as the FFImageLoading point where the error occurs:
``` 
FFImageLoading.Cache.DownloadCache+<DownloadAsync>d__17.MoveNext () [0x0006c] in C:\projects\ffimageloading\source\FFImageLoading.Common\Cache\DownloadCache.cs:100
```

Here is the Xaml code:
``` XML
<ffimageloading:CachedImage HorizontalOptions="Center" 
                    VerticalOptions="Center" 
                    WidthRequest="100" HeightRequest="100" 
                    Aspect="AspectFit"
                    Source="{Binding ImageSource}" />
```

The ViewModel Code:
``` C#
ImageSource = "resource://ProjectName.Path.To.Image.png";
```

I can however explicitly do the Source like this and the image will load properly:
``` XML
<ffimageloading:CachedImage HorizontalOptions="Center" 
                    VerticalOptions="Center" 
                    WidthRequest="100" HeightRequest="100" 
                    Aspect="AspectFit"
                    Source="resource://ProjectName.Path.To.Image.png" />
```

**Comment by daniel-luberda** [comment]
Could you try the newest prerelease? (2.2.21.583)

**Comment by quinnhoener** [comment]
Just updated to 2.2.21.583 and still seeing the errors on both iOS and Android.

**Comment by daniel-luberda** [comment]
@quinnhoener 

- Did you remove all bin / obj folders from your projects & cleaned solution? 
- Is your `ViewModel` in the same assembly?

**Comment by ArtjomP** [comment]
I have the same issue with version 2.2.24. Have you @quinnhoener found a way to solve it.

**Comment by ArtjomP** [comment]
@daniel-luberda 
1. I cleaned my solution

**Comment by ArtjomP** [comment]
I avoided the issue this way:
`  <ContentView Grid.Column="0" Grid.Row="0" 
                                     Content="{Binding ImageFilename, Converter={StaticResource ImageSourceConverter}}"/>
`

`
internal sealed class FFImageSourceConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var sourceString = value as String;
            return new CachedImage()
            {
                HorizontalOptions = LayoutOptions.Center,
                VerticalOptions = LayoutOptions.Center,
                WidthRequest = 48,
                HeightRequest = 48,
                DownsampleToViewSize = true,
                Source = new EmbeddedResourceImageSource(new Uri(sourceString)),
            };
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
`

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/wiki/Data-URL-&-Embedded-Resources-support-(including-base64)#embedded-resources-uri-support

Use this when using images from another assembly:

`resource://{resourceName}?assembly={Uri.EscapeUriString(resourceAssembly.FullName)}";`

**Comment by quinnhoener** [comment]
@daniel-luberda I can confirm this is still an issue with version 2.2.24. I believe @ArtjomP and I are attempting the same thing which exactly as described in the initial details. Setup a XAML page and bind the the CachedImage Source to a code behind property.
```
Source="{Binding ImageSource}"
```

In the code behind, set the ImageSource string property to a resource url:
```
ImageSource = "resource://ProjectName.Path.To.Image.png";
```

You will see this error:
```
System.ArgumentException: Only http or https scheme is allowed
```

Doing a binding directly in XAML code will work properly with a resource url.
```
<ffimageloading:CachedImage HorizontalOptions="Center" 
                    VerticalOptions="Center" 
                    WidthRequest="100" HeightRequest="100" 
                    Aspect="AspectFit"
                    Source="resource://ProjectName.Path.To.Image.png" />
```

For how I'm using images, I'm dynamically changing the image based on user settings so it needs to be bound to a code behind property.

**Comment by quinnhoener** [comment]
@ArtjomP I needed to dynamically swap between local assets and web assets and adjusted your Converter like this:

```
public class FFImageSourceConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var sourceString = value as String;

            if ( sourceString.StartsWith("resource://", StringComparison.OrdinalIgnoreCase) )
            {
                return new EmbeddedResourceImageSource(new Uri(sourceString));
            }
            else
            {
                return new DataUrlImageSource(sourceString);
            }
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
```

Then in XAML code you can do this:
```
<ffimageloading:CachedImage HorizontalOptions="Center"
                        HeightRequest="72"
                        Aspect="AspectFit"
                        Source="{Binding ImageUrl, Converter={StaticResource imageSource}}" />
```

I hope this helps!

**Comment by stesvis** [comment]
I solved it like this:
XAML
`<ffimageloadingsvg:SvgCachedImage Source="{Binding GuidesFilterImage}" WidthRequest="{StaticResource dashIconSize}" HeightRequest="{StaticResource dashIconSize}"></ffimageloadingsvg:SvgCachedImage>`

ViewModel

```
        private EmbeddedResourceImageSource _guidesFilterImage;
        public EmbeddedResourceImageSource GuidesFilterImage
        {
            get { return _guidesFilterImage; }
            set { SetProperty(ref _guidesFilterImage, value); }
        }

GuidesFilterImage = new EmbeddedResourceImageSource(new Uri("resource://VeloGuideApp.Resources.Images.dash_guest_ic_guides.svg"));
```
