### ISSUE TITLE
SVG from PCL in UWP absent

### ISSUE THREAD

**Issue by helzgate** [luberda-molinet/FFImageLoading#779]
Do svg's work loaded from PCL in a UWP app?  I have this working fine in iOS and Android but it won't load in a UWP app.  If it does work, what is the minimum code required in the MainPage.xaml.cs (or App.xaml.cs)?  I see the code in the sample app so I tried to implement it but no svg image loads and there are no errors.

I'm using a brand new project in Visual Studio 2017 that does noting but load a single page with an SVG image.  I'm not using any mvvm frameworks or anything advanced yet.

Xamarin.FFImageLoading.Svg.Forms version 2.2.22

Thanks!

**Comment by helzgate** [comment]
Never mind.  Found that I had to install SkiaSharp 1.59.1 within my UWP app then everything worked.

**Comment by EmilAlipiev** [comment]
thanks for that. i didnt recognize that ffimageloading package doesnt install it as dependency on UWP. @daniel-luberda  maybe it needs to extended in notes. I guess that it is a general issue with falls creaters update of UWP

**Comment by JTOne123** [comment]
Should I install only this one nuget Install-Package SkiaSharp -Version 1.60.1 ?

It does not work, maybe I missed something?

**Comment by JTOne123** [comment]
I've figured out where the issue is! No need a skiasharp with latest ffimage. But in the version 2.4.1.823 something is broken, with 2.3.6 everything works well.

**Comment by kyurkchyan** [comment]
@JTOne123 thanks, was having the same issue. Downgraded to 2.3.6 and everything worked auto-magically :)

**Comment by themultiplexer** [comment]
Same problem here. Is there an ETA for a fix or a prerelease?

**Comment by daniel-luberda** [comment]
Fixed. Stable nuget today.
