### ISSUE TITLE
Grayscale / Sepia transformations don't preserve transparency channel

### ISSUE THREAD

**Issue by peejz** [luberda-molinet/FFImageLoading#780]
Hi,

I have a .png image that has some transparency on it and I'm loading it with FFImageLoading and the image appears correctly on both android and ios.

When I add a grayscale transformation on the image the transparent parts turn black on ios. On android all is fine. I've tried adding the transformation with both xaml and C#.

Any ideas?

im using v2.2.22 and Xamarin.Forms v2.4.0.282

**Comment by daniel-luberda** [comment]
It should be fixed now. Prerelease nuget soon.

**Comment by daniel-luberda** [comment]
You can test it in 2.2.23 prerelease, please let me know if it's working.

**Comment by peejz** [comment]
Its working now.

Thanks Daniel.
