### ISSUE TITLE
Memory Leak In Xamarin Forms CachedImage

### ISSUE THREAD

**Issue by john-larson** [luberda-molinet/FFImageLoading#782]
Here is the scenario I followed:

Get an image from Android photo gallery as a byte array (possibly a downsampled size of 3MP). Create a CachedImage with `DownsampleWidth = 100` and `DownsampleUseDipUnits = true`. Set the source of the `CachedImage  as photo.Source = ImageSource.FromStream(() => new MemoryStream(photoByteArray))`.  Add this CachedImage to an empty StackLayout. 

Repeat the steps above 10 times. Then remove all the images from the StackLayout (possibly by tapping on each).

I used Android Studio to track memory usage. App starts with 11.66 MB and ends with 14.66 MB. Removing the images has no effect, it does not reduce the memory back. I manually triggered Garbage collection from Android Studio.

Plus, I also tried `FFImageLoading.Forms.CachedImage.InvalidateCache(photo.Source, FFImageLoading.Cache.CacheType.Memory, true); `and it had no effect either.

**Comment by daniel-luberda** [comment]
I don't think there's a memory leak. Try `ImageService.Instance.InvalidateMemoryCache()` instead. 

 The thing is you're using `StreamImageSource`. When no custom key factory is provided `Stream` key is a stream md5 hash, so to remove stream image source from cache, you need to do something like this: `FFImageLoading.Forms.CachedImage.InvalidateCache(streamMD5hashValue, FFImageLoading.Cache.CacheType.Memory, true);`

I strongly advice you to use custom cache key factory for stream image sources.

**Comment by john-larson** [comment]
After your suggestion, I used a Guid string for the cache key in the CacheKeyFactory since I do not need caching for these images. Then I did `FFImageLoading.Forms.CachedImage.InvalidateCache(guidString, FFImageLoading.Cache.CacheType.Memory, true`).  It did not solve the problem. Strangely, now memory usage increased to 16.87 MB. By the way I am using version 2.2.9. Is there a memory leak problem resolved since then?

**Comment by daniel-luberda** [comment]
>  since I do not need caching for these images

So why don't you disable memory cache then? `cachedImage.CacheType = CacheType.Disk`

>  I used a Guid string for the cache key in the CacheKeyFactory

That's even worse for memory usage, as every image will have an unique cache key and won't be reused

>By the way I am using version 2.2.9. Is there a memory leak problem resolved since then?

There's a lot of issues resolved after 2.2.9, it's not supported anymore.

**Comment by john-larson** [comment]
I updated FFImageLoading to the latest version and disabled caching by using `cachedImage.CacheType = CacheType.Disk `as per your suggestion. My two observations:

1. My application was starting with a memory usage of around 11 MB, now it rose to 28 MB. Is it normal for the plugin update to increase the initial memory usage like this?
2. I tested the scenario again. After adding 10 images, memory increased form 28.41 MB to 33.37 MB. And after removing the images and doing a garbage collection, nothing changed. It seems to be related to the image view renderers and their bitmaps not being disposed rather than a cache issue.

**Comment by daniel-luberda** [comment]
> My application was starting with a memory usage of around 11 MB, now it rose to 28 MB. Is it normal for the plugin update to increase the initial memory usage like this?

How do you tell it's plugin using the memory, not other things? There's a lot of other things that may take the space, as Xamarin.Forms Views / Renderers, native system bitmap caching (of which you don't have control) and many many more things.

**Comment by john-larson** [comment]
It was always starting out with around 11 MB of memory usage, and right after just updating FFImageLoading, it rose to 28 MB. There was no other change I did.

**Comment by daniel-luberda** [comment]
That's not enough info. With Xamarin profiler you're able to see details with a list of objects memory usage. Could you provide that?

**Comment by john-larson** [comment]
Unfortunately I am not allowed to share dumps due to corporate privacy policies. But reverting back to version 2.2.9 made the initial memory usage back to 11 MB again, so we will continue using that I guess since the latest version did not solve the memory not being released issue either.

**Comment by daniel-luberda** [comment]
It's not possible that FFImageLoading is taking additional 10MB in memory when no images are loaded. I'm quite sure of it. It must be something different.  This project is used in many projects (from small to large ones) and there are no currently known memory leaks or some strange additional memory usage between versions. I'll need some reproduction to help you. Please reopen if you'll have some more info. Cheers.
