### ISSUE TITLE
Memory Leak In Xamarin Forms CachedImage When Using Grid

### ISSUE THREAD

**Issue by john-larson** [luberda-molinet/FFImageLoading#783]
Here is the scenario I followed:

Get an image from Android photo gallery as a byte array (possibly a downsampled size of 3MP). Create a CachedImage with DownsampleWidth = 100 and DownsampleUseDipUnits = true. Set the source of the CachedImage as photo.Source = ImageSource.FromStream(() => new MemoryStream(photoByteArray)). Then add this to a `List<CachedImage> photoViews` list.

After each addition or removal, update the Grid with the following code:

```
        public void ArrangePhotoViews()
        {
            photosGrid.Children.Clear();
            int row = 0;
            int column = 0;
            for (int i = 0; i < photoViews.Count; i++)
            {
                photosGrid.Children.Add(photoViews[i], column, row);
                if(column == 0)
                {
                    column = 1;
                }
                else if(column == 1)
                {
                    column = 0;
                    row++;
                }
            }
        }
```

I used Android Studio to track memory usage. Every time `ArrangePhotoViews `is called, regradless whether it is an addition or a removal operation, memory increases as if every photo in the list is newly being created and added to the grid.

**Comment by daniel-luberda** [comment]
What version of FFImageLoading?

**Comment by john-larson** [comment]
I tested it with the latest version: 2.2.22. Application starts with 27.26 MB. After adding 10 photos, it becomes 35.22 MB. And after removing all 10 photos, it is 51.90 MB.

**Comment by daniel-luberda** [comment]
What is you cached image code? 

Please mind that by default, FFImageLoading caches bitmaps in memory for future usage and it's completely normal to use some ram for that. 

BTW: removing a view from grid doesn't guarantee to dispose it immediately.

**Comment by john-larson** [comment]
I was mistaken to think that Android Monitor's Garbage Collect button would also trigger a garbage collection on Xamarin (.Net) side. After using GC.Collect() from code, I saw that there was no leak.

**Comment by daniel-luberda** [comment]
Nice to hear that you sort it out 👍 Cheers

**Comment by EmilAlipiev** [comment]
@john-larson  in which part of your code do you use GC.Collect() ? I mean how do you generally clean cache images. For example, I have listview on my page, when I pop from that page, i want to clean memory for all cached images. what is the suggested way to do this?

**Comment by john-larson** [comment]
@EmilAlipiev I manually forced garbage collection just to test the memory usage, that was not meant for managing caching. As far as I understand, what you are trying to do is to clear the cache. @daniel-luberda  has recommended me to use the ImageService.Instance.InvalidateMemoryCache() method of the library for that purpose in another thread(see https://github.com/luberda-molinet/FFImageLoading/issues/782). But I would not want to misguide you as I am not an expert on the library. You can find the documentation here: https://github.com/luberda-molinet/FFImageLoading/wiki
