### ISSUE TITLE
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by StanleyBroo** [luberda-molinet/FFImageLoading#784]
Hi! Have tired this three times now with different projects, listview, basicpage with one image etc. All the latest stable Nuget for FFImageLoading and Xamarin.Forms and all implemented as suggested ..but still: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. Any idea what is going on?

MainActivity.cs...
using FFImageLoading.Forms.Droid;
	base.OnCreate (bundle);
            CachedImageRenderer.Init();

XAML Contentpage...
xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
xmlns:fftransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
   
 <ffimageloading:CachedImage WidthRequest="300" HeightRequest="300"
DownsampleToViewSize="true" Source="https://i.ytimg.com/vi/eip9pC11q0o/maxresdefault.jpg">
    </ffimageloading:CachedImage>

**Comment by daniel-luberda** [comment]
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. Any idea what is going on?

I don't know, it may a lot of things, like: 

- Try to remove all `bin`/`obj` directories in all projects, then clean & rebuild
- Try to disable Xamarin linker or reference `CachedImage` somewhere in code (not only in XAML)
- Make sure you added packages in all projects, shared & platform specific
