### ISSUE TITLE
 ffimageloading:CachedImage not found in xmlns clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms

### ISSUE THREAD

**Issue by altroviswisnu** [luberda-molinet/FFImageLoading#786]
Hey @daniel-luberda ,

I suddenly got error  ffimageloading:CachedImage not found in xmlns clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms , Everything was fine until last week, but my app suddenly crushed with that error. The Error only occur in iOS, in Android it works just fine. I don't use any transformation, just use it for loading image. 

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             x:Class="Smart.Views.LoginPage">
	<RelativeLayout>
        <ffimageloading:CachedImage Source="bg.png" Aspect="AspectFill" 
            RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width}" 
            RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height}"/>
 </RelativeLayout>
</ContentPage> 
```

Thx in advance

**Comment by daniel-luberda** [comment]
I don't know, it may a lot of things, like:

- Try to remove all bin/obj directories in all projects, then clean & rebuild
- Try to disable Xamarin linker or reference CachedImage somewhere in code (not only in XAML)
- Make sure you added packages in all projects, shared & platform specific

**Comment by daniel-luberda** [comment]
Also try the newest 2.2.23 package (it fixed some issues too). Please reopen if you'll still experience it.

**Comment by brux88** [comment]
hi, i have the same error. i use the 2.2.24 version.
how can i fix?

**Comment by brux88** [comment]
hi, i have the same error with version 2.2.24 on ios.
How cani fix?

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/786#issuecomment-340394428

**Comment by brux88** [comment]
I just tried but, always the same problem

**Comment by daniel-luberda** [comment]
Make a reproduction then and I'll try to help.

**Comment by brux88** [comment]
hello, i did some tests.
I tried to remove the plugin and install it again, but now I do not work on android:
```
                     <forms:CachedImage Aspect="Fill" HorizontalOptions="Fill" VerticalOptions="Fill"
							            DownsampleHeight="100" DownsampleUseDipUnits="false" 						
							            Source="{Binding ico_mobile}"/> 
```
![2017-11-13_2037](https://user-images.githubusercontent.com/3495339/32745274-87f6a842-c8b2-11e7-9f73-4850a5839ca7.png)

on ios i set  Xamarin linker  = Don't Link but not work :(

**Comment by brux88** [comment]
hello, i did some tests.
I tried to remove the plugin and install it again, but now I do not work on android
```

             xmlns:forms="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
......
                               <forms:CachedImage Aspect="Fill" HorizontalOptions="Fill" VerticalOptions="Fill"
							            DownsampleHeight="100" DownsampleUseDipUnits="false" 						
							            Source="{Binding ico_mobile}"/> 
```
![2017-11-13_2037](https://user-images.githubusercontent.com/3495339/32745875-56f1de5e-c8b4-11e7-8fce-16fdd62fb18b.png)


and on ios the same error

**Comment by altroviswisnu** [comment]
this is what I did, I removed CachedImageRenderer.Init() in AppDelegate, then rebuild the project, add it back, rebuild again. I don't know why, but somehow it works for me.

**Comment by stesvis** [comment]
I am still having this issue.
But only when I reference it in XAML. The xmlns doesn't throw any error, only when I try to use it.
Also, when I start typing `<ffim`.. it gives me intellisense, but at this point `ffimageloading:` it doesn't find anything else, so it won't let me use `CachedImage`.

I cleaned, rebuilt, deleted obj/bin....no luck.
