### ISSUE TITLE
Blurred Image is working in Xamarin Android but not in Xamarin iOS.

### ISSUE THREAD

**Issue by TheIncredibleIllmo** [luberda-molinet/FFImageLoading#789]
Hi I have a special case where Blurred image is working in Xamarin.Android but in Xamarin.iOS it is not, so I tried to upgrade and downgrade the version of the nuget in Xamarin, but it doesn't work for iOS, even I tried to update Xamarin.Forms version to the newest. 

So I read that there is a way where I can apply something in legacy mode or something but I'm not sure or applying blurred photo from code behind.

I'm working on the version 2.2.22 of the nuget Xamarin.FFImageLoading, .Forms and .Transformations. 

Kind regards.

**Comment by daniel-luberda** [comment]
Hi @TheIncredibleIllmo,

- Are you sure Xamarin linker isn't removing platform transformation implementation? 
- Are you sure transformation packages are added to all projects (shared and platform specific)
- Please  include `var ignore = typeof(BlurredTransformation)` in iOS project (important) and see if it helped
- Legacy blurred transformation is only available for Android

**Comment by TheIncredibleIllmo** [comment]
Hi Daniel, I appreciate your fast support.

I'm sure about the first 2 points that you wrote me, but I will try the third one and I will let you know if it works.

Regards.

**Comment by TheIncredibleIllmo** [comment]
Ok I check the following items:

- Xamarin.iOS linker is in Don't Link mode.
- Xamarin.FFImageLoading, Xamarin.FFImageLoading.Forms and Xamarin.FFImageLoading.Transformations (all 2.2.22 versions) are already installed in PCL, Xamarin.iOS and Xamarin.Android project.
- I added var `ignore = typeof(BlurredTransformation);` in AppDelegate and in Main.cs in iOS project, and nothing changed.
- In Android I don't have any problem.

This is my iOS config and the packages that I installed. Any other suggestion?
![captura de pantalla 2017-10-31 a la s 16 29 19](https://user-images.githubusercontent.com/21352255/32252323-dd54adca-be62-11e7-9f75-480c0db55c02.png)
![captura de pantalla 2017-10-31 a la s 16 49 44](https://user-images.githubusercontent.com/21352255/32252331-e2c06880-be62-11e7-82a7-18f480e7febe.png)

**Comment by daniel-luberda** [comment]
- What version of Xamarin.Forms? 
- Does it also happen on an empty newly created project?
- Could you provide a repo?

**Comment by marcelocferdeveloper** [comment]
Im with the same problem...

**Comment by marcelocferdeveloper** [comment]
* Xamarin forms 3.2.0 (but Since 3.0 is not working no iOS)
* Yes, I created another project to test

In my case, the blurred image become almost silver... on Android works as expected.
