### ISSUE TITLE
About Jenkins build failure after adding  ffimageloading to the project 

### ISSUE THREAD

**Issue by nagarjunareddyk** [luberda-molinet/FFImageLoading#790]
Thanks for great Plugin ffimageloading.  When compiling in Visual Studio its working fine but when we use MSBuild environment Its giving the namespace not found in assembly error in xamarin forms  from which  unable to build the application on jenkins.

**Comment by daniel-luberda** [comment]
We use msbuild on appveyour just fine. I'll need some more info to hep you. 

https://github.com/luberda-molinet/FFImageLoading/blob/master/MakefileAll.bat

Do you call this before building: 

```
nuget restore -MsbuildPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
dotnet restore
```

**Comment by nagarjunareddyk** [comment]
Thanks for the reply. Ya I have tried using nuget restore and dotnet restore is implicitly called in MSBuild Still the same error happens even I have tried to call the dotnet restore explicitly through build tools in visual studio.
![jenkins erros](https://user-images.githubusercontent.com/15308938/32534199-7c6912bc-c47a-11e7-96c5-4ba0c519e34b.png)

**Comment by daniel-luberda** [comment]
Did you try newest 2.2.25? It may be this (which was fixed already): https://github.com/luberda-molinet/FFImageLoading/issues/798

**Comment by nagarjunareddyk** [comment]
Ya It worked
