### ISSUE TITLE
Can not acquire a resource containing uppercase letters in android.

### ISSUE THREAD

**Issue by tyonishi** [luberda-molinet/FFImageLoading#792]
ToLower method used in Context.Resources.GetIdentifier() of ResourceDataResolver depends on the culture. Please change to a non-dependent ToLowerInvariant method.

if (!_resourceIdentifiersCache.TryGetValue(resourceName, out resourceId))
{
    token.ThrowIfCancellationRequested();
    resourceId = Context.Resources.GetIdentifier(resourceName.**ToLowerInvariant()**, "drawable", Context.PackageName);
    _resourceIdentifiersCache.TryAdd(resourceName.**ToLowerInvariant()**, resourceId);
}

**Comment by daniel-luberda** [comment]
@tyonishi Thanks! Nice catch, it's fixed :)

**Comment by molinch** [comment]
A better solution would be to make the ConcurrentDictionary use the Ordinal comparer.
Then you don't need such things, and it's faster.
