### ISSUE TITLE
svgimage unsharp, when binded at start

### ISSUE THREAD

**Issue by Andy74** [luberda-molinet/FFImageLoading#793]
Hello,

I try to load a svg image with FFImageLoading in a UWP project. 
But it will be displayed differently, depending when I will bind the image.
When I will bind it at the start of the application the image will be displayed unsharp.
When I will bind it with a command, which will be executed when hitting a button, it will be displayed sharp.

So that you will be able to simulate this behavior, I have attached a little demo-project.
When you start it, you will see a small image, which is not very sharp. When you will click the button "Change2" you will see, that this image will be shown sharp.
When you click "Change1" then the image will disappear und when you click again it will be shown again. But this time it will be displayed sharp.
Are there any tipps, how to force the image to be displayed sharp?

Best Regards
Andy

[PrismUnityApp1.zip](https://github.com/luberda-molinet/FFImageLoading/files/1441013/PrismUnityApp1.zip)

**Comment by daniel-luberda** [comment]
By default, ffimageloading tries to use width height / width, at startup, your view doesn't have a size, that's why you're experiencing it.  Try to use a constant `HeightRequest`/`WidthRequest` for `SvgCachedImageView` or use width / height parameters in `SvgImageSource` constructor.
