### ISSUE TITLE
 bindable not an instance of AssociatedType for Triggers on ffimageloading:CachedImage

### ISSUE THREAD

**Issue by pumaprog** [luberda-molinet/FFImageLoading#794]
Hey guys, since I am new to Xamarin, this question/issue may be more a result of my inexperience than an actual bug.  I was having issues with images loading in an Android listview until I found your package, which seems to work great.   I am using FFImageLoading.Forms with a Xamarin Forms project and I am trying to use image triggers to change one image to another based on a setting value.   The error I get when I implement my trigger is  "bindable not an instance of AssociatedType".  Below is my xaml image.  Am I missing something?

```
<ffimageloading:CachedImage Grid.Column="3"
                                                      Grid.Row="0" 
                                                      Grid.RowSpan="2"
                                                      HorizontalOptions="End"
                                                      VerticalOptions="Center"
                                                      DownsampleHeight="25"
                                                      DownsampleWidth="25"
                                                      Source="{Binding Source={x:Reference _pageView}, Path=BindingContext.Images.Image}">
                                    <Image.Triggers>
                                        <DataTrigger TargetType="Image" Binding="{Binding IsSelected}" Value="True">
                                            <Setter Property="IsVisible" Value="True"/>
                                        </DataTrigger>
                                        <DataTrigger TargetType="Image" Binding="{Binding IsSelected}" Value="False">
                                            <Setter Property="IsVisible" Value="False"/>
                                        </DataTrigger>
                                    </Image.Triggers>
                                    <Image.GestureRecognizers>
                                        <TapGestureRecognizer CommandParameter ="{Binding .}"
                                                              Tapped="_OnTapped"
                                                              NumberOfTapsRequired="1">
                                        </TapGestureRecognizer>
                                    </Image.GestureRecognizers>
                                </ffimageloading:CachedImage>

**Comment by daniel-luberda** [comment]
Replace all `Image` with `CachedImage` or `View` (I suppose you copied the code from somewhere). `CachedImage` is not a `Image` derivative.

**Comment by pumaprog** [comment]
Thank you for the quick response @daniel-luberda .  I really appreciate the help.  After replacing Image with CachedImage, I now receive:

Type CachedImage not found in xmlns http://xamarin.com/schemas/2014/forms

```
ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ffimageloading="clr-
 namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"

**Comment by daniel-luberda** [comment]
You need to add correct xmlns namespace: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/BasicPage.xaml

**Comment by pumaprog** [comment]
I'm not sure I understand?  I have the same namespace that is in your example:

xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"

Here is my full declaration:

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             x:Class="MyApp.Views.MyView"
             x:Name="_pageView">
</ContentPage>

**Comment by daniel-luberda** [comment]
Did you read this: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API
?

**Comment by pumaprog** [comment]
I did, but I will go over it again in case I missed something.  I am calling CachedImageRenderer.Init(); in my MainActivity.cs and I have the packages FFImageLoading and FFImageLoading.Forms added to all projects.

**Comment by daniel-luberda** [comment]
you must use `ffimageloading:CachedImage`, not `CachedImage` everywhere.

**Comment by pumaprog** [comment]
That did it.  Thank you so much for walking through it with me.
