### ISSUE TITLE
Images not cached on iOS using Xamarin Forms

### ISSUE THREAD

**Issue by K232** [luberda-molinet/FFImageLoading#795]
Hi all,
I read some postings and also the Xamarin Forms forum but did not find an answer, even though it's a quite general question: I'm using latest Xamarin Forms to build an iOS App but the images are not cached.

According to the [wiki](https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API), I only need to add a single line to AppDelegate.cs: 
`FFImageLoading.Forms.Touch.CachedImageRenderer.Init();`
I've placed it right before `LoadApplication(new App());`.
Of course I've also added Xamarin.FFImageLoading and Xamarin.FFImageLoading.Forms (latest release 2.2.22) to my iOS and my PCL project.

I'm using CachedImage in a Listview which looks like this:

```
 <ListView 
x:Name="allTags" 
ItemsSource="{Binding .}" >
<ListView.ItemTemplate>
    <DataTemplate>
        <ViewCell Height="40">
            <StackLayout Padding="5">
                <StackLayout Orientation="Horizontal" Padding="3" BackgroundColor="#80ffffff">
                    <ffimageloading:CachedImage HorizontalOptions="Center" VerticalOptions="Center" Source="{Binding Thumbnail}" CacheDuration="90"
                        Aspect="AspectFill" HeightRequest="32" MinimumWidthRequest="32" LoadingPlaceholder="loading.jpg" ErrorPlaceholder="error.jpg" />
                    <Label Text="{Binding Title}" VerticalTextAlignment="Center" HorizontalOptions="StartAndExpand" />
                </StackLayout>
            </StackLayout>
        </ViewCell>
    </DataTemplate>
</ListView.ItemTemplate>
</ListView>
```

I've set CacheDuration to "90" which is hopefully 90 days. Nevertheless, already after maybe 1 or 2 days, when I open the app in airplane mode, all icons are gone :-( 

Any ideas?

**Comment by daniel-luberda** [comment]
"90" is not 90 days - this property is of `Timespan` type.

**Comment by K232** [comment]
Thanks for clarification! Do you have an example how to do this in xaml?
many thanks!

**Comment by daniel-luberda** [comment]
There are a few ways, using custom binding converter, static property reference (`x:Static`), resource dictionaries, etc

**Comment by K232** [comment]
How can I check whether it was successfull? Is it possible to get a list of all currently cached images and their end date?

**Comment by daniel-luberda** [comment]
Success event contains many useful informations, including if the item was retrieved from cache
