### ISSUE TITLE
Build issue when using VSTS

### ISSUE THREAD

**Issue by jbowmanp1107** [luberda-molinet/FFImageLoading#797]
I am trying to use VSTS to build my Xamarin Forms app (Android in this case). 

I am seeing an error that says
Xamarin\SampleApp\obj\Debug\SampleApp.Views.PurchaseOptionButtonView.xaml.g.cs(18,25): Error CS0400: The type or namespace name 'FFImageLoading' could not be found in the global namespace (are you missing an assembly reference?)

But I also see a bunch of warnings (below) and I am wondering if these might be the cause. Any idea how I can fix these?

  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3274: The primary reference "FFImageLoading, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111". [d:\a\1\s\Xamarin\SampleApp\SampleApp.csproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3275: The primary reference "FFImageLoading.Forms, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "FFImageLoading, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111". [d:\a\1\s\Xamarin\SampleApp\SampleApp.csproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3275: The primary reference "FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "FFImageLoading, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111". [d:\a\1\s\Xamarin\SampleApp\SampleApp.csproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3275: The primary reference "FFImageLoading.Transformations, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "FFImageLoading, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111". [d:\a\1\s\Xamarin\SampleApp\SampleApp.csproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3274: The primary reference "FFImageLoading.Forms, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111". [d:\a\1\s\Xamarin\SampleApp\SampleApp.csproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3274: The primary reference "FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111". [d:\a\1\s\Xamarin\SampleApp\SampleApp.csproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3275: The primary reference "FFImageLoading.Forms, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111". [d:\a\1\s\Xamarin\SampleApp\SampleApp.csproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3274: The primary reference "FFImageLoading.Transformations, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETPortable,Version=v5.0" framework. This is a higher version than the currently targeted framework ".NETPortable,Version=v4.5,Profile=Profile111". [d:\a\1\s\Xamarin\SampleApp\SampleApp.csproj]

Regards,

-Jeff

**Comment by daniel-luberda** [comment]
It's probably this: https://nicksnettravels.builttoroam.com/post/2016/12/06/When-I-grow-up-I-want-to-be-a-NETStandard-Library!.aspx

It's not exactly FFImageLoading issue, rather msbuild / Visual Studio. I can use some workarounds for that, but the problem is it's only a work-around.
