### ISSUE TITLE
Udated version 2.2.23 issue and 2.2.22 secondary issue

### ISSUE THREAD

**Issue by Hellyster** [luberda-molinet/FFImageLoading#799]
Platform : Xamarin.Forms Android device.
I installed your new release version (2.2.23) from 2.2.22 which was stable.
The new version doesn't show some Images while the previous one did.
Just to mention there's probably a problem during rendering.

Test made : 2.2.23
-XAML defined source : Not showing
-ViewModel loading source -> FromFile : Ok, FromStream : Ok

About the 2.2.22 : 
-Using FFImageLoading (ffCachedImage) from ContentPage inside CarouselPage
=>Bat quality rendering for PNG (Bad definition at first load) after 2 pages swipe and come back, rendering quality fixed.
=>ffCachedImage inside grid with non fixed size (* size) and DownSampleToViewSize set to true, load the image with non adapted size (Smaller) -, after 2 pages swipe and come back, size fixed and rendering fine.

Just to mention the actual issues I found.
Thanks for the great work you did, well satisfied of the functionnality you created, helped me a lot.
So again, thank you

**Comment by collaorodrigo7** [comment]
I am having the same problem. 2.2.22 used to work fine and I can not get 2.2.23 to work.
I did tried ```CachedImageRenderer.Init(false)``` , do you have any other suggestion?

**Comment by daniel-luberda** [comment]
Clean, remove `bin` / `obj` folders & rebuild first.

**Comment by collaorodrigo7** [comment]
I just did, remove bin/obj folders & rebuild, still do can not load images

**Comment by collaorodrigo7** [comment]
My bad, it does work after removing bin/obj and rebuilding
