### ISSUE TITLE
Tap gesture does not fire in 2.2.23

### ISSUE THREAD

**Issue by ozzy1873** [luberda-molinet/FFImageLoading#800]
Using the code below with 2.2.22, the CachedImage gets the tap gesture. With 2.2.23, the tap gesture is now passed through to the grid and the CachedImage never sees it. I'm using Xamarin Forms v2.5.0.19271-pre2 on Android. I should mention this is in a ViewCell in a ListView.

BTW, this control is absolutely awesome! Thank you!

> <Grid>
        <Grid.GestureRecognizers>
            <TapGestureRecognizer Tapped="OnGridTapped"/>
        </Grid.GestureRecognizers>

        <StackLayout>

            <ff:CachedImage x:Name="ProfilePhoto" 
                            HeightRequest="60"
                            WidthRequest="60" 
                            Margin="12,12,6,12"
                            Source="{Binding SenderPhotoUrl}"
                            DownsampleHeight="60"
                            LoadingPlaceholder="no_avatar.png" 
                            ErrorPlaceholder="no_avatar.png"
                            HorizontalOptions="Center"
                            VerticalOptions="Start">

                <ff:CachedImage.Transformations>
                    <ffx:RoundedTransformation Radius="60"/>
                </ff:CachedImage.Transformations>

                <ff:CachedImage.GestureRecognizers>
                    <TapGestureRecognizer Tapped="OnProfilePhotoTapped"/>
                </ff:CachedImage.GestureRecognizers>

            </ff:CachedImage>

**Comment by michelmoorlag** [comment]
I have the same issue on the SvgCachedImage. Works fine in 2.2.22 but on 2.2.23 the tap is never received.

**Comment by daniel-luberda** [comment]
You could try to disable Android fast renderer (it's enabled by default if supported, it's mentioned in the release note). `CachedImageRenderer.Init(false)`

I'll fix this in the `2.2.24`

**Comment by acaliaro** [comment]
In 2.2.25 This TGR does not fire also with` CachedImageRenderer.Init(false)
`
                <ffimageloading:CachedImage HorizontalOptions="Center" VerticalOptions="Center"
                    WidthRequest="200" HeightRequest="200"
                    DownsampleToViewSize="true"
                    ErrorPlaceholder="error.png"
                    LoadingPlaceholder="load_md.png"              
                    Source="{Binding ArticoloCorrente.Immagine}">
                    <ffimageloading:CachedImage.GestureRecognizers>
                        <TapGestureRecognizer Command="{Binding ImageMenuCommand}"/>
                    </ffimageloading:CachedImage.GestureRecognizers>
                </ffimageloading:CachedImage>
