### ISSUE TITLE
Help About Circle Image in UWP 

### ISSUE THREAD

**Issue by Mahan3340** [luberda-molinet/FFImageLoading#801]
hi , I'm currently using  
```
<ff:FFImage Height="40" Width="40" Grid.Column="2" Margin="0,0,10,0"  x:Name="ListProfileImage" Source="{Binding finalImage}" >
     </ff:FFImage>

```
to load images but i cant find the way to make a circular image and I looked your examples but neither of them is recognized by compiler like they are not in the library , could you provider some help please as am new to UWP ?
 
Edit : i used bellow code but don't know how to achieve this via XAML 

```
ImageService.Instance.LoadUrl(urlToImage)
.Transform(new GrayscaleTransformation())
.Into(imgDisplay);

```

**Comment by Mahan3340** [comment]
I ended up creating a userControl for listview DataTemplate and do use the code i mentioned in EDIT to apply circle transformation to images , you may close this issue after u mentioned the XAML way too but my problem is solved

**Comment by daniel-luberda** [comment]
What you're looking for is a standard XAML syntax: 

```XML
<ff:FFImage Height="40" Width="40" Grid.Column="2" Margin="0,0,10,0"  x:Name="ListProfileImage" Source="{Binding finalImage}">
    <ff:FFImage.Transformations>
        <fft:CircleTransformation/>
    </ff:FFImage.Transformations>
</ff:FFImage>
```
