### ISSUE TITLE
FFImageLoading.Forms.Droid.CachedImageRenderer.init()' not found

### ISSUE THREAD

**Issue by matthew798** [luberda-molinet/FFImageLoading#802]
Both the `FFImageLoading` and `FFImageLoading.Forms` are installed in my android project. The function `CachedImageRendere.init()` is called in the `MainActivity.cs` as described in the docs, yet I get the following exception:

`System.MissingMethodException: method 'FFImageLoading.Forms.Droid.CachedImageRenderer.Init()' not found.`

This issue occurs with and without any controls present in the XAML refering FFIL.

Thanks

**Comment by matt4pi** [comment]
I had the same issue, but a clean rebuild solved it. Not sure if it'll help you, but give it a shot.

**Comment by galadril** [comment]
I had the same issue, but a clean rebuild solved it.

**Comment by jerone** [comment]
Also same issue, and like mentioned above, rebuilding solves the issue. This issues has not appeared on any other packages.

**Comment by matthew798** [comment]
Yup, rebuilding solved it. Very annoying! Thanks guys!
