### ISSUE TITLE
CachedImage.IsLoading never sets to false on Android

### ISSUE THREAD

**Issue by matt4pi** [luberda-molinet/FFImageLoading#803]
The CachedImageFastRenderer does not seem to be setting IsLoading to false. Looks to be due to the commented out code [here](https://github.com/luberda-molinet/FFImageLoading/blob/6af79e498f52a6295ec93d9525e91d15c808c85c/source/FFImageLoading.Forms.Droid/CachedImageFastRenderer.cs#L267)

Work around is to stop the FastRenderer from being used by using the explicit image renderer initialiser: CachedImageRenderer.Init(false);

**Comment by daniel-luberda** [comment]
Nice catch! :) Thanks @matt4pi - it's fixed.
