### ISSUE TITLE
GestureRecognizer on 2.2.23

### ISSUE THREAD

**Issue by LuigiMaestrelli** [luberda-molinet/FFImageLoading#805]
TapGestureRecognizer is not firing on Android after update to 2.2.23.
Even with CachedImage.FixedAndroidMotionEventHandler = true

I'm using Xamarin.Forms 2.5.0.19271-pre2

**Comment by daniel-luberda** [comment]
Fixed.

BTW: Duplicate: https://github.com/luberda-molinet/FFImageLoading/issues/800
