### ISSUE TITLE
Load SVG on Android

### ISSUE THREAD

**Issue by jorgenstorlie** [luberda-molinet/FFImageLoading#806]
_imgDisplay = view.FindViewById<ImageViewAsync>(Resource.Id.imgDisplay);
    
I can find out how to load SVG on Android.
I try this:
            var svgString = @"<svg><rect width=""30"" height=""30"" style=""fill:blue"" /></svg>";

            ImageService.Instance
        .LoadString(svgString)
     //   .LoadingPlaceholder(placeHolderPath)
        .WithCustomDataResolver(new SvgDataResolver(64, 0, true))
        .WithCustomLoadingPlaceholderDataResolver(new SvgDataResolver(64, 0, true))
                        .Into(_imgDisplay);

Any reason this does not work?
@

**Comment by daniel-luberda** [comment]
`<rect width=""30"" height=""30"" style=""fill:blue"" />` is not a valid SVG file. Valid SVG file example: 

```XML
<svg  xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink">
    <rect x="10" y="10" height="100" width="100"
          style="stroke:#ff0000; fill: #0000ff"/>
</svg>
```


Also are you sure you:

- Added SkiaSharp package to all projects (shared & platform specific)
- Added FFImageLoading packages to all projects (shared & platform specific)
- Added FFImageLoading SVG packages to all projects (shared & platform specific)

?
