### ISSUE TITLE
UWP incorrect image colors when using transformations

### ISSUE THREAD

**Issue by melimion** [luberda-molinet/FFImageLoading#808]
When using and transformation on UWP, result image have invalid colors. 
Explanation is here: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/80210058-cacb-443e-afe6-e6bd6cfc8f2a/blue-tint-on-image-when-loading-manually-from-stream?forum=winappswithcsharp

Issue is in ToWriteableBitmap method in FFImageLoading.Windows/Extensions/ImageExtensions.cs

You can try it by applying transformation to attached image.
![example](https://user-images.githubusercontent.com/33512073/32602078-d535f8ca-c555-11e7-8389-c168f465a09e.png)

**Comment by daniel-luberda** [comment]
Nice catch! :) Fixed, thank you for the info.
