### ISSUE TITLE
Images missing when similar data uri's

### ISSUE THREAD

**Issue by GuidoNeele** [luberda-molinet/FFImageLoading#810]
I have a list of data uri's that are exactly the same. First two images will show the rest never appears. Is this a known issue? Something to do with uri caching?

**Comment by daniel-luberda** [comment]
There are no knows issues with it. I'll need some more info. Could you make a sample project or write more details?

**Comment by daniel-luberda** [comment]
It should be fixed in latest 2.2.25, please reopen if you still experience it.
