### ISSUE TITLE
FixedOnMeasureBehavior does not work in XAML in Xamarin.Forms

### ISSUE THREAD

**Issue by OpticNectar** [luberda-molinet/FFImageLoading#811]
If I add the `FixedOnMeasureBehavior` to a `ffimageloading:CachedImage` in XAML in Xamarin.Forms it throws the following error:

```
No property, bindable property, or event found for 'FixedOnMeasureBehavior', or mismatching type between value and property.
```

**Code:**
```
<ffimageloading:CachedImage 
            FixedOnMeasureBehavior="true"
            FadeAnimationEnabled="true"
            Source="{ Binding image }"  />
```

**Comment by daniel-luberda** [comment]
It's not a instance property. It's a global static property. You can set it at app startup:

`CachedImage. FixedOnMeasureBehavior = true`

**Comment by OpticNectar** [comment]
@daniel-luberda If that's the case it probably shouldn't show up in the options drop down for the XAML element then.

**Comment by daniel-luberda** [comment]
@OpticNectar Yes, but currently there are no ways to disable this for XAML only.
