### ISSUE TITLE
Getting exception: Unhandled Exception: System.TypeLoadException: Could not load list of method overrides

### ISSUE THREAD

**Issue by ShahriatHossain** [luberda-molinet/FFImageLoading#815]
Xamarin.Forms:  2.3.4.224

Xamarin.FFImageLoading.Forms:  2.2.25

Getting exception:
Unhandled Exception: System.TypeLoadException: Could not load list of method overrides
 on FFImageLoading.Forms.Droid.CachedImageRenderer.Init();

can anybody help me what should I do now?

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/814

**Comment by LandonReilly** [comment]
Same issue now with forms 3.4.0.1008975

**Comment by jitendrajadav** [comment]
System.TypeLoadException: VTable setup of type FFImageLoading.Forms.Platform.CachedImageFastRenderer failed

getting error on Xamarin.forms version 3.4

**Comment by GowthamRajasri** [comment]
@jitendrajadav For me also same problem. when I update the "xamarin forms to 3.4.0.1008975" in .net standard library form version 3.3.0, 
I got an error "VTable setup of type FFImageLoading.Forms.Platform.CachedImageFastRenderer failed" .

**Comment by daniel-luberda** [comment]
Duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/1154
