### ISSUE TITLE
Got error when loading list image : Number.StringToNumber 

### ISSUE THREAD

**Issue by tininess** [luberda-molinet/FFImageLoading#817]
Hi,
I am new with xamarin and i choose FFImageLoading for image loading. Which the HTC M10 device, the crash issue seem not happen. But when I load with another device with lower ram (2gb). I face some issue and it crashing many time. This is the crash log 

> Number.StringToNumber
> android.runtime.JavaProxyThrowable: FFImageLoading.DownloadAggregateException: One or more errors occurred. ---> System.Net.WebException: Error getting response stream (ReadDone4): ServerProtocolViolation ---> System.FormatException: Input string was not in a correct format.
> 

And the details is 

> caused.WebException(ReadDone4)
System.Number.StringToNumber(string str, NumberStyles options, ref Number.NumberBuffer number, NumberFormatInfo info, bool parseDecimal)<3dc9ed3d31194319991e686734adcb10>:0
System.Number.ParseUInt32(string value, NumberStyles options, NumberFormatInfo numfmt)<3dc9ed3d31194319991e686734adcb10>:0
System.UInt32.Parse(string s)<3dc9ed3d31194319991e686734adcb10>:0
System.Net.WebConnection.GetResponse(WebConnectionData data, ServicePoint sPoint, byte[] buffer, int max)<d079ae5f54e340a2ae25ccad188ee40f>:0
System.Net.WebConnection.ReadDone(IAsyncResult result)<d079ae5f54e340a2ae25ccad188ee40f>:0
--- End of inner exception stack trace ---
System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)<d079ae5f54e340a2ae25ccad188ee40f>:0
System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<T, TResult> endFunction, Action<T> endAction, Task<TResult> promise, bool requiresSynchronization)<3dc9ed3d31194319991e686734adcb10>:0
System.Net.Http.HttpClientHandler.SendAsync()<6e92ad09d0bd49b996fe288564eee203>:0
System.Net.Http.HttpClient.SendAsyncWorker()<6e92ad09d0bd49b996fe288564eee203>:0
FFImageLoading.Cache.DownloadCache.<DownloadAsync>d__17.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
FFImageLoading.Cache.DownloadCache.<>c__DisplayClass16_0.<<DownloadAndCacheIfNeededAsync>b__0>d.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
FFImageLoading.Retry.<DoAsync>d__0<T>.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
--- End of inner exception stack trace ---
FFImageLoading.Retry.<DoAsync>d__0<T>.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
FFImageLoading.Cache.DownloadCache.<DownloadAndCacheIfNeededAsync>d__16.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
FFImageLoading.DataResolvers.UrlDataResolver.<Resolve>d__7.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
FFImageLoading.DataResolvers.WrappedDataResolver.<Resolve>d__2.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
FFImageLoading.Work.ImageLoaderTask<TImageContainer, TImageView>.<RunAsync>d__107.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
VehicleAppraisal.Android.ImagesItemViewHolder.<LoadData>d__7.MoveNext()<919376300a2f40d997f9345e31226567>:0
Android.App.SyncContext.<Post>c__AnonStorey0.<>m__0()<9eb16c47cc8f4aa6b6ac4abed5ff79de>:0
Java.Lang.Thread.RunnableImplementor.Run()<9eb16c47cc8f4aa6b6ac4abed5ff79de>:0
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<9eb16c47cc8f4aa6b6ac4abed5ff79de>:0
at (wrapper dynamic-method) System.Object:65d04f57-b84b-4a87-a7aa-c3525462e481 (intptr,intptr)
---> (Inner Exception #0) System.Net.WebException: Error getting response stream (ReadDone4): ServerProtocolViolation ---> System.FormatException: Input string was not in a correct format.
System.Number.StringToNumber(string str, NumberStyles options, ref Number.NumberBuffer number, NumberFormatInfo info, bool parseDecimal)<3dc9ed3d31194319991e686734adcb10>:0
System.Number.ParseUInt32(string value, NumberStyles options, NumberFormatInfo numfmt)<3dc9ed3d31194319991e686734adcb10>:0
System.UInt32.Parse(string s)<3dc9ed3d31194319991e686734adcb10>:0
System.Net.WebConnection.GetResponse(WebConnectionData data, ServicePoint sPoint, byte[] buffer, int max)<d079ae5f54e340a2ae25ccad188ee40f>:0
System.Net.WebConnection.ReadDone(IAsyncResult result)<d079ae5f54e340a2ae25ccad188ee40f>:0
--- End of inner exception stack trace ---
System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)<d079ae5f54e340a2ae25ccad188ee40f>:0
System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<T, TResult> endFunction, Action<T> endAction, Task<TResult> promise, bool requiresSynchronization)<3dc9ed3d31194319991e686734adcb10>:0
System.Net.Http.HttpClientHandler.SendAsync()<6e92ad09d0bd49b996fe288564eee203>:0
System.Net.Http.HttpClient.SendAsyncWorker()<6e92ad09d0bd49b996fe288564eee203>:0
FFImageLoading.Cache.DownloadCache.<DownloadAsync>d__17.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
FFImageLoading.Cache.DownloadCache.<>c__DisplayClass16_0.<<DownloadAndCacheIfNeededAsync>b__0>d.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
FFImageLoading.Retry.<DoAsync>d__0<T>.MoveNext()<75a73da4f62d4596bb7efcda393ce1b6>:0
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
android.os.Handler.handleCallback()Handler.java:739
android.os.Handler.dispatchMessage()Handler.java:95
android.os.Looper.loop()Looper.java:148
android.app.ActivityThread.main()ActivityThread.java:5530
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:733
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:623

Do you have any idea about this error :(

**Comment by daniel-luberda** [comment]
IMO it's not an FFImageLoading issue: 

- What http client handler do you use? 
- Could you provide some not working url examples? 

`Error getting response stream` indicates that you have either connections issues or server issues.
