### ISSUE TITLE
Discrepancies with versions past 2.2.22

### ISSUE THREAD

**Issue by JMNewsome** [luberda-molinet/FFImageLoading#820]
I have noticed there are issues that crop up starting with version 2.2.23 and forward that completely destroy the normal way FFImageLoading handles cachedImage displays on Android and IOS.

One of the issues is with Aspect.AspectFill, it is performing differently on Android vs IOS. it appears that Android is not rendering properly and will cause on my app images to ignore their containers and bleed over or not render properly. I am looking to see what code changed between the versions past 2.2.22 to help identify this issue

**Comment by daniel-luberda** [comment]
Just disable fast renderer which is enabled by default: `CachedImageRenderer.Init(false)`

**Comment by JMNewsome** [comment]
This fixed it, thank you!

**Comment by daniel-luberda** [comment]
Are you able to reproduce this when using `Image` with fast renderer enabled instead `CachedImage` too?
