### ISSUE TITLE
v2.2.25 Android AspectFill works incorrect

### ISSUE THREAD

**Issue by ignasbagdonas** [luberda-molinet/FFImageLoading#823]
For example I have grid and inside it Image with Height and Width. But when I set aspect to AspectFill my Image is bigger than my over grid. Problem occurs only on Android. I had revert to lower version (now I tested with 2.2.22, works good).

```

<Grid HeightRequest="196" WidthRequest="148">
   <Grid.RowDefinitions>
          <RowDefinition Height="*" />
          <RowDefinition Height="48" />
   </Grid.RowDefinitions>
   <img:CachedImage Grid.Row="0" Aspect="AspectFill" Source="{TemplateBinding ImageSource}" ErrorPlaceholder="error.png" LoadingPlaceholder="loading.png" HeightRequest="148" WidthRequest="148" DownsampleToViewSize="true" />
...
</Grid>
```

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/820

Just disable fast renderer which is enabled by default: CachedImageRenderer.Init(false)

**Comment by daniel-luberda** [comment]
Are you able to reproduce this when using `Image` with fast renderer enabled instead `CachedImage` too?

**Comment by ignasbagdonas** [comment]
Yes. With your fix everything works good. Thanks.
