### ISSUE TITLE
Fastrenderer issues

### ISSUE THREAD

**Issue by bentmar** [luberda-molinet/FFImageLoading#824]
this is using the latest 2.

issue #1

MainPage = ContentPage();
some taps later..
MainPage = new MasterDetailPage(); //master is contentpage, detail is navigationpage

in masterpage i have an image that is only shown when not using fastrenderers.
If the device is rotated the image will show.

issue#2

Images grow beyond grids bounds when in grid and using aspect AspectFill
This is also only when using fastrenderers.

I could give you a quick look at my code sometime via skype or something, I cant share it though.
If i get time i will setup a repro.

This is using latest stable XF and FFimageloading when writing this.
I only see this on Android

Thank you!

**Comment by JMNewsome** [comment]
Ive reported same issue, the fix provided was setting the init to false
CachedImageRenderer.Init(false);

**Comment by daniel-luberda** [comment]
Are you able to reproduce this when using `Image` with fast renderer enabled too?

**Comment by KonradCzarny** [comment]
@daniel-luberda  I've changed from CachedImage to Image, still the same result. Also I've set CachedRenderer.Init to false in android mainactivity oncreate method 
[Image of how it looks](https://imgur.com/a/Wwvam)

**Comment by bentmar** [comment]
This is absolutely an issue with fastrenderers only. But CachedImage is not the problem, i see the same bugs with Image "sigh...."

**Comment by bentmar** [comment]
@KonradCzarny 

What answer do you excpect from that comment?

![image](https://user-images.githubusercontent.com/10244000/33099512-629a532c-cf11-11e7-9391-280bac4b38d1.png)
