### ISSUE TITLE
Debugging "loading cancelled" on Xamarin iOS native

### ISSUE THREAD

**Issue by Tarostar** [luberda-molinet/FFImageLoading#826]
I am having an issue where I am getting "loading cancelled" frequently in ViewWillAppear and occasionally if I load the image in ViewDidAppear.

This even happens when navigating back to the view on the stack and the image was previously shown and in the cache. I'm trying to understand what is going wrong, but I'm not sure how to get to the cause of the cancellation,

I use:
ImageService.Instance.LoadUrl(url)
                        .Retry(3, 200)
                        .Into(avatarImage);

**Relevant Log Line**:
`[0:] FFImageLoadingDebug_Image loading cancelled: https://assets-cdn.github.com/images/modules/logos_page/Octocat.png;CircleTransformation,borderSize=0,borderHexColor=`

More information on [stackoverflow](https://stackoverflow.com/questions/47377506/how-to-use-ffimageloading-in-viewwillappear/47385651#47385651)

**Comment by daniel-luberda** [comment]
Is it possible to have a sample repo?
