### ISSUE TITLE
How to use GetImageAsPngAsync from ViewModel?

### ISSUE THREAD

**Issue by asafgo** [luberda-molinet/FFImageLoading#827]
Hi,
Is there a way to use GetImageAsPngAsync from ViewModel at SuccessCommand?
I am using XAML

Thanks,
AG

**Comment by daniel-luberda** [comment]
- There are various ways to do it including messaging / etc, you can search for this on Xamarin.Forums
- You could use `ImageService` apis which are available everywhere: https://github.com/luberda-molinet/FFImageLoading/wiki/Fluent-Syntax
