### ISSUE TITLE
Out of memories. Xamarin Forms (Android)

### ISSUE THREAD

**Issue by idimkk** [luberda-molinet/FFImageLoading#828]
Hello.

I use your library (Xamarin Forms) to display pictures from archives in the stream. Full-size images, full-page.
Usually one image weighs after extraction 1.5mb (format jpg/png). When rendering, images are usually about 6MB.

With a standard heap - about 200-250 mb, the overflow is very fast, 10-20 photos are enough, depending on the settings of DownsampleWidth. 
**Desired result: view 150+ photos.**
Look at the pictures in turn. It is necessary to store only 3-5 nearest photos from behind and in front.

I tried several implementations that would change the collection and fill it up on demand, but the old images are not unloaded from their RAM. I use the Using design everywhere - it does not help either.
I attached a piece of my implementation, with detailed comments.

[Sample code](https://pastebin.com/e219v8ev)

Perhaps you can tell me how it can be implemented to avoid the out of memories of the android.

Best Regards,
Dmitriy.

**Comment by daniel-luberda** [comment]
When using `StreamImageSource`  you should implement & set `CacheKeyFactory` property. This is needed for `CachedImage` to know that the source is already in memory cache and doesn't need to be loaded again and can be reused instead.

**Comment by idimkk** [comment]
Thanks for your reply. 
I'll try. but I tried to load the already unpacked images to disk, and use the "fromFile" method - the result was the same. CustomCacheKeyFactory - method was absent.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms/CachedImage.cs#L540

**Comment by idimkk** [comment]
Thanks!
I will do this and write if the problem remains.

**Comment by daniel-luberda** [comment]
Any news?

**Comment by idimkk** [comment]
Excuse me. I was developing another project. I will implement it today. Do you have no other example than what is under the link:
[https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-Advanced](Custom cache keys)

**Comment by daniel-luberda** [comment]
- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/CustomKeyPageCell.xaml
- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/CustomKeyPageModel.cs

**Comment by idimkk** [comment]
Thank you, I will do it right now.

**Comment by idimkk** [comment]
I did this kind of implementation, but the images are still not destroyed in memory after they are no longer visible.

```
        private async void LoadPages()
        {
            try
            {
                using (Stream stream = await file.OpenAsync(FileAccess.Read))
                using (IArchive archive = ArchiveFactory.Open(stream))
                {
                    foreach (IArchiveEntry entry in archive.Entries)
                    {
                        using (var imageStream = entry.OpenEntryStream())
                        {
                            collection.Add(new CachedImage()
                            {
                                Source = ImageSource.FromStream(() => imageStream),
                                DownsampleWidth = 1080,
                                Aspect = Aspect.AspectFill,
                                CacheKeyFactory = new CustomCacheKeyFactory()
                            });
                        }

                    }

                    var carousel = new CarouselViewControl
                    {
                        Position = 0,
                        ItemsSource = collection,
                        ShowIndicators = true,
                        ShowArrows = true,
                        IsSwipingEnabled = true
                    };
                    //carousel.PositionSelected += changeCollection;
                    carousel.SetBinding(CarouselViewControl.PositionSelectedCommandProperty, "MyCommand");

                    Content = carousel;
                    BindingContext = new MainViewModel();
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
            }

        }
```


```
        public class CustomCacheKeyFactory : ICacheKeyFactory
        {
            public string GetKey(ImageSource imageSource, object bindingContext)
            {
                if (imageSource == null)
                    return null;

                var uriImageSource = imageSource as UriImageSource;
                if (uriImageSource != null)
                    return uriImageSource.Uri.ToString();

                var fileImageSource = imageSource as FileImageSource;
                if (fileImageSource != null)
                    return fileImageSource.File;

                var streamImageSource = imageSource as StreamImageSource;
                if (streamImageSource != null)
                {
                    string cacheKey = Guid.NewGuid().ToString();
                    Debug.WriteLine(cacheKey);
                    return cacheKey;
                }

                return null;
            }
        }
```

**Comment by idimkk** [comment]
I can provide a test project if this helps me and you :)

**Comment by daniel-luberda** [comment]
Sure :) If you have some sample project I'll debug it and see why it happens. 

It's completely normal that images are not destroyed right away. See this: https://github.com/luberda-molinet/FFImageLoading/issues/851#issuecomment-351751538

**Comment by idimkk** [comment]
Thanks for the help!
Here is a test project. I removed the folder "Packages", so restore them please through Nuget.
[Sample Project](https://goo.gl/S8Z5Mq)

And this is a test file, it needs to be placed on the path "/storage/emulated/0/Download/" and click on the already filled line or you can put it anywhere, but then you have to use the "Нажми!" button.
[Test File](https://goo.gl/7odFwi)

**Comment by idimkk** [comment]
If you set the ViewPage.xaml.cs file in line 78:
Downsample Width = 1080
Then "Out of memories exception" occurs on page 7-8.
With a standard heap of 200-250 MB. The collector does not even try to clean it.

**Comment by daniel-luberda** [comment]
Use this: 

```C#
       private async void LoadPages()
        {
            try
            {
                using (Stream stream = await file.OpenAsync(FileAccess.Read))
                using (IArchive archive = ArchiveFactory.Open(stream))
                {
                    foreach (IArchiveEntry entry in archive.Entries)
                    {
                        byte[] bytes = null;
                        using (var imageStream = entry.OpenEntryStream())
                        using (var memoryStream = new MemoryStream())                            
                        {
                            imageStream.CopyTo(memoryStream);
                            bytes = memoryStream.ToArray();
                        }

                        collection.Add(new CachedImage()
                        {
                            CacheKeyFactory = new CustomCacheKeyFactory(),
                            Source = new CustomStreamImageSource((token) => new MemoryStream(bytes), entry.Key),
                            DownsampleWidth = 640,
                            Aspect = Aspect.AspectFill,
                        });
                    }

                    var carousel = new CarouselViewControl
                    {
                        Position = 0,
                        ItemsSource = collection,
                        ShowIndicators = true,
                        ShowArrows = true,
                        IsSwipingEnabled = true
                    };
                    //carousel.PositionSelected += changeCollection;
                    carousel.SetBinding(CarouselViewControl.PositionSelectedCommandProperty, "MyCommand");

                    Content = carousel;
                    BindingContext = new MainViewModel();
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
            }

        }

        public class CustomStreamImageSource : StreamImageSource
        {
            public CustomStreamImageSource(Func<CancellationToken, Stream> func, string key)
            {
                Stream = (token) => Task.FromResult(func.Invoke(token));
                Key = key;
            }

            public string Key { get; set; }
        }

        public class CustomCacheKeyFactory : ICacheKeyFactory
        {
            public string GetKey(ImageSource imageSource, object bindingContext)
            {
                if (imageSource == null)
                    return null;

                var streamImageSource = imageSource as CustomStreamImageSource;
                if (streamImageSource != null)
                {
                    string cacheKey = streamImageSource.Key;
                    Debug.WriteLine(cacheKey);
                    return cacheKey;
                }

                return null;
            }
        }
```

**Comment by daniel-luberda** [comment]
Also memory leaks can come from your archive tool & carousel views implementations.

**Comment by idimkk** [comment]
I tested your code. The problem persists (if you set the value in line 78 to 1080), I tried, unpack the archive to disk and take the files from there. I am ready to abandon the carousel, the main task is to overcome the memory leaks.

> collection.Add(new CachedImage()
                        {
                            CacheKeyFactory = new CustomCacheKeyFactory(),
                            Source = new CustomStreamImageSource((token) => new MemoryStream(bytes), entry.Key),
                            DownsampleWidth = **1080**,
                            Aspect = Aspect.AspectFill,
                        });

Thanks.

**Comment by daniel-luberda** [comment]
- If files are big you should enable large heap in Android project. 
- How do you check if there are memory leaks?

**Comment by idimkk** [comment]
In this project, when you turn the page, you can see how much memory the application has in memory. This can be seen in the "Debugging" field.
Example of output on paging 8 pages:

> 12-15 07: 05: 32.825 I / art (10924): Alloc concurrent mark sweep GC freed 2 (80B) AllocSpace objects, 0 (0B) LOS objects, 5% free, 182MB / 192MB, paused 157us total 8.187ms

**Comment by idimkk** [comment]
No, I do not use a large heap. It seems to me that the memory cleaning functionality should work on a small heap size. Or am I wrong?

**Comment by daniel-luberda** [comment]
- FFImageLoading is also a memory cache so it's normal to cache some of the bitmaps, cache is freed automatically, but only if it's full. If you don't want to cache in memory you can set `CacheType` to `Disk`. Max memory cache size is configurable. Default is: 20% of available app memory
- You should use large heap only if you're getting OOM exceptions

**Comment by daniel-luberda** [comment]
Also see this: https://forums.xamarin.com/discussion/comment/311934/#Comment_311934

**Comment by daniel-luberda** [comment]
Also see this: https://github.com/luberda-molinet/FFImageLoading/issues/867
