### ISSUE TITLE
CachedImage TapRecognizer different from button click

### ISSUE THREAD

**Issue by SelamSoft** [luberda-molinet/FFImageLoading#829]
I have Forms.Button objects and FFImageLoading.CachedImaged objects in my app and noticed that the Tap gesture on images does not perform as reliably as the Button.Click event. Is there a way to implement a click event for CachedImage or, as you mentioned in another post, implement CachedButton? 

I'm new to Xamarin but I've developed in C# before as well as Java Android and Cordova. What I really liked about Cordova was TouchStart events. It seems that these have to be implemented in each platform for Xamarin, but at least having a proper Button.Click in CachedImage and CachedButton would solve some of the usability issues with users thinking they had clicked when they hadn't properly tapped.

**Comment by daniel-luberda** [comment]
Just put `CachedImage` inside `ContentView` with defined size and assign gesture recogniser to this `ContentView` instead. With this, whole `ContentView` region will be "tappable".

**Comment by SelamSoft** [comment]
I tried this but it still has the limitations of a tap. I think this is more of an issue with xamarin not considering touch and usability in forms which is pushing developers toward platform-specific implementations. I'm new to xamarin, but if you have the start of a CachedButton, I could probably implement it from there.

My main problem is that tap is a very specific event and when I try this with my users they "tap" about 1/3 of the time. The other 2/3 of the time, the event is a click but does not fire as a tap.
