### ISSUE TITLE
CachedImage inside a ContentView

### ISSUE THREAD

**Issue by acaliaro** [luberda-molinet/FFImageLoading#831]
Hi Daniel.
I have a problem with your lib
When I add a CachedImage inside a ContentView, it does not display the image.
If I move it outside the contentview... it displays image.

**Comment by daniel-luberda** [comment]
Hi @acaliaro,

- What platform? If Android, do you have FastCachedImageRenderer enabled?
- Could you share some code?

**Comment by acaliaro** [comment]
Hi @daniel-luberda 
If I remember correctly, I have tried with `CachedImageRenderer.Init();` and `CachedImageRenderer.Init(false);`

I do some tests and send you more info (or a repo...)

**Comment by daniel-luberda** [comment]
It may be related to this: https://github.com/luberda-molinet/FFImageLoading/issues/830

**Comment by daniel-luberda** [comment]
Any news?
