### ISSUE TITLE
Error CS0246 and CS0400: The type or namespace name 'FFImageLoading' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by wenyonk** [luberda-molinet/FFImageLoading#832]
MAIN\Src\Xyz\App.xaml.cs(7):MAIN\Src\Xyz\App.xaml.cs(7,7): Error CS0246: The type or namespace name 'FFImageLoading' could not be found (are you missing a using directive or an assembly reference?)

AND

MAIN\Src\Xyz\obj\Release\Xyz.Views.EmployeeLoginPage.xaml.g.cs(24):MAIN\Src\Xyz\obj\Release\Xyz.Views.EmployeeLoginPage.xaml.g.cs(24,25): Error CS0400: The type or namespace name 'FFImageLoading' could not be found in the global namespace (are you missing an assembly reference?)

I do not get this error when I build Android locally on my Mac.
The error is being generated from a build agent as part of our CI
The package files are in source control and part of the solution

Any suggestions.  I saw something similar with the SVG component, not sure if it is the same issue? 

We are using Xamarin Forms v2.4.0.91020
          using FFImageLoading v2.2.20, FFImageLoading.Forms for image caching only.  Just to be clear we are not using the SVG component.

Additionally, these errors (34) in all, are in 17 different code files in our PCL (where our Views and ViewCells are located).

We cannot upgrade to a new version of XF (2.5.x)  or the FFImageLoading as it breaks the UI and images are no longer scaled correctly.

**Comment by daniel-luberda** [comment]
It was fixed in FFImageLoading v2.2.25, you can safely update, but just remember to disable fast renderer with `CachedImageRenderer.Init(false)`.

**Comment by wenyonk** [comment]
Daniel,
Thank you for the quick response.  
Thank you for the CachedImageRenderer.Init(false) tip.

Where can I find additional information on the new behavior (*.Init(true))
  What are the advantages or Why
  What are the side effects developers should consider in making the change
  What might be the typical code change to have the *.Init(true) behavior?

**Comment by daniel-luberda** [comment]
`true` uses fast renderers, read more here: https://developer.xamarin.com/guides/xamarin-forms/under-the-hood/fast-renderers/
