### ISSUE TITLE
ReplaceStringMap doesn't work

### ISSUE THREAD

**Issue by stmax82** [luberda-molinet/FFImageLoading#833]
I'd like to replace a color within an SVG file.

As far as I found out, ReplaceStringMap is the way to go.

The following example should display a **blue** rectangle, but it's **red** (as defined in the SVG file):

The SVG file contains a **red** rectangle:

```
<svg viewBox="0 0 24 24">
  <rect fill="#ff0000" width="24" height="24" />
</svg>
```

Code to display the image - note the ReplaceStringMap should replace **red** by **blue**:

```
  public partial class MainPage : ContentPage {
    public MainPage() {
      var layout = new StackLayout();

      layout.Children.Add(new SvgCachedImage {
        Source = "resource://Foo.Images.test.svg",
        ReplaceStringMap = new Dictionary<string, string> { { "ff0000", "0000ff"} },
        WidthRequest = 98, HeightRequest = 98
      });

      this.Content = layout;
    }
```

The result is a **red** rectangle instead of a **blue** one. Am I doing something wrong?

(PS.: I also tried calling ReloadImage() but that didn't help either)

Xamarin.FFImageLoading.Svg version is 2.2.25.

**Comment by daniel-luberda** [comment]
It should work. You don't need to call `ReloadImage`. Could you check:

```C#
      layout.Children.Add(new SvgCachedImage {
        ReplaceStringMap = new Dictionary<string, string> { { "ff0000", "0000ff"} },
        WidthRequest = 98, HeightRequest = 98
        Source = "resource://Foo.Images.test.svg",
      });
```

Are you sure you have same package versions in all projects?

**Comment by stmax82** [comment]
Yes all projects use the same version.

It looks like the order in which the properties are set matters:

This one does not work (image stays red):

```
      layout.Children.Add(new SvgCachedImage {
        Source = "resource://ReplaceStringMapProblem.test.svg",
        ReplaceStringMap = new Dictionary<string, string> { { "ff0000", "0000ff" } },
        WidthRequest = 98, HeightRequest = 98
      });
```

This one works (image turns blue):

```
      layout.Children.Add(new SvgCachedImage {
        ReplaceStringMap = new Dictionary<string, string> { { "ff0000", "0000ff" } },
        Source = "resource://ReplaceStringMapProblem.test.svg",
        WidthRequest = 98, HeightRequest = 98
      });
```

So it seems like the replacement does not work when the ReplaceStringMap property is set after the Source property.

**Comment by lsrob123** [comment]
Hi Daniel,

This is sort of like a bug. in XAML, if you do things like

<forms:SvgCachedImage x:Name="SvgExpanderIcon" VerticalOptions="Fill" HorizontalOptions="Fill"
                          Source="resource://something.svg" ReplaceStringMap="{Binding ColorMaps}" 
                          ></forms:SvgCachedImage>

string replacement just won't work. 

You have to set ReplaceStringMap before setting the Source

<forms:SvgCachedImage x:Name="SvgExpanderIcon" VerticalOptions="Fill" HorizontalOptions="Fill"
                          ReplaceStringMap="{Binding ColorMaps}" Source="resource://something.svg"
                          ></forms:SvgCachedImage>

Cheers

Lixin

**Comment by AaronV-T** [comment]
I have created a custom class `RecolorableSvg` that inherits from `SvgCachedImage` with a bindable property `NewColor` that changes colors in the SVG by setting the `ReplaceStringMap`. Unfortunately, it only works if I set the NewColor before the RecolorableSvg object is initialized; setting NewColor to an explicit color (e.g. XAML: `NewColor="Red"`) will successfully recolor the SVG, but setting NewColor via a XAML binding does nothing.

Calling `svg.ReloadImage();` 
 and `svg.OnPropertyChanged(nameof(FFImageLoading.Forms.CachedImage.SourceProperty));` do nothing. The only way that I can get the SVG to successfully change color is by setting its `Source` to the resource path string but is not desirable because it requires a bindable property just to remember the path to the source file and it takes time for the image to update.

Here is the code that runs when the NewColor property changes:

    private static void OnNewColorPropertyChanged(BindableObject bindable, object oldValue, object newValue)
    {
      var svg = (RecolorableSvg)bindable;
      var newColor = (Color)newValue;

      string oldColorText = svg.OriginalColorText;
      if ((Color)oldValue != Color.Default)
      {
        oldColorText = ((Color)oldValue).GetHexString();
      }

      svg.ReplaceStringMap = new Dictionary<string, string>
      {
        { $"fill=\"{oldColorText}\"", $"fill=\"{newColor.GetHexString()}\"" }
      };

      svg.Source = svg.SourcePath; // Without this line the SVG will not be recolored.
    }

**Comment by andreysilov** [comment]
For me it works on both platforms (iOS and Android):

```
if (Source is SvgImageSource source)
{
    var colorMap = new Dictionary<string, string> { { "regex:fill=\"#(?:[0-9a-fA-F]{3}){1,2}\"", $"fill=\"{color.ToHex()}\"" } };
    source.ReplaceStringMap = colorMap;
    ReplaceStringMap = colorMap;
}
```
