### ISSUE TITLE
[question]: FFImageLoading for map pin

### ISSUE THREAD

**Issue by RaoulNL** [luberda-molinet/FFImageLoading#834]
In what way can I use FFImageLoading for displaying a pin with a custom image on a Google Maps View.
Note that the question is not about displaying the pin on a map, but to use the custom image for that particular pin.

Regards, Raoul

**Comment by daniel-luberda** [comment]
This is quite a general question, but I'll try to answer:

- You can use SVG files for your pins
- If you have a lot of pins (same image), FFImageLoading will save RAM as it reuses / caches bitmaps

Do you use Xamarin.Forms.Maps or native google maps?

**Comment by RaoulNL** [comment]
I do not use Xamarin.Forms.Maps, but the package Xamarin.Forms.GoogleMaps in both the Android and iOS project. And yes; there can be quite a few pins on the map.
The images I need for the pins reside on some backend server, so I need to download them first I order to use them at a later stage in the map.
Can you point me in the right direction how I could use your package to accomplish this?

**Comment by daniel-luberda** [comment]
You must ask at project site for details, but in short: just use `CachedImage` for pins: 

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/BitmapDescriptorFactory.cs#L23

Just set `CachedImage.Source` to your http image address, FFImageLoading will handle everything for you (caching, download, etc).
