### ISSUE TITLE
FFimageLoading never appaering in Carousel

### ISSUE THREAD

**Issue by PierreCourt** [luberda-molinet/FFImageLoading#836]
Hello,

I use the Carousel of rainman (https://github.com/alexrainman/CarouselView) with your FFImageLoading in it. 

```
 <carousel:CarouselViewControl>
         <carousel:CarouselViewControl.ItemTemplate>
                     <DataTemplate>
                             <Grid Padding="0,10,0,10" >
                                 <ffimageloading:CachedImage
                                 Aspect="AspectFit"
                                 IsVisible="{Binding FrontIsVisible}"
                                 Source="{Binding TheCard.UrlRecto}"
                                     CacheType="Disk" />
                                 <ffimageloading:CachedImage
                                 Aspect="AspectFit"
                                 IsVisible="{Binding BackIsVisible}"
                                 Source="{Binding TheCard.UrlVerso}"
                                      CacheType="Disk" />
                             </Grid>
                    </DataTemplate>
          </carousel:CarouselViewControl.ItemTemplate>
   </carousel:CarouselViewControl>
```

The problem is that after a moment (it is not consistent), the images are not loading anymore. And when it is happening and I go back to the previous images, they disappeared. I tried with the 2.2.24 and 2.2.25.

Do you have any idea why ?

Thanks

**Comment by daniel-luberda** [comment]
- Does it work when you replace `CachedImage` with `Image`
- Which platform?

**Comment by PierreCourt** [comment]
I tested it on Android and I with Image, there is the same problem. I found that it was a OutOfMemory, so I used your Downsample and it seems to works.

Thanks !

**Comment by daniel-luberda** [comment]
@PierreCourt if it's OOM there is probably a memory leak somewhere in `CarouselViewControl` - you should report it on project's site. Cheers.
