### ISSUE TITLE
Caching Downsampled images ?

### ISSUE THREAD

**Issue by Giorgi** [luberda-molinet/FFImageLoading#837]
Hello,

Does this library keep a disk cache for Down-sampled images or does it resize them every time an image is displayed? I am showing images already stored on the device in external folder and I don't have any images in disk cache folder. I know that down-sampling is working because I'm not getting an error about it in my custom logger.

**Comment by EmilAlipiev** [comment]
what is an  external folder i dont know if you mean drawables for android but if you use downsample and caching together, it caches your original image as downsampled and your ui is using this image everytime until your expiry date. So in this case it wont do resizing. It is all documented and there is already similar question. you should do your research before you ask this question.

**Comment by Giorgi** [comment]
I mean a folder outside of the app files which contains images taken by camera. When I load an image from a url I get log entries printed by `Disk_Cache` and I can see cached images in FFSimpleDiskCache folder.

When I load images from that folder I get log entries printed by `MEMORY_CACHE` and no resized images in FFSimpleDiskCache folder. I want to cache the resized images so that when I launch the app second time it does not need to load the large images again and so that it doesn't spend time resizing the images.

Is that possible?

**Comment by daniel-luberda** [comment]
You can manually save files as FFImageLoading is able to return you a JPG/PNG `Stream`:

```C#
using (var stream = await ImageService.Instance.LoadFile("/Path").DownSample(width: 200).AsJPGStreamAsync())
{
//save stream to disk
}
```

**Comment by Giorgi** [comment]
I could do that but I don't know how wide the image view will be until runtime and also I think this is something that the library should be taking care of, not the developer.

**Comment by RedasP** [comment]
Hello, not sure if I have to make a new thread, since my issue is exactly the same, but I just have something to add.

If I save the stream to disk and load the image later using CachedImage, will CachedImage remove it from cache and disk when duration is expired or will I have to manually remove the file when it's expired?
