### ISSUE TITLE
Preloading: Is't possible to use a color instead of an image?

### ISSUE THREAD

**Issue by biapar** [luberda-molinet/FFImageLoading#838]
Is't possible to use a color instead of an image?

**Comment by EmilAlipiev** [comment]
Do you mean about LoadingPlaceholder ?

**Comment by biapar** [comment]
Yes...but use a colour instead of an image.

**Comment by daniel-luberda** [comment]
You can use SVG files with `SvgCachedImage`. Just set `LoadingPlaceholder` property to string: 

```XML
<svg width="400" height="400">
  <rect width="400" height="400" style="fill:red;" />
</svg>
```
