### ISSUE TITLE
Unable to activate instance of type Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer from native handle

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#839]
Hi,

I am getting a weird issue with fast renderers in latest XF. I reported on bugzilla here https://bugzilla.xamarin.com/show_bug.cgi?id=60961

I only wanted to check that it is not issue with ffimageloading because i am using only ffimageloading. Have you ever happened to see something like that?

**Comment by daniel-luberda** [comment]
FFImageLoading doesn't use `Forms.SetFlags("FastRenderers_Experimental")` at all. So it's rather Xamarin.Forms issue.
