### ISSUE TITLE
Applying a transformation on a stream?

### ISSUE THREAD

**Issue by RaoulNL** [luberda-molinet/FFImageLoading#840]
Just found the way to directly load the image from a URL:
`Stream imageStream = await ImageService.Instance.LoadUrl(resourceURL).AsPNGStreamAsync();`

Now I want to apply a transformation on this result. How would I do that?

**Comment by daniel-luberda** [comment]
`Stream imageStream = await ImageService.Instance.LoadUrl(resourceURL).Transform(new CircleTransformation()).AsPNGStreamAsync();`, etc.
