### ISSUE TITLE
Image isn't loaded into UIImageView if LoadUrl() is called twice for the same URL

### ISSUE THREAD

**Issue by walkerj77** [luberda-molinet/FFImageLoading#841]
I have a UITableView with cells that contain an UIImageView that I'm loading images into from a URL using MvvmCross.

The cell's class looks like this:

    public partial class ImageCellView : MvxTableViewCell
    {
        private const string BindingText = @"ImageUrl ImageUrl";

        public ImageCellView(IntPtr handle) : base(BindingText, handle)
        {
        }

        private string _imageUrl { get; set; }

        public string ImageUrl
        {
            get { return _imageUrl ?? string.Empty; }
            set
            {
                _imageUrl = value;

                ImageService.Instance
                    .LoadUrl(_imageUrl)
                    .LoadingPlaceholder("PlaceholderImage", ImageSource.CompiledResource)
                    .DownloadProgress((DownloadProgress obj) =>
                    {
                        var progress = obj.Total != 0 ? (double)obj.Current / (double)obj.Total : 0;
                        Debug.WriteLine($"Downloading: {progress:P2} ({_imageUrl}) {ImageView}");
                    })
                    .Success(() => { Debug.WriteLine($"Success: {_imageUrl}"); })
                    .Error((error) => { Debug.WriteLine($"Error: {_imageUrl} {error.Message}"); })
                    .Finish((obj) => { Debug.WriteLine($"Finished: {_imageUrl}"); })
                    .Into(ImageView);
            }
        }
    }

I'm not sure what causes this, but occasionally, when scrolling through the tableview very fast, I will see the following in the application output:

    Downloading: 7.89 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe627350;>
    Downloading: 7.89 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe625ff0;>
    Downloading: 23.42 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe627350;>
    Downloading: 23.42 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe625ff0;>
    Downloading: 39.20 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe627350;>
    Downloading: 39.20 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe625ff0;>
    (... yada yada yada ...)
    Downloading: 94.42 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe627350;>
    Downloading: 94.42 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe625ff0;>
    Downloading: 100.00 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe627350;>
    Downloading: 100.00 % (http://url.to.my/image.jpg) <OdImageView: 0x7fcbfe625ff0;>
    Success: http://url.to.my/image.jpg
    Finished: http://url.to.my/image.jpg`

A few things that are odd about this:
- Despite the image having completely downloaded, the UIImageView still displays only the image specified in _LoadingPlaceholder_ and not the image from the URL.
- The target UIImageView is different in the duplicate call to the _DownloadProgress_ delegate (0x7fcbfe627350 vs. 0x7fcbfe625ff0). This may be because two cells were dequeued and assigned the same image URL??? However, ...
- Even though there are duplicate calls to the _DownloadProgress_ delegate, the _Success_ and _Finished_ delegates are only called once, which makes me question if it's two distinct calls to _LoadUrl_ that are being made.

The image is definitely being loaded and cached, because if I scroll the tableview so that the affected cell is out of view and then scroll it back into view, the correct image is displayed. It's just not being displayed on the first call.

Is this a bug in FFImageLoading behavior or is it due to me not using FFImageLoading (and possibly FFImageLoading + MvvmCross) incorrectly?

**Comment by daniel-luberda** [comment]
> Despite the image having completely downloaded, the UIImageView still displays only the image specified in LoadingPlaceholder and not the image from the URL.

It's a normal behaviour as decoding image file also shows loading placeholders. (eg when bitmap is not present in memory cache)

> The target UIImageView is different in the duplicate call to the DownloadProgress delegate (0x7fcbfe627350 vs. 0x7fcbfe625ff0). This may be because two cells were dequeued and assigned the same image URL??? However, ...

You forgot that cells are reused (especially when fast scrolling). You should cancel earlier image loading task first: 

```C#
public partial class ImageCellView : MvxTableViewCell
{
    private const string BindingText = @"ImageUrl ImageUrl";
    IScheduledWork _task;

    public ImageCellView(IntPtr handle) : base(BindingText, handle)
    {
    }

    private string _imageUrl { get; set; }

    public string ImageUrl
    {
        get { return _imageUrl ?? string.Empty; }
        set
        {
            _imageUrl = value;

            _task?.Cancel();
            _task = ImageService.Instance
                .LoadUrl(_imageUrl)
                .LoadingPlaceholder("PlaceholderImage", ImageSource.CompiledResource)
                .DownloadProgress((DownloadProgress obj) =>
                {
                    var progress = obj.Total != 0 ? (double)obj.Current / (double)obj.Total : 0;
                    Debug.WriteLine($"Downloading: {progress:P2} ({_imageUrl}) {ImageView}");
                })
                .Success(() => { Debug.WriteLine($"Success: {_imageUrl}"); })
                .Error((error) => { Debug.WriteLine($"Error: {_imageUrl} {error.Message}"); })
                .Finish((obj) => { Debug.WriteLine($"Finished: {_imageUrl}"); })
                .Into(ImageView);
        }
    }
}
```

I advise you to use `MvxCachedImageView` which is a MVVMCross oriented control (it supports bindings etc), you just bind to `ImageSource` and forget about anything. It's included in `FFImageLoading` package. Demo here: https://github.com/luberda-molinet/FFImageLoading/tree/master/samples/ImageLoading.MvvmCross.Sample

You can look how it's implemented here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Cross/MvxCachedImageView.cs#L282


> Even though there are duplicate calls to the DownloadProgress delegate, the Success and Finished delegates are only called once, which makes me question if it's two distinct calls to LoadUrl that are being made.

When you fast scroll some download operations are simply cancelled and must be repeated once again.

**Comment by walkerj77** [comment]
**\<SOLVED\>**

> I advise you to use MvxCachedImageView which is a MVVMCross oriented control.

I did this as per the sample code, and it worked perfectly. Scrolling is much smoother now and no images get "stuck". Thank you!

> You forgot that cells are reused (especially when fast scrolling).

I knew this was happening, I just didn't think to capture the task returned by _LoadUrl_ and cancel it, figuring that FFImageLoading wouldn't attempt to pull from cached images if the same URL was being loaded a second time. Good to know, though.

**Comment by daniel-luberda** [comment]
> figuring that FFImageLoading would attempt to pull from cached images if the same URL was being loaded a second time

Many people expect that behaviour, that's why I implemented it. With https://github.com/luberda-molinet/FFImageLoading/commit/cbbd6b4a7c1185a74799042049cab6f1c3f5b8ac FFImageLoading automatically does that.
