### ISSUE TITLE
[Android] 2.2.25: AspectFill does not clip the Image correctly.

### ISSUE THREAD

**Issue by voydz** [luberda-molinet/FFImageLoading#843]
Hi there,

I implemented loads of CachedImages in my app, here are some example implementations.

**Implementation**
```xaml
<!-- Contained in a relative layout -->
<ff:CachedImage
  Aspect="AspectFill"
  DownsampleToViewSize="true"
  LoadingPlaceholder="{StaticResource placeholder}"
  ErrorPlaceholder="{StaticResource placeholder}"
  Source="{Binding ImageUrl}"
  IsVisible="{Binding HasImage}"
  RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1, Constant=0}"
  RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1, Constant=0}"
  RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=0, Constant=0}">
  <ff:CachedImage.GestureRecognizers>
    <TapGestureRecognizer
      Command="{Binding SelectImageCommand}" />
  </ff:CachedImage.GestureRecognizers>
</ff:CachedImage>
```

[Click here for Preview of the issue with this implementation](https://www.dropbox.com/s/a66cuwea4opl69p/Screenshot%202017-12-05%2009.43.01.png?dl=0)

```xaml
<!-- Contained in a grid as cell inside of a listview -->
<ff:CachedImage
  Grid.Column="1"
  HeightRequest="65"
  WidthRequest="60"
   Aspect="AspectFill"
   DownsampleToViewSize="true"
   LoadingPlaceholder="{StaticResource placeholder}"
   ErrorPlaceholder="{StaticResource placeholder}"
   Source="{Binding ImageUrlFallback}" />
```

[Click here for Preview of the issue with this implementation](https://www.dropbox.com/s/zxdyn9v7gq8nwkw/Screenshot%202017-12-05%2009.42.29.png?dl=0)

**Issue**
This issue seems to be only appearing on Android. (Tested it with a Nexus 5 and a x86 Android 7.1. simulator) 

The CachedImage should crop their bitmaps according to `Aspect="AspectFill"`. This worked fine in the past. However upgrading to 2.2.25 the bitmaps are scaled, maintaining their aspect ratio, but the edges passing the actual views bounds are not clipped.

**Things I tried already**
- setting CachedImage.FixedOnMeasureBehavior = true
- enable Xamarin Forms fast renderers

Any help would be much appreciated.

**Comment by voydz** [comment]
After digging some more related issues and reading through the comments of #813 again. I tried to explicitly **disable the fast renderer support**. Doing this, the images are displayed just fine again.

I would not consider this issue closed though, as this is only a workaround.

So for people running into the same issue try to pass `false` as the first argument of the initialization call. Like so: `CachedImageRenderer.Init(false);`

**Comment by daniel-luberda** [comment]
Hi @voydz  It's a Xamarin.Forms issue, not FFImageLoading. I will probably change `Init` method from optional param to required param instead, so the user will notice that it has two options on Android. 

See this: https://github.com/luberda-molinet/FFImageLoading/issues/830 - there's a workaround mentioned there too. 

>Note: Using IsClippedToBounds="true" on a nested StackLayout in the demo project resolves the problem, but this was not required before XF 2.3.5 and don't want to assume this is a fix (may be a workaround).
