### ISSUE TITLE
Adnroid Crash - System.NullReferenceException: Object reference not set to an instance of an object.  at FFImageLoading.Forms.Droid.CachedImageFastRenderer.OnTouchEvent 

### ISSUE THREAD

**Issue by bolicd** [luberda-molinet/FFImageLoading#844]
Im using Xamarin.Fomrs v2.4.0.266-pre1.

When clicking on image i keep getting this exception.
`0x7fedd83ff450] worker parking
12-05 10:48:06.032 I/MonoDroid( 3096): System.NullReferenceException: Object reference not set to an instance of an object.
12-05 10:48:06.032 I/MonoDroid( 3096):   at FFImageLoading.Forms.Droid.CachedImageFastRenderer.OnTouchEvent (Android.Views.MotionEvent e) [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Forms.Droid\CachedImageFastRenderer.cs:125 
12-05 10:48:06.032 I/MonoDroid( 3096):   at Android.Views.View.n_OnTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x0000f] in <d278c06ad5684d6882c743a94a93ebc2>:0 
12-05 10:48:06.032 I/MonoDroid( 3096):   at (wrapper dynamic-method) System.Object:a690faad-e1da-423d-8da6-c0400cbaa2ac (intptr,intptr,intptr)`

Not sure if this is something related to Xamarinf forms or this library? 

Any thoughts?

Im using Xamarin.FFImageLoading -Version 2.2.25 Xamarin.FFImageLoading.Forms -Version 2.2.25

**Comment by TobiasBuchholz** [comment]
Same for me with version 2.2.25 and Xamarin.Forms 3.0.0.101-embeddingpreview.

One possible workaround for now is to disable the `CachedImageFastRenderer` by calling `CachedImageRenderer.Init(false);` in the `MainActivity`.

**Comment by daniel-luberda** [comment]
`_visualElementRenderer` apis are internal, so I am forced to use reflection, which is well tested only on newest XF stable.  https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs#L77-L85

Reflection code is here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms.Droid/CachedImageFastRenderer.cs#L33


Any clues?

**Comment by TobiasBuchholz** [comment]
After updating to Xamarin.Froms 2.5.0.121934 the `NullReferenceException` isn't occurring anymore. I guess you are right, it was a problem regarding to the reflection code.
