### ISSUE TITLE
RoundedTransformation makes Rectangled image Squared with correct corners.

### ISSUE THREAD

**Issue by aleksandrsmyk** [luberda-molinet/FFImageLoading#845]
Using this transformation squared images are good, but rectangled started to be like squared.

**Comment by daniel-luberda** [comment]
Set correct `CropWidthRatio` / `CropHeightRatio` properties for your `RoundedTransformation`, eg 2 / 1 for rectangle. This is how it works.

**Comment by aleksandrsmyk** [comment]
@daniel-luberda Thank you. But how can I detect these CropWidthRatio / CropHeightRatio? I dont know the type of an image (square or rectangle) and the height/width.
