### ISSUE TITLE
Cache cannot be invalidated (Xamarin iOS)

### ISSUE THREAD

**Issue by gbuyukliev** [luberda-molinet/FFImageLoading#847]
`imagePath = value;`
`ImageService.Instance.LoadFile(ImagePath)
                            .LoadingPlaceholder(@"/Images/Placeholder.png")
                            .Into(TheImageView);`

This is the code that I'm using in the setter of `imagePath` - the path that I'm using for each of my UIColectionView's reusable cells.

The path remains the same every time I change the image, however, so because of the caching it's never really updated. Ideally I would want to invalidate the cache for that particular entry once the image is changed. I tried calling `InvalidateCacheAsync`, `InvalidateMemoryCache`, `InvalidateDiskCacheAsync`, `InvalidateCacheEntryAsync` before loading the image, even afterwards. Nothing works.

**Comment by daniel-luberda** [comment]
- Do you await those `async` calls?
- `ImageService.Instance.InvalidateCacheEntryAsync("/Images/Placeholder.png", Cache.CacheType.All, true);` should works just fine.
