### ISSUE TITLE
Add CachedButton implementation for Xamarin.Forms

### ISSUE THREAD

**Issue by daniel-luberda** [luberda-molinet/FFImageLoading#850]
It'll allow us to use SVG's and all other FFImageLoading features.

**Comment by candidodmv** [comment]
Hi @daniel-luberda, could you tell me if it's possible to use FFImageLoading as ImageSource for any others controls that offer this feature? like I remember right now, button, tabbed page, navigation bar ?

**Comment by daniel-luberda** [comment]
Hi @candidodmv,

It's possible only if control supports `StreamImageSource`. Then something like: 

```C#
var stream = await ImageService.Instance.LoadUrl("http://image...").AsJpgStreamAsync();
```

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/issues/860

**Comment by candidodmv** [comment]
Thanks @daniel-luberda  for quick answer, but I dont understand how to use your sample, could you show using a button for exemple?

**Comment by daniel-luberda** [comment]
https://developer.xamarin.com/api/type/Xamarin.Forms.StreamImageSource/

If the control support stream image source, you could provide one. I gave you code which can generate an image stream with FFImageLoading.
