### ISSUE TITLE
Memory leak using gif? 

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#852]
I am using cachedimage withint listview datatemplate as below and when I profile, I am seeing cycles for 
LoadingPlaceholder  using as gif as shown below? Does it mean that when we use gifs we have memory leak?

```
    <ffimageloading:CachedImage 	Aspect="AspectFit" WidthRequest="48" HeightRequest="48"    BackgroundColor="Transparent" Margin="5"  
                                        LoadingPlaceholder = "loading.gif" DownsampleToViewSize="True"  
                            CacheType="Disk" CacheDuration="30"  TransparencyEnabled = "false"   InputTransparent="True" ErrorPlaceholder="{Binding errorimageurl}"
                                              Source="{Binding imageurl}"
                            />
```

![image](https://user-images.githubusercontent.com/10422347/33843751-83257468-de9e-11e7-8171-8c26600ac0da.png)

**Comment by daniel-luberda** [comment]
@EmilAlipiev Yes, good catch, I made a new implementation for gif delay. Thanks!

**Comment by EmilAlipiev** [comment]
@daniel-luberda  thank you for your response. I am wondering something, i didnt check myself in details maybe you can give me quicker answer.

If I am using LoadingPlaceholder within the listview, those loading images are first displayed until actual image is displayed. what happens to those LoadingPlaceholder image after that? are they still hold in the memory or they are disposed immediately after the Source image is displayed?

**Comment by daniel-luberda** [comment]
Yes, loading placeholders are also cached, they're purged if not used (as any other image) when cache limit is reached.

**Comment by EmilAlipiev** [comment]
@daniel-luberda Do you think if it can be possible to purge it directly after the actual image is displayed in order to keep the memory usage lower?  btw, please let me know if you make new nuget update with this fix, i will profile again. thank you

**Comment by daniel-luberda** [comment]
Yes, it's possible, just call `ImageService.Instance.InvalidateCacheEntryAsync` for your placeholder in `CachedImage.Success` callback. 

It's released now.

**Comment by EmilAlipiev** [comment]
@daniel-luberda  android library has support.exif dependency. if I may ask what is it for? is it something related?

**Comment by EmilAlipiev** [comment]
@daniel-luberda  this update doenst seem to be working for me at all. gifs are runinng all the time, actual image is not displayed until i scroll the in the listview up and down. other problem using fastrenderers:true, i am gettin timeout. using fastrenrers=False i get exception below.

12-16 01:39:02.444 E/mono-rt (10137): [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.referenceTable GDEF length=814 1
referenceTable GSUB length=11364 1
referenceTable GPOS length=47302 1

**Comment by daniel-luberda** [comment]
Are you sure you have the same package version in every project?

**Comment by EmilAlipiev** [comment]
yes i have all 2.3.1 and all my other packages are also up to date. I have just updated support.exif latest version, I think your nuget update has older version as reference? any problem updating this library?

**Comment by EmilAlipiev** [comment]
@daniel-luberda ok I fixed the error by deleting bin and obj folder under the PCL project. I usually delete bin, obj folders of Android project but this time was somehow required PCL as well. 

 Using fastrenderers:true without   LoadingPlaceholder="loading.gif"  is awesome. images are loaded super fast from disk. Thanks for that. but when I use  LoadingPlaceholder as gif, gif is displayed all the time. Sometimes even, gif is displayed, actual image appears very fast and again gif is displayed. If  I scroll up and down to disappear image and appear on the screen again, gif disappears and actual image is displayed

**Comment by daniel-luberda** [comment]
Hi @EmilAlipiev 

> android library has support.exif dependency. if I may ask what is it for? 

Up to this day, only reading exif orientation from local files was possible. With this we're able to read EXIF from every source, including url - just the same as iOS platform does (unified behaviour). 


> Using fastrenderers:true without LoadingPlaceholder="loading.gif" is awesome. images are loaded super fast from disk. Thanks for that. but when I use LoadingPlaceholder as gif, gif is displayed all the time. Sometimes even, gif is displayed, actual image appears very fast and again gif is displayed. If I scroll up and down to disappear image and appear on the screen again, gif disappears and actual image is displayed

Thank you ❤️ After reviewing some code, I think I know the possible cause for that. Let me see if I could fix it.

**Comment by daniel-luberda** [comment]
Try 2.3.2-pre. Is it better?

**Comment by EmilAlipiev** [comment]
@daniel-luberda yes, it works perfect. i tested with connection, slow connection, without connection all cases passed. only i found a small problem with the ErrorPlaceholder. If I have image inside grid without fix height weight using Aspect="AspectFit", Image is fitting fine inside grid but when no connection, ErrorPlaceholder doesnt fit, it appears very small.

**Comment by EmilAlipiev** [comment]
Ok i see that you changed the default behavior in this release. using             FFImageLoading.Forms.CachedImage.FixedOnMeasureBehavior = false; fixed the size problem

**Comment by EmilAlipiev** [comment]
@daniel-luberda  I found an issue here. If I cache the image with above xaml on disk and i set my phone on plane mode, restart the app, cached image is appearing shortly in the listview but then it starts showing loading.gif  all the time. So this is otherway around, previous one was under wifi connection using cachetype memory.

**Comment by daniel-luberda** [comment]
> I found an issue here. If I cache the image with above xaml on disk and i set my phone on plane mode, restart the app, cached image is appearing shortly in the listview but then it starts showing loading.gif all the time. So this is otherway around, previous one was under wifi connection using cachetype memory.

I don't understand. Could you explan what is the issue in details? Thanks.
