### ISSUE TITLE
Exif rotation broken (Android)

### ISSUE THREAD

**Issue by sabvente** [luberda-molinet/FFImageLoading#853]
Hi,

Unfortunately exif image rotation doesn't work for me. The lib seems to be ignoring the jpeg exif rotation attribute.

Looking at FFImageLoading source I found out that there is no calls to `ExifExtensions.ToRotatedBitmap` in the `FFImageLoading.Droid` project. Is that on purpose?
I think `PlatformImageLoaderTask.PlatformGenerateBitmapAsync` should do additional work, when the `exifRotation` variable is not 0.

Thanks for your work :)

**Comment by daniel-luberda** [comment]
It was a regression. Fixed. Thanks for the info! :)

**Comment by sabvente** [comment]
Thank you @daniel-luberda!

**Comment by szotp** [comment]
@daniel-luberda Is `CachedImage` with EXIF orientation supported? It doesn't seem to work.
