### ISSUE TITLE
CachedImage does not respect size when set aspect property to AspectFill on Android

### ISSUE THREAD

**Issue by wallacesantos** [luberda-molinet/FFImageLoading#854]
If I define this use to CachedImage:
<ff:CachedImage x:Name="imageAvatar"
                        Source="{Binding Source}"
                        LoadingPlaceholder = "progress"
                        ErrorPlaceholder="user_100"
                        DownsampleToViewSize="true"
                        CacheDuration="0"
                        HeightRequest="90"
                        WidthRequest="90" 
                        Aspect="AspectFill"/>

The image does not respect the defined size if it is not a square, exceding in the major dimension. This behavior happens only on Android.

**Comment by daniel-luberda** [comment]
It's Xamarin.Forms bug. Duplicate & more info here: https://github.com/luberda-molinet/FFImageLoading/issues/830
