### ISSUE TITLE
2.3.0 ios on device

### ISSUE THREAD

**Issue by iWeaverMan** [luberda-molinet/FFImageLoading#857]
Wrapper type 'WebP.Touch.WebPDecoder' is missing its native ObjectiveC class 'WebPDecoder'.

**Comment by daniel-luberda** [comment]
- Do you have the same package version in all projects?
- Did you delete all `bin`/`obj` folders. from your projects?

**Comment by daniel-luberda** [comment]
I think there's an issue in a nuspec file. You should also update WebP package.

**Comment by daniel-luberda** [comment]
Fixed in 2.3.1 (should be visible soon)
