### ISSUE TITLE
error CS7036: There is no argument given that corresponds to the required formal parameter 'enableFastRenderer' of 'CachedImageRenderer.Init(bool?)'

### ISSUE THREAD

**Issue by K232** [luberda-molinet/FFImageLoading#862]
I've updated to Xamarin Forms 2.3.1 today and now I get the following error message when I try to compile the Android project:

_error CS7036: There is no argument given that corresponds to the required formal parameter 'enableFastRenderer' of 'CachedImageRenderer.Init(bool?)'_

In MainActivity I've used
`FFImageLoading.Forms.Droid.CachedImageRenderer.Init();`
which worked fine until today.

Using
`FFImageLoading.Forms.Droid.CachedImageRenderer.Init(true);`
fixed the problem, I just wanted to let you know.

Have a nice weekend!

**Comment by K232** [comment]
P.S. iOS works fine with
`FFImageLoading.Forms.Touch.CachedImageRenderer.Init();`

**Comment by daniel-luberda** [comment]
Hi @K232 

It's mentioned in the release: https://github.com/luberda-molinet/FFImageLoading/releases/tag/v2.3.1

**Comment by K232** [comment]
OK thanks! I only checked [Xamarin.Forms API](https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API)

**Comment by daniel-luberda** [comment]
I'll update it, sorry :)
