### ISSUE TITLE
Question: dynamically modifying a transformation

### ISSUE THREAD

**Issue by kentcb** [luberda-molinet/FFImageLoading#864]
Hi,

I'm trying to dynamically change a blur transformation. I found that if I just update the `BlurredTransformation` object directly, nothing happens. I can force things to update via the `ReloadImage` method, but doing so creates an unpleasant "in/out" effect as the image is reloaded. That is, the edges of the images seem to go in and out as the blur is modified and the image reloaded. If I replace the list of `ITransformation` objects completely at each update cycle, the same in/out effect occurs.

I'm just wondering if there's a better way to have the image update when transformations are modified?

**Comment by kentcb** [comment]
I figured out the cause of the in/out effect. It's because I also had a `CircleTransformation` _before_ the `BlurredTransformation`. Swapping the order of those solved that issue.

I'm still interested in whether forcing a reload of the image is the right thing to do.

**Comment by daniel-luberda** [comment]
Hi @kentcb,

Bindable transformations properties are not yet implemented: https://github.com/luberda-molinet/FFImageLoading/issues/860

Using `ReloadImage` is a valid way to refresh it. Also you can just set Transformations to a new list, it will also refresh: `image.Transformations = new List<ITransformation>(image.Transformations)`

**Comment by kentcb** [comment]
Yeah, I tried replacing the list of transformations per my original post. However, I was trying to do this with the best possible performance, especially as the transformation will be changed quite a lot as part of an animation.

**Comment by daniel-luberda** [comment]
This shouldn't affect performance, all it does internally is calling a reload method.

**Comment by kentcb** [comment]
Hmm, that seems to work OK on iOS. But on Android, calling `ReloadImage` too aggressively before it has had the chance to load at least once results in the image never appearing. I've hacked around this problem thusly:
```C#
var imageLoadedAtLeastOnce = false;

this
    .WhenAnyValue(x => x.ViewModel.UploadProgress)
    .Do(
        uploadProgress =>
        {
            this.blurTransformation.Radius = maximumBlurRadius - (uploadProgress * maximumBlurRadius);

            if (this.image.Source != null && !this.image.IsLoading)
            {
                imageLoadedAtLeastOnce = true;
            }

            // We have to wait until the image is loaded at least once, otherwise it may never display at all.
            if (imageLoadedAtLeastOnce)
            {
                this.image.ReloadImage();
            }
        })
    .SubscribeSafe()
    .AddTo(disposables);
```

**Comment by kentcb** [comment]
Ugh, and that doesn't work on iOS. It loads the image once, but subsequent changes to the blur don't appear unless sufficient time elapses between `ReloadImage` calls. I've changed to this, which seems the best I can do to support both platforms in a somewhat consistent manner:
```C#
// We can't reload the image too aggressively or it won't display at all.
if (!this.image.IsLoading || MathExtensions.ApproximatelyEqual(uploadProgress, 1f))
{
    this.image.ReloadImage();
}
```

**Comment by daniel-luberda** [comment]
@kentcb Try to set `LoadingDelay` to `0` (`15 ms` default)

**Comment by kentcb** [comment]
Yes, I already tried that - made no difference.
