### ISSUE TITLE
coloring svg progamatically

### ISSUE THREAD

**Issue by candidodmv** [luberda-molinet/FFImageLoading#865]
Considering the approach to generate svg images from scratch using ImageService.Instance.LoadUrl or ImageService.Instance.LoadString, which is the correct way to chage the color of the file or string that you don't know if there is inline color definitions to use replaceStringMap as described in documentation suggestion?

To be more specific, if I know what format the file or string, I can use replaceStringMap defining which color there is on the svg source code for another color that i want to use, but if I don't know which color there is i can't change the color because I dont know what replace to my desired color.

**Comment by daniel-luberda** [comment]
Changing random colours is a very unusual thing. 

- How could you determine which part you want to change? 
- Isn't it better to replace it on your own as SVG is just a string?

I could add `Regex.Replace` support, eg keys starting with `regex:` would be detected as regex.

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/commit/b3c50c6c0f3d41d5816f5b5676f3631a58ebf0d4

**Comment by daniel-luberda** [comment]
You can test it with 2.3.2-pre-663 prerelease package, wiki: https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support#svg-string-replacement-including-colors
