### ISSUE TITLE
Crash when using V2.3.1 ImageLoader

### ISSUE THREAD

**Issue by JKennedy24** [luberda-molinet/FFImageLoading#868]
Getting the following error when using FFImageLoader with Xamarin.Forms V2.4

> Could not resolve type with token 01000081 (from typeref, class/assembly Xamarin.Forms.PlatformConfiguration.AndroidSpecific.Elevation, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)

**Comment by daniel-luberda** [comment]
It's fixed (I wish I didn't have to use so much reflection to support older XF versions brrr)

**Comment by daniel-luberda** [comment]
You can test it with 2.3.2-pre-663 prerelease package
