### ISSUE TITLE
"twitching" icons on iOS in view cell - still an issue in latest

### ISSUE THREAD

**Issue by kspearrin** [luberda-molinet/FFImageLoading#869]
Hey @daniel-luberda ,

I left a comment on the #772 several days ago that 2.2.5 was still not working correctly regarding this problem. Since #772 was closed already, it didn't seem like it was getting any attention so I figured I would open this new issue to bring attention to the problem. Feel free to re-open #772 (and close this) or use this new issue for tracking.

Thanks!

**Comment by daniel-luberda** [comment]
@kspearrin Sure. I think it's a Xamarin layout bug. I don't know what else I can do.

**Comment by daniel-luberda** [comment]
Are you able to provide an isolated repo project for this?

**Comment by kspearrin** [comment]
I can work on providing a project sometime, but it definitely only happens after version 2.2.9 so I would assume the issues exists in this library rather than XF.

**Comment by daniel-luberda** [comment]
Does it also happen when you change `CachedImage` to `Image`?

**Comment by kspearrin** [comment]
@daniel-luberda No. XF 2.3 - 2.5 with `Image` do not have this problem. 2.2.9 of this library does not have the problem with `CachedImage`. Whenever I update to latest 2.3.1 of `CachedImage` the problem occurs.

**Comment by daniel-luberda** [comment]
I'll need a simple repo to go forward with it.

**Comment by kspearrin** [comment]
@daniel-luberda See test repo here: https://github.com/kspearrin/CachedImageTest

Only dealing with 1 file/page with a simple list view and bound view cell. Very basic:

https://github.com/kspearrin/CachedImageTest/blob/master/CachedImageTest/CachedImageTest/ListPage.cs#L11

**Comment by daniel-luberda** [comment]
There's no issue. Your images are corrupted, they contain multiple images and iOS detects it:

![screen shot 2018-01-04 at 17 40 05](https://user-images.githubusercontent.com/13569983/34574001-6ef66ff2-f176-11e7-8467-85fdfe2ba761.png)

**Comment by kspearrin** [comment]
Thanks for checking it out @daniel-luberda. Are .ico images not supported in `FFImageLoading`?

**Comment by daniel-luberda** [comment]
They're supported, but iOS decoder detects multiple images in container, we use the same mechanism to detect animated gif files. I could disable animations for ICO format, but I would need some help how to detect if the file is a ICO stream (header, magic strings etc), meanwhile you can avoid it by disabling gif support via custom config.

**Comment by kspearrin** [comment]
The content type of these ico images is always `image/x-icon`. The `.png` extension is just there for consistency when requesting them to our service and has no bearing on if it is actually a png or not.

**Comment by daniel-luberda** [comment]
Content type is not enough as we don't store it in a disk cache. We'll need to identify ICO from raw stream.

**Comment by kspearrin** [comment]
@daniel-luberda How are you detecting `gif` and others from the raw stream? `ico` does has a header in the stream that can be read as well I believe. I know `System.Drawing` detects it as a valid `ImageFormat` (Icon) so it must be possible.

Also,

> meanwhile you can avoid it by disabling gif support via custom config

Could you also point me in the direction on how to how to do this? Is this a custom config in `FFImageLoading` or something in the iOS app configuration somewhere?

**Comment by daniel-luberda** [comment]
https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Helpers/FileHeader.cs


AppDelegate.cs:

```C#
var config = new FFImageLoading.Config.Configuration()
{
  AnimateGifs = false,
};
ImageService.Instance.Initialize(config);
```

**Comment by kspearrin** [comment]
Thanks. I don't need gif support anyways so I will just disable it for now as a workaround.

**Comment by kspearrin** [comment]
@daniel-luberda This may be helpful. Here is the header information: https://en.wikipedia.org/wiki/ICO_(file_format)#Outline

**Comment by kspearrin** [comment]
I can confirm that setting AnimateGifs = false in the config resolves the problem.

IMO this issue should remain open until ICO format is properly supported.

**Comment by daniel-luberda** [comment]
As you see it's fixed already :) Cheers. https://github.com/luberda-molinet/FFImageLoading/commit/8e5b9e6e314b16390c8f7fc924af87d9fc573ec2
