### ISSUE TITLE
How to use CacheKeyFactory

### ISSUE THREAD

**Issue by jnormen** [luberda-molinet/FFImageLoading#870]
Hi,

I have an old problem with the new version of Xamarin Forms and FFImageLoader on iOS. (using.Net Standard 2.0)

In a cell inside a listview, I used a stream of an image. I create a unique image based on a pricetag length.
So each ViewCell shall have unique images with round corners. 

<forms:CachedImage
                    x:Name="PricePlate"
                    Aspect="AspectFill"
.../>

Code Behind:
...
PricePlate.Source = ImageSourc.FromStrem(....)
...

Works as a charm in UWP but in iOS all cells seem to share the absolute first Image I set. 
And when I scroll the images disappears.

I also set a new image each time a quantity label increases in the cell. 

The problem is that the image is increasing as intended on UWP but in iOS it always uses the absolute first image created on all cells. 

We are not using the RecycleElement thing. 

And I set the new image as soon my label got some changes.

PriceLabel.SizeChanged += PriceLabelOnSizeChanged;
..
    PricePlate.Source = ...
..

I tried the solution of OnBindingContextChange but still same problem.

And I also tried to add a CustomKeyFasctory to give me a unique key for each item. But then there is no image showing at all, But if I return null from my custom factory. The image shows again but still the same problem as above. 

     <forms:CachedImage
                    x:Name="PricePlate"
                    Aspect="AspectFill"
                    AbsoluteLayout.LayoutBounds="0.5, 0.5, -1, -1"
                    AbsoluteLayout.LayoutFlags="PositionProportional">
                    <forms:CachedImage.CacheKeyFactory>
                        <images:CustomCacheKeyFactory/>
                    </forms:CachedImage.CacheKeyFactory>

So a unique key value seems not work at all :/ 

Must I have missed something? Or why does not unique keys work? And why is the image still disappearing on scrolling? 

Best, Johan

**Comment by daniel-luberda** [comment]
Here's the sample of using custom cache key factory + custom `StreamImageSource` subclass which has a `Key` property [sample1](https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/ByteArrayListPageModel.cs#L120-L123) [sample2](https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/ByteArrayListPageCell.xaml.cs#L12-L26). This will allow FFImageLoading to use memory cache properly, without it, no images would be reused.

**Comment by jnormen** [comment]
yes tried that sample. That was my try with a customfactory. 

First, try I did with a datetime.now.Tick value. But no images showed up. 
second try with a hash value, same problem. When my factory returned a null key image show but the same problem as before, 

Here is my subclass. 

```
    public class KeyImageSource : StreamImageSource
    {
        public string Key { get; set; }

        public static ImageSource FromStream(Func<Stream> stream, string name)
        {
            var f = (ImageSource)new KeyImageSource()
            {
                Stream = (Func<CancellationToken, Task<Stream>>)(token => Task.Run<Stream>(stream, token)),
                Key = $"{DateTime.UtcNow.Ticks}-{name}".ToHash()
            };
            return f;
        }
    }

```
My factory:
```
 class CustomCacheKeyFactory : ICacheKeyFactory
    {
        public string GetKey(ImageSource imageSource, object bindingContext)
        {

            return null;
        }
}
```

And xaml:
```
   <forms:CachedImage
                    x:Name="PricePlate"
                    Aspect="AspectFill"
                    AbsoluteLayout.LayoutBounds="0.5, 0.5, -1, -1"
                    AbsoluteLayout.LayoutFlags="PositionProportional">
                    <forms:CachedImage.CacheKeyFactory>
                        <images:CustomCacheKeyFactory/>
                    </forms:CachedImage.CacheKeyFactory>
                    <forms:CachedImage.Transformations>
                        <transformations:TintTransformation 
                        HexColor="{StaticResource BUTTON_BACKGROUND_COLOR_AS_STRING}" EnableSolidColor="True" />
                    </forms:CachedImage.Transformations>
                </forms:CachedImage>
```

With null in my factory same problem as without a factory on iOS still show up the image but all cells seem to share the same one. Alla shall have different sizes, but all got the same size as the first cell image. In UWP everything works as expected. BUT uwp also do not show an image at all if I return other value then Null from my factory. 

Here is my method that creates the image for me. 

`  public static ImageSource GenerateRoundedCornerImageSource(int width, int height, int radius,string cacheKey = null, bool isAntialias = false)
        {
            var bitmap = new SKBitmap(width, height, SKImageInfo.PlatformColorType, SKAlphaType.Premul);

            var canvas = new SKCanvas(bitmap);
            canvas.Clear(SKColors.Transparent);

            var paint = new SKPaint
            {
                IsAntialias = isAntialias,
                Color = SKColors.Black
            };
            
            canvas.DrawRoundRect(new SKRect(0, 0,width, height), radius, radius, paint);

            var image = SKImage.FromBitmap(bitmap);
            var data = image.Encode(SKEncodedImageFormat.Png, 100);
            
            var ms = new MemoryStream();
            data.SaveTo(ms);
            
            return KeyImageSource.FromStream(() => ms, cacheKey);
        }`

**Comment by daniel-luberda** [comment]
```C#
class CustomCacheKeyFactory : ICacheKeyFactory
{
    public string GetKey(ImageSource imageSource, object bindingContext)
    {
        var keySource = imageSource as KeyImageSource;
        return keySource?.Key;
    }
}
```

**Comment by jnormen** [comment]
Still the same problem. 
As soon there is a value from key beside null, no images are in the list :( And if I send null, or remove the factory the images are there. BUT then I have the issue that iOS seems to show me only the first created image in all cells added. And removed them when scrolling outside the scroll. 

Not sure if you can access my dropbox. But I will try. 
In the box image with the name as the problem. 

https://www.dropbox.com/sh/8gnz8x8y1l3nxr0/AAClU8WDqB72F2QHZhuOM3iJa?dl=0

**iOS**
_With null key_
- Images are shown. But all are the same size as first ever made image in the list.
- At scolling images disapear

_With key from my code above (and yours with key set)_
- Images are not there at all

**UWP**
_With null key_
- Images are shown as expected. different size based on price length
- At scroll, they are still there. 
- When price label expand so do the image as I want to (not on iOS though it seams to share first image
created

_With key_
- No images are there

Android
Not tested yet.

**Comment by jnormen** [comment]
Damn, should not close this issue... pressed the wrong button...

**Comment by daniel-luberda** [comment]
It should work fine, but I noticed another error in you code. You must always return a new stream: 

Instead:

`return KeyImageSource.FromStream(() => ms, cacheKey);`

Do:

`return KeyImageSource.FromStream(() => new MemoryStream(bytes), cacheKey);` 

That's why those methods require actions not stream reference.

**Comment by jnormen** [comment]
Even if I have this?
 var ms = new MemoryStream(); ///New stream
 data.SaveTo(ms);
           
 return KeyImageSource.FromStream(() => ms, cacheKey);

**Comment by jnormen** [comment]
Here are my versions:
    <PackageReference Include="Xamarin.FFImageLoading" Version="2.3.2-pre-664" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.3.2-pre-664" />
    <PackageReference Include="Xamarin.FFImageLoading.Svg" Version="2.3.2-pre-664" />
    <PackageReference Include="Xamarin.FFImageLoading.Svg.Forms" Version="2.3.2-pre-664" />
    <PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.3.2-pre-664" />
    <PackageReference Include="Xamarin.Forms" Version="2.5.0.121934" />

**Comment by jnormen** [comment]
`var bytes = ms.ToArray();
return KeyImageSource.FromStream(() => new MemoryStream(bytes), cacheKey);` `

Cool works with key on UWP will try iOS now... have 8-10 build time till test.

**Comment by daniel-luberda** [comment]
Your code is a bad / non working version. You must always return a new stream, also in Xamarin.Forms too.

**Comment by daniel-luberda** [comment]
Actually, more optimised version is: 

```C#
public static ImageSource GenerateRoundedCornerImageSource(int width, int height, int radius,string cacheKey = null, bool isAntialias = false)
{        
        return KeyImageSource.FromStream(() => 
        {
            var bitmap = new SKBitmap(width, height, SKImageInfo.PlatformColorType, SKAlphaType.Premul);

            var canvas = new SKCanvas(bitmap);
            canvas.Clear(SKColors.Transparent);

            var paint = new SKPaint
            {
                IsAntialias = isAntialias,
                Color = SKColors.Black
            };
            
            canvas.DrawRoundRect(new SKRect(0, 0,width, height), radius, radius, paint);

            var image = SKImage.FromBitmap(bitmap);
            var data = image.Encode(SKEncodedImageFormat.Png, 100);
            
            var ms = new MemoryStream();
            data.SaveTo(ms);
            return ms;
        }, cacheKey);
    }
```

**Comment by jnormen** [comment]
You are the king 👍 it works now... Thank you so much. Sad I didn't see that part from the beginning. Was so blind though UWP worked as intended for me. 

Thanx so thankful for your help. have nice Christmass! And you gave me the best present :)

**Comment by daniel-luberda** [comment]
@jnormen Nice to hear that's working! :) Have a nice Christmas too :) Cheers!
