### ISSUE TITLE
trying to display gif loader in xamarin.android not working

### ISSUE THREAD

**Issue by aloksharma1** [luberda-molinet/FFImageLoading#871]
### Description

hello, i am working on a very basic one page app where i am using ffimageloading to show some pics from remote url and while loading images i wish to put a loader gif showing some background work going on. but when i run my app in my mobile, it shows blank until the image is full loaded.

please help 

### Steps to Reproduce
below is the code i am using 
in my mail.axml
```
<FFImageLoading.Views.ImageViewAsync
        android:layout_width="match_parent"
        android:scaleType="matrix"
        android:layout_height="match_parent"
        android:id="@+id/imgView" />
```

in MainActivity
```
ImageService.Instance.LoadUrl("myurl.jpg").WithCache(FFImageLoading.Cache.CacheType.Disk).LoadingPlaceholder("@drawable/loading", FFImageLoading.Work.ImageSource.CompiledResource).FadeAnimation(true).Into(imageViewAsync);
imageViewAsync.ScaleToFit = true;
var photoViewAttacher = new PhotoViewAttacher(imageViewAsync);
```

you can use gif from this url:
[loading.gif](https://i.pinimg.com/originals/90/80/60/9080607321ab98fa3e70dd24b2513a20.gif
)

### Basic Information

- Version with issue: 2.3.1
- Last known good version: -
- Platform: xamarin.android Oreo

**Comment by daniel-luberda** [comment]
Please try newest prerelease. (2.3.2)

**Comment by aloksharma1** [comment]
hi i tried as you said but using 
LoadingPlaceholder("loading.gif", FFImageLoading.Work.ImageSource.CompiledResource)

or 

LoadingPlaceholder("@drawable/loading", FFImageLoading.Work.ImageSource.CompiledResource)

or 

LoadingPlaceholder("https://i.pinimg.com/originals/90/80/60/9080607321ab98fa3e70dd24b2513a20.gif", FFImageLoading.Work.ImageSource.Url)

didnt worked for me even with pre release version. can you check what i am doing wrong in here??

**Comment by daniel-luberda** [comment]
- I just tested your image and it works fine
- Please make sure you have the same package version in all projects, then remove all `bin`/`obj` folders, then rebuild.

Try to first setup you view, then run image loader:

```C#
imageViewAsync.ScaleToFit = true; 
ImageService.Instance.LoadUrl("myurl.jpg").WithCache(FFImageLoading.Cache.CacheType.Disk).LoadingPlaceholder("@drawable/loading", FFImageLoading.Work.ImageSource.CompiledResource).FadeAnimation(true).Into(imageViewAsync);
```

**Comment by aloksharma1** [comment]
hello i tried what you said, but it didnt worked for me, can you provide me with a working sample or if you want i can upload the issue sample. also what do yo mean by setup your view? my main activity looks like this 

`protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            Window.RequestFeature(WindowFeatures.NoTitle);
            // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.Main);
            ImageViewAsync imageViewAsync = FindViewById<ImageViewAsync>(Resource.Id.imgView);
            try
            {
                imageViewAsync.ScaleToFit = true;
              
                    ImageService.Instance.LoadUrl("http://imgsv.imaging.nikon.com/lineup/lens/zoom/normalzoom/af-s_dx_18-140mmf_35-56g_ed_vr/img/sample/sample1_l.jpg").WithCache(FFImageLoading.Cache.CacheType.Disk).LoadingPlaceholder("@drawable/loading", FFImageLoading.Work.ImageSource.CompiledResource).FadeAnimation(true).Into(imageViewAsync);
               
                var photoViewAttacher = new PhotoViewAttacher(imageViewAsync);
                
                

            }
            catch (Exception ex)
            {
                Toast.MakeText(this, "some error occured, please check your network"+ex.StackTrace, ToastLength.Long).Show();
            }
        }`

the layout

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/mainAppLayout"
    android:minWidth="25px"
    android:minHeight="25px">
    <FFImageLoading.Views.ImageViewAsync
        android:layout_width="match_parent"
        android:scaleType="matrix"
        android:layout_height="match_parent"
        android:id="@+id/imgView" />
</LinearLayout>`

hope this helps :(

**Comment by daniel-luberda** [comment]
Please attach a sample project with your issue.

**Comment by aloksharma1** [comment]
hi please find the sample attached, this have the loading gif in resource folder and its not working on either my emulator or device
[ffImageIssue.zip](https://github.com/luberda-molinet/FFImageLoading/files/1586073/ffImageIssue.zip)

**Comment by daniel-luberda** [comment]
Your sample works fine for me (didn't change anything, just run)

![screenshot_1514313074](https://user-images.githubusercontent.com/13569983/34362391-6c21ce3e-ea73-11e7-81d8-0bea84bb1772.png)
![screenshot_1514313077](https://user-images.githubusercontent.com/13569983/34362392-6c3ed420-ea73-11e7-9afb-3bee668c0a0c.png)

**Comment by aloksharma1** [comment]
ok this does not work for me no matter what i tried, i am using visual studio 2015 and testing on android 6.0 device redmi note 3 can this be the cause??

**Comment by aloksharma1** [comment]
and as i said i always do clean build by deleting obj/bin folders and rebuilding the project

**Comment by aloksharma1** [comment]
ok with some tinkering i found out that using loadUrl as gif source is working but not `"@drawable/loading"` i think we are close to solve this issue, although its still puzzling me how its working for you but not me
