### ISSUE TITLE
CachedImage in StackLayout display with wrong height in WrapLayout(From Nuget:AiFormsLayouts)

### ISSUE THREAD

**Issue by chentotal** [luberda-molinet/FFImageLoading#877]
### Description

If I put a CachedImage in StackLayout in a WrapLayout(From Nuget:AiFormsLayouts), the images would display with wrong height.
If I put Image in StackLayout in a WrapLayout, it shows correctly.

### Basic Information

- Version with issue: 2.3.2
- Last known good version: 
- Platform: Only Test on Android

### Screenshots

Wrong
![wrong](https://user-images.githubusercontent.com/17058420/34399998-c501173a-ebc7-11e7-8885-af6659cccaf4.jpg)

Right
![right](https://user-images.githubusercontent.com/17058420/34400001-c8660200-ebc7-11e7-9c92-6124678c1c0e.jpg)

### Reproduction Link / Code

Wrong Code

    <ContentPage.Content>
        <l:WrapLayout
            x:Name="wrapLayout"
            BackgroundColor="Red"
            Spacing="4"
            UniformColumns="3">

            <StackLayout BackgroundColor="Gray" Spacing="0">
                <ffimageloading:CachedImage
                    LoadingPlaceholder="pic_bg.png"
                    RetryCount="10"
                    Source="pic_bg.png" />
                <Label Text="Name" />
            </StackLayout>

            <StackLayout BackgroundColor="Gray" Spacing="0">
                <ffimageloading:CachedImage
                    LoadingPlaceholder="pic_bg.png"
                    RetryCount="10"
                    Source="pic_bg.png" />
                <Label Text="Name" />
            </StackLayout>

            <StackLayout BackgroundColor="Gray" Spacing="0">
                <ffimageloading:CachedImage
                    LoadingPlaceholder="pic_bg.png"
                    RetryCount="10"
                    Source="pic_bg.png" />
                <Label Text="Name" />
            </StackLayout>

            <StackLayout BackgroundColor="Gray" Spacing="0">
                <ffimageloading:CachedImage
                    LoadingPlaceholder="pic_bg.png"
                    RetryCount="10"
                    Source="pic_bg.png" />
                <Label Text="Name" />
            </StackLayout>
        </l:WrapLayout>
    </ContentPage.Content>

Right Code

    <ContentPage.Content>
        <l:WrapLayout
            x:Name="wrapLayout"
            BackgroundColor="Red"
            Spacing="4"
            UniformColumns="3">

            <StackLayout BackgroundColor="Gray" Spacing="0">
                <Image Source="pic_bg.png" />
                <Label Text="Name" />
            </StackLayout>

            <StackLayout BackgroundColor="Gray" Spacing="0">
                <Image Source="pic_bg.png" />
                <Label Text="Name" />
            </StackLayout>

            <StackLayout BackgroundColor="Gray" Spacing="0">
                <Image Source="pic_bg.png" />
                <Label Text="Name" />
            </StackLayout>

            <StackLayout BackgroundColor="Gray" Spacing="0">
                <Image Source="pic_bg.png" />
                <Label Text="Name" />
            </StackLayout>
        </l:WrapLayout>
    </ContentPage.Content>

**Comment by daniel-luberda** [comment]
- Does the same things happen if you replace `CachedImage` with `Image`?
- Maybe it's related to Xamarin bug, read more here: https://github.com/luberda-molinet/FFImageLoading/issues/830 Can you confirm?

**Comment by chentotal** [comment]
Does the same things happen if you replace CachedImage with Image?
No, it's correct with Image.

It's probably related to Xamarin bug, read more here: #830 Can you confirm?
I'll try it.
Thanks.

**Comment by daniel-luberda** [comment]
It's fixed in 2.3.4
