### ISSUE TITLE
CircleTransformation - Ability to offset from center?

### ISSUE THREAD

**Issue by mzhukovs** [luberda-molinet/FFImageLoading#878]
### Description

Not so much a major issue but a nice-to-have feature request. Description:
I pull profile pics from an intranet site and they're all portrait style where the bottom 60% of the pic is somebody's suit and their face is closer to the middle of the upper half of the image, so when using the circle transformation their heads are getting scalped. Would be nice to have a way to supply an optional parameter that offsets where the circle is cropped from the middle of the pic.

### Steps to Reproduce

Just apply the circle transformation to an image like [this](https://michiganross.umich.edu/sites/default/files/images/students/eizaguirre_florian_mg_6450.jpg) (no idea who that guy is, just a random google image...). At a minimum, I expect his hair to not make it into the circle image.

### Expected Behavior

Ability to apply an offset to x or y from the middle of the pic. In my case, I would set y to be -50 so it's above the center.

### Actual Behavior

No control over something like this right now (right?) so I have to modify the images themselves individually.

### Basic Information

- Version with issue: latest
- Platform: Xamarin Forms latest, VS2017 latest

**Comment by mzhukovs** [comment]
Ok looks like adding the CropTransformation achieves my aim above, please disregard. 

     <ffimageloading:CachedImage HorizontalOptions="Center" VerticalOptions="Center"  Margin="10,0,0,0"
		WidthRequest="70" HeightRequest="70"
		DownsampleToViewSize="true"
		Source = "{Binding AvatarImg}">
        <ffimageloading:CachedImage.Transformations>
            <fftransformations:CropTransformation
                YOffset="-50"/>
            <fftransformations:CircleTransformation />
        </ffimageloading:CachedImage.Transformations>
    </ffimageloading:CachedImage>

**Comment by daniel-luberda** [comment]
> Ok looks like adding the CropTransformation achieves my aim above, please disregard.

Exactly, you can use multiple transformations together :)
