### ISSUE TITLE
2.3.2 breaking changes and problems

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#880]
First I want to say that. Please dont remove any pre release version after you publish a stable version. Because 2.3.2 pre656 works much better for me. but it is removed from nuget and i was lucky to have it on my offline cache and i could restore it.
Now the problems; 
 1) Using in listview 2.3.2 version doesnt display any loading.gif at all. maybe it loads much faster or timeout handling is changed as i can see from commits. I am using fastrenderers.

2) I tested offline-online switch case and it fails to work. 
Behavior on 2.3.2 pre 656- offline, error images are displayed and if i go online without navigating back and reload the page. images are automatically downloaded without any user interaction. 
Behavior on 2.3.2 images are still staying on errorplaceholder and If I only pop the page and push on the stack. Images "maybe" displayed. 90% displays but sometimes error placeholder remains.

3) in the listview if there are many images, 2.3.2 pre 656 downloads all without any single error placeholder. 2.3.2 doesnt download all. pre 656 displays loading placeholder, displays for a short moment but this moment is less than a second. it looks like 2.3.2 has some enhancement and it shows images too quick, i dont even see any loading palceholder image, thats why it looks like some images are getting timeout (i guess) therefore i see error placeholder.

I tested each version side by side on 2 different devices and I confirm that 2.3.2 pre 656 worked much better. 

```

                    <ffimageloading:CachedImage 	Aspect="AspectFit"    Grid.Row="0" Grid.Column="1" Grid.RowSpan="3" HeightRequest="65"
                                                    LoadingPlaceholder="loading.gif"   TransparencyEnabled = "false"   CacheDuration = "120" ErrorPlaceholder="error.png"
                                              Source="{Binding imagethumbnail, Converter={StaticResource thumbnailConvertor}, ConverterParameter=0}"/>
          
```

**Comment by aloksharma1** [comment]
loading placeholder is causing me lots of headaches too, for time being i am going to remove it from my app as its in live.

**Comment by daniel-luberda** [comment]
> First I want to say that. Please dont remove any pre release version after you publish a stable version. 

You can download all nugets from project's CI: https://ci.appveyor.com/project/daniel-luberda/ffimageloading

> Using in listview 2.3.2 version doesnt display any loading.gif at all. maybe it loads much faster or timeout handling is changed as i can see from commits. I am using fastrenderers.

It's a configurable property (provide custom configuration via `ImageService.Instance.Init(config)` method. `HttpReadTimeout` & `HttpHeadersTimeout`. Generally, you shouldn't use such a large files (which gifs are) from a remote locations. 

Can you make a repo?

**Comment by EmilAlipiev** [comment]
I had already configured both Timeouts as 5.  My images are also very small most of them are under 10kb. They just have black and transparent colors. Gif file is also super tiny. I thought this is a General Problem as i experienced on my all apps.  I will try to get you a small repro. But can you try number 2 case if you can see the difference between pre Release and latest stable

**Comment by daniel-luberda** [comment]
Please try the newest stable release. Does it work for you?

**Comment by EmilAlipiev** [comment]
yes perfect update. thank you very much. I dont see any of the problems above.
