### ISSUE TITLE
LoadingPlaceholder => How to Make it be a Lottie Animation?

### ISSUE THREAD

**Issue by mzhukovs** [luberda-molinet/FFImageLoading#882]
### Description

Would be a very nice feature if the LoadingPlaceholder could be an animation, namely a Lottie animation, as opposed to a static image - is this possible already somehow? Would appreciate the guidance if so, otherwise, would be a fantastic enhancement imo.

**Comment by daniel-luberda** [comment]
I don't think it would be possible to implement it. Lottie uses its own custom views. But there's a possibility to use it: 

# Xamarin.Forms

Create a custom view which is a `Grid` with stacked `LottieView` and `CachedImage` views. Then add a code to handle changes from `CachedImage.IsLoading` property and show/hide `LottieView`

# Native

Similarly as above, but use `Success` handler instead.

**Comment by DanielCauser** [comment]
Hey, I saw this questioin and thought it was interesting, so I made a sample app that does just this, uses lottie and ffimageloading libs. I hope it helps 😊

https://github.com/DanielCauser/XamarinFFImageLoadingAndLottie

**Comment by DanielCauser** [comment]
I also wrote a blog post about it, if you want to check it out :)

https://causerexception.com/2019/02/10/ffimageloader-lottie-%F0%9F%98%8D/

**Comment by jrahma** [comment]
It will be great if this added as a property like this:

`LoadingPlaceholder="MyLottieFileName"`
