### ISSUE TITLE
Xamarin.Forms - iOS - Image not showing when it's in Assets.xcassets and ImageSet has .png name ending

### ISSUE THREAD

**Issue by DatBluBat** [luberda-molinet/FFImageLoading#885]
### Description

I wanted to use one name for image resources in Xamarin Forms for Android and iOS, so
I've created ImageSet with name login_background.png in Assets.xcassets and placed there 3 background "Universal" images: login_background.png, login_background@2.png, login_background@3.png and in android drawable and drawable dpi versions with name login_background.png

I've set Source attribute to:
`            <ffimageloading:CachedImage
                Aspect="AspectFill"
                Source="login_background.png">
            </ffimageloading:CachedImage>`

The outcome is:
- background image is not visible on iOS
- background image is visible on Android

But when I add ".imageset" postfix to Source like this:
`            <ffimageloading:CachedImage
                Aspect="AspectFill"
                Source="login_background.png.imageset">
            </ffimageloading:CachedImage>`

then the outcome is:
- background image is visible on iOS
- background image is not visible on Android

So I have to add OnPlatform tags/code in XAML and I have no benefits naming ImageSet this way.

### Steps to Reproduce

- Create ImageSet with name ending on ".png".
- Try to use CachedImage with this exact name as Source

### Expected Behavior

Image visible on iOS.

### Actual Behavior

Image not visible on iOS.

### Basic Information

- Version with issue: 2.3.2
- Last known good version: N/A
- Platform: Xamarin.Forms - iOS

**Comment by daniel-luberda** [comment]
Hi @DatBluBat,

Did you try `login_background` (without extension)?  This is current resolver code: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Shared.IosMac/DataResolvers/BundleDataResolver.cs#L27

Any ideas how could we improve that?

**Comment by DatBluBat** [comment]
Hi @daniel-luberda Thanks for the response. I've renamed ImageSet to `login_background` - without extension and it works fine now for iOS and Android, but I think `CachedImage` should behave exactly like ordinary `Image` class in terms of functionality and my best guess is this line here is causing the issue:
https://github.com/luberda-molinet/FFImageLoading/blob/0d2f206502338774643e8ff7eb796e9273514ae8/source/FFImageLoading.Shared.IosMac/DataResolvers/BundleDataResolver.cs#L113
passing to `NSDataAsset ` constructor `filename` variable instead of `identifier`
Probably `NSDataAsset` fails to locate my login_background.png ImageSet if we strip extension - and this is happening here:
https://github.com/luberda-molinet/FFImageLoading/blob/0d2f206502338774643e8ff7eb796e9273514ae8/source/FFImageLoading.Shared.IosMac/DataResolvers/BundleDataResolver.cs#L30

**Comment by DatBluBat** [comment]
I've found also that loading from an ImageSet takes much longer time that loading from Resources on iOS (high res background images). When image is in Assets.xcassets then `CachedImage` loads even slower than just `Image`! I've tested this disabling FadeAnimation (FadeAnimationEnabled = "false") - background stays "white" much longer time than just using `Image` class or using CachedImage and loading from Resources.

**Comment by daniel-luberda** [comment]
`CachedImage` default `LoadingDelay` is set to `15ms`. Set it to `0` first to have a measurable test. But I agree, we should optimise `BundleDataResolver` code anyway.

**Comment by DatBluBat** [comment]
I've set `LoadingDelay` to `0ms` and when using background from Resources it loads perfectly fast - can't see that any loading occurs at all, but when using background from an ImageSet/Assets.xcassets then "white" backround lasts for at least 100 - a few hundred miliseconds  (it is noticeable)

**Comment by daniel-luberda** [comment]
That was not an easy fix 😨  as iOS doesn't have any methods to get image assets as `Stream` or `NSData`, but I modified some FFImageLoading's internal code to also support native image containers. Earlier, `UIImage` was exported back to PNG Stream representation, that's why it was so slow. It should work better now. Can you test newest prerelease nuget? (2.3.4-pre-679)
