### ISSUE TITLE
SIGSEGV while srolling fast in listview with CachedImages

### ISSUE THREAD

**Issue by jeremymarabel** [luberda-molinet/FFImageLoading#887]
### Description

Hi, since the version 2.3.2, the app crash with a SIGSEGV if we are scrolling fast a listview with customviewcells containing a CachedImage. 
This appends on iOS in a Xamarin forms app (didnt test on android)
Temporary fix => rolling back the package to 2.3.1

### Steps to Reproduce

Create a Xamarin Forms App with a listview using a customviewcell displaying a CachedImage
Add some items with differents images loaded from url (~50 to be able to scroll fast)
Scroll fast from top to bottom and vice versa

### Expected Behavior

Display the placeholders while downloading the images, then display the downloaded image when the download is complete and the item is on screen

### Actual Behavior

App start to lag and then crash with a SIGSEGV while scrolling fast

### Basic Information

- Version with issue: 2.3.2 and 2.3.3
- Last known good version: 2.3.1
- Platform: iOS (Xamarin Forms)

### Stacktrace
XXXXX.iOS[1840:1008510] critical:   at <unknown> <0xffffffff>
XXXXX.iOS[1840:1008510] critical:   at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative.ReadZStream (intptr,intptr,int) <0x00007>
XXXXX.iOS[1840:1008510] critical:   at System.IO.Compression.DeflateStreamNative.ReadZStream (intptr,int) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/System/System.IO.Compression/DeflateStream.cs:381
XXXXX.iOS[1840:1008510] critical:   at System.IO.Compression.DeflateStream.ReadInternal (byte[],int,int) [0x00027] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/System/System.IO.Compression/DeflateStream.cs:129
XXXXX.iOS[1840:1008510] critical:   at (wrapper runtime-invoke) object.runtime_invoke_dynamic (intptr,intptr,intptr,intptr) [0x0001e] in <bdb3aaa208384edf9f1266721cf8f9c1#6407480E-0996-34DE-EBD2-87EDC06657B6>:0
XXXXX.iOS[1840:1008510] critical:   at <unknown> <0xffffffff>
XXXXX.iOS[1840:1008510] critical:   at (wrapper managed-to-native) System.Runtime.Remoting.Messaging.AsyncResult.Invoke (System.Runtime.Remoting.Messaging.AsyncResult) <0x00007>
XXXXX.iOS[1840:1008510] critical:   at System.Runtime.Remoting.Messaging.AsyncResult.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/corlib/System.Runtime.Remoting.Messaging/AsyncResult.cs:210
XXXXX.iOS[1840:1008510] critical:   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:856
XXXXX.iOS[1840:1008510] critical:   at ObjCRuntime.Runtime.ThreadPoolDispatcher (System.Func`1<bool>) [0x00006] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/ObjCRuntime/Runtime.cs:244
XXXXX.iOS[1840:1008510] critical:   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1208
XXXXX.iOS[1840:1008510] critical:   at (wrapper runtime-invoke) object.runtime_invoke_dynamic (intptr,intptr,intptr,intptr) [0x0001e] in <bdb3aaa208384edf9f1266721cf8f9c1#6407480E-0996-34DE-EBD2-87EDC06657B6>:0
XXXXX.iOS[1840:1008510] critical: 

Native stacktrace:
XXXXX.iOS[1840:1008510] critical: 	0   Mono                                0x00000001051c8c5c mono_handle_native_crash + 224
XXXXX.iOS[1840:1008510] critical: 	1   Mono                                0x00000001051d5408 mono_sigsegv_signal_handler + 316
XXXXX.iOS[1840:1008510] critical: 	2   libsystem_platform.dylib            0x000000018239fb50 _sigtramp + 52
XXXXX.iOS[1840:1008510] critical: 	3   libz.1.dylib                        0x000000018262b758 inflate + 44
XXXXX.iOS[1840:1008510] critical: 	4   XXXXX.iOS                           0x00000001047db05c xamarin_localized_string_format_9 + 30612
XXXXX.iOS[1840:1008510] critical: 	5   XXXXX.iOS                           0x0000000101d61f60 CLSNSLogv + 17693104
XXXXX.iOS[1840:1008510] critical: 	6   XXXXX.iOS                           0x0000000101b81db8 CLSNSLogv + 15726600
XXXXX.iOS[1840:1008510] critical: 	7   XXXXX.iOS                           0x0000000101b80b94 CLSNSLogv + 15721956
XXXXX.iOS[1840:1008510] critical: 	8   XXXXX.iOS                           0x00000001012a2bd4 CLSNSLogv + 6424100
XXXXX.iOS[1840:1008510] critical: 	9   Mono                                0x00000001051d8540 mono_get_runtime_build_info + 1008
XXXXX.iOS[1840:1008510] critical: 	10  Mono                                0x00000001052558e8 mono_runtime_invoke + 368
XXXXX.iOS[1840:1008510] critical: 	11  Mono                                0x00000001052590ec mono_runtime_try_invoke_array + 1108
XXXXX.iOS[1840:1008510] critical: 	12  Mono                                0x000000010525c794 mono_message_invoke + 420
XXXXX.iOS[1840:1008510] critical: 	13  Mono                                0x000000010525c474 ves_icall_System_Runtime_Remoting_Messaging_AsyncResult_Invoke + 76
XXXXX.iOS[1840:1008510] critical: 	14  XXXXX.iOS                           0x0000000101068b84 CLSNSLogv + 4089300
XXXXX.iOS[1840:1008510] critical: 	15  XXXXX.iOS                           0x0000000101068af4 CLSNSLogv + 4089156
XXXXX.iOS[1840:1008510] critical: 	16  XXXXX.iOS                           0x0000000100fc9cfc CLSNSLogv + 3438412
XXXXX.iOS[1840:1008510] critical: 	17  XXXXX.iOS                           0x0000000102601e60 CLSNSLogv + 26736816
XXXXX.iOS[1840:1008510] critical: 	18  XXXXX.iOS                           0x0000000100fcbb18 CLSNSLogv + 3446120
XXXXX.iOS[1840:1008510] critical: 	19  XXXXX.iOS                           0x00000001012a2bd4 CLSNSLogv + 6424100
XXXXX.iOS[1840:1008510] critical: 	20  Mono                                0x00000001051d8540 mono_get_runtime_build_info + 1008
XXXXX.iOS[1840:1008510] critical: 	21  Mono                                0x00000001052558e8 mono_runtime_invoke + 368
XXXXX.iOS[1840:1008510] critical: 	22  Mono                                0x000000010527d9d8 ves_icall_System_Threading_ThreadPool_IsThreadPoolHosted + 1024
XXXXX.iOS[1840:1008510] critical: 	23  Mono                                0x000000010527b1c8 mono_threadpool_worker_set_suspended + 3652
XXXXX.iOS[1840:1008510] critical: 	24  Mono                                0x0000000105285420 mono_thread_internal_is_current + 692
XXXXX.iOS[1840:1008510] critical: 	25  libsystem_pthread.dylib             0x00000001823a42b4 <redacted> + 308
XXXXX.iOS[1840:1008510] critical: 	26  libsystem_pthread.dylib             0x00000001823a4180 <redacted> + 0
XXXXX.iOS[1840:1008510] critical: 	27  libsystem_pthread.dylib             0x00000001823a2b74 thread_start + 4
XXXXX.iOS[1840:1008510] critical: 
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

If you need more info let me know.

**Comment by daniel-luberda** [comment]
It's because of this line: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Cache/DownloadCache.cs#L145

but IMO it's a Xamarin issue, streams should be disposed correctly, but aren't. I changed some logic to avoid it anyway.
