### ISSUE TITLE
Images loading from URL not shown

### ISSUE THREAD

**Issue by qtran** [luberda-molinet/FFImageLoading#888]
### Description

Images loading from the web is not shown

### Steps to Reproduce

I used the FrogScroller example in combination with the Simple.iOS.Sample

Import the FrogScroller project from https://github.com/xamarin/ios-samples/tree/master/FrogScroller
Modify ImageScrollViewController#LoadView

### Expected Behavior

Image loaded and shown

### Actual Behavior

Image loading was successful but not shown

### Basic Information

- Version with issue: 2.3.2 and 2.3.3
- Last known good version: Don't know
- Platform: iOS

### Reproduction Link / Code

```
public override void LoadView ()
{
            UIImageView imageView = new UIImageView();

            var imageURL = Config.Images[PageIndex];
            ImageService.Instance.LoadUrl(imageURL).Success((arg1, arg2) =>
            {
                Console.WriteLine("Success");

            }).Into(imageView);

            this.View = imageView;
}
```

What I'm doing wrong? If you need more info let me know.

**Comment by daniel-luberda** [comment]
- Your code looks good. Is `Success` printed in console output?
- See our sample here: https://github.com/luberda-molinet/FFImageLoading/tree/master/samples/Simple.iOS.Sample

**Comment by qtran** [comment]
Hi Daniel,
I did see your sample, the Config class in my is copied from your sample project :)
"Success" was printed in the console but the Image is not shown. 
The image is visible though (but not always) if there is an placeholder image in the UIImageView

**Comment by daniel-luberda** [comment]
Then it must be something different, like setting your `UIImageView` content gravity, layout settings, etc. Also what is the value of ` var imageURL = Config.Images[PageIndex];`?

**Comment by qtran** [comment]
I deleted first entry (https://fake.com/imageurl.jpg) from Config.cs
so the first one is https://lh4.googleusercontent.com/-Lfgi-xEMwuk/VNWoy8EDWcI/AAAAAAAAACk/rwsluNfhSZY/w1486-h832-no/photo.jpg

I have the same problem in my app which is just paging over images loaded from the web.
The FrogScroller from xamarin is really small:
https://github.com/xamarin/ios-samples/blob/master/FrogScroller/FrogScroller/AppDelegate.cs
https://github.com/xamarin/ios-samples/blob/master/FrogScroller/FrogScroller/ImageViewController.cs

And here is my modified ImageViewController:
```
public partial class ImageViewController : UIViewController
	{
		public ImageViewController (int pageIndex)
		{
			PageIndex = pageIndex;
		}

		public int PageIndex { get; private set; }

		public static ImageViewController ImageViewControllerForPageIndex (int pageIndex)
		{
            return pageIndex >= 0 && pageIndex < Config.Images.Count ?
				new ImageViewController (pageIndex) : null;
		}

		public override void LoadView ()
		{
            
            UIImageView imageView = new UIImageView();
            imageView.Image = ImageScrollView.ImageAtIndex(0);

            var imageURL = Config.Images[PageIndex];

            ImageService.Instance.LoadUrl(imageURL).Success((arg1, arg2) =>
            {
                Console.WriteLine("Success");

            }).Into(imageView);

            this.View = imageView;
		}
}

```

**Comment by qtran** [comment]
I think we can close this now, somehow now it works but I have no idea why...
