### ISSUE TITLE
Cannot display SVG image

### ISSUE THREAD

**Issue by Hudhud** [luberda-molinet/FFImageLoading#889]
### Description

I am trying to use the SvgCachedImage to display a SVG image. However, it's not displaying for some odd reason. When I try with a PNG image it works fine. I am trying to do it in Xamarin.Forms. This is the code snippet:

` <ffimageloadingsvg:SvgCachedImage  HeightRequest="48" WidthRequest="48" Source="backbutton.svg">
                            <ffimageloadingsvg:SvgCachedImage.GestureRecognizers>
                                <TapGestureRecognizer Tapped="OnBackButtonPressed" />
                            </ffimageloadingsvg:SvgCachedImage.GestureRecognizers>
                        </ffimageloadingsvg:SvgCachedImage>`

I have installed the nuget plugin, and I do have `xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"`

I have tried with two different SVG images.

### Expected Behavior

The SVG image is displayed

### Actual Behavior

The SVG image is not displayed

### Basic Information

- Version with issue: 2.3.3

- Platform: Xamarin.Forms

### Reproduction Link / Code

`<ffimageloadingsvg:SvgCachedImage  HeightRequest="48" WidthRequest="48" Source="backbutton.svg">
                            <ffimageloadingsvg:SvgCachedImage.GestureRecognizers>
                                <TapGestureRecognizer Tapped="OnBackButtonPressed" />
                            </ffimageloadingsvg:SvgCachedImage.GestureRecognizers>
                        </ffimageloadingsvg:SvgCachedImage>`

**Comment by daniel-luberda** [comment]
- See this: https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support#xamarinforms - especially: `var ignore = typeof(SvgCachedImage);` part
- Make sure you installed packages in both platform specific / shared projects.

**Comment by EmilAlipiev** [comment]
Hi @daniel-luberda, quick question regarding SVG usage. I am thinking to replace all png icons (not listview images) with svg images. Does using svg reduces app performance significantly? I think that there should be some extra rendering for svgs, is it correct?

**Comment by daniel-luberda** [comment]
I did some measures recently and it's almost the same. SVG files are smaller in size, so reading stream from assets is a lot faster, leading to similar loading time. After image is decoded it's cached as any other image. There could be a performance issue for a really large and complex SVG files when decoding though. 

BTW: I use SVG's in all my projects, it's such a time saver.

**Comment by EmilAlipiev** [comment]
@daniel-luberda  is it supported for all android Api levels? I read here that it is not supported for some levels to use svg https://stackoverflow.com/questions/26709611/svg-vs-png-on-android

**Comment by daniel-luberda** [comment]
We use SkiaSharp for rendering, it's independent of Android version (and cross platform).

**Comment by EmilAlipiev** [comment]
@daniel-luberda  cool. I just tried and perfectly working for me using in xaml on pcl project. 

      <ffimageloadingsvg:SvgCachedImage  Source="resource://myApp.Images.Icons.rating.svg" />

i went through documentation and sample and saw your replace.png sample. you are basically replacing the text inside the svg. is it possible to change the color? I have a svg like below.  How can I replace the fill="#FFFFFF" on run time with converter in xaml? is it possible?

```
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" height="72" width="72" viewBox="0 0 72 72">
  <g>
    <path id="path1" transform="rotate(0,36,36) translate(1.49000203609467,1) scale(2.1875,2.1875)  " fill="#FFFFFF" d=""  />
  </g>
</svg>
```

**Comment by daniel-luberda** [comment]
I updated samples to also replace colors. You can also use regex as mentioned here: https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support#svg-string-replacement-including-colors
