### ISSUE TITLE
Android XML support

### ISSUE THREAD

**Issue by AndreiMisiukevich** [luberda-molinet/FFImageLoading#891]
@daniel-luberda 
validate pls PR https://github.com/luberda-molinet/FFImageLoading/pull/890

**Comment by AndreiMisiukevich** [comment]
I think, it isn't actual

**Comment by fedemkr** [comment]
I see that this issue was closed and the PR also but was the feature added? If so how is it intended to be used?
Thanks in advance

**Comment by MdNaushad** [comment]
Is this completed?

**Comment by AndreiMisiukevich** [comment]
@fedemkr @MdNaushad 

Hi guys, no, i closed this PR as I thought, that it isn't useful

xml and pdf (native vector images) are supported by Xamarin.Forms.Image from box
Just user Image for it :)

**Comment by MdNaushad** [comment]
@AndreiMisiukevich Thanks for the update :)

**Comment by xXdRaGoNrIdDeRXx** [comment]
I think this feature should still be added it looks like this PR was cancelled due to Xamarin.Forms base image control handling it but Xamarin Forms Image Control does not cache the image and i would like to utilize best of both worlds.

**Comment by daniel-luberda** [comment]
@xXdRaGoNrIdDeRXx Hi, feel free to update PR to the latest codebase with suggestions and I'll merge it. https://github.com/luberda-molinet/FFImageLoading/pull/890
