### ISSUE TITLE
Xamarim Forms Android App crashing immediately when FFImageLoading library is added to the project

### ISSUE THREAD

**Issue by chumeanbro** [luberda-molinet/FFImageLoading#892]
### Description

When adding FFimageLoading to my project, the app immediately crashes with the message "App has stopped working". The NuGet Package has just been added to the project. No instance or whatsoever has been made. The OnCreate is not even called anymore.

### Steps to Reproduce

Installed FFimageLoading via NuGet Package Manager

### Expected Behavior

No crash

### Actual Behavior

Crash

### Basic Information

- Visual Studio 2017
- Android_Accelerated_Nougat (Android 7.1 - API 25)
- Xamarin Forms 2.5.0.121934

### Debug Output

`Android application is debugging.
01-08 20:21:29.656 I/art     (10087): Not late-enabling -Xcheck:jni (already on)
01-08 20:21:29.657 W/art     (10087): Unexpected CPU variant for X86 using defaults: x86_64
01-08 20:21:29.709 D/AndroidRuntime(10087): Shutting down VM
01-08 20:21:29.710 E/AndroidRuntime(10087): FATAL EXCEPTION: main
01-08 20:21:29.710 E/AndroidRuntime(10087): Process: com.companyname.Mobile, PID: 10087
01-08 20:21:29.710 E/AndroidRuntime(10087): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.companyname.Mobile-1/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.Mobile-1/lib/x86_64, /system/fake-libs64, /data/app/com.companyname.Mobile-1/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libmonodroid.so"
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at java.lang.System.loadLibrary(System.java:1530)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:34)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:42)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5853)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at android.os.Looper.loop(Looper.java:154)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at java.lang.reflect.Method.invoke(Native Method)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-08 20:21:29.710 E/AndroidRuntime(10087): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by EmilAlipiev** [comment]
did you this line in your mainactivity

  FFImageLoading.Forms.Droid.CachedImageRenderer.Init(enableFastRenderer:true);

**Comment by chumeanbro** [comment]
Yes, but the thing is that it doesn't even break in MainActivity's OnCreate anymore if i put a breakpoint in there

**Comment by EmilAlipiev** [comment]
your problem should be something else related. probably your project is corrupted. try a clean one to see if it occurs for you

**Comment by daniel-luberda** [comment]
@chumeanbro Just as @EmilAlipiev said, it must be something with your targets settings. It's hard to guess without a repo project. This is the key part: `Unexpected CPU variant for X86 using defaults: x86_64`

**Comment by oguzhanorhaan** [comment]
I have the same problem with this. Only added the library and inits, android app crashes. iOS works with no problem.

**Comment by daniel-luberda** [comment]
@chumeanbro @oguzhanorhaan  Could you make a repo?

**Comment by chumeanbro** [comment]
Fixed this by installing "Google APIs Intel x86 System Image" through the SDK Manager and creating a new emulator with that CPU
