### ISSUE TITLE
Svg images with SkiaSharp increasing app size significantly

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#893]
Svg plugin awsome and works great but I recognize that this SkiaSharp plugin is 4mb big. it is a significant size for a single package. Cant we find a better alternative or it is the best we can get? I am seeing this 4mb
using Full Linking, Bundle into Native Assemblies and without AOT in release mode when I extract the package as shown in the image

![image](https://user-images.githubusercontent.com/10422347/34701173-fa4734d8-f4e6-11e7-8f18-efea4ee43ad4.png)

**Comment by daniel-luberda** [comment]
It's best what we can get. See this: 

- https://github.com/mono/SkiaSharp/issues/259
- https://bugzilla.xamarin.com/show_bug.cgi?id=53250
- https://github.com/mono/SkiaSharp/issues/174

**Please mind that you will compensate those 4MB when you add some images. Image files are  many times larger than SVG files and you also don't need to include multiple image sizes when using SVGs.**

**Comment by EmilAlipiev** [comment]
I agree with you about compensation but in my gain from images are 1 mb  max.  I think that it is perfect solution for the apps heavily using high resolution images. I asked this question because i went through some other libraries doing without skiasharp although these libraries looks like not updated and almost dead. anyway i am closing this ticket. just wanted to bring into your attention. thank you

**Comment by EmilAlipiev** [comment]
Oh my good, this became crazy now. i am using 1.60.1 version of skiasharp and it occupies 9mb size. in April last time i checked it was like shown above around 3.8mb what happened with the newer versions? what did they do? it is impossible to use your library because of skiasharp. how can we report it best? 

![image](https://user-images.githubusercontent.com/10422347/42138805-960983ce-7d83-11e8-839c-f83752aeea18.png)

**Comment by KristofferBerge** [comment]
I use Xamarin.FFImageLoading.Svg.Forms to render SVGs, but the size of the library is way too big. Is it possible to configure linking to exclude parts of the SkiaSharp library for the SVG nuget?
