### ISSUE TITLE
CachedImages are not loaded at all for existing Uri

### ISSUE THREAD

**Issue by OndrejValenta** [luberda-molinet/FFImageLoading#894]
### Description

I'm deeply confused. No matter what kind of Xamarin Forms project I create the images are not loaded at all. Even more the OnError, OnDownloadStarted event handlers are also not called at all. It also makes not difference what kind of Uri I put in the CachedImage https/http nor if I do it from Xaml or code behind via ImageSource.FromUri.

It's not a networking or 404 issue because the same path works for the standard Xamarin Image control I put just above the CachedImage.

Btw. the same issue goes for SVG images. It simple does not do anything, not even for embedded or local images. No errors, no nothing.

### Steps to Reproduce

Simply use in any kind of Xamarin Forms project in latest updated VS Enterprise, in both Code Sharing strategies (.NET Standard, SharedProject). 

Colleague of mine had the same experience on a different machine with the same setup. He was fighting with SVGs not loading for hours, he was able to load it once from internet but could not to reproduce it later. 

We tried to change HTTP client to Android but it had no effect.

### Expected Behavior

Images loaded or at least some kind of an error except "Could not load type "

### Actual Behavior

Nothing

### Basic Information

- Version with issue: latest
- Last known good version: 
- Platform: Xamarin Forms (latest), Shared/NET Standard, Android Emulator

### Screenshots

As you can see the Google logo is there only once

![screenshot_1515558043](https://user-images.githubusercontent.com/6738956/34755701-15bec250-f5c6-11e7-926f-c341a54b894f.png)

### Reproduction Link / Code

From Xaml:
<Image Source="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Google-favicon-2015.png/150px-Google-favicon-2015.png"></Image>
<forms:CachedImage x:Name="CachedImage" 
		  Source="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Google-favicon-2015.png/150px-Google-favicon-2015.png"
		  DownsampleWidth="300" 
		  DownloadStarted="CachedImage_OnDownloadStarted" 
		  Error="CachedImage_OnError"></forms:CachedImage>

From code behind: 
CachedImage.Source = ImageSource.FromUri(new Uri("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Google-favicon-2015.png/150px-Google-favicon-2015.png"));

**Comment by OndrejValenta** [comment]
Just to be sure I tried another emulator image (Android 7.1 previous was 6.0) and the issues is the same.
![screenshot_1515559009](https://user-images.githubusercontent.com/6738956/34756051-54a41306-f5c8-11e7-88b2-3c0d6ba34ad4.png)

You can find the simplest app possible here
[App2.zip](https://github.com/luberda-molinet/FFImageLoading/files/1617536/App2.zip)

Please HELP! I'm utterly perplexed. ;-)

**Comment by AndreiMisiukevich** [comment]
@OndrejValenta Hi)
Did you install all necessary packages into all projects and call CachedImageRenderer.Init() ?

- Xamarin.FFImageLoading.Forms >> for Android and PCL
Xamarin.FFImageLoading  >> For android

CachedImageRenderer.Init(true); // In your MainActivity AFTER Forms.Init(this, bundle);

**Comment by OndrejValenta** [comment]
Ok, you were right.. For all the others you should follow this wiki page [Xamarin.Forms API](https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API)

My bad. I was expecting this to be the primary use case so I was expecting this to be in first chapters of the wiki pages.
