### ISSUE TITLE
SVG Text to large

### ISSUE THREAD

**Issue by BlackRamsis** [luberda-molinet/FFImageLoading#895]
### Description
Hy,
I tried to use FFImageLoading to load SVGs into my project, but the text is rendered differently.
On web browser or webview the text is smaller, with FFImageLaoding the text is larger.

### Steps to Reproduce
i added a part of my SVG as code

### Expected Behavior
there should be space between the black text and the white text

### Actual Behavior
there is no space between the texts

### Basic Information
- Version with issue: 2.3.4
- Last known good version: -
- Platform: Android

### Reproduction Link / Code

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="11.69444in" height="8.263889in" class="slides-canvas" viewBox="0 0 842 595">
  <g text-rendering="geometricPrecision" transform="scale(1, 1)">
    <rect x="0" y="0" width="842" height="595" fill="#FFFFFF" />
    <path stroke-width="0.5" stroke="#333333" fill="none" d="M48.2 578.3L793.4 578.3" />
    <path fill="#999999" d="M48.2 39.8L793.8 39.8 793.8 111.8 48.2 111.8z" />
    <path stroke-width="0.5" stroke="#333333" fill="none" d="M48.2 34L793.4 34" />
    <g transform="matrix(1, 0, 0, 1, 59.03984, 46.8)">
      <text font-family="Arial" font-weight="bold" font-size="9pt" fill="#333333">
        <tspan x="0" y="12.10027">In this document</tspan>
      </text>
    </g>
    <g transform="matrix(1, 0, 0, 1, 59.039856, 62.66142)">
      <text font-family="Arial" font-size="10.5pt" fill="#FFFFFF">
        <tspan x="0" y="13.61329">Table of contents</tspan>
      </text>
    </g>
</g>
</svg>
```

**Comment by daniel-luberda** [comment]
FFImageLoading currently doesn't support `tspan` inside `text` element. You can modify it like: 

```XML
      <text x="0" y="12.10027" font-family="Arial" font-weight="bold" font-size="9pt" fill="#333333">
        In this document
      </text>
```

Feel free to implement it, PR welcome. Code responsible for `text` is here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SkSvg.cs#L582-L595

**Comment by daniel-luberda** [comment]
shpuld be fixed in newest prerelease
