### ISSUE TITLE
2.3.4 Android Slow Performance ??

### ISSUE THREAD

**Issue by wenyonk** [luberda-molinet/FFImageLoading#897]
### Description

I have recently upgraded from FFIL 2.2.25 to 2.3.4 and have noticed a 50% decrease in Android performance.  

I have tried various combinations of FFIL Android settings and configurations.  With different results, the most optimal Android configuration is below:

     MainActivity.cs
                base.OnCreate(savedInstanceState);

                //global::Xamarin.Forms.Forms.SetFlags("FastRenderers_Experimental");
                global::FFImageLoading.Forms.Droid.CachedImageRenderer.Init(enableFastRenderer: false);

                var config = new FFImageLoading.Config.Configuration()
                    {
                        DiskCacheDuration = TimeSpan.FromDays(60),
                        VerboseLogging = false,
                        VerbosePerformanceLogging = false,
                        VerboseMemoryCacheLogging = false,
                        VerboseLoadingCancelledLogging = false
                    };
                global::FFImageLoading.ImageService.Instance.Initialize(config);

                global::Xamarin.Forms.Forms.Init(this, savedInstanceState);

     App.cs (Constructor)
                    InitializeComponent();

                    CachedImage.FixedOnMeasureBehavior = true;
                    CachedImage.FixedAndroidMotionEventHandler = true;

I am not specifying an image width or height, I am binding in the OnBindingContextChanged() method

ViewCell XAML Code looks like this
<ffImageLoadingForms:CachedImage x:Name="BackgroundImage" AutomationId="BackgroundImage" 
                Grid.Row="0" Grid.RowSpan="11" Grid.Column="0" Grid.ColumnSpan="8"
		Aspect="AspectFill" 
                BackgroundColor="White"/>

ViewCell CodeBehind looks like this 
            BackgroundImage.ErrorPlaceholder = feedItemModel.ErrorOrMissingBackgroundImageUrl;
            BackgroundImage.LoadingPlaceholder = feedItemModel.ErrorOrMissingBackgroundImageUrl;
            BackgroundImage.Source = feedItemModel.BackgroundImageUrl;

            base.OnBindingContextChanged();

### Steps to Reproduce

Upgraded Platforms (Android and iOS) and PCL from 2.2.25. to. 2.3.4
Recompiled, deployed and started application.    App loading time doubled

### Expected Behavior

Expected faster loading time than 2.2.25.  
v2.2.25 Loading time on Android ~12 seconds

iOS is faster v2.2.25 Loading time ~15 seconds

### Actual Behavior

2.3.4 50%+ slower then 2.2.25.
v2.3.4 Loading time on Android ~28 seconds for same data set

iOS is faster v2.3.4 Loading time ~12 seconds
In AppDelegate.cs
                global::Xamarin.Forms.Forms.SetFlags("FastRenderers_Experimental");
                global::FFImageLoading.Forms.Touch.CachedImageRenderer.Init();

                var config = new FFImageLoading.Config.Configuration()
                    {
                        DiskCacheDuration = TimeSpan.FromDays(60),
                        VerboseLogging = false,
                        VerbosePerformanceLogging = false,
                        VerboseMemoryCacheLogging = false,
                        VerboseLoadingCancelledLogging = false
                    };
                global::FFImageLoading.ImageService.Instance.Initialize(config);

                global::Xamarin.Forms.Forms.Init();

### Basic Information

- Version with issue: 2.3.4
- Last known good version: 2.2.25
- Platform: Xamarin Forms v2.4.0.91020

- Profile 78 for PCL's
- Latest version of XS for Mac
- Android SDK v2.6.1.0.1

### Screenshots

See attached Android images with and without FastRenderers on (true) and off (false)
FastRenderers ON:
![ffil_w_fastrenderers_on](https://user-images.githubusercontent.com/3248973/34795219-67fe4b9a-f61f-11e7-854a-03f24d480638.png)

FastRenderers OFF
![ffil_w_fastrenderers_off](https://user-images.githubusercontent.com/3248973/34795230-749a9804-f61f-11e7-80f8-5b1e92b26863.png)

**Comment by wenyonk** [comment]
Daniel,

Thank you for your response...

Loading time in this context is the time the app starts until the home page is displayed (See screenshots above, that is the home page).  When I say the loading time is 50% slower, I mean the time the app starts went from ~12 seconds (v2.2.25). to ~28 seconds (v2.3.4) on Android.

As far as Fast Renders if you look at the two screenshots above and you look at the images with FastRenderers OFF, you will notice that the images are uniform and stay within the white borders.  If you look at the images with FastRenderers ON you will see the images are scaled differently and do not respect the boarders.  Also please note the settings/code for each ON/OFF in the DESCRIPTION and ACTUAL BEHAVIOR

**Comment by daniel-luberda** [comment]
It was a bug related to this: https://github.com/luberda-molinet/FFImageLoading/commit/04486596c3c5ae01228bef5f144ee6c081dcf41f

Please reopen if you still experience it. Cheers.
