### ISSUE TITLE
Can't binding string color to TintTransformation.HexColor

### ISSUE THREAD

**Issue by Raystorm7** [luberda-molinet/FFImageLoading#898]
### Description

Hi, I can't bind a Hex Color in string format to the HexColor property of TintTransformation.

This is the error:
**No property, bindable property, or event found for 'HexColor', or mismatching type between value and property**.

This is my XAML code:
```
<ffimageloading:CachedImage HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand" Aspect="AspectFill"
  Grid.Row="0" Grid.Column="1"
  Source="{Binding ImageClose}">
    <ffimageloading:CachedImage.Transformations>
       <fftransformations:RotateTransformation Degrees="45" />
       <fftransformations:TintTransformation HexColor="{Binding ImageColor}" EnableSolidColor="True" />
  </ffimageloading:CachedImage.Transformations>
</ffimageloading:CachedImage>
```

And this is the C# code (in ViewModel):

```
public string ImageColor { get; set; }
[...]
 var DefaultLabelColor = Application.Current.Resources["DefaultLabelColor"] as OnPlatform<Color>;
            List<On> ListaP = DefaultLabelColor.Platforms as List<On>;

On Platform = ListaP.Find(ele => ele.Platform[0] == Device.RuntimePlatform);
ImageColor = (string)Platform.Value;
RaisePropertyChanged(() => ImageColor);
```
If i set the HexColor manually like # 2266FF all works.

I have this NuGet package installed:
Xamarin.FFImageLoading
Xamarin.FFImageLoading.Forms
Xamarin.FFImageLoading.Transformations

### Basic Information

- Version with issue: 2.3.4

EDIT: After update to version 2.3.4, neither the <fftransformations:RotateTransformation Degrees="45" /> works.

**Comment by daniel-luberda** [comment]
Those properties are not bindable. See this: https://github.com/luberda-molinet/FFImageLoading/issues/860

**Comment by gsgou** [comment]
@daniel-luberda It would be nice addition to have HexColor as BindableProperty.
With the help of ColorToHexConverter we could keep the styling logic to XAML.

**Comment by lachtan163** [comment]
you can use attachedbehavior, works also if you change ColorString later (classic binding)

XAML:
                    <ffimageloadingsvg:SvgCachedImage WidthRequest="100" HeightRequest="100" Source="{Binding Source}"
                                                      behaviors:StatusTypeToColorBehavior.HexColor="{Binding ColorString}">
                        <ffimageloadingsvg:SvgCachedImage.Transformations>
                            <ffimageloadingtrans:TintTransformation HexColor="#FF000000" EnableSolidColor="true"/>
                        </ffimageloadingsvg:SvgCachedImage.Transformations>
                        <ffimageloadingsvg:SvgCachedImage.Behaviors>
                            
                        </ffimageloadingsvg:SvgCachedImage.Behaviors>
                    </ffimageloadingsvg:SvgCachedImage>

Behavior class:
    using FFImageLoading.Svg.Forms;
    using FFImageLoading.Transformations;
    using Xamarin.Forms;

    public static class StatusTypeToColorBehavior
    {
        public static readonly BindableProperty HexColorProperty =
            BindableProperty.CreateAttached(
                "HexColor",
                typeof(string),
                typeof(StatusTypeToColorBehavior),
                "",
                propertyChanged: OnHexColorChanged);

        public static string GetHexColor(BindableObject view)
        {
            return (string)view.GetValue(HexColorProperty);
        }

        public static void SetHexColor(BindableObject view, bool value)
        {
            view.SetValue(HexColorProperty, value);
        }

        static void OnHexColorChanged(BindableObject view, object oldValue, object newValue)
        {
            var entry = view as SvgCachedImage;
            if (entry == null)
            {
                return;
            }

            ((TintTransformation)entry.Transformations[0]).HexColor = (string)newValue;
        }
    }

**Comment by tamnguyen98** [comment]
> you can use attachedbehavior, works also if you change ColorString later (classic binding)
> 
> XAML: <ffimageloadingsvg:SvgCachedImage WidthRequest="100" HeightRequest="100" Source="{Binding Source}" behaviors:StatusTypeToColorBehavior.HexColor="{Binding ColorString}"> ffimageloadingsvg:SvgCachedImage.Transformations <ffimageloadingtrans:TintTransformation HexColor="#FF000000" EnableSolidColor="true"/> </ffimageloadingsvg:SvgCachedImage.Transformations> ffimageloadingsvg:SvgCachedImage.Behaviors
> 
> ```
>                     </ffimageloadingsvg:SvgCachedImage.Behaviors>
>                 </ffimageloadingsvg:SvgCachedImage>
> ```
> 
> Behavior class: using FFImageLoading.Svg.Forms; using FFImageLoading.Transformations; using Xamarin.Forms;
> 
> ```
> public static class StatusTypeToColorBehavior
> {
>     public static readonly BindableProperty HexColorProperty =
>         BindableProperty.CreateAttached(
>             "HexColor",
>             typeof(string),
>             typeof(StatusTypeToColorBehavior),
>             "",
>             propertyChanged: OnHexColorChanged);
> 
>     public static string GetHexColor(BindableObject view)
>     {
>         return (string)view.GetValue(HexColorProperty);
>     }
> 
>     public static void SetHexColor(BindableObject view, bool value)
>     {
>         view.SetValue(HexColorProperty, value);
>     }
> 
>     static void OnHexColorChanged(BindableObject view, object oldValue, object newValue)
>     {
>         var entry = view as SvgCachedImage;
>         if (entry == null)
>         {
>             return;
>         }
> 
>         ((TintTransformation)entry.Transformations[0]).HexColor = (string)newValue;
>     }
> }
> ```

Hi, can you fix your pasted xaml code? I've tried to recreate your example, but can't seem to get mine working.

My xaml looks like this 

```
xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
xmlns:fftransf="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
xmlns:viewmodels="clr-namespace:XamarinAttributeProgrammer.ViewModels" 
xmlns:ffimgform="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
```
----------------------
```
<ffimageloadingsvg:SvgCachedImage 
      x:Name="NeedleSVG"
      WidthRequest="200" 
      HeightRequest="200" 
      CacheType="None"
      Source="resource://XamarinAttributeProgrammer.Resources.Images.Needle.svg"
      viewmodels:StatusTypeToColorBehavior.HexColor="{Binding NeedleColorInHex}">
      <ffimgform:CachedImage.Transformations>
          <fftransf:TintTransformation HexColor="#ff0000" EnableSolidColor="true"/>
      </ffimgform:CachedImage.Transformations>
  </ffimageloadingsvg:SvgCachedImage>
```

**Comment by tamnguyen98** [comment]
Found a solution that sometimes work:
Import xamarin community tool kit:
```xmlns:xct="http://xamarin.com/schemas/2020/toolkit"```
and then add the tintcolor to your svg like so
```
<ffimageloadingsvg:SvgCachedImage 
                        x:Name="NeedleSVG"
                        WidthRequest="200" 
                        HeightRequest="200" 
                        CacheType="None"
                        Source="resource://XamarinAttributeProgrammer.Resources.Images.Needle.svg"
                        xct:IconTintColorEffect.TintColor="{Binding NeedleColorInHex}"/> <!-- KEY PART RIGHT HERE-->
```

For my project, I have to update a property in order for it to render in real time, but idk why that certain (bool) value would have any affects to this....
