### ISSUE TITLE
SVG <style> is ignored when placed within <defs>

### ISSUE THREAD

**Issue by JoshaMunnik** [luberda-molinet/FFImageLoading#899]
### Description

When exporting a SVG file in AI using Internal CSS settings, the `<style>` is placed within `<defs>.` The css definitions are ignored when the SVG is rendered.

### Steps to Reproduce

Export a SVG file using Internal CSS settings in AI (using a few different colors).

### Expected Behavior

SVG getting rendered with the colors

### Actual Behavior

SVG getting rendered in black

### Work around

Exporting SVG using inline styles or manually removing the `<defs>` tag solves the problem.

**Comment by daniel-luberda** [comment]
It's not implemented yet. PR welcome - Parser code: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SkSvg.cs

**Comment by daniel-luberda** [comment]
Thanks to @xtergs it's implemented now. See https://github.com/luberda-molinet/FFImageLoading/pull/952

Cheers :)
