### ISSUE TITLE
Xamarin.Forms : EmbeddedResourceImageSource in XAML 

### ISSUE THREAD

**Issue by orcundeniz** [luberda-molinet/FFImageLoading#902]
I am little confused about EmbeddedResourceImageSource.
Is Source="resource://ProjectName.Resources.image.png" property of CachedImage in XAML equals to myImage.Source = new EmbeddedResourceImageSource("ProjectName.Resources.image.png") in code behind? Or They have some differences in some ways?

**Comment by daniel-luberda** [comment]
Yes, it's exactly the same. You can also specify a different assembly for both of them too: https://github.com/luberda-molinet/FFImageLoading/wiki/Data-URL-&-Embedded-Resources-support-(including-base64)
