### ISSUE TITLE
Android pics are looking blurred

### ISSUE THREAD

**Issue by asafgo** [luberda-molinet/FFImageLoading#904]
### Description

Android pics are looking blurred where in iOS looks ok when using version 2.3.4.
With version 2.3.1 no problem with Android.

### Steps to Reproduce

 
                    <forms:CachedImage Grid.Row="0" Grid.Column="0"
                                       CacheType="All"
                                       RetryDelay="1000"
                                       DownsampleHeight="150"
                                       RetryCount="5"
                                       CacheDuration="30"
                                       BackgroundColor="Transparent"
                                       BitmapOptimizations="True"
                                       SuccessCommand="{Binding UserPhoto1SuccessCommand}"
                                       Source = "{Binding UserPhoto1}">
                        <forms:CachedImage.Transformations>
                            <transformations:CornersTransformation
                                BottomLeftCornerSize="5"
                                BottomRightCornerSize="5"
                                TopLeftCornerSize="5"
                                TopRightCornerSize="5"
                                CornersTransformType="AllRounded" />
                        </forms:CachedImage.Transformations>
                    </forms:CachedImage>

### Expected Behavior

Pics on Android should not be blurred.

### Actual Behavior

iOS works fine but not on Android

### Basic Information

- Version with issue: 2.3.4
- Last known good version: 2.3.1
- Platform: Xamarin Froms
![android](https://user-images.githubusercontent.com/12719112/34957361-fc9aa00e-fa35-11e7-8518-667ba615d787.png)
![ios](https://user-images.githubusercontent.com/12719112/34957360-fc77282c-fa35-11e7-8af9-7bdae8c63ecf.png)

**Comment by daniel-luberda** [comment]
Couldn't reproduce it. Could you attach a repo project?

**Comment by asafgo** [comment]
[ffimage_test1.zip](https://github.com/luberda-molinet/FFImageLoading/files/1649226/ffimage_test1.zip)

**Comment by asafgo** [comment]
I have attached a repo...

**Comment by asafgo** [comment]
Any option to solve this problem please?

**Comment by EmilAlipiev** [comment]
off the topic, i was having similar problems on android and uwp for different reasons and i fed up finally. converted all my images into svg and using svg is life changer. it takes time and effort but worth it.

**Comment by asafgo** [comment]
SVG is not an option for me so I wish PNG will work great like in version 2.3.1

**Comment by asafgo** [comment]
removing DownsampleHeight="150" solved the problem.
