### ISSUE TITLE
Not all images appearing

### ISSUE THREAD

**Issue by DiogoCosta1998** [luberda-molinet/FFImageLoading#905]
### Description

Using XAML code to display crests of football teams via urls, some work others don't.

E.g. https://upload.wikimedia.org/wikipedia/commons/f/fc/Emblema_CD_Tondela.png (Works)
      https://upload.wikimedia.org/wikipedia/de/b/bd/Vit%C3%B3ria_Set%C3%BAbal.svg (Doesn't work) 

### XAML code

`                                <ffimageloadingsvg:SvgCachedImage Source="{Binding crestURI}"
                                                                  HeightRequest="128" WidthRequest="128"
                                                                  DownsampleToViewSize="True"
                                                                  InputTransparent="True"/>`

### Basic Information

- Platform: UWP

### Screenshots

![capture](https://user-images.githubusercontent.com/31896387/35002466-aa36207a-fae1-11e7-8438-ef8154cbeeaa.PNG)

**Comment by daniel-luberda** [comment]
Do you have `Xamarin.FFImageLoading.Svg`, `Xamarin.FFImageLoading.Forms.Svg`, `SkiaSharp` packages installed in your Windows, platform specific project?

**Comment by DiogoCosta1998** [comment]
Fixed it, need to install SkiaSharp (never knew that). Thanks.
