### ISSUE TITLE
Gifs on iOS

### ISSUE THREAD

**Issue by ratamahatta88** [luberda-molinet/FFImageLoading#907]
### Description

On iOS I could not see any gif from my backend. Added sources and looked at your sources and found why loading crashed.

### Steps to Reproduce

Load GIF with different delays between frames.

### Expected Behavior

GIF is shown

### Actual Behavior

Exception is thrown

> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00018] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/throwhelper.cs:93 
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/throwhelper.cs:56 
>   at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:181 
>   at FFImageLoad
> ing.Decoders.GifDecoder.SourceRegfToDecodedImage (Foundation.NSData nsdata, CoreGraphics.CGSize destSize, System.nfloat destScale, FFImageLoading.Config.Configuration config, FFImageLoading.Work.TaskParameter parameters, FFImageLoading.Decoders.GifDecoder+RCTResizeMode resizeMode, FFImageLoading.Work.ImageInformation imageinformation, System.Boolean allowUpscale) [0x0027f] in C:\FFImageLoading-master\source\FFImageLoading.Shared.IosMac\Decoders\GifDecoder.cs:129 
>   at FFImageLoading.Decoders.GifDecoder.DecodeAsync (System.IO.Stream stream, System.String path, FFImageLoading.Work.ImageSource source, FFImageLoading.Work.ImageInformation imageInformation, FFImageLoading.Work.TaskParameter parameters) [0x00075] in C:\FFImageLoading-master\source\FFImageLoading.Shared.IosMac\Decoders\GifDecoder.cs:43 
>   at FFImageLoading.Work.ImageLoaderTask`3+<GenerateImageAsync>d__104[TDecoderContainer,TImageContainer,TImageView].MoveNext () [0x00066] in C:\FFImageLoading-master\source\FFImageLoading.Common\Work\ImageLoaderTask.
> cs:281 
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frame
> works/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
>   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
> 

### Basic Information
in GifDecoder.cs:
```
#if __IOS__
                        var frames = GetFrames(sourceRef, options);
                        var delays = GetDelays(sourceRef);
                        var totalDuration = delays.Sum();
                        var adjustedFrames = AdjustFramesToSpoofDurations(frames, destScale, delays, totalDuration);

                        images = new AnimatedImage<PImage>[adjustedFrames.Length];

                        for (int i = 0; i < images.Length; i++)
                        {
                            images[i] = new AnimatedImage<PImage>() { Image = adjustedFrames[i], Delay = delays[i] };
                        }
```

after AdjustFramesToSpoofDurations() we may have different sizes of arrays `adjustedFrames` and `delays`. That is the cause of crash. Also after that method we have to use one new delay based on CGD.
`images[i] = new AnimatedImage<PImage>() { Image = adjustedFrames[i], Delay = totalDuration / adjustedFrames.Length };`
Or something like that.

**Comment by AndrewBriareZya** [comment]
Can confirm that this same issue is happening for me as well.

**Comment by daniel-luberda** [comment]
Could you attach a sample file which for this case so I could fix this?

**Comment by ratamahatta88** [comment]
Do you mean a gif? Here are some for example
https://fittersbuddy.com/media/1352/0107_leak-detection_system.gif
https://fittersbuddy.com/media/1354/0109_observe_temp_difference.gif
https://fittersbuddy.com/media/1596/0328_low_press_range_change_setting.gif
https://fittersbuddy.com/media/1597/0329_low_press_change_diff_setting.gif
 Above that AdjustFramesToSpoofDurations() method can run into OOM since it creates a lot of extraneous files. I experince some similar case on android with those images. Two of images above is enough to crash empty application. May be you have an idea about that as well?

**Comment by daniel-luberda** [comment]
Fixed
