### ISSUE TITLE
EXIF in examples

### ISSUE THREAD

**Issue by szotp** [luberda-molinet/FFImageLoading#908]
Could EXIF example be added to the sample Forms project? I'm not sure if EXIF support doesn't work or I'm doing something wrong. 

Image that could be used:
https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_3.jpg

**Comment by daniel-luberda** [comment]
It's probably a bug in Android's `ExifInterface support` library, somehow this code: 

```C#
            var exifInt = new ExifInterface(stream);

            int exifRotation = exifInt.GetAttributeInt(ExifInterface.TagOrientation, ExifInterface.OrientationNormal);
```

returns `0` for your image file. I think it may be related to this: https://stackoverflow.com/a/39567169/5064986

**Comment by daniel-luberda** [comment]
Fixed
