### ISSUE TITLE
Out of memory when a user go from Android.App.Fragment to another Android.App.Fragment

### ISSUE THREAD

**Issue by lfongaroScp** [luberda-molinet/FFImageLoading#909]
### Description
I guess there is a memory problem with Fragment/recyclerview. I create a sample app where the layout of a Fragment is a RecyclerView. If the user tap on a single image the app start a new Fragment (same class fragment) with a RecyclerView. I attach the sample.

### Steps to Reproduce

Just scroll the list in the sample app and tap on a Image and watch the heap size through Android Device Monitor

### Expected Behavior

The heap size do not increase indefinitely

### Actual Behavior

The heap size do increase indefinitely until a OOM.

### Basic Information

- Version with issue: 2.3.4
- Last known good version: none
- Platform: Xamarin.Android

### Reproduction Link / Code

[TestImmagini.zip](https://github.com/luberda-molinet/FFImageLoading/files/1647227/TestImmagini.zip)

**Comment by IvanVelickovski** [comment]
Have you found a way to fix this? I have this problem in my app after I switched to using nested fragments.

**Comment by daniel-luberda** [comment]
- I can't reproduce it on 2.3.6. Everything is cleared properly. 
- Do you take into account that some of the memory is reserved for caching images? You can control its size with a custom configuration.
