### ISSUE TITLE
Lots of instances of MiniLoggerWrapper

### ISSUE THREAD

**Issue by marius-bughiu** [luberda-molinet/FFImageLoading#911]
### Description

Hi there, I was investigating some memory-related performance issues in one of my apps when I noticed some weird behavior from FFImageLoading. Apparently, lots of instances of the MiniLoggerWrapper get created and from what I can figure they don't get disposed.

I'm assuming it's not something in my code, since my data templates containing the CachedImage do get disposed, and I'm left with only 12 after switching through lots of pages. (I'm loading up to 150 per page, due to virtualization only 5 to 12 are actually created per page).

### Steps to Reproduce

In my scenario, I've got multiple pages containing SfListView with a data template called CompactArticleView in which I've got 1 CachedImage.

- navigate through multiple pages
- then return to the root page (PopToRoot)

All controls are disposed properly, and I am left with 12 CompactArticleViews, yet, I've got 1166 instances of MiniLoggerWrapper hanging there. Also, there's a similar amount of BindablePropertyContexts there as well.

### Expected Behavior

Is there any way to disable logging entirely?

### Basic Information

- Version with issue: 2.3.4
- Last known good version: don't know
- Platform: UWP (haven't tested others)

### Screenshots

![image](https://user-images.githubusercontent.com/11870708/35197932-f6471390-feef-11e7-84c6-fd1f1227f665.png)

**Comment by molinch** [comment]
Regarding MiniLogger I think the issues comes from https://github.com/luberda-molinet/FFImageLoading/blob/f745eac15aa9372defe668f8a54d690a97619713/source/FFImageLoading.Common/ImageServiceBase.cs#L36

There we always pass the configuration to `InitializeIfNeeded` which means it will always try to initialize, regardless of _initialized flag.

Then in that method, we do: https://github.com/luberda-molinet/FFImageLoading/blob/f745eac15aa9372defe668f8a54d690a97619713/source/FFImageLoading.Common/ImageServiceBase.cs#L138

So of course this will keep creating wrapper instances

**Comment by daniel-luberda** [comment]
Fixed. @marius-bughiu @molinch Nice catch! :) 

> Is there any way to disable logging entirely?

Just provide a custom `IMiniLogger` implementation which does nothing.
