### ISSUE TITLE
[question] How to get ImageSource or FileImageSource from SVG?

### ISSUE THREAD

**Issue by rraallvv** [luberda-molinet/FFImageLoading#913]
I'm looking for a way to load SVG images into Xamarin.Form controls like so:

```
var MyImage = new Image { Source = ImageSource.FromFile("image.svg") };
var MyToobarItem = new ToolbarItem { Icon = new FileImageSource { File = "image.svg" } };
```

My understanding is that `FFImageLoading` converts SVG files to rasterized images and caches those images somewhere. So, my question is whether it is possible to get an `ImageSource` or `FileImageSource` from the cached SVG image? which will be as effective as getting those from the SVG image directly.

Keep up the good work.

**Comment by EmilAlipiev** [comment]
Did you find any solution for this?

**Comment by rraallvv** [comment]
@EmilAlipiev I ended up converting all the SVG images to PNG at build time using this [NuGet package](https://github.com/Redth/Resizetizer).

**Comment by EmilAlipiev** [comment]
why do you prefer PNGs over SVG?

**Comment by rraallvv** [comment]
@EmilAlipiev I was looking for a tool to convert all SVG files to PNG right from the beginning but couldn't find one, then I tried experimenting with the available packages that have build-in SVG support, but neither of them works nicely with `ToolbarItem.Icon` nor `Button.Image`, mainly because they need to have the image as a PNG.

Then I decided to experiment with custom page and button renderers and try to load rasterized versions of the SVG images from the file system, anyway I dropped that approach once I found the package to make the conversion that I posted in my previous comment.

One of the reasons for using PNG files is that it would allow me to have crispy and sharp images of the right size without having to ship SVG images that could be potentially be used for some other purpose that to be embedded in my app.

**Comment by daniel-luberda** [comment]
Unluckily, current implementation of toolbar in Xamarin.Forms only allows pngs from app resources, we can't do anything about it. 

You can use this: https://github.com/daniel-luberda/XamarinFormsToolbarCustomFont as a tip to implement it on your own, **but I would advice to add a feature request on Xamarin.Forms forum, the more people will need this, the higher chance that it would be implemented.**
