### ISSUE TITLE
Not a valid bitmap when I try to preload SVG

### ISSUE THREAD

**Issue by WilliamWatterson86** [luberda-molinet/FFImageLoading#914]
### Description

I have a content page where I am loading an SVG image.  The image loads and displays on screen - however the first time the app is loaded it takes a second or two for the image to appear.  So I tried using this:

ImageService.Instance.LoadEmbeddedResource("SVGImages.temp-circle.svg", typeof(App).GetTypeInfo().Assembly).Preload();

But using this I am getting the error below:
System.BadImageFormatException: Not a valid bitmap

Is there something different I have to do in order to preload the SVG and stop the screen flicker on the first load of the page?

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform:

**Comment by MarcosCobena** [comment]
It happens the same for me, although I'm referencing the image directly from XAML.

**Comment by MarcosCobena** [comment]
Hey! Got it working, double check the SVG appears in this way in your CSPROJ —try moving it to Android's Resources just the assure in this way works:

`<AndroidResource Include="Resources\drawable\icon_nfc.svg" />`

, and that you follow the guideline when installing the NuGet packages:

https://github.com/luberda-molinet/FFImageLoading/wiki/SVG-support#xamarinforms

It should work.
