### ISSUE TITLE
Images overlap randomly in ListView on Android 7.1

### ISSUE THREAD

**Issue by eliasnawfal** [luberda-molinet/FFImageLoading#916]
### Description

Images from Uri are rendered over each other in a ListView in Xamarin Forms Android 7.1 only
if you set DownsampleToViewSize   to true

### Steps to Reproduce
creat listview with cachedImage in it
set DownsampleToViewSize  = true
then you should see images over each other
### Expected Behavior
Images should not overlap

### Actual Behavior

Some Images overlap

### Basic Information

- Version with issue: 2.3.3 (Xamarin.FFImageLoading and Xamarin.FFImageLoading.Forms)
- Platform: Android 7.1 only 

### Screenshots

![image](https://user-images.githubusercontent.com/15719103/35401371-fb7e6862-0201-11e8-8d2a-641c482577bb.png)

**Comment by daniel-luberda** [comment]
I can't reproduce it. Could you make a repo project?
