### ISSUE TITLE
Feature Request - Circle Transformation Border Percent

### ISSUE THREAD

**Issue by mogwai** [luberda-molinet/FFImageLoading#918]
Would it be possible to create a bindable float for border of the circle image so that not the entire border is drawn:

[Example](http://www.johnhembree.com/wp-content/uploads/2015/06/incomplete-circle.png)

Would be very useful for showing a count down of something to users.

**Comment by daniel-luberda** [comment]
You can achieve something similar with SVG files already. You can also create your own custom transformation for this. I'll close this for now.
