### ISSUE TITLE
Can't load SVG image in Xamarin.forms android in version 2.3.4

### ISSUE THREAD

**Issue by asafHorvitz** [luberda-molinet/FFImageLoading#919]
### Description

I have created a new xamarin.forms project, install all Nuget of FFimageloading (version 2.3.4), used the Svg from the FFimageLoading sample, put it in the android resource, and in the forms main root as embedded resource and the svg is not presented.

I tried to use both SvgImageSource.FromResource and ImageSource.FromResource and it didn't work

I attached the sample project i did
[ffimageloadingtests.zip](https://github.com/luberda-molinet/FFImageLoading/files/1670493/ffimageloadingtests.zip)

Off curse i have added the initialization lines in the android  

            global::Xamarin.Forms.Forms.Init(this, bundle);

            FFImageLoading.Forms.Droid.CachedImageRenderer.Init(false);
            var ignore = typeof(FFImageLoading.Svg.Forms.SvgCachedImage);

            LoadApplication(new App());

### Steps to Reproduce

run the sample project

### Basic Information

- Version with issue: <2.3.4>
- Last known good version: 
- Platform:

**Comment by vallchri10** [comment]
I also am running into Android issues with SVG for all verions after 2.2.13

**Comment by eric99r** [comment]
Yea same here. i upgraded to 2.3.4 because i couldn't see my iOS SVGs on the previous versions. but now i can't see Android SVGs

**Comment by EmilAlipiev** [comment]
I think that your project is Android native. I dont know about it but it perfectly works on xamarin forms application. it should logically work on xamarin android as well.

**Comment by daniel-luberda** [comment]
@asafHorvitz First of all, you didn't include embedded resource correctly, your project file has some strange colliding items: 

```XML
  <ItemGroup>
    <None Remove="apple.svg" />
    <None Remove="Resources\test.svg" />
    <None Remove="test.svg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\test.svg" />
    <EmbeddedResource Include="test.svg" />
  </ItemGroup>

```

Second, you should reference SVG by resource name which is generated automatically when you set file build action as `EmbeddedResource`, eg. `FFImageLoading.Forms.Sample.Resources.sample.svg`
