### ISSUE TITLE
SVG ReplaceMap does not support Binding

### ISSUE THREAD

**Issue by TiBall** [luberda-molinet/FFImageLoading#920]
### Description

The SvgCachedImage has a ReplaceMap Property. In the official example there is a Binding to a string dictionary. However, the Property does react to the binding value

### Steps to Reproduce

Add a Binding to the ReplaceMap like in this branch of the example:
https://github.com/TiBall/FFImageLoading-XamarinForms-Demo

### Expected Behavior

Image draws using the ReplaceMap

### Actual Behavior

nothing happens

### Basic Information

- Version with issue: Xamarin.FFImageLoading.Svg.Forms 2.3.4
- Last known good version: none
- Platform: UWP

### Reproduction Link / Code
https://github.com/TiBall/FFImageLoading-XamarinForms-Demo

Is there any other instant workaround?

**Comment by EmilAlipiev** [comment]
Strange this was working in the earlier versions. I wonder what was changed. I tested on Android also not working

**Comment by EmilAlipiev** [comment]
It is totally working fine for me. you can use converter as below.

this is a replacing color withing the svg. default has #2196F3. you need raise AssignColor as fake value just to trigger purpose

```
   <ffimageloadingsvg:SvgCachedImage  BackgroundColor="Transparent" Aspect="AspectFit"  
                   ReplaceStringMap="{Binding AssignColor, Converter={StaticResource AppColorConverter}"
                  HorizontalOptions="Fill"  Source="resource://myApp.Images.Icons.icon.svg" />
```


 ```
public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (PreferredColor != null)
            {
                var ReplaceMap = new Dictionary<string, string>()
                {
                    { "#2196F3", $"{PreferredColor}" }
                };

                return ReplaceMap;
            }
            else
                return "#2196F3";
        }

    
```

**Comment by TiBall** [comment]
Maybe you are using a different version of FFImageLoading? Please check out the demo sourcecode I provided and see if this works for you on the UWP platform?

**Comment by EmilAlipiev** [comment]
I am using the latest version 2.3.4. I am sorry. I dont have much time to verify projects but it surely does work with my code above. I use it all over my project.

**Comment by TiBall** [comment]
Your code is probably different from what I have:
- You are probably providing the AssignColor Value in your binding-Property before initialization of the Image control and did not try to change it later.
- However in my case I want to update the Binding Value. And this does not have any effect. I peaked into the code and saw, that there is not even a PropertyChanged Handler registered for that ReplaceStringMap Property. So do it just can´t work!

**Comment by TiBall** [comment]
I´m pasting the code for you so you don´t have to clone anything:
XAML-View
`<ffSvg:SvgCachedImage x:Name="CachedImage" 
			                      Source="resource://FfImageLoadingApp.svg.svg" 
			                      WidthRequest="100" 
			                      HeightRequest="100" ReplaceStringMap="{Binding ReplaceMap}"/>
<Button Clicked="Button_OnClicked" Text="Update Color using Binding"/>
			  <Button Clicked="Button2_OnClicked" Text="Update Color directly"/>
				<Button Clicked="Button3_OnClicked" Text="Update Color directly and reset source"/>`
Code-Behind
`public MainPage()
        {
	        myViewModel = new MyViewModel() { ReplaceMap = CreateRandomReplaceMap() };
	        BindingContext = myViewModel;

			InitializeComponent();	       	
		}
	    
	    private void Button_OnClicked(object sender, EventArgs e)
	    {
		    //Binding does not work. ReplaceMap does not support binding
		    myViewModel.ReplaceMap = CreateRandomReplaceMap();
	    }
	    private void Button2_OnClicked(object sender, EventArgs e)
	    {
			//Setting it directly on the control even does not work
		    CachedImage.ReplaceStringMap = CreateRandomReplaceMap();			
		}
	    private void Button3_OnClicked(object sender, EventArgs e)
	    {
			//Setting it directly on the control and then updating the Source even doesn´t work		    
			CachedImage.ReplaceStringMap = CreateRandomReplaceMap();
		    CachedImage.Source = "resource://FfImageLoadingApp.svg - Copy.svg";
		    CachedImage.Source = "resource://FfImageLoadingApp.svg.svg";
	    }

	    private Dictionary<string, string> CreateRandomReplaceMap()
	    {
		    var r = _random.Next(256);
		    var g = _random.Next(256);
		    var b = _random.Next(256);

		    string randomColor = $"#{r:X2}{g:X2}{b:X2}";

		    return new Dictionary<string, string>()
		    {
			    {"#FILLCOLOR10", randomColor},
			    {"#FILLCOLOR20", randomColor},
			    {"#FILLCOLOR30", randomColor},
			    {"#FILLCOLOR40", randomColor},
			    {"#FILLCOLOR50", randomColor},
		    };
	    }`
ViewModel
`public class MyViewModel : GalaSoft.MvvmLight.ViewModelBase
	{
		private Dictionary<string, string> _replaceMap;
		public Dictionary<string, string> ReplaceMap
		{
			get => _replaceMap;
			set { Set(() => ReplaceMap, ref _replaceMap, value); }
		}
	}`

**Comment by EmilAlipiev** [comment]
I think that you have problem with your binding.  You have to raise property changed on your binding object yourself in your viewmodel. In order to verify your binding is working, you can attach any converter to see if you hit the converter.

**Comment by TiBall** [comment]
This is doing the notification using MVVMLight:
`set { Set(() => ReplaceMap, ref _replaceMap, value); }`

Also setting the ReplaceStringMap Property directly on the control does not work either:
```
private void Button2_OnClicked(object sender, EventArgs e)
	    {
			//Setting it directly on the control even does not work
		    CachedImage.ReplaceStringMap = CreateRandomReplaceMap();			
		}
```

I have a workaround in my project inside the Converter for the Source-Property: Loading the svg-string myself from the embedded resource and replacing the strings from the Replacemap.

Just wanted to give feedback to improve this cool library. Just check the code yourself please

**Comment by TiBall** [comment]
Oh, and yes, the converter is hit, but it does not reflect in the image.

**Comment by EmilAlipiev** [comment]
yes setting it directly on code behind doesnt work, I tested it before but it works on binding definitely.
I dont know about the mvvmlight but I tested exact code in the sample and it works fine. below is my code

`  <ffimageloadingsvg:SvgCachedImage    BackgroundColor="Transparent"      ReplaceStringMap="{Binding ReplaceColor}"     HorizontalOptions="Fill" Source="resource://myApp.Images.Icons.icon.svg">`



`public System.Collections.Generic.Dictionary<string, string> ReplaceColor { get; set; }
`
and in the viewmodels constructor i am raising 
 ```
  ReplaceColor = new System.Collections.Generic.Dictionary<string, string>()
                {
                    { "#2196F3", $"{PreferredColor}" }
                };

            RaisePropertyChanged("ReplaceColor");
```
I believe that sample code is also working.  you should check your code for binding or maybe your svg has problem.
PS, please use a proper language if you need assistance when you create an issue. this is not a competition.

**Comment by TiBall** [comment]
@EmilAlipiev Sry, I did not mean to use inappropriate language. Where?
Back to my point:
Yes, If all the properties are initialized with the Viewmodel, as in my MainPage-Constructor, the SvgCachedImage pickes up the ReplaceStringMap and replaces the Colors.
**However if the ReplaceStringMap Property is updated later, e.g. from a Button Click Handler, the SvgCachedImage does not update in my code.**
Background: I have an Observable List as a Source to populate a ListView. The Items inside the Listview are added step by step after they come in from my Rest-calls. In that case the ReplaceStringMap did not work with a Binding. This is why I added the ReplaceStringMap Binding to the provided example code on Github and attached the forked Branch. I thought this was the easiest way to report the problem.

Sure, there might be something I am doing wrong, but I couldn´t figure it out by reading the documentation and discussions. Maybe you can just send me your project so I can compare if I am doing something differently, that causes the problem.

Again, I like the project and I´m happy about your investigation. I don´t know why you are offended or think this is some kind of competition?

**Comment by daniel-luberda** [comment]
@TiBall There's a full working example of ReplaceStringMap in sample project: 

- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/SvgReplacePage.xaml
- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/SvgReplacePage.xaml.cs
- https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Shared/Pages/SvgReplacePageModel.cs

Please make sure you have a correct `INotifyPropertyChanged` implementation inside your view model
