### ISSUE TITLE
Is it possible to remove image cache at once?

### ISSUE THREAD

**Issue by 5yunus2efendi** [luberda-molinet/FFImageLoading#921]
I have a scenario whenever user logout I need to clear all current image cache, is possible to do that? What I have so far is to get the list of images from current user and get the image link and then call `await CachedImage.InvalidateCache(url, CacheType, true);`

**Comment by AndreiMisiukevich** [comment]
Hi @5yunus2efendi 
Try this
```csharp
await ImageService.Instance.InvalidateCacheAsync(CacheType.All);
```

**Comment by 5yunus2efendi** [comment]
Thanks!

**Comment by EmilAlipiev** [comment]
@AndreiMisiukevich  does this for both cachetype disk and memory? What is the purpose of using for cachetype=disk if I am using embedded images for example?
for memory I am using   FFImageLoading.ImageService.Instance.InvalidateMemoryCache()
Is it any difference?

**Comment by AndreiMisiukevich** [comment]
@EmilAlipiev 
So, if your app caches an image, it will be stored on device (DiskCache).
if you enable MemoryCache, during first request of this image, your app will retrieve bytes[] from disk and store it into RAM... So, every next request it needn't have to retrieve it from disk again (Convert bytes to Bitmap etc).

So, if you invalidate only memory cache, files will stay on your device. But your RAM will be cleaned.

as for "What is the purpose of using for cachetype=disk if I am using embedded images for example?"
I hope, it should be clear) If you don't use memory cache, every call of images will start retrieving chunk.
