### ISSUE TITLE
[macOS] CachedImage on Modal appears only the first time

### ISSUE THREAD

**Issue by YZahringer** [luberda-molinet/FFImageLoading#922]
### Description
On macOS, the CachedImage is displayed only the first time in a Modal. If the Modal is closed and reopened, the image is not displayed. It works on UWP, iOS & Android.

### Basic Information
- Version with issue: 2.3.4
- Platform: Xamarin.Forms 2.5.0.122203 on macOS

### Reproduction Link / Code
https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/FFImageLoading-ModalPage

**Comment by YZahringer** [comment]
@daniel-luberda do you have a fix for this? I tried to disable the cache, the problem persists. This is blocking on macOS, the images are displayed only the first time in navigation between views.

**Comment by daniel-luberda** [comment]
That was hard :/ Fixed :)

**Comment by YZahringer** [comment]
Thank you 😄
