### ISSUE TITLE
Unable to add nuget package

### ISSUE THREAD

**Issue by geedsen** [luberda-molinet/FFImageLoading#924]
### Description
Adding in VS2017 using Manage Nugets results in

Error reading '' at line 0 column 0 : Imports contains an invalid framework: '[  "unsupported",  "portable-monoandroid10+monotouch10+net45+win+win81+wp8+wpa81+xamarinios10"]' in 'project.json'.
Imports contains an invalid framework: '[  "unsupported",  "portable-monoandroid10+monotouch10+net45+win+win81+wp8+wpa81+xamarinios10"]' in 'project.json'.			0	

### Steps to Reproduce

See above

### Expected Behavior

Package gets added

### Actual Behavior

There is an error

**Comment by EmilAlipiev** [comment]
Nobody can you help you with this Information as nuget works for everybody else. You should provide more information and even a reproduction project. Because  Problem is specific to your project

**Comment by daniel-luberda** [comment]
Please attach a sample project, those informations are not enough. Thanks :)
