### ISSUE TITLE
[XF.UWP] Black color instead of transparency if use smallest 8-bit png only with downsample params

### ISSUE THREAD

**Issue by JTOne123** [luberda-molinet/FFImageLoading#927]
### Description
I optimized my images on a website with Photoshop export with option Smaller File (8-bit) after it I got black color in UWP (ios and android is ok).

When I deleted downsample parameters for CachedImage then transparency was back.

### Steps to Reproduce
Resave png with photoshop smaller file (8-bit)
DownsampleToViewSize = true

### Expected Behavior
Transparency instead of black color

### Actual Behavior
Black color

### Basic Information

- Version with issue: 
2.3.4 and 2.2.x
- Last known good version: 
- Platform: 

### Screenshots
![uwp-transparency-issue](https://user-images.githubusercontent.com/3457140/35683377-5ddd2876-076c-11e8-951d-c7c03b5133fd.png)

2 files before and after PS smaller file optimization

![courier_works_but_bigsize](https://user-images.githubusercontent.com/3457140/35683650-543ff478-076d-11e8-8c7a-3d55c6fd4809.png)
![courier_black_insteadof_transparency](https://user-images.githubusercontent.com/3457140/35683651-54610c4e-076d-11e8-932a-4e1187b07d93.png)

**Comment by daniel-luberda** [comment]
Let's continue here: https://github.com/luberda-molinet/FFImageLoading/issues/986

**Comment by JTOne123** [comment]
thank you!
