### ISSUE TITLE
Extended CachedImage

### ISSUE THREAD

**Issue by poseydonfba** [luberda-molinet/FFImageLoading#928]
I am trying to create an ExtendedImage, but the image does not load, it is left blank. Any tips on what could be wrong?

**It works**
`
                        <ffimageloading:CachedImage HeightRequest="100" Aspect="AspectFill"
                            DownsampleHeight="100" DownsampleUseDipUnits="false"
                            LoadingPlaceholder="image_loading.png" ErrorPlaceholder="image_error.png" 
                            Source="{Binding Source}">
                        </ffimageloading:CachedImage>
`

**Does not work**
`
                        <Controls:ExtendedImage HeightRequest="100" Aspect="AspectFill"
                            DownsampleHeight="100" DownsampleUseDipUnits="false"
                            LoadingPlaceholder="image_loading.png" ErrorPlaceholder="image_error.png" 
                            Source="{Binding Source}">
                        </Controls:ExtendedImage>
`

This code is inside a FlowListView
`

            <flv:FlowListView.FlowColumnTemplate>
                <DataTemplate>

                    <Grid Padding="1">

                        <Grid.RowDefinitions>
                            <RowDefinition Height="*" />
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*" />
                        </Grid.ColumnDefinitions>

                        

                        <Controls:ExtendedImage HeightRequest="100" Aspect="AspectFill"
                            DownsampleHeight="100" DownsampleUseDipUnits="false"
                            LoadingPlaceholder="image_loading.png" ErrorPlaceholder="image_error.png" 
                            Source="{Binding Source}">
                        </Controls:ExtendedImage>

                        <Label x:Name="" HorizontalOptions="Fill" HorizontalTextAlignment="Center" VerticalOptions="End"
                                BackgroundColor="Silver" Opacity="0.5" Text="Imagem"/>

                    </Grid>

                </DataTemplate>
            </flv:FlowListView.FlowColumnTemplate>
`

Extended component
`
    public class ExtendedImage : CachedImage
    {
    }
`

**Comment by daniel-luberda** [comment]
Did you try lowercase namespace? Change `Control` to `control`
