### ISSUE TITLE
UWP doesnt download Gif (non animated), it used to work before

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#929]
If i have gif file like attached and i am storing in the cloud with code below, it doesn't download in a ListView.  It display errorplaceholder immediately.  I have unfortunately images stored mix gif (non-animated) and png, pngs are downloaded but gifs are not. It works perfectly fine on Android.

I tested only on UWP desktop so far, I will test on emulator later as well. This used to work in earlier versions. I cant unfortunately know which version because I haven't touched my UWP project long time until today.

![biceps-curl-reverse-1](https://user-images.githubusercontent.com/10422347/35750483-6cb506b8-0855-11e8-8c64-9d44202a55b7.gif)
```


    <ffimageloading:CachedImage  RetryCount="1"	  TransparencyEnabled = "false"   CacheDuration = "120" DownsampleToViewSize="True"   LoadingPlaceholder="loading.gif"   FadeAnimationEnabled="True"     CacheType="All"  InputTransparent="True"     ErrorPlaceholder="error.png"
                                                    Source="{Binding Image, Converter={StaticResource thumbnailConvertor}, ConverterParameter=0}"
                             Aspect="AspectFit"  Grid.Row="0" Grid.Column="0"  />
```

**Comment by daniel-luberda** [comment]
Do you get any errors in console?

**Comment by EmilAlipiev** [comment]
To be honest, I changed all my images as svg and not even using any png or gif anymore and using ffimage svg library all works fine so far. If you want you can close this ticket :)

**Comment by daniel-luberda** [comment]
Ok then :)
