### ISSUE TITLE
Make TintTransformation.HexColor a bindable property

### ISSUE THREAD

**Issue by odyodyodys** [luberda-molinet/FFImageLoading#931]
### Description
It would be **really** helpful if the `TintTransformation.HexColor` property was bindable

### Basic Information

- Version with issue: Current
- Platform: All

**Comment by daniel-luberda** [comment]
Duplicate of https://github.com/luberda-molinet/FFImageLoading/issues/860 and https://github.com/luberda-molinet/FFImageLoading/issues/499
