### ISSUE TITLE
this.DataLocationUri doesn't exist in ImageViewAsync class

### ISSUE THREAD

**Issue by justintoth** [luberda-molinet/FFImageLoading#933]
### Description

I created a CachedImageView class that has ImageViewAsync as a base class, so that I could implement the JavaFinalize method, as suggested [here](https://github.com/luberda-molinet/FFImageLoading/wiki/Advanced-Usage). However, this.DataLocationUri doesn't exist so I can't expire the cache entry. Please advice how to retrieve this.DataLocationUri, as it's not obvious from the docs.

### Steps to Reproduce

Implement your own image view class, inheriting from ImageViewAsync.

### Expected Behavior

this.DataLocationUri would be available for expiring the cache key, as shown in the docs.

### Actual Behavior

this.DataLocationUri doesn't exist so you get a build error.

### Basic Information

- Version with issue: Latest nuget package.
- Platform: Visual Studio for Mac, Xamarin Android

### Reproduction Link / Code

```
public class CachedImageView : ImageViewAsync {
        protected CachedImageView (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer) {
		}

        public CachedImageView (Context context) : base (context) {
		}

        public CachedImageView (Context context, IAttributeSet attrs) : base (context, attrs) {
		}

        public CachedImageView (Context context, IAttributeSet attrs, int defStyle) : base (context, attrs, defStyle) {
		}

        protected override void JavaFinalize () {
            SetImageDrawable (null);
            SetImageBitmap (null);
            //ImageService.Instance.InvalidateCacheEntryAsync (this.DataLocationUri, FFImageLoading.Cache.CacheType.Memory);
            base.JavaFinalize ();
        }
	}
```

**Comment by justintoth** [comment]
I was able to get around this issue by adding a custom property, CacheKey, to my custom CachedImageView control and then setting that manually on both the view and the FFImageLoading CacheKey method when loading an image into the view.

Here is the new CachedImageView: (Note the removeSimilar = true was necessary, as the actual cache key isn't exactly what I set it to in the .CacheKey method)

```
public class CachedImageView : ImageViewAsync {
        public string CacheKey { get; set; }

        protected CachedImageView (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer) {
		}

        public CachedImageView (Context context) : base (context) {
		}

        public CachedImageView (Context context, IAttributeSet attrs) : base (context, attrs) {
		}

        public CachedImageView (Context context, IAttributeSet attrs, int defStyle) : base (context, attrs, defStyle) {
		}

        protected override void JavaFinalize () {
            CleanUp ();
            base.JavaFinalize ();
        }

        public void CleanUp () {
            if (!Handle.IsValid ())
                return;

            var drawable = Drawable as BitmapDrawable;
            if (drawable != null && drawable.Bitmap != null) {
                if (!drawable.Bitmap.IsRecycled)
                    drawable.Bitmap.Recycle ();
                drawable.Bitmap.Dispose ();
                drawable.Dispose ();
                drawable = null;
            }
            SetImageDrawable (null);
            SetImageBitmap (null);

            if (!string.IsNullOrEmpty (CacheKey)) {
                ServiceLocator.Current.Resolve<ILoggingService> ().Log (Shared.Resources.CommonEnums.LogLevel.Info, "Removing image from memory cache: " + CacheKey);
                ImageService.Instance.InvalidateCacheEntryAsync (CacheKey, FFImageLoading.Cache.CacheType.Memory, removeSimilar: true);
            }
        }
	}
```

And here is how it's used:

```
public static void SetUrlBitmap (this CachedImageView imageView, string url, 
            int? loadingResourceId = null, int? errorResourceId = null, double? zoomFactor = null) {
            var activity = ApplicationContext.Activity;
            activity.RunOnUi (() => {
                imageView.CacheKey = url;
                var transformations = new List<ITransformation> ();
                if (zoomFactor.HasValue)
                    transformations.Add (new CropTransformation (zoomFactor.Value, 0, 0));
                ImageService.Instance.LoadUrl (url)
                    .CacheKey (url)
                    .Transform (transformations)
                    .Retry (3, 200)
                    .Into (imageView);
            });
        }
```

Now it's correctly removing the cached entries from the memory cache. Unfortunately, this has now caused the application to start throwing the following exception:

> Image loading failed: http://rprimage.realestatedigital.com/ListingImages/flmfr-n1b/addl_picts/1756/0/T2868833-7.jpg?201703311054;CropTransformation,zoomFactor=1.22000002861023,xOffset=0,yOffset=0,cropWidthRatio=1,cropHeightRatio=1
> Java.Lang.IllegalStateException: md59cd5ae6924ea1865908f6a4eed48fb35.LRUCache.sizeOf() is reporting inconsistent results!
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
>   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <e8c0e16a54534fa885244f0ad837c79e>:0 
>   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <e8c0e16a54534fa885244f0ad837c79e>:0 
>   at Android.Util.LruCache.Put (Java.Lang.Object key, Java.Lang.Object value) [0x00043] in <848bbd7c681a4975918c72f17d2f5144>:0 
>   at FFImageLoading.Cache.ByteBoundStrongLruCache`1[TValue].Add (System.String key, TValue value) [0x00011] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ByteBoundStrongLruCache.cs:67 
>   at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].PromoteReuseEntryToDisplayedCache (TValue value) [0x0006e] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:294 
>   at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].OnEntryDisplayed (System.Object sender, System.EventArgs args) [0x00025] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:267 
>   at FFImageLoading.Drawables.SelfDisposingBitmapDrawable.SetIsDisplayed (System.Boolean isDisplayed) [0x00075] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Drawables\SelfDisposingBitmapDrawable.cs:151 
>   at FFImageLoading.Drawables.FFBitmapDrawable.SetIsDisplayed (System.Boolean isDisplayed) [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Drawables\FFBitmapDrawable.cs:78 
>   at FFImageLoading.Views.ManagedImageView.UpdateDrawableDisplayedState (Android.Graphics.Drawables.Drawable drawable, System.Boolean isDisplayed) [0x00028] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Views\ManagedImageView.cs:205 
>   at FFImageLoading.Views.ManagedImageView.SetImageDrawable (Android.Graphics.Drawables.Drawable drawable) [0x00092] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Views\ManagedImageView.cs:168 
>   at FFImageLoading.Targets.ImageViewTarget.Set (FFImageLoading.Work.IImageLoaderTask task, FFImageLoading.Drawables.SelfDisposingBitmapDrawable image, System.Boolean animated) [0x00020] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Targets\ImageViewTarget.cs:48 
>   at FFImageLoading.PlatformImageLoaderTask`1+<>c__DisplayClass5_0[TImageView].<SetTargetAsync>b__0 () [0x0000b] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Work\PlatformImageLoadingTask.cs:89 
>   at FFImageLoading.Helpers.MainThreadDispatcher+<>c__DisplayClass2_0.<PostAsync>b__0 () [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Helpers\MainThreadDispatcher.cs:32

**Comment by daniel-luberda** [comment]
You shouldn't dispose those bitmaps. They would be disposed after `ImageService.Instance.InvalidateCacheEntryAsync` call.
