### ISSUE TITLE
AsPNGStreamAsync crashes app but gives no error in logs

### ISSUE THREAD

**Issue by justintoth** [luberda-molinet/FFImageLoading#934]
### Description

When calling AsPNGStreamAsync on a loaded file, the app crashes but gives no error in the logs. I tested both by passing in a file path, and also by passing in a stream of the file. Also, no exception is thrown.

### Steps to Reproduce

- Pick a photo from the Android gallery picker.
- Pass the photo's path (e.g. /storage/emulated/0/Android/data/com.rpr.mobile/cache/image-cache/photo-file-789e3d9e-f81c-4191-955a-240988d7b9ec1131019452.jpg) into the LoadFile method, or read the file path into a stream and then pass that in, then call AsPNGStreamAsync on it and wait for the result.

### Expected Behavior

A stream will be returned for the passed in file.

### Actual Behavior

The app crashes. No exception is thrown (if you have a try/catch around the code) and no errors are logged to the application output.

Edit: I pulled down the source code and retested, it's giving a SIGSEGV: https://gist.github.com/justintoth/2bf2e3f50955660c2614383cd5565a74

### Basic Information

- Version with issue: Latest nuget package
- Platform: Visual Studio for Mac, Xamarin Android

### Reproduction Link / Code

```
try {
                var task = ImageService.Instance.LoadFile (filePath)
                    .DownSample (width: SharedConstants.PhotoKeys.PHOTO_WIDTH)
                    .AsPNGStreamAsync ();
                task.Wait ();// App crashes here
                var stream = task.Result;
                var bytes = stream.ToByteArray ();
                return bytes;
            } catch (Exception exc) {
                throw exc;
            }
```

```
try {
                var task = ImageService.Instance.LoadStream ((cts) => {
                        var tcs = new TaskCompletionSource<Stream> ();
                        var originalStream = ContentHelper.GetStream (ContentHelper.GetFileUri (filePath));
                        tcs.SetResult ((Stream)originalStream);
                        return tcs.Task;
                    })
                    .DownSample (width: SharedConstants.PhotoKeys.PHOTO_WIDTH)
                    .AsPNGStreamAsync ();
                task.Wait ();
                var stream = task.Result;
                var bytes = stream.ToByteArray ();
                return bytes;
            } catch (Exception exc) {
                throw exc;
            }
```

**Comment by daniel-luberda** [comment]
Could you reproduce it with 2.3.5?

**Comment by daniel-luberda** [comment]
`task.Wait ();` 

It's not an FFImageLoading issue. That code is leading to a deadlock. You should't use async apis like that.

That **could** help, but I still advice not to do it: 

`task.ConfigureAwait(false)`
`var result = task.GetAwaiter().GetResult()`
