### ISSUE TITLE
Transformations leak memory

### ISSUE THREAD

**Issue by justintoth** [luberda-molinet/FFImageLoading#936]
### Description

When using a transformation, such as a CropTransformation, on an image loaded by a url, the memory is held onto and leaks. No amount of cleanup on the imageview, drawable, or bitmap will release this memory. And yet, if I disable the transformations then the memory is cleaned up correctly.

### Steps to Reproduce

- Load a sequence of large images into an imageview, using ImageService.Instance.LoadUrl, while using a CropTransformation. 
- Before loading the next image, clean up the first image by disposing of its drawable, bitmap, etc... 
- Watch the memory from Android device monitor, how it jumps up each time a new image is loaded into the imageview. Eventually the app will crash with OOM exceptions.
- You can also try switching to disk caching instead of memory caching, or disable the cache already, and it'll still leak.
- Disable the transformations code, and notice how now the memory doesn't leak at all.

### Expected Behavior

The memory wouldn't leak when using transformations.

### Actual Behavior

Memory does leak when using transformations.

### Basic Information

- Version with issue: Latest nuget package
- Platform: Visual Studio for Mac, Xamarin Android

### Reproduction Link / Code

```
public static void SetUrlBitmap (this CachedImageView imageView, string url, double? zoomFactor = null) {
            var activity = ApplicationContext.Activity;
            activity.RunOnUi (() => {
                imageView.CacheKey = url;
                var transformations = new List<ITransformation> ();
                if (zoomFactor.HasValue)
                    transformations.Add (new CropTransformation (zoomFactor.Value, 0, 0));
                ImageService.Instance.LoadUrl (url)
                    //.WithCache (FFImageLoading.Cache.CacheType.Disk)
                    .CacheKey (url)
                    .Transform (transformations)
                    .Retry (3, 200)
                    .Into (imageView);
                transformations.Clear ();
            });
        }
```

**Comment by daniel-luberda** [comment]
See this: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Droid/Work/PlatformImageLoadingTask.cs#L149-L156

```C#
                        if (old != null && old.Handle != IntPtr.Zero && !old.IsRecycled && old != bitmap && old.Handle != bitmap.Handle)
                        {
                            // Adding to pool gives us a better performance
                            ImageCache.Instance.AddToReusableSet(new SelfDisposingBitmapDrawable(old) { InCacheKey = Guid.NewGuid().ToString() });
                            // Old and less efficient:
                            //old?.Recycle();
                            //old.TryDispose();
                        }
```

Previously, we disposed those bitmaps, but recently it was changed to put those bitmaps into reuse pool (which cleans automatically). That's why it's still in cache. Those bitmaps are used to speed up loading of another images, but in your case (large bitmaps) it may lead to some issues. I'll consider rolling it back.

**Comment by daniel-luberda** [comment]
Should be fixed now.

**Comment by justintoth** [comment]
Now it gives this error when enabling a crop transformation:

> Transformation failed: CropTransformation,zoomFactor=1.22000002861023,xOffset=0,yOffset=0,cropWidthRatio=1,cropHeightRatio=1
> Java.Lang.IllegalArgumentException: width and height must be > 0
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
>   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <e8c0e16a54534fa885244f0ad837c79e>:0 
>   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <e8c0e16a54534fa885244f0ad837c79e>:0 
>   at Android.Graphics.Bitmap.CreateBitmap (System.Int32 width, System.Int32 height, Android.Graphics.Bitmap+Config config) [0x0005a] in <848bbd7c681a4975918c72f17d2f5144>:0 
>   at FFImageLoading.Transformations.CropTransformation.ToCropped (Android.Graphics.Bitmap source, System.Double zoomFactor, System.Double xOffset, System.Double yOffset, System.Double cropWidthRatio, System.Double cropHeightRatio) [0x000c3] in C:\projects\ffimageloading\source\FFImageLoading.Transformations.Droid\CropTransformation.cs:90 
>   at FFImageLoading.Transformations.CropTransformation.Transform (Android.Graphics.Bitmap sourceBitmap, System.String path, FFImageLoading.Work.ImageSource source, System.Boolean isPlaceholder, System.String key) [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Transformations.Droid\CropTransformation.cs:46 
>   at FFImageLoading.Transformations.TransformationBase.Transform (FFImageLoading.Work.IBitmap bitmapHolder, System.String path, FFImageLoading.Work.ImageSource source, System.Boolean isPlaceholder, System.String key) [0x00007] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Transformations\TransformationBase.cs:14 
>   at FFImageLoading.PlatformImageLoaderTask`1+<TransformAsync>d__10[TImageView].MoveNext () [0x000b4] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Work\PlatformImageLoadingTask.cs:138 
>   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
> java.lang.IllegalArgumentException: width and height must be > 0
> 	at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
> 	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
> 	at android.graphics.Bitmap.createBitmap(Bitmap.java:823)

Here is the code:

```
public static void SetUrlBitmap (this CachedImageView imageView, string url, 
            string loadingResource = null, string errorResource = null, double? zoomFactor = null) {
            var activity = ApplicationContext.Activity;
            activity.RunOnUi (() => {
                imageView.CacheKey = url;
                var transformations = new List<ITransformation> ();
                if (zoomFactor.HasValue)
                    transformations.Add (new CropTransformation (zoomFactor.Value, 0, 0));
                ImageService.Instance.LoadUrl (url)
                    .CacheKey (url)
                    .LoadingPlaceholder (loadingResource, ImageSource.ApplicationBundle)
                    .Transform (transformations)
                    .Retry (3, 200)
                    .Into (imageView);
                transformations.Clear ();
            });
        }
```
