### ISSUE TITLE
TintTransformation.HexColor Binding

### ISSUE THREAD

**Issue by NVentimiglia** [luberda-molinet/FFImageLoading#937]
### Description
I would like to bind a fft:TintTransformation.HexColor to a constant string or DynamicResource

### Steps to Reproduce

```
<fft:TintTransformation
    HexColor="{Binding Source={x:Static res:Colours.ICON_TINT_HEX}}"
    EnableSolidColor="true" />

```

### Expected Behavior

It binds.

### Actual Behavior

No property, bindable property, or event found for 'HexColor', or mismatching type between value and property

**Comment by MosCD** [comment]
I have the same problem

**Comment by flchaux** [comment]
Idem here.

**Comment by MosCD** [comment]
I found the reply is here
https://github.com/luberda-molinet/FFImageLoading/issues/491#issuecomment-279891483

**Comment by daniel-luberda** [comment]
@MosCD Thanks!

> Yes, transformations properties are not bindable as they must also work in a non Xamarin.Forms projects. But that will change soon, as we're including Transformations packages in a base nugets, so we can add Xamarin.Forms specific Transformations for that which can have bindable properties :) I created issue for this: #499
