### ISSUE TITLE
Building project on VisualStudio 2017

### ISSUE THREAD

**Issue by salemoh** [luberda-molinet/FFImageLoading#940]
### Description

I'm trying to build the project FFImageLoading from GitHub in Visual Studio 2017 but facing a lot of the below errors

'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\BasicPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\ByteArrayListPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\ByteArrayListPageCell.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\CachedImageSizingTestPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\CustomKeyPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\CustomKeyPageCell.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\DataUrlPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\ListPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\ListPageCell.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\ListTransformationsPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\ListTransformationsPageCell.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\MenuPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\PlaceholdersPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\SimpleGifPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\SimpleWebpPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\StreamListPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\StreamListPageCell.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\SvgReplacePage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\SvgSamplePage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\Transformations\BlurredTransformationPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\Transformations\CircleTransformationPage.xaml	0	
'EmbeddedResource' is not supported by one or more of the project's targets.	ImageLoading.Forms.Sample\Shared\Pages\Transformations\ColorSpaceTransformationPage.xaml	0

**Comment by EmilAlipiev** [comment]
This has nothing to do with this library. it is general VS2017 problem. it happens almost with any library when you donwload from github. see your nuget references probably all broken

**Comment by daniel-luberda** [comment]
FFImageLoading build just fine on our AppVeyor CI  page and Visual Studio 2017 is used there too. I'll close this one.  See: https://ci.appveyor.com/project/daniel-luberda/ffimageloading
