### ISSUE TITLE
UWP Kiosk mode (assigned apps) not working

### ISSUE THREAD

**Issue by csciallano** [luberda-molinet/FFImageLoading#941]
Hi,
i just tried to integrate FFImageLoading in a Xamarin (UWP netstandard 2.0) application who has to be configured through the kiosk mode (assigned apps)
[create-a-kiosk-app-for-assigned-access](https://docs.microsoft.com/fr-fr/windows-hardware/drivers/partnerapps/create-a-kiosk-app-for-assigned-access)

Windows version 1709 (16299.192)

This mode is used to let only a single app running on a machine.

I couldn't get it to work with FFIMageLoading because it's crashing on the call : CachedImageRenderer.Init()

Sadly i can't get any logs because the app is crashing only in kiosk mode and i can't attach to the process.

BUT, if i refer to the above link from microsoft, i can read that :

> The usage of CoreApplication.MainView.Dispatcher would cause the app crash in this example because in assigned access mode, the main window is not MainView but rendered in a secondary view. It is recommended you use CoreApplication.GetCurrentView.Dispatcher.

In the CachedImageRenderer.Init() method, the [ScaleHelper](https://github.com/luberda-molinet/FFImageLoading/blob/6141949d3da8da918ed89595073d34584df9bf15/source/FFImageLoading.Windows/Helpers/ScaleHelper.cs) is called and instantiante a [MainThreadDispatcher](https://github.com/luberda-molinet/FFImageLoading/blob/6141949d3da8da918ed89595073d34584df9bf15/source/FFImageLoading.Windows/Helpers/MainThreadDispatcher.cs) using the wrong dispatcher according to ms.

What do you think ? :)

**Comment by daniel-luberda** [comment]
You can provide your own `MainThreadDispatcher` implementation with custom config. That should be easy.

**Comment by csciallano** [comment]
Hi, I didn't know that kind of configuration was possible in FFImageloading but yeah i tried and it worked perfectly !
