### ISSUE TITLE
Crash occured in 2.2.17 NSInternalInconsistencyException Reason: No view controller managing revealed view

### ISSUE THREAD

**Issue by Resham143** [luberda-molinet/FFImageLoading#942]
### Description

Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: No view controller managing revealed view <FFImageLoading_Forms_Touch_CachedImageRenderer: 0x7fe9314ca770; frame = (0 0; 375 175); autoresize = LM+W+RM+TM+H+BM; layer = <CALayer: 0x6040044300e0>>
Native stack trace:
	0   CoreFoundation                      0x0000000118d9512b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000119d57f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000118d9a2f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001180edd69 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x0000000116827619 -[UIPageViewController queuingScrollView:willManuallyScroll:toRevealView:concealView:animated:] + 1124
	5   UIKit                               0x000000011694a314 -[_UIQueuingScrollView _notifyDelegateWillManuallyScroll:toRevealView:concealingView:animated:] + 127
	6   UIKit                               0x000000011694ba93 __54-[_UIQueuingScrollView _didScrollWithAnimation:force:]_block_invoke + 466
	7   UIKit                               0x000000011694b5b2 -[_UIQueuingScrollView _didScrollWithAnimation:force:] + 534
	8   UIKit                               0x0000000116946e34 -[_UIQueuingScrollView _scrollViewAnimationEnded:finished:] + 92
	9   UIKit                               0x0000000116015c53 -[UIAnimator stopAnimation:] + 422
	10  UIKit                               0x00000001160163a1 -[UIAnimator _advanceAnimationsOfType:withTimestamp:] + 282
	11  QuartzCore                          0x00000001154b02b8 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 684
	12  QuartzCore                          0x00000001155f0894 _ZL22display_timer_callbackP12__CFMachPortPvlS1_ + 248
	13  CoreFoundation                      0x0000000118d24899 __CFMachPortPerform + 169
	14  CoreFoundation                      0x0000000118d247d9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	15  CoreFoundation                      0x0000000118d24741 __CFRunLoopDoSource1 + 465
	16  CoreFoundation                      0x0000000118d1c524 __CFRunLoopRun + 2596
	17  CoreFoundation                      0x0000000118d1b889 CFRunLoopRunSpecific + 409
	18  GraphicsServices                    0x000000011b73f9c6 GSEventRunModal + 62
	19  UIKit                               0x0000000115e845d6 UIApplicationMain + 159
	20  ???                                 0x00000001389a1508 0x0 + 5244589320
	21  ???                                 0x00000001389a1133 0x0 + 5244588339
 (Foundation.MonoTouchException)
  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/ObjCRuntime/Runtime.cs:362 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/runtime/Delegates.generated.cs:130 
  at (wrapper native-to-managed) ObjCRuntime.Runtime:throw_ns_exception (intptr)
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at ......iOS.Application.Main (System.String[] args) [0x00000] in /Users/......./Main.cs:17 

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

### Steps to Reproduce

Can not reproduce by my own. Occurs some time and not at fixed location because i am only using CachedImage 

### Expected Behavior

Expected to work smoothly with out any crash
### Actual Behavior
Sometimes get crash and can not be handled 

### Basic Information

- Version with issue: 2.2.17
- Last known good version: unknown
- Platform: Xamarin Forms (iOS)

**Comment by daniel-luberda** [comment]
It's a Xamarin Forms issue, FFImageLoading isn't responsible for managing view controller, it's a `ViewRenderer` implementation issue. You could submit it to Xamarin.Forms project. Thanks :)

**Comment by AmauryBJ** [comment]
it's a bug !

**Comment by AmauryBJ** [comment]
FFImageLoading issue !!
