### ISSUE TITLE
Cache is not cleared properly for all transformations

### ISSUE THREAD

**Issue by woutermeuwis** [luberda-molinet/FFImageLoading#944]
### Description

It appears that the cache has multiple instances for each image. (One for each different transformation used)
When the cache is cleared for a certain key, not all images using this key are updated (only the first one)

### Steps to Reproduce

1. Implement an image in your application using a circletransformation with a size and color
2. Implement an image on a different page and do not set it's properties
3. Give both images the same source
4. Load both images
3. Upload a different image to the source url (don't change the url, just the image it points to)
5. Clear the key from the cache with `awaitImageService.Instance.InvalidateCacheEntryAsync(key, CacheType.All, true);`
6. Check both images again

### Expected Behavior

Both images should display the new image.

### Actual Behavior

Only one image updates to the new one, the other image will get the old one from it's cache

### Basic Information

- Version with issue: 2.3.4
- Last known good version: ??
- Platform: Android

**Comment by daniel-luberda** [comment]
Images won't be refreshed automatically after cache clean, you have to reload them manually to see any changes (eg. set to null, then once again to a correct source).
