### ISSUE TITLE
In a Xamarin Forms app, Uwp in release mode does not display a picture.

### ISSUE THREAD

**Issue by WillAutioItrax** [luberda-molinet/FFImageLoading#946]
### Description

In a Xamarin Forms app, Uwp in release mode does not display a picture.

### Steps to Reproduce

Take a picture. Store it locally. Display the picture.

### Expected Behavior

It displays.

### Actual Behavior

It does not display for UWP in release mode.
It does display for UWP debug mode and for either mode for iOS and Droid.

### Basic Information

- Version with issue: FFImageLoading v2.3.4 (and I had tried some earlier ones)
- Last known good version: This is the first time I am trying to do this in UWP
- Platform: Windows 10

### Reproduction Link / Code
https://bitbucket.org/WillAutio/pictest
(Let me know if the sharing does not work - I have never done it this way before)

### Additional comments:
I use:
`
                mediaFile = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    Name = filename,
                    PhotoSize = PhotoSize.Custom,
                    CustomPhotoSize = 80
                });
`
to take a picture. As I use XAML for everything except assigning an ObservableCollection to the FlowItemsSource, I also added:
`FlowListView.Init();`
as recommended elsewhere in a few places.

The key XAML code is:

                <flv:FlowListView FlowColumnCount="3" x:Name="listItems"  
		                SeparatorVisibility="Default"
		                HasUnevenRows="false" RowHeight="150" >
                    <flv:FlowListView.FlowColumnTemplate>
                        <DataTemplate >
                            <ffimageloading:CachedImage  DownsampleToViewSize="true"                                              
                                            Margin="5,5,5,5"
                                            HeightRequest="150"                                                    
                                            Source="{Binding Name}"
                                            Aspect="AspectFill" 
                                            HorizontalOptions="FillAndExpand">
                            </ffimageloading:CachedImage>
                            

                        </DataTemplate>
                    </flv:FlowListView.FlowColumnTemplate>
                </flv:FlowListView>

Thanks for taking a look at this.

**Comment by daniel-luberda** [comment]
It's explained here: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API#windows-uwp---compile-with-net-native-tool-chain-note

**Comment by WillAutioItrax** [comment]
Ah - so once I  changed App.xaml.cs in the UWP project with:
var assembliesToInclude = new List<Assembly>()
{
	typeof(CachedImage).GetTypeInfo().Assembly,
	typeof(CachedImageRenderer).GetTypeInfo().Assembly            
};
Xamarin.Forms.Forms.Init(e, assembliesToInclude);
I see pictutres. Thanks you!
