### ISSUE TITLE
LoadingPlaceholder not appearing until ImageSource.FromStream() finished loading

### ISSUE THREAD

**Issue by ParticularEric** [luberda-molinet/FFImageLoading#948]
### Description

Hi, I am using FFImageLoading in my Xamarin.Forms project but I don´t get  the behaviour I want. I have a list of objects containing the URL for a method to get an image via ImageSource.FromStream for each object. 
In my current example I have 15 of these objects and it takes around 10 seconds to load the pictures. I use a LoadingPlaceholder for that time, but it does not work as expected: Every image is blank for around 9.5 seconds, then I see the loading placeholder for 0.5 seconds and then my downloaded picture. Obviously I would like the placeholder to show the whole time until the download is finished.

I guess its my code, could you give me a hint what I have to change to see the placeholder instantly?

### Basic Information

- Version with issue: 2.3.4
- Last known good version: 
- Platform: Xamarin.Forms / testing on Android

### Screenshots
Here is a gif of the behaviour:
![recipeloading](https://user-images.githubusercontent.com/9088071/36386549-636f93f4-1596-11e8-9e1b-737be4ca7f7d.gif)

### Reproduction Link / Code
This is the basic code example I am experiencing the problem. RecipeGuessResult just has the url and a name in it.

```C#
public class MyClass : ContentPage
    {
        List<RecipeGuessResult> recipeResults;
        public MyClass(List<RecipeGuessResult> recipeResults)
        {
            this.recipeResults = recipeResults;

            ScrollView scrollPage = new ScrollView();
            StackLayout page = new StackLayout();
            page.Spacing = 0;
            Padding = 0;
            BackgroundColor = Color.White;
            scrollPage.Content = page;
            foreach (RecipeGuessResult recipe in recipeResults)
            {
                RecipeResultStack resultStack = new RecipeResultStack(recipe);
                page.Children.Add(resultStack);
            }
            Content = scrollPage;
        }

        public class RecipeResultStack : StackLayout
        {
            public RecipeResultStack(RecipeGuessResult recipe)
            {
                CachedImage recipeImage = new CachedImage();
                recipeImage.HeightRequest = 200;
                recipeImage.WidthRequest = 320;
                recipeImage.LoadingPlaceholder = "recipe_loading";
                recipeImage.ErrorPlaceholder = "recipe_error";
                recipeImage.Aspect = Aspect.AspectFill;
                if (!String.IsNullOrEmpty(recipe.imageUrl))
                {
                    recipeImage.Source = ImageSource.FromStream(() => new MemoryStream(App.MyMethod(recipe.imageUrl)));
                }
                else
                    recipeImage.Source = "recipe_default";

                Children.Add(recipeImage);
                Label nameLabel = new Label();
                nameLabel.Text = recipe.name;
                Children.Add(nameLabel);
            }
        }

    }
```

**Comment by bpater-tp** [comment]
I have the very similar problem. The loading placeholder just doesn't appear. The common thing with sample code above is that I also construct `CachedImage` via code not XAML. And the sample from FFimageloading repo uses XAML and it works.

**Comment by ParticularEric** [comment]
Oh, this is interesting! I am not having that much experience with XAML, but it would be interesting to see if the exact code from my first post would work flawless when written in XAML.

**Comment by daniel-luberda** [comment]
1. Are you sure `recipe_loading` / `recipe_error` files are added to Resources/drawable folder? 
2. FFImageLoading outputs all errors to console. Could you paste it?

**Comment by ParticularEric** [comment]
Hi! 
1. Yes, they are added. I can see them for a split second before the real images load. If you watch the GIF very closely one can see them for maybe half a second before the real images appear. So they are there and load, but much too late.
2. I could not find any log line belonging to FFImageLoading. Does this mean that there are no errors or did I just did not find the right lines? Is there a log line which is always printed so that I can search for it? 

Thanks for taking time to look at it!

**Comment by daniel-luberda** [comment]
Do you initialize CachedImageRenderer with fast renderer option enabled or disabled? 

> I could not find any log line belonging to FFImageLoading. Does this mean that there are no errors or did I just did not find the right lines? Is there a log line which is always printed so that I can search for it?

All errors should be written to console. You can also provide your custom logger implementation via FFImageLoading custom configuration as here: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/Droid/MainActivity.cs#L35-L58

**Comment by ParticularEric** [comment]
It does not seem to matter if I initialize CacheImageRenderer with fast renderer or not. Both times exactly the same behaviour: It seems that the code does all the downloading of the images first, then showing the placeholder and immediatly afterwards showing the real images.

I tripple-checked the console, absolutely no errors regarding images.

**Comment by daniel-luberda** [comment]
Could you reproduce it with 2.3.5?

**Comment by ParticularEric** [comment]
Hi, I updated to 2.3.5 and it did not make a difference. However, I tried a few coding methods and they provided different results (the same in 2.3.4 and 2.3.5):

If I change the code inside RecipeResultStack to
```
                    byte[] b = App.MyMethod(recipeResult.imageUrl);
                    if (b == null)
                        recipeImage.Source = "recipe_error";
                    else
                        recipeImage.Source = ImageSource.FromStream(() => new MemoryStream(b));
```
the behaviour changes. The page loads much longer (from 1sec to 10sec) but then all the images are already loaded (one can see the transition from placeholder to real image immediately). I use the UserDialogs plugin to show a loadingscreen when loading a page

```
             UserDialogs.Instance.ShowLoading("", MaskType.Clear);
             Task.Run(() =>
             {
                 Device.BeginInvokeOnMainThread(async () =>
                 {
                         await Navigation.PushAsync(new MobileRecipeSearch(favorites,false));
                     UserDialogs.Instance.HideLoading();
                 });
             });
```
and the code from my first post shows the loadingscreen smoothly while the new code makes it hang completely until the load is done. I never experienced the loadingscreen completely hanging before (as if the app has 100% cpu usage).

**Comment by ParticularEric** [comment]
Hey, I just want to say that I was able to fix it. It has/had nothing to do with your plugin, rather some weird Xamarin stuff. However, the solution:

new method:
```
static List<KeyValuePair<string, CachedImage>> loadList = new List<KeyValuePair<string, CachedImage>>();
private static void LoadAndDisplayRecipeImages()
{
        foreach (KeyValuePair<string, CachedImage> x in loadList)
	{
		byte[] b =MyApp.GetRecipeImage(x.Key);
		Device.BeginInvokeOnMainThread(() =>
		{
			ImageSource source = ImageSource.FromStream(() => new MemoryStream(b));
			x.Value.Source = source;
		});
	}
}
```
RecipeResultStack:
`loadList.Add(new KeyValuePair<string, CachedImage>(recipeResult.imageUrl, recipeImage));`

And at the very end of the page constructor:
```
//Load recipe images:
if (loadList.Any())
{
	Task.Run(() =>
	{
		LoadAndDisplayRecipeImages();
	});
}
```

It now works exactly as expected, the page loads fast, shows the placeholder and one after the other turns into the real image.
