### ISSUE TITLE
Android problem versión:  

### ISSUE THREAD

**Issue by engaro** [luberda-molinet/FFImageLoading#949]
### Description

I have a problem with Android with UWP works fine.
I have:
- Xamarin.FFImageLoading.Forms (2.3.4)
- Xamarin.Forms  (2.5.122203)

Project: NET Standard 2.0

Proyect UWP:  I have added next lines and works fine

 using FFImageLoading.Forms.WinUWP;   
 CachedImageRenderer.Init();

Project Android, does not work.
using FFImageLoading.Forms.Droid;

   protected override void OnCreate(Bundle bundle)
        {
     
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            CachedImageRenderer.Init(true);
          // CachedImageRenderer.Init(enableFastRenderer: true);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App());
        }

In Xaml:

 xmlns:ff="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
  <ff:CachedImage Source="https://www.codeproject.com/KB/GDI-plus/ImageProcessing2/flip.jpg"></ff:CachedImage>

I am testing my app with Live Player.

 Error:
Default value did not match return type
Parameter name: DefaultValue (argumentexception)
 

- Version with issue: 2.3.4
- Last known good version: 
- Platform: Android

 
Thank you for your help.
Best regards,

**Comment by engaro** [comment]
Well ... the problem is because I'm using Live Play with my device ... when I use the emulator it works fine.

Any idea?

Thank you!

**Comment by daniel-luberda** [comment]
I can't help you as it's rather an issue which should be posted on LivePlay project page. But it looks like you have some older FFImageLoading files cached somewhere (Init method signature has changed some time ago)
