### ISSUE TITLE
Everything works expectedly on iOS but on Android image is not cropped.

### ISSUE THREAD

**Issue by IStep95** [luberda-molinet/FFImageLoading#951]
### Description

Everything works expectedly on iOS but on Android image is not cropped.
Device name: Samsung Galaxy S6

### Expected Behavior

Want image 75x75 in a listview.

### Actual Behavior

But on android image stays in original dimensions.
Device name: Samsung Galaxy S6

### Basic Information

Property Aspect="AspectFill" is not set on Android.
On Android emulator API 25 the same issue.
When I replace CachedImage with Xamarin.Forms.Image i get correct image 75x75. 

- Version with issue: 2.3.4.
- Platform: Android 7.0. API 24
- Device: Samsung Galaxy S6

### Reproduction Link / Code
In XAML:
![kod](https://user-images.githubusercontent.com/11096292/36594983-b7dc885e-18a0-11e8-98f5-064ec3ca2639.png)

**Comment by daniel-luberda** [comment]
Did you initialize `CachedImageRenderer` with fast renderer enabled or disabled?

**Comment by IStep95** [comment]
Thank you on fast reply. When I initialize it with CachedImageRenderer.Init(enableFastRenderer: true); Image is not cropped, but when I initialize with CachedImageRenderer.Init(enableFastRenderer: false); Image is cropped.
