### ISSUE TITLE
Question about performance and caching

### ISSUE THREAD

**Issue by VladD2** [luberda-molinet/FFImageLoading#955]
Thanx, we use your library successfully.

But we have a problem with the performance of drawing a pictures in the list during fast scrolling (call log of a phone). Images (ImageSource) are loaded in a separate thread from the streams (which are obtained from contacts of a phone).

Is it possible to get image directly from the cache with minimum of operations instead of getting it on the other task?

In particulars, we see couple of overhead operations:
- While drawing a picture additional task is created.
- There are lot of actions that burn many temporary objects that increases GC launches.

Is there an already implemented option to avoid overhead above? Or could you tell us how to do it by ourselves by point us to particular code place?

**Comment by daniel-luberda** [comment]
- If the image is already in cache no additional tasks are created. 
- If you don't use custom cache keys currently, every time before cache is used, whole stream is read and it's checksum is calculated, that leads to decreased performance
- You should use custom cache key set to contact id  to increase scrolling performance (memory cache will be used) and there would be no unnecessary stream reads

TDLR: Just implement custom cache keys and you should be fine.

**Comment by VladD2** [comment]
I'm using custom cache key factory. But still the performance is poor. I looked in your code and understood the cause of the problem. More precisely, there are two problems:

1. At work, FFImage creates a lot of temporary objects, which causes garbage collection. It leads to freezing (Mogo GC is bad), which leads to freez (frozen frames) when scrolling.

2. When a cached bitmap is available in memory, you still use async/awate. This leads to the fact that during rendering the picture is not yet there and the old picture is drawn (our list works in the recycling mode). When the image is loaded, then another redrawing occurs. I made a hack in your code and the rendering became smoother. I simply set the cahed bitmap in UI thread if  bitmap in cache.

```csharp
public static IScheduledWork Into(this TaskParameter parameters, ImageViewAsync imageView)
{
    var target = new ImageViewTarget(imageView);

    if (parameters.Source != ImageSource.Stream && string.IsNullOrWhiteSpace(parameters.Path))
    {
        target.SetAsEmpty(null);
        parameters.TryDispose();
        return null;
    }

    var task = ImageService.CreateTask(parameters, target);

    // Running in UI thread!
    var cache = Cache.ImageCache.Instance;
    var key = task.Key;
    var found = cache.Get(key);
    if (found != null)
    {
        var image = found.Item1;
        // Set cached bitmap synchronously to prevent flickering!
        target.Set(task, image, false);
        task.ImageInformation = found.Item2;
        task.Dispose();
        return null; // prevent start task
    }

    ImageService.Instance.LoadImage(task);
    return task;
}
```

But I still have problems with the GC. And my fix is hack.

I need a solution in which the cached bitmap will be applied at the it show. And I would like to be able to manage the cache myself. I would put the scaled cached bitmap into my view model and return it to image control if necessary (in event handler).

I display a call log with contact photos. And I would like it to be scrolled smoothly.
