### ISSUE TITLE
Sharpness of SVG render fluctuates with size of View

### ISSUE THREAD

**Issue by charlesroddie** [luberda-molinet/FFImageLoading#958]
The sharpness of SVG rendering depends on the size of the CachedImage.

Otherwise SVG rendering is working well in my initial tests.

### Steps to Reproduce

Take an svg with some detail that will show sharpness (e.g. text). Create a CachedImage. Vary the size of the CachedImage (width and height). Each time, load the svg.

### Expected Behavior

Sharp at all resolutions, always rendering at the actual resolution.

### Actual Behavior

For some sizes the render is sharp, and for others it is blurred. Changing the View size by a single pixel can have a large effect on sharpness. The blur is what you would expect from an image rendered at a close but different resolution and then resized, about a 0.5 pixel blur effect.

The sharpness or blur is always constant throughout each render, only varying with the size of the View.

### Basic Information

- Version with issue: 2.3.4
- Platform: UWP

### Reproduction Link / Code

```fsharp
let svgV = FFImageLoading.Forms.CachedImage(FadeAnimationEnabled = Nullable<bool>(false))
do  svgV.SizeChanged.Add(fun _ ->
    svgV.Source <- FFImageLoading.Svg.Forms.SvgImageSource.FromSvgString(svgString))
```

**Comment by daniel-luberda** [comment]
I made some changes, please let me know if it solved in upcoming release.

**Comment by charlesroddie** [comment]
That was fast! I will do that.

**Comment by charlesroddie** [comment]
@daniel-luberda Do you know when the next release will be?

**Comment by daniel-luberda** [comment]
It's already released as a prerelease

**Comment by charlesroddie** [comment]
It didn't immediately but I managed to fix this issue. Describing here in case anyone else has the same problem when maintaining an aspect ratio. Here is what I think is happening:

FFImageLoading is using the height of the View to determine the resolution to render at. (Only tested in the case when height < width).

I was taking the width as given (by Xamarin.Forms caluclations) and setting the height. For a given width, the right height for that aspect ratio may not be an integer. Therefore the View height may be too large or too small. (The View height seems to act as if it were an integer, a rounded version of its floating point value - but haven't tested this thoroughly.)

If the height is too small, FFImageLoading renders to this height and a lower width than the View width. With Aspect.AspectFill set, Xamarin.Forms then scales up the images, causing blur. With Aspect.AspectFit set, there is no scaling and no blurriness.

If the height is too large, FFImageLoading renders to this height and a greater width than the View width. With Aspect.AspectFit set, X.F scales down the images, causing blur. With Aspect.AspectFill, then there is no scaling or blurriness.

The fix is therefore to make sure that the height is rounded up (ceiling) with Aspect.AspectFill set, or rounded down (floor) with Aspect.AspectFill set. A normal rounding only works half of the time with either Aspect.

**Comment by charlesroddie** [comment]
FFImageLoading must know the width and height of its View in pixels, and these are integers. Any rendering of svgs must be to these pixels and should therefore be sharp. I assume these are the case already.

The problem is therefore that there is scaling happening somewhere. And this scaling is not based on pixels when rendering and current pixels. It is using true image dpi or View height and width and is running into rounding errors as a result.

@daniel-luberda Does this analysis make sense? And can we reopen this issue please?

**Comment by daniel-luberda** [comment]
Here, svg image size is calculated: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SvgDataResolver.cs#L123-L162

```C#
double sizeX = 0;
double sizeY = 0;

if (VectorWidth <= 0 && VectorHeight <= 0)
{
    if (picture.CullRect.Width > 0)
        sizeX = picture.CullRect.Width;
    else
        sizeX = 300;

    if (picture.CullRect.Height > 0)
        sizeY = picture.CullRect.Height;
    else
        sizeY = 300;
}
else if (VectorWidth > 0 && VectorHeight > 0)
{
    sizeX = VectorWidth;
    sizeY = VectorHeight;
}
else if (VectorWidth > 0)
{
    sizeX = VectorWidth;
    sizeY = (VectorWidth / picture.CullRect.Width) * picture.CullRect.Height;
}
else
{
    sizeX = (VectorHeight / picture.CullRect.Height) * picture.CullRect.Width;
    sizeY = VectorHeight;
}

if (UseDipUnits)
{
    sizeX = sizeX.DpToPixels();
    sizeY = sizeY.DpToPixels();
}

lock (_encodingLock)
{
    using (var bitmap = new SKBitmap(new SKImageInfo((int)sizeX, (int)sizeY)))

    // ..........
}
```

Then after this, the only place where scaling can occur (FFImageLoading side) is downsampling (if it's enabled). Any thoughts?

**Comment by charlesroddie** [comment]
OK. The bitmap has approximately the true aspect ratio and the resolution should be similar to the pixels in the View. Can we find the pixels in the view directly as an int or must that be achieved by this calculation?

It would be better to make sizeX and sizeY integers, as they are intended to represent the resolution of the bitmap. The subsequent code looks wrong when sizeX is not an int.
```
float scaleX = (float)sizeX / picture.CullRect.Width;
float scaleY = (float)sizeY / picture.CullRect.Height;
```

**Comment by daniel-luberda** [comment]
> Can we find the pixels in the view directly as an int or must that be achieved by this calculation?

FFImageLoading must work for all cases and there might be a case where view is in different size / asoect ratio than image, so IMO we can't use direct values from a view. Also some views are expandable and don't have any fixed size (or only one is specified)

> It would be better to make sizeX and sizeY integers, as they are intended to represent the resolution of the bitmap. The subsequent code looks wrong when sizeX is not an int.

There are already integers, casting is only done for a better divide precision.

**Comment by charlesroddie** [comment]
OK so we have to make sure that our approximation is identical to Xamarin.Forms.

Re: ints. Am I missing something? `sizeX` has type double:
```
double sizeX ... 
```
I don't know whether `VectorWidth` is an int but here it seems clear that `sizeX` is a double which may have a fractional part:
```
sizeY = (VectorWidth / picture.CullRect.Width) * picture.CullRect.Height;
```
Then a bitmap is created based on `(int)sizeX` which is different from `sizeX` not only in type but also in value.

**Comment by daniel-luberda** [comment]
> I don't know whether VectorWidth is an int but here it seems clear that sizeX is a double which may have a fractional part

`VectorWidth` / `VectorWidth` are ints

> Then a bitmap is created based on (int)sizeX which is different from sizeX not only in type but also in value.

SkiaSharp can only accept int values, that's the reason I use cast.

**Comment by charlesroddie** [comment]
Why isn't it more correct to start with:
```
int sizeX = 0;
int sizeY = 0;
```
So that these represent the number of pixels in the image? At the moment these quantities represent a floating point number which is close to the number of pixels in the image.

It's probable this isn't the core issue though.

When the bitmap is created the predicted number of pixels is used, but these are based on castings to ints. Castings to ints have to happen somewhere, but these are done by truncation. I do not know how Xamarin Forms does this. Truncation or rounding?

If it's not possible to render a bitmap in a View 1:1 (i.e. force Xamarin Forms not to scale the image), then we need to get the identical approximation to Xamarin.Forms.

**Comment by daniel-luberda** [comment]
Could you try newest release? This commit could solve your issue: https://github.com/luberda-molinet/FFImageLoading/commit/7b14b064c4d682dedfea4b8f4ef1dc81bf77ff7e

**Comment by mclillill** [comment]
We also have this problem. Xamarin.FFImageLoading.Svg Version 2.4.3.840
Images are from IPhoneSimulator but on devices it's the same.
It's seems it's only like this the first time the image loads. If I replace the Source then the image is sharp.

![unbenannt](https://user-images.githubusercontent.com/37399504/41283059-e492579e-6e35-11e8-8a42-988eda87de4e.png)
Replaced source:
![unbenannt1](https://user-images.githubusercontent.com/37399504/41283060-e4ac6fa8-6e35-11e8-851e-d566c026b7d3.PNG)

**Comment by daniel-luberda** [comment]
Did you try to set FIXED image view size?

**Comment by mclillill** [comment]
Thanks for the quick reply.
I set:
```xaml			
WidthRequest="20.45" 
HeightRequest="20" 
```
Is this what you mean by fixed size?

**Comment by matibak** [comment]
> Thanks for the quick reply.
> I set:
> 
> ```
> WidthRequest="20.45" 
> HeightRequest="20" 
> ```
> 
> Is this what you mean by fixed size?
I made it by using `Margin` instead of `WidthRequest`, and `HeightRequest`
