### ISSUE TITLE
Http Cache

### ISSUE THREAD

**Issue by rudacs** [luberda-molinet/FFImageLoading#959]
Hello,

I have a problem is that when the image changes on the server the application is not updated because it does not check on the server if the file is the newest one.

I need it to take the file from the disk and make a request on the server asking if it has a new file. If it has it update the disk and it shows on the screen. If it has no change it updates the expiration date of the file.

**Comment by molinch** [comment]
@rudacs Currently that's not how the app works: it just downloads based on URL and caches for the time you define in the configuration.

But I think you could overcome this by using LoadFromStream and some custom code. Might be complicated though.
@daniel-luberda Any hint on this?

**Comment by daniel-luberda** [comment]
@rudacs I implemented http header `MaxAge` support, it'll be used if no other custom duration is set (and available)
