### ISSUE TITLE
CachedImage.Cancel() doesn't always prevent Finish event to be fired

### ISSUE THREAD

**Issue by Nico04** [luberda-molinet/FFImageLoading#962]
### Description
I'm using CachedImage as a Xamarin.Forms component to show a MJPEG stream.
I'm subscribed to the "Finish" event to unhide the component at the last moment (an activity indicator is shown before that).
In some case I need to cancel all current operations to start a new one, so I use CachedImage.Cancel() to prevent the Finish event to be fired if an image is currently being processed by CachedImage (after set in Source).
In most cases it works fine, but in some cases the Finish event **is still fired up** and it messed up my cod*.

And because I can't guess which image is firing up Finish after I set Source (from a byte[]), I can't filter that extra non-desired event.

Do you have any clues ?

### Basic Information
- Version with issue: v2.3.4
- Platform: Xamarin.Forms / Android

**Comment by Nico04** [comment]
After further digging, I found that when Finish is unwantedly fired, Source is null.
But I also found that maybe I'm just looking for the Success event instead, can someone please explain me the technical difference please ?

**Comment by molinch** [comment]
I could be wrong but if the task is already running I don't think it's canceled.
@daniel-luberda could you confirm?

**Comment by daniel-luberda** [comment]
@Nico04 Task is cancelled when running too. What `Cancel` method does is invoking `Cancel` method of current task's `CancellationTokenSource`. 

Eg. see this file: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Common/Work/ImageLoaderTask.cs

and search for `ThrowIfCancellationRequested();`

Callbacks:

- `Error` is called when error occurs
- `Success` is only called when image loading tasks end without any errors
- `Finish` is always called even when any error occurs. 

**Task cancellation is also an error.**
