### ISSUE TITLE
Xamarin.Forms Android rotating iOS camera photos

### ISSUE THREAD

**Issue by cocoretch** [luberda-molinet/FFImageLoading#963]
### Description

My app is sending photos to server and getting these photos into the application. But when I send a photo which is taken from iOS camera it is proper shape on iOS devices and saved properly to server. But in android FFIMAGELOADING rotating these photo 90 degrees to the left.

### Expected Behavior

Android FFIMAGELOADING.FORMS shouldn't rotate these images should understand there is no need to rotate. 

### Actual Behavior

FFIMAGELOADING.FORMS cannot read photos exif information properly in Android it cannot understand is it rotated or not if photo taken by iOS camera. If photo taken by iOS camera FFIMAGELOADING says: "this photo is not in proper shape i have to rotate it" when it reads the exif information of photo.

### Basic Information

- Version with issue: v2.3.4
- Platform: Android

### Screenshots

https://i.hizliresim.com/QVzk3A.jpg

As you see there is keyboard on photo but its rotated. This photo uploaded in portrait shape.

**Comment by daniel-luberda** [comment]
Fixed

**Comment by sinappsys** [comment]
hi @daniel-luberda 
when will the new release with this fix come out?
Thanks

**Comment by viveklpu2011** [comment]
getting my third list image rotated left 90 degree, any help on this
