### ISSUE TITLE
FFImageLoading Error

### ISSUE THREAD

**Issue by JonathanLewis09** [luberda-molinet/FFImageLoading#964]
### Description

im working with CahedImage in a listView but the second time i navigate to this page the image is not showing 

DllImport loaded library '/system/lib/liblog.so'.
Image loading failed: E00743F983EBECC522D087F6CB4E80C503-06 10:39:55.719 D/Mono    (22946): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').

03-06 10:39:55.719 D/Mono    (22946): Searching for '__android_log_print'.System.NullReferenceException: Object reference not set to an instance of an object.
  at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].ProcessRemoval (TValue value, System.Boolean evicted) [0x00030] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:235 
  at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].Remove (System.String key, System.Boolean evicted) [0x0005f] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:383 
  at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].Add (System.String key, TValue value) [0x00078] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:349 
  at FFImageLoading.Cache.ImageCache`1[TValue].Add (System.String key, FFImageLoading.Work.ImageInformation imageInformation, TValue bitmap) [0x00059] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ImageCache.cs:171 
  at FFImageLoading.Work.ImageLoaderTask`3+<RunAsync>d__10

03-06 10:39:55.719 D/Mono    (22946): Probing '__android_log_print'.8[TDecoderContainer,TImageContainer,TImageView].MoveNext () [0x0056e] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:564 

03-06 10:39:55.719 D/Mono    (22946): Found as '__android_log_print'.
03-06 10:39:55.720 I/mono-stdout(22946): Image loading failed: E00743F983EBECC522D087F6CB4E80C5
03-06 10:39:55.723 I/mono-stdout(22946): System.NullReferenceException: Object reference not set to an instance of an object.
03-06 10:39:55.723 I/mono-stdout(22946):   at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].ProcessRemoval (TValue value, System.Boolean evicted) [0x00030] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:235 
03-06 10:39:55.723 I/mono-stdout(22946):   at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].Remove (System.String key, System.Boolean evicted) [0x0005f] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:383 
03-06 10:39:55.724 I/mono-stdout(22946):   at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].Add (System.String key, TValue value) [0x00078] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:349 
03-06 10:39:55.724 I/mono-stdout(22946):   at FFImageLoading.Cache.ImageCache`1[TValue].Add (System.String key, FFImageLoading.Work.ImageInformation imageInformation, TValue bitmap) [0x00059] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ImageCache.cs:171 
03-06 10:39:55.724 I/mono-stdout(22946):   at FFImageLoading.Work.ImageLoaderTask`3+<RunAsync>d__108[TDecoderContainer,TImageContainer,TImageView].MoveNext () [0x0056e] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:564 

im read the images from a sqlite data 
 byte[] binaryData = Convert.FromBase64String(Activo.ImagenActivo);
 imgArticulo.Source = ImageSource.FromStream(() => new MemoryStream(binaryData));

if i change the Cached image for Image it works fine but not supot more than 10 images that is why i try with this 

sorry for mi bad english

**Comment by daniel-luberda** [comment]
It should be fixed in upcoming release.

**Comment by daniel-luberda** [comment]
Please use newest prerelease.
