### ISSUE TITLE
SVG not render properly

### ISSUE THREAD

**Issue by SergioBarbosa** [luberda-molinet/FFImageLoading#966]
### Description

I can´t make a svg render properly with a svg exported from sketch

### Expected Behavior

![image](https://user-images.githubusercontent.com/1131800/37126129-7d1b126e-2267-11e8-85e1-40307bef9edb.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/1131800/37126166-a6729d30-2267-11e8-86a7-faee3b425d92.png)

### Basic Information

the svg source is here
`<?xml version="1.0" encoding="UTF-8"?>
<svg width="52px" height="38px" viewBox="0 0 52 38" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>Page 1</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="conta" transform="translate(-664.000000, -617.000000)" fill="#00A0E9">
            <path d="M672.272727,647.727273 L688.818182,647.727273 C689.470545,647.727273 690,647.199 690,646.545455 C690,645.893091 689.470545,645.363636 688.818182,645.363636 L672.272727,645.363636 C671.620364,645.363636 671.090909,645.893091 671.090909,646.545455 C671.090909,647.199 671.620364,647.727273 672.272727,647.727273 L672.272727,647.727273 Z M672.272727,643 L693.545455,643 C694.197818,643 694.727273,642.471727 694.727273,641.818182 C694.727273,641.165818 694.197818,640.636364 693.545455,640.636364 L672.272727,640.636364 C671.620364,640.636364 671.090909,641.165818 671.090909,641.818182 C671.090909,642.471727 671.620364,643 672.272727,643 L672.272727,643 Z M666.363636,624.090909 L713.636364,624.090909 L713.636364,619.363636 L666.363636,619.363636 L666.363636,624.090909 Z M666.363636,652.454545 L713.636364,652.454545 L713.636364,633.545455 L666.363636,633.545455 L666.363636,652.454545 Z M713.636364,617 L666.363636,617 C665.058909,617 664,618.058909 664,619.363636 L664,652.454545 C664,653.759273 665.058909,654.818182 666.363636,654.818182 L713.636364,654.818182 C714.941091,654.818182 716,653.759273 716,652.454545 L716,619.363636 C716,618.058909 714.941091,617 713.636364,617 L713.636364,617 Z M703,647.727273 L707.727273,647.727273 C708.379636,647.727273 708.909091,647.199 708.909091,646.545455 L708.909091,641.818182 C708.909091,641.165818 708.379636,640.636364 707.727273,640.636364 L703,640.636364 C702.347636,640.636364 701.818182,641.165818 701.818182,641.818182 L701.818182,646.545455 C701.818182,647.199 702.347636,647.727273 703,647.727273 L703,647.727273 Z" id="Page-1"></path>
        </g>
    </g>
</svg>`

maybe it's an error from parser?

**Comment by charlesroddie** [comment]
Can you cut this until you find the simplest string that renders incorrectly?
