### ISSUE TITLE
How to declare ImageService in .NetStandard2.0 XF?

### ISSUE THREAD

**Issue by biapar** [luberda-molinet/FFImageLoading#968]
How to declare ImageService in .NetStandard2.0 XF?

**Comment by biapar** [comment]
var config = new FFImageLoading.Config.Configuration()
            {
                VerboseLogging = false,
                VerbosePerformanceLogging = false,
                VerboseMemoryCacheLogging = false,
                VerboseLoadingCancelledLogging = false,
                Logger = new CustomLogger(),
                DownsampleInterpolationMode = FFImageLoading.Work.InterpolationMode.High,
                FadeAnimationForCachedImages = false,
                FadeAnimationDuration = 250,
                FadeAnimationEnabled = false
            };

            FFImageLoading.ImageService.Instance.Initialize(config);

**Comment by daniel-luberda** [comment]
Please provide all necessary informations (issue template), as I don't know what the question is and reopen. Thanks.
