### ISSUE TITLE
FFImageLoading Xamarin.Forms sample for .Net Standard 2.0

### ISSUE THREAD

**Issue by abrasat** [luberda-molinet/FFImageLoading#971]
Would be please possible to add a sample Xamarin.Forms project (IoS, Droid, UWP) for VS 2017, where FFImageLoading is used from a .NetStandard 2.x library ?
Thx for help.

**Comment by daniel-luberda** [comment]
FFImageLoading supports .NET Standard  >= 1.0 - just be sure you install all packages (There are some informations, that Visual Studio doesn't install it sometimes, but that's not an FFImageLoading issue). You don't need to do anything else.
