### ISSUE TITLE
SimpleDiskCache ClearAsync exception

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#975]
I am seeing this exception in my stacktrace sometimes. Do you know what it is related to? Exception is thrown on this line  await `FFImageLoading.ImageService.Instance.InvalidateCacheAsync(FFImageLoading.Cache.CacheType.All);`
```

SimpleDiskCache+<ClearAsync>d__16.MoveNext ()
System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/user/0/myapp.myapp/cache/FFSimpleDiskCache'.
__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath)
FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path)
FileSystemEnumerableIterator`1[TSource].CommonInit ()
System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) [0x000d6] in :0
FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost)
Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost)
Directory.InternalGetDirectories (System.String path, System.String searchPattern, System.IO.SearchOption searchOption)
Directory.GetDirectories (System.String path)
Directory.RecursiveDelete (System.String path)
Directory.Delete (System.String path, System.Boolean recursive)
SimpleDiskCache+<ClearAsync>d__16.MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
ImageServiceBase`1+<InvalidateCacheAsync>d__46[TImageContainer].MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
TaskAwaiter.GetResult ()
Page+<OnDisappearing>d__10.MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.e1cae9d1-f90d-4a2e-9e85-5d549c933fbf(intptr,intptr)
```

**Comment by daniel-luberda** [comment]
The error is self explanatory: `System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/user/0/myapp.myapp/cache/FFSimpleDiskCache'` but I don't know its cause. Are removing that dir on your own? Maybe the device is low on hdd space and removes caches automatically?

**Comment by EmilAlipiev** [comment]
I didnt move myself. it is from my users on production but yes i think that it could be something to do with low disk space. or could it be about storing in the sd card and umounting sd card?

**Comment by daniel-luberda** [comment]
Could be both cases. FFImageLoading reads all disk cache entries when lib is first used, if the file was deleted by eg. OS, it won't notice that file is missing.

**Comment by EmilAlipiev** [comment]
ok i would just ignore this now. thank you for information

**Comment by EmilAlipiev** [comment]
hi @daniel-luberda , just coming back to this issue because i was able to reproduce myself. It seems like that it occurs on low disk space but I am curious why should it be matter to have low disk when it is crashing on InvalidateCacheAsync ? because I am wiping out all cache, not trying to store anything.

**Comment by daniel-luberda** [comment]
It may be both. Pushed a fix.

**Comment by ornolisvt** [comment]
Recently this problem has also occurred in my android app. It was reported in Alcatel U5 with Android 6.0, the trace

FileSystemEnumerator`1[TResult].FindNextEntry (System.Byte* entryBufferPtr, System.Int32 bufferLength)
FileSystemEnumerator`1[TResult].MoveNext ()
SimpleDiskCache.InitializeEntries ()
FFImageLoading.Cache.SimpleDiskCache..ctor (System.String cachePath, FFImageLoading.Config.Configuration configuration) [0x00082] in <e4a68679a2a44c4694e04140bb609f9a>:0
ImageService.CreatePlatformDiskCacheInstance (FFImageLoading.Config.Configuration configuration)
ImageServiceBase`1[TImageContainer].InitializeIfNeeded (FFImageLoading.Config.Configuration userDefinedConfig)
ImageServiceBase`1[TImageContainer].get_Config ()
ImageCache.get_Instance ()
ImageService.get_MemoryCache ()
ImageServiceBase`1[TImageContainer].InvalidateMemoryCache ()
MainApplication.OnTrimMemory (Android.Content.TrimMemory level)
Application.n_OnTrimMemory_I (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 native_level)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.4(intptr,intptr,int)

My method in MainApplication

 ```
public override void OnTrimMemory([GeneratedEnum] TrimMemory level)
        {
            ImageService.Instance.InvalidateMemoryCache();
            GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
            base.OnTrimMemory(level);
        }
```
