### ISSUE TITLE
Xamarin.Forms project, with xaml pages in NetStandard 2 class library: how to use ImageSourceConverter ?

### ISSUE THREAD

**Issue by abrasat** [luberda-molinet/FFImageLoading#976]
I have a Xamarin.Forms project, where the xaml pages are located in a NetStandard 2 class library.
Where exactly (in which directory) must the *.jpg files be located in the NetStandard project (as embedded resources), to be found when using the ImageSourceConverter ? Is there any sample available about how to use the ImageSourceConverter ?

The *.xaml file from the NetStandard library looks for instance like this:

```
...
<ContentPage.Resources>
	<ResourceDictionary>
		<ffimageloading:ImageSourceConverter x:Key="ImageSourceConverter"></ffimageloading:ImageSourceConverter>
	</ResourceDictionary>
</ContentPage.Resources>

<StackLayout VerticalOptions="Center" HorizontalOptions="Center">
	<ffimageloading:CachedImage WidthRequest="100" HeightRequest="100" DownsampleToViewSize="true" Source="{Binding ImageUrl, Converter={StaticResource ImageSourceConverter}}">
	</ffimageloading:CachedImage>
</StackLayout>
...
```

The ImageUrl property is set in the view model and should be correctly bound to the Source element of the CachedImage.

**Comment by daniel-luberda** [comment]
Images must be located in a platform specific manner, `Resources` folder for iOS, `Drawables` on Android, etc. If you want to share the same images among all platforms, you must use net embedded resources build type: https://github.com/luberda-molinet/FFImageLoading/wiki/Data-URL-&-Embedded-Resources-support-(including-base64)

**Comment by abrasat** [comment]
Thx for reply. Do you have some samples about how to use net embedded resources to bind the Source property of a CachedImage to a view model property ?
