### ISSUE TITLE
AspectFill => RoundedTransformation ignored

### ISSUE THREAD

**Issue by CNDOGTA** [luberda-molinet/FFImageLoading#977]
When I use a RoundedTransformation on an Image With AspectFill, then the transformation is ignored.

**Comment by daniel-luberda** [comment]
- It's not ignored - please make sure your image is a square
- If it's not a square, set `CropWidthRatio`/`CropHeightRatio ` properties to your custom aspect.

**Comment by FrancoisM** [comment]
(switching to my proper account)

No my image is not a square.
Can't find in the docs what these ratios mean?
I dont know any ratios of my images. It can be any.
The image is within a grid cell whose height is fixed and whose width is a multiple of *. I want to keep the image aspect (hence AspectFill) while rounding the corners. I had a custom renderer doing it but as I migrate to FFImageLoading I can't use it anymore.

Tks for the gr8 library btw.

**Comment by fatfatson** [comment]
same problem. without knowing the aspect, just want to fill the parent view and keep aspect and make round corner.
