### ISSUE TITLE
SvgCachedImage - Update bindable source from PCL resources not working?

### ISSUE THREAD

**Issue by frode** [luberda-molinet/FFImageLoading#978]
### Description

Does SvgCachedImage support loading new svg images from bindable source?

First value initially works, but if I change the binding source value to a new source svg, it does not update.

### Steps to Reproduce

View Model:

```
ToggleTorchCommand = new Command(()=> IsTorchOn = !IsTorchOn );

public string TorchIcon => IsTorchOn ? "resource://AppName.Resources.ic_flash_off_black_48px.svg" : "resource://AppName.Resources.ic_flash_on_black_48px.svg";
```

XAML:

```
</Grid.ColumnDefinitions>
 <svg:SvgCachedImage Grid.Row="0" Grid.Column="1"  Source="{Binding TorchIcon}" HeightRequest="38" WidthRequest="38">
    <svg:SvgCachedImage.GestureRecognizers>
    <TapGestureRecognizer Command="{Binding ToggleTorchCommand}" NumberOfTapsRequired="1"  />
   </svg:SvgCachedImage.GestureRecognizers>
</svg:SvgCachedImage>
```

### Expected Behavior

When ToggleTorchCommand is called, the value of TorchIcon changes, and so should TorchIcon reflect the new bindable source svg update on UI.

### Actual Behavior

Image never update, only renders initial set svg image from source.

### Basic Information

- Version with issue: 2.3.4
- Last known good version: None
- Platform: Xamarin Forms v2.5.0.280555 (Android, iOS)

**Comment by daniel-luberda** [comment]
It's not FFImageLoading related. Please make sure your view model implements correctly `INotifyPropertyChanged` for that property. After that, it will work fine.

**Comment by frode** [comment]
Thank you, I was missing one line of code..

Changes to IsTorchOn must notify that the TorchIcon is changing too!

```
public bool IsTorchOn
 {
     get { return isTorchOn; }
     set
	{
	     if (isTorchOn == value) return;

	      isTorchOn = value;
	      OnPropertyChanged(nameof(IsTorchOn));
	      OnPropertyChanged(nameof(TorchIcon)); <--- this was missing
	}
  }
```
