### ISSUE TITLE
Cannot load svg from resource of the forms library

### ISSUE THREAD

**Issue by CNDOGTA** [luberda-molinet/FFImageLoading#979]
The following from the docs

		<ffimageloadingsvg:SvgCachedImage WidthRequest="200" HeightRequest="200" Source="resource://myresourcepath.svg"/> 

doesn't work and the output says:

> Unable to retrieve image data from source: resource://myresourcepath.svg. Only http or https scheme is allowed

Note: my forms library is not a pcl but .net standard.

**Comment by daniel-luberda** [comment]
- Please make sure you installed all necessary packages in every project (FFImageLoading.Svg && FFImageLoading.Svg.Forms)
- Please provide you test platform
- Please provide a repo

**Comment by frode** [comment]
@FrancoisM Do you have NuGet reference to both?

`<PackageReference Include="Xamarin.FFImageLoading.Svg.Forms" Version="2.3.4" /><PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.3.4" />`

**Comment by daniel-luberda** [comment]
Also: 

`<PackageReference Include="Xamarin.FFImageLoading.Svg" Version="2.3.4" />`

**Comment by FrancoisM** [comment]
I had 

```
<ItemGroup>
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.3.4" />
    <PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.3.4" />
    <PackageReference Include="Xamarin.FFImageLoading.Svg.Forms" Version="2.3.4" />
    <PackageReference Include="Xamarin.Forms" Version="2.5.0.280555" />
  </ItemGroup>
```

Trying now with

```
<ItemGroup>
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.3.4" />
    <PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.3.4" />
    <PackageReference Include="Xamarin.FFImageLoading.Svg" Version="2.3.4" />
    <PackageReference Include="Xamarin.FFImageLoading.Svg.Forms" Version="2.3.4" />
    <PackageReference Include="Xamarin.Forms" Version="2.5.0.280555" />
  </ItemGroup>
```

Same result :-(

Here is my appdelegate

**Comment by frode** [comment]
@FrancoisM Could you try this for init:

```
var svgAssembly = typeof(SvgCachedImage).GetTypeInfo().Assembly;
CachedImageRenderer.Init();
```

**Comment by FrancoisM** [comment]
Note: I tried without Gorilla, same issue (although the error message is slightly different):

> Image loading failed: ressource://myNameSpace.photo-camera.svg;(size=0x0,dip=True)
> FFImageLoading.DownloadAggregateException: One or more errors occurred. ---> System.ArgumentException: Only http or https scheme is allowed

I also tried:
```
var svgAssembly = typeof(SvgCachedImage).GetTypeInfo().Assembly;
CachedImageRenderer.Init();
```

however it didn't work.

**Comment by frode** [comment]
ressource://myNameSpace.photo-camera.svg;(size=0x0,dip=True)

should it be resource://myNameSpace.photo-camera.svg ? one s

**Comment by frode** [comment]
Did you try to create a folder in the PCL project named "Resources" add the photo-camera.svg and set build action to "EmbeddedResource" and reference it?

**Comment by FrancoisM** [comment]
aahhhhh!!!! My bad english!
Correcting the typo still gives me (and I copy/paste from the console output):

> Unable to retrieve image data from source: resource://************.photo-camera.svg. Only http or https scheme is allowed .....

**Comment by frode** [comment]
@FrancoisM Check my comment above..

**Comment by FrancoisM** [comment]
It's not a PCL bt a net standard library.
I have included the svg as embedded resource but without putting it into a dedicated folder (why should I?) but I'll try.

**Comment by frode** [comment]
It shouldnt make a difference between pcl/shared project, its similar project/solution structure.

You probably have something like:
MyApp.SharedProject
MyApp.AndroidProject
MyApp.iOSProject
Etc..

Give it a try, and remember to use that path structure i gave as an example..

**Comment by FrancoisM** [comment]
I get your question now. You want me to add the svg in the main xamarin forms library, the one that set the MainPage. I've tried that already but I had the same result. I'll try once more to be sure.

**Comment by FrancoisM** [comment]
I have:
MyProject.App
MyProject.App.Views
MyProject.App.iOS
MyProject.App.Droid

MyPage.xaml is within MyProject.App.Views. I do MainPAge = new MyPage() within MyProject.App.
Both MyProject.App.Views and MyProject.App.iOS reference all the nuget packages.

I tried both:
Source="resource://MyApp.App.Views.Resources.file.svg" with file.svg as en embeded resource within a folder called Resources in MyApp.Views

as well as
Source="resource://MyApp.App.Resources.file.svg" with file.svg as en embeded resource within a folder called Resources in MyApp

It didn't work in both case.

I'll put together a repro project to share here.

**Comment by frode** [comment]
Yes, better put up a project to share.. 

A tip, you only need to reference the NuGet packages once, from the MyProject.App project.

These two references is all you need:

`<PackageReference Include="Xamarin.FFImageLoading.Svg.Forms" Version="2.3.4" /><PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.3.4" />`

**Comment by FrancoisM** [comment]
Ok I made it work

1°) it doesn't work when the svg is within the resources of the views project. The error message is clear and says that it is looking in the main assembly. I couldn't see that error while using Gorilla

> System.IO.FileNotFoundException: resource://MyProject.App.Views.Resources.photo-camera.svg?assembly=MyProjecy.App

2°) it doesn't work with Gorilla. When I first tried without it I was in case 1 and concluded I had the same problem without looking at the actual error message which is different. So, with the svg as a resource of the main library, and without Gorilla, it is working fine.

I still need to make it work with Gorilla as I cannot work without it lol

Anyway, thanks a lot for your reactivity and the great libraries!

**Comment by daniel-luberda** [comment]
Thanks, for the info. You ca provide assembly manually, read more here: https://github.com/luberda-molinet/FFImageLoading/wiki/Data-URL-&-Embedded-Resources-support-(including-base64)#embedded-resources-uri-support

@FrancoisM  You could make an issue on gorilla player's project page :)

**Comment by FrancoisM** [comment]
@daniel-luberda I did ;-)
