### ISSUE TITLE
parts of svg are not rendered

### ISSUE THREAD

**Issue by abenedykt** [luberda-molinet/FFImageLoading#980]
### Description
Tried to display SVG in Xamarin.Forms (4.9.0.752) VS 15.6.3 

Unfortunelty the graphic is rendered only partially. 

### Steps to Reproduce

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
             x:Class="Pages.StartupPage">
    <ContentPage.Content>
        <StackLayout>
            <StackLayout>
                <ffimageloadingsvg:SvgCachedImage WidthRequest="400" HeightRequest="400" Source="test.svg"/>
            </StackLayout>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

### Expected Behavior

SVG to be displayed properly

### Actual Behavior

Only some parts of svg are rendered
[failing svg example.zip](https://github.com/luberda-molinet/FFImageLoading/files/1830377/failing.svg.example.zip)

### Basic Information

- Version with issue: 
Xamarin.FFImageLoading.Forms 2.3.4
Xamarin.FFImageLoading.Svg.Forms 2.3.4
amarin.FFImageLoading.Transformations 2.3.4
Xamarin.Forms 2.4.0.91020
- Platform: Both iOS and Android

### Screenshots
source image and screenshot from the device
[failing svg example.zip](https://github.com/luberda-molinet/FFImageLoading/files/1830383/failing.svg.example.zip)

**Comment by abenedykt** [comment]
I've narrowed it a bit. It looks like that changing root of the tree (in svg) to solid colors does the trick. It appears that my gradients are not rendered

**Comment by daniel-luberda** [comment]
Cześć @abenedykt :)

It works if I replace: 

```XML
<use xlink:href="#path0_fill" transform="translate(-1854 -1429.6)" fill="url(#paint0_linear)" />
```
with
```XML
<use xlink:href="#path0_fill" transform="translate(-1854 -1429.6)" fill="#444444" />
```

so it leads us to LinearGradient handling - I'll need to investigate it further. The code is here: 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SkSvg.cs#L1277-L1295

and 

https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SkSvg.cs#L376-L394

**Comment by abenedykt** [comment]
Czołem Daniel :) 

Awesome. I can confirm that the full image with fill changed to fill="#444444" works. SVG-s were exported by Figma (from project made in Sketch )
