### ISSUE TITLE
SVG external assembly

### ISSUE THREAD

**Issue by Spookenator** [luberda-molinet/FFImageLoading#982]
### Description

I have a Xamarin Forms standard project and I would like to leverage svg's. Acording to the documentation I should be able to leverage an external assembly for referencing my files. 

> When loading from embedded resources, you can specify different assembly with following format: resource://FFImageLoading.Forms.Sample.Resources.sample.svg?assembly=[ASSEMBLY FULL NAME]

I created an .net standard library and marked all the svg files as embedded resources. I reference the external library but i am not seeing anything on the screen.

    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 xmlns:local="clr-namespace:ASHT"
                 xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
                 x:Class="ASHT.MainPage">
    
        <ffimageloadingsvg:SvgCachedImage WidthRequest="200" HeightRequest="200" Source="resource://Xamarin.FontAwesome.amazon.svg?assembly=Xamarin.FontAwesome"/>
    
    </ContentPage>

Am i doing something wrong?

**Comment by daniel-luberda** [comment]
Yes,

`Xamarin.FontAwesome` is not a valid assembly name. You need to specify full assembly name: https://stackoverflow.com/questions/658446/how-do-i-find-the-fully-qualified-name-of-an-assembly

**Comment by Spookenator** [comment]
Xamarin.FontAwesome is my external Assembly name?

**Comment by daniel-luberda** [comment]
I sent you a link how to get a full assembly name : https://stackoverflow.com/questions/658446/how-do-i-find-the-fully-qualified-name-of-an-assembly

**Comment by Spookenator** [comment]
Thank you. I originally didn't understand what you meant, but i loaded the assembly.
It works fine now!
