### ISSUE TITLE
Trying to load From NetStandard 2.0 Library "PCL" EmbeddedResource 

### ISSUE THREAD

**Issue by CarLoOSX** [luberda-molinet/FFImageLoading#983]
### Description

Hello, I'm unable to load Sample.svg from Sample code. My "PCL" is type of NetStandard Library 2.0.
I have added a folder called Resources and inside it I added the sample svg from the sample project selecting the image as EmbeddedResource.

PD: I'm also using native forms.
### Expected Behavior

I do this in XAML             

```
    xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms">

<ffimageloadingsvg:SvgCachedImage
                WidthRequest="200"
                HeightRequest="200"
                Source="resource://MyProject.Resources.Sample.svg" />
```
And it should show the image in 200x200

### Actual Behavior

Nothing happens

### Basic Information

- Version with issue: 2.3.4
- Last known good version: I used ffimageloading in native projects and Forms PCL projects.
- Platform: iOS but I suppose Android too.

**Comment by daniel-luberda** [comment]
- Is SVG located in the same assembly as your app? 
- Can you provide FFImageLoading console error output?

**Comment by CarLoOSX** [comment]
Well I have added to my iOS project this library ( working with binding etc ) as a reference. 

How can I see the console log ??

**Comment by CarLoOSX** [comment]
Yes is in the same assembly. I'm trying to load the svg in my NetStandardLibrary from a view in xaml which is in the same Library. I Also have this nugget packages in the library and in the iOS project.
![captura de pantalla 2018-03-22 a las 17 18 45](https://user-images.githubusercontent.com/9008334/37783196-2ca44640-2df5-11e8-9f14-4ab72732eec8.png)
![captura de pantalla 2018-03-22 a las 17 19 02](https://user-images.githubusercontent.com/9008334/37783197-2cbe7330-2df5-11e8-93dd-f0f100812c82.png)

**Comment by CarLoOSX** [comment]
Thank you!

**Comment by daniel-luberda** [comment]
> How can I see the console log ??

When you debug your app you can see console output, if there is any FFImageLoading error, it's there.


You must ensure that  `Sample.svg` build action is set to `EmbeededResource` ans the file is in the same assembly as your views, otherwise you need to specify assembly manually: https://github.com/luberda-molinet/FFImageLoading/wiki/Data-URL-&-Embedded-Resources-support-(including-base64)#embedded-resources-uri-support

**Comment by nexussays** [comment]
I seem to be having the same issue. Exact same setup as OP, except I'm using 2.3.5 and testing on Android. Nothing is showing up on screen and there's nothing in the logs.

**Comment by daniel-luberda** [comment]
@nexussays I modified lib to throw an exception if `CachedImageRenderer.Init` is not called: https://github.com/luberda-molinet/FFImageLoading/commit/cc221ff94284b980c11e41be6ffe69117339f726
