### ISSUE TITLE
How to exclude images auto backup in Android?

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#984]
I am trying to exclude cached images to be excluded from android auto backup feature? according to the [documentation ](https://developer.android.com/guide/topics/data/autobackup.html)
we can define  `  <exclude domain="file"  path="string" />` but I am not sure what path this should be?  for database simply I used, `<exclude domain="database"  path="mydatabase.db" />`  becasuse database is installed on a specific location looks like. how about images? do you have any check or experience with that?

**Comment by daniel-luberda** [comment]
>> Auto Backup excludes files in directories returned by getCacheDir(), getCodeCacheDir(), or getNoBackupFilesDir(). The files saved in these locations are only needed temporarily, or are intentionally excluded from backup operations.

FFImageLoading uses cache folders by default (it is configurable though) - those folders aren't usually included into any backups.
