### ISSUE TITLE
Image not loading more than once per app session

### ISSUE THREAD

**Issue by Nixon-Joseph** [luberda-molinet/FFImageLoading#985]
### Description

Image not loading from SourceProperty Binding in ContentView - Works fine on Xamarin.Forms.Image. The `CachedImage` is amazing, and is way faster than the stock one, but I need to know it will load all images just as well as Xamarin's. 

I've set up the successCommand and it never gets hit, as well as retryCount > 500 with a retryDelay > 500, just goes strait to the ErrorPlaceholder. Like it's not even trying to pull from the url.

A particular image that's failing - https://media.wattswater.com/UPC/Image/098268238518.tif.jpg

I event set the source directly to the referenced url, instead of through a binding, and it still failed to load.

If I have an ErrorCommand set, it gets hit, and the args show a null reference exception with the following stack trace:

```
  at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].ProcessRemoval (TValue value, System.Boolean evicted) [0x00030] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:235 
  at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].Remove (System.String key, System.Boolean evicted) [0x0005f] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:383 
  at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].Add (System.String key, TValue value) [0x00078] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:349 
  at FFImageLoading.Cache.ImageCache`1[TValue].Add (System.String key, FFImageLoading.Work.ImageInformation imageInformation, TValue bitmap) [0x00059] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ImageCache.cs:171 
  at FFImageLoading.Work.ImageLoaderTask`3+<RunAsync>d__108[TDecoderContainer,TImageContainer,TImageView].MoveNext () [0x0056e] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:564 
```

On further testing, it looks like the image will load exactly once (anywhere on my app). I've got a 'recently viewed' section when I load up the app, and the image loads there fine. But it will not load any subsequent times during that application session.

If it's not in the recently viewed portion, then i'll see the image load successfully in the search results, but it'll then fail if I proceed to try to look at the item in the detail view. Then if I restart the app, it'll show properly in the recently viewed portion, but will no longer show up in search results, or in the item detail.

### Steps to Reproduce

.... coming if I have time to make a repro.

### Expected Behavior

Image loads

### Actual Behavior

Image fails to load

### Basic Information

- Version with issue: 2.3.4
- Last known good version: unknown
- Platform: Android only - IOS seems fine.

### Screenshots

![image](https://user-images.githubusercontent.com/10250222/37796801-23167558-2de6-11e8-8dec-9aae9bbd2484.png)

![image](https://user-images.githubusercontent.com/10250222/37797244-4ee8b2d0-2de7-11e8-9f3f-9836bfae6e64.png)

### Reproduction Link / Code

```
var carousel = new PanCardView.CarouselView()
            {
                ItemTemplate = new DataTemplate(() =>
                {
                    var img = new CachedImage() { VerticalOptions = LayoutOptions.FillAndExpand, HorizontalOptions = LayoutOptions.FillAndExpand, ErrorPlaceholder = "not_found.gif", RetryCount = 100, RetryDelay = 100 };
                    img.SetBinding(CachedImage.SourceProperty, "ImageUrl");
                    return new ContentView() { Content = img, HorizontalOptions = LayoutOptions.FillAndExpand, VerticalOptions = LayoutOptions.FillAndExpand };
                }),
                PanDelay = 0,
                IsAutoNavigating = false,
                IsCyclical = false
            };
```

**Comment by daniel-luberda** [comment]
Can you reproduce it with 2.3.5?

**Comment by Nixon-Joseph** [comment]
Yes, same behavior.

**Comment by daniel-luberda** [comment]
Are you sure? That bug was fixed, there's a null check there now. Please provide a new stack trace and check if you updated package in all projects.

**Comment by Nixon-Joseph** [comment]
Nope, you are correct. A full clean and rebuild did the trick. Thanks for the help!

And good work!
