### ISSUE TITLE
Where to catch exceptions with Xamarin Forms?

### ISSUE THREAD

**Issue by CNDOGTA** [luberda-molinet/FFImageLoading#990]
When I have an http not found exception on an image, where can I catch the exception?
I tried surrounding `Source = ...` with` try catch` but got nothing.

**Comment by daniel-luberda** [comment]
- FFImageLoading outputs all errors to console output by default. 
- If you want to use your own logging, just provide a custom logger implementation via custom config, example here: https://github.com/luberda-molinet/FFImageLoading/blob/master/samples/ImageLoading.Forms.Sample/iOS/AppDelegate.cs#L24
