### ISSUE TITLE
Re-Open Svg-s are rendered pixelated #522

### ISSUE THREAD

**Issue by MosCD** [luberda-molinet/FFImageLoading#991]
Re- Opening of the Issue

https://github.com/luberda-molinet/FFImageLoading/issues/522

SVGs are rendered pixelated, it's several months since the issue was supposed to be closed and resolved but it is still there

### Basic Information

- Version with issue: 
- Last known good version: 
- Platform:

**Comment by daniel-luberda** [comment]
Let's continue there.
