### ISSUE TITLE
FFImageLoading doesn't load url with redirect from facebook

### ISSUE THREAD

**Issue by aleksandrsmyk** [luberda-molinet/FFImageLoading#992]
URL: https://graph.facebook.com/10215352589839118/picture?type=normal
can not be loaded by the FFImageLoading up to redirection I guess.

**Comment by daniel-luberda** [comment]
Works fine for me. Please provide more info to reopen. It may be this (unrelated to ffimageloading): https://blog.xamarin.com/securing-web-requests-with-tls-1-2/

![simulator screen shot - iphone 8 - 2018-03-29 at 14 11 46](https://user-images.githubusercontent.com/13569983/38088169-27a9ab60-335b-11e8-8132-0b2f0e38bbc5.png)
