### ISSUE TITLE
BlurredTransformation creates strange striated effect

### ISSUE THREAD

**Issue by peppe130** [luberda-molinet/FFImageLoading#995]
Hi,

I'm using the latest version of this library on Android Nougat and I tried to blur an image. I don't know why, the blurred image has a strange striated effect:
<img width="447" alt="screen shot 2018-03-29 at 11 51 42" src="https://user-images.githubusercontent.com/6855692/38082727-e09d4744-3347-11e8-9772-8af16072bc97.png">

Is there a solution? Is it a bug? Thanks.

**Comment by daniel-luberda** [comment]
Fixed

**Comment by peppe130** [comment]
Ok, thanks. This solved my issue!
