### ISSUE TITLE
SVG package to support splat 3.0

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#997]
Do you see any issue to support splat 3.0? it solves a problem on UWP if running on .net standard
`The type 'Color' exists in both 'Splat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`
I hate updated myself splat 3.0 and tested, it looks fine for me.

**Comment by daniel-luberda** [comment]
Could you elaborate? FFImageLoading doesn't use `Splat` at all.

**Comment by EmilAlipiev** [comment]
Opps, i was confused with Skiasharp :) so many nuget updates at once yesterday late in the evening. I guess your latest version 2.3.6 updated to latest skiasharp 1.6.0 already :)
