### ISSUE TITLE
[help wanted] Do I have a possibility to see a LoadingPlaceholder until slow stream will be available?

### ISSUE THREAD

**Issue by JTOne123** [luberda-molinet/FFImageLoading#998]
### Description

My app works with images via stream source in some cases.

For example:
At the iOs, the image can be on iCloud and we should wait for until image will be downloaded.

At the UWP, at PC a user can use very high-resolution images and to resolve stream also need a time.

### Steps to Reproduce

Example: how to get

```
ImageSource.FromStream(() => {

//I expected to see LoadingPlaceholder at this moment

Task.Delay(5000).Result;
return file.GetFileStream();
);
```

### Expected Behavior

The same behavior like download by URL

### Actual Behavior

The LoadingPlaceholder fast blink before showing an image

----------

What do you think? This a bug? Or maybe I'm doing something wrong?

**Comment by daniel-luberda** [comment]
Fixed. For older versions, as a workaround you can disable `StreamChecksumsAsKeys` via custom config
